document.write('<!-- Google Tag Manager -->');
document.write("<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':");
document.write("new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],");
document.write("j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=");
document.write("'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);");
document.write("})(window,document,'script','dataLayer','GTM-TQJZWCV');</script>");
document.write('<!-- End Google Tag Manager -->');
document.write('<!-- Global site tag (gtag.js) - Google Analytics -->');
document.write('<script async src="https://www.googletagmanager.com/gtag/js?id=UA-42613638-11"></script>');
document.write('<script>');
document.write('  window.dataLayer = window.dataLayer || [];');
document.write('  function gtag(){dataLayer.push(arguments);}');
document.write("  gtag('js', new Date());");
document.write("  gtag('config', 'UA-42613638-11');");
document.write('</script>');
document.write('<link rel="stylesheet" href="/css/luminous-basic.min.css">');
document.write('<script src="/js/luminous.min.js"></script>');
document.write('<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">');
document.write('<title>Manuscript of Tsugio Sekiguchi</title>');