document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">分類番号</div><div class="col-8">分類題目</div><div class="col-2">総目次ページ</div></div>');
document.write('<div class="row"><div class="col-2">01-1B</div><div class="col-8"><a href="http://biblevi.minibird.jp/sekiguchi/001/s0001/">固有名詞でもあり普通名詞でもあり</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">01-2B</div><div class="col-8"><a href="http://biblevi.minibird.jp/sekiguchi/000/s0002/">固有名詞</a></div><div class="col-2">2-49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］固有地名は原則として中性</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］ニ格で=es</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］Unter den Lindenの格変化</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］=e</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］=sch</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］複数のs</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］複数の=en, =e</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］Dativで-n、-en（三格支配の前置なき時の一法）</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］Akkusativで=n、=en.</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］Meines Roderich</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］固有名詞と冠詞</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］ニ格で=ens</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］des grossen Fritzen</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］des heutigen Deutschland</div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］Apostroch（省字符）による二格</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］複数でdie～（=s無し）</div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］Der alte Fritz, Der gruene Heinrich等も前出と同じ</div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">01-3R</div><div class="col-8"> </div><div class="col-2">50-51</div></div>');
document.write('<div class="row"><div class="col-2">01-4B</div><div class="col-8">格変化</div><div class="col-2">52-108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］成句に限ってあうDativ, Fem, の=en</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］弱変化男性名詞</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］Name型</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］Des Papa型</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］Herz, Schmerz</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］gleiches Namens等</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］弱変化名詞の三四格以外（聯語） zu Mensch und Welt</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］単独のNennform（弱変化）（及びWille等）</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］Das Schwert des Demokles</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］表題の引用とその格（二通り）</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Zur Erden等</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］Theseus'+"' Stadt, Dollfuss'"+' Beisetzung</div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］弱変化男性の=enの例外的省略</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］Friede, Gedanke, Funke.</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］des Sturm und Dranges －－数語を一括して一個の名詞と見る。－－</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］Euer Gnaden (EW)の各格</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2">01-5</div><div class="col-8"> </div><div class="col-2">109-134</div></div>');
document.write('</div>');