<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">04-1B</div>
<div class="daimoku">三格支配の動詞</div>
<div class="mpage">1-23</div>
<div class="bango"> </div>
<div class="daimoku">［01］dienen, ähnlich sehen, folgen, gehorchen, ets</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">［03］zu=entgegen=, nach=を伴ふ動詞</div>
<div class="mpage">18</div>
<div class="bango"> </div>
<div class="daimoku">［03］熟語。物の主語と人の三格。特例Liebkosen等。<br />Ihm ward(Zuteil), 及び類似のもの。<br /><u>folgen</u> <u>auf</u>と<u>三格直結</u></div>
<div class="mpage">20<br /> <br /> </div>
<div class="bango">04-2B</div>
<div class="daimoku">数個の補足語を採る勁詞</div>
<div class="mpage">24-38</div>
<div class="bango"> </div>
<div class="daimoku">［01］3格と4格</div>
<div class="mpage">25</div>
<div class="bango">04-3R</div>
<div class="daimoku">初歩用。 梵 yacch与える</div>
<div class="mpage">39</div>
<div class="bango">04-4B</div>
<div class="daimoku"> </div>
<div class="mpage">40-42</div>
<div class="bango"> </div>
<div class="daimoku">［02］四格と奪格的三格</div>
<div class="mpage">40</div>
<div class="bango"> </div>
<div class="daimoku">［03］geben型動詞</div>
<div class="mpage">41</div>
<div class="bango"> </div>
<div class="daimoku">［04］二重四格、参考。</div>
<div class="mpage">42</div>
<div class="bango">04-5B</div>
<div class="daimoku">日本語とは格支配の閏係を異にするもの</div>
<div class="mpage">43-47</div>
<div class="bango"> </div>
<div class="daimoku">［01］<u>berühren</u>. <u>helfen</u>. <u>grüssen</u>. etc.</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">［02］に耐える、 及第する。</div>
<div class="mpage">45</div>
<div class="bango"> </div>
<div class="daimoku">［03〕</div>
<div class="mpage">46</div>
<div class="bango"> </div>
<div class="daimoku">［04］「英」 三、四格の区別が独ではあるが英では<br />単に目的語（即ちAKK）</div>
<div class="mpage">47<br /> </div>
<div class="bango"> </div>
<div class="daimoku">［05］前綴との関係</div>
<div class="mpage">47</div>
<div class="bango">04-6B</div>
<div class="daimoku">二格支配 形容詞</div>
<div class="mpage">48-118</div>
<div class="bango">04-7B</div>
<div class="daimoku">二格支配 動詞</div>
<div class="mpage">119-170</div>
<div class="bango">04-8B</div>
<div class="daimoku">三格支配 形容詞</div>
<div class="mpage">171-224</div>
<div class="bango">04-9B</div>
<div class="daimoku">二格支配 動詞（特に「独」の分冊）</div>
<div class="mpage">225-265</div>
<div class="bango">04-10B</div>
<div class="daimoku">四格支配の動詞</div>
<div class="mpage">266-275</div>
<div class="bango">04-11B</div>
<div class="daimoku">四格支配の熟語成句</div>
<div class="mpage">276-280</div>
<div class="bango">04-12B</div>
<div class="daimoku">in支配。</div>
<div class="mpage">281</div>
<div class="bango">04-13B</div>
<div class="daimoku">前置詞支配の形容詞</div>
<div class="mpage">282-284</div>
<div class="bango">04-14B</div>
<div class="daimoku">三格支配か四格支配の問題。 j.versichern.nützen</div>
<div class="mpage">285</div>
<div class="bango">04-15B</div>
<div class="daimoku">形容詞の前置詞句支配 auf.an.zu.</div>
<div class="mpage">286-287</div>
<div class="bango">04-16B</div>
<div class="daimoku">「態」一般　相・法・式・時・様の置き場所</div>
<div class="mpage">288</div>
<div class="bango">04-17B</div>
<div class="daimoku">支配異なれば意味異なる。 folgen dem<br />                              auf</div>
<div class="mpage">289<br /> </div>
<div class="bango">04-18B</div>
<div class="daimoku">一格支配の動詞</div>
<div class="mpage">290-302</div>
<div class="bango">04-19B</div>
<div class="daimoku">四格支配 形容詞</div>
<div class="mpage">303</div>
<div class="bango">04-20B</div>
<div class="daimoku">非人称動詞の二格支配</div>
<div class="mpage">304</div>
</div>