<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">03-1B</div>
<div class="daimoku">er, el, en n型（複数及び性）</div>
<div class="mpage">1-17</div>
<div class="bango">03-2B</div>
<div class="daimoku">性</div>
<div class="mpage">18-91</div>
<div class="bango"> </div>
<div class="daimoku">［01］複合名詞の性はその最後の字によって決める－－といふ規則についての注意</div>
<div class="mpage">20</div>
<div class="bango"> </div>
<div class="daimoku">［02］人格と見なすものは他品詞の名詞化でも男性</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">［03］自然の性と一致せざるもの。</div>
<div class="mpage">40</div>
<div class="bango"> </div>
<div class="daimoku">［04］自然の性と一致せざるものの受け方。（関係代名詞、物主代名詞）</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">［05］異性異意</div>
<div class="mpage">55</div>
<div class="bango"> </div>
<div class="daimoku">［06］Scheibare Inkongruenzen 指示代名詞、男女無差別の男性（der-等）</div>
<div class="mpage">56</div>
<div class="bango"> </div>
<div class="daimoku">［07］女を男性普通名で指すとき。（性・数両方）（主語に非ずして客語的位置にある時）</div>
<div class="mpage">57<br /> </div>
<div class="bango"> </div>
<div class="daimoku">［08］MutとWehmut</div>
<div class="mpage">80</div>
<div class="bango"> </div>
<div class="daimoku">［09］eines, keines, yedes（男女混れる時）”中性視”</div>
<div class="mpage">89</div>
<div class="bango">03-3B</div>
<div class="daimoku">地名の性 及び定冠詞の問題</div>
<div class="mpage">92-122</div>
<div class="bango">03-4R</div>
<div class="daimoku">複数形の随一の例外：Sporen =en が男性語Par. Excelanceなることの備考。女性固有名詞のpl.=en</div>
<div class="mpage">123-125<br /> </div>
<div class="bango">03-5R</div>
<div class="daimoku">Zeppelin=eその他 =e 一般</div>
<div class="mpage">126-146</div>
<div class="bango">03-6B</div>
<div class="daimoku">性数格を近い方に合わす。性数のKongruenz一般</div>
<div class="mpage">147-156</div>
<div class="bango">03-7B</div>
<div class="daimoku">性数の二つ以上あるもの性の誤をも含む!!!</div>
<div class="mpage">155-180</div>
<div class="bango">03-8B</div>
<div class="daimoku">Zirkus-se</div>
<div class="mpage">181</div>
<div class="bango">03-9B</div>
<div class="daimoku">Pluralia tantum等</div>
<div class="mpage">182-266</div>
<div class="bango">03-10B</div>
<div class="daimoku">der Flirt その他 酒・衣服、etc</div>
<div class="mpage">267-290</div>
<div class="bango">03-11B</div>
<div class="daimoku">女性語尾 = in</div>
<div class="mpage">291-304</div>
<div class="bango">03-12B</div>
<div class="daimoku">数</div>
<div class="mpage">305-448</div>
<div class="bango">03-13B</div>
<div class="daimoku">［01］=heiten, =Kkeitenが「性質」でなく「性質を帯びたもの」即ち言語又は動作又は物体等を指す傾向</div>
<div class="mpage">310<br /> </div>
<div class="bango"> </div>
<div class="daimoku">［02］Pluralia tantum</div>
<div class="mpage">318</div>
<div class="bango"> </div>
<div class="daimoku">［03］複数が別意を持つもの</div>
<div class="mpage">326</div>
<div class="bango"> </div>
<div class="daimoku">［04］好んで複数を用いるもの。</div>
<div class="mpage">328</div>
<div class="bango"> </div>
<div class="daimoku">［05］=ma:pl=men, =a-・=en</div>
<div class="mpage">328</div>
<div class="bango"> </div>
<div class="daimoku">［06］generelier Singular.（中性の場合も然り）</div>
<div class="mpage">329</div>
<div class="bango"> </div>
<div class="daimoku">［07］Kollektiva</div>
<div class="mpage">344</div>
<div class="bango"> </div>
<div class="daimoku">［08］共有の単数（複数を用ひる代り）</div>
<div class="mpage">366</div>
<div class="bango"> </div>
<div class="daimoku">［09］Singularia tantum</div>
<div class="mpage">371</div>
<div class="bango"> </div>
<div class="daimoku">［10］物質的取扱のSingularia tantum</div>
<div class="mpage">379</div>
<div class="bango"> </div>
<div class="daimoku">［11］Schein Plural</div>
<div class="mpage">379</div>
<div class="bango"> </div>
<div class="daimoku">［12］共通の単数のKopulaが複数の例。</div>
<div class="mpage">381</div>
<div class="bango"> </div>
<div class="daimoku">［13］単位扱いのplは単数形</div>
<div class="mpage">388</div>
<div class="bango"> </div>
<div class="daimoku">［14］Dinger.等</div>
<div class="mpage">388</div>
<div class="bango"> </div>
<div class="daimoku">［15］Die Jas =s</div>
<div class="mpage">388</div>
<div class="bango"> </div>
<div class="daimoku">［16］das Auge, Ohr Hand, 等（Augen, Ohren, Haendenの代わり）</div>
<div class="mpage">389</div>
<div class="bango"> </div>
<div class="daimoku">［17］純共有の単数（distributiv, 各々）</div>
<div class="mpage">398</div>
<div class="bango"> </div>
<div class="daimoku">［18］主語がplで客語が 's. （及びその反対）</div>
<div class="mpage">410</div>
<div class="bango"> </div>
<div class="daimoku">［19］尊称的単数名詞にはplの定型を用ふ</div>
<div class="mpage">420</div>
<div class="bango"> </div>
<div class="daimoku">［20］複数名詞が「習憤的」事実の暗示に用いられる際</div>
<div class="mpage">422</div>
<div class="bango"> </div>
<div class="daimoku">［21］聯語には単数を用ふ。</div>
<div class="mpage">424</div>
<div class="bango"> </div>
<div class="daimoku">［22］Die Feuer etc.（意味がnomen materieより転化せり）</div>
<div class="mpage">425</div>
<div class="bango"> </div>
<div class="daimoku">［23］die Salze, die Fette, die zZucker等</div>
<div class="mpage">435</div>
<div class="bango"> </div>
<div class="daimoku">［24］聯語と定型。（pl. の際）</div>
<div class="mpage">436</div>
<div class="bango"> </div>
<div class="daimoku">［25］倒置定形の単数形と二個以上の単数主語。</div>
<div class="mpage">437</div>
<div class="bango"> </div>
<div class="daimoku">［26］数的主語はpl.</div>
<div class="mpage">438</div>
<div class="bango">03-13R</div>
<div class="daimoku">男性、人名より普通名へ Die Schumanns- 家族夫妻、=sかGenetiv=sなること 古代には複数が貧弱で単と同形か多かったということ。複数形におけるアクセン卜の移動。. aus Wohlklangsrurcksichten. 概念としては明らかにpl.なるものを単として扱ふ独の癖（古典語と比べて） Alle Mann hielten<br />編者注 : ほかに25件あり</div>
<div class="mpage">449-476<br /> <br /> <br /> <br /> </div>
<div class="bango">03-14B</div>
<div class="daimoku">der Sofa der Pult等</div>
<div class="mpage">477-480</div>
<div class="bango">03-15B</div>
<div class="daimoku">抽象名詞のpl.種々の場合を想起せしめる効果あり</div>
<div class="mpage">481</div>
<div class="bango">03-16B</div>
<div class="daimoku">Dualis</div>
<div class="mpage">482-484</div>
<div class="bango">03-17B</div>
<div class="daimoku">複雑な内容を含むと推察される抽象概念には好んでPLを用いる</div>
<div class="mpage">485-487</div>
<div class="bango">03-18B</div>
<div class="daimoku">Zeugs Dings Krams</div>
<div class="mpage">488-489</div>
<div class="bango">03-19B</div>
<div class="daimoku">「仏」物の集約名詞</div>
<div class="mpage">490</div>
<div class="bango">03-20B</div>
<div class="daimoku">代名詞の中性化傾向</div>
<div class="mpage">491-495</div>
<div class="bango">03-21R</div>
<div class="daimoku">人問の中性扱い</div>
<div class="mpage">496-501</div>
<div class="bango">03-22R</div>
<div class="daimoku">英語でも、例えば蜜蜂（bee）などは女性扱いにする！ Tausennd und eine Nacht 英は拉式複数形多し。 商品名の性Die Leica等。 勤物名中性。<br />編者注：ほかに40件あり</div>
<div class="mpage">502-540<br /> <br /> </div>
<div class="bango">03-23B</div>
<div class="daimoku">Die Dpktos, Die Kerls等 =s 語尾のpl.</div>
<div class="mpage">541-551</div>
<div class="bango">03-24B</div>
<div class="daimoku">複数形、Die Warumsか？ Die Warumか？</div>
<div class="mpage">552-558</div>
<div class="bango">03-25R</div>
<div class="daimoku">Die Theorie von den zwei China. 固有名詞の無語尾複数</div>
<div class="mpage">559-560<br /> </div>
<div class="bango">03-26B</div>
<div class="daimoku">Dinge</div>
<div class="mpage">561-582</div>
<div class="bango">03-27B</div>
<div class="daimoku">外来語の複数語尾としての =s</div>
<div class="mpage">583-589</div>
<div class="bango">03-28B</div>
<div class="daimoku">「仏」 仏独「性」の相違</div>
<div class="mpage">590-593</div>
<div class="bango">03-29R</div>
<div class="daimoku">Kongruenzfrageの一覧。失後、Zwei mann=Tank等。音響名（Schallwort）"Knacks"の男性</div>
<div class="mpage">594-603<br /> </div>
<div class="bango">03-30B</div>
<div class="daimoku">「船名・その他一括</div>
<div class="mpage">604-621</div>
<div class="bango">03-31B</div>
<div class="daimoku">=ien, =en複数語尾　外来語</div>
<div class="mpage">622-635</div>
<div class="bango">03-32B</div>
<div class="daimoku">Das Blau 色彩その他</div>
<div class="mpage">636-640</div>
<div class="bango">03-33B</div>
<div class="daimoku">Muskeln型</div>
<div class="mpage">641-645</div>
</div>