<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">10-1B</div>
<div class="daimoku">不定冠詞 雑項</div>
<div class="mpage">1-63</div>
<div class="bango">10-2B</div>
<div class="daimoku">任意的、否定的</div>
<div class="mpage">64-79</div>
<div class="bango">10-3B</div>
<div class="daimoku">MHD, AHD, GOTその他に不定冠詞はあるか</div>
<div class="mpage">80-82</div>
<div class="bango">10-4B</div>
<div class="daimoku">定冠詞代りの不定冠詞</div>
<div class="mpage">83-100</div>
<div class="bango">10-5B</div>
<div class="daimoku">冠詞用法の初歩的な典型</div>
<div class="mpage">101-105</div>
<div class="bango">10-6B</div>
<div class="daimoku">1. ein 30 Männer. 2. ein Tager acht. 3. 英 a hundred</div>
<div class="mpage">106-115</div>
<div class="bango">10-7B</div>
<div class="daimoku">ein＋固有名詞及び"gewiss"一般</div>
<div class="mpage">116-121</div>
<div class="bango">10-8B</div>
<div class="daimoku">関係文規定</div>
<div class="mpage">122-124</div>
<div class="bango">10-9R</div>
<div class="daimoku">ein Davinci 作品と不定冠詞</div>
<div class="mpage">125-136</div>
<div class="bango">10-10B</div>
<div class="daimoku">性質の強調、主として無冠詞との関係</div>
<div class="mpage">137-159</div>
<div class="bango">10-11B</div>
<div class="daimoku">具体的、紹介導入</div>
<div class="mpage">160-204</div>
<div class="bango">10-12B</div>
<div class="daimoku">定冠詞または無冠詞の筈のところに性質の含みの不定<br />冠詞（規定ある場合）</div>
<div class="mpage">205-206</div>
<div class="bango">10-13B</div>
<div class="daimoku">性質＝不定冠詞整理ノー卜</div>
<div class="mpage">207-209</div>
<div class="bango">10-14B</div>
<div class="daimoku">多中の一を意味する場合（第二章）</div>
<div class="mpage">210-214</div>
<div class="bango">10-15R</div>
<div class="daimoku"> </div>
<div class="mpage">215-216</div>
<div class="bango">10-16B</div>
<div class="daimoku">数詞 einと不定冠詞ejn 第一章</div>
<div class="mpage">217-223</div>
<div class="bango">10-17B</div>
<div class="daimoku">不定冠詞 述語</div>
<div class="mpage">224-233</div>
<div class="bango">10-18B</div>
<div class="daimoku">普遍妥当命題</div>
<div class="mpage">234-243</div>
<div class="bango">10-19R</div>
<div class="daimoku">Es ist ein E1end!</div>
<div class="mpage">1244-245</div>
<div class="bango">10-21B</div>
<div class="daimoku">性質強調と関係、未定の仮構事象 etwaige型<br />可能～、仮構～、架空～、未然、企画的～</div>
<div class="mpage">250-360</div>
</div>