<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">09-1B</div>
<div class="daimoku">附置規定（殊に掲称的附置規定）命名の附置規定</div>
<div class="mpage">1-24</div>
<div class="bango">09-1B</div>
<div class="daimoku">[01]普通名詞。固有名詞。</div>
<div class="mpage">4</div>
<div class="bango">09-1B</div>
<div class="daimoku">[02]Adresse, Wohnort.</div>
<div class="mpage">11</div>
<div class="bango">09-1B</div>
<div class="daimoku">[03]序数、年代等の規定。</div>
<div class="mpage">11</div>
<div class="bango">09-1B</div>
<div class="daimoku">[04]「格」は揃えること普通名詞</div>
<div class="mpage">12</div>
<div class="bango">09-1B</div>
<div class="daimoku">[05]格を揃えぬ場合（無格的一格を付す）</div>
<div class="mpage">13</div>
<div class="bango">09-1B</div>
<div class="daimoku">[06]Psuedo=Apposition. <u>Eine Art</u>～</div>
<div class="mpage">14</div>
<div class="bango">09-1B</div>
<div class="daimoku">[07]文章のApposition.</div>
<div class="mpage">19</div>
<div class="bango">09-1B</div>
<div class="daimoku">[08]「即ち」と説明して同「格」になるもの。</div>
<div class="mpage">16</div>
<div class="bango">09-1B</div>
<div class="daimoku">[09]形容詞のApposition.</div>
<div class="mpage">19</div>
<div class="bango">09-1B</div>
<div class="daimoku">[10]Genitivus appositivus相当するもの。</div>
<div class="mpage">20</div>
<div class="bango">09-1B</div>
<div class="daimoku">[11]格の如何に拘らず、1格のAppositionを付した例</div>
<div class="mpage">22</div>
<div class="bango">09-1B</div>
<div class="daimoku">[12]<u>Sanders' Sprachbriefe</u></div>
<div class="mpage">23</div>
<div class="bango">09-1B</div>
<div class="daimoku">[13]「何々としての位置」等。</div>
<div class="mpage">23</div>
<div class="bango">09-2B</div>
<div class="daimoku">König Arthus 凍結形として等。</div>
<div class="mpage">23</div>
<div class="bango">09-3B</div>
<div class="daimoku">命令の附置規定</div>
<div class="mpage">25-29</div>
<div class="bango">09-4B</div>
<div class="daimoku">格一致せざる挙格的同格。Der Dichter Goethe.<br />Die Stadt Berlin.</div>
<div class="mpage">43-47</div>
<div class="bango">09-5B</div>
<div class="daimoku">Herr Hauptmann Frau Hauptmann</div>
<div class="mpage">48-50</div>
<div class="bango">09-6B</div>
<div class="daimoku">Philipp der Zweite型</div>
<div class="mpage">51-54</div>
<div class="bango">09-7R</div>
<div class="daimoku">〔失！〕Regierung Papen型。〔仏〕Le mot <u>de</u><br />Science Apposition（格を揃へずして<u>Nominativ</u>を<br />用いるものあり、省略文と心得るべし）<br />編者注：このほか22件あり。</div>
<div class="mpage">55-77</div>
</div>