<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">07-1B</div>
<div class="daimoku">名詞 Dativ</div>
<div class="mpage">1-187</div>
<div class="bango"> </div>
<div class="daimoku">[01]<u>Ablativ</u>(AB.=その他） ab= のみ（他にan=）</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">[02]物主代名詞＝格名詞｝代り。（物主に属する付属<br />物の名詞を伴い、定冠詞。）</div>
<div class="mpage">4</div>
<div class="bango"> </div>
<div class="daimoku">[03]「・・・・に取って」 （für）（その人〔たち〕<br />から見れぱ）</div>
<div class="mpage">29</div>
<div class="bango"> </div>
<div class="daimoku">[04]Dativ des Interesses. 利害。真に利害関係ある時〉</div>
<div class="mpage">43</div>
<div class="bango"> </div>
<div class="daimoku">[05]〔例外〕 = auf, an, bei <u>Akkusativ</u></div>
<div class="mpage">50</div>
<div class="bango"> </div>
<div class="daimoku">[06]離格。 -ent=</div>
<div class="mpage">56</div>
<div class="bango"> </div>
<div class="daimoku">[07]固有名詞の三格は特に注意を要す</div>
<div class="mpage">70</div>
<div class="bango"> </div>
<div class="daimoku">[08]Dem ist so. Dem sei wie ihm wolle.</div>
<div class="mpage">74</div>
<div class="bango"> </div>
<div class="daimoku">[09]拉典のDoppelter Dativに相当するもの。（zu）</div>
<div class="mpage">86</div>
<div class="bango"> </div>
<div class="daimoku">[10]Ethischer Dativ（Manのeinemと同じ）</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">[11]falsche "Appdsition" für Präpositionale Aduerbiale（墺式）</div>
<div class="mpage">119</div>
<div class="bango"> </div>
<div class="daimoku">[12]einem läuten等。（通信の三格）<u>An</u>rede</div>
<div class="mpage">126</div>
<div class="bango"> </div>
<div class="daimoku">[13]離格支配 (nehmen, rauben, stehlen等）</div>
<div class="mpage">129</div>
<div class="bango"> </div>
<div class="daimoku">[14]Ethischer Datjv参考。（mir: für mich）</div>
<div class="mpage">1433</div>
<div class="bango"> </div>
<div class="daimoku">[15]lebenと三格。（「捧げる」意の三格）</div>
<div class="mpage">144</div>
<div class="bango"> </div>
<div class="daimoku">[16]最も普通なるzugunsten, zuungunstenの三格。</div>
<div class="mpage">147</div>
<div class="bango"> </div>
<div class="daimoku">[17]Wohl dem ....! Wehe dem! Dank dem!</div>
<div class="mpage">148</div>
<div class="bango"> </div>
<div class="daimoku">[18]der Hoffnung <u>leben</u>.</div>
<div class="mpage">169</div>
<div class="bango"> </div>
<div class="daimoku">[19]<u>Dem</u> Vater seine....</div>
<div class="mpage">173</div>
<div class="bango"> </div>
<div class="daimoku">[20]DaS <u>der Horcherin</u>!</div>
<div class="mpage">180</div>
<div class="bango"> </div>
<div class="daimoku">[21]羅・Dative of purpose</div>
<div class="mpage">181</div>
<div class="bango"> </div>
<div class="daimoku">[22]或人にとって [in seiner Meinung]</div>
<div class="mpage">182</div>
<div class="bango"> </div>
<div class="daimoku">[23]拉丁語・希語の主語的三格 梵<u>具格</u></div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">[24]<u>geben</u>形態。（基本的）</div>
<div class="mpage">186</div>
<div class="bango"> </div>
<div class="daimoku">[25]三格と前綴。</div>
<div class="mpage">187</div>
<div class="bango">07-2B</div>
<div class="daimoku">三格直結と前置詞を介するのとの相違。</div>
<div class="mpage">188-189</div>
<div class="bango">07-3R</div>
<div class="daimoku">或る対象に対するVerhaltenの三格。自由な三格の<br />用法。相当自由な三格の用法。委ねる任せる。<br />対処・善処の対象としてのDativは大範疇。<br />Berliner, Platt. 三格を要求する前綴（vorher=）</div>
<div class="mpage">190-205</div>
</div>