<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">16-1B</div>
<div class="daimoku">比較、形容詞、比較級</div>
<div class="mpage">1-187</div>
<div class="bango"> </div>
<div class="daimoku">［01］普通の用法。（述語的）（附加語的）</div>
<div class="mpage">7</div>
<div class="bango"> </div>
<div class="daimoku">［02］alsを省いて突然比較級を使ふ際。</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">［03］Nichts....ais, kein....als等。（程…なもの<br />はない。</div>
<div class="mpage">30</div>
<div class="bango"> </div>
<div class="daimoku">［04］[eben] so gut wie, so viel wie.（als）…も同然</div>
<div class="mpage">39</div>
<div class="bango"> </div>
<div class="daimoku">［05］（eben）so gut（wohl）.....wie（als）<br />（so wohl...als auch）</div>
<div class="mpage">47</div>
<div class="bango"> </div>
<div class="daimoku">［06］<u>mehr aLs</u>.（前置接続詞的） weniger als</div>
<div class="mpage">48</div>
<div class="bango"> </div>
<div class="daimoku">［07］so....wie, ebenso....wie（als）</div>
<div class="mpage">52</div>
<div class="bango"> </div>
<div class="daimoku">［08］um so....., desto <u>als</u>なしにもちひる場合<br /><u>je</u>と対照せずして</div>
<div class="mpage">60</div>
<div class="bango"> </div>
<div class="daimoku">［09］比較級を規定する副詞 immer（ますます）</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">［10］比較級の重複。（ますます）<br />1. tiefer und tiefer. 2. tief und tiefer.</div>
<div class="mpage">73</div>
<div class="bango"> </div>
<div class="daimoku">［11］程度のみの比較（相違せる二概念の）</div>
<div class="mpage">84</div>
<div class="bango"> </div>
<div class="daimoku">［12］weniger....als....（vielmehr）</div>
<div class="mpage">88</div>
<div class="bango"> </div>
<div class="daimoku">［13］<u>noch</u></div>
<div class="mpage">91</div>
<div class="bango"> </div>
<div class="daimoku">［14］<u>gein', lieber, liebsten</u> eher, am ehesten.</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">［15］普通の用法（附加的）als, als wieとwie, denn<br />との用法。</div>
<div class="mpage">105</div>
<div class="bango"> </div>
<div class="daimoku">［16］「難」（否定句が入ることあり）<br />alsの次に来る文に注意。</div>
<div class="mpage">111</div>
<div class="bango"> </div>
<div class="daimoku">［17］「難」<u>wie</u>（nur）と同形容詞の反復<br />wie以下の方に形容詞をおく。<br />mehr..X als..Y［<u>むしろ</u>］</div>
<div class="mpage">115</div>
<div class="bango"> </div>
<div class="daimoku">［18］比較級の代りにmehrを用ひた方がよい時。</div>
<div class="mpage">130</div>
<div class="bango"> </div>
<div class="daimoku">［19］<u>mehr oder weniger</u></div>
<div class="mpage">131</div>
<div class="bango"> </div>
<div class="daimoku">［20］bei weitem, weit, viel, lange nicht 等</div>
<div class="mpage">132</div>
<div class="bango"> </div>
<div class="daimoku">［21］<u>絶対比較級</u> <u>näher</u> bezeichnen früher schon.</div>
<div class="mpage">139</div>
<div class="bango"> </div>
<div class="daimoku">［22］比較級とals....je(irgend)etc.</div>
<div class="mpage">152</div>
<div class="bango"> </div>
<div class="daimoku">［23］差を示すにはum---又は単に四格。（量的なもの<br />に限る。）</div>
<div class="mpage">153</div>
<div class="bango"> </div>
<div class="daimoku">［24］<u>Mehr</u>の持つ価値的意義（wenigerも）</div>
<div class="mpage">154</div>
<div class="bango"> </div>
<div class="daimoku">［25］二個の動詞定形を比ベる<u>wie</u></div>
<div class="mpage">162</div>
<div class="bango"> </div>
<div class="daimoku">［26］<u>als</u>の次の代名詞省略</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">［27］...wie nie(je) einer war…等。</div>
<div class="mpage">166</div>
<div class="bango"> </div>
<div class="daimoku">［28］alsの次の指示代名詞省略（〃接続詞〃にも）</div>
<div class="mpage">169</div>
<div class="bango"> </div>
<div class="daimoku">［29］Doppelt so....noch eimal so....<br />比較級を用ひず</div>
<div class="mpage">178</div>
<div class="bango"> </div>
<div class="daimoku">［30］<u>ebensowenig</u> 二個所の否定（sowenig wie.）</div>
<div class="mpage">180</div>
<div class="bango"> </div>
<div class="daimoku">［31］wieと人代名詞の関係文中の比較級。</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">［32］alsの次の格の問題</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">［33］je（desto, immer）---, je um so.</div>
<div class="mpage">185</div>
<div class="bango"> </div>
<div class="daimoku">［34］zu（餘りに）, allzu,, viel zu, vier zu viel<br />等。 <u>genug</u></div>
<div class="mpage">186</div>
<div class="bango"> </div>
<div class="daimoku">［35］nicht weniger....als</div>
<div class="mpage">187</div>
<div class="bango">16-2B</div>
<div class="daimoku">schwerstzubehandelnde....及び<br />der bestmögliche Ausdruck..</div>
<div class="mpage">188-193</div>
<div class="bango">16-3B</div>
<div class="daimoku">どれも互いに劣らぬ、の意に比較級を。</div>
<div class="mpage">194-195</div>
<div class="bango">16-4B</div>
<div class="daimoku">autant vautこの比較級がmieux vaut<br />könnte ebenso gut. pourrait tout aussi bien</div>
<div class="mpage">196-202</div>
<div class="bango">16-5B</div>
<div class="daimoku">最高級</div>
<div class="mpage">203-315</div>
<div class="bango"> </div>
<div class="daimoku">［01］述語的用法。（他と較ベる際）</div>
<div class="mpage">205</div>
<div class="bango"> </div>
<div class="daimoku">［02］述語的用法。（自己と較ベる際）</div>
<div class="mpage">211</div>
<div class="bango"> </div>
<div class="daimoku">［03］附加語的用法。</div>
<div class="mpage">221</div>
<div class="bango"> </div>
<div class="daimoku">［04］認容的意味をもつ傾向（auch）<br />auchなきこともあり。</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">［05］定冠詞なく用ひる際（非常に、）</div>
<div class="mpage">230</div>
<div class="bango"> </div>
<div class="daimoku">［06］der....-steとam....stenとの区別に関する普通<br />の規則が必ずしも絶対的ならざる証明。<br />他と較べる際でも<u>am</u>=stenがよき場合あり。</div>
<div class="mpage">231</div>
<div class="bango"> </div>
<div class="daimoku">［07］関係代名詞を伴う最高級。<br />（…した中の一番…）wasの先行詞を<br />伴うなり。</div>
<div class="mpage">234</div>
<div class="bango"> </div>
<div class="daimoku">［08］"bei weitem"等。"weitaus"</div>
<div class="mpage">235</div>
<div class="bango"> </div>
<div class="daimoku">［09］最高級のPeriphrase（wie…nichts in der Welt等（否定を伴う場合）</div>
<div class="mpage">239</div>
<div class="bango"> </div>
<div class="daimoku">［10］von, unterの用法。</div>
<div class="mpage">243</div>
<div class="bango"> </div>
<div class="daimoku">［11］=st副詞の結成形=（aufs--ste）</div>
<div class="mpage">247</div>
<div class="bango"> </div>
<div class="daimoku">［12］---von der Welt.等（最高級の強調）</div>
<div class="mpage">252</div>
<div class="bango"> </div>
<div class="daimoku">［13］je等を伴ふ規定。（不定詞）</div>
<div class="mpage">255</div>
<div class="bango"> </div>
<div class="daimoku">［14］－stens.（aufs-steの代り）</div>
<div class="mpage">268</div>
<div class="bango"> </div>
<div class="daimoku">［15］－stensの「最大限度」指示。</div>
<div class="mpage">270</div>
<div class="bango"> </div>
<div class="daimoku">［16］aufs--ste.とzum～sten.</div>
<div class="mpage">287</div>
<div class="bango"> </div>
<div class="daimoku">［17］Gründlichst = aufs gründlichste</div>
<div class="mpage">295</div>
<div class="bango"> </div>
<div class="daimoku">［18］<u>Das Mindeste, was</u>...（又は<u>des</u>）<br />［nichits, Geringeres, ais....］</div>
<div class="mpage">301</div>
<div class="bango"> </div>
<div class="daimoku">［19］aller=schönst</div>
<div class="mpage">302</div>
<div class="bango"> </div>
<div class="daimoku">［20］<u>erst best</u>.</div>
<div class="mpage">305</div>
<div class="bango"> </div>
<div class="daimoku">［21］auf--steを=ensの代りに。</div>
<div class="mpage">312</div>
<div class="bango">16-6B</div>
<div class="daimoku">［羅］satius est ［梵］varam, ［etc］</div>
<div class="mpage">313-315</div>
<div class="bango">16-7B</div>
<div class="daimoku">比較級の<u>変音</u>の問題 zarterかzärterか</div>
<div class="mpage">316-319</div>
<div class="bango">16-8B</div>
<div class="daimoku">nur eben gerade....genug<br />辛うじて、緩やかに....やっと</div>
<div class="mpage">320-323</div>
<div class="bango">16-9B</div>
<div class="daimoku">比較のals（参考事項）</div>
<div class="mpage">324</div>
<div class="bango">16-10B</div>
<div class="daimoku"><u>出来るだけ</u>325-340</div>
<div class="mpage"> </div>
<div class="bango">16-11B</div>
<div class="daimoku"><u>およそ....なりとせぱ之れならめ<br />最高級表現の一形式</u></div>
<div class="mpage">341-344</div>
<div class="bango">16-12R</div>
<div class="daimoku">二者を比較して最高級を用ふ</div>
<div class="mpage">345-348</div>
<div class="bango">16-13B</div>
<div class="daimoku">構文の問題 eine nöheren Druck als 760mm</div>
<div class="mpage">349-352</div>
<div class="bango">16-14B</div>
<div class="daimoku">Zweitbest</div>
<div class="mpage">353-364</div>
<div class="bango">16-15B</div>
<div class="daimoku">öfter=絶対比較級（形）<br />öfterer= 比較級（副）365-367</div>
<div class="mpage"> </div>
<div class="bango">16-16R</div>
<div class="daimoku">形式化した比較級 inner=等<br />nicht<u>eher</u>....als 云々するより前には云々しない<br />was....als...? was....wenn nicht....? 移轍<br />最高級の飾り、（関係代名詞）</div>
<div class="mpage">368-372</div>
<div class="bango">16-17B</div>
<div class="daimoku">「むしろ」<u>cher</u> <u>lieber</u></div>
<div class="mpage">373-379</div>
<div class="bango">16-18R</div>
<div class="daimoku">frei-e-st! sovie1....wie（als）....dass<br />....［um］....zu不定法 <u>程度の制限</u> 及び<br /><u>同数の表現</u></div>
<div class="mpage">380-390</div>
<div class="bango">16-19R</div>
<div class="daimoku">genug....（と名詞）<br />比較の<u>als</u>, <u>wie</u>と倍数半数その他お数詞<br />絶対最高級の冠置用法<br /><u>絶対最高級</u> ラテン式 附加語に用いるのが特有<br />only, first, last等か最高級の一種なること<br />絶対最高級の附加語用法は独ではあまり用いないが、<br />羅典系語では存在する。</div>
<div class="mpage">391-393</div>
<div class="bango">16-20B</div>
<div class="daimoku">denkbar～st menschenmöglich 等</div>
<div class="mpage">394-396</div>
<div class="bango">16-21B</div>
<div class="daimoku">mehr, mehrer, mehrest等の現象</div>
<div class="mpage">397-399</div>
<div class="bango">16-22B</div>
<div class="daimoku">nicht mehr u. nicht weniger<br />以上にも非ず以下にも非ず。</div>
<div class="mpage">400-402</div>
<div class="bango">16-23B</div>
<div class="daimoku">denn（=a1s）［MHD］dan</div>
<div class="mpage">403</div>
<div class="bango">16-24B</div>
<div class="daimoku"><u>Gern</u>, lieber, liebst</div>
<div class="mpage">404-406</div>
<div class="bango">16-25B</div>
<div class="daimoku">Der Wunder höchstes</div>
<div class="mpage">407-412</div>
<div class="bango">16-26B</div>
<div class="daimoku">Alsの次の構文 及びstattも、</div>
<div class="mpage">413-422</div>
<div class="bango">16-27R</div>
<div class="daimoku">zuとall zu［餘りにも］nimis<br />［英］<u>any</u> bette等 no good.<br />［英］as many as high as late as</div>
<div class="mpage">423-425</div>
<div class="bango">16-28B</div>
<div class="daimoku">comme autant de</div>
<div class="mpage">426-431</div>
<div class="bango">16-29R</div>
<div class="daimoku">mehr oder weniger［more or less］</div>
<div class="mpage">432-433</div>
<div class="bango">16-30B</div>
<div class="daimoku">so gut er eben kann.（曲かったなりにも）</div>
<div class="mpage">434-436</div>
<div class="bango">16-31R</div>
<div class="daimoku">［英］more often <u>than not</u>.<br />「…と同じ」のとの二つお表現法:<br />（A）関係代名詞<br />（B）als, wie<br />［英］in=<u>most</u><br />［英］The lowest of the low等<br />［英］比較級の=erとmore～<br />最高級の=estとmpst～<br />=譬喩援用＝　認容的KⅡ約束話法と比較級<br />（又はso.等）<br />編者注：このほか5件あり。</div>
<div class="mpage">437-447</div>
<div class="bango">16-32B</div>
<div class="daimoku">比較文のそもそも <u>ais</u> 及ひ GENITIVとvon</div>
<div class="mpage">448-450</div>
<div class="bango">16-33B</div>
<div class="daimoku">…の一つや二つ多かろうと少なかろうと…<br />1.à ～ près<br />2.es kommt an～</div>
<div class="mpage">451-452</div>
<div class="bango">16-34R</div>
<div class="daimoku">［希］比較文参考 <u>That</u> LONG<br />「…と同じ」の構文<br />原級（positiv）なき比較級・最高級の形<br />［羅］quamを省いて<br />Non amplius mille passuum abest.<br />「云々ほど好いものは無い」の表現<br />［英］ best suited<br />［仏］meilleur, pire, pis<br />［英］The best <u>runner</u><br />編者注：このほか28件あり。</div>
<div class="mpage">453-472</div>
<div class="bango">16-35B</div>
<div class="daimoku">形式の問題（最高級）eをはさまぬ <u>bedeutendst</u></div>
<div class="mpage">473</div>
<div class="bango">16-36R</div>
<div class="daimoku">Allerbestとin <u>aller</u> Frühe等<br />編者注：このほか10件あり。</div>
<div class="mpage">474-477</div>
</div>