<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">18-1B</div>
<div class="daimoku">人代名詞</div>
<div class="mpage">1-49</div>
<div class="bango"> </div>
<div class="daimoku">［01］Ihre Majestät（Substrat des Peisonalpronoms）</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">［02］Periphrase als:Substratum des Pers.-prono.</div>
<div class="mpage">6</div>
<div class="bango"> </div>
<div class="daimoku">［03］人代名詞の二格。（真の二格的使用法）</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">［04］人代名詞の格 unsr aller 等<br />selbst</div>
<div class="mpage">27</div>
<div class="bango"> </div>
<div class="daimoku">［05］sieをmanの代りに用ふ。</div>
<div class="mpage">32</div>
<div class="bango"> </div>
<div class="daimoku">［06］Habt's vier verdienst heute？のs.</div>
<div class="mpage">39</div>
<div class="bango"> </div>
<div class="daimoku">［07］Ethischer Dat1vと同じDu.（Manの代り）</div>
<div class="mpage">40</div>
<div class="bango"> </div>
<div class="daimoku">［08］Hochdieselben等。</div>
<div class="mpage">43</div>
<div class="bango"> </div>
<div class="daimoku">［09］Du im Monolog.</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">［10］Seinesgleichen.</div>
<div class="mpage">49</div>
<div class="bango">18-2B</div>
<div class="daimoku">人代名詞、不定代名詞（es）</div>
<div class="mpage">50-193</div>
<div class="bango"> </div>
<div class="daimoku">［01］__句中の四格のes</div>
<div class="mpage">52</div>
<div class="bango"> </div>
<div class="daimoku">［02］次のdassを受ける一格es, 四格のes.</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">［03］esを省く傾向。（定形転置、後置の際）</div>
<div class="mpage">105</div>
<div class="bango"> </div>
<div class="daimoku">［04］damit davon等の代りに用ひられる傾向</div>
<div class="mpage">107</div>
<div class="bango"> </div>
<div class="daimoku">［05］紹介のes.（前に男性等があればなほハッキリする。</div>
<div class="mpage">109</div>
<div class="bango"> </div>
<div class="daimoku">［06］文の非人称。（文法上の王語）</div>
<div class="mpage">138</div>
<div class="bango"> </div>
<div class="daimoku">［07］C'est....que....（関係代名詞）（述語）</div>
<div class="mpage">139</div>
<div class="bango"> </div>
<div class="daimoku">［08］述語のes（形容詞、名詞を述語として受ける）</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">［09］<u>Nexus</u>の総体の意を受けるes.</div>
<div class="mpage">179</div>
<div class="bango"> </div>
<div class="daimoku">［10］es...<u>wenn</u>.</div>
<div class="mpage">182</div>
<div class="bango"> </div>
<div class="daimoku">［11］形容詞その他を受けるesの省略。<br />［als, wieの後て］</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">［12］成句中の四格の<u>das</u>.（俗調）</div>
<div class="mpage">185</div>
<div class="bango"> </div>
<div class="daimoku">［13］三格<u>dem</u>.（dasの）</div>
<div class="mpage">188</div>
<div class="bango"> </div>
<div class="daimoku">［14］esの省略（主語） 1.wie, als等の後</div>
<div class="mpage">189</div>
<div class="bango"> </div>
<div class="daimoku">［15］倒置の際のesの省略は人の四格を伴ふものに限る。然らざるものはesを存す。<br />また「後置」の際の「受動自動詞」のesの省略と混同す可からず。</div>
<div class="mpage">190</div>
<div class="bango"> </div>
<div class="daimoku">［16］文意（後に未る文意）を預め受けるes。</div>
<div class="mpage">191</div>
<div class="bango">18-3B</div>
<div class="daimoku">人代名詞と名詞の語順</div>
<div class="mpage">193-210</div>
<div class="bango">18-4B</div>
<div class="daimoku">haste? Weisst?</div>
<div class="mpage">211-222</div>
<div class="bango">18-5R</div>
<div class="daimoku">二人称<u>ihr</u>に関する参考</div>
<div class="mpage">223-233</div>
<div class="bango"> </div>
<div class="daimoku">紹介のse。 1ch bin's.等<br />事務的<u>wir</u>, <u>unser</u>.（当方、売店、本社）<u>unser Held</u>.<br />二人称du, sie, ihr等に関する参考<br />中性以外をesで受ける如き観を呈する場合<br />編者注：このほか6件あり。</div>
<div class="mpage"> </div>
<div class="bango">18-6B</div>
<div class="daimoku">it was the weather.</div>
<div class="mpage">234-236</div>
<div class="bango">18-7R</div>
<div class="daimoku"><u>unser</u>eins, <u>unser</u>keins の文法を加える！<br />返事としてのich.<br />［エ］Estas mire. Ke...<br />Es kommen <u>ihrer</u> 103など von <u>ihnen</u><br />1.指示代名詞の代りに人代名詞を用いることが多い<br />2.Der bin ichなども</div>
<div class="mpage">237-240</div>
<div class="bango">18-8B</div>
<div class="daimoku">著者用のwir ［仏］onを用ふ。</div>
<div class="mpage">241-245</div>
<div class="bango">18-9B</div>
<div class="daimoku">複数二格 <u>ihrer</u>の残物</div>
<div class="mpage">246-247</div>
<div class="bango">18-10R</div>
<div class="daimoku">二人称に持ひるer, sie等。（大書するや否やは不定）<br />伯林訛りのmirとmich</div>
<div class="mpage">248-249</div>
<div class="bango">18-11B</div>
<div class="daimoku">Meine wenigkeit等</div>
<div class="mpage">250-253</div>
<div class="bango">18-12R</div>
<div class="daimoku">頓呼法（二人称への急転）<br />［羅］等の人代名詞省略<br />Dammelo等について donne-le-moi!<br />"BESAME MUCHO"<br />教訓的宣言に於て一般的に指すDu.<br />方言 ihrの代りにdir<br />方言 wirの代りにmer<br />Dualis -Zweizahl-</div>
<div class="mpage">254-261</div>
<div class="bango">18-13B</div>
<div class="daimoku">古典語は人代名詞主語を省くことが多いという点について。</div>
<div class="mpage">262-264</div>
<div class="bango">18-14R</div>
<div class="daimoku">希臘語等に於ては物主形容詞の代りに人代名詞二格を用ふ。<br /><u>wir</u> Japaner<br />Lieber <u>Leser</u>, du～ 読者にduzenするは独独特なるべし。仏はvous（manと通ず）<br />代名詞がどの名詞を受けるか？という問題<br />代名詞のqui pro quo.<br />人代名詞（及ぴ物形詞）の決定は意味の如何によらず、その局部の考え方による。<br />編者注：このほか29件あり。</div>
<div class="mpage">265-289</div>
</div>