<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">20-1B</div>
<div class="daimoku">schon</div>
<div class="mpage">1-101</div>
<div class="bango"> </div>
<div class="daimoku">順序（論理的9…となると既に</div>
<div class="mpage">3</div>
<div class="bango"> </div>
<div class="daimoku">前置接続詞的。</div>
<div class="mpage">6</div>
<div class="bango"> </div>
<div class="daimoku">大丈夫、もう、まあ。「いづれ」楽観の表現</div>
<div class="mpage">7</div>
<div class="bango"> </div>
<div class="daimoku">こうなって来るとこるなどうしても「もう」…仕方がない どうも</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">gleich, nur, gleich.doch.</div>
<div class="mpage">13</div>
<div class="bango"> </div>
<div class="daimoku">疑問文に（auchと同じ） 侮蔑的。<br />「いづれ」大したものじゃない。</div>
<div class="mpage">14</div>
<div class="bango"> </div>
<div class="daimoku">なあに、（負け惜しみ、etc）<br />begütigend 安堵させるため。 （ja schon）<br />認める（たしかに）「まあ」</div>
<div class="mpage">20</div>
<div class="bango"> </div>
<div class="daimoku">驚く勿れ等 「とても」 「そりやアとても」</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">命令法と共に。「まあどうぞ」御勘弁遊ばせて等。</div>
<div class="mpage">22</div>
<div class="bango"> </div>
<div class="daimoku">況んや…に至っては（schon gar nicht.）</div>
<div class="mpage">27</div>
<div class="bango"> </div>
<div class="daimoku">既に既に…（尖置）</div>
<div class="mpage">29</div>
<div class="bango"> </div>
<div class="daimoku">肯定を強めるもの。（勿論）</div>
<div class="mpage">31</div>
<div class="bango"> </div>
<div class="daimoku">既に云々せんとしたるところ</div>
<div class="mpage">32</div>
<div class="bango"> </div>
<div class="daimoku">Ich will schon! schon lieber, schon wieder</div>
<div class="mpage">33</div>
<div class="bango"> </div>
<div class="daimoku">Es müsste schon mit dem Teufe1 zugehen, <br />wenn....sollte</div>
<div class="mpage">35</div>
<div class="bango"> </div>
<div class="daimoku">so（ge1egent1ich）=ich weiss nicht wie....<br />なんだか</div>
<div class="mpage">39</div>
<div class="bango"> </div>
<div class="daimoku">その通りで（よろしい、等）形容詞的</div>
<div class="mpage">43</div>
<div class="bango"> </div>
<div class="daimoku">比較Wieの後に来るso<br />さう言う風に（動詞につ&lt;）<u>thus</u></div>
<div class="mpage">51</div>
<div class="bango"> </div>
<div class="daimoku">so vier, so gut, so lange 非常に（一般項）</div>
<div class="mpage">52</div>
<div class="bango"> </div>
<div class="daimoku">斯&lt;の如くにしては（仮定的）</div>
<div class="mpage">53</div>
<div class="bango"> </div>
<div class="daimoku">古典的so. ［so c1assicum］ wohl</div>
<div class="mpage">62</div>
<div class="bango"> </div>
<div class="daimoku">仏語のtant....（aussiニ非ズ） 後に来るso....<br />sonst</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">然らずんば さもなければ</div>
<div class="mpage">87</div>
<div class="bango"> </div>
<div class="daimoku">so auch so 接続詞としてのso</div>
<div class="mpage">96</div>
<div class="bango">20-2B</div>
<div class="daimoku">Nur <u>nur noch.</u>. （<u>nicht</u> <u>mehr</u>の肯定）</div>
<div class="mpage">102-160</div>
<div class="bango"> </div>
<div class="daimoku">疑問のnur.（不審る）（反語にも）<br />（あきれる時も）<br />願望のnur. 心配のnur</div>
<div class="mpage">107</div>
<div class="bango"> </div>
<div class="daimoku">nur［dann］....wenn. nur zu....（nur soも同じ）</div>
<div class="mpage">113</div>
<div class="bango"> </div>
<div class="daimoku">nur（leider）但し</div>
<div class="mpage">119</div>
<div class="bango"> </div>
<div class="daimoku">普通のnur</div>
<div class="mpage">121</div>
<div class="bango"> </div>
<div class="daimoku">とにかく--<u>だけ</u>の.（nur eben）</div>
<div class="mpage">123</div>
<div class="bango"> </div>
<div class="daimoku"><u>wo nur</u>....（allein） <u>der nur</u>....（a11ein）<br />前置詞的接続詞として。<br />せめて（wenigstens.）</div>
<div class="mpage">129</div>
<div class="bango"> </div>
<div class="daimoku">命令法と共に<u>nur</u>.（まアいいから）（まあ）</div>
<div class="mpage">130</div>
<div class="bango"> </div>
<div class="daimoku">前置詞的接続詞としてのnur, alleinは、必ずしも名詞等の直前直後にはない。</div>
<div class="mpage">138</div>
<div class="bango"> </div>
<div class="daimoku">nur［noch］（ただますます…なるぱかりだ）<br />「もはや…」のnur nochとはちがふ。</div>
<div class="mpage">139</div>
<div class="bango"> </div>
<div class="daimoku">…にして始めて…なる… wie…nur</div>
<div class="mpage">145</div>
<div class="bango"> </div>
<div class="daimoku">, allein）</div>
<div class="mpage">149</div>
<div class="bango"> </div>
<div class="daimoku">微妙なnur（悪い方の意）</div>
<div class="mpage">151</div>
<div class="bango"> </div>
<div class="daimoku">ただ…した<u>ばっかりに</u> 普通の<u>nur so</u></div>
<div class="mpage">155</div>
<div class="bango">20-3B</div>
<div class="daimoku">Noch</div>
<div class="mpage">161-246</div>
<div class="bango"> </div>
<div class="daimoku"><u>noch lange nicht</u>.（D.Kein） なほ（一層）のnoc&lt;（比較級と）</div>
<div class="mpage">162</div>
<div class="bango"> </div>
<div class="daimoku">sogar［前置的場合のみ］最高級</div>
<div class="mpage">164</div>
<div class="bango"> </div>
<div class="daimoku">sogar…時問的</div>
<div class="mpage">167</div>
<div class="bango"> </div>
<div class="daimoku">Das fehlte noch. Das fehlte noch gerade<br />と接続法。</div>
<div class="mpage">178</div>
<div class="bango"> </div>
<div class="daimoku">大丈夫、その中に（<u>schon</u>） <u>noch einmal</u><br />その内にいづれ、きっと</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">nochの先置（まだ、今のところは）仮定強調的</div>
<div class="mpage">189</div>
<div class="bango"> </div>
<div class="daimoku">準否定詞kaum, wenig, selten, nur,等の際のmehrはnochとなる。</div>
<div class="mpage">193</div>
<div class="bango"> </div>
<div class="daimoku">危なく、際どくも（やっと間に合ふ）</div>
<div class="mpage">194</div>
<div class="bango"> </div>
<div class="daimoku"><u>wahr1ich</u>［間投文内のnoch］</div>
<div class="mpage">201</div>
<div class="bango"> </div>
<div class="daimoku">noch nachträglich.（そのうちに、いづれ、あとになって、後日）</div>
<div class="mpage">202</div>
<div class="bango"> </div>
<div class="daimoku">むしろ。まだしも。weinigstens.</div>
<div class="mpage">205</div>
<div class="bango"> </div>
<div class="daimoku"><u>noch so</u> …［認容的］=<u>auch</u> <u>noch</u> <u>so</u>.</div>
<div class="mpage">208</div>
<div class="bango"> </div>
<div class="daimoku">wann...._<u>noch</u>（殆んど無意）<br />まだしも。まあ…さう言ってもまあ</div>
<div class="mpage">209</div>
<div class="bango"> </div>
<div class="daimoku">古い物が案外現在と関係ある事を示すnoch.</div>
<div class="mpage">214</div>
<div class="bango"> </div>
<div class="daimoku">schon.（noch vor, noch ehe）<u>very</u></div>
<div class="mpage">220</div>
<div class="bango"> </div>
<div class="daimoku">時聞的。「すぐに、早速」<u>noch</u> heute</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">［sogar］<u>noch</u></div>
<div class="mpage">226</div>
<div class="bango"> </div>
<div class="daimoku">疑問文中のnoch</div>
<div class="mpage">233</div>
<div class="bango"> </div>
<div class="daimoku">noch（dazu）剰さへ</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">まづどうにか</div>
<div class="mpage">243</div>
<div class="bango"> </div>
<div class="daimoku">Zum Kuckuk noch mal!</div>
<div class="mpage">244</div>
<div class="bango">20-4B</div>
<div class="daimoku">sehr</div>
<div class="mpage">247</div>
<div class="bango">20-5B</div>
<div class="daimoku">selbst<br /><u>selbst</u>と<u>selber</u> その他self=の複合詞<br />Hier ist er selbst!（om Person）<br />登場人物をmeldenする時。</div>
<div class="mpage">248-255</div>
<div class="bango">20-6R</div>
<div class="daimoku">［und］soそういうわけで <u>so</u>〈z.B.）</div>
<div class="mpage">256-259</div>
<div class="bango">20-7B</div>
<div class="daimoku">nun</div>
<div class="mpage">260-296</div>
<div class="bango"> </div>
<div class="daimoku">辛抱を切らした際に出る<u>nun</u></div>
<div class="mpage">263</div>
<div class="bango"> </div>
<div class="daimoku">間投詞の<u>nun</u>（<ruby>惘<rt>あき</rt></ruby>れた時）</div>
<div class="mpage">263</div>
<div class="bango"> </div>
<div class="daimoku">nanu!</div>
<div class="mpage">264</div>
<div class="bango"> </div>
<div class="daimoku">認容文の<u>nun</u></div>
<div class="mpage">264</div>
<div class="bango"> </div>
<div class="daimoku">nun ja, nun freilich,</div>
<div class="mpage">265</div>
<div class="bango"> </div>
<div class="daimoku"><u>nun einmal</u>,<u>einmal</u>,</div>
<div class="mpage">267</div>
<div class="bango"> </div>
<div class="daimoku">nun, nun! nu, nu!（宥める時） begütigend.</div>
<div class="mpage">272</div>
<div class="bango"> </div>
<div class="daimoku"><ruby>扠<rt>さ</rt></ruby>て、ところで。</div>
<div class="mpage">278</div>
<div class="bango"> </div>
<div class="daimoku">nun denn 然らば <u>nun</u> also</div>
<div class="mpage">279</div>
<div class="bango"> </div>
<div class="daimoku">....nun（eben）</div>
<div class="mpage">282</div>
<div class="bango"> </div>
<div class="daimoku">nun wohl eben nicht. nun einmal</div>
<div class="mpage">283</div>
<div class="bango">20-8B</div>
<div class="daimoku">und</div>
<div class="mpage">297-331</div>
<div class="bango"> </div>
<div class="daimoku">dann, soの意 さうすれば</div>
<div class="mpage">298</div>
<div class="bango"> </div>
<div class="daimoku">しかも（trotzdem） undと定形</div>
<div class="mpage">300</div>
<div class="bango"> </div>
<div class="daimoku">und（doch）.... …なのだが。</div>
<div class="mpage">302</div>
<div class="bango"> </div>
<div class="daimoku"><u>oder</u></div>
<div class="mpage">302</div>
<div class="bango"> </div>
<div class="daimoku">darum....であったので、因由、（und［so］）</div>
<div class="mpage">303</div>
<div class="bango"> </div>
<div class="daimoku">それに…［”しかも”とはちがふ］</div>
<div class="mpage">303</div>
<div class="bango"> </div>
<div class="daimoku">殆ど無意味なつなぎ方</div>
<div class="mpage">304</div>
<div class="bango"> </div>
<div class="daimoku">undを何度も用ふ polysyndeton</div>
<div class="mpage">305</div>
<div class="bango"> </div>
<div class="daimoku"><u>undを最後に</u>（普通）</div>
<div class="mpage">310</div>
<div class="bango"> </div>
<div class="daimoku">undなく。いわゆるAsyndeton</div>
<div class="mpage">318</div>
<div class="bango"> </div>
<div class="daimoku">近くして遠からず。</div>
<div class="mpage">319</div>
<div class="bango"> </div>
<div class="daimoku">逆順（一般的な宣言があと）</div>
<div class="mpage">320</div>
<div class="bango">20-9B</div>
<div class="daimoku">wohl</div>
<div class="mpage">332-379</div>
<div class="bango"> </div>
<div class="daimoku">まあ、まず（渋々の承諾）, 「恐らくは」の変態。</div>
<div class="mpage">333</div>
<div class="bango"> </div>
<div class="daimoku">おそらくは、思うに。</div>
<div class="mpage">334</div>
<div class="bango"> </div>
<div class="daimoku">疑問文内のwohl.</div>
<div class="mpage">335</div>
<div class="bango"> </div>
<div class="daimoku">Pleonastisches "Wohl".云々するの<u>であった</u> 頭など振りけり <u>叙述的</u>の場合多し</div>
<div class="mpage">336</div>
<div class="bango"> </div>
<div class="daimoku">習慣性のwohl「よく」あった、等</div>
<div class="mpage">340</div>
<div class="bango"> </div>
<div class="daimoku"><u>wohl aber</u></div>
<div class="mpage">347</div>
<div class="bango"> </div>
<div class="daimoku">なるほど確かに……であらう！　認容<br />さうであらうとも！　尤もでござる</div>
<div class="mpage">352</div>
<div class="bango"> </div>
<div class="daimoku"><u>ungefähr</u>，又は「裕に」gut（数詞）</div>
<div class="mpage">354</div>
<div class="bango"> </div>
<div class="daimoku"><u>wohl</u>（=zwahr）-aber-</div>
<div class="mpage">356</div>
<div class="bango"> </div>
<div class="daimoku">Es ist sehr wohl mÖglich.<br />たしかに、とうも（可能性濃厚）</div>
<div class="mpage">358</div>
<div class="bango"> </div>
<div class="daimoku">［雑］wieder, wiederum</div>
<div class="mpage">360</div>
<div class="bango"> </div>
<div class="daimoku"><u>zurück</u></div>
<div class="mpage">361</div>
<div class="bango"> </div>
<div class="daimoku"><u>wieder einmal</u></div>
<div class="mpage">362</div>
<div class="bango"> </div>
<div class="daimoku">doch wieder（さうかとおもふとまた）</div>
<div class="mpage">363</div>
<div class="bango"> </div>
<div class="daimoku">wiederum, seinerseits</div>
<div class="mpage">364</div>
<div class="bango"> </div>
<div class="daimoku">疑問文または間投文内のwieder</div>
<div class="mpage">367</div>
<div class="bango"> </div>
<div class="daimoku">wieder=immer やはり、同様</div>
<div class="mpage">368</div>
<div class="bango"> </div>
<div class="daimoku">wiederとwiederum（”反対に”のwiederumもあり）</div>
<div class="mpage">378</div>
<div class="bango"> </div>
<div class="daimoku">schon wieder.<br />［雑］ <u>was</u><br />何</div>
<div class="mpage">371</div>
<div class="bango"> </div>
<div class="daimoku">文意を受ける関係的was</div>
<div class="mpage">373</div>
<div class="bango"> </div>
<div class="daimoku">wasの意のwas. "wozu"</div>
<div class="mpage">373</div>
<div class="bango"> </div>
<div class="daimoku">名詞化形容詞を伴ふ疑問の<u>was</u>.</div>
<div class="mpage">374</div>
<div class="bango"> </div>
<div class="daimoku">was（wie）---!</div>
<div class="mpage">374</div>
<div class="bango"> </div>
<div class="daimoku">［雑］ <u>wenig</u></div>
<div class="mpage">375</div>
<div class="bango"> </div>
<div class="daimoku">［雑］ <u>wo</u></div>
<div class="mpage">377</div>
<div class="bango"> </div>
<div class="daimoku">関係代名詞（空間的）</div>
<div class="mpage">378</div>
<div class="bango"> </div>
<div class="daimoku">関係代名詞（時間的）</div>
<div class="mpage">378</div>
<div class="bango"> </div>
<div class="daimoku">Wo <u>nur</u>; wo <u>allein</u>.</div>
<div class="mpage">378</div>
<div class="bango"> </div>
<div class="daimoku">［雑］ <u>wer</u></div>
<div class="mpage">379</div>
</div>