<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango"> </div>
<div class="daimoku"> </div>
<div class="mpage"> </div>
<div class="bango">24-1B</div>
<div class="daimoku">接続詞 従属的接続詞</div>
<div class="mpage">1-35</div>
<div class="bango"> </div>
<div class="daimoku">［01］複雑な成句的接続詞</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">［02］後続的意 "als"を主として</div>
<div class="mpage">6</div>
<div class="bango"> </div>
<div class="daimoku">［03］一つの単語（名詞，代名詞）を規定する際。</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">［04］関係代名詞の文の後続的なるもの。</div>
<div class="mpage">13</div>
<div class="bango"> </div>
<div class="daimoku">［05］<u>副詞と相呼應するもの</u>。</div>
<div class="mpage">15</div>
<div class="bango"> </div>
<div class="daimoku">［06］solangeとsolange.<br />従属的が前置詞的になる例。（附加語的）</div>
<div class="mpage">16</div>
<div class="bango"> </div>
<div class="daimoku">［07］副詞と同語 solange...., solange....<br />sooft...., ,sooft....<br />sobald...., sobald....</div>
<div class="mpage">24</div>
<div class="bango"> </div>
<div class="daimoku">［08］接続詞の発生 gesetzt, voraus gesetzt,<br />ausgenommen,angenommen im Fall<br />widrigenfalls</div>
<div class="mpage">29</div>
<div class="bango"> </div>
<div class="daimoku">［09］後続（又は「延長」）に関する雜例：<br />［英］when, while等の次に現在分詞句等を</div>
<div class="mpage">31</div>
<div class="bango">24-2B</div>
<div class="daimoku">前置詞的接続詞</div>
<div class="mpage">36-166</div>
<div class="bango"> </div>
<div class="daimoku">［01］前置詞的接統詞が名詞以外の品詞にもつく例。</div>
<div class="mpage">40</div>
<div class="bango"> </div>
<div class="daimoku">［02］<u>umso</u>, <u>desto</u>.（比較級にのみつく。）</div>
<div class="mpage">42</div>
<div class="bango"> </div>
<div class="daimoku">［03］従属的接続詞が前置的接続詞化する経過</div>
<div class="mpage">43</div>
<div class="bango"> </div>
<div class="daimoku">［04］nur,lauter,eitel,bloß,allein,rein,etc.</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">［05］<u>als</u>（として）とその次の格。（<u>wie</u>も）</div>
<div class="mpage">49</div>
<div class="bango"> </div>
<div class="daimoku">［06］schon.= noch</div>
<div class="mpage">63</div>
<div class="bango"> </div>
<div class="daimoku">［07］<u>vollends</u>, <u>nun</u> <u>gar</u>,<u>erst</u>,<u>erst recht</u>,<u>wohigar</u>,<u>nun erst</u>.</div>
<div class="mpage">70</div>
<div class="bango"> </div>
<div class="daimoku">［08］geschweige denn（及び…zu schweigenn）</div>
<div class="mpage">78</div>
<div class="bango"> </div>
<div class="daimoku">［09］<u>wie</u>と<u>格</u></div>
<div class="mpage">81</div>
<div class="bango"> </div>
<div class="daimoku">［10］selbst,sogar,auch,noch,auch nur.</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">［11］zumal,besonders inbesondere, vor allem,</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">［12］<u>gerade</u>,<u>eben</u>,（が反って）</div>
<div class="mpage">101</div>
<div class="bango"> </div>
<div class="daimoku">［13］geradezu,g1eichsam,direkt.</div>
<div class="mpage">106</div>
<div class="bango"> </div>
<div class="daimoku">［14］動詞にもつくか。（大問題）</div>
<div class="mpage">112</div>
<div class="bango"> </div>
<div class="daimoku">［15］als....<u>の時に</u>。</div>
<div class="mpage">113</div>
<div class="bango"> </div>
<div class="daimoku">［16］selber,selbst（必ず後置）</div>
<div class="mpage">116</div>
<div class="bango"> </div>
<div class="daimoku">［17］nur, erst.（…云々にして初めて）</div>
<div class="mpage">118</div>
<div class="bango"> </div>
<div class="daimoku">［18］überhaupt, schlechthin, schlechtweg.</div>
<div class="mpage">119</div>
<div class="bango"> </div>
<div class="daimoku">［19］zuerst（最初に）</div>
<div class="mpage">121</div>
<div class="bango"> </div>
<div class="daimoku">［20］<u>sich</u>とals（四格か一格か）</div>
<div class="mpage">123</div>
<div class="bango"> </div>
<div class="daimoku">［21］<u>als</u>, <u>wie</u>と前置詞の繰返し。（及び繰返さぬ例）</div>
<div class="mpage">146</div>
<div class="bango"> </div>
<div class="daimoku">［22］nur（普通の）allein.</div>
<div class="mpage">155</div>
<div class="bango"> </div>
<div class="daimoku">［23］auch.</div>
<div class="mpage">165</div>
<div class="bango">24-3B</div>
<div class="daimoku">編者注：本袋「24-3B」内は二つのノート・ブックに整理されているので、これを記号①、②で示すことにした。</div>
<div class="mpage">167-317</div>
<div class="bango"> </div>
<div class="daimoku">対照的接続詞 Korrelative Partikeln</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">①［01］例</div>
<div class="mpage">169</div>
<div class="bango"> </div>
<div class="daimoku">①［02］je....destoは対句的接続詞にず。・・・・</div>
<div class="mpage">183</div>
<div class="bango"> </div>
<div class="daimoku">①［03］entweder....oder（aber）....</div>
<div class="mpage">199</div>
<div class="bango"> </div>
<div class="daimoku">①［04］weder.... noch....<br />nlcht（等）.... noch....</div>
<div class="mpage">205</div>
<div class="bango"> </div>
<div class="daimoku">①［05］wohl.... doch.［zwar....aber等］</div>
<div class="mpage">222</div>
<div class="bango"> </div>
<div class="daimoku">①［06］nlcht［nur］....sondern［auch, sogar］</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">①［07］nlcht sowoh1----als vielmehr</div>
<div class="mpage">240</div>
<div class="bango"> </div>
<div class="daimoku">①［08］wenn auch［nlcht］....so doch（wenigstens）</div>
<div class="mpage">247</div>
<div class="bango"> </div>
<div class="daimoku">前置詞 一般論</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">②［01］nlcht nur....sonder auch</div>
<div class="mpage">257</div>
<div class="bango"> </div>
<div class="daimoku">②［02］sowenig....daß viel mehr....</div>
<div class="mpage">259</div>
<div class="bango"> </div>
<div class="daimoku">②［03］einmal....dann aber（sodann）<br />zum ersten....zum zweiten</div>
<div class="mpage">266</div>
<div class="bango"> </div>
<div class="daimoku">②［04］hie....hie</div>
<div class="mpage">279</div>
<div class="bango"> </div>
<div class="daimoku">②［05］bald....bald....（jetzt, jetzt）その他<br />mal....mal....</div>
<div class="mpage">281</div>
<div class="bango"> </div>
<div class="daimoku">②［06］so...., wie....,<br />sowohl...., auch....</div>
<div class="mpage">291</div>
<div class="bango">24-4B</div>
<div class="daimoku">併立的接続詞</div>
<div class="mpage">318-375</div>
<div class="bango"> </div>
<div class="daimoku">［01］例</div>
<div class="mpage">320</div>
<div class="bango"> </div>
<div class="daimoku">［02］所属不明なるもの <u>und zwar</u>.</div>
<div class="mpage">329</div>
<div class="bango"> </div>
<div class="daimoku">［03］um nicht sogar</div>
<div class="mpage">341</div>
<div class="bango"> </div>
<div class="daimoku">［04］［um］ wieviel mehr（いはんゃ）</div>
<div class="mpage">343</div>
<div class="bango"> </div>
<div class="daimoku">［05］<u>sagen wir</u>（meinetwegen） sprich! 即ち</div>
<div class="mpage">364</div>
<div class="bango"> </div>
<div class="daimoku">［06］aber auch</div>
<div class="mpage">367</div>
<div class="bango"> </div>
<div class="daimoku">［07］und（そのくせ、しかも） und doch.</div>
<div class="mpage">369</div>
<div class="bango"> </div>
<div class="daimoku">［08］und 然らば…せん。</div>
<div class="mpage">369</div>
<div class="bango"> </div>
<div class="daimoku">［09］oder（Alternativisch）</div>
<div class="mpage">372</div>
<div class="bango">24-5B</div>
<div class="daimoku">副詞一般の前置詞的傾向</div>
<div class="mpage">376-378</div>
<div class="bango">24-6B</div>
<div class="daimoku">So+ 云々の従属文構成 alsの機能<br />Korrelativaを含む alsのなくなった形なり。<br />so jung ich bin. ［als］</div>
<div class="mpage">379-405</div>
<div class="bango"> </div>
<div class="daimoku">［01］soと形容詞、副詞（認容的）</div>
<div class="mpage">380</div>
<div class="bango"> </div>
<div class="daimoku">［02］so gut等（できるだけ）<br />wieの省略。</div>
<div class="mpage">387</div>
<div class="bango"> </div>
<div class="daimoku">［03］so vier（できるだけ）alsを含まぬもの</div>
<div class="mpage">388</div>
<div class="bango"> </div>
<div class="daimoku">［04］Maximum（soと形容詞、副詞）</div>
<div class="mpage">391</div>
<div class="bango"> </div>
<div class="daimoku">［05］原因、理のso....家（als）er war等</div>
<div class="mpage">393</div>
<div class="bango"> </div>
<div class="daimoku">［06］誓ひ。 （so wahr....）</div>
<div class="mpage">394</div>
<div class="bango"> </div>
<div class="daimoku">［07］so～, so～（主文、副文ともsoの構造）<br />so gewiß, とso wenigが主なり。</div>
<div class="mpage">397</div>
<div class="bango"> </div>
<div class="daimoku">［08］soweit, solange（限定的）</div>
<div class="mpage">403</div>
<div class="bango">24-7B</div>
<div class="daimoku">als（として）と同意のwie（微妙な閏係）</div>
<div class="mpage">406</div>
<div class="bango">24-8B</div>
<div class="daimoku">kurz, im Gegenteil, nun等<u>間投的</u>接続詞</div>
<div class="mpage">407-415</div>
<div class="bango">24-9R</div>
<div class="daimoku">文から文への移向を滑らかにするための<br />particle of transition<br /><u>渡しことば</u><br />Particula transitionis<br />als（即ち） 意味の問題<br />als, wieの次の餘計な補足<br />Wie ich es tue.等<br />und <u>umgekehrt</u><br />句の従属接続詞化</div>
<div class="mpage">416-422</div>
<div class="bango">24-10B</div>
<div class="daimoku">副詞的接続詞 indessen等</div>
<div class="mpage">423-429</div>
<div class="bango">24-11B</div>
<div class="daimoku">接続詞 一般論</div>
<div class="mpage">430-432</div>
<div class="bango"> </div>
<div class="daimoku">［01］接続詞の前につく副詞</div>
<div class="mpage">431</div>
<div class="bango"> </div>
<div class="daimoku">［02］<u>一般問題</u>：<u>Adnominal</u></div>
<div class="mpage">431</div>
<div class="bango"> </div>
<div class="daimoku">［03］副詞に非ずして接続詞なることのKriteriumは其の貶置的位置なり。</div>
<div class="mpage">432</div>
<div class="bango">24-12R</div>
<div class="daimoku"><u>Syllogismus</u>.: （also, folglich等と其の後の倒置、正置の問題）<br />dann.（一語を説明する）<br />（挿入文にも関係す）挿入の<u>denn</u>又は<u>und</u><br />荘重なるdenn<br />Dem: 結果を以て推す<br />Dennの発言的基礎なることを証するによき例：<br />編者注：このほかに11件あり。</div>
<div class="mpage">433-443</div>
</div>