<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">31-1B</div>
<div class="daimoku">編者注：本袋「31-1B」内は二つのノート・ブックに整理されているので、これを記号①、②で示すことにした。<br />定形倒置及び先置 転置</div>
<div class="mpage">1-2</div>
<div class="bango"> </div>
<div class="daimoku">①［01］doch, aber それが証拠に。</div>
<div class="mpage">3</div>
<div class="bango"> </div>
<div class="daimoku">①［02］sah ein Knab ein Röslein stehn.<br />（es sah ein Knab）</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">①［03］WENN SATZ</div>
<div class="mpage">23</div>
<div class="bango"> </div>
<div class="daimoku">①［04］一分肢の先置（普通の場合）</div>
<div class="mpage">41</div>
<div class="bango"> </div>
<div class="daimoku">①［05］二つ以上の。肢の先置</div>
<div class="mpage">47</div>
<div class="bango"> </div>
<div class="daimoku">①［06］過去分詞の先置。</div>
<div class="mpage">58</div>
<div class="bango"> </div>
<div class="daimoku">①［07］Arbeiten <u>tut</u> der Kerl nieh.</div>
<div class="mpage">62</div>
<div class="bango"> </div>
<div class="daimoku">①［08］不定法先置<br />Arbeiten will der Keil nicht.</div>
<div class="mpage">65</div>
<div class="bango"> </div>
<div class="daimoku">①［09］鋭いAntithese</div>
<div class="mpage">67</div>
<div class="bango"> </div>
<div class="daimoku">①［10］反語文に於ける第二倒置の主語は省く。</div>
<div class="mpage">73</div>
<div class="bango"> </div>
<div class="daimoku">①［11］Daher,deshalb等の後の定形のみならず<br />動詞全部）</div>
<div class="mpage">75</div>
<div class="bango"> </div>
<div class="daimoku">①［12］"Habe dich!" triumphiert sie. 勝った！</div>
<div class="mpage">78</div>
<div class="bango"> </div>
<div class="daimoku">①［13］俗語に於ける倒置。</div>
<div class="mpage">79</div>
<div class="bango"> </div>
<div class="daimoku">①［14］第二倒置の主語省略（一般的）</div>
<div class="mpage">88</div>
<div class="bango"> </div>
<div class="daimoku">定形先置</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">②［01］wennの代。（もしも）</div>
<div class="mpage">94</div>
<div class="bango"> </div>
<div class="daimoku">②［02］間投的。</div>
<div class="mpage">95</div>
<div class="bango"> </div>
<div class="daimoku">②［03］主語の省略（実は先置に非ず）</div>
<div class="mpage">97</div>
<div class="bango"> </div>
<div class="daimoku">②［04］Fertig ist es schon ～.</div>
<div class="mpage">97</div>
<div class="bango"> </div>
<div class="daimoku">②［05］<u>sagte er</u> 等</div>
<div class="mpage">98</div>
<div class="bango"> </div>
<div class="daimoku">②［06］それが証拠に（doch）</div>
<div class="mpage">98</div>
<div class="bango"> </div>
<div class="daimoku">②［07］接続詞後の倒置</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">②［08］文肢の強きもの。</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">②［09］疑問文・間投文においては一文肢の強調先置は普通は不可</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">②［10］形容詞を残して名詞の先置。</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">②［11］<u>不定句の先置</u></div>
<div class="mpage">101</div>
<div class="bango"> </div>
<div class="daimoku">②［12］対立と認容には好んで文肢を先置す。</div>
<div class="mpage">101</div>
<div class="bango"> </div>
<div class="daimoku">②［13］<u>文肢先置</u>の普通例。</div>
<div class="mpage">102</div>
<div class="bango"> </div>
<div class="daimoku">②［14］形容詞等の先置</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">②［15］疑問文に於ても一文肢を先置する：</div>
<div class="mpage">107</div>
<div class="bango">31-2B</div>
<div class="daimoku">正置</div>
<div class="mpage">108-157</div>
<div class="bango"> </div>
<div class="daimoku">［01］also「では」等と正（nun.）間投詞化す。</div>
<div class="mpage">109</div>
<div class="bango"> </div>
<div class="daimoku">［02］副文章後の主文章の正置、倒置。</div>
<div class="mpage">111</div>
<div class="bango"> </div>
<div class="daimoku">［03］Es mährte nicht lange und....</div>
<div class="mpage">120</div>
<div class="bango"> </div>
<div class="daimoku">［04］wennの文の第二次以後を正置。倒置。</div>
<div class="mpage">125</div>
<div class="bango"> </div>
<div class="daimoku">［05］叙述に直接性を附するための、後部に於ける<br />正置への転向。</div>
<div class="mpage">135</div>
<div class="bango"> </div>
<div class="daimoku">［06］Ich glaube, er ist fort.</div>
<div class="mpage">136</div>
<div class="bango"> </div>
<div class="daimoku">［07］Er wäre im stande <u>und</u> malte es hin.</div>
<div class="mpage">140</div>
<div class="bango"> </div>
<div class="daimoku">［08］Es fehlt nicht viel,so....</div>
<div class="mpage">145</div>
<div class="bango"> </div>
<div class="daimoku">［09］Sei bitte so gut und komm zeitig<br />nach Hause,ja?</div>
<div class="mpage">149</div>
<div class="bango">31-3B</div>
<div class="daimoku">Inversion nach "<u>und</u>"</div>
<div class="mpage">158-163</div>
<div class="bango">31-4B</div>
<div class="daimoku">文肢先置とコンマの問題</div>
<div class="mpage">164</div>
<div class="bango">31-5B</div>
<div class="daimoku">定形</div>
<div class="mpage">165-228</div>
<div class="bango"> </div>
<div class="daimoku">［01］単か複か?</div>
<div class="mpage">169</div>
<div class="bango"> </div>
<div class="daimoku">［02］ニ語の次に来る定形の数。（無冠詞）</div>
<div class="mpage">182</div>
<div class="bango"> </div>
<div class="daimoku">［03］尊称的複数。PLURALIS <u>REVERENTIAE</u>.</div>
<div class="mpage">188</div>
<div class="bango"> </div>
<div class="daimoku">［04］代名詞が述語となる場合（Nennsatzに於て）</div>
<div class="mpage">190</div>
<div class="bango"> </div>
<div class="daimoku">［05］das,was,dies,es,jenes,welchesと複数定形。<br />（主として<u>was</u>）</div>
<div class="mpage">191</div>
<div class="bango"> </div>
<div class="daimoku">［06］Ich und mein Vater <u>haben</u>....</div>
<div class="mpage">192</div>
<div class="bango"> </div>
<div class="daimoku">［07］Dreierlei等とs,（od.）pl.</div>
<div class="mpage">196</div>
<div class="bango"> </div>
<div class="daimoku">［08］聯語主語と定形単数</div>
<div class="mpage">197</div>
<div class="bango"> </div>
<div class="daimoku">［09］eine Menge等とpl.定形。（或は単）</div>
<div class="mpage">202</div>
<div class="bango"> </div>
<div class="daimoku">［10］oder, wederでつないだ主語には単数定形。</div>
<div class="mpage">218</div>
<div class="bango"> </div>
<div class="daimoku">［11］mitsamt,zusamt等でつないだものは？</div>
<div class="mpage">221</div>
<div class="bango"> </div>
<div class="daimoku">［12］Ein Freund nach dem andern <u>zog</u> sich zurück.</div>
<div class="mpage">222</div>
<div class="bango"> </div>
<div class="daimoku">［13］Hoch und niedrig, 等が主語の際。<br />Reich und arm</div>
<div class="mpage">222</div>
<div class="bango"> </div>
<div class="daimoku">［14］Meilenstein um Meilensteinと（単数？）</div>
<div class="mpage">223</div>
<div class="bango"> </div>
<div class="daimoku">［15］列挙の後の<u>des</u></div>
<div class="mpage">225</div>
<div class="bango">31-6R</div>
<div class="daimoku">定形の数を近きものに合致せしむ。<br />多くの主語が、実は「繰りかへし」なる事あり。<br />やり直し、言ひ換え、「換覆」</div>
<div class="mpage">229</div>
<div class="bango">31-7B</div>
<div class="daimoku">定形 後置</div>
<div class="mpage">230-244</div>
<div class="bango"> </div>
<div class="daimoku">［01］関係分の後置</div>
<div class="mpage">231</div>
<div class="bango"> </div>
<div class="daimoku">［02］従属的接続詞後の後置</div>
<div class="mpage">232</div>
<div class="bango"> </div>
<div class="daimoku">［03］疑問詞の従属文</div>
<div class="mpage">233</div>
<div class="bango"> </div>
<div class="daimoku">［04］感嘆文の後置</div>
<div class="mpage">233</div>
<div class="bango"> </div>
<div class="daimoku">［05］後置せざるもの（古し）<br />（後置すべきものを後置せざる例）</div>
<div class="mpage">233</div>
<div class="bango"> </div>
<div class="daimoku">［06］主文章の後置</div>
<div class="mpage">234</div>
<div class="bango"> </div>
<div class="daimoku">［07］馬鹿正直なbiedemeyerischな定形後置に<br />関する考察。</div>
<div class="mpage">238</div>
<div class="bango"> </div>
<div class="daimoku">［08］定形後置と外国語。</div>
<div class="mpage">239</div>
<div class="bango"> </div>
<div class="daimoku">［09］定形後置に於て、必ずしも主語が第一位とは<br />限らぬ。</div>
<div class="mpage">242</div>
<div class="bango"> </div>
<div class="daimoku">［10］和蘭語の定形後置：</div>
<div class="mpage">243</div>
<div class="bango"> </div>
<div class="daimoku">［11］英仏の定形後置熟語</div>
<div class="mpage">244</div>
<div class="bango"> </div>
<div class="daimoku">［12］....<u>zu tun</u> die Lust <u>hatte</u>等<br />（zu+不定法と定形後置）</div>
<div class="mpage">244</div>
<div class="bango">31-8B</div>
<div class="daimoku">詩文等における従属文の定形正置</div>
<div class="mpage">245</div>
<div class="bango">31-9B</div>
<div class="daimoku">英仏の定形倒置</div>
<div class="mpage">246-285</div>
<div class="bango">31-10B</div>
<div class="daimoku">正置の場合の填充物について</div>
<div class="mpage">286-291</div>
<div class="bango">31-11R</div>
<div class="daimoku">...., <u>sagt er</u><br />viei+二格複数を主語にして定形を単にする。<br />定形が二個以上になる場合（und,oder）<br />編者注：このほか１３けんあり。</div>
<div class="mpage">292-302</div>
<div class="bango">31-12B</div>
<div class="daimoku">定形倒置 主語省略（代名詞主語）<br />Schlagfertige Antwort及び間投文</div>
<div class="mpage">303-308</div>
<div class="bango">31-13B</div>
<div class="daimoku">wenig sind ihrer（定形は単か複か？）<br />ist</div>
<div class="mpage">309</div>
<div class="bango">31-14B</div>
<div class="daimoku">定形倒置の純例外</div>
<div class="mpage">310</div>
<div class="bango">31-15B</div>
<div class="daimoku">定形倒置に於ける主語の位置</div>
<div class="mpage">311-313</div>
<div class="bango">31-16B</div>
<div class="daimoku">Fifteen minutes is ampl time!［主語］が複数詞</div>
<div class="mpage">314-315</div>
<div class="bango">31-17B</div>
<div class="daimoku">it's 3600 statute miles. 述語が複数詞</div>
<div class="mpage">316-317</div>
<div class="bango">31-18R</div>
<div class="daimoku"><u>Du</u> <u>armes Weib</u>などの際の定形は二人称扱い<br />共通（有）的単数の場合の定形はpl.を要す<br />編者注：このほか13件あり。</div>
<div class="mpage">318-325</div>
<div class="bango">31-19B</div>
<div class="daimoku">俗語と主語duの省略</div>
<div class="mpage">326</div>
<div class="bango">31-20R</div>
<div class="daimoku">定形倒置説明用（初歩） 英語<br />英語に於ける先置の次の定形正置<br />［希］中性pl.と単数定形</div>
<div class="mpage">327</div>
</div>