<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">32-1B</div>
<div class="daimoku">Zuを伴ふ不定法</div>
<div class="mpage">1-252</div>
<div class="bango"> </div>
<div class="daimoku">［01］動詞の直接補足（四格的）となるzu+inf.</div>
<div class="mpage">5</div>
<div class="bango"> </div>
<div class="daimoku">［02］名詞の附加語（限定）となるzu+inf.</div>
<div class="mpage">6</div>
<div class="bango"> </div>
<div class="daimoku">［03］主語esを受けるzu+不定法。</div>
<div class="mpage">24</div>
<div class="bango"> </div>
<div class="daimoku">［04］名詞以外（das, darin等）附加語となるもの</div>
<div class="mpage">33</div>
<div class="bango"> </div>
<div class="daimoku">［05］形容詞の附加語となるもの。（bereit等）</div>
<div class="mpage">34</div>
<div class="bango"> </div>
<div class="daimoku">［06］述語（es）を説明するもの。</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">［07］四格esを受けるzu+不定法</div>
<div class="mpage">49</div>
<div class="bango"> </div>
<div class="daimoku">［08］zu+INF.</div>
<div class="mpage">53</div>
<div class="bango"> </div>
<div class="daimoku">［09］zu+Infとhaben.</div>
<div class="mpage">92</div>
<div class="bango"> </div>
<div class="daimoku">［10］zu+不定法+geben.</div>
<div class="mpage">113</div>
<div class="bango"> </div>
<div class="daimoku">［11］関係文中に入り組んだzu+不定法。</div>
<div class="mpage">114</div>
<div class="bango"> </div>
<div class="daimoku">［12］関係文中のzu+不定法（定形中置、コンマ）</div>
<div class="mpage">120</div>
<div class="bango"> </div>
<div class="daimoku">［13］genug---［um］zu.</div>
<div class="mpage">130</div>
<div class="bango"> </div>
<div class="daimoku">［14］zu+不定法が名詞的なる事の例。</div>
<div class="mpage">141</div>
<div class="bango"> </div>
<div class="daimoku">［15］（um zu）…のために（umの省略）</div>
<div class="mpage">142</div>
<div class="bango"> </div>
<div class="daimoku">［16］schön anzusehen.</div>
<div class="mpage">143</div>
<div class="bango"> </div>
<div class="daimoku">［17］zu....、als daß....</div>
<div class="mpage">176</div>
<div class="bango"> </div>
<div class="daimoku">［18］zu+不定法とkommen.（venir de....と比較）</div>
<div class="mpage">177</div>
<div class="bango"> </div>
<div class="daimoku">［19］名詞化した不定法を伴ふzu</div>
<div class="mpage">191</div>
<div class="bango"> </div>
<div class="daimoku">［20］zu+不定法とbekommen.</div>
<div class="mpage">192</div>
<div class="bango"> </div>
<div class="daimoku">［21］zu+不定法とes gibt.</div>
<div class="mpage">195</div>
<div class="bango"> </div>
<div class="daimoku">［22］［an］statt---zu.</div>
<div class="mpage">199</div>
<div class="bango"> </div>
<div class="daimoku">［23］ohne---zu</div>
<div class="mpage">199</div>
<div class="bango"> </div>
<div class="daimoku">［24］zu+不定法とfinden<br />sehen</div>
<div class="mpage">200</div>
<div class="bango"> </div>
<div class="daimoku">［25］zu+不定法とbleiben, (zu tun bleiben)</div>
<div class="mpage">202</div>
<div class="bango"> </div>
<div class="daimoku">［26］so viel....［um］ zu.</div>
<div class="mpage">206</div>
<div class="bango"> </div>
<div class="daimoku">［27］zu+不定法とgeben.bieten, bringen.</div>
<div class="mpage">208</div>
<div class="bango"> </div>
<div class="daimoku">［28］zu+不定法の句には主語一格なし。<br />それに関する異例その他</div>
<div class="mpage">217</div>
<div class="bango"> </div>
<div class="daimoku">［29］不定区の代りに<u>und</u>を用ひて正文を置く。</div>
<div class="mpage">219</div>
<div class="bango"> </div>
<div class="daimoku">［30］_____ nict zu vergessen, nicht zu rechen. zu schweigen.（認容的）</div>
<div class="mpage">220</div>
<div class="bango"> </div>
<div class="daimoku">［31］ohne....zu.</div>
<div class="mpage">227</div>
<div class="bango"> </div>
<div class="daimoku">［32］名詞附加的［um］zu不定法。<br />－名詞附加は<u>um</u> zuのみなり－</div>
<div class="mpage">227</div>
<div class="bango"> </div>
<div class="daimoku">［33］文肢の先置から起る不定句の遊離。</div>
<div class="mpage">228</div>
<div class="bango"> </div>
<div class="daimoku">［34］<u>未来分詞？</u> <u>Gerundivum</u>. 附加語的</div>
<div class="mpage">229</div>
<div class="bango"> </div>
<div class="daimoku">［35］成句の附加語となるzu+不定法。</div>
<div class="mpage">233</div>
<div class="bango"> </div>
<div class="daimoku">［36］附加語となるもの。（Deine Art zu sein）</div>
<div class="mpage">237</div>
<div class="bango"> </div>
<div class="daimoku">［37］Zuを伴ふ不定法の重畳。</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">［38］<u>an</u> etw......zu ～ haben.</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">［39］istを省いた....zu+不定法</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">［40］zu不定法とstehen.（=sein）</div>
<div class="mpage">242</div>
<div class="bango"> </div>
<div class="daimoku">［41］［über］jm.schlecht <u>zu sprechen sein</u>.</div>
<div class="mpage">248</div>
<div class="bango"> </div>
<div class="daimoku">［42］zu....machen 等。sich zu schaffen machen.<br />zu wissen tun</div>
<div class="mpage">250</div>
<div class="bango"> </div>
<div class="daimoku">［43］à constater que.... …して<u>は</u>、</div>
<div class="mpage">252</div>
<div class="bango"> </div>
<div class="daimoku">［44］zu不定法+mitbringen［其他］ <br />schicken</div>
<div class="mpage">252</div>
<div class="bango">32-2B</div>
<div class="daimoku">英語のto+不定法の可能範囲に関する参考</div>
<div class="mpage">253-282</div>
<div class="bango">32-3B</div>
<div class="daimoku">不定法</div>
<div class="mpage">283-403</div>
<div class="bango"> </div>
<div class="daimoku">［01］不定法のみの独立用法（<u>heißen</u>）等</div>
<div class="mpage">285</div>
<div class="bango"> </div>
<div class="daimoku">［02］定形なき時はein Rat.（命令指示）</div>
<div class="mpage">304</div>
<div class="bango"> </div>
<div class="daimoku">［03］［zuを伴ふ］不定法の名詞的用法</div>
<div class="mpage">306</div>
<div class="bango"> </div>
<div class="daimoku">［04］stehen <u>haben</u>, u.s.w.（wissenもあり）</div>
<div class="mpage">308</div>
<div class="bango"> </div>
<div class="daimoku">［05］sitzen <u>bleiben</u>. （自動詞と結合して）</div>
<div class="mpage">313</div>
<div class="bango"> </div>
<div class="daimoku">［06］似而非不定法。（名詞化の如く見ゆ）</div>
<div class="mpage">316</div>
<div class="bango"> </div>
<div class="daimoku">［07］ist....不定法</div>
<div class="mpage">317</div>
<div class="bango"> </div>
<div class="daimoku">［08］過去の不定法。（zuを伴ふ場合も）</div>
<div class="mpage">325</div>
<div class="bango"> </div>
<div class="daimoku">［09］gut....不定法....haben.（認容。）</div>
<div class="mpage">327</div>
<div class="bango"> </div>
<div class="daimoku">［10］auf ihn ist kein Verlaß.<br />（ist gut 不定法と同意）</div>
<div class="mpage">332</div>
<div class="bango"> </div>
<div class="daimoku">［11］schlafen <u>lagen</u>.（稀に<u>liegen</u>も）</div>
<div class="mpage">334</div>
<div class="bango"> </div>
<div class="daimoku">［12］aus dem <u>es</u> so leicht <u>kein Herausfinden</u> <u>gäbe</u>.<br />［es gibt, sein］否定。</div>
<div class="mpage">335</div>
<div class="bango"> </div>
<div class="daimoku">［13］jedes,allesと共に用ふる名詞用法。</div>
<div class="mpage">346</div>
<div class="bango"> </div>
<div class="daimoku">［14］schlafen <u>gehen</u>.</div>
<div class="mpage">347</div>
<div class="bango"> </div>
<div class="daimoku">［15］schlafen <u>schicken</u>.</div>
<div class="mpage">364</div>
<div class="bango"> </div>
<div class="daimoku">［16］Das ist ein Geigen und Flöten.!</div>
<div class="mpage">366</div>
<div class="bango"> </div>
<div class="daimoku">［17］疑問文の不定句。</div>
<div class="mpage">367</div>
<div class="bango"> </div>
<div class="daimoku">［18］helfen kommen（Supinisch）</div>
<div class="mpage">370</div>
<div class="bango"> </div>
<div class="daimoku">［19］Ein hartes Schicksal, <u>aufgeopfert werden</u>.</div>
<div class="mpage">377</div>
<div class="bango"> </div>
<div class="daimoku">［20］heißen 命ずる</div>
<div class="mpage">379</div>
<div class="bango"> </div>
<div class="daimoku">［21］es heißt …云々せざるべからず</div>
<div class="mpage">379</div>
<div class="bango"> </div>
<div class="daimoku">［22］führenを基部とするもの spazieren führen</div>
<div class="mpage">380</div>
<div class="bango"> </div>
<div class="daimoku">schlafen führen</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">［23］einkaufen <u>gewesen sein</u></div>
<div class="mpage">381</div>
<div class="bango"> </div>
<div class="daimoku">［24］brauchen（例外的）俗語</div>
<div class="mpage">385</div>
<div class="bango"> </div>
<div class="daimoku">［25］tun,（tät）</div>
<div class="mpage">385</div>
<div class="bango"> </div>
<div class="daimoku">［26］名詞的用法 （特に作為的なるもの）</div>
<div class="mpage">386</div>
<div class="bango"> </div>
<div class="daimoku">［27］不定句全部の名詞化。</div>
<div class="mpage">387</div>
<div class="bango"> </div>
<div class="daimoku">［28］Soldatentochter <u>und</u> <u>weinen</u> !</div>
<div class="mpage">392</div>
<div class="bango"> </div>
<div class="daimoku">［29〕疑問詞十zu不定法。（の代りにzuを省いて用ふ）</div>
<div class="mpage">400</div>
<div class="bango"> </div>
<div class="daimoku">［30］名詞化</div>
<div class="mpage">403</div>
<div class="bango"> </div>
<div class="daimoku"> </div>
<div class="mpage"> </div>
<div class="bango">32-4B</div>
<div class="daimoku">未然表現（目的表現）としての不定形（参考）</div>
<div class="mpage">404</div>
<div class="bango">32-5B</div>
<div class="daimoku">zu vermieten</div>
<div class="mpage">405</div>
<div class="bango">32-6B</div>
<div class="daimoku">挿入句的zu+Inf. à enjuger par....410-417</div>
<div class="mpage"> </div>
<div class="bango">32-7B</div>
<div class="daimoku">聞いて、 泣く、及び：「云々するに当っては」</div>
<div class="mpage">418-426</div>
<div class="bango">32-8B</div>
<div class="daimoku">sagen等とzu+Inf文</div>
<div class="mpage">427-430</div>
<div class="bango">32-9B</div>
<div class="daimoku">ACCUSAT. cum Infinitivo</div>
<div class="mpage">431-451</div>
<div class="bango">32-10B</div>
<div class="daimoku">間投的 was lieben ! （愛するところの騒ぎか）<br />絶対的 ach lieben !</div>
<div class="mpage">452</div>
<div class="bango">32-11B</div>
<div class="daimoku">zuに関する考察 zuと三格語尾=e.</div>
<div class="mpage">453-462</div>
<div class="bango">32-12B</div>
<div class="daimoku">［MHD］直接不定法</div>
<div class="mpage">463-467</div>
<div class="bango">32-13B</div>
<div class="daimoku">start ～ ing, burst ～ ing 等 開始過程其の他</div>
<div class="mpage">468-488</div>
<div class="bango">32-14B</div>
<div class="daimoku"><u>不定法直結</u> 古典語を主に、 仏をも含む。</div>
<div class="mpage">489-503</div>
<div class="bango">32-15B</div>
<div class="daimoku">Historical Infinitive</div>
<div class="mpage">504</div>
<div class="bango">32-16B</div>
<div class="daimoku">im Stande sein+ zu+Inf.</div>
<div class="mpage">505-508</div>
<div class="bango">32-17B</div>
<div class="daimoku">「…とは…」</div>
<div class="mpage">509-516</div>
<div class="bango">32-18B</div>
<div class="daimoku">zu+Inf. 主語関係の会はざるもの</div>
<div class="mpage">517-525</div>
<div class="bango">32-19B</div>
<div class="daimoku">geben + Infinit mit zu<br />［希式文法］云々すべく与える</div>
<div class="mpage">526</div>
<div class="bango">32-20B</div>
<div class="daimoku">Nicht umhin können.</div>
<div class="mpage">527-535</div>
<div class="bango">32-21R</div>
<div class="daimoku">［MHD］いったいun- の結合が多いということ！<br />挙形［絶対用法］ ”云々すること”</div>
<div class="mpage">536</div>
<div class="bango">32-22B</div>
<div class="daimoku">adnominal 関係文を用いるに同じzu +不定句</div>
<div class="mpage">537-562</div>
<div class="bango">32-23R</div>
<div class="daimoku">anfangen等とzu +不定法 －構文の問題－<br />Aufgabeの用語”云々せよ”（<u>命令法</u>に関係す）<br />DELIBERATIV<br />Ich weiß nicht <u>wo</u> anzufanngen.<br />zu +不定法をzum <u>Ankleben</u> などとすること</div>
<div class="mpage">563-565</div>
<div class="bango">32-24B</div>
<div class="daimoku">不定形名詞 Blutvergießen Entgegenkommen</div>
<div class="mpage">566-569</div>
<div class="bango">32-25B</div>
<div class="daimoku">zuを伴ふ不定句とDavon,darin等の省略、或ひは<br />Kontaminationで説明す可き結合。</div>
<div class="mpage">570-574</div>
<div class="bango">32-26B</div>
<div class="daimoku">不定句の絶対用法 das ist ： 型</div>
<div class="mpage">575</div>
<div class="bango">32-27B</div>
<div class="daimoku">云々して以て云々する</div>
<div class="mpage">576</div>
<div class="bango">32-28R</div>
<div class="daimoku">zu+ INF.のzuが仏ではdeまたはàなることに関する<br />参考事項。<br />約束話法の前提部をzu+不定句で表現し得。<br />過去の不定形<br />zu+不定形を一語に書いた時代がある。</div>
<div class="mpage">577-578</div>
<div class="bango">32-29B</div>
<div class="daimoku">Quel mal y-a-t-il à faire cela?</div>
<div class="mpage">579-584</div>
<div class="bango">32-30B</div>
<div class="daimoku"><u>mit Respekt zu melden</u>.</div>
<div class="mpage">585-587</div>
<div class="bango">32-31R</div>
<div class="daimoku">再帰勤詞の ［中性］名詞化にはsichを省く。<br />zu+ Inf. に相当するGERUNDIVUMとGERUNDIUMに就いて<br />非人称のesと、zu+ 不定句の関係及び移轍的現象<br />［初歩］zu+ 不定句には主語なし</div>
<div class="mpage">588-589</div>
<div class="bango">32-32B</div>
<div class="daimoku">WARUM Infin.?<br />WOZU<br />what's the use of ....ing ?</div>
<div class="mpage">590</div>
<div class="bango">32-33R</div>
<div class="daimoku">［仏］あいまいな結合のde+不定法
<p> </p>
<p>［仏］Je les connais de les voir tous les jours.<br />Auxiliare Formeln<br />英語のGerund<br />［仏］finir par ～<br />独のdazu beitragen, ....zu,（またはes....、....zu ～）は仏ではà（de）+ 不定形<br />zu+不定法の代りのdassの文［古］<br />編者注：このほか4件あり。</p>
</div>
<div class="mpage">591-595</div>
<div class="bango">32-34B</div>
<div class="daimoku">［英］Gerundの名詞的用法</div>
<div class="mpage">596</div>
<div class="bango">32-35B</div>
<div class="daimoku">［仏］不定法のみの用法 Autant en profiter<br />どうせ…なら…いっそ…</div>
<div class="mpage">597</div>
<div class="bango">32-36R</div>
<div class="daimoku">不定法の名詞化には殊に行事、挙動、Verrichtung<br />所作多し。<br />編者注：このほか5件あり。</div>
<div class="mpage">598-600</div>
<div class="bango">32-37B</div>
<div class="daimoku">zu+不定句と本文との融合</div>
<div class="mpage">601</div>
<div class="bango">32-38R</div>
<div class="daimoku">間投的絶対用法の不定句<br />［英］There is no use denying 等<br /><u>zu+ 不定法</u>、［参考］<br />daßが重なる時にzu+不定法。<br />zu 不定法+haben.ねばならぬ（四格無きを純<br />とす。）<br />編者注：このほか14件あり。</div>
<div class="mpage">602-611</div>
</div>