<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">34-1B</div>
<div class="daimoku">時称 過去</div>
<div class="mpage">1-51</div>
<div class="bango"> </div>
<div class="daimoku">［01］durativisch.</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">［02］Iterative Aktion. 習慣（pflegte zu ....）</div>
<div class="mpage">9</div>
<div class="bango"> </div>
<div class="daimoku">［03］immer nimmer等を伴ふ際。<br />（少し客観的に見る）</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">［04］Iterative Aktion <u>oft</u></div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">［05］過去中の未来。（<u>iturus</u> essem, usw.）</div>
<div class="mpage">18</div>
<div class="bango"> </div>
<div class="daimoku">［06］間接話法としての過去形</div>
<div class="mpage">18</div>
<div class="bango"> </div>
<div class="daimoku">［07］約束法の代り。（würde?）未来の代り</div>
<div class="mpage">22</div>
<div class="bango"> </div>
<div class="daimoku">［08］前にさう言ふ事を述べて置いた。</div>
<div class="mpage">28</div>
<div class="bango"> </div>
<div class="daimoku">［09］Das war ein Wort! ［味わった後、感じの判断<br />をロにする時に用ひる過去］</div>
<div class="mpage">31</div>
<div class="bango"> </div>
<div class="daimoku">［10］Gnomischer Aorist.（現在完了もあり）</div>
<div class="mpage">36</div>
<div class="bango"> </div>
<div class="daimoku">［11］現在完了代りに用ひるもの。</div>
<div class="mpage">43</div>
<div class="bango"> </div>
<div class="daimoku">［12］終熄的現完了に似たる用法。</div>
<div class="mpage">48</div>
<div class="bango">34-2B</div>
<div class="daimoku">時称 未未</div>
<div class="mpage">52-97</div>
<div class="bango"> </div>
<div class="daimoku">［01］普通の例（確実さの約束－－のタイプなり。）</div>
<div class="mpage">55</div>
<div class="bango"> </div>
<div class="daimoku">［02］単に推察の意。</div>
<div class="mpage">60</div>
<div class="bango"> </div>
<div class="daimoku">［03］例証的想像（sagen....wir....）一般的宣言<br />wirt so tun....wenn der Fall wirklich eintritt.</div>
<div class="mpage">64</div>
<div class="bango"> </div>
<div class="daimoku">［04］命令法的用法</div>
<div class="mpage">80</div>
<div class="bango"> </div>
<div class="daimoku">［05］現在形で表現。（殊にwenn-）</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">［06］決心の表現（<u>きっぱり</u>と） 予言</div>
<div class="mpage">85</div>
<div class="bango"> </div>
<div class="daimoku">［07］勿論…だらうね？</div>
<div class="mpage">90</div>
<div class="bango"> </div>
<div class="daimoku">［08］wennの場合</div>
<div class="mpage">91</div>
<div class="bango"> </div>
<div class="daimoku">［09］如何にも<u>未来</u>らしき時に用ふ（ausdrücklicher<br />Zukunft begriff）</div>
<div class="mpage">92</div>
<div class="bango"> </div>
<div class="daimoku">［10］sollenと同じ、（自己の決心決菅をいふ）<br />仏は必ず未来</div>
<div class="mpage">93</div>
<div class="bango"> </div>
<div class="daimoku">［11］Konjunctivus Diplomaticusと殆ど同じ用法。</div>
<div class="mpage">94</div>
<div class="bango"> </div>
<div class="daimoku">［12］<u>sollte</u>と同じ用法</div>
<div class="mpage">95</div>
<div class="bango"> </div>
<div class="daimoku">［13］未来時称に不定形はないか挙形としては可能：</div>
<div class="mpage">95</div>
<div class="bango"> </div>
<div class="daimoku">［14］反問のII.Kと同じもの。疑問詞とと共に。<br />（別に間投詞には非ざるもの）</div>
<div class="mpage">97</div>
<div class="bango">34-3B</div>
<div class="daimoku">編者注：本袋「34-3B」内は二つの<br />ノート・ブックに整理されている</div>
<div class="mpage">98-125</div>
<div class="bango"> </div>
<div class="daimoku">ので、これを記号①、②で示すこ<br />とにした。</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">扮役的直接法</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">①［01］Nesthäkchen und der Weltkrieg</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">①［02］<u>現在時称</u>の場合<br />（会話文に多し、嘸ぞ…でしょうよ、など）</div>
<div class="mpage">110</div>
<div class="bango"> </div>
<div class="daimoku">①［03］<u>Praesens mimicum</u></div>
<div class="mpage">113</div>
<div class="bango"> </div>
<div class="daimoku">①［04］副文章内に現れる（関係文が主）ものにして、<br />元来は接続法たる可きものが、扮役の意味<br />で直接法の過去になるもの。</div>
<div class="mpage">115</div>
<div class="bango"> </div>
<div class="daimoku">①［05］一語が扮役的なるもの。</div>
<div class="mpage">115</div>
<div class="bango"> </div>
<div class="daimoku">①［06］間接話法の独立用法（そのまま直接法過去に<br />すればMimicusになる）<br />欺瞞的直接法 ［Indicativus hypocriticus］<br />wollen,sollenの問題に関係す。（”であった<br />事にしてしてしまふ等。）</div>
<div class="mpage">116</div>
<div class="bango"> </div>
<div class="daimoku">②［01］</div>
<div class="mpage">118</div>
<div class="bango"> </div>
<div class="daimoku">②［02］［仏］間接話法の独立文化と同意のもの</div>
<div class="mpage">124</div>
<div class="bango">34-4B</div>
<div class="daimoku">時称 現在完了</div>
<div class="mpage">126-214</div>
<div class="bango"> </div>
<div class="daimoku">［01］niemals, immerを伴ふ場合。（過去総体を一括<br />して）</div>
<div class="mpage">129</div>
<div class="bango"> </div>
<div class="daimoku">［02］…した「のである」（言者の判断）</div>
<div class="mpage">138</div>
<div class="bango"> </div>
<div class="daimoku">［03］jeを伴ふ場合</div>
<div class="mpage">145</div>
<div class="bango"> </div>
<div class="daimoku">［04］現在そのものを指す。</div>
<div class="mpage">146</div>
<div class="bango"> </div>
<div class="daimoku">［05］過去を偲ぶ現在完了。［einst］</div>
<div class="mpage">157</div>
<div class="bango"> </div>
<div class="daimoku">［06］「しまふ」とは譯せない。今までずっと<br />働いていて、その影響が現在も残っている。<br />（statische Aktionの動詞）</div>
<div class="mpage">161</div>
<div class="bango"> </div>
<div class="daimoku">［07］「結果が現在に残る」といふ例。</div>
<div class="mpage">162</div>
<div class="bango"> </div>
<div class="daimoku">［08］結果が現在に残る、他の例。<br />－した経験をもっている。－</div>
<div class="mpage">165</div>
<div class="bango"> </div>
<div class="daimoku">［09］一般的に「…の例がある」と普遍化して言ふ際</div>
<div class="mpage">165</div>
<div class="bango"> </div>
<div class="daimoku">［10］現在完了、又は過去完了、未来完了に代り得る<br />Durativa.</div>
<div class="mpage">166</div>
<div class="bango"> </div>
<div class="daimoku">［11］bis, sobaldは好んで「完了。」（状態）</div>
<div class="mpage">167</div>
<div class="bango"> </div>
<div class="daimoku">［12］habenを用ふることの説明。</div>
<div class="mpage">173</div>
<div class="bango"> </div>
<div class="daimoku">［13］終熄の現在完了</div>
<div class="mpage">175</div>
<div class="bango"> </div>
<div class="daimoku">［14］…云々であった事にしてしまふ。</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">［15］現在を使っても同じになる。<br />ist geblieben, hat sich erhalten.</div>
<div class="mpage">193</div>
<div class="bango"> </div>
<div class="daimoku">［16］habenのみと同意になる（過去分詞を除いても<br />同じ）</div>
<div class="mpage">199</div>
<div class="bango"> </div>
<div class="daimoku">［17］seinと同意になる。（er <u>ist</u> um die Ecke等と関係して）</div>
<div class="mpage">200</div>
<div class="bango"> </div>
<div class="daimoku">［18］jetzt等と共に。（しまっている）（しまった）</div>
<div class="mpage">201</div>
<div class="bango"> </div>
<div class="daimoku">［19］Gern geschehen! Ist bald gesagt!</div>
<div class="mpage">202</div>
<div class="bango"> </div>
<div class="daimoku">［20］seitの際は？ <u>状態詞</u>は現在<br />動作詞は完了</div>
<div class="mpage">207</div>
<div class="bango"> </div>
<div class="daimoku">［21］未来完了の代りに（確認的現完に近きものあり）</div>
<div class="mpage">208</div>
<div class="bango"> </div>
<div class="daimoku">［22］Gnomischer Aorist. 過去もあり。</div>
<div class="mpage">210</div>
<div class="bango">34-5B</div>
<div class="daimoku">時称 過去完了</div>
<div class="mpage">215-249</div>
<div class="bango"> </div>
<div class="daimoku">［01］例。（過去たる事の一目瞭然たる）</div>
<div class="mpage">216</div>
<div class="bango"> </div>
<div class="daimoku">［02］過去の或瞬問に於ける「状態」を指す。</div>
<div class="mpage">226</div>
<div class="bango"> </div>
<div class="daimoku">［03］Nachdem.</div>
<div class="mpage">227</div>
<div class="bango"> </div>
<div class="daimoku">［04］hatteの説明に。（持っていた）</div>
<div class="mpage">228</div>
<div class="bango"> </div>
<div class="daimoku">［05］終煌（nicht mehr!）</div>
<div class="mpage">228</div>
<div class="bango"> </div>
<div class="daimoku">［06］迅速さを示す完了形（又はStativa）</div>
<div class="mpage">229</div>
<div class="bango"> </div>
<div class="daimoku">［07］alsと過去完了。</div>
<div class="mpage">231</div>
<div class="bango"> </div>
<div class="daimoku">［08］現在・對・過去完了</div>
<div class="mpage">231</div>
<div class="bango"> </div>
<div class="daimoku">［09］時問を飛ばして状態に移るもの。</div>
<div class="mpage">237</div>
<div class="bango"> </div>
<div class="daimoku">［10］kaum型意型（als....）</div>
<div class="mpage">237</div>
<div class="bango"> </div>
<div class="daimoku">［11］云々しつつあった。／<u>していた</u>。</div>
<div class="mpage">238</div>
<div class="bango">34-6R</div>
<div class="daimoku">直前過去 ［仏］venir d'arriver<br />［西］acabar de llegar<br />逼迫的未来 FUTURUM IMMINENS</div>
<div class="mpage">250-254</div>
<div class="bango">34-7B</div>
<div class="daimoku">時称 現在</div>
<div class="mpage">255-295</div>
<div class="bango"> </div>
<div class="daimoku">［01］一般宣告の現在。</div>
<div class="mpage">256</div>
<div class="bango"> </div>
<div class="daimoku">［02］進行形現在。</div>
<div class="mpage">257</div>
<div class="bango"> </div>
<div class="daimoku">［03］未来代りの現在。</div>
<div class="mpage">259</div>
<div class="bango"> </div>
<div class="daimoku">［04］要求的現在（現在とは限らず、完了）</div>
<div class="mpage">262</div>
<div class="bango"> </div>
<div class="daimoku">［05］現完的。ich komme! （未来的）<br />da kommt er!</div>
<div class="mpage">263</div>
<div class="bango"> </div>
<div class="daimoku">［06］Historisches Präsens. ［Narrativisch］</div>
<div class="mpage">281</div>
<div class="bango"> </div>
<div class="daimoku">［07］将に云々せんとする。（er stirbt!）</div>
<div class="mpage">282</div>
<div class="bango"> </div>
<div class="daimoku">［08］所謂Historisches Präsensは、或種の出来事の<br />系列を一完した劇的局面としてまとめて描<br />出して相手の全体的把握に訴へるときにも<br />用ひる。（sich davon ein Bild machen）</div>
<div class="mpage">283</div>
<div class="bango"> </div>
<div class="daimoku">［09］未来のことを取極める際の相談。（叙述的）</div>
<div class="mpage">288</div>
<div class="bango"> </div>
<div class="daimoku">［10］We <u>have been</u> married now for a year.</div>
<div class="mpage">289</div>
<div class="bango"> </div>
<div class="daimoku">［11］直前過去：Il me vient une idée.</div>
<div class="mpage">295</div>
<div class="bango">34-8B</div>
<div class="daimoku">過去完了<br />物語調の現完<br />通俗調の Perfectum historikum<br />過去の代り（Erzählungsstil） 俗調</div>
<div class="mpage">296-303</div>
<div class="bango">34-9R</div>
<div class="daimoku">［MHD］完了形（殊に助動詞）は単に過去で<br />［MHD］の未来形</div>
<div class="mpage">304-307</div>
<div class="bango">34-10B</div>
<div class="daimoku">時称 未来完了</div>
<div class="mpage">308-317</div>
<div class="bango"> </div>
<div class="daimoku">［01］例</div>
<div class="mpage">309</div>
<div class="bango"> </div>
<div class="daimoku">［02］現在完了を以て代ふ。</div>
<div class="mpage">313</div>
<div class="bango"> </div>
<div class="daimoku">［03］想像のwerden.</div>
<div class="mpage">315</div>
<div class="bango"> </div>
<div class="daimoku">［04］単なる未来と同じになる。</div>
<div class="mpage">316</div>
<div class="bango"> </div>
<div class="daimoku">［05］werdenの「確言的用法」にあたるもの。</div>
<div class="mpage">316</div>
<div class="bango"> </div>
<div class="daimoku">［06］antizipierend</div>
<div class="mpage">317</div>
<div class="bango"> </div>
<div class="daimoku">［07］wemの場合はwerdenを省く</div>
<div class="mpage">317</div>
<div class="bango">34-11B</div>
<div class="daimoku">現在完了の重要形態：－云々している－</div>
<div class="mpage">318</div>
<div class="bango">34-12B</div>
<div class="daimoku">Er ist um die Ecke等</div>
<div class="mpage">319-324</div>
<div class="bango">34-13B</div>
<div class="daimoku">Konstatieren der Aorist</div>
<div class="mpage">325</div>
<div class="bango">34-14B</div>
<div class="daimoku">現在完了 「云々していた」 「云々しつつあった」</div>
<div class="mpage">326-330</div>
<div class="bango">34-15B</div>
<div class="daimoku">未来表現</div>
<div class="mpage">331</div>
<div class="bango">34-16B</div>
<div class="daimoku">英語の現在完了</div>
<div class="mpage">332-334</div>
<div class="bango">34-17B</div>
<div class="daimoku">［仏］venir de 時称 －直前過去－</div>
<div class="mpage">335</div>
<div class="bango">34-18B</div>
<div class="daimoku">現在・未来と対照する過去対称</div>
<div class="mpage">336-341</div>
<div class="bango">34-19B</div>
<div class="daimoku">現完PARADIGMA集</div>
<div class="mpage">342-345</div>
<div class="bango">34-20B</div>
<div class="daimoku">［羅］書簡で過去形 <u>Perfectum</u></div>
<div class="mpage">346</div>
<div class="bango">34-21B</div>
<div class="daimoku">完了形助動詞habenにっいての参考</div>
<div class="mpage">347</div>
<div class="bango">34-22B</div>
<div class="daimoku">たとえ現在時称文肢でも、過去の出来事を一つ抽出し<br />て報告する時（英は過去）</div>
<div class="mpage">348-349</div>
<div class="bango">34-23R</div>
<div class="daimoku">現完の意局果たすべき義務としての行為が問題にな<br />る場合<br />希羅のPerfectumと <u>Präterio-Praesentia的意型</u><br />英の現在完了と過去副詞との関係</div>
<div class="mpage">350-351</div>
<div class="bango">34-24B</div>
<div class="daimoku">完了形の不定法 （総括的）</div>
<div class="mpage">352-353</div>
<div class="bango">34-25B</div>
<div class="daimoku">真に現在に至って完成したもの</div>
<div class="mpage">354</div>
<div class="bango">34-26R</div>
<div class="daimoku">独では現完・英では過去<br />脚本卜ガキ中の過去に遡る時の現在完了<br />［仏］<u>Passé antéreur</u><br />［仏］Passé définiとPassé indéfini</div>
<div class="mpage">355-364</div>
<div class="bango"> </div>
<div class="daimoku">編者注：このほか13件あり。</div>
<div class="mpage"> </div>
<div class="bango">34-27B</div>
<div class="daimoku">Stativa（lieben, hassen等）の代りに完了形を用ふる<br />熟語</div>
<div class="mpage">365</div>
<div class="bango">34-28R</div>
<div class="daimoku">簡潔ならんがための過去の自由な用法。<br />過去時称（<u>Einmaligkeit</u>の強調）<br />Ohne....zu haben<br />受勤状態の完了形（後傾性）<br />wir sind gefangen !<br />現在完了でも過去でも好い際<br />過去 gehalt haben と過去分詞。<br />gewessen sein<br />云々していたことがあった。<br /><u>現在完了</u>。<br />［芝居のAnweisungに於て、現在形の文脈中に<br />現れる場合。<br />完了形の説明。（日本語）<br />僕はくたびれ<u>た</u>。 ich bin müde.<br />Davon, habe ich nichts gehört.</div>
<div class="mpage">366-369</div>
</div>