<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">36-1B</div>
<div class="daimoku">固有名詞でもあり普通名詞でもあり</div>
<div class="mpage">1</div>
<div class="bango">36-2B</div>
<div class="daimoku">編者注：本袋「36-2B」内はノート<br />ブック型のもの「［01］…［17］」と<br />単に資料番号で整理されているもの<br />「（18）…（20）」とがある。
<p> </p>
<p>廣い意味のSubjekt=Prädikativ関イ系を表現する動詞<br />廣い意味のKopula<br />Sätze, die ein <u>Subjekt=Prädikativ=Verhältnis</u><br />einschließen</p>
</div>
<div class="mpage">2-61</div>
<div class="bango"> </div>
<div class="daimoku">［01］<u>sein</u>と名詞、形容詞、分詞</div>
<div class="mpage">4</div>
<div class="bango"> </div>
<div class="daimoku">［02］bielbenと名詞、形容詞、分詞…のまま</div>
<div class="mpage">4</div>
<div class="bango"> </div>
<div class="daimoku">［03］<u>werden</u>と名詞、形容詞、分詞。<br />'［英］to turn pale ［仏］tourner à ～</div>
<div class="mpage">5</div>
<div class="bango"> </div>
<div class="daimoku">［04］heißenと名詞、及び動詞其他。</div>
<div class="mpage">8</div>
<div class="bango"> </div>
<div class="daimoku">［05］<u>nennen</u>. findenもあり （四格二個）</div>
<div class="mpage">8</div>
<div class="bango"> </div>
<div class="daimoku">［06］zu seinの省略（scheinen等）</div>
<div class="mpage">9</div>
<div class="bango"> </div>
<div class="daimoku">［07］<u>als</u>を用ひるもの。</div>
<div class="mpage">9</div>
<div class="bango"> </div>
<div class="daimoku">［08］scheinen, vorkommen等と</div>
<div class="mpage">11</div>
<div class="bango"> </div>
<div class="daimoku">［09］stehen, kopulativsatz.</div>
<div class="mpage">15</div>
<div class="bango"> </div>
<div class="daimoku">［10］liegen, sitzen, hängen, 其の他<br />［英］This area lies <u>unused</u>.</div>
<div class="mpage">19</div>
<div class="bango"> </div>
<div class="daimoku">［11］dünken.（名詞一格）</div>
<div class="mpage">24</div>
<div class="bango"> </div>
<div class="daimoku">［12］［英］come, prove等。</div>
<div class="mpage">25</div>
<div class="bango"> </div>
<div class="daimoku">［13］sein, werden, の Periphrase.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">［14］se trouver....<br />［仏］ mon fauteuil <u>se trouve</u> <u>occupé</u>.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">［15］<u>存在</u>を意味する<u>sein</u>（Kopulaと区別するために：</div>
<div class="mpage">27</div>
<div class="bango"> </div>
<div class="daimoku">［16］schwer <u>fallen</u>.（<u>halten</u>）</div>
<div class="mpage">27</div>
<div class="bango"> </div>
<div class="daimoku">［17］ausfallen,geraten,等。</div>
<div class="mpage">28</div>
<div class="bango"> </div>
<div class="daimoku">（18）bleiben［…の侭になってしまう］</div>
<div class="mpage">30</div>
<div class="bango"> </div>
<div class="daimoku">（19）述語形容詞支配の動詞 K0PULATIV</div>
<div class="mpage">32</div>
<div class="bango"> </div>
<div class="daimoku">（20）［希］<u>υπαρχειν</u><br />［仏］demeurer d'accord<br />［英］continue to be<br />編者注：このほか30件あり。</div>
<div class="mpage"> </div>
<div class="bango">36-3B</div>
<div class="daimoku">再帰動詞の際に起る「格」の問題</div>
<div class="mpage">62-68</div>
<div class="bango">36-4B</div>
<div class="daimoku">主語の補足的述語としてのalle, beide, （sämtliche）<br />（das ist alles....など）</div>
<div class="mpage">69</div>
<div class="bango">36-5B</div>
<div class="daimoku">［形容詞］述語支配の動詞<br />den Preis zu hoch <u>nehmen</u>等</div>
<div class="mpage">70-74</div>
<div class="bango">36-6B</div>
<div class="daimoku">［西］estavとser</div>
<div class="mpage">75-76</div>
<div class="bango">36-7B</div>
<div class="daimoku">名詞述語一般の観點</div>
<div class="mpage">77-79</div>
<div class="bango">36-8B</div>
<div class="daimoku">述語の間接表現</div>
<div class="mpage">80-99</div>
<div class="bango">36-9B</div>
<div class="daimoku">［エ］....estas neces<u>e</u>について</div>
<div class="mpage">100</div>
<div class="bango">36-10B</div>
<div class="daimoku">Kopulaの省略</div>
<div class="mpage">101-103</div>
<div class="bango">36-11B</div>
<div class="daimoku">述語 NoMENKLATUR</div>
<div class="mpage">104-105</div>
<div class="bango">36-12R</div>
<div class="daimoku">述語「名詞」を比較的形態の形容詞様に用いることは<br />不可、但し ～ genug, umは例外：<br />～ gehenによる表現<br />「を」と「と」の判別困難なること多し<br />編者注：このほか4件あり。</div>
<div class="mpage">106-111</div>
<div class="bango">36-13B</div>
<div class="daimoku">「を」－「と」型に<u>不定形代に分詞</u></div>
<div class="mpage">112-115</div>
<div class="bango">36-14R</div>
<div class="daimoku">一格述語（dünken, scheinen, usw.）<br />das <u>hält</u> schwer. das <u>fällt</u> schwer.<br />das <u>wirt mir</u> schwer. das <u>läßt</u> häßlich.<br />das <u>kommt</u> so vor.<br />「述語」なる概念を必要とする諸種の込み入った場合<br />主語対述語の一つの問題</div>
<div class="mpage">116-128</div>
<div class="bango">36-15B</div>
<div class="daimoku">Wenn ich <u>dich</u> wäre.</div>
<div class="mpage">118</div>
<div class="bango">36-16R</div>
<div class="daimoku">als（…としての）（述語表現）<br />Flachsmann als Erzieher.<br /><u>前置詞つき述語</u>の本質を明らかにする一型<br />（構造の如何に拘らず述語的意味形態）<br />il est <u>de mon devoir</u> de....<br />これを<br />Je crois de mon devoir de....<br />と言っても同じ。<br />念を入れるための関代述語句<br />A L'heure qu(il est型<br />初歩用（述語論） Ich bin nicht zimperlich.
<p> </p>
<p>編者注：このほか11件あり。</p>
</div>
<div class="mpage">119-128</div>
</div>