document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0006.gif" class="luminous"><img src="../../img/001/s0006.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<h2>Noun treated as proper noun, without article!</h2>');
document.write('﻿<ol><li>(Präsidents) Aber der größe Teil det Conversation am andern Ende des Tisches galt <u>Präsidents</u> Ida. (Hauff: Der Mann im Monde I)</li>');
document.write('<li>Das wohl, Ich mag alle Tiere leiden, obgleich <u>Tante</u> mirs nicht glauben will. <u>Tantes</u> Hunde sind ein bißchen ungeyogen und dann -<br>(L. Westkirch: Aus dem Hexenkessel der Zeit)</li>');
document.write('<li><u>Mutters</u> Bargeld ist immer knapp.<br>(%) <u>Vater</u> lag es viel daran, dass wir rechtzeitig zum Frühstück herunterkamen.</li></ol>');
document.write('<div style="width:5em;border:solid 1px #000;text-align:center;float:left;">English</div><ol start="4" style="width:90%;float:left;"><li>When Father died in 1910 Mother was left with practically no money and us five children.<br>(RERalph Moody: Man of the Family)</li></ol>');
document.write('<ol start="5" style="clear:both;">');
document.write('<li><u>Mutters</u> Geburstsag. (DUDEN)</li>');
document.write('<li>ruf mal Mutter(n)l (DUDEN)</li>');
document.write('<li>Unter neuen Hurrahs entführte der Zug den hohen Durchreisenden, und wir hatten <u>Geschichte</u> gesehen. (Th. Mann. Meine Zeit)<br>Story which one saw Wilhelm der Erste in Lübeck<br />p. (9)');
document.write('<li>FRITZ: Gibbt der <u>Großvatern</u> viel Geld?<br>(Die Weber, II)</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');