document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0008.gif" class="luminous"><img src="../../img/001/s0008.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>[3] Case inflection of Unter den Linden</p>');
document.write('<ol><li>Wollen wir nachmittags Unter den Linden gehen? (IV)</li>');
document.write('<li>Er geht Unter den Linden spazieren. (III)</li>');
document.write('<li>Ausserdem wurde eine neue  Straßen: und Lau***** der **** zwischen den Linden und der ********** ********* (Z. 1939)</li></ol>');
document.write('<p><u>Ein</u> <u>gewisser</u> Herr ～</p>');
document.write('<div style="width:4em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">Italian</div> <p> Son vainguer fut <u>un nommé</u> Pierre Daval</p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');