document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0001.gif" class="luminous"><img src="../../img/001/s0001.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<h2>At once proper noun and normal noun:</h2>');
document.write('<ol>');
document.write('<li>Name of Plain (geometry) →</li>');
document.write('<li>Name of Emperor</li>');
document.write('<li>Name of Wind</li>');
document.write('<li>Name of People</li>');
document.write('</ol>');
document.write('<h2 style="margin-top: 2em;">Plain</h2>');
document.write('<p>Die Pampas. Die Llianos. Die Steppe. Tundra, -en. Wüste,</p>');
document.write('<ol>');
document.write('<li>Die Gauchos reiten tagelang über die <u>Llianos</u>.<br>The plain located in the northern part of the Amazon</li>');
document.write('</ol>');
document.write('<p>[yanos] (mid.)<br>[janos] (south)<br>[lyanos] (north)</p><br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');