document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0013.gif" class="luminous"><img src="../../img/001/s0013.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>=er</p>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">NB</div>');
document.write('<p>In case of Country\'s name, does Schweiz only become -er?</p>');
document.write('<ol>');
document.write('<li>Die <u>Schweizer</u> Mount-Everst-Expedition 1952.</li>');
document.write('<li>=er of residents is in other paper.</li>');
document.write('</ol>');
document.write('<div style="width:3em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">Eng.</div>');
document.write('<p>America → America<u>n</u></p>');
document.write('<ol>');
document.write('<li>The <u>Incan</u> empire. (Inca, South America)</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');