document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0019.gif" class="luminous"><img src="../../img/001/s0019.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿=sche [1]<br><br><br>');
document.write('<u>Basedowsche</u> Krankheit.<br><br>');
document.write('Plancksche Konstante. Planck constant (h)<br><br>');
document.write('Rydbergsche Konstante. Rydberg constant<br><br>');
document.write('R 109,677.69<br>');
document.write('1/λ = R(1/2<sup>2</sup>-1/n<sup>2</sup>)<br><br>');
document.write('Avogadrosches Gesetz. Avogadro\'s law<br><br>');
document.write('Loschmidtsche Zahl<br>');
document.write('(od. Avogadrosche Zahl)<br><br>');
document.write('Dumassches Verfahren.<br><br>');
document.write('Paulisches Ausschlließungsprinzip (Pauli exclusion principle)<br><br>');
document.write('<div style="float:left;width:50%;border:#000 solid 1px;">');
document.write('*Zeemaneffekt Z eeman effect<br>');
document.write('Ramaneffekt.  Raman scattering (Indian)<br>');
document.write('Balmerserie  Balmer series (of atom spectrum)<br>');
document.write('Lymanserie Lyman series (of atom spectrum)<br>');
document.write('Paschenserie  Paschen series (of atom spectrum)<br>');
document.write('Röntgenstrahlen.');
document.write('</div>');
document.write('<div style="float:left;width:50%;border:#000 solid 1px;">');
document.write('Nipkowscheik</div>');
document.write('<p style="clear:both;">');
document.write('Brownsche Molekular bewegung.<br>');
document.write('Halleyscher Komet<br>');
document.write('Lindemannsche Farmel<br>');
document.write('Fraunhofersche Linien<br>');
document.write('Faradaysche Gesetze<br>');
document.write('Kirchhoffsches Gesetz<br>');
document.write('Daltonsches Gesetz<br>');
document.write('Huygenssches Prinzip<br>');
document.write('Die Mendelschen Vererbungsgesetze<br>');
document.write('Dopplens Prinzip<br>');
document.write('Torricellis Vakuum<br>');
document.write('Gay-Lussacs Gesetz<br>');
document.write('Kepplers Gesetz');
document.write('</p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');