document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0011.gif" class="luminous"><img src="../../img/001/s0011.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>Berlin=er (2)</p>');
document.write('<p>Verlängerter Weihnachtsurlaub</p>');
document.write('<p>Bonn, 27. Dezember (UP). Der Bundeskanyler wird voraussichtlich erst nach Neujahr seine Amtsgeschäfte im <u>Bonner</u> Palais Schaumburg wiederaufnehmen. Wie am Dienstag aus Regierungskreisen mitgeteilt wurde, will sich der Bundeskanzler bis dahin in seinem <u>Rhöndorfer</u> Heim im Familienkreise noch einige Tage der Ruhe gönnen.</p>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">NB</div> <p>Officially written as schweizerisch,<br>');
document.write('Schweizer is unofficial.</p>');
document.write('<ol start="7">');
document.write('<li>der schweizerische Botschafter<br>');
document.write('(nicht: der Schweizer Botschafter)<br>');
document.write('aber:<br>');
document.write('der Schweizer Käse. Schweizer Kühe.<br>');
document.write('<u>Schweizerdeutsch</u>. Schweizerland. Schweizerhäuschen.</li>');
document.write('<li>Sófià (Capital of Bulgarien)<br>');
document.write('written as sofiater</li>');
document.write('<li>Kandia = (Kreta)<br>');
document.write('Kandiote, Kandi<u>a</u>t)<br>');
document.write('Kandiater');
document.write('</li></ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');