document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0016.gif" class="luminous"><img src="../../img/001/s0016.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<div style="margin-bottom:2em;">Venedig: Venezianisch<br>');
document.write('Florenz: florentinisch<br>');
document.write('Ferrara: ferraresisch<br>');
document.write('Genua: genuesisch<br>');
document.write('Urbino: urbinatisch<br>');
document.write('Mantua<br>');
document.write('Mailand: mailändisch,<br>');
document.write('Napoli: neapolitanisch<br>');
document.write('Sorrento: sorrentinisch?<br>');
document.write('Byzant: byzantinisch.</div>');
document.write('<div style="width:25%;float:left;">');
document.write('Lothringen, -er<br>');
document.write('Erlangn, -er<br>');
document.write('Thüringen, -er<br>');
document.write('Göttingen, -er<br>');
document.write('Zähringen<br>');
document.write('Thübingen<br>');
document.write('Gissingen<br>');
document.write('Meiningen<br>');
document.write('gröningen<br>');
document.write('Sikkingen</div>');
document.write('<div style="width:25%;float:left;">');
document.write('Leiden<br>');
document.write('Bremen<br>');
document.write('Posen<br>');
document.write('Emden<br>');
document.write('Baden<br>');
document.write('Friedrichshafen<br>');
document.write('Rügen<br>');
document.write('Nordhausen<br>');
document.write('Mühlhausen<br>');
document.write('Antwerpen<br>');
document.write('Essen<br>');
document.write('München<br>');
document.write('Pilsen<br>');
document.write('Bergen<br>');
document.write('Dresden<br>');
document.write('Westfalen<br>');
document.write('Böhmen<br>');
document.write('Lithhauen<br>');
document.write('Nauen<br>');
document.write('Hagen<br>');
document.write('Preußen<br>');
document.write('Sachsen<br>');
document.write('Schwaben<br>');
document.write('Bayern<br>');
document.write('Aegypten<br>');
document.write('Franken<br>');
document.write('Pommern*</div>');
document.write('<div style="width:25%;float:left;">');
document.write('Lessing<br>');
document.write('Brüning<br>');
document.write('Hamerling<br>');
document.write('Nassau<br>');
document.write('Spandau<br>');
document.write('Torgau<br>');
document.write('Gronau<br>');
document.write('Breslau<br>');
document.write('Krakau<br>');
document.write('Moskau<br>');
document.write('Warschau</div>');
document.write('<p style="clear:both;"></p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');