document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0018.gif" class="luminous"><img src="../../img/001/s0018.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<div style="width:4em;border:solid 1px #000;text-align:center;margin-right:1em;">French</div><br>');
document.write('<ol><li>Il a recansé scrupuleusement les épithètes <u>baudelqiriennes</u>. Le Fig. 1.)</li>');
document.write('<li>hogolien: théâtre romantique <u>hugolien</u>.</li>');
document.write('<li>régime <u>hitlérien</u>.</li>');
document.write('<li>sartrien</li>');
document.write('<li>wagnérien.</li>');
document.write('<li>Les romans <u>balzaciens</u></li>');
document.write('<li>les guerres napoléoniennes.<br>');
document.write('die napoleonischen Kriege.</li>');
document.write('<li>Il y a un dosage <u>shakespearien</u> de la farce et de la comédie poét1que que je crois bien difficile à retrouver. (Le Fig. litt)</li>');
document.write('<li>La biologie soviétique (ou <u>mitchourinienne</u>) rejette les conceptions <u>mendél1ennes</u>.<br>');
document.write('Théor1es de M1tchourin et de Olga Lepechinskala)</li>');
document.write('<li>L\'habituel music—hall <u>hollywoodien</u>.</li>');
document.write('<li>conforme aux règles <u>mendéliennes</u>,');
document.write('</li></ol>');
document.write('<p style="clear:both;"></p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');