document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0024.gif" class="luminous"><img src="../../img/001/s0024.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>Neither s of genitive<br>');
document.write('nor plural, it comes from =<u>sche</u>.</p><br><br>');
document.write('ski<br>');
document.write('(WeibsenMannsen)<br>');
document.write('Goebbels.<br>');
document.write('Sanders.<br>');
document.write('Jaspers.<br>');
document.write('Engels.<br>');
document.write('Brahms<br>');
document.write('Brandes<br>');
document.write('Nielsen,<br>');
document.write('Andersen,<br>');
document.write('Jakobson<br>');
document.write('Medelssohn<br>');
document.write('Frenssen.<br>');
document.write('Siemens<br>');
document.write('Dickens<br>');
document.write('Rubens<br>');
document.write('*Magnussen<br>');
document.write('Paulsen<br>');
document.write('Petersen<br>');
document.write('Mattisson<br>');
document.write('Nelson<br>');
document.write('Wilson<br>');
document.write('Jackson<br>');
document.write('Edison<br>');
document.write('Nansen<br>');
document.write('Ibsen<br>');
document.write('Bergson<br>');
document.write('Siebs<br>');
document.write('Löns?<br>');
document.write('Adison<br><br>');
document.write('Emil Jannings.<br>');
document.write('Engels<br>');
document.write('Thorwaldsen?<br>');
document.write('Brandes<br>');
document.write('Mathisson<br>');
document.write('Niels<br>');
document.write('Lipps<br>');
document.write('Diercksen<br>');
document.write('Brahms (Brahm)<br>');
document.write('Kackensen<br>');
document.write('*Sunjatsen!<br><br>');
document.write('Johnson<br>');
document.write('Nelson<br>');
document.write('Wilson<br>');
document.write('Robinson<br>');
document.write('(Jespersen)<br>');
document.write('Jackson)<br>');
document.write('Tomson<br>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');