document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0022.gif" class="luminous"><img src="../../img/001/s0022.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>N. B. There is a problem of definite article the.</p>');
document.write('<div style="width:4em;text-align:center;border:#000 solid 1px;">English</div>');
document.write('<ol start="21">');
document.write('<li>Do you know tha Petersons?</li>');
document.write('<li>The <u>Prices</u>? No. I don\'t believe I do. You don\'t mean <u>the Pearsons</u>?<br />');
document.write('No, I don\'t know <u>tha Pearsons</u>.</li>');
document.write('</ol>');
document.write('<p>N. B. There is also die -schen (dialect)</p>');
document.write('<ol start="23">');
document.write('<li>Das meinten die Neumayerschen wohl  selber.<br />(Anzeng uber, Zu fromm)/li>');
document.write('<li>Acht <u>Tags später</u><br /> schaut nur die Neumayerschen an, die beten doch ihr schön Teil tagüber, aber ...(i)</li>');
document.write('<li>Die Neumeyerschen blickten von der Arbeit auf und grüßten. (i)</li>');
document.write('</ol>');
document.write('<p>26.<br />');
document.write('This is a man and wife, der Neumayer und die Neumayer<u>in</u>.</p>');
document.write('<div style="float:left;width:4em;text-align:center;border:#000 solid 1px;margin-right:1em;">French</div>without -s<br />');
document.write('<ol start="27" style="clear:both;">');
document.write('<li>Etienne ne croyait à rien. Il était le seul <u>des Montenoy</u> qui refusât d\'aller à la messe, (Maurice Dekobra: La pavane des poisons)</li>');
document.write('</ol>');
document.write('<p>When we indicates a one who announces the name not by "clan" but by "family",  we use both with =S or without =S.</p>');
document.write('<ol><li>');
document.write('In Urach war eine Leinwandkompanie, die der Familie Schertlin gehörte. <u>Die Schentlin</u> (this would be <u>Schertlins</u>)  hatten unter Herzog Eberhard Ludwig klein angefangen, jetzt waren sie weit im Land verzweigt. (F. Jud Süß)');
document.write('</li></ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');