document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0027.gif" class="luminous"><img src="../../img/001/s0027.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<p>Dativ -n, =en</p>');
document.write('<ol>');
document.write('<li><u>Junonen</u> ähnlich, <u>Ledan</u>, <u>Helenen</u>, / ');
document.write('Wie majestätisch lieblich mir\'s im Auge schwankt! (Faust II Teil. IV)</li>');
document.write('<li>LA ROQUETTE: Und alles das hast du <u>Molièren</u> erzählt -<br>');
document.write('MADELEINE: Ich? <u>Molièren</u>? (G. Das Urb. d. Tartüffe. IV. 2)<br>But:<br>Kommen Sie <u>zu Molière</u>‚ um sich unter die königlichen Schauspieler aufnehmen zu lassen? (ib. )</li>');
document.write('<p style="clear:both;">it is not someone\'s name, but sword\'s name</p>');
document.write('<div style="border:solid 1px #000; width:4em;text-align:center;float:left;margin-right:2em;">Special</div>');
document.write('<li>Nach <u>Durandaln</u> ist euch. bei meinem Rittereid. Kein Schwert, das d e m glich\' in der Christenheit. (Johann Alxinger, geb. 1755. Doolin)</li>');
document.write('<li>Um: zu beurteilen, inwiefern dieses <u>Winckelmannen</u> gelungen, liegen der Dokumente nunmehr genugsam vor uns. (Goethe: "Winckelmann")<br>There are other examples in same name\'s accusative (14)</li>');
document.write('<li>JUST: Doch nicht die hundert Pistolen, die Ihnen Ihr alter Wachtmister vor vier oder fünf Wochen brachte?<br>');
document.write('TELLHEIM: Die nämlichen, von Paul <u>Wernern</u>. (Minna I. 4)</li>');
document.write('<div style="border:solid 1px #000; width:4em;text-align:center;float:left;margin-right:2em;">MHD</div>');
document.write('<p><strong>=e</strong> Tristan → Tristande<br>（Akk. is Tristanden）</p>');
document.write('<li>vil schiere ez an daz maere kam, daz der künec <u>Rüäle</u> seite,...<br>');
document.write('(Tristan 4344 f)');
document.write('<br><br>');
document.write('Da geschah es bald, dass der König dem Rual sagte,');
document.write('</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');