document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0021.gif" class="luminous"><img src="../../img/001/s0021.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('﻿<ol start="10">');
document.write('<li>Zweimal traf ich mit Doktor Kallmeyer <u>bei Mädlers</u> zusammen. (ib.)</li>');
document.write('<li>Wir sind <u>keine Pascals</u>, wir sind nicht sonderlich am "Heil der Seele”, am eigenen Glück, an der eigenen Tugend interessiert. (Der Wille zur Macht, 426)</li>');
document.write('<li>');
document.write('Inmitten dieser entsetzlichen Spannung von Tugend zu reden war nur vollendeten  <u>Tartüffs</u> möglich - (ib.429)</li>');
document.write('<li>Es sind nicht alle Offiziere <u>Tellheims</u>. (Minna‚ II.1)</li>');
document.write('<li>Das klingt sehr tragisch! - Doch, mein Herr, bis ich jenen wieder finde, — in <u>die Tellheims</u> bin ich nun einmal vernarrt‚ — dieser wird mir schon aus der Not helfen müssen. (Minna‚ II.9)<br>');
document.write('it also indicates a man and wife (it is <u>Kielblock und Frau</u>)</li>');
document.write('<li>Aber nlcht nur auf allen Tanzmusiken ihres Dorfes waren <u>Kielblocks</u> anwesend, auch auf denen der umliegen den Dörfer fehlten sie selten. (Hauptmann: Fasching)</li>');
document.write('<li>Ich Bin morgen <u>bei Treibels</u> zu Tisch geladen. (Th. Fontane: Frau Jenny Treibel I)</li>');
document.write('<li><u>Treibels</u> geben heut ein Diner. (ib.2)</li>');
document.write('<li>Ich hatte bei euren Verwandten, <u>den Tornaouonis</u>, zu Mittag gegessen, Giovanni, und mich dort allzu lange verweilt. Man muß <u>den Tornabuonis</u> lassen, daß sie eine gute Küche führen. (Th. Mann. Fiorenza)</li>');
document.write('<li>Der Skatabend gestern <u>bei Schlüters</u> war wieder prima, sagte er am Sonntagmorgen zu se1ner Frau. (Z. 1937)</li>');
document.write('</ol>');
document.write('<p>Par analogie:</p>');
document.write('<ol start="20">');
document.write('<li>Entweder hat der jüngste in Mathematik eine Vier nach hause gebracht oder der ältere Bruder hat <u>bei Nachbars</u> mit dem fußball die Schlafzimmer Scheibe zur trummert . (Z. 1938)</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');