document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- tub bottun -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">Manuscript</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">Decipherment</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--tub contents-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="../../img/001/s0029.gif" class="luminous"><img src="../../img/001/s0029.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<h2>=n. in Akkusativ</h2>');
document.write('﻿<ol start="11">');
document.write('<li>(strange) Diese Schönheit, diese Anmut erschreckte <u>Leonardo\'n</u>. (Wanderjahre, I.II.)</li>');
document.write('<li>Fichte aber nahm dies Ausgehen vom Subjekt für Das, worauf es ankomme, vermeinte‚ nach Weise ahler Nachahmer‚ daß wenn er <u>Kanten</u> darin noch überböte, er ihn auch überträfe, ');
document.write('(Schopenhauer: Die Welt za- W. u. V. I)</li>');
document.write('<li>Psyche fastet und kasteit sich, Weil sie <u>Amorn</u> nackend sah. (Heine, Psyche)</li>');
document.write('<li>Bei einem Aufenthalte zu Seehausen fand er <u>Winckelmannen</u>, mit dem er sich freundschaftlich verband. (Goethe‚"Winckelmann")<br />');
document.write('There is an example of Winckelmannen\'s Dative in the same part. (4)</li>');
document.write('<div style="border: 1px solid #000;width:4em;text-align:center;">MHD</div>');
document.write('<li>Dô sprach der herre Hartmuot: "zwiu ertrenket ir mîn wîp, <u>die schoenen Kûdrûnen</u>?');
document.write('(Kudrun, 964)<br />');
document.write('Wozu erträmkt ihr mein Weib, die schöne Kudrun?<br /><br />');
document.write('Hartmuot spricht so au Herwig, seinem Vater, er die Gudrun ins eer werfen wollte</li></ol>');
document.write('<ol start="15">');
document.write('<li>Dâ wil ich <u>Ortrûnen</u>‚ die <u>schoenen</u> swester dîn, geben hie ze wîde de, lieben bruoder mîn.<br />');
document.write('(Kudruh 1659)</li>');
document.write('<li>Darzuo hiez si nieman wan <u>Fruoten</u> gân.<br /><i. 1635)<br />');
document.write('Darthin ließ sie nur Fruote gehen.</li>');
document.write('<li>sô nim ich <u>Hildeburgen</u>. (sc. ze wîbe)<br />(i- 1640)<br />');
document.write('Hildeburg‚ Mädchenname');
document.write('</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');