document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">05-1R</div><div class="col-8">それ自身としてはまだ格を決めるわけに行かないもの<br />は一格を以てNeuefallとして持ちふ。（内的格と対外格との問題）。掲称・列挙の一格→無冠詞（掲称）。Nenn=Nominativ.四格使用の例外として。Vocativと物主形容詞との関係：Unser Vater, Mein Vater, はあるがSein Verter, Dein Vater etcは<u>存在せず</u>！ Apposition代りの一格</div><div class="col-2">1-6<br /> <br /> <br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">05-2B</div><div class="col-8">描写・列挙の際の一格</div><div class="col-2">7-8</div></div>');
document.write('<div class="row"><div class="col-2">05-3B</div><div class="col-8">alsの次のNenn=Nominativ</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2">05-4R</div><div class="col-8">定形中心文法の基礎問題「伯父の到着」＝「伯父が到<br />着した」（日誌文体など）。副詞的一格。「羅」古きLocativ。罵言は呼掛け（Vokativ）とは違うから<u>定冠詞</u>をつける。alsとNenn=Nominativ</div><div class="col-2">10-11<br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">05-5B</div><div class="col-8">名詞 Nominativ</div><div class="col-2">12-52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］<u>freier Nominativ</u>（これも述語なり）</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］Nenn=Nominativ</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］<u>Ein rascher Griff</u>, und alles ist getan</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］省略された文章としての Nenn=Nominativ.</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］主語以外の一格文肢（副詞的）</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］表題等の引用に於ける格の問題（一格及びその他）</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］fünf Mark die Flasche</div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］<u>Vokativ</u></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］die Fülle und die Menge など量の規定。</div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］Apposition（正置）の際の無格</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2">05-6B</div><div class="col-8">先置するNenn=Nominativ。vonと挙形（諸種の問題を一括）</div><div class="col-2">54-55</div></div>');
document.write('<div class="row"><div class="col-2">05-7B</div><div class="col-8">状況言的無格。Angabe=Nominativ.</div><div class="col-2">56-58</div></div>');
document.write('<div class="row"><div class="col-2">05-8B</div><div class="col-8">間投的一格 Feuer! Fluch!等の格の問題</div><div class="col-2">59-60</div></div></div>');