document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">03-1B</div><div class="col-8">er, el, en n型（複数及び性）</div><div class="col-2">1-17</div></div>');
document.write('<div class="row"><div class="col-2">03-2B</div><div class="col-8">性</div><div class="col-2">18-91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］複合名詞の性はその最後の字によって決める－－といふ規則についての注意</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］人格と見なすものは他品詞の名詞化でも男性</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］自然の性と一致せざるもの。</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］自然の性と一致せざるものの受け方。（関係代名詞、物主代名詞）</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］異性異意</div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］Scheibare Inkongruenzen 指示代名詞、男女無差別の男性（der-等）</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］女を男性普通名で指すとき。（性・数両方）（主語に非ずして客語的位置にある時）</div><div class="col-2">57<br /> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］MutとWehmut</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］eines, keines, yedes（男女混れる時）”中性視”</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2">03-3B</div><div class="col-8">地名の性 及び定冠詞の問題</div><div class="col-2">92-122</div></div>');
document.write('<div class="row"><div class="col-2">03-4R</div><div class="col-8">複数形の随一の例外：Sporen =en が男性語Par. Excelanceなることの備考。女性固有名詞のpl.=en</div><div class="col-2">123-125<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-5R</div><div class="col-8">Zeppelin=eその他 =e 一般</div><div class="col-2">126-146</div></div>');
document.write('<div class="row"><div class="col-2">03-6B</div><div class="col-8">性数格を近い方に合わす。性数のKongruenz一般</div><div class="col-2">147-156</div></div>');
document.write('<div class="row"><div class="col-2">03-7B</div><div class="col-8">性数の二つ以上あるもの性の誤をも含む!!!</div><div class="col-2">155-180</div></div>');
document.write('<div class="row"><div class="col-2">03-8B</div><div class="col-8">Zirkus-se</div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2">03-9B</div><div class="col-8">Pluralia tantum等</div><div class="col-2">182-266</div></div>');
document.write('<div class="row"><div class="col-2">03-10B</div><div class="col-8">der Flirt その他 酒・衣服、etc</div><div class="col-2">267-290</div></div>');
document.write('<div class="row"><div class="col-2">03-11B</div><div class="col-8">女性語尾 = in</div><div class="col-2">291-304</div></div>');
document.write('<div class="row"><div class="col-2">03-12B</div><div class="col-8">数</div><div class="col-2">305-448</div></div>');
document.write('<div class="row"><div class="col-2">03-13B</div><div class="col-8">［01］=heiten, =Kkeitenが「性質」でなく「性質を帯びたもの」即ち言語又は動作又は物体等を指す傾向</div><div class="col-2">310<br /> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］Pluralia tantum</div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］複数が別意を持つもの</div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］好んで複数を用いるもの。</div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］=ma:pl=men, =a-・=en</div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］generelier Singular.（中性の場合も然り）</div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Kollektiva</div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］共有の単数（複数を用ひる代り）</div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］Singularia tantum</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］物質的取扱のSingularia tantum</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Schein Plural</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］共通の単数のKopulaが複数の例。</div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］単位扱いのplは単数形</div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］Dinger.等</div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］Die Jas =s</div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］das Auge, Ohr Hand, 等（Augen, Ohren, Haendenの代わり）</div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］純共有の単数（distributiv, 各々）</div><div class="col-2">398</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］主語がplで客語が \'s. （及びその反対）</div><div class="col-2">410</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］尊称的単数名詞にはplの定型を用ふ</div><div class="col-2">420</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］複数名詞が「習憤的」事実の暗示に用いられる際</div><div class="col-2">422</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］聯語には単数を用ふ。</div><div class="col-2">424</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］Die Feuer etc.（意味がnomen materieより転化せり）</div><div class="col-2">425</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］die Salze, die Fette, die zZucker等</div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］聯語と定型。（pl. の際）</div><div class="col-2">436</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］倒置定形の単数形と二個以上の単数主語。</div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［26］数的主語はpl.</div><div class="col-2">438</div></div>');
document.write('<div class="row"><div class="col-2">03-13R</div><div class="col-8">男性、人名より普通名へ Die Schumanns- 家族夫妻、=sかGenetiv=sなること 古代には複数が貧弱で単と同形か多かったということ。複数形におけるアクセン卜の移動。. aus Wohlklangsrurcksichten. 概念としては明らかにpl.なるものを単として扱ふ独の癖（古典語と比べて） Alle Mann hielten<br />編者注 : ほかに25件あり</div><div class="col-2">449-476<br /> <br /> <br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-14B</div><div class="col-8">der Sofa der Pult等</div><div class="col-2">477-480</div></div>');
document.write('<div class="row"><div class="col-2">03-15B</div><div class="col-8">抽象名詞のpl.種々の場合を想起せしめる効果あり</div><div class="col-2">481</div></div>');
document.write('<div class="row"><div class="col-2">03-16B</div><div class="col-8">Dualis</div><div class="col-2">482-484</div></div>');
document.write('<div class="row"><div class="col-2">03-17B</div><div class="col-8">複雑な内容を含むと推察される抽象概念には好んでPLを用いる</div><div class="col-2">485-487</div></div>');
document.write('<div class="row"><div class="col-2">03-18B</div><div class="col-8">Zeugs Dings Krams</div><div class="col-2">488-489</div></div>');
document.write('<div class="row"><div class="col-2">03-19B</div><div class="col-8">「仏」物の集約名詞</div><div class="col-2">490</div></div>');
document.write('<div class="row"><div class="col-2">03-20B</div><div class="col-8">代名詞の中性化傾向</div><div class="col-2">491-495</div></div>');
document.write('<div class="row"><div class="col-2">03-21R</div><div class="col-8">人問の中性扱い</div><div class="col-2">496-501</div></div>');
document.write('<div class="row"><div class="col-2">03-22R</div><div class="col-8">英語でも、例えば蜜蜂（bee）などは女性扱いにする！ Tausennd und eine Nacht 英は拉式複数形多し。 商品名の性Die Leica等。 勤物名中性。<br />編者注：ほかに40件あり</div><div class="col-2">502-540<br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-23B</div><div class="col-8">Die Dpktos, Die Kerls等 =s 語尾のpl.</div><div class="col-2">541-551</div></div>');
document.write('<div class="row"><div class="col-2">03-24B</div><div class="col-8">複数形、Die Warumsか？ Die Warumか？</div><div class="col-2">552-558</div></div>');
document.write('<div class="row"><div class="col-2">03-25R</div><div class="col-8">Die Theorie von den zwei China. 固有名詞の無語尾複数</div><div class="col-2">559-560<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-26B</div><div class="col-8">Dinge</div><div class="col-2">561-582</div></div>');
document.write('<div class="row"><div class="col-2">03-27B</div><div class="col-8">外来語の複数語尾としての =s</div><div class="col-2">583-589</div></div>');
document.write('<div class="row"><div class="col-2">03-28B</div><div class="col-8">「仏」 仏独「性」の相違</div><div class="col-2">590-593</div></div>');
document.write('<div class="row"><div class="col-2">03-29R</div><div class="col-8">Kongruenzfrageの一覧。失後、Zwei mann=Tank等。音響名（Schallwort）"Knacks"の男性</div><div class="col-2">594-603<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-30B</div><div class="col-8">「船名・その他一括</div><div class="col-2">604-621</div></div>');
document.write('<div class="row"><div class="col-2">03-31B</div><div class="col-8">=ien, =en複数語尾　外来語</div><div class="col-2">622-635</div></div>');
document.write('<div class="row"><div class="col-2">03-32B</div><div class="col-8">Das Blau 色彩その他</div><div class="col-2">636-640</div></div>');
document.write('<div class="row"><div class="col-2">03-33B</div><div class="col-8">Muskeln型</div><div class="col-2">641-645</div></div></div>');