document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">02-1B</div><div class="col-8">Nomen agentisの用法</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">02-2B</div><div class="col-8">”子”ling, Eektron, Isolator 格子、穴ぼっこ、娘っこ</a></div><div class="col-2">2-5</div></div>');
document.write('<div class="row"><div class="col-2">02-3B</div><div class="col-8">貶詞、附: launenhafte bezeichnung</a></div><div class="col-2">6-59</div></div>');
document.write('<div class="row"><div class="col-2">02-4B</div><div class="col-8">縮小名詞 Diminutiva Koseform</a></div><div class="col-2">60-148</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］ =chen, =lein 両方あるもの</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］一方よりなきもの Äuglein</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］ =chen, =leinのつけ方の不規則 変音せざるもの</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］ =el, (とumlaut) =el, (ohne umlaut)</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］スイスの =li, =i.</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］=erl (Weiberl)</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］kleinを用ひる例</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］Waegelchen等、Grärtchen.</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］縮小名詞の意味、及ぴ例外</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］=leinchen</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Umlautなき例 (Fauchen)</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］ =leinchen</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Umlautなき例 (Fauchen)</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2">02-5B</div><div class="col-8">Schwimmer型 Schnitzwe型</a></div><div class="col-2">149-163</div></div>');
document.write('<div class="row"><div class="col-2">02-6B</div><div class="col-8">Der Hebel型 男性名詞</a></div><div class="col-2">164-167</div></div>');
document.write('<div class="row"><div class="col-2">02-7B</div><div class="col-8">Physiognomik statt Physiognomie</a></div><div class="col-2">168-75</div></div>');
document.write('<div class="row"><div class="col-2">02-8B</div><div class="col-8">抽象名詞</a></div><div class="col-2">176-197</div></div>');
document.write('<div class="row"><div class="col-2">02-9B</div><div class="col-8">Ge= [集合名詞］ Ge=stein型</a></div><div class="col-2">198-203</div></div>');
document.write('<div class="row"><div class="col-2">02-10B</div><div class="col-8">=ierung と =ation</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2">02-11B</div><div class="col-8">動詞の語幹に相当する男性名詞</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2">02-12B</div><div class="col-8">稀なもの、der Emphehl 等</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2">02-13B</div><div class="col-8">自由型貶詞 für Sachen貶詞をも含む 事と物と人と<br />、名詞の性に関する諸種の疑問な事例</a></div><div class="col-2">207-213<br /> </div></div>');
document.write('<div class="row"><div class="col-2">02-14B</div><div class="col-8">欧一般の癖、固有名詞で一般問題を論ずる</a></div><div class="col-2">214-215</div></div>');
document.write('<div class="row"><div class="col-2">02-15R</div><div class="col-8">Nomen agentisで文意をGrand coureur de filles.</a></div><div class="col-2">216-232</div></div>');
document.write('<div class="row"><div class="col-2">02-16B</div><div class="col-8">外来語（主として名詞）</a></div><div class="col-2">233</div></div></div>');