document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">12-1B</div><div class="col-8">本編の主人公 unser 問題の男、etc.</div><div class="col-2">1-8</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">物主形容詞</div><div class="col-2">9-83</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[01]直前を受けるもの。（物）再帰物主形容詞なり</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[02]物主代名詞を用いざる場合。</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[03]直前を受けるもの（人）殆ど無意</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[04]例の、おきまりの。</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[05]名詞を略する際。</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[06]zu seiner Zeit,\' seinerzeit,\' an seinem Orte.</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[07]mein,\' dein,\' sein (adverba1)とnennen<br />特に<u>mein eigen</u>なる形に注意せよ：</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[08]das seinige (Absolut) sein Teil</div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[09]物主代名詞の代りに<u>von mir</u>等。</div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[10]主語を受ける無意味な物主代名詞の熟語。</div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[11]Das ist mein.</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[12]Dieser sein等。</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[13]豫め受ける物主代名詞。－文の全体主語に限る－</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[14]物主代名詞の前に附け得る冠飾語 <u>alle</u> seine<br />とdiese(jene) seine.</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[15]<u>Ihro</u> Majestät. <u>höchstdero</u> aller-</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[16]味方、身内 Die Unsrigen（単もあり） <u>unsern</u> <br />Die Unsern</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[17]<u>Euer</u>（Gnaden）の各格。</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[18]物主代名詞を名詞の後に。</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8">[19]<u>Dem</u> Franzel <u>sein</u> Vater. （(三格と） <u>Meines</u> Vater sein Sohn.（二格と）</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2">12-3R</div><div class="col-8">物主形容詞の補強。英の<u>0f his</u>と仏の<u>à elle</u><br />一般称の三人称 英のone\'s. 独、仏：sein, \' son.</div><div class="col-2">84-87</div></div>');
document.write('<div class="row"><div class="col-2">12-4B</div><div class="col-8">間投的：Ma tête, Ma pauvre tête!</div><div class="col-2">88-92</div></div>');
document.write('<div class="row"><div class="col-2">12-5R</div><div class="col-8">後置のdein, sein. 人代名詞の二格のir(ihrer)など</div><div class="col-2">93-95</div></div>');
document.write('<div class="row"><div class="col-2">12-6B</div><div class="col-8">価格見積の際（価値のみに非ず）</div><div class="col-2">96-100</div></div>');
document.write('<div class="row"><div class="col-2">12-7B</div><div class="col-8">再帰物主形容詞一般論</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">12-8B</div><div class="col-8"><u>il</u> mio padre式</div><div class="col-2">102-110</div></div>');
document.write('<div class="row"><div class="col-2">12-9B</div><div class="col-8">Mein Mann,\' Meine Frau,\'etc.</div><div class="col-2">111-113</div></div>');
document.write('<div class="row"><div class="col-2">12-10R</div><div class="col-8">sein eigener Arzt. 再帰物主冠詞（補）（自主自足<br />性の顕著なもの）。「MHD」物主冠詞の諸種の形<br />。物主形容詞代りに人代名詞の二格を。<br />編者注：このほか22件あり</div><div class="col-2">114-134</div></div></div>');