document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">07-1B</div><div class="col-8">名詞 Dativ</div><div class="col-2">1-187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[01]<u>Ablativ</u>(AB.=その他） ab= のみ（他にan=）</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[02]物主代名詞＝格名詞｝代り。（物主に属する付属<br />物の名詞を伴い、定冠詞。）</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[03]「・・・・に取って」 （für）（その人〔たち〕<br />から見れぱ）</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[04]Dativ des Interesses. 利害。真に利害関係ある時〉</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[05]〔例外〕 = auf, an, bei <u>Akkusativ</u></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[06]離格。 -ent=</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[07]固有名詞の三格は特に注意を要す</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[08]Dem ist so. Dem sei wie ihm wolle.</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[09]拉典のDoppelter Dativに相当するもの。（zu）</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[10]Ethischer Dativ（Manのeinemと同じ）</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[11]falsche "Appdsition" für Präpositionale Aduerbiale（墺式）</div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[12]einem läuten等。（通信の三格）<u>An</u>rede</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[13]離格支配 (nehmen, rauben, stehlen等）</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[14]Ethischer Datjv参考。（mir: für mich）</div><div class="col-2">1433</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[15]lebenと三格。（「捧げる」意の三格）</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[16]最も普通なるzugunsten, zuungunstenの三格。</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[17]Wohl dem ....! Wehe dem! Dank dem!</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[18]der Hoffnung <u>leben</u>.</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[19]<u>Dem</u> Vater seine....</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[20]DaS <u>der Horcherin</u>!</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[21]羅・Dative of purpose</div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[22]或人にとって [in seiner Meinung]</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[23]拉丁語・希語の主語的三格 梵<u>具格</u></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[24]<u>geben</u>形態。（基本的）</div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[25]三格と前綴。</div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2">07-2B</div><div class="col-8">三格直結と前置詞を介するのとの相違。</div><div class="col-2">188-189</div></div>');
document.write('<div class="row"><div class="col-2">07-3R</div><div class="col-8">或る対象に対するVerhaltenの三格。自由な三格の<br />用法。相当自由な三格の用法。委ねる任せる。<br />対処・善処の対象としてのDativは大範疇。<br />Berliner, Platt. 三格を要求する前綴（vorher=）</div><div class="col-2">190-205</div></div></div>');