document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">10-1B</div><div class="col-8">不定冠詞 雑項</a></div><div class="col-2">1-63</div></div>');
document.write('<div class="row"><div class="col-2">10-2B</div><div class="col-8">任意的、否定的</a></div><div class="col-2">64-79</div></div>');
document.write('<div class="row"><div class="col-2">10-3B</div><div class="col-8">MHD, AHD, GOTその他に不定冠詞はあるか</a></div><div class="col-2">80-82</div></div>');
document.write('<div class="row"><div class="col-2">10-4B</div><div class="col-8">定冠詞代りの不定冠詞</a></div><div class="col-2">83-100</div></div>');
document.write('<div class="row"><div class="col-2">10-5B</div><div class="col-8">冠詞用法の初歩的な典型</a></div><div class="col-2">101-105</div></div>');
document.write('<div class="row"><div class="col-2">10-6B</div><div class="col-8">1. ein 30 Männer. 2. ein Tager acht. 3. 英 a hundred</a></div><div class="col-2">106-115</div></div>');
document.write('<div class="row"><div class="col-2">10-7B</div><div class="col-8">ein＋固有名詞及び"gewiss"一般</a></div><div class="col-2">116-121</div></div>');
document.write('<div class="row"><div class="col-2">10-8B</div><div class="col-8">関係文規定</a></div><div class="col-2">122-124</div></div>');
document.write('<div class="row"><div class="col-2">10-9R</div><div class="col-8">ein Davinci 作品と不定冠詞</a></div><div class="col-2">125-136</div></div>');
document.write('<div class="row"><div class="col-2">10-10B</div><div class="col-8">性質の強調、主として無冠詞との関係</a></div><div class="col-2">137-159</div></div>');
document.write('<div class="row"><div class="col-2">10-11B</div><div class="col-8">具体的、紹介導入</a></div><div class="col-2">160-204</div></div>');
document.write('<div class="row"><div class="col-2">10-12B</div><div class="col-8">定冠詞または無冠詞の筈のところに性質の含みの不定<br />冠詞（規定ある場合）</a></div><div class="col-2">205-206</div></div>');
document.write('<div class="row"><div class="col-2">10-13B</div><div class="col-8">性質＝不定冠詞整理ノー卜</a></div><div class="col-2">207-209</div></div>');
document.write('<div class="row"><div class="col-2">10-14B</div><div class="col-8">多中の一を意味する場合（第二章）</a></div><div class="col-2">210-214</div></div>');
document.write('<div class="row"><div class="col-2">10-15R</div><div class="col-8"> </a></div><div class="col-2">215-216</div></div>');
document.write('<div class="row"><div class="col-2">10-16B</div><div class="col-8">数詞 einと不定冠詞ejn 第一章</a></div><div class="col-2">217-223</div></div>');
document.write('<div class="row"><div class="col-2">10-17B</div><div class="col-8">不定冠詞 述語</a></div><div class="col-2">224-233</div></div>');
document.write('<div class="row"><div class="col-2">10-18B</div><div class="col-8">普遍妥当命題</a></div><div class="col-2">234-243</div></div>');
document.write('<div class="row"><div class="col-2">10-19R</div><div class="col-8">Es ist ein E1end!</a></div><div class="col-2">1244-245</div></div>');
document.write('<div class="row"><div class="col-2">10-21B</div><div class="col-8">性質強調と関係、未定の仮構事象 etwaige型<br />可能～、仮構～、架空～、未然、企画的～</a></div><div class="col-2">250-360</div></div></div>');