document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">08-1B</div><div class="col-8">間投的四格。</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">四格 Akkusativ</div><div class="col-2">2-156</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[01]umliche Erstreckung. 編者注:?</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[02]Zeitliche Erstreckung. Meine Tage等</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[03]測定的。（主として比較級の前に）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[04]測定定。（weiter, voraus等を伴わぬ場合） <u>副詞的</u></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[05]時の副詞。<u>Zeitpunkt</u></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[06] [02]と同じ ...über, durch.</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[07]四格の副詞化。 nichts.（ονδεν, πολ<br />υ）</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[08]結果挙述の四格</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[09]結果挙述四格の一種</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[10]Erstreckungusakkusativ mit Nachadverb通過のAkkusativ（<u>hinau</u>等と）</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[11]drei Meter hoch等。</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[12]「差のum」＋比較級の代りに単に四格。</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[13]Inneres Objekt. 〔外国語〕</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[14]Lassenと二個の四格</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[15]数量四格を支配する動詞。～betragen,<br />～messen, ～zähLen</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[16]be= と四格。</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[17]eine Zeit <u>lang</u> 「langを前置詞に扱っては？〕</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[18]<u>einen Strich</u> malen. 量的規定の四格。</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[19]二菫四格（nennen, schelten)</div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[20]特 「lehren, 其他」</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[21]結果挙述。退去を命ずる等。</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[22]挙形（又は省略形は一格又は四格）</div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[23]Wache stehenに対する一格形</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[24]<u>seinen</u> <u>Mann</u> stehen=sich Bewähren</div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8">[25]Karussel fahren等</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2">08-3B</div><div class="col-8">数値の四格。 aufと関係</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">文肢。Inneres Objekt</div><div class="col-2">158-191</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[01]Genitiv.</div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[02]四格の例</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[03]Funken sprühen等（結果の四格と似て非なこと）</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[04]代名詞四格のInneres Objektは、普通のものより<br />は目に立たざる故、用ひられる事多し。</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[05]特別に拵へるもの。</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[06]lassenと二つの四格</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[07]einen Strich streichen ひとこすりする。</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[08]<u>夢が</u>夢みる。（主語とinneres Verbum）</div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8">[09]希・羅</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2">08-5R</div><div class="col-8">特に人聞の四格に閲する注意：「その人の言う事を」<br />「その人の考えていることを」など。 Guten Morgen<br />! の完全形。 den <u>Weg gehen</u>, die <u>Strasse</u> ziehen<br />等。 Den Herrn Spielen等<br />編者注：このほか9件</div><div class="col-2">192-199</div></div>');
document.write('<div class="row"><div class="col-2">08-6B</div><div class="col-8"><u>Was</u> andere <u>tanzen</u>, muss er schätzen.</div><div class="col-2">200-202</div></div></div>');