document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0001.html">附置規定（殊に掲称的附置規定）命名の附置規定</a></div><div class="col-2">1-24</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0004.html">[01]普通名詞。固有名詞。</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0011.html">[02]Adresse, Wohnort.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0011.html">[03]序数、年代等の規定。</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0012.html">[04]「格」は揃えること普通名詞</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0013.html">[05]格を揃えぬ場合（無格的一格を付す）</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0014.html">[06]Psuedo=Apposition. <u>Eine Art</u>～</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0019.html">[07]文章のApposition.</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0016.html">[08]「即ち」と説明して同「格」になるもの。</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0019.html">[09]形容詞のApposition.</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0020.html">[10]Genitivus appositivus相当するもの。</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0022.html">[11]格の如何に拘らず、1格のAppositionを付した例</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0023.html">[12]<u>Sanders\' Sprachbriefe</u></a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2">09-1B</div><div class="col-8"><a href="../009/s0023.html">[13]「何々としての位置」等。</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2">09-2B</div><div class="col-8"><a href="../009/s0023.html">König Arthus 凍結形として等。</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2">09-3B</div><div class="col-8"><a href="../009/s0025.html">命令の附置規定</a></div><div class="col-2">25-29</div></div>');
document.write('<div class="row"><div class="col-2">09-4B</div><div class="col-8"><a href="../009/s0043.html">格一致せざる挙格的同格。Der Dichter Goethe.<br />Die Stadt Berlin.</a></div><div class="col-2">43-47</div></div>');
document.write('<div class="row"><div class="col-2">09-5B</div><div class="col-8"><a href="../009/s0048.html">Herr Hauptmann Frau Hauptmann</a></div><div class="col-2">48-50</div></div>');
document.write('<div class="row"><div class="col-2">09-6B</div><div class="col-8"><a href="../009/s0051.html">Philipp der Zweite型</a></div><div class="col-2">51-54</div></div>');
document.write('<div class="row"><div class="col-2">09-7R</div><div class="col-8"><a href="../009/s0055.html">〔失！〕Regierung Papen型。〔仏〕Le mot <u>de</u><br />Science Apposition（格を揃へずして<u>Nominativ</u>を<br />用いるものあり、省略文と心得るべし）<br />編者注：このほか22件あり。</a></div><div class="col-2">55-77</div></div></div>');