document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">15-1R</div><div class="col-8">具体的なdas ～ e</div><div class="col-2">1-2</div></div>');
document.write('<div class="row"><div class="col-2">15-2B</div><div class="col-8">形容詞の名詞化 名詞的用法<br />Das schickssal Teusend<u>er</u> von Menschen.</div><div class="col-2">3-158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[01]過去分詞。（男女のみ） 形容詞の名詞化<br />der Abtrünnige, Aufständische, der Aussätzige.</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[02]形容詞（男女のみ）及ひ複数（人）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[03]女性。</div><div class="col-2">37-38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[04]重（名詞化）Allerlei等</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[05]中性の際を小文字で書く傾向。</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[06]zu-endを名詞化</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[07]中性。（......点、方面を指すもの）（性質）定冠詞</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[08]Gattunngegriffの中性。</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[09]学問的概念としての中性。 Das 0rganische,<br />Unorganische.</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[10]名詞か略される場合には小書</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[11]過去、現在「分詞句」の名詞化</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[12]冠詞を件はぬ際</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[13]現在分訶より。（成句語）</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[14]現在分詞（新造）</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[15]小書するもの。（前置詞と共に）</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[16]形容詞の次に転来名詞。（弱変化例外あり！）</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[17]ein Leichtes sein.</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[18]<u>Was</u> gibt\'s <u>Neues</u>? (ce que.....de....)</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[19]manches, vieles, weniges, alles, einiges, eines,<br />solches, =mancherlei u.s.w. dieses, yenes,<br />das beste, meiste.</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[20]中性（其の場合云々の具体的「事柄」を指す）<br />普通名詞的の中性（das Freie, des Äussere）</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[21]zu+不定法の名詞化</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[22]Gedrucktes, Eingemachtes, Gebackenes, Gehacktes</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[23]弱語尾（三格語尾=emの弱化）<br />Der mich <u>zu</u> Saladins <u>Gefangenen</u> machte.<br />(statt Gefangenem.)</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[24]yung und alt</div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[25]長き冠飾句的なるもの。然し、<u>der Lebendig<br />begrabene</u>等も可。</div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2">15-3B</div><div class="col-8">［英］Gerundによる文の名詞化。</div><div class="col-2">159-169</div></div>');
document.write('<div class="row"><div class="col-2">15-4B</div><div class="col-8">主語二格と〈前置詞句一個）の附加詞（durchの機能）</div><div class="col-2">170-222</div></div>');
document.write('<div class="row"><div class="col-2">15-5B</div><div class="col-8">名詞化〈但し形容詞を除く）</div><div class="col-2">223-256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[01]［接続其他のPartikel］大文字（二格は無語尾）</div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[02]動詞（結？したるものとせざるものと）</div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[03]再帰動詞の=ung名詞化。</div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[04]動詞不定法（新造）</div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[05]動詞不定法句（新造）。</div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[06]形容詞のまま。</div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[07]etwas Gutes, nichts Gutes等。</div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[08]形容詞つきの名詞。 （大書）。</div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[09]男性化。</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[10]名詞の名詞化（中性）</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[11]Nomen actions mit dem yungen Nexus.</div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[12]不定法。殊に不定冠詞。ein Kommen und Gehen</div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[13]不定法。keinと共に。</div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[14]文章の名詞化（中性）<br />［英］→「自由型Composita」と一部一致す。</div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[15]名詞化とmit Bestimmungen</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2">15-6B</div><div class="col-8"><u>文の</u>名詞化</div><div class="col-2">257-263</div></div>');
document.write('<div class="row"><div class="col-2">15-7R</div><div class="col-8">四格目的語が二格でなく、前置詞を要するもの<p> </p><ol><li>der Besuch bei～</li><li>ein Überfall auf～</li></ol><p>Das <u>vertriebenen</u>gesetz（合成名詞と、形容詞の<br />名詞化の複数の……二格か？</p></div><div class="col-2">264-265</div></div>');
document.write('<div class="row"><div class="col-2">15-8B</div><div class="col-8">複数二格の無冠詞、（形容詞の名詞化）<br /><u>普通名詞</u>の場合は不可能なり。</div><div class="col-2">266-268</div></div>');
document.write('<div class="row"><div class="col-2">15-9R</div><div class="col-8">形容詞のままを名詞的に。<br /><u>Das Deutsche, das Italienische</u>など（中性の場合<br />の重要なもの）</div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2">15-10B</div><div class="col-8">不定法名詞化の一型 「文章の短縮」的意形</div><div class="col-2">270-276</div></div>');
document.write('<div class="row"><div class="col-2">15-11B</div><div class="col-8">=en(不完全名詞化〉)</div><div class="col-2">277-279</div></div>');
document.write('<div class="row"><div class="col-2">15-12R</div><div class="col-8">an <u>das Unmög1iche</u> grenzen.（範囲ヲ指スモノ〉<br />［英］<u>verge</u> on～<br />Das Äussere 中性にして具体物を指すもの。<br />［羅］にも不定名詞あり、中性！<br />熟語的（形容詞の名詞化）<br />=en動作名詞と語幹形との区別、習慣的に差の生<br />ぜるもの多し！<br />\'statt Erfunde =n<u>em</u><br />［羅］GERUNDIUMとGERUNDIVUM. zu+不定旬に相当<br />文の名詞化の際の一つの注意 adnominalな前置詞<br />文肢の重畳は避けよ</div><div class="col-2">280-284</div></div>');
document.write('<div class="row"><div class="col-2">15-13B</div><div class="col-8">文を不定法名詞に省略する経過（直前を受ける<br />不定法名詞</div><div class="col-2">285-288</div></div>');
document.write('<div class="row"><div class="col-2">15-14B</div><div class="col-8">名詞化した不定法（<u>具体動作</u>）</div><div class="col-2">289-293</div></div>');
document.write('<div class="row"><div class="col-2">15-15R</div><div class="col-8">定形中心文法の基礎問題 「伯父か書いた」を<br />「伯父の到着」という（日誌などで）<br />［仏］alleés et venues. Kommeen u.Gehen.<br />名詞化はまだ文章として考えていることの徴候的<br />証拠</div><div class="col-2">294-295</div></div>');
document.write('<div class="row"><div class="col-2">15-16B</div><div class="col-8">=ung型 nomen actionisの諸問題。</div><div class="col-2">296-297</div></div>');
document.write('<div class="row"><div class="col-2">15-17B</div><div class="col-8">名詞化形容詞の如くにして然らざるもの：</div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2">15-18B</div><div class="col-8">［仏］不定法名詞<br />1. Au lever du rideau, la scène est vide.</div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2">15-19R</div><div class="col-8"><u>［領］を意味するもの</u>。<br />das <u>Nachsehen</u> haben等の熟語的なもの。<br />完全に名詞化した不定法<br />熟成した不定法の名詞化<br />［英］sewing machine型<br />Der Blick <u>in den</u>Garten等、方向指示の問題<br />bis zum <u>Überfliessen</u>.<br />領地を意味する中性<br /><u>Die Herren Gelehrten</u></div><div class="col-2">300-306</div></div>');
document.write('<div class="row"><div class="col-2">15-20B</div><div class="col-8"><u>Bediente</u>の問題 複数の弱変化</div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2">15-21R</div><div class="col-8">［語尾］人間のDeutsch<u>em</u>, Deutsch<u>es</u>は避ける。<br />ihnen als Deutsch<u>en</u>.<br />葡萄酒名は男性。<br />再帰動詞の名訶化 sich winden → das Winden.<br />複数形 Das Verbrechen→die Verbrechen:<br />die ersten, die beiden, die meisten, die übrigen<br />zum Aufdenbaum klettern<br />［英］無冠詞もあり。 1.Give to needy!<br />Das Deutsch<u>e</u>とdas Deutsch<br />im Dunkeln. （im Dunkel）<br />im Stillen. （*in der Stille）<br /><u>男性で人ならざるもの。</u><br />複数は人ならざること。</div><div class="col-2">308-313</div></div></div>');