document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">13-1B</div><div class="col-8">形容詞形態・語尾</a></div><div class="col-2">1-131</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[01]? 尾をつけさるもの（中には不定数詞に扱うもの<br />あり。</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[02]定冠詞をくりかえすことあり。</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[03]中性単数の前の語尾の省略 (archaistich)</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[04]（熟語的用法の際のみ.）前綴の形容詞化。</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[05]ganz Deutschland.</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[06]wir Deutscheかwir Deutschenか？</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[07]=erkei</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[08]語尾をとらぬ熟語。</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[09]<u>al1erhand</u>.</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[10]形容詞の後置</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[11]<u>Lieben</u> Freunde! (Vokati.)</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[12]frohes Mutes.（副詞的 Genitivに多し）</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[13]lauter, eitel.（前置詞的接続詞なり）</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[14]=eの語尾</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[15]強変化の例語について</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[16]大害する附加語的形容詞</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[17]Das <u>Weisse Haus</u> 白亜館（アメリカ）</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[18]Saxon genitive後の形容詞は強変化<br />（弱変化：schönes Knaben等もあるわけ）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[19]mir Unglücklichem等。（名詞化へ行く）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[20]so ist diese Auffassung <u>eine irrige</u>.</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[21]弱変化男性名詞の前の強語尾</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[22]形容詞 格支配 無語尾のrosa, lila等</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[23]?</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2">13-2B</div><div class="col-8"> </a></div><div class="col-2">132-250</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（1）前に何かある場合に弱変化語尾を用いる例。</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（2）Die graue Substanz. 造語形容詞</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（3）形容詞　形容詞の意味</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（4）Epithetisch.</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（5）副詞と見られ勝ちな場合。</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（6）Epithetischとは少し違う場合。羅典式、述語（副詞） <u>Laetus</u> abit</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">動詞代りの形容詞。1.（seinと共に）<br />2.sich machenと共に 3.weidenと共に</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（8）厳密に規定的（特殊化的、限定的）</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（9）外囲的形容詞の重畳（弱語尾の問題もあり）<br />指示詞と称するものの理由ここにあり。</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（10）形容に非ずして「限定」的</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（11）拉丁のsummus, medius, imus等と同じ関係にな<br />るもの。</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（12）Genitiv的（及び範囲規定）philosophische<br />Unkenntnis<p> </p><p>編者注：上記（3）～（12）はノート・ブ<br />ック式にまとめられている。したがって、この<br />部分だけを独立させ、-つの袋にしたほうが良<br />かったかもしれない。この部分の主タイ卜ルは<br />「形容詞・形容詞の意味」である。</p></a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2">13-3B</div><div class="col-8">定語尾属か不定語尾属か?。（準定語尾属）</a></div><div class="col-2">251-299</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[01]alle其他定語尾属と形容詞</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[02]Alle, dieseと<u>強</u>（その他例外）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[03]einige, mehrere, viele, beide</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[04]mancherと弱（強）</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[05]二個の形容詞のうち前を強、後を弱にする例。（前が指示詞化す）</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[06]二番目の形容詞を無意味に弱にすることがManieになっている人の例。</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[07]一格のwir, ihr後の弱変化</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[08]einzeln等の後の弱変化 <u>dieser</u> <u>mein</u> best<u>er</u> Freund.</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[09]viele, wenige, mehrere</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">[10]schönes Äuss<u>ere</u>.(=es)</a></div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2">13-4R</div><div class="col-8">Sie ist tipptopp.（firstrate)</a></div><div class="col-2">300-306</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「仏」は名詞と形容詞との区別あいまいなり：<br />porteur, porteuse型及び、(Appositiv →)<br />名詞をすぐ形容詞として用い得。<br />形容詞の無語尾：（色）Des rubans <u>chocolat</u>.<br />形容詞の示格機能</a></div><div class="col-2">300-306</div></div>');
document.write('<div class="row"><div class="col-2">13-5B</div><div class="col-8">Weissbrot</a></div><div class="col-2">307-314</div></div>');
document.write('<div class="row"><div class="col-2">13-6B</div><div class="col-8">rot und geres Tu1penbeet.</a></div><div class="col-2">315-322</div></div>');
document.write('<div class="row"><div class="col-2">13-7B</div><div class="col-8">geraum, feind, gram等、専ら述語用法の形容詞。</a></div><div class="col-2">323-333</div></div>');
document.write('<div class="row"><div class="col-2">13-8B</div><div class="col-8">形容詞の性数。KONGRUENZ</a></div><div class="col-2">334-338</div></div>');
document.write('<div class="row"><div class="col-2">13-9B</div><div class="col-8">Alles Gute. Dieses Gute. 及びそれらに類する場合</a></div><div class="col-2">339-352</div></div>');
document.write('<div class="row"><div class="col-2">13-10R</div><div class="col-8">人を主語にするか、物を主語にするかの問題<br />形容詞 動詞もあり：gefallen.<br />形容詞格語尾 無冠詞の場合の形容詞変化：<br />問題の gut<u>es</u> Mensch<u>en</u></a></div><div class="col-2">353-355</div></div>');
document.write('<div class="row"><div class="col-2">13-11B</div><div class="col-8">合成名詞 Rote=Kieuz=Schwester.</a></div><div class="col-2">356-362</div></div>');
document.write('<div class="row"><div class="col-2">13-12R</div><div class="col-8">la sage-femme 産婆<br />副詞の形容詞化 Militärische Erfolk=losigkeit<br />.=見地の形容詞。<br />名詞化は弱か強か?</a></div><div class="col-2">363-370</div></div>');
document.write('<div class="row"><div class="col-2">13-13B</div><div class="col-8">alle=, dies=, jed=, kein=, 等の二格語尾（弱を主に）</a></div><div class="col-2">371-376</div></div>');
document.write('<div class="row"><div class="col-2">13-14R</div><div class="col-8">格語尾=el, =belの際<br />形容詞の格語尾 <u>Unser</u> wacke<u>re</u> Freund<br />定語尾属一般論。<br />前に何かある際の強語尾<br />附加語は格語尾あり、述語は無語尾といふ基本問題の<br />参考<br />「仏」<u>grand</u> hommeとhomme <u>grand</u><br />度量衡名（単）の前につける場合の形容詞語尾。</a></div><div class="col-2">377-383</div></div>');
document.write('<div class="row"><div class="col-2">13-15R</div><div class="col-8"><u>強語尾の重要性</u>。複数（名詞化した）の=en語尾形<br />複数（名詞化した）の=en語尾形<br />solcheの後の強弱に依る意味の区別<br />Saxon Genitive等の強語尾<br />動詞とà blanc, à vide等 moudre à vide<br />形容詞の意味上の根本問題<br />indifferenzとDifferenziertheit<p> </p><p>編者注：このほか17件あり。</p></a></div><div class="col-2">384-403</div></div></div>');