document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">19-1B</div><div class="col-8">副詞、主要なる副詞</div><div class="col-2">1-106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］代名詞的副詞（述語）</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］間投的副詞あり。</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］<u>überrhein</u>, rheinüber. main über</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］halb und halb（薄々）</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］<u>überhaupt</u>.</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］hintenauf. nebenan.等</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］all=bereits型</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］<u>vorderhand</u>.</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］<u>schlankweg</u>.</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］weiterhin, späterhin, daraufhin, mithin, vorhin（nebenhin）</div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］meerab等。 querfeidein</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］schliesslich, am Ende.（論理的）</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］tagaus, tagein等。 明けても暮れても。<br />［英］［day in, day out］</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］Wand an Wand mit....</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］holterdiploter, usw. 擬音的副詞句。</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］<u>Hals, übeir Kopf</u>等の句。</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］二格形の結成形</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］現在は完全に副詞なる筈のものを、語尾を取りたる例外。</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］=hei beiher, seither, nebenher, anher（O） weither, nachher, vorher</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2">19-2B</div><div class="col-8">論理関係の副詞 gern. 無意識に、知らず知らず。やむを得ず im gegenteil. allenfalls そうでなくてさえ。ほか38件</div><div class="col-2">107-158</div></div>');
document.write('<div class="row"><div class="col-2">19-3B</div><div class="col-8">副詞 一般的法則</div><div class="col-2">159-220</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］時の副詞</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］auf "=st"</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］成句的副詞。</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］副詞（所）を主語にできない所から起る一種の言い回し</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］genugと語順</div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］hinnen, dannen, wannen, 等</div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］<u>inne</u>（innenと区別して）</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］形容詞を規定する副詞</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］beruflich=Berus wegen</div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］動詞を規定する際。</div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］<u>見地より</u>（意味の問題）nachと同じものあり。</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］numen agentisを言いかえる副詞<br />（polizeihlich hÖheienorts.）</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］副詞の<u>制限的</u></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2">19-4B</div><div class="col-8">時間の副詞<br />たまたま（von ungefähr）。<br />何らかの‥irgendwie geartet. 直ちに。<br />先刻、先程、今しがた。まだ（noch nicht）<br />昨夜（diese nacht）。だしぬけに、唐突に<br />編者注：このほか34件あり。</div><div class="col-2">221-246</div></div>');
document.write('<div class="row"><div class="col-2">19-5B</div><div class="col-8">方向の考え方。 kommen, gehen, hinとher</div><div class="col-2">247-275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］kommenの逆用（kommenの意味）</div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］<u>gehen</u></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］英語との比較</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］hin, hei等の参考。</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］Akkusativで</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］古典特有の「通過方向」表現の副詞。<br />π，η，qua，</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］b1eibe <u>dort</u> weg!</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2">19-6B</div><div class="col-8">副詞的接続詞の用法、特有性</div><div class="col-2">276-305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］darum, deshalb, des wegen,<br />さうかと言って。 そのためになにも。</div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］<u>darein</u></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］Dafür.（そのために）</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］übel <u>daran</u> sein.</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］<u>dahin</u>. = <u>so</u>と同意の。</div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］dabeiそれにも拘ず。</div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］deshalb（其の件に関して）</div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］dafür（um diesen Preis.）</div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］dafüber（それに関して）</div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］<u>In</u> der Kanne ist noch Kaffee <u>drin</u>.</div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］<u>daneben</u>.（それる、）</div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］<u>darum</u>, <u>deshalb</u>, deswegen</div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］熟語の要素としてのdaran, drauf, dahin</div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］dessenungeachtet. demungeachtet.</div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］<u>drin</u>（darinに非ず）</div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］hiermitこれで・・これを以て</div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］und damit, ［それと同時に］ 従ってまた</div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］必ず省略形（dr～）をようするもの</div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］dazu, hierzu 加うるに。</div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］［英］のthere～ therefore</div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］dafürの代りにfür等</div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］そもそもdar～が「こと」を受ける傾向があって「もの」には不適であると言うこと：</div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2">19-7B</div><div class="col-8">副詞の形<br />, ［AHD］ofto, gerno, 等<br />［MHD］dick<u>e</u>等 =e 多し<br />mit+抽象名 avec précaution<br />編者注：このほか33件あり。</div><div class="col-2">306-344</div></div>');
document.write('<div class="row"><div class="col-2">19-8B</div><div class="col-8">=lings</div><div class="col-2">345-350</div></div>');
document.write('<div class="row"><div class="col-2">19-9B</div><div class="col-8">空間関係副詞<br />簡単なもの …の中ほどの所<br />［英］あちら、（こちら） <u>over</u> yonder <u>over</u> there<br />anderswo sonstwo [a-] anderweit 等 ［英］up huer<br />到る處 allewärts allerwegen überall allerorten<br />遠くから von weitem. aus der Ferne.<br />印刷物中の空間指定<br />あちこち</div><div class="col-2">351-358</div></div>');
document.write('<div class="row"><div class="col-2">19-10B</div><div class="col-8">現在の副詞と話の中の副詞</div><div class="col-2">359-363</div></div>');
document.write('<div class="row"><div class="col-2">19-11B</div><div class="col-8">程度の副詞</div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2">19-12R</div><div class="col-8">独特有の間投的副詞 <u>leider</u> 等<br />心理関係副詞<br />von ungefähr（ふと）<br />副詞の名詞的表現 Il arriva <u>le premier</u>. hier=→ h = hüben, haussen insgesamt allesamt samt und sonders等<br />wohl oder übel schlecht und recht früher oder später等の句<br />schlecht und recht<br />無冠詞名詞の副詞的用法<br />編者注：このほか6件あり。</div><div class="col-2">365-374</div></div></div>');