document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">20-1B</div><div class="col-8"><a href="../020/s0001.html">schon</a></div><div class="col-2">1-101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0003.html">順序（論理的9…となると既に</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0006.html">前置接続詞的。</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0007.html">大丈夫、もう、まあ。「いづれ」楽観の表現</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0011.html">こうなって来るとこるなどうしても「もう」…仕方がない どうも</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0013.html">gleich, nur, gleich.doch.</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0014.html">疑問文に（auchと同じ） 侮蔑的。<br />「いづれ」大したものじゃない。</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0020.html">なあに、（負け惜しみ、etc）<br />begütigend 安堵させるため。 （ja schon）<br />認める（たしかに）「まあ」</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0021.html">驚く勿れ等 「とても」 「そりやアとても」</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0022.html">命令法と共に。「まあどうぞ」御勘弁遊ばせて等。</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0027.html">況んや…に至っては（schon gar nicht.）</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0029.html">既に既に…（尖置）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0031.html">肯定を強めるもの。（勿論）</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0032.html">既に云々せんとしたるところ</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0033.html">Ich will schon! schon lieber, schon wieder</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0035.html">Es müsste schon mit dem Teufe1 zugehen, <br />wenn....sollte</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0039.html">so（ge1egent1ich）=ich weiss nicht wie....<br />なんだか</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0043.html">その通りで（よろしい、等）形容詞的</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0051.html">比較Wieの後に来るso<br />さう言う風に（動詞につ&lt;）<u>thus</u></a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0052.html">so vier, so gut, so lange 非常に（一般項）</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0053.html">斯&lt;の如くにしては（仮定的）</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0062.html">古典的so. ［so c1assicum］ wohl</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0072.html">仏語のtant....（aussiニ非ズ） 後に来るso....<br />sonst</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0087.html">然らずんば さもなければ</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0096.html">so auch so 接続詞としてのso</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2">20-2B</div><div class="col-8"><a href="../020/s0102.html">Nur <u>nur noch.</u>. （<u>nicht</u> <u>mehr</u>の肯定）</a></div><div class="col-2">102-160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0107.html">疑問のnur.（不審る）（反語にも）<br />（あきれる時も）<br />願望のnur. 心配のnur</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0113.html">nur［dann］....wenn. nur zu....（nur soも同じ）</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0119.html">nur（leider）但し</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0121.html">普通のnur</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0123.html">とにかく--<u>だけ</u>の.（nur eben）</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0129.html"><u>wo nur</u>....（allein） <u>der nur</u>....（a11ein）<br />前置詞的接続詞として。<br />せめて（wenigstens.）</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0130.html">命令法と共に<u>nur</u>.（まアいいから）（まあ）</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0138.html">前置詞的接続詞としてのnur, alleinは、必ずしも名詞等の直前直後にはない。</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0139.html">nur［noch］（ただますます…なるぱかりだ）<br />「もはや…」のnur nochとはちがふ。</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0145.html">…にして始めて…なる… wie…nur</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0149.html">, allein）</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0151.html">微妙なnur（悪い方の意）</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0155.html">ただ…した<u>ばっかりに</u> 普通の<u>nur so</u></a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2">20-3B</div><div class="col-8"><a href="../020/s0161.html">Noch</a></div><div class="col-2">161-246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0162.html"><u>noch lange nicht</u>.（D.Kein） なほ（一層）のnoc&lt;（比較級と）</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0164.html">sogar［前置的場合のみ］最高級</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0167.html">sogar…時問的</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0178.html">Das fehlte noch. Das fehlte noch gerade<br />と接続法。</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0184.html">大丈夫、その中に（<u>schon</u>） <u>noch einmal</u><br />その内にいづれ、きっと</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0189.html">nochの先置（まだ、今のところは）仮定強調的</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0193.html">準否定詞kaum, wenig, selten, nur,等の際のmehrはnochとなる。</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0194.html">危なく、際どくも（やっと間に合ふ）</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0201.html"><u>wahr1ich</u>［間投文内のnoch］</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0202.html">noch nachträglich.（そのうちに、いづれ、あとになって、後日）</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0205.html">むしろ。まだしも。weinigstens.</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0208.html"><u>noch so</u> …［認容的］=<u>auch</u> <u>noch</u> <u>so</u>.</a></div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0209.html">wann...._<u>noch</u>（殆んど無意）<br />まだしも。まあ…さう言ってもまあ</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0214.html">古い物が案外現在と関係ある事を示すnoch.</a></div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0220.html">schon.（noch vor, noch ehe）<u>very</u></a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0224.html">時聞的。「すぐに、早速」<u>noch</u> heute</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0226.html">［sogar］<u>noch</u></a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0223.html">疑問文中のnoch</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0241.html">noch（dazu）剰さへ</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0243.html">まづどうにか</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0244.html">Zum Kuckuk noch mal!</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2">20-4B</div><div class="col-8"><a href="../020/s0247.html">sehr</a></div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2">20-5B</div><div class="col-8"><a href="../020/s0248.html">selbst<br /><u>selbst</u>と<u>selber</u> その他self=の複合詞<br />Hier ist er selbst!（om Person）<br />登場人物をmeldenする時。</a></div><div class="col-2">248-255</div></div>');
document.write('<div class="row"><div class="col-2">20-6R</div><div class="col-8"><a href="../020/s0256.html">［und］soそういうわけで <u>so</u>〈z.B.）</a></div><div class="col-2">256-259</div></div>');
document.write('<div class="row"><div class="col-2">20-7B</div><div class="col-8"><a href="../020/s0260.html">nun</a></div><div class="col-2">260-296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0263.html">辛抱を切らした際に出る<u>nun</u></a></div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0263.html">間投詞の<u>nun</u>（<ruby>惘<rt>あき</rt></ruby>れた時）</a></div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0264.html">nanu!</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0264.html">認容文の<u>nun</u></a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0265.html">nun ja, nun freilich,</a></div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0267.html"><u>nun einmal</u>,<u>einmal</u>,</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0272.html">nun, nun! nu, nu!（宥める時） begütigend.</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0278.html"><ruby>扠<rt>さ</rt></ruby>て、ところで。</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0279.html">nun denn 然らば <u>nun</u> also</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0282.html">....nun（eben）</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0283.html">nun wohl eben nicht. nun einmal</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2">20-8B</div><div class="col-8"><a href="../020/s0297.html">und</a></div><div class="col-2">297-331</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0298.html">dann, soの意 さうすれば</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0300.html">しかも（trotzdem） undと定形</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0302.html">und（doch）.... …なのだが。</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0302.html"><u>oder</u></a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0303.html">darum....であったので、因由、（und［so］）</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0303.html">それに…［”しかも”とはちがふ］</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0304.html">殆ど無意味なつなぎ方</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0305.html">undを何度も用ふ polysyndeton</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0310.html"><u>undを最後に</u>（普通）</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0318.html">undなく。いわゆるAsyndeton</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0319.html">近くして遠からず。</a></div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0320.html">逆順（一般的な宣言があと）</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2">20-9B</div><div class="col-8"><a href="../020/s0332.html">wohl</a></div><div class="col-2">332-379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0333.html">まあ、まず（渋々の承諾）, 「恐らくは」の変態。</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0334.html">おそらくは、思うに。</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0335.html">疑問文内のwohl.</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0336.html">Pleonastisches "Wohl".云々するの<u>であった</u> 頭など振りけり <u>叙述的</u>の場合多し</a></div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0340.html">習慣性のwohl「よく」あった、等</a></div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0347.html"><u>wohl aber</u></a></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0352.html">なるほど確かに……であらう！　認容<br />さうであらうとも！　尤もでござる</a></div><div class="col-2">352</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0354.html"><u>ungefähr</u>，又は「裕に」gut（数詞）</a></div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0356.html"><u>wohl</u>（=zwahr）-aber-</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0358.html">Es ist sehr wohl mÖglich.<br />たしかに、とうも（可能性濃厚）</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0360.html">［雑］wieder, wiederum</a></div><div class="col-2">360</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0361.html"><u>zurück</u></a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0362.html"><u>wieder einmal</u></a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0363.html">doch wieder（さうかとおもふとまた）</a></div><div class="col-2">363</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0364.html">wiederum, seinerseits</a></div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0367.html">疑問文または間投文内のwieder</a></div><div class="col-2">367</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0368.html">wieder=immer やはり、同様</a></div><div class="col-2">368</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0378.html">wiederとwiederum（”反対に”のwiederumもあり）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0371.html">schon wieder.<br />［雑］ <u>was</u><br />何</a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0373.html">文意を受ける関係的was</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0373.html">wasの意のwas. "wozu"</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0374.html">名詞化形容詞を伴ふ疑問の<u>was</u>.</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0374.html">was（wie）---!</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0375.html">［雑］ <u>wenig</u></a></div><div class="col-2">375</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0377.html">［雑］ <u>wo</u></a></div><div class="col-2">377</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0378.html">関係代名詞（空間的）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0378.html">関係代名詞（時間的）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0378.html">Wo <u>nur</u>; wo <u>allein</u>.</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../020/s0379.html">［雑］ <u>wer</u></a></div><div class="col-2">379</div></div></div>');