document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">21-1B</div><div class="col-8"><u>immer</u></div><div class="col-2">1-20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer 常に。</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">認容的<u>immer</u></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">jedenfalls. immerhin（併しいづれにせよ）</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer（toujours）<u>やはり</u> 今までに従って、<br />gleichfalls.</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">命令法と共に。</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">空間的。（immer gradaus）</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer = je 各々</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］irgend（＝） nirgend（s）</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">21-2B</div><div class="col-8">［雑］<u>mal</u>と<u>einmal</u></div><div class="col-2">21-49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（nun）einmal「どうせ」</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst mal wieder mal</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">zunächst einmal. erst einmal vorläufig einmal</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nlcht einmal</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wieder einmal（erst einmal）</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>nicht einmal</u>.</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">endlich einmal schliesslich einmal</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade einmal gelegentlich einmal<br />später einmal たまに いつか一度</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">vorlänglig einmal zunächst einmal</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">21-3B</div><div class="col-8">［雑］<u>ja</u></div><div class="col-2">50-87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…ja…！（どうも畏れ入った）　実に！</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">自明の事柄として言ふ際。</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「否むしろ」（wo nicht gar, と同じ）<br />Man könnte fast sagen.→（並列接続的）</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>ja</u> nicht.（金輪際） ja（命令法と）<br /><u>nur ja</u></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係文中のja（doch）</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文の先頭に（せき込むトキ） ja［aber］</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">如何となれば…、それが証拠に。 auchに似たり</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">反語的「…ではないか！」（助勢詞）「ハア」</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">肯定命令法とja.</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>je</u></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">von je, von jeher.</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je nachdem，（副詞的、接続詞的）</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je（nieの反対）</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je <u>各々</u> <u>respektive</u>.ja wohl? da ja....<br />ja（うるさいとき、よい加減な返事）<br /><u>ja aber</u></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">21-4B</div><div class="col-8"><u>gerade</u></div><div class="col-2">88-119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">noch gerade....［genug.］</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">just.（前置的） ちようど</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">かへって…が 「が」</div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">丁度（偶然） <u>ausgerechnet</u>.</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht gerade必ずしも…と言ふ程ではない。<br />-1itotes- まさか…に非ず</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">普通の場合（時間的）ちようど</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">ちようど直ぐ right here.</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade deshlb, weil 等（前置的接続詞）</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade....皮肉 仏の<u>bien</u></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade so wie～</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">ちょうど（時間的ならざるもの）</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Adverbal さヘ一一一する。</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">überhaupt nicht = gar nicht</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>nicht gar</u> nicht so gar.<br />ganzと同じ（肯定の際）<br />und gar = nun gar, vollends.</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>gar</u></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar zuとgar so gal=sogar.gar［sogar］［wohigar］.</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">sogar wohl gar</div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so gar gar nicht.</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］ ganz</div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar nicht gar kein ganz und gar gut.（nicht....gut）</div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2">21-5B</div><div class="col-8">［雜］<u>erst</u></div><div class="col-2">120-165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">わざわざ <u>vollende</u>（否定の強調）</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">それこそ（大変なことになる） vollends.<br />況ンヤ、ニ至ッテハ</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">先以て…して掛かる。（時聞的） erst <u>noch</u></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「やっと」</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst recht. 又はerstのみ。 nun erst recht.</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wenn....［nur］erst 云々した暁にはが最後</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">試みに…せしめよ。（まづ…）</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst「はやく」に近し</div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben（最も軽い場合）ほとんど無意味=nur<br />［雑］ <u>eben</u></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben（Litotes）あながち…に非ず。<br />大して、…といふほどでもない。<br />否定詞を伴ふもの。</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">つまり、とりも直ず。</div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">というのは（denn） つまり（大した仕細なし!）</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht eben（大して）（必ずしも）</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben doch.（つまりやっぱり）</div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">同じ概念に逆戻って強調するeben.<br />［それより言ひ様がない」時</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">申すまでもなく。</div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben=gerade.</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>etwa</u></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht etwa....sondern.</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">etwa ....なぞと（結局が否定）</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…とでも（思ふか、等）=疑問文の</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eventuell.（疑問文に非ざる場合）</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">etwa=sagen wirたとへば</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">概ね、凡そ。</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">殆ど無くてもよい際の erst</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>etwas</u></div><div class="col-2">165</div></div></div>');