document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">20-1B</div><div class="col-8">schon</div><div class="col-2">1-101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">順序（論理的9…となると既に</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">前置接続詞的。</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">大丈夫、もう、まあ。「いづれ」楽観の表現</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">こうなって来るとこるなどうしても「もう」…仕方がない どうも</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gleich, nur, gleich.doch.</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文に（auchと同じ） 侮蔑的。<br />「いづれ」大したものじゃない。</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">なあに、（負け惜しみ、etc）<br />begütigend 安堵させるため。 （ja schon）<br />認める（たしかに）「まあ」</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">驚く勿れ等 「とても」 「そりやアとても」</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">命令法と共に。「まあどうぞ」御勘弁遊ばせて等。</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">況んや…に至っては（schon gar nicht.）</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">既に既に…（尖置）</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">肯定を強めるもの。（勿論）</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">既に云々せんとしたるところ</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Ich will schon! schon lieber, schon wieder</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Es müsste schon mit dem Teufe1 zugehen, <br />wenn....sollte</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so（ge1egent1ich）=ich weiss nicht wie....<br />なんだか</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">その通りで（よろしい、等）形容詞的</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">比較Wieの後に来るso<br />さう言う風に（動詞につ&lt;）<u>thus</u></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so vier, so gut, so lange 非常に（一般項）</div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">斯&lt;の如くにしては（仮定的）</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">古典的so. ［so c1assicum］ wohl</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">仏語のtant....（aussiニ非ズ） 後に来るso....<br />sonst</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">然らずんば さもなければ</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so auch so 接続詞としてのso</div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2">20-2B</div><div class="col-8">Nur <u>nur noch.</u>. （<u>nicht</u> <u>mehr</u>の肯定）</div><div class="col-2">102-160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問のnur.（不審る）（反語にも）<br />（あきれる時も）<br />願望のnur. 心配のnur</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nur［dann］....wenn. nur zu....（nur soも同じ）</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nur（leider）但し</div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">普通のnur</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">とにかく--<u>だけ</u>の.（nur eben）</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wo nur</u>....（allein） <u>der nur</u>....（a11ein）<br />前置詞的接続詞として。<br />せめて（wenigstens.）</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">命令法と共に<u>nur</u>.（まアいいから）（まあ）</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">前置詞的接続詞としてのnur, alleinは、必ずしも名詞等の直前直後にはない。</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nur［noch］（ただますます…なるぱかりだ）<br />「もはや…」のnur nochとはちがふ。</div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…にして始めて…なる… wie…nur</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">, allein）</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">微妙なnur（悪い方の意）</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">ただ…した<u>ばっかりに</u> 普通の<u>nur so</u></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2">20-3B</div><div class="col-8">Noch</div><div class="col-2">161-246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>noch lange nicht</u>.（D.Kein） なほ（一層）のnoc&lt;（比較級と）</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">sogar［前置的場合のみ］最高級</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">sogar…時問的</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Das fehlte noch. Das fehlte noch gerade<br />と接続法。</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">大丈夫、その中に（<u>schon</u>） <u>noch einmal</u><br />その内にいづれ、きっと</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nochの先置（まだ、今のところは）仮定強調的</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">準否定詞kaum, wenig, selten, nur,等の際のmehrはnochとなる。</div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">危なく、際どくも（やっと間に合ふ）</div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wahr1ich</u>［間投文内のnoch］</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">noch nachträglich.（そのうちに、いづれ、あとになって、後日）</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">むしろ。まだしも。weinigstens.</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>noch so</u> …［認容的］=<u>auch</u> <u>noch</u> <u>so</u>.</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wann...._<u>noch</u>（殆んど無意）<br />まだしも。まあ…さう言ってもまあ</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">古い物が案外現在と関係ある事を示すnoch.</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">schon.（noch vor, noch ehe）<u>very</u></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">時聞的。「すぐに、早速」<u>noch</u> heute</div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［sogar］<u>noch</u></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文中のnoch</div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">noch（dazu）剰さへ</div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">まづどうにか</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Zum Kuckuk noch mal!</div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2">20-4B</div><div class="col-8">sehr</div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2">20-5B</div><div class="col-8">selbst<br /><u>selbst</u>と<u>selber</u> その他self=の複合詞<br />Hier ist er selbst!（om Person）<br />登場人物をmeldenする時。</div><div class="col-2">248-255</div></div>');
document.write('<div class="row"><div class="col-2">20-6R</div><div class="col-8">［und］soそういうわけで <u>so</u>〈z.B.）</div><div class="col-2">256-259</div></div>');
document.write('<div class="row"><div class="col-2">20-7B</div><div class="col-8">nun</div><div class="col-2">260-296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">辛抱を切らした際に出る<u>nun</u></div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">間投詞の<u>nun</u>（<ruby>惘<rt>あき</rt></ruby>れた時）</div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nanu!</div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">認容文の<u>nun</u></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nun ja, nun freilich,</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>nun einmal</u>,<u>einmal</u>,</div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nun, nun! nu, nu!（宥める時） begütigend.</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><ruby>扠<rt>さ</rt></ruby>て、ところで。</div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nun denn 然らば <u>nun</u> also</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">....nun（eben）</div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nun wohl eben nicht. nun einmal</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2">20-8B</div><div class="col-8">und</div><div class="col-2">297-331</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">dann, soの意 さうすれば</div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">しかも（trotzdem） undと定形</div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">und（doch）.... …なのだが。</div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>oder</u></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">darum....であったので、因由、（und［so］）</div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">それに…［”しかも”とはちがふ］</div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">殆ど無意味なつなぎ方</div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">undを何度も用ふ polysyndeton</div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>undを最後に</u>（普通）</div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">undなく。いわゆるAsyndeton</div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">近くして遠からず。</div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">逆順（一般的な宣言があと）</div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2">20-9B</div><div class="col-8">wohl</div><div class="col-2">332-379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">まあ、まず（渋々の承諾）, 「恐らくは」の変態。</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">おそらくは、思うに。</div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文内のwohl.</div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Pleonastisches "Wohl".云々するの<u>であった</u> 頭など振りけり <u>叙述的</u>の場合多し</div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">習慣性のwohl「よく」あった、等</div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wohl aber</u></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">なるほど確かに……であらう！　認容<br />さうであらうとも！　尤もでござる</div><div class="col-2">352</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>ungefähr</u>，又は「裕に」gut（数詞）</div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wohl</u>（=zwahr）-aber-</div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Es ist sehr wohl mÖglich.<br />たしかに、とうも（可能性濃厚）</div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］wieder, wiederum</div><div class="col-2">360</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>zurück</u></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wieder einmal</u></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">doch wieder（さうかとおもふとまた）</div><div class="col-2">363</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wiederum, seinerseits</div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文または間投文内のwieder</div><div class="col-2">367</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wieder=immer やはり、同様</div><div class="col-2">368</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wiederとwiederum（”反対に”のwiederumもあり）</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">schon wieder.<br />［雑］ <u>was</u><br />何</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">文意を受ける関係的was</div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wasの意のwas. "wozu"</div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">名詞化形容詞を伴ふ疑問の<u>was</u>.</div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">was（wie）---!</div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］ <u>wenig</u></div><div class="col-2">375</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］ <u>wo</u></div><div class="col-2">377</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係代名詞（空間的）</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係代名詞（時間的）</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Wo <u>nur</u>; wo <u>allein</u>.</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］ <u>wer</u></div><div class="col-2">379</div></div></div>');