document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">21-1B</div><div class="col-8">［雑］<u>doch</u>1-102</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">副文章内のdoch（…筈の、…の癖に）</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">doch［woh1］勿論…だらうじゃないか。</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">どうも！</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">その癖。 <u>doch</u>, <u>und doch</u> それでもやはり</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">不審る。（主文章）…のだがなあ。</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「やっぱり。」</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">trotzdem. やはり。 さすがだ</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">doch［wohl］nicht.（まさか）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">doch（zu...）いくらなんでもあまり</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">jaと同じ（強めるため）…つてば！ etc.</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">願望の意（konj.）</div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>どうぞ</u> <u>bitte</u>. （f1ehend.）</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Lteinisches "Nonne"</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">転置とdochが、dennを用ふるに等しくなる。</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">不審りのdoch（疑問文に）不審、間投的</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">doch語考</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">22-2B</div><div class="col-8">［雑］<u>da</u></div><div class="col-2">103-135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>vergegenwärtigend</u></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">其處へ持って来ると。</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係文中の_____</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">それはどうも.…さうだとすると…これは…</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係文中（fast p1eonastisch）</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">具体的叙述を開始するための機みの da.</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">da ”<u>その點なら</u>。”</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">voilà.</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">da....also....さうするとつまり</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">vergegenwärtigend <u>Le voilà</u></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>Da</u> hingisch<br />（und war\'s mir mit grausen bewusst）</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">hierと同じ</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">darauf, darin等のdar-に関する一般問題</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雜］<u>das</u></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">感嘆的das.感嘆的非人称主語のdas</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">dass....das</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Das ist alles. voilà tout.</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Das ist eine Schmied <u>hier</u></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">強い das ist ［仏］＝C\'est là.</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2">22-3B</div><div class="col-8"><u>alle</u></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2">22-4B</div><div class="col-8"><u>Also</u>（接続詞に）</div><div class="col-2">137-146</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">説明（…というのは即ち）</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">繰返しの際のalso</div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">also wieder auf sein Thema kommend:</div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2">22-5B</div><div class="col-8"><u>auch</u> Das war auch alles.<br />しかしそれだけのことだった。</div><div class="col-2">147-152</div></div>');
document.write('<div class="row"><div class="col-2">22-6B</div><div class="col-8">auch</div><div class="col-2">153-216</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［希］καιの微妙な用法<br />日本語の「も」と対比して<br />それに、しやっくり「も」止んだしするから…云々</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">前置的普通のauch</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">0h....auch?</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>同概念を対照するauch</u>.</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">auch -- nuch. ［も」、「なほ」</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">auch それが<u>また</u>本当だ</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（dann）auch <u>dann</u>の意。（その上に又、）</div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">auch noch おまけに 時間的</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">denn <u>auch</u>［果たして］の略 予期したごとく。（<u>道理</u>でというauch）</div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">den Teufel <u>auch</u>!</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>aber auch</u></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問詞とauch.（denn）</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">auch nur（或はauch, 又は単にnur）</div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">auch（それに）並列的接続詞と倒置<br />それに…云々しなければなりませんし。</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">反語的な間投文に（spöttelnd）</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">間投文に。（皮肉モコモルコトアリ）批評的。</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>wenn</u>....auch....!（但し…）［Wunschsatz］<br />auch=nur</div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">だからまた。（多少<u>因由</u>的）</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2">22-7B</div><div class="col-8">［雑］<u>auch</u></div><div class="col-2">217-244</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">aber auch（wirklich） 懸値なし！</div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…です<u>が</u>。（極く軽きaber）</div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（nun）aber ところで、（対照の）</div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">oder aber（それとも）</div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">aber= und zwar</div><div class="col-2">230</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">aber auch（然し同時にまた…）</div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">間投の<u>aber</u>（ja aber）</div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">aber= <u>und</u> autem</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">aber= <u>sondern</u> wohr aber</div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2">22-18B</div><div class="col-8"><u>Aber</u></div><div class="col-2">245-276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">まことに失礼ではございますが等</div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>denn</u></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">如何となれぱ</div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">---たい（？）</div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>denn auch</u> 期待に違はざるを謂ふ<br />もちろん、当然、安の條、いよいよ</div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">後続的（dann）の意を強める denn</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">後続のdennの代りにdannを用ひた例</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">denn=also.さらば、然らば、 ［so....denn］</div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">denn {durchaus doch auch}</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so....denn.</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so....denn!<br />さう言ふわけで、とにかくまあさういふ風にして…</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>dann</u></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">fas tp1eonastisch</div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">dann 仏の<u>ensuite</u></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">dann: =so</div><div class="col-2">276</div></div></div>');