document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">21-1B</div><div class="col-8"><u>immer</u></a></div><div class="col-2">1-20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer 常に。</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">認容的<u>immer</u></a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">jedenfalls. immerhin（併しいづれにせよ）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer（toujours）<u>やはり</u> 今までに従って、<br />gleichfalls.</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">命令法と共に。</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">空間的。（immer gradaus）</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">immer = je 各々</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］irgend（＝） nirgend（s）</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">21-2B</div><div class="col-8">［雑］<u>mal</u>と<u>einmal</u></a></div><div class="col-2">21-49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（nun）einmal「どうせ」</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst mal wieder mal</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">zunächst einmal. erst einmal vorläufig einmal</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nlcht einmal</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wieder einmal（erst einmal）</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>nicht einmal</u>.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">endlich einmal schliesslich einmal</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade einmal gelegentlich einmal<br />später einmal たまに いつか一度</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">vorlänglig einmal zunächst einmal</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">21-3B</div><div class="col-8">［雑］<u>ja</u></a></div><div class="col-2">50-87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…ja…！（どうも畏れ入った）　実に！</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">自明の事柄として言ふ際。</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「否むしろ」（wo nicht gar, と同じ）<br />Man könnte fast sagen.→（並列接続的）</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>ja</u> nicht.（金輪際） ja（命令法と）<br /><u>nur ja</u></a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">関係文中のja（doch）</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">疑問文の先頭に（せき込むトキ） ja［aber］</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">如何となれば…、それが証拠に。 auchに似たり</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">反語的「…ではないか！」（助勢詞）「ハア」</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">肯定命令法とja.</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>je</u></a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">von je, von jeher.</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je nachdem，（副詞的、接続詞的）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je（nieの反対）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">je <u>各々</u> <u>respektive</u>.ja wohl? da ja....<br />ja（うるさいとき、よい加減な返事）<br /><u>ja aber</u></a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">21-4B</div><div class="col-8"><u>gerade</u></a></div><div class="col-2">88-119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">noch gerade....［genug.］</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">just.（前置的） ちようど</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">かへって…が 「が」</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">丁度（偶然） <u>ausgerechnet</u>.</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht gerade必ずしも…と言ふ程ではない。<br />-1itotes- まさか…に非ず</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">普通の場合（時間的）ちようど</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">ちようど直ぐ right here.</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade deshlb, weil 等（前置的接続詞）</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade....皮肉 仏の<u>bien</u></a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gerade so wie～</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">ちょうど（時間的ならざるもの）</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">Adverbal さヘ一一一する。</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">überhaupt nicht = gar nicht</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>nicht gar</u> nicht so gar.<br />ganzと同じ（肯定の際）<br />und gar = nun gar, vollends.</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><u>gar</u></a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar zuとgar so gal=sogar.gar［sogar］［wohigar］.</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">sogar wohl gar</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">so gar gar nicht.</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］ ganz</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">gar nicht gar kein ganz und gar gut.（nicht....gut）</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2">21-5B</div><div class="col-8">［雜］<u>erst</u></a></div><div class="col-2">120-165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">わざわざ <u>vollende</u>（否定の強調）</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">それこそ（大変なことになる） vollends.<br />況ンヤ、ニ至ッテハ</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">先以て…して掛かる。（時聞的） erst <u>noch</u></a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">「やっと」</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst recht. 又はerstのみ。 nun erst recht.</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">wenn....［nur］erst 云々した暁にはが最後</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">試みに…せしめよ。（まづ…）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">erst「はやく」に近し</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben（最も軽い場合）ほとんど無意味=nur<br />［雑］ <u>eben</u></a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben（Litotes）あながち…に非ず。<br />大して、…といふほどでもない。<br />否定詞を伴ふもの。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">つまり、とりも直ず。</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">というのは（denn） つまり（大した仕細なし!）</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht eben（大して）（必ずしも）</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben doch.（つまりやっぱり）</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">同じ概念に逆戻って強調するeben.<br />［それより言ひ様がない」時</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">申すまでもなく。</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eben=gerade.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>etwa</u></a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">nicht etwa....sondern.</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">etwa ....なぞと（結局が否定）</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">…とでも（思ふか、等）=疑問文の</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">eventuell.（疑問文に非ざる場合）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">etwa=sagen wirたとへば</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">概ね、凡そ。</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">殆ど無くてもよい際の erst</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［雑］<u>etwas</u></a></div><div class="col-2">165</div></div></div>');