document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">25-1R</div><div class="col-8">wenn....nicht.... 或は云々することもあるべし<br />....es sei denn,daß....<br />［MHD］ daz, dazの構造：<br />Verweisung<br />Konsekutiv=wenn<br />wennと時称 Modusの問題一括</a></div><div class="col-2">1-3</div></div>');
document.write('<div class="row"><div class="col-2">25-2B</div><div class="col-8">接続詞補足 1.einmal（…云々するや否や、したる以上…） 2.<u>als ob</u>,［tout comme si］</a></div><div class="col-2">4-5</div></div>');
document.write('<div class="row"><div class="col-2">25-3B</div><div class="col-8">wenn....nur.... pourvu que</a></div><div class="col-2">6-10\'</div></div>');
document.write('<div class="row"><div class="col-2">25-4R</div><div class="col-8">一概念一用語の圧釈、Wenn<br />wenn（falls） …の場合のために言うが<br />およろしければ等 （会話）<br />wie wenn....?</a></div><div class="col-2">11-23</div></div>');
document.write('<div class="row"><div class="col-2">25-5B</div><div class="col-8">…する時の。 adnominal（時間関係を存す）</a></div><div class="col-2">24-34</div></div>');
document.write('<div class="row"><div class="col-2">25-6B</div><div class="col-8"><u>普通のwenn</u> PARADIGMA</a></div><div class="col-2">35-38</div></div>');
document.write('<div class="row"><div class="col-2">25-7B</div><div class="col-8">時間性を帯びた<u>wenn</u>（im Augenblick）</a></div><div class="col-2">39-40</div></div>');
document.write('<div class="row"><div class="col-2">25-8B</div><div class="col-8">引用的・指摘的［ADVERSATIV］</a></div><div class="col-2">41-45</div></div>');
document.write('<div class="row"><div class="col-2">25-9B</div><div class="col-8">［英］ unless</a></div><div class="col-2">46-48</div></div>');
document.write('<div class="row"><div class="col-2">25-10B</div><div class="col-8">加項。wenn.</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">25-11B</div><div class="col-8"> </a></div><div class="col-2">50-100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］もしも。…れば。</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］対比の型 1.so sehr... so....</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］-Dass-</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］nichtに注意（直接法ゆえ）</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］daßを使はず並立せしめる際<br />（直接法を用ひる場合）</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］damitの意（挿入文ならず）</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］daßと直接法。</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］daßの代りにum zu或ひは単に不定法とzuを用ひることもあり。</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］事程左様に（daßのみ）（及びso daß）<br />規定的及び中間現象</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］規定的</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］0hne daß.</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］damit....（…するために言うが）挿入的</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2">25-12B</div><div class="col-8">Daß dich die Pest!</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">25-13B</div><div class="col-8">挿入のdaß.</a></div><div class="col-2">102-108</div></div>');
document.write('<div class="row"><div class="col-2">25-14B</div><div class="col-8">dasはdasなること。</a></div><div class="col-2">109-114</div></div>');
document.write('<div class="row"><div class="col-2">25-15B</div><div class="col-8">nicht,daß....<u>nicht</u> …しなかったといふわけではないが、勿論…することはしたがね。（zwar....）</a></div><div class="col-2">115-122</div></div>');
document.write('<div class="row"><div class="col-2">25-16B</div><div class="col-8">höchstens, daß....其他例外的のもの à peine si..</a></div><div class="col-2">123-128</div></div>');
document.write('<div class="row"><div class="col-2">25-17R</div><div class="col-8"><u>nur daß</u>ただ……だけの<u>話</u>だ<br />vorausgesetzt, daß....<br />anstatt daß, statt daß.<br />（währendと同意にも用ふ）<br />編者注：このほか11件あり。</a></div><div class="col-2">129-141</div></div>');
document.write('<div class="row"><div class="col-2">25-18B</div><div class="col-8">問投句的daß--!</a></div><div class="col-2">142-144</div></div>');
document.write('<div class="row"><div class="col-2">25-19B</div><div class="col-8">副詞化するdaß----</a></div><div class="col-2">145-147</div></div>');
document.write('<div class="row"><div class="col-2">25-20B</div><div class="col-8">Daß dich!［<u>Apokope</u>］</a></div><div class="col-2">148-149</div></div>');
document.write('<div class="row"><div class="col-2">25-21B</div><div class="col-8"><u>adnominalのdaß</u></a></div><div class="col-2">150-152</div></div>');
document.write('<div class="row"><div class="col-2">25-22B</div><div class="col-8">daß = 0hne daß. （quin的）</a></div><div class="col-2">153-165</div></div>');
document.write('<div class="row"><div class="col-2">25-23B</div><div class="col-8">Quelque sotte, ma foi !<br />ich müßte ein Narrsein !</a></div><div class="col-2">166-174</div></div>');
document.write('<div class="row"><div class="col-2">25-24B</div><div class="col-8">Quelque sotte !</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2">25-25B</div><div class="col-8">移轍的現象としてのdassの特殊用法<br />同じことをもう一度言い直す型</a></div><div class="col-2">176-177</div></div>');
document.write('<div class="row"><div class="col-2">25-26B</div><div class="col-8">daß ”と言って、とての意多し<br />主文章にdeswegen,darüber、前置詞をsubintellige</a></div><div class="col-2">178-184</div></div>');
document.write('<div class="row"><div class="col-2">25-27B</div><div class="col-8">daß = ut,（damit）</a></div><div class="col-2">185-187</div></div>');
document.write('<div class="row"><div class="col-2">25-28B</div><div class="col-8">daß［ut....=eret］ damit. …せんとして。<br />時称一致の問題。</a></div><div class="col-2">188-199</div></div>');
document.write('<div class="row"><div class="col-2">25-29R</div><div class="col-8">daß es［nur so］eine Art hat.<br />daßの用ひ方のアイマイなもの<br />bis（普通の）<br />餘計なdaß bis daß bevor daß jenachdem daß<br />編者注：このほか6件あり。</a></div><div class="col-2">200-208</div></div>');
document.write('<div class="row"><div class="col-2">25-30B</div><div class="col-8"> </a></div><div class="col-2">209-250</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］-bis-</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］遂に。</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］um so mehr....da</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］wennにも同じものあり …であるに拘らず</a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］da=wo 関係的 （adnominal, adverbal）</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］wie....denn</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］wie.</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］....であると同様に wie（sowie） 並立的</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2">25-31R</div><div class="col-8">wie<br />関係詞様（adnominai）な<u>wie</u>, <u>so wie</u><br />wie billig = billigerweise<br />wieと同意のmaßen</a></div><div class="col-2">251-252</div></div>');
document.write('<div class="row"><div class="col-2">25-32B</div><div class="col-8">wie Sie wollen. as you like it.</a></div><div class="col-2">253-256</div></div>');
document.write('<div class="row"><div class="col-2">25-33B</div><div class="col-8">顛末と現状</a></div><div class="col-2">257-260</div></div>');
document.write('<div class="row"><div class="col-2">25-34R</div><div class="col-8">現場のwie<br />wie = sowie …云々すると…（…である）<br />…云々するにつれて…</a></div><div class="col-2">261-267</div></div>');
document.write('<div class="row"><div class="col-2">25-35B</div><div class="col-8">wie ich es bin, 等 （wie da sind....）</a></div><div class="col-2">268-275</div></div>');
document.write('<div class="row"><div class="col-2">25-36R</div><div class="col-8">drive as he would<br /><u>Wie</u> dies <u>hier</u> der Fall ist</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2">25-37B</div><div class="col-8">hungrig wie er war等</a></div><div class="col-2">277-286</div></div>');
document.write('<div class="row"><div class="col-2">25-38B</div><div class="col-8">wie er gekommen war等</a></div><div class="col-2">287-293</div></div>');
document.write('<div class="row"><div class="col-2">25-39R</div><div class="col-8">um zu in order to in oder that<br />仏 en vue de</a></div><div class="col-2">294-301</div></div>');
document.write('<div class="row"><div class="col-2">25-40B</div><div class="col-8">［仏］ histoire de...</a></div><div class="col-2">302-303</div></div>');
document.write('<div class="row"><div class="col-2">25-41B</div><div class="col-8">um</a></div><div class="col-2">304-305</div></div>');
document.write('<div class="row"><div class="col-2">25-42B</div><div class="col-8">後続のum....zu</a></div><div class="col-2">306-311</div></div>');
document.write('<div class="row"><div class="col-2">25-43B</div><div class="col-8">意外な結果ではないがやはり後続的意型<br />”云々して云々する″型</a></div><div class="col-2">312-319</div></div>');
document.write('<div class="row"><div class="col-2">25-44B</div><div class="col-8"> </a></div><div class="col-2">320-392</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］純粋に後続を指すum（直後を指す）</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］teleologische Auslegung.<br />云々「して」云々している（対照のum.）</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］「…であるとは」と言ふdaßと同じ用法</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］目的と結果との中間現象（皮肉が現れる）</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］weil</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］Warum! weil.</a></div><div class="col-2">363</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］dennと同</a></div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］weii=während（遅くならなぃぅちに…しておく）</a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］Sintemal,其他古形一般</a></div><div class="col-2">376</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］weil, puisque....（da....doch）</a></div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Bis.</a></div><div class="col-2">383</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］規定的bis.</a></div><div class="col-2">384</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］Solangel----bis----</a></div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］文頭のbis</a></div><div class="col-2">390</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］wenn</a></div><div class="col-2">391</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］wann=als</a></div><div class="col-2">392</div></div>');
document.write('<div class="row"><div class="col-2">25-45R</div><div class="col-8">wenn anders.</a></div><div class="col-2">393-396</div></div>');
document.write('<div class="row"><div class="col-2">25-46B</div><div class="col-8">挿入的（um--zu）sc,［anders］<br /><u>wenn anders</u> = vorausgesetzt,<br />（andersは仏語のd\'ailleursなる可し）<br />si elles sont bonnes d\'ailleurs等</a></div><div class="col-2">397-399</div></div>');
document.write('<div class="row"><div class="col-2">25-47R</div><div class="col-8">wenn=<u>daß</u> zu + 不定法<br />wenn（um zuの挿入句と同じ）<br />wenn=daß （dadurch....等と対する時は殊に明瞭）</a></div><div class="col-2">400-403</div></div>');
document.write('<div class="row"><div class="col-2">25-48B</div><div class="col-8"> </a></div><div class="col-2">404-499</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］殆んどdaß（zu+不定法）と同じ。<br />（事実を指すwennの順序が上下に変ったもの）</a></div><div class="col-2">404</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］「もしも」と「wenn」と二つとも含む（一般的宣言）</a></div><div class="col-2">405</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］sooft</a></div><div class="col-2">406</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］wenn = Während, da doch</a></div><div class="col-2">407</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］wenn（wannの代り）</a></div><div class="col-2">412</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］nur dann, wenn.... erst dann, wenn</a></div><div class="col-2">413</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］wenn....!</a></div><div class="col-2">414</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］wennと省略文</a></div><div class="col-2">421</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］<u>Während</u>. 時間的derweil<br />Währendとsolangeとの差</a></div><div class="col-2">422</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］時間的と同時に対立的</a></div><div class="col-2">425</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］純粋に論理的対立</a></div><div class="col-2">426</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］殆ど0bgleich</a></div><div class="col-2">431</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］Indem 同時性</a></div><div class="col-2">432</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］相反的indem 同時と対比 aduersativ.</a></div><div class="col-2">436</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］indem = weil</a></div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］indem = dadurch, daß....</a></div><div class="col-2">440</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］wie = sobald, sowie, als</a></div><div class="col-2">442</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］［SO］WIE DU BIST.</a></div><div class="col-2">461</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］wie</a></div><div class="col-2">471</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］wie denn, ［überhaupt］</a></div><div class="col-2">474</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］…の所謂る …する所によれば …する如くんば</a></div><div class="col-2">475</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］Solange（alsの問題）</a></div><div class="col-2">485</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］…せぬ問に（bevor） während, weil</a></div><div class="col-2">493</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］Sooft（alsの問題あり）</a></div><div class="col-2">494</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］soviel_（soweit）（…限り）</a></div><div class="col-2">499</div></div>');
document.write('<div class="row"><div class="col-2">25-49B</div><div class="col-8">［英］directly = as soon as</a></div><div class="col-2">500</div></div>');
document.write('<div class="row"><div class="col-2">25-50B</div><div class="col-8">sobald</a></div><div class="col-2">501-508</div></div>');
document.write('<div class="row"><div class="col-2">25-51R</div><div class="col-8">Sobald（alsの問題あり）<br />So wie（sobald）<br />zumal</a></div><div class="col-2">509-514</div></div>');
document.write('<div class="row"><div class="col-2">25-52B</div><div class="col-8"> </a></div><div class="col-2">515-638</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］zumal</a></div><div class="col-2">515</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］falls</a></div><div class="col-2">517</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］im fall（für den Fall, <u>daß</u>....）</a></div><div class="col-2">518</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］nun</a></div><div class="col-2">524</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］Seit（時称）</a></div><div class="col-2">532</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］Trotzdem</a></div><div class="col-2">532</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Seitdem</a></div><div class="col-2">636</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］nachdem nunと同じ（…したる今日）<br />（したる以上は）</a></div><div class="col-2">538</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］nachdem</a></div><div class="col-2">542</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］<u>je nachdem</u>（単にnachdemもあり）</a></div><div class="col-2">543</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11jehe（及びehe noch, before even, avant même）</a></div><div class="col-2">547</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］sowie（種々）</a></div><div class="col-2">551</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］bevor</a></div><div class="col-2">552</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］<u>sofern, sowei</u>t, ［Aanminalな場合あり！］</a></div><div class="col-2">557</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］soweit, soviel, sofern wofern</a></div><div class="col-2">558</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］sowet（制限ならざるもの）</a></div><div class="col-2">564</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］insofern, inwiefern.</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］sofern = wenn.</a></div><div class="col-2">569</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］insoweit</a></div><div class="col-2">570</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］statt, anstatt. <u>statt daß</u></a></div><div class="col-2">571</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］挿入文的になる。（まだ多少umの元意で通ずる際）</a></div><div class="col-2">574</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］…するとすれぱ</a></div><div class="col-2">574</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］zu....um, genug....um.</a></div><div class="col-2">575</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］…するほどに、（adverbal）<br />…するほどの、（adnominal）（程度を指す）</a></div><div class="col-2">576</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］<u>w o</u> 空間的 wo----da....</a></div><div class="col-2">576</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［26］関係代名詞としてのwo<br />名詞にかかるwoとその結合（worin, worauf, etc.）</a></div><div class="col-2">577</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［27］空間的よりはむしろ場合、時（wenn）</a></div><div class="col-2">578</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［28］wo, wo doch=da doch</a></div><div class="col-2">585</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［29］so = wenn so Gott will</a></div><div class="col-2">589</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［30］so = wie</a></div><div class="col-2">590</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［31］ohne</a></div><div class="col-2">591</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［32］ohne zu, ohne daß 普通の。（現在と）</a></div><div class="col-2">592</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［33］挿入的［別に…云々しようといふ譯ではないが］</a></div><div class="col-2">598</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［34］ohne（daß）相反的「しかも」云々、<br />「…としても、…しない」<br />「必ずしも云々といふのでないにしても」</a></div><div class="col-2">599</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［35］damit 1.<u>sodaß</u>を以ても表現し得ることあり<br />2.単にdaß→ 3.auf daß→</a></div><div class="col-2">605</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［36］挿入のdamit daßにも同意型あり！</a></div><div class="col-2">616</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［37］Als 普通のals（過去） 英 as 多し</a></div><div class="col-2">617</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［38］alsと現在 （historical presence）</a></div><div class="col-2">623</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［39］als（後続的）</a></div><div class="col-2">624</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［40］als=wie（zum Beispiel, etwa.）</a></div><div class="col-2">625</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［41］in dem Grade....als. umso～als....<br />insofern als, umsomehr als等のals</a></div><div class="col-2">632</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［42］<u>auf daß</u> 目的 ［英］in order that</a></div><div class="col-2">638</div></div>');
document.write('<div class="row"><div class="col-2">25-53R</div><div class="col-8">widrigenfalls等<br />aufdass</a></div><div class="col-2">639-543</div></div>');
document.write('<div class="row"><div class="col-2">25-54B</div><div class="col-8">Adnominalな<u>als ob</u></a></div><div class="col-2">644-647</div></div>');
document.write('<div class="row"><div class="col-2">25-55B</div><div class="col-8">wie, wenn...!</a></div><div class="col-2">648</div></div>');
document.write('<div class="row"><div class="col-2">25-56B</div><div class="col-8"><u>unerachtet</u>, <u>ungeachtet</u>.</a></div><div class="col-2">649</div></div>');
document.write('<div class="row"><div class="col-2">25-57B</div><div class="col-8">obの独立文章</a></div><div class="col-2">650-653</div></div>');
document.write('<div class="row"><div class="col-2">25-58R</div><div class="col-8">obの史的関係 ob = wenn<br />wie （als） soie<br />wie....denn<br />dieweil, derweil.<br />demzufolge<br />wie（云々すると…） 云々するや否や<br />編者注：このほか7件あり。</a></div><div class="col-2">654-667</div></div>');
document.write('<div class="row"><div class="col-2">25-59B</div><div class="col-8">ob［普通の場合］</a></div><div class="col-2">668-672</div></div>');
document.write('<div class="row"><div class="col-2">25-60B</div><div class="col-8">［古］maßen wie....denn....と同様に<br />（simplizに多し）</a></div><div class="col-2">673</div></div>');
document.write('<div class="row"><div class="col-2">25-61B</div><div class="col-8">云々するにつれて =je nachdem.（云々次第で）<br />云々するに従って （wie es kommt）</a></div><div class="col-2">674-676</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">波にゆらるるままに</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">25-62B</div><div class="col-8">daher</a></div><div class="col-2">677</div></div>');
document.write('<div class="row"><div class="col-2">25-63R</div><div class="col-8">wie（どうしたら云々できるかと……くろうする、など）</a></div><div class="col-2">678-679</div></div>');
document.write('<div class="row"><div class="col-2">25-64B</div><div class="col-8">adverbalなる現場描写的 wie appositiv.</a></div><div class="col-2">680</div></div></div>');