document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">27-1B</div><div class="col-8"><a href="../027-1/s0001.html">damitかmit ihrか</a></div><div class="col-2">1-2</div></div>');
document.write('<div class="row"><div class="col-2">27-2R</div><div class="col-8"><a href="../027-1/s0003.html">尊称の代名詞としてのDieselbe（n）<br />Höchst=dieselben等<br />［Das］複数的観念を考へる如く思われる時<br />（beid<u>e</u>s）等の用法と同じ<br />allerhand（=Alleriei） 名詞的にも附加的にも<br />Mein Rat is <u>der</u> （Das ist mein Rat.）<br /><u>dieser</u></a></div><div class="col-2">3-4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0003.html"> </a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">27-3B</div><div class="col-8"><a href="../027-1/s0005.html">der derとかdie dieとかの重複する場合</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2">27-4R</div><div class="col-8"><a href="../027-1/s0006.html">［英］<u>that</u> intended = <u>What</u> was intended<br />damit等は「者」型名詞（人・生物）に用いない<br />その例外［MHD］</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">27-5B</div><div class="col-8"><a href="../027-1/s0007.html"><u>That</u> long 限度のsoと同</a></div><div class="col-2">7-9</div></div>');
document.write('<div class="row"><div class="col-2">27-6B</div><div class="col-8"><a href="../027-1/s0010.html"><u>Im</u> Kaffee sit Zucker <u>dr土n</u>.</a></div><div class="col-2">10-11</div></div>');
document.write('<div class="row"><div class="col-2">27-7B</div><div class="col-8"><a href="../027-1/s0012.html">das（雑）</a></div><div class="col-2">12-26</div></div>');
document.write('<div class="row"><div class="col-2">27-8B</div><div class="col-8"><a href="../027-1/s0027.html"><u>Darein</u>を用ひる動詞</a></div><div class="col-2">27-28</div></div>');
document.write('<div class="row"><div class="col-2">27-9B</div><div class="col-8"><a href="../027-1/s0029.html">先行代名詞darüber等の省略</a></div><div class="col-2">29-40</div></div>');
document.write('<div class="row"><div class="col-2">27-10B</div><div class="col-8"><a href="../027-1/s0041.html">［MHD］iht aught</a></div><div class="col-2">41-49</div></div>');
document.write('<div class="row"><div class="col-2">27-11B</div><div class="col-8"><a href="../027-1/s0050.html">uunsereiner unsereins</a></div><div class="col-2">50-52</div></div>');
document.write('<div class="row"><div class="col-2">27-12B</div><div class="col-8"><a href="../027-1/s0053.html">「左様な」の諸型</a></div><div class="col-2">53-59</div></div>');
document.write('<div class="row"><div class="col-2">27-13B</div><div class="col-8"><a href="../027-1/s0053.html">desgleichen</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">27-14B</div><div class="col-8"><a href="../027-1/s0064.html">dessenの用法［及びdes］<br />1.Es gibt <u>deren</u>, die....<br />2.仏の<u>en</u>, 伊のne</a></div><div class="col-2">64-69</div></div>');
document.write('<div class="row"><div class="col-2">27-15B</div><div class="col-8"><a href="../027-1/s0070.html">不定数詞 viel, mehr, nichts等々</a></div><div class="col-2">70-72</div></div>');
document.write('<div class="row"><div class="col-2">27-16R</div><div class="col-8"><a href="../027-1/s0073.html">gewißく或種の）<br />die andern（他人）<br />定冠詞と共に用ひた異例。</a></div><div class="col-2">73-74</div></div>');
document.write('<div class="row"><div class="col-2">27-17B</div><div class="col-8"><a href="../027-1/s0075.html">（A）いづれも each 二者中の<br />（B）いづれか eiher</a></div><div class="col-2">75-81</div></div>');
document.write('<div class="row"><div class="col-2">27-18R</div><div class="col-8"><a href="../027-1/s0082.html"><u>Einer</u> muß weichen. ［<u>どちらか</u>....］<br />dessen, eines, keines等を含む二格の重畳<br />誰かeiner不定詞。と規定詞、句。<br />［一方は、他は］einer, der andere, der eine, <br />der andere, einer, ein anderer<br />数詞としての<u>eines 二格</u><br />nichtは<u>nichts</u>なること（名詞的であること）</a></div><div class="col-2">82-86</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0082.html">hoch<u>dero</u>, höchst<u>dero</u>などについて</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">27-19B</div><div class="col-8"><a href="../027-1/s0087.html">derjenigeの諸形態</a></div><div class="col-2">87-110</div></div>');
document.write('<div class="row"><div class="col-2">27-20B</div><div class="col-8"><a href="../027-1/s0111.html">編者注：本袋「27-20B」内は二つのノー卜ブックに整理されているので、これを記号①、②で示すことにした。</a></div><div class="col-2">111-358</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0114.html">指示代名詞其他</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0114.html">①［01］der erstere, der letztere. Dieser, jener</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0131.html">①［02］da=と前置詞の結合。（dahin, daherも）</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0132.html">①［03］der, die, das（指示代名詞）</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0149.html">①［04］der 指示「形容」詞</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0155.html">①［05］eben=との結合（ebendaselbst等）</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0156.html">①［06］einer, keiner［solcheの意］<br />関係句を伴ひ得ること。</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0164.html">①［07］der...”の”「それ」。（規定を伴ふ場合）</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0165.html">①［08］solcher（関係文を（伴ふ）（二格規定）</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0167.html">①［09］関係代名詞代り。（の如きもの）der, die, das</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0168.html">①［10］<u>solch</u>=「…なぞといふもの」（意味に注意）</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0171.html">①［11］alle, alle beide, alle <u>zusammen</u><br /><u>samt und sonders</u><br />等の副詞的用法。（述語句なり）</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0174.html">①［12］anderer, vieler等の複数二格の用法。</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0174.html">①［13］dabei, damit等の Tmesis?</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0174.html">①［14］alles Gute等。（形容詞）</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0175.html">①［15］中性を人に用ひる例。（jedes, alles, keines）<br />was, das, eines</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0180.html">①［16］［derer］”der”形（物に関して）</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0188.html">①［17］dieserのemplatischな用法。<br />（selcheにもあり）</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0194.html">①［18］或者は、或者は。［der］, eine, der andere; der, der;</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0196.html">①［19］無選択なる指示。省略的指示<br />der und der u.s.w dieser und jener.</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0215.html">①［20］deinesgleichen etc.</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0216.html">①［21］derjenige</a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0217.html">①［22］derselbe（derselbige.）同じ<br />（関係代名詞の構文）</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0223.html">①［23］dar=Prep.を用ひず<u>das</u>, <u>dessen</u>を用ひること</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0224.html">①［24］andersの補足（<u>sonst</u>）kein anderer</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0288.html">①［29］als solcher. adnominalとadverbal.</a></div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0298.html">①［30］［daß］等の前の<u>da</u>=von等の省略。</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0299.html">①［31］……する「人の如き」（einer, jemand, 等）</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0305.html">①［32］solcherの「指示的」用法。</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0311.html">①［33］<u>ein und derselbe</u>.</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0318.html">①［34］Wer.</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0319.html">①［35］<u>eines</u>（男女の中の一人をさす）片一方</a></div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0319.html">不定代名詞</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0323.html">②［01］alles</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0326.html">②［02］ander（nominal）</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0327.html">②［03］alle=（dieser, jener, derの前で無語尾）</a></div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0333.html">②［04］mehr als einer等（一にして止まらず）</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0333.html">②［05］dergleichen.（動詞は単?）（adnominal nominal）</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0334.html">②［06］etwas, was.</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0336.html">②［07］etwas, was.</a></div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0337.html">②［08］all=を単数と共に用ひる際 二つの場合あり。（gannz....とjeder）</a></div><div class="col-2">337</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0338.html">②［09］all=と単数</a></div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0339.html">②［10］稀なる。<u>das</u>の三格（事柄を指す。）</a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0346.html">②［11］dasの二格dessen.（事柄を受ける）<u>was</u>あるものとなきものと。</a></div><div class="col-2">346</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0348.html">②［12］<u>das</u>の一格四格。</a></div><div class="col-2">348</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0349.html">②［13］alle（副詞的位置）主語の述語又は四格の述語</a></div><div class="col-2">349</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0353.html">②［14］<u>einer</u> der----.</a></div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0354.html">②［15］ein....ander....［相互的ならざる］名詞的と附加語的</a></div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0356.html">②［16］alles, （名詞的）wenig, manches, dies, das, etwas, viel</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0357.html">②［17］alleの後置</a></div><div class="col-2">357</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-1/s0358.html">②［18］alsの次の指示代名詞の省略。</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2">27-21B</div><div class="col-8"><a href="../027-2/s0359.html">強調用alle及び：jeder <u>in aller Stille</u></a></div><div class="col-2">359-375</div></div>');
document.write('<div class="row"><div class="col-2">27-22B</div><div class="col-8"><a href="../027-2/s0376.html">ander=</a></div><div class="col-2">376-414</div></div>');
document.write('<div class="row"><div class="col-2">27-28B</div><div class="col-8"><a href="../027-2/s0453.html">davonの代りにda....von</a></div><div class="col-2">453-462</div></div>');
document.write('<div class="row"><div class="col-2">27-29B</div><div class="col-8"><a href="../027-2/s0463.html">名詞的用法の複数二格（単数も）aller, vieier, usw. einiger usw. dieses, jenes usw.</a></div><div class="col-2">463-470</div></div>');
document.write('<div class="row"><div class="col-2">27-30B</div><div class="col-8"><a href="../027-2/s0471.html">das Ganze.（指示詞的）及び"das alles"</a></div><div class="col-2">471-478</div></div>');
document.write('<div class="row"><div class="col-2">27-31B</div><div class="col-8"><a href="../027-2/s0479.html">dessentwillen, dieserhalb等　形態の問題</a></div><div class="col-2">479-483</div></div>');
document.write('<div class="row"><div class="col-2">27-32B</div><div class="col-8"><a href="../027-2/s0484.html">［MHD］にはまだ中性の複数があった：diu</a></div><div class="col-2">484</div></div>');
document.write('<div class="row"><div class="col-2">27-33B</div><div class="col-8"><a href="../027-2/s0485.html"><u>Beides</u>及び関係諸項</a></div><div class="col-2">485-490</div></div>');
document.write('<div class="row"><div class="col-2">27-34R</div><div class="col-8"><a href="../027-2/s0491.html">無語尾の<u>viel</u>,<u>wenig</u><br /><u>alles und jedes</u><br />［特］alles, was<br /><u>全称の表現</u></a></div><div class="col-2">491-493</div></div>');
document.write('<div class="row"><div class="col-2">27-35B</div><div class="col-8"><a href="../027-2/s0494.html">welchesの代名詞用法</a></div><div class="col-2">494-498</div></div>');
document.write('<div class="row"><div class="col-2">27-36B</div><div class="col-8"><a href="../027-2/s0499.html">編者注：本袋「27-36B」内は普通の資料番号、（1）, （2）…により整理されているが、（5）, （6）だけがノー卜ブック形式に整理されているので、この部分だけは（5）［01］（6）［01］等として示すことにした。<p> </p><p>各々の概念 jeder語考</p></a></div><div class="col-2">499-576</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0501.html">（1）everyとeach</a></div><div class="col-2">501</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0503.html">（2）bini,singuli</a></div><div class="col-2">503</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0503.html">（3）一切の、いかなる、どんな（jeder,alle）</a></div><div class="col-2">503</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0503.html">（4）［仏］tout le monde</a></div><div class="col-2">503</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0505.html">（5）「各々」といふ概念</a></div><div class="col-2">505</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0505.html">（5）［01］je 各々、毎</a></div><div class="col-2">505</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0506.html">（5）［02］jeder（附加的）</a></div><div class="col-2">506</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0508.html">（5）［03］je nachdem.</a></div><div class="col-2">508</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0509.html">（5）［04］alle</a></div><div class="col-2">509</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0511.html">（5）［05］auf=<u>einander</u>等</a></div><div class="col-2">511</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0516.html">（5）［06］ein....den andern［名詞が一方］</a></div><div class="col-2">516</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0520.html">（5）［07］einander</a></div><div class="col-2">520</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0522.html">（5）［08］jeder dritte<br />alle</a></div><div class="col-2">522</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0546.html">（6）［02］einer....dem andern（及び前置詞）</a></div><div class="col-2">546</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0551.html">（6）［03］<u>der</u> eine....den andern（及前置詞）<br />及びeiner den andern</a></div><div class="col-2">551</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0557.html">（6）［04jeinender, .....miteinander.</a></div><div class="col-2">557</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0560.html">（6）［05］名詞の重畳</a></div><div class="col-2">560</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0562.html">（6）［06］sich, euch, uns.再帰動詞</a></div><div class="col-2">562</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0565.html">（6）［07］jederを使って<u>複数</u></a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0567.html">（6）［08］alles und jedes</a></div><div class="col-2">567</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0568.html">（6）［09］einer und der andere（etlicheの意に）<br /><u>der und der</u>（irgendwelchの意）</a></div><div class="col-2">568</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0570.html">（6）［10］どれも同じの意<br />（so....wie....又は比較級）</a></div><div class="col-2">570</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0573.html">（6）［11］von Mund zu Mund ロ々に</a></div><div class="col-2">573</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../027-2/s0576.html">（6）［12］<u>man</u>----sich 其の他、単数形の場合</a></div><div class="col-2">576</div></div>');
document.write('<div class="row"><div class="col-2">27-37B</div><div class="col-8"><a href="../027-2/s0577.html">指示の助詞</a></div><div class="col-2">577-581</div></div>');
document.write('<div class="row"><div class="col-2">27-38B</div><div class="col-8"><a href="../027-2/s0582.html"><u>普通の指示代名詞</u></a></div><div class="col-2">582-585</div></div>');
document.write('<div class="row"><div class="col-2">27-39B</div><div class="col-8"><a href="../027-2/s0586.html">ganze Schiffe</a></div><div class="col-2">586-594</div></div>');
document.write('<div class="row"><div class="col-2">27-40B</div><div class="col-8"><a href="../027-2/s0595.html">間投的 Nun sage mir noch <u>einer</u>---!</a></div><div class="col-2">595-599</div></div>');
document.write('<div class="row"><div class="col-2">27-41B</div><div class="col-8"><a href="../027-2/s0600.html">jederの一用法（少しでも…すると忽ち）</a></div><div class="col-2">600</div></div>');
document.write('<div class="row"><div class="col-2">27-42B</div><div class="col-8"><a href="../027-2/s0601.html">省けぬdarin, davon其の他</a></div><div class="col-2">601-606</div></div>');
document.write('<div class="row"><div class="col-2">27-43B</div><div class="col-8"><a href="../027-2/s0607.html">darinの代りにin <u>ihm</u></a></div><div class="col-2">607-613</div></div>');
document.write('<div class="row"><div class="col-2">27-44B</div><div class="col-8"><a href="../027-2/s0614.html">jemand<u>em</u>（niemandと同じ問題）<br />jemandemの複数形の如き感じを与えるが、実は<br />単（DATIVの時）</a></div><div class="col-2">614-616</div></div>');
document.write('<div class="row"><div class="col-2">27-45B</div><div class="col-8"><a href="../027-2/s0623.html">或者は……或者は… 及び”一方が他を”（複のみ扱ふ） Die einen ....die andern</a></div><div class="col-2">617-623</div></div>');
document.write('<div class="row"><div class="col-2">27-46B</div><div class="col-8"><a href="../027-2/s0624.html">Das war</a></div><div class="col-2">624</div></div>');
document.write('<div class="row"><div class="col-2">27-47R</div><div class="col-8"><a href="../027-2/s0625.html">［仏］のen 人間にも用ひる：</a></div><div class="col-2">625-632</div></div>');
document.write('<div class="row"><div class="col-2">27-48B</div><div class="col-8"><a href="../027-2/s0633.html">広義の指示詞は語順に於て形容詞の前に置かれる</a></div><div class="col-2">633</div></div>');
document.write('<div class="row"><div class="col-2">27-49R</div><div class="col-8"><a href="../027-2/s0634.html">英仏に不要な<u>darauf</u>, ～の構造<br />jed<u>es</u> solch<u>es</u><br />事柄を指す各種の［中性］代名詞</a></div><div class="col-2">634-637</div></div>');
document.write('<div class="row"><div class="col-2">27-51R</div><div class="col-8"><a href="../027-2/s0641.html">viel<u>en</u> Kummer<br />etwesとwas<br />名詞的 dasjenige, wes....<br />重要見地：定概念と不定概念<br />［羅］iste（指示力お参考として）<br />［仏］toutとtoute<br />ein, keinは男一格；中一四格で（名詞省略では）<br />必ず強語尾を附す：<br />［英］alles= everything</a></div><div class="col-2">641-645</div></div>');
document.write('<div class="row"><div class="col-2">27-52B</div><div class="col-8"><a href="../027-2/s0646.html">これ、それ、あれ 基本事項</a></div><div class="col-2">646-648</div></div>');
document.write('<div class="row"><div class="col-2">27-53R</div><div class="col-8"><a href="../027-2/s0649.html">単なる辞令としてのalle<br />mehrere, plusieurs, several<br />und dergleichen<br />einzig, einig等の意味<br />keinerの二格 <u>keines</u><br />dergleichen, nichts, etwas等に起って来る二格形の問題。<br />solcherの形容詞扱ひ。 ein solcher, kein solcher<br />darinと<u>in dem</u><br />普通の場合 jemand, niemand<br />jemand anders?<br />manchermann<br />derjenige=Teufelの意</a></div><div class="col-2">649-656</div></div>');
document.write('<div class="row"><div class="col-2">27-54B</div><div class="col-8"><a href="../027-2/s0657.html">Die halbe Stadt. Die ganze Stadt.</a></div><div class="col-2">657</div></div>');
document.write('<div class="row"><div class="col-2">27-55R</div><div class="col-8"><a href="../027-2/s0658.html">場所を指す際には<u>von wo</u>, <u>von da</u>を用ひる。<br />（woven, devenに非ず!）</a></div><div class="col-2">658</div></div>');
document.write('<div class="row"><div class="col-2">27-56B</div><div class="col-8"><a href="../027-2/s0659.html">The lady <u>in question</u></a></div><div class="col-2">659</div></div></div>');