document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">29-1B</div><div class="col-8"><a href="../029/s0001.html">subsumptions=Unter.</a></div><div class="col-2">1-8</div></div>');
document.write('<div class="row"><div class="col-2">29-2R</div><div class="col-8"><a href="../029/s0009.html">…の下に隠れて、…を掲げて。<br />「云々の美名にかくれて」</a></div><div class="col-2">9-12</div></div>');
document.write('<div class="row"><div class="col-2">29-3R</div><div class="col-8"><a href="../029/s0013.html">among, aumilieu de.</a></div><div class="col-2">13-21</div></div>');
document.write('<div class="row"><div class="col-2">29-4R</div><div class="col-8"><a href="../029/s0022.html">unter der Flagge.</a></div><div class="col-2">22-32</div></div>');
document.write('<div class="row"><div class="col-2">29-5B</div><div class="col-8"><a href="../029/s0033.html">の美名にかくれて</a></div><div class="col-2">33-35</div></div>');
document.write('<div class="row"><div class="col-2">29-6B</div><div class="col-8"><a href="../029/s0036.html">迂言前置詞のunter～ unter Einschluss von～</a></div><div class="col-2">36-45</div></div>');
document.write('<div class="row"><div class="col-2">29-7R</div><div class="col-8"><a href="../029/s0046.html">警戒の<u>vor</u> Die Sterne <u>erbleichen vor</u> der Sonne.</a></div><div class="col-2">46-68</div></div>');
document.write('<div class="row"><div class="col-2">29-8B</div><div class="col-8"><a href="../029/s0069.html">vor</a></div><div class="col-2">69-115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0069.html">［01］…の餘り。（無冠詞）</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0071.html">［02］…を差し置いて、…を駆けぬけて<br />…よりも秀れて。</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0072.html">［03］警戒のvor</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0075.html">［04］vor sich（hin） Für sich hin.</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0076.html">［05］時間的に「前」</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0081.html">［06］圧倒的因由のvor …を迎えて、に臨んで<br />（「原因」的）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0082.html">［07］云々に面する、臨む、さし向かふ vis-à-vis, en face de</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0083.html">［08］［膳」（bei einem Glas Bier）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0084.html">［09］の前に立って。（裁く者の）</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0093.html">［10］vor einer <u>Festung</u>, einer <u>Stadt</u>.（の外）</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0094.html">［11］空間的（下） unter</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0094.html">［12］下から（hinter, Zwischen等と）</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0110.html">［13］…の下（もと）に（何か支配的なる事情に<br />壓せられつつ）</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0111.html">［14］治下、代、（unter Trajan等）及び誰々「の下で」（働く等）</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0112.html">［15］概念の内容 verstehen.</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0113.html">［16］…されつつ、しつつ mit nomen avtionis.</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2">29-9B</div><div class="col-8"><a href="../029/s0116.html">警戒のvorと二格との関係 Horror vacui.</a></div><div class="col-2">116-120</div></div>');
document.write('<div class="row"><div class="col-2">29-10B</div><div class="col-8"><a href="../029/s0121.html">vor Wut等 Kohlhaas schäumte vor Wut.</a></div><div class="col-2">121-138</div></div>');
document.write('<div class="row"><div class="col-2">29-11R</div><div class="col-8"><a href="../029/s0139.html">über そんなことをしていたら。<br />（vergessen等と）<br />原因（四格の際は<u>um</u>等に近い）<br />anとinとの差 哲学的立場から</a></div><div class="col-2">139-142</div></div>');
document.write('<div class="row"><div class="col-2">29-12B</div><div class="col-8"><a href="../029/s0146.html">乗り越える。克つ。</a></div><div class="col-2">143-146</div></div>');
document.write('<div class="row"><div class="col-2">29-13B</div><div class="col-8"><a href="../029/s0147.html">－に就いて－ er sprocht von～と<br />er spricht über～との^区別</a></div><div class="col-2">147-163</div></div>');
document.write('<div class="row"><div class="col-2">29-14B</div><div class="col-8"><a href="../029/s0154.html">運命のüber über jem. schweben.</a></div><div class="col-2">154-159</div></div>');
document.write('<div class="row"><div class="col-2">29-15R</div><div class="col-8"><a href="../029/s0160.html">原因のüber（三格？） 或時は<u>vor</u>と同じ。<br />理由。über</a></div><div class="col-2">160-162</div></div>');
document.write('<div class="row"><div class="col-2">29-16B</div><div class="col-8"><a href="../029/s0163.html">nach（über Nacht,etc）</a></div><div class="col-2">163-170</div></div>');
document.write('<div class="row"><div class="col-2">29-17B</div><div class="col-8"><a href="../029/s0171.html">währennd（nachも同じ） 真のwährenndもあり</a></div><div class="col-2">171-173</div></div>');
document.write('<div class="row"><div class="col-2">29-18B</div><div class="col-8"><a href="../029/s0174.html">場所のauf（基本） 「席上で」など</a></div><div class="col-2">174-184</div></div>');
document.write('<div class="row"><div class="col-2">29-19B</div><div class="col-8"><a href="../029/s0185.html">über,auf</a></div><div class="col-2">185-275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0185.html">［01］über「見渡す見おろす」は四格（死命を制し、支配する意）</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0197.html">［02］währennd.</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0199.html">［03］［…に応じて」 aufeinanerfolgen.</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0201.html">［04］目標、方向（狙ふ対称）四格</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0224.html">［05］auf....着眼点、問題にせんとする点。</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0232.html">［06］働き掛けのauf［…に及ぶ、届く、達する］</a></div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0240.html">［07］auf,到着する地点「思い出す」</a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0268.html">［08］auf, 公開的な、人寄りの場所。</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0272.html">［09］auf die Nase fallen.</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0272.html">［10］auf eigene Faust,etc.（複） on his own,</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0273.html">［11］auf....los（空間的に）</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0275.html">［12］über 表面移動</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2">29-20B</div><div class="col-8"><a href="../029/s0276.html"> </a></div><div class="col-2">276-290</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0276.html">［01］auf,に掛け誓ふ。</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0277.html">［02］Zeitdauer. （四格、又はfür,währennd.）<br />auf immer=für ewig.<br />à jamais pour toujours</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0279.html">［03］重複のauf.</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0281.html">［04］…しに行く。 auf ～ <u>aus</u> sein,<u>aus</u>gehen</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2">29-21B</div><div class="col-8"><a href="../029/s0291.html">即應のauf 因由に転用可能</a></div><div class="col-2">291-304</div></div>');
document.write('<div class="row"><div class="col-2">29-22B</div><div class="col-8"><a href="../029/s0305.html">betragen（ohne"auf"） to reach, to total<br />betragenの表現 est <u>de</u><br />［英］一般的宣告の無冠詞（複数のGattungsnamen）<br /><u>Flowers</u> are sweet. <u>Cats</u> kill birds.<br /><u>Die</u> Katzen töten die vögel.</a></div><div class="col-2">305-332</div></div>');
document.write('<div class="row"><div class="col-2">29-23B</div><div class="col-8"><a href="../029/s0333.html">Betragの表現参考 in die Tausende gehen.</a></div><div class="col-2">333-335</div></div>');
document.write('<div class="row"><div class="col-2">29-24R</div><div class="col-8"><a href="../029/s0336.html">擧文のauf<br />限度、程度、境界を劃するauf bis auf....<br />auf（島、星の世界、等々）<br />Auf Java sind die Mädels braun.</a></div><div class="col-2">336-342</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0336.html">einen am Narrenseil führen.etc.</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-25B</div><div class="col-8"><a href="../029/s0343.html">性質のan 具有性のan</a></div><div class="col-2">343-358</div></div>');
document.write('<div class="row"><div class="col-2">29-26B</div><div class="col-8"><a href="../029/s0359.html"><u>Am</u> <u>Narrensell</u>で手段</a></div><div class="col-2">359-361</div></div>');
document.write('<div class="row"><div class="col-2">29-27B</div><div class="col-8"><a href="../029/s0362.html">最も普通なる空間的an.</a></div><div class="col-2">362-369</div></div>');
document.write('<div class="row"><div class="col-2">29-28B</div><div class="col-8"><a href="../029/s0370.html">享受、受益のan Die Lust am Schein.</a></div><div class="col-2">370-381</div></div>');
document.write('<div class="row"><div class="col-2">29-29B</div><div class="col-8"><a href="../029/s0382.html">増減（部分の） an Gesundheit zu nehmen.</a></div><div class="col-2">382-384</div></div>');
document.write('<div class="row"><div class="col-2">29-30B</div><div class="col-8"><a href="../029/s0385.html">結果のan sich <u>daran</u> zu Tode trinken.</a></div><div class="col-2">385-386</div></div>');
document.write('<div class="row"><div class="col-2">29-31B</div><div class="col-8"><a href="../029/s0387.html">「増減と」an</a></div><div class="col-2">387-389</div></div>');
document.write('<div class="row"><div class="col-2">29-32B</div><div class="col-8"><a href="../029/s0390.html">an ～zu ～habenはgenug等の<u>量詞規定ある</u>こと多し<br />これが現象の-Momentなり</a></div><div class="col-2">390-392</div></div>');
document.write('<div class="row"><div class="col-2">29-33B</div><div class="col-8"><a href="../029/s0393.html">一部分が段々減って行く。（…し「で」がある等）</a></div><div class="col-2">393-396</div></div>');
document.write('<div class="row"><div class="col-2">29-34B</div><div class="col-8"><a href="../029/s0397.html">部分的処理完成のan</a></div><div class="col-2">397-402</div></div>');
document.write('<div class="row"><div class="col-2">29-35B</div><div class="col-8"><a href="../029/s0403.html">内容を示すan. adnominalとadverbal.（genug an）</a></div><div class="col-2">403-413</div></div>');
document.write('<div class="row"><div class="col-2">29-36R</div><div class="col-8"><a href="../029/s0414.html">内容のan. －明らかにadnominal－<br />was....<u>an</u>と同じ。</a></div><div class="col-2">414-415</div></div>');
document.write('<div class="row"><div class="col-2">29-37B</div><div class="col-8"><a href="../029/s0416.html">失ふ対象のum</a></div><div class="col-2">416-419</div></div>');
document.write('<div class="row"><div class="col-2">29-38B</div><div class="col-8"><a href="../029/s0420.html">内容のan lack of materials</a></div><div class="col-2">420-427</div></div>');
document.write('<div class="row"><div class="col-2">29-39B</div><div class="col-8"><a href="../029/s0428.html"> </a></div><div class="col-2">428-438</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0428.html">［01］um …を得るために。<br />…を中心として</a></div><div class="col-2">428</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0430.html">［02］忌避の対象に。［um....herum=］</a></div><div class="col-2">430</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0431.html">［03］----を中心として。 －関心の対象、問題。<br />sich um ～ kümmern,（fragen）</a></div><div class="col-2">431</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0432.html">［04］ある者「ゆえに」苦労する。心配する等。<br />einen <u>um</u> etwas tadeln.</a></div><div class="col-2">432</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0435.html">［05］時刻を指すum.（頃、時刻）</a></div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0437.html">［06］失う対象のum.</a></div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2">29-40B</div><div class="col-8"><a href="../029/s0439.html">…を中心として</a></div><div class="col-2">439-448</div></div>');
document.write('<div class="row"><div class="col-2">29-41B</div><div class="col-8"><a href="../029/s0449.html">um（得るために）</a></div><div class="col-2">449-452</div></div>');
document.write('<div class="row"><div class="col-2">29-42B</div><div class="col-8"><a href="../029/s0453.html">…を得るために。…<u>を賭して</u><br />jemand um Beistand <u>anrufen</u>.</a></div><div class="col-2">453-455</div></div>');
document.write('<div class="row"><div class="col-2">29-43B</div><div class="col-8"><a href="../029/s0456.html">英語の<u>for</u></a></div><div class="col-2">456-459</div></div>');
document.write('<div class="row"><div class="col-2">29-44B</div><div class="col-8"><a href="../029/s0460.html">［<u>um</u> die <u>Wette</u>］ à l\'envi avec émulation</a></div><div class="col-2">460-463</div></div>');
document.write('<div class="row"><div class="col-2">29-45R</div><div class="col-8"><a href="../029/s0464.html">身辺［君］側. 等 身辺のum</a></div><div class="col-2">464-470</div></div>');
document.write('<div class="row"><div class="col-2">29-46B</div><div class="col-8"><a href="../029/s0471.html">Logisches Subjektのum</a></div><div class="col-2">471-477</div></div>');
document.write('<div class="row"><div class="col-2">29-47B</div><div class="col-8"><a href="../029/s0478.html">失う。 奪う。（einen um etwas prellen,etc）</a></div><div class="col-2">478-481</div></div>');
document.write('<div class="row"><div class="col-2">29-48B</div><div class="col-8"><a href="../029/s0482.html">失う。 奪う。 の<u>um</u></a></div><div class="col-2">482-483</div></div>');
document.write('<div class="row"><div class="col-2">29-49B</div><div class="col-8"><a href="../029/s0484.html">差のum ［英］<u>preceeded</u> him <u>by</u> a few seconds</a></div><div class="col-2">484-502</div></div>');
document.write('<div class="row"><div class="col-2">29-50B</div><div class="col-8"><a href="../029/s0503.html">um 陸続と。 Auto um Auto rollt an.</a></div><div class="col-2">503-505</div></div>');
document.write('<div class="row"><div class="col-2">29-51R</div><div class="col-8"><a href="../029/s0503.html">in 時間的階梯（段階）の局限</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0503.html">或る状態に置き移す。状態、心理状態<br />「點」で、「…する事に於て」<br />in ～ setzen in ～ treten in geraten <br />in ～bringen Zug um Zug in ～ versetzen. <br />in Gebrauch kommmen. in ～ verfallen<br />［英］to fall in love with ～</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-52B</div><div class="col-8"><a href="../029/s0533.html">teilen in ～ 分析、分解</a></div><div class="col-2">533-539</div></div>');
document.write('<div class="row"><div class="col-2">29-53B</div><div class="col-8"><a href="../029/s0540.html">時問的に（後続する）距たりを示す。<br />（nach）nach verlauf von.</a></div><div class="col-2">540-541</div></div>');
document.write('<div class="row"><div class="col-2">29-54B</div><div class="col-8"><a href="../029/s0542.html">in 3 stunden</a></div><div class="col-2">542-558</div></div>');
document.write('<div class="row"><div class="col-2">29-55R</div><div class="col-8"><a href="../029/s0559.html">in： Maß, Ausmaß, Grad, Umfang</a></div><div class="col-2">559-563</div></div>');
document.write('<div class="row"><div class="col-2">29-56B</div><div class="col-8"><a href="../029/s0564.html">in Ruhe. in Ehren. （im Grunde）（im Gegenteil）</a></div><div class="col-2">564-571</div></div>');
document.write('<div class="row"><div class="col-2">29-57B</div><div class="col-8"><a href="../029/s0572.html">in「和平裡に」の裡。（次に抽象名詞）</a></div><div class="col-2">572-576</div></div>');
document.write('<div class="row"><div class="col-2">29-58B</div><div class="col-8"><a href="../029/s0577.html">in［形を描いて］</a></div><div class="col-2">577-585</div></div>');
document.write('<div class="row"><div class="col-2">29-59B</div><div class="col-8"><a href="../029/s0586.html">in 極限化のin （部分と性質とあり）</a></div><div class="col-2">586-600</div></div>');
document.write('<div class="row"><div class="col-2">29-60R</div><div class="col-8"><a href="../029/s0601.html">für Gefühl für等</a></div><div class="col-2">601-606</div></div>');
document.write('<div class="row"><div class="col-2">29-61B</div><div class="col-8"><a href="../029/s0607.html">für （mot à mot） 徐々と、逐一、順を追って</a></div><div class="col-2">607-618</div></div>');
document.write('<div class="row"><div class="col-2">29-62R</div><div class="col-8"><a href="../029/s0619.html">für 期間のfür<br />geführ für等<br />賛成のfür<br />単に三格。（…に取って）</a></div><div class="col-2">619-623</div></div>');
document.write('<div class="row"><div class="col-2">29-63B</div><div class="col-8"><a href="../029/s0624.html">identitäts=in</a></div><div class="col-2">624-633</div></div>');
document.write('<div class="row"><div class="col-2">29-64B</div><div class="col-8"><a href="../029/s0634.html">～ für ～ step by step one by one</a></div><div class="col-2">634-638</div></div>');
document.write('<div class="row"><div class="col-2">29-65B</div><div class="col-8"><a href="../029/s0639.html">zu=als</a></div><div class="col-2">639-660</div></div>');
document.write('<div class="row"><div class="col-2">29-66R</div><div class="col-8"><a href="../029/s0661.html">zum Raub → Raub 古典語では<u>熟語的同格</u>を以て<br />表現す<br />by way of</a></div><div class="col-2">661-664</div></div>');
document.write('<div class="row"><div class="col-2">29-67B</div><div class="col-8"><a href="../029/s0665.html">zu Befehl zum Abmarsch（=<u>Abmarsch befehl</u>）</a></div><div class="col-2">665-671</div></div>');
document.write('<div class="row"><div class="col-2">29-68R</div><div class="col-8"><a href="../029/s0672.html">zum----en.<br />dazu noch<br />al（として） 結果のzuに通ず。<br />zum Scherz=scherzweise「冗談に」の「に」</a></div><div class="col-2">672-684</div></div>');
document.write('<div class="row"><div class="col-2">29-69B</div><div class="col-8"><a href="../029/s0685.html">zu［付属、対立のzu］意見のzu</a></div><div class="col-2">685-698</div></div>');
document.write('<div class="row"><div class="col-2">29-70R</div><div class="col-8"><a href="../029/s0699.html">zu 結果のzu（不定冠詞）<br />価格で、…価格の… <br />um....zu の文章と同意。（adnominaL u. adverbal）<br />目的（adnominaL u. adverbal）zu diesem Zwecke.</a></div><div class="col-2">699-705</div></div>');
document.write('<div class="row"><div class="col-2">29-71B</div><div class="col-8"><a href="../029/s0706.html">結果のzu</a></div><div class="col-2">706-717</div></div>');
document.write('<div class="row"><div class="col-2">29-72B</div><div class="col-8"><a href="../029/s0718.html">anと同じ（ce qu\'il y a de....）</a></div><div class="col-2">718-721</div></div>');
document.write('<div class="row"><div class="col-2">29-73R</div><div class="col-8"><a href="../029/s0722.html">von はなれている意（静止的）</a></div><div class="col-2">722-729</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../029/s0722.html">von ［先置する］Gen1tivus partitivus</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-74R</div><div class="col-8"><a href="../029/s0730.html">von 副詞、形容詞化的、（冠詞なし） par....<br />von von Beruf等 by trade by calling<br />von seiten.... von jemandes Seite<br />von 著作。<br />von der Arbeit ausruhen.<br />von einer Krankheit genesen.<br />von etwas abkommen.<br />（仏 <u>revenir</u> <u>sur</u> son opinion）<br />von …に就いて、…に関して。</a></div><div class="col-2">730-762</div></div>');
document.write('<div class="row"><div class="col-2">29-75B</div><div class="col-8"><a href="../029/s0763.html">von schwer von Begriff. schwer von Begriffen.</a></div><div class="col-2">763-784</div></div>');
document.write('<div class="row"><div class="col-2">29-76R</div><div class="col-8"><a href="../029/s0785.html">von 或る性質を有する。（von Belang, von <br />nutzen sein.）<br />形容のvon</a></div><div class="col-2">785-810</div></div>');
document.write('<div class="row"><div class="col-2">29-77R</div><div class="col-8"><a href="../029/s0811.html">nach nach etwas schmecken等。（らしい）<br />nach 従へば（仮定強調）</a></div><div class="col-2">811-822</div></div>');
document.write('<div class="row"><div class="col-2">29-78R</div><div class="col-8"><a href="../029/s0823.html">nach 時間的（普通のnach）<br />nach 空間的（普通のnach）</a></div><div class="col-2">823-844</div></div>');
document.write('<div class="row"><div class="col-2">29-79B</div><div class="col-8"><a href="../029/s0845.html">nach nemen <u>nach</u></a></div><div class="col-2">845-853</div></div>');
document.write('<div class="row"><div class="col-2">29-80B</div><div class="col-8"><a href="../029/s0854.html">nach 適、不適（嗜好の問題）添ふ</a></div><div class="col-2">854-889</div></div>');
document.write('<div class="row"><div class="col-2">29-81R</div><div class="col-8"><a href="../029/s0890.html">mit 言説をauffangenするmit<br />反発のmit</a></div><div class="col-2">890-898</div></div>');
document.write('<div class="row"><div class="col-2">29-82R</div><div class="col-8"><a href="../029/s0899.html">mit Gegenstand, womit, man so umgeht.<br />gegen für［Ayer pitié avec moi ! ］</a></div><div class="col-2">899-905</div></div>');
document.write('<div class="row"><div class="col-2">29-83B</div><div class="col-8"><a href="../029/s0906.html">mit 交渉・従事のmit</a></div><div class="col-2">906-913</div></div>');
document.write('<div class="row"><div class="col-2">29-84B</div><div class="col-8"><a href="../029/s0914.html">mit 「人」の時はいいが、「物の時はlogisches <br />0bjektを一致す</a></div><div class="col-2">914-937</div></div>');
document.write('<div class="row"><div class="col-2">29-85B</div><div class="col-8"><a href="../029/s0938.html">mit es steht so und so mit----.</a></div><div class="col-2">938-940</div></div>');
document.write('<div class="row"><div class="col-2">29-86R</div><div class="col-8"><a href="../029/s0941.html">mit esとmit<br />英語 matters, things, case<br />Esの代りに<u>was</u>等<br />編者注：このほか7件あり。</a></div><div class="col-2">941-953</div></div>');
document.write('<div class="row"><div class="col-2">29-87B</div><div class="col-8"><a href="../029/s0954.html">mit副詞的用法。<br />mit zugreifen（手つだふ） anpacken.</a></div><div class="col-2">954-992</div></div>');
document.write('<div class="row"><div class="col-2">29-88R</div><div class="col-8"><a href="../029/s0993.html">mit 附帯描写のmit</a></div><div class="col-2">993-1003</div></div>');
document.write('<div class="row"><div class="col-2">29-89B</div><div class="col-8"><a href="../029/s1004.html">mit 誰それの言葉通りに。（mit N.N. zu reden）</a></div><div class="col-2">1004-1008</div></div>');
document.write('<div class="row"><div class="col-2">29-90B</div><div class="col-8"><a href="../029/s1009.html">bei 或る人の「許」（家）</a></div><div class="col-2">1009-1044</div></div>');
document.write('<div class="row"><div class="col-2">29-91B</div><div class="col-8"><a href="../029/s1045.html">動機のaus aus politischen Beweg gründen.</a></div><div class="col-2">1045-1073</div></div></div>');