document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">28-1R</div><div class="col-8"><a href="../028/s0001.html">前置詞 前置句<br />［雑］bei Gelegenheit des = gelegentiich<br />bei dint of ～ à force de ～<br />à grand renfort de～ vor→にも通ず「の余り」<br />［英］short of</a></div><div class="col-2">1-4</div></div>');
document.write('<div class="row"><div class="col-2">28-2B</div><div class="col-8"><a href="../028/s0005.html">［英］by way of</a></div><div class="col-2">5-7</div></div>');
document.write('<div class="row"><div class="col-2">28-3B</div><div class="col-8"><a href="../028/s0008.html">［仏］前置句一般</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2">28-4B</div><div class="col-8"><a href="../028/s0009.html"> </a></div><div class="col-2">9-43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0009.html">［01］</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0010.html">［02］auf auf Grund…等</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0015.html">［03］an an Hand等 …を據所にして，unstelle<br />…に頼って，…を手がかりに，</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0017.html">［04］mit mit Hilfe等<br />ohne</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0025.html">［05］unter <u>前置詞を用ひざるもの</u></a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0034.html">［06］in</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0034.html">［07］bei bei Begin des</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0035.html">［08］nach nach art....</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0042.html">［09］von von seiten</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0042.html">［10］前置詞の先頭の前置詞を省くもの（仏が主）<br />1.faute de....</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0043.html">［11］<u>vo</u>r,<u>nach</u>,<u>unter</u>,seitとnomen actionisは<br />一般現象とみなす可し<br />nach Abschluß seiner Studien</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">28-5R</div><div class="col-8"><a href="../028/s0044.html">nach,vor,unter<br />zu: durch,<br />指向性について<br />vor Ablauf eines Monats</a></div><div class="col-2">44-48</div></div>');
document.write('<div class="row"><div class="col-2">28-6B</div><div class="col-8"><a href="../028/s0049.html">前置詞の前後に附く詞</a></div><div class="col-2">49-68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0050.html">［01］auf---zu, los,ein <u>vor</u> sich <u>hin</u></a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0059.html">［02］後曳追加詞（単語）</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0061.html">［03］前置詞に前置される副詞（文例）</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0067.html">［04］前置詞に前置される副詞（句）</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2">28-7B</div><div class="col-8"><a href="../028/s0069.html">三四格支配の前置詞</a></div><div class="col-2">69-135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0071.html">［01］in</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0078.html">［02］außenをも加へる必要あり。</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0105.html">［03］四格支配の例</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0110.html">［04］<u>neben</u></a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0111.html">［05］区別の例。</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0114.html">［06］［neben］ihm <u>her</u> 等 <u>einher</u><br />［hinter］ihm <u>drein</u> <u>hin</u> <u>drein</u></a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0118.html">［07］unter....<u>hervor</u> zwischen....hervor<br />hinter.....hervor［…から去る］</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0125.html">［08］三格で運動。</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0126.html">［09］darinとdarein, worinとworein</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0128.html">［10］静止にも拘らず、その動詞によっては四格。<br />完了状態的 述語的性質。<br />（文章構造の保全）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2">28-8B</div><div class="col-8"><a href="../028/s0136.html">前置詞一般論</a></div><div class="col-2">136-160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0137.html">［01］im und zum等</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0138.html">［02］ニ個以上の、格支配を異にする前置詞を用ひた例（近きに従って格を決す）</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0141.html">［03］Kathegorieのちがふ前置詞（同一物）を二回以上用ひた例。説明用）</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0141.html">［04］二格支配前置詞中、vonを用ふ可き場合あり。<br />nördlich von Berlin.</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0142.html">［05］前置詞の後に副詞。（等）名詞以外</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0145.html">［06］後置詞は、単に直接被支配名詞のみならず、そもそも「句」総体の最後に置くこと</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0145.html">［07］後置詞的なるものに就いて。<br />（分離動詞の前綴との関係） gleich nahe<br />zuと三格</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0145.html">［08］二つ以上の前置詞</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0146.html">［09］<u>im</u>,<u>am</u>,<u>zum</u>,<u>vom</u>等に就いて</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0150.html">［10］<u>ums</u> Himmels willen 二格の=s</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0150.html">［11］unters,unterum等</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0151.html">［12］前置詞化の途上にあるもの。<br />1.Punkt ein Uhr wird gegessen.</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0152.html">［13］位置規定前置詞句の主観的と客観的、</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0155.html">［14］in<u>s</u> Teufels Namen! ［desの省略］ da,</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0156.html">［15］vonを用ひるもの links von,</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0156.html">［16］前置句の重要な区別</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0157.html">［17］adnominal adverbal<br />Die Reise <u>nach Berlin</u>.<br />wir reisen <u>nach Berlin</u>.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0159.html">［18］前置詞の重要な区別：［<u>主語の局限的機能</u>］<br />（in,an,mit bei）等</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0159.html">［19］前置詞が多く重なる場合</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0160.html">［20］空間時間表象の変な関係。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0160.html">［21］前置詞二個の重畳を要する場合について<br />statt um....außer um....など。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2">28-9B</div><div class="col-8"><a href="../028/s0161.html">前置詞 二格支配</a></div><div class="col-2">161-179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0162.html">［01］inmitten vermöge</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0165.html">［02］「関する」といふ意のもの。</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0176.html">［03］附加語なき時は格の表現不可能なることあり。<br />（女性、複数）無語尾。［無格］</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0177.html">［04］二格支配の生ずる経過その他参考材料<br />angesichts,rücksichts,hinsichtlich</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0178.html">［05］nördlich <u>von</u></a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0178.html">［06］「に拘らず…」の意のもの。</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0178.html">［07］unfern Nördlingen等<br />（vonを用ひざることあり）</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0179.html">［08］…のために。</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0179.html">［09］statt,während,ob,unfern,nördich等の支配法<br />［1］二格、［2］von,［3］三格モアリ<br />［4］直接に名詞。（殊に固有名詞）</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2">28-10B</div><div class="col-8"><a href="../028/s0180.html">前置詞が格支配をしない場合<br />was für einem,usw.</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2">28-11B</div><div class="col-8"><a href="../028/s0181.html">前置詞 三格支配</a></div><div class="col-2">181-189</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［01］</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［02］［nach;nahe］</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［03］wegenの三格支配。</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［04］<u>volan</u></a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［05］plus,mal等と三格 仏はmoinsもあり 独はweniger（数詞と）</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../028/s0181.html">［06］餘計な三格支配に理あることあり：</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">28-12B</div><div class="col-8"><a href="../028/s0190.html">融合形一般に就いて seim,eim</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2">28-13B</div><div class="col-8"><a href="../028/s0191.html">見地的意局の表現</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2">28-14R</div><div class="col-8"><a href="../028/s0192.html">前置詞の意味型態論<br />（1）転用（Analogieによる）<br />［英］前置詞とGerund.（after having ～）<br />意型が同じために慣習の用法を誤ること多し<br />（移轍現象）<br />［初歩］動詞の前置詞支配<br />ABLATIVUS ABSOLUTUSが前置詞へと転化する筋道<br />［羅］注目すべき前置句.前置詞</a></div><div class="col-2">192-194</div></div>');
document.write('<div class="row"><div class="col-2">28-15B</div><div class="col-8"><a href="../028/s0195.html">英仏語の前置句</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2">28-16B</div><div class="col-8"><a href="../028/s0196.html">動詞の前置詞支配（区別用）</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2">28-17B</div><div class="col-8"><a href="../028/s0197.html">Paitikel 総論 副詞-接続詞-前置詞-助詞</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">28-18R</div><div class="col-8"><a href="../028/s0198.html">［英］二重の解釈（前置詞か副詞か?）<br />adnominal前置詞句<br />重要な一般問題 副詞を作るは前置詞一般の機能なり</a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2">28-19B</div><div class="col-8"><a href="../028/s0199.html">仏語の前置句</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2">28-20R</div><div class="col-8"><a href="../028/s0200.html">意味範疇に関する考察（如何なる前置詞も因由・仮定其の他の意に用ひられること）<br />［初歩］Hoffnung auf den Lohn<br />二種以上の前置詞が可能<br />前置詞が格支配を為さざる場合（副詞）<br />1.wasfür....<br />2.an die....<br /><u>bei</u>....<br />3.bis zu dreihundert....<br />前置詞用法の微妙な区別を述べる時の例（同文中に二つ以上の異なる型の同一前置詞が出てくるもの）</a></div><div class="col-2">200-201</div></div>');
document.write('<div class="row"><div class="col-2">28-21B</div><div class="col-8"><a href="../028/s0202.html">前置詞を種々支配し得る動詞［支配なる考ヘ方の制限を…］</a></div><div class="col-2">202</div></div></div>');