document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">31-1B</div><div class="col-8">編者注：本袋「31-1B」内は二つのノート・ブックに整理されているので、これを記号①、②で示すことにした。<br />定形倒置及び先置 転置</a></div><div class="col-2">1-2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［01］doch, aber それが証拠に。</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［02］sah ein Knab ein Röslein stehn.<br />（es sah ein Knab）</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［03］WENN SATZ</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［04］一分肢の先置（普通の場合）</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［05］二つ以上の。肢の先置</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［06］過去分詞の先置。</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［07］Arbeiten <u>tut</u> der Kerl nieh.</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［08］不定法先置<br />Arbeiten will der Keil nicht.</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［09］鋭いAntithese</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［10］反語文に於ける第二倒置の主語は省く。</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［11］Daher,deshalb等の後の定形のみならず<br />動詞全部）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［12］"Habe dich!" triumphiert sie. 勝った！</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［13］俗語に於ける倒置。</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①［14］第二倒置の主語省略（一般的）</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">定形先置</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［01］wennの代。（もしも）</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［02］間投的。</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［03］主語の省略（実は先置に非ず）</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［04］Fertig ist es schon ～.</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［05］<u>sagte er</u> 等</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［06］それが証拠に（doch）</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［07］接続詞後の倒置</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［08］文肢の強きもの。</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［09］疑問文・間投文においては一文肢の強調先置は普通は不可</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［10］形容詞を残して名詞の先置。</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［11］<u>不定句の先置</u></a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［12］対立と認容には好んで文肢を先置す。</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［13］<u>文肢先置</u>の普通例。</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［14］形容詞等の先置</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">②［15］疑問文に於ても一文肢を先置する：</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2">31-2B</div><div class="col-8">正置</a></div><div class="col-2">108-157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］also「では」等と正（nun.）間投詞化す。</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］副文章後の主文章の正置、倒置。</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］Es mährte nicht lange und....</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］wennの文の第二次以後を正置。倒置。</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］叙述に直接性を附するための、後部に於ける<br />正置への転向。</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］Ich glaube, er ist fort.</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Er wäre im stande <u>und</u> malte es hin.</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］Es fehlt nicht viel,so....</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］Sei bitte so gut und komm zeitig<br />nach Hause,ja?</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">31-3B</div><div class="col-8">Inversion nach "<u>und</u>"</a></div><div class="col-2">158-163</div></div>');
document.write('<div class="row"><div class="col-2">31-4B</div><div class="col-8">文肢先置とコンマの問題</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2">31-5B</div><div class="col-8">定形</a></div><div class="col-2">165-228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］単か複か?</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］ニ語の次に来る定形の数。（無冠詞）</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］尊称的複数。PLURALIS <u>REVERENTIAE</u>.</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］代名詞が述語となる場合（Nennsatzに於て）</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］das,was,dies,es,jenes,welchesと複数定形。<br />（主として<u>was</u>）</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］Ich und mein Vater <u>haben</u>....</a></div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Dreierlei等とs,（od.）pl.</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］聯語主語と定形単数</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］eine Menge等とpl.定形。（或は単）</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］oder, wederでつないだ主語には単数定形。</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］mitsamt,zusamt等でつないだものは？</a></div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］Ein Freund nach dem andern <u>zog</u> sich zurück.</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］Hoch und niedrig, 等が主語の際。<br />Reich und arm</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］Meilenstein um Meilensteinと（単数？）</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］列挙の後の<u>des</u></a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2">31-6R</div><div class="col-8">定形の数を近きものに合致せしむ。<br />多くの主語が、実は「繰りかへし」なる事あり。<br />やり直し、言ひ換え、「換覆」</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2">31-7B</div><div class="col-8">定形 後置</a></div><div class="col-2">230-244</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］関係分の後置</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］従属的接続詞後の後置</a></div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］疑問詞の従属文</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］感嘆文の後置</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］後置せざるもの（古し）<br />（後置すべきものを後置せざる例）</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］主文章の後置</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］馬鹿正直なbiedemeyerischな定形後置に<br />関する考察。</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］定形後置と外国語。</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］定形後置に於て、必ずしも主語が第一位とは<br />限らぬ。</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］和蘭語の定形後置：</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］英仏の定形後置熟語</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］....<u>zu tun</u> die Lust <u>hatte</u>等<br />（zu+不定法と定形後置）</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2">31-8B</div><div class="col-8">詩文等における従属文の定形正置</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2">31-9B</div><div class="col-8">英仏の定形倒置</a></div><div class="col-2">246-285</div></div>');
document.write('<div class="row"><div class="col-2">31-10B</div><div class="col-8">正置の場合の填充物について</a></div><div class="col-2">286-291</div></div>');
document.write('<div class="row"><div class="col-2">31-11R</div><div class="col-8">...., <u>sagt er</u><br />viei+二格複数を主語にして定形を単にする。<br />定形が二個以上になる場合（und,oder）<br />編者注：このほか１３けんあり。</a></div><div class="col-2">292-302</div></div>');
document.write('<div class="row"><div class="col-2">31-12B</div><div class="col-8">定形倒置 主語省略（代名詞主語）<br />Schlagfertige Antwort及び間投文</a></div><div class="col-2">303-308</div></div>');
document.write('<div class="row"><div class="col-2">31-13B</div><div class="col-8">wenig sind ihrer（定形は単か複か？）<br />ist</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2">31-14B</div><div class="col-8">定形倒置の純例外</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2">31-15B</div><div class="col-8">定形倒置に於ける主語の位置</a></div><div class="col-2">311-313</div></div>');
document.write('<div class="row"><div class="col-2">31-16B</div><div class="col-8">Fifteen minutes is ampl time!［主語］が複数詞</a></div><div class="col-2">314-315</div></div>');
document.write('<div class="row"><div class="col-2">31-17B</div><div class="col-8">it\'s 3600 statute miles. 述語が複数詞</a></div><div class="col-2">316-317</div></div>');
document.write('<div class="row"><div class="col-2">31-18R</div><div class="col-8"><u>Du</u> <u>armes Weib</u>などの際の定形は二人称扱い<br />共通（有）的単数の場合の定形はpl.を要す<br />編者注：このほか13件あり。</a></div><div class="col-2">318-325</div></div>');
document.write('<div class="row"><div class="col-2">31-19B</div><div class="col-8">俗語と主語duの省略</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2">31-20R</div><div class="col-8">定形倒置説明用（初歩） 英語<br />英語に於ける先置の次の定形正置<br />［希］中性pl.と単数定形</a></div><div class="col-2">327</div></div></div>');