document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">33-1B</div><div class="col-8">時称 seinか habenか</div><div class="col-2">1-43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］habenの用法の生ずるわけ。<br />（分詞と名詞とが合体）</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］habenの用法。（名詞四格と分詞とが別々<br />になる）（現在完了と間違えがちな場合）</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］<u>sein</u>.を用ひる動詞。</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］ist getreten → hat angetreten型</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］<u>stehen</u>,<u>sitzen</u>,<u>liegen</u></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］完了形のhabenが「持つ」と考へ得る場合。</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Schwankende Verbeu,</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］純自動詞にしてhaben支配。<br />（was hat er <u>getan</u>?）<br />....eine Zeitlangと言えるもの</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］--gegangenの代り。（四格支配と関係）</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］四格を取るもsein.（<u>eingehen</u>等）</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">33-2B</div><div class="col-8">時称に関する一般事項 Consecutio Temporum</div><div class="col-2">44-68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］was....betrifft（betraf）現在でもよき際</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］副文章内の接続法。</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］日本語で言ふと現在になるもの。<br />（副文章の定形は主文章に従ふ）</div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］時称の一致不必要なる場合</div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］sein,habenの定形省略。</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］聞接話法</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］vergessen <u>gehabt</u> 等。</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］時称の不一致：過去文脈中に現在完了<br />過去文脈中に現われる「超時間的一般言明」<br />（過去でも現在でもない）</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］完了不定形の要不要の問題</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］Ce n\'est pas....quel....<u>fit</u>....<br />ne fut</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］異例（雑）</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］未来文脈内の想定では［英］過去形。</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］現在完了文肢中に過去を用ふ：</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2">33-3B</div><div class="col-8">werden型の動詞<br />werden型も結局は到達型なり、たとへば：<br />Was ich mir immer sagte,ist eingetroffen.<br />の如し。</div><div class="col-2">69-79</div></div>');
document.write('<div class="row"><div class="col-2">33-4R</div><div class="col-8">gelingen,glücken等<br />静止状態とhaben<br />陥入る、落る、沈む</div><div class="col-2">80-82</div></div>');
document.write('<div class="row"><div class="col-2">33-5B</div><div class="col-8">活動型のhaben支配</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2">33-6B</div><div class="col-8">純sein支配自働詞の他働詞化</div><div class="col-2">84-86</div></div>');
document.write('<div class="row"><div class="col-2">33-7B</div><div class="col-8">verfahrenのsein支配 mit jemand so und so</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2">33-8B</div><div class="col-8">fahren, laufen, raisen 等の「行為」的場合<br />（殊にviel, reisen等）<br />過去に於て度々繰返された行為といえども<br />sein支配！</div><div class="col-2">88-91</div></div>');
document.write('<div class="row"><div class="col-2">33-9B</div><div class="col-8">同一動詞で自働詞と他働詞とがある場合に於ける<br />sein, haben</div><div class="col-2">92-93</div></div>');
document.write('<div class="row"><div class="col-2">33-10R</div><div class="col-8">生起・突発 経過<br />自働詞（純）で<u>haben</u>.</div><div class="col-2">94-95</div></div>');
document.write('<div class="row"><div class="col-2">33-11B</div><div class="col-8">Schwankende Verben</div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2">33-12B</div><div class="col-8">［仏］être 動詞</div><div class="col-2">97-98</div></div>');
document.write('<div class="row"><div class="col-2">33-13B</div><div class="col-8">［英］You are come 等</div><div class="col-2">99-102</div></div>');
document.write('<div class="row"><div class="col-2">33-14R</div><div class="col-8">［仏］疑問？ de～ の特殊型<br />完了時称の不定法<br />運動型の動詞<br />Schnellboote peitschen durch das<br />Küstengewässer.<br /><u>laufen</u>に就いて<br />sein支配とhaben支配との区別<br />動作より動きヘの転向。<br />運勤と状態変化との一致</div><div class="col-2">103-106</div></div>');
document.write('<div class="row"><div class="col-2">33-15B</div><div class="col-8">sein支配でしかも真のAKKUSATIV目的語を伴ふもの：<br />Verbindung <u>eingehen</u> → TUN型 →</div><div class="col-2">107-108</div></div>');
document.write('<div class="row"><div class="col-2">33-16B</div><div class="col-8">”四格目的語あればhaben支配” 其の例外</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">33-17R</div><div class="col-8">［仏］再帰動詞はêtre支配<br />（但し俗語 je m\'<u>ai</u> fait mal）<br />［仏］seinの場合<br />編者注：このほか18件あり。</div><div class="col-2">110-121</div></div>');
document.write('<div class="row"><div class="col-2">33-18B</div><div class="col-8">同一動詞でseinとhabenと両方あるのも<br />（意味が違ふ）</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2">33-19B</div><div class="col-8">Inneres Objekt のためにhabenを取らざる動詞<br />（gehen, stehen）<br />Wieviel tausend Tode mußte sie <u>gestorben sein</u>!</div><div class="col-2">123</div></div></div>');