document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">38-1B</div><div class="col-8"><a href="../038/s0001.html">三要形の不規則<br>bewegen式に弱形あるもの   schweigen<br>verhehlen<br>umrimgenの件<br>schroten → geschroten<br>Der Regen klatscht dem -- ins Gesicht.<br>sendete, sandte<br><br>編者注：このほか79件あり。<br></a></div><div class="col-2">1-50</div></div>');
document.write('<div class="row"><div class="col-2">38-2R</div><div class="col-8"><a href="../038/s0051.html">韻のために形態の湾曲<br>atmen → at<u>e</u>mbar</a></div><div class="col-2">51-54</div></div>');
document.write('<div class="row"><div class="col-2">38-3B</div><div class="col-8"><a href="../038/s0055.html">ge= なき強変化動詞の過去分詞  altbacken</a></div><div class="col-2">55-57</div></div>');
document.write('<div class="row"><div class="col-2">38-4B</div><div class="col-8"><a href="../038/s0058.html">人称語尾</a></div><div class="col-2">58-83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0059.html">［01］kreucht型。 ich krieche, du kreuchst<br>er kreucht</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0065.html">［02］<u>fahen</u> statt fangen</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0067.html">［03］er lauft. Er schlagt.（等） <u>druckt</u>（ü）</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0070.html">［04］däucht, deucht.</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0071.html">［05］frägt, kömmt等</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0072.html">［06］verderb ! 等（命令法）</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0076.html">［07］stickt（stecken）等 e → i</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0077.html">［08］sturb等stund</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0077.html">［09］"t"  statt  "st"</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0082.html">［10］複数一人称三人称=et語尾</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0083.html">［11］du löst, du tanzt等。</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0083.html">［12］<u>geschicht</u> für geschieht</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2">38-5B</div><div class="col-8"><a href="../038/s0084.html">三要形</a></div><div class="col-2">84-113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0085.html">［01］ich floh<u>e</u>.</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0085.html"></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0088.html">［02］遺物的過去分詞。  verschroben</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0092.html">［03］強と弱とで意味の相違するもの<br>bewegen. -- er bleichen.</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0092.html">［04］強を弱に</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0098.html">［05］ich g<u>ien</u>g, giebt.</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0100.html">［06］ge=無き過去分詞</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0105.html">［07］kunnt, stund, etc.</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0106.html">［08］古形  kiff等。（keifen）</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0108.html">［09］frug（frägt）比較的近代にも用ひらる。</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0109.html">［10］er kennte等</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0111.html">［11］=ierenの過去分詞にge=</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0112.html">［12］方言 kennt statt gekannt<br>  denkt statt gedacht</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2">38-6B</div><div class="col-8"><a href="../038/s0114.html">IIKの形</a></div><div class="col-2">114-124</div></div>');
document.write('<div class="row"><div class="col-2">38-7B</div><div class="col-8"><a href="../038/s0125.html">find\'t statt findet.</a></div><div class="col-2">125-131</div></div>');
document.write('<div class="row"><div class="col-2">38-8B</div><div class="col-8"><a href="../038/s0132.html">［MHD］定形倒置の場合：hab<u>e</u> wir<br>des <u>habe wir</u> niht vernomen.</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2">38-9B</div><div class="col-8"><a href="../038/s0133.html">Reduplicatio</a></div><div class="col-2">133-137</div></div>');
document.write('<div class="row"><div class="col-2">38-10B</div><div class="col-8"><a href="../038/s0138.html">tun <u>tat</u> getan</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2">38-11B</div><div class="col-8"><a href="../038/s0139.html">tätに就て</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2">38-12R</div><div class="col-8"><a href="../038/s0140.html">過去分詞語尾=tの省略。<br>複数三人称は［MHD］までは不定形と区別される！ =nt<br>［MHD］強変化単人称語尾は =e<br>fungie<u>ren</u>とfunksioni<u>eren</u></a></div><div class="col-2">140-141</div></div>');
document.write('<div class="row"><div class="col-2">38-13B</div><div class="col-8"><a href="../038/s0142.html">現在分詞の=de語尾</a></div><div class="col-2">142-144</div></div>');
document.write('<div class="row"><div class="col-2">38-14B</div><div class="col-8"><a href="../038/s0145.html">過去形現在</a></div><div class="col-2">145-155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0146.html">［01］羅典では</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0147.html">［02］［希］では</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0152.html">［03］［Gotisch］では</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0153.html">［04］［独］話法助動詞はwollenを除いて他の五つ。</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0153.html">［05］［英］の<u>need</u></a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0154.html">［06］［MHD］MHD以外に<u>ganah</u>あり</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0155.html">［07］［MHD］</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2">38-15B</div><div class="col-8"><a href="../038/s0.html">du tanzt, du wunscht等。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">38-16B</div><div class="col-8"><a href="../038/s0157.html">人称変化の異例  need not  raten  braten</a></div><div class="col-2">157-158</div></div>');
document.write('<div class="row"><div class="col-2">38-17R</div><div class="col-8"><a href="../038/s0159.html">［MHD］の形のいろいろある雑例<br>werde !<br>verwitw<u>e</u>tのe<br>i gib, i nim</a></div><div class="col-2">159-160</div></div>');
document.write('<div class="row"><div class="col-2">38-18B</div><div class="col-8"><a href="../038/s0161.html">Oesterreichischの"s"</a></div><div class="col-2">161-164</div></div>');
document.write('<div class="row"><div class="col-2">38-19B</div><div class="col-8"><a href="../038/s0165.html">rechnen型</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2">38-20R</div><div class="col-8"><a href="../038/s0166.html">［英］build buil<u>t</u>型<br>［英］put put put型<br>不定法の語尾<br>=enを=eと言ふ方言<br>［AHD］teta（=tat）<br>（古）sieh<u>e</u>t  等<br>［英］shut, shut, shut  型</a></div><div class="col-2">166-169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0166.html">［形の上の相似］</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">38-21B</div><div class="col-8"><a href="../038/s0170.html">幹語尾=en=  leug=, rech=, zeich,=etc.<br>［AHD］動詞の過去形<br>「未来の不定形は無し」<br>vewitwen式</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0170.html"></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0170.html"></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">38-22R</div><div class="col-8"><a href="../038/s0171.html">=ern語尾の例外現象：doktorn（doktern）<br>an einem Uebel <u>herumdoktorn</u>.<br>［英］話法助動のPräterito-Präsentienに平行する<br>英のneedの三人称単<br>［英］ドイツ語の不定法語尾=enと英の（形）=en<br><br>編者注：このほか5件あり。</a></div><div class="col-2">171-176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../038/s0171.html"></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">38-23B</div><div class="col-8"><a href="../038/s0177.html">強変化と混同す可からざる場合 beauf<u>tragen</u>等</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">38-24R</div><div class="col-8"><a href="../038/s0178.html">=et語尾の省略<br>過去の語幹に幹母音<u>ei</u>は今はないが昔はあった<br>（bieib等）</a></div><div class="col-2">178-179</div></div>');
document.write('<div class="row"><div class="col-2">38-25B</div><div class="col-8"><a href="../038/s0180.html">偶然形態の一致するもの</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2">38-26R</div><div class="col-8"><a href="../038/s0181.html">gewillt, gesinnt, umringt等の現象<br>過去形<br>1.Konjunktiv  seie<br>強変化動詞と似た語幹を有するDenominativa<br>（beanspruchen）<br>ge=の省略（古）  worden.<br>ebnen, ordnen, widmen, regnen, rechnen,....<br>助動詞の命令形（wolle!等）  so wolle nur !<br>=ierenと前綴<br><u>essen</u>とその結合。  verge-essen:vergessen<br>第二式接続法形の形態上の不都合<br>（第一式と同じになる際等）</a></div><div class="col-2">181-189</div></div></div>');
