document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">39-1B</div><div class="col-8">wo kommt die Stimme <u>her</u> ?</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">39-2B</div><div class="col-8">疑問文</div><div class="col-2">2-84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］反語</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］反語 wer <u>wollte</u>....?<br>…する奴があるか。</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］was für eins ?  was für welches ?</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］疑問文副文章。</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］疑問副文章の省略。</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］was....［nucht］ alles...反語。</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］was....anderes, besseres, viel, groß, mehr, sonst</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］疑問詞の先置とその配語。</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］疑問詞で始まる問投文の意味。</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］疑問文を強めるための飾り。<br>（in aller welt等）</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］疑問文の二つの定形の始末</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］感嘆文。（定形の位置と助詞）<br><u>What</u> a horrible idea !</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］副文章的疑問文か極くルーズに主文章に結び<br>つく例。（Kontamination）</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］mit was, auf was等。（関係代名詞も）</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］疑問関係文か関係文か?（難）</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］Adnominalな疑問副文章。<br>Der Grund, warum等</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［17］<u>Was weiß ich</u> ? （分かったものじゃなぃ）</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［18］<u>Was</u> reden ?  不定法の用法</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［19］<u>Weißt du was</u> ? （was ich sagen wollte）</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［20］ich weiß nicht was等</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［21］疑問文、反語文の定形主語省略。</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［22］「等々」の意のWer nennte sie alle等。</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［23］<u>nicht wahr</u> ? （gelt,? was ? wie ? ja ? hm ?）</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2">39-3B</div><div class="col-8">Wozu....? ［羅］<u>quid opus</u> nota noscere ?</div><div class="col-2">85-89</div></div>');
document.write('<div class="row"><div class="col-2">39-4B</div><div class="col-8">叙事詩の導入的疑問文</div><div class="col-2">90-91</div></div>');
document.write('<div class="row"><div class="col-2">39-5R</div><div class="col-8">［英］whom are you talking about ? </div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2">39-6B</div><div class="col-8">疑問詞</div><div class="col-2">93-131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］wohinの代りにwo hin= 等</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］was für.</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］間投的wasをwieの意に用ひる。［なんと…！］</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］ich Weiß nicht welch=等。</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］二人のうちで「どちらの者が」は（we1cher <u>von</u><br>beiden）または単に<u>wer</u>を用ひる事。</div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］Was glaubst du, daß es kostet ?</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］Werは複数にも用ひる事。</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］was für welches ?（=was für eins ?）</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］was, wessen, ---, was.</div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］<u>Was gibts Neues</u> ?</div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2">39-7B</div><div class="col-8">adnominal = 疑問副文章<br>=関係文章</div><div class="col-2">132-134</div></div>');
document.write('<div class="row"><div class="col-2">39-8B</div><div class="col-8">was sag ich?  それどころか。</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2">39-9B</div><div class="col-8">［仏］仏の疑問文（その特殊性）</div><div class="col-2">136-137</div></div>');
document.write('<div class="row"><div class="col-2">39-10B</div><div class="col-8">was = etwas<br>wer = jemand</div><div class="col-2">138-143</div></div>');
document.write('<div class="row"><div class="col-2">39-11B</div><div class="col-8">nicht wahr?</div><div class="col-2">144-156</div></div>');
document.write('<div class="row"><div class="col-2">39-12R</div><div class="col-8">どちらが？ wederez<br>Wer?=welcher von beiden?<br>（二人のうちでどちらが）</div><div class="col-2">157-158</div></div>');
document.write('<div class="row"><div class="col-2">39-13B</div><div class="col-8"><u>Wann vorhin</u>?（さっきって何時？）</div><div class="col-2">159-161</div></div>');
document.write('<div class="row"><div class="col-2">39-14B</div><div class="col-8">［西］関係文で表現。</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2">39-15B</div><div class="col-8">Er weiß nicht, was er will</div><div class="col-2">163-175</div></div>');
document.write('<div class="row"><div class="col-2">39-16B</div><div class="col-8">疑問文は必ずしも文頭に来ない</div><div class="col-2">176-183</div></div>');
document.write('<div class="row"><div class="col-2">39-17B</div><div class="col-8">Alternativeの疑問文</div><div class="col-2">184-189</div></div>');
document.write('<div class="row"><div class="col-2">39-18B</div><div class="col-8">基礎事項  疑問副文か関係文か？</div><div class="col-2">190-199</div></div>');
document.write('<div class="row"><div class="col-2">39-19B</div><div class="col-8">如何にして、どう言う具合に  qua ratione?</div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2">39-20B</div><div class="col-8">否定肯定の問題 wer weiß, welch<br>…かわかったものじゃない。</div><div class="col-2">201-207</div></div>');
document.write('<div class="row"><div class="col-2">39-21B</div><div class="col-8">weiß Gott ! ［そりやどうも実に！］</div><div class="col-2">208-209</div></div>');
document.write('<div class="row"><div class="col-2">39-22B</div><div class="col-8"><u>Gott weiß</u>, wann und wie ich Euch wiedersehen<br>werde!</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2">39-23B</div><div class="col-8">was <u>warren</u>---? Wer <u>warren</u>---?</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2">39-24B</div><div class="col-8">Ist das ein Wein ? どうだ、うまいだろう？</div><div class="col-2">212-214</div></div>');
document.write('<div class="row"><div class="col-2">39-25R</div><div class="col-8">Warum ? Quare ? Cur ? Quam ob causam ?<br>［英］wphin ? woher ?<br>war = wohin</div><div class="col-2">215-218</div></div>');
document.write('<div class="row"><div class="col-2">39-26B</div><div class="col-8">how to～等</div><div class="col-2">219-222</div></div>');
document.write('<div class="row"><div class="col-2">39-27B</div><div class="col-8">Was Wunder ?</div><div class="col-2">223-224</div></div>');
document.write('<div class="row"><div class="col-2">39-28R</div><div class="col-8">［英］前置詞と疑問副文章  <u>on</u> how to avoid等<br>疑問視 für was?  statt   wofür ?<br>Que n\'ai-je....!  どうして…しなかったもの</div><div class="col-2">225-227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">だろうなぁ！<br>［英］as to whether～<br>adnominalな疑問従属文。</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">39-29B</div><div class="col-8">二つ以上の疑問詞を用ひた疑問文</div><div class="col-2">228-229</div></div>');
document.write('<div class="row"><div class="col-2">39-30R</div><div class="col-8">肯定形の侭の疑問文<br>［仏］疑問形式<br>Qu\'est-Ce que c\'est que ça?<br>［失］疑問文内の助辞<br>wo er in die Nachbarschaft hingegangen ist.<br>［疑問詞の他になほ詳しき規定］<br>soundsoviel, wievielstzt<br><br>編者注：このほか23件あり。<br></div><div class="col-2">230-244</div></div>');
document.write('<div class="row"><div class="col-2">39-31B</div><div class="col-8">la particule interrogative</div><div class="col-2">245-252</div></div>');
document.write('<div class="row"><div class="col-2">39-32B</div><div class="col-8">定形正置の質問文  doch nicht（まさか）は<br>必ず正置</div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2">39-33B</div><div class="col-8">特殊な疑問詞  wievielst?</div><div class="col-2">254-259</div></div>');
document.write('<div class="row"><div class="col-2">39-34B</div><div class="col-8">疑問詞分類  どんな具合か？  とういうわけか？<br>何処？</div><div class="col-2">260-261</div></div>');
document.write('<div class="row"><div class="col-2">39-35R</div><div class="col-8">疑問文の助詞一般論<br>denn eigentlich, nur, doch, zum Teufel. auch<br>Wie geht es ihr denn?<br>英語特有の疑問文章連結法。<br><br>編者注：このほか14件あり。</div><div class="col-2">262-269</div></div>');
document.write('<div class="row"><div class="col-2">39-36B</div><div class="col-8">疑問文に関する一般問題</div><div class="col-2">270-272</div></div></div>');