document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">41-1B</div><div class="col-8">再帰動詞</div><div class="col-2">1-82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］動詞の再帰「的」用法。 sich überwinden</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］自働詞に化す。  sich ereifern（gegen）</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］（sich....lasten, kaum...., t....merden.）の意</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］受動的になる。（könnenの概念を伴ふことあ<br>り）</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］<u>Es</u> sitzt <u>sich</u> schön等［非人称、自動］</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］三格支配の如きも、その三格は単にfür sich,<br>für seinen Gebrauchの意にして、in<br>loserem Verhältnisにあるもの。</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］alsの次の格で、真の再帰動詞と然らざるもの<br>とを見別ける方法。</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］sichの位置</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］獲得着服の三格 sich（自分のものにする）<br>sich etw. ausdennken</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］Hier <u>läßt</u> ［es］ <u>sich</u> schön sterben.</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］Hier plaudert sich\'s schön<br>イ夕リのsi può= man kann</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］相互的（主語は一方的で単数）</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2">41-2B</div><div class="col-8">三格支配再帰動詞<br>sich etwas merken. sich gütlich tun<br>sich etwa vornehmen<br>vorsetzen</div><div class="col-2">83-102</div></div>');
document.write('<div class="row"><div class="col-2">41-3B</div><div class="col-8">再帰か自働か？</div><div class="col-2">103-120</div></div>');
document.write('<div class="row"><div class="col-2">41-4B</div><div class="col-8">再帰代名詞<br>Er liebt <u>sich</u>とEr liebt <u>ihn</u></div><div class="col-2">121-221</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］sichの位置は強まる</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］sichが必ずしも文の主語ならざる例<br>jmn....sich ～ en lassen.<br>einen sich ～ en sehen.<br>ein sich erhebendes Gebäude</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］再帰代名詞と前置詞の熟語。</div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］A. sichはなる可く前に。（副文章でも）</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］人代名詞を用ひる例</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］三格のsich（掴得着服）</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］再帰代名詞は四格のみで、一・二格は<br>人代名詞を使ふ（殊に二格）</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］sichの位置例外。</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］lassenとの構造においては文の主語以外の<br>目的語のsichあり（主語と一致せず）</div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］sichの省略</div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］一般的に云ふ際（不定句の或種の場合）には<br>sichでも<u>mich</u>等でもよきことあり。</div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2">41-5R</div><div class="col-8">再帰哲学の結論<br>”<u>思った</u>”をsich sagen müssen等<br>Heideggerの語学的sich<br>schläft sich was !<br><u>es hat sich</u> was mit dem Strike !<br>再帰は自働なり、という最も一般的な観察<br><br>儡者注：このほか7件あり。</div><div class="col-2">222-233</div></div>');
document.write('<div class="row"><div class="col-2">41-6B</div><div class="col-8">［英」hlmとhlmself［<u>前置詞</u>の有無<u>で決す</u>］</div><div class="col-2">234-241</div></div>');
document.write('<div class="row"><div class="col-2">41-7R</div><div class="col-8">［仏」soi<br>sich packen, sich fort machen, sich stehlen,<br>sich scheren, sich davonmachen<br>等の類型としての<u>sich</u> trollen等<br><br>編者注：このほか6件あり。</div><div class="col-2">242-246</div></div>');
document.write('<div class="row"><div class="col-2">41-8R</div><div class="col-8">sich mit etw. <br>tragen（ = herumtragen）<br>sich....herum necken等。<br>sich herum quälen<br>［仏」命令形の際  Donne-moiの代りに<br>Me donne !<br>再帰形のみしかない動詞  sich schäen<br>［仏」再帰動詞<br><br>編者注：このほか19件あり。</div><div class="col-2">247-259</div></div></div>');