document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">39-1B</div><div class="col-8"><a href="../039/s0001.html">wo kommt die Stimme <u>her</u> ?</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">39-2B</div><div class="col-8"><a href="../039/s0002.html">疑問文</a></div><div class="col-2">2-84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0004.html">［01］反語</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0005.html">［02］反語 wer <u>wollte</u>....?<br>…する奴があるか。</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0006.html">［03］was für eins ?  was für welches ?</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0007.html">［04］疑問文副文章。</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0013.html">［05］疑問副文章の省略。</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0014.html">［06］was....［nucht］ alles...反語。</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0015.html">［07］was....anderes, besseres, viel, groß, mehr, sonst</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0016.html">［08］疑問詞の先置とその配語。</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0029.html">［09］疑問詞で始まる問投文の意味。</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0030.html">［10］疑問文を強めるための飾り。<br>（in aller welt等）</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0036.html">［11］疑問文の二つの定形の始末</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0036.html">［12］感嘆文。（定形の位置と助詞）<br><u>What</u> a horrible idea !</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0038.html">［13］副文章的疑問文か極くルーズに主文章に結び<br>つく例。（Kontamination）</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0051.html">［14］mit was, auf was等。（関係代名詞も）</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0053.html">［15］疑問関係文か関係文か?（難）</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0056.html">［16］Adnominalな疑問副文章。<br>Der Grund, warum等</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0058.html">［17］<u>Was weiß ich</u> ? （分かったものじゃなぃ）</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0061.html">［18］<u>Was</u> reden ?  不定法の用法</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0062.html">［19］<u>Weißt du was</u> ? （was ich sagen wollte）</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0070.html">［20］ich weiß nicht was等</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0081.html">［21］疑問文、反語文の定形主語省略。</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0083.html">［22］「等々」の意のWer nennte sie alle等。</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0084.html">［23］<u>nicht wahr</u> ? （gelt,? was ? wie ? ja ? hm ?）</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2">39-3B</div><div class="col-8"><a href="../039/s0085.html">Wozu....? ［羅］<u>quid opus</u> nota noscere ?</a></div><div class="col-2">85-89</div></div>');
document.write('<div class="row"><div class="col-2">39-4B</div><div class="col-8"><a href="../039/s0090.html">叙事詩の導入的疑問文</a></div><div class="col-2">90-91</div></div>');
document.write('<div class="row"><div class="col-2">39-5R</div><div class="col-8"><a href="../039/s0092.html">［英］whom are you talking about ? </a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2">39-6B</div><div class="col-8"><a href="../039/s0093.html">疑問詞</a></div><div class="col-2">93-131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0094.html">［01］wohinの代りにwo hin= 等</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0097.html">［02］was für.</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0105.html">［03］間投的wasをwieの意に用ひる。［なんと…！］</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0115.html">［04］ich Weiß nicht welch=等。</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0119.html">［05］二人のうちで「どちらの者が」は（we1cher <u>von</u><br>beiden）または単に<u>wer</u>を用ひる事。</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0122.html">［06］Was glaubst du, daß es kostet ?</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0123.html">［07］Werは複数にも用ひる事。</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0124.html">［08］was für welches ?（=was für eins ?）</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0127.html">［09］was, wessen, ---, was.</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0131.html">［10］<u>Was gibts Neues</u> ?</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2">39-7B</div><div class="col-8"><a href="../039/s0132.html">adnominal = 疑問副文章<br>=関係文章</a></div><div class="col-2">132-134</div></div>');
document.write('<div class="row"><div class="col-2">39-8B</div><div class="col-8"><a href="../039/s0135.html">was sag ich?  それどころか。</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2">39-9B</div><div class="col-8"><a href="../039/s0136.html">［仏］仏の疑問文（その特殊性）</a></div><div class="col-2">136-137</div></div>');
document.write('<div class="row"><div class="col-2">39-10B</div><div class="col-8"><a href="../039/s0138.html">was = etwas<br>wer = jemand</a></div><div class="col-2">138-143</div></div>');
document.write('<div class="row"><div class="col-2">39-11B</div><div class="col-8"><a href="../039/s0144.html">nicht wahr?</a></div><div class="col-2">144-156</div></div>');
document.write('<div class="row"><div class="col-2">39-12R</div><div class="col-8"><a href="../039/s0157.html">どちらが？ wederez<br>Wer?=welcher von beiden?<br>（二人のうちでどちらが）</a></div><div class="col-2">157-158</div></div>');
document.write('<div class="row"><div class="col-2">39-13B</div><div class="col-8"><a href="../039/s0159.html"><u>Wann vorhin</u>?（さっきって何時？）</a></div><div class="col-2">159-161</div></div>');
document.write('<div class="row"><div class="col-2">39-14B</div><div class="col-8"><a href="../039/s0162.html">［西］関係文で表現。</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2">39-15B</div><div class="col-8"><a href="../039/s0163.html">Er weiß nicht, was er will</a></div><div class="col-2">163-175</div></div>');
document.write('<div class="row"><div class="col-2">39-16B</div><div class="col-8"><a href="../039/s0176.html">疑問文は必ずしも文頭に来ない</a></div><div class="col-2">176-183</div></div>');
document.write('<div class="row"><div class="col-2">39-17B</div><div class="col-8"><a href="../039/s0184.html">Alternativeの疑問文</a></div><div class="col-2">184-189</div></div>');
document.write('<div class="row"><div class="col-2">39-18B</div><div class="col-8"><a href="../039/s0190.html">基礎事項  疑問副文か関係文か？</a></div><div class="col-2">190-199</div></div>');
document.write('<div class="row"><div class="col-2">39-19B</div><div class="col-8"><a href="../039/s0200.html">如何にして、どう言う具合に  qua ratione?</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2">39-20B</div><div class="col-8"><a href="../039/s0201.html">否定肯定の問題 wer weiß, welch<br>…かわかったものじゃない。</a></div><div class="col-2">201-207</div></div>');
document.write('<div class="row"><div class="col-2">39-21B</div><div class="col-8"><a href="../039/s0208.html">weiß Gott ! ［そりやどうも実に！］</a></div><div class="col-2">208-209</div></div>');
document.write('<div class="row"><div class="col-2">39-22B</div><div class="col-8"><a href="../039/s0210.html"><u>Gott weiß</u>, wann und wie ich Euch wiedersehen<br>werde!</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2">39-23B</div><div class="col-8"><a href="../039/s0211.html">was <u>warren</u>---? Wer <u>warren</u>---?</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2">39-24B</div><div class="col-8"><a href="../039/s0212.html">Ist das ein Wein ? どうだ、うまいだろう？</a></div><div class="col-2">212-214</div></div>');
document.write('<div class="row"><div class="col-2">39-25R</div><div class="col-8"><a href="../039/s0215.html">Warum ? Quare ? Cur ? Quam ob causam ?<br>［英］wphin ? woher ?<br>war = wohin</a></div><div class="col-2">215-218</div></div>');
document.write('<div class="row"><div class="col-2">39-26B</div><div class="col-8"><a href="../039/s0219.html">how to～等</a></div><div class="col-2">219-222</div></div>');
document.write('<div class="row"><div class="col-2">39-27B</div><div class="col-8"><a href="../039/s0223.html">Was Wunder ?</a></div><div class="col-2">223-224</div></div>');
document.write('<div class="row"><div class="col-2">39-28R</div><div class="col-8"><a href="../039/s0225.html">［英］前置詞と疑問副文章  <u>on</u> how to avoid等<br>疑問視 für was?  statt   wofür ?<br>Que n\'ai-je....!  どうして…しなかったもの</a></div><div class="col-2">225-227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../039/s0225.html">だろうなぁ！<br>［英］as to whether～<br>adnominalな疑問従属文。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">39-29B</div><div class="col-8"><a href="../039/s0228.html">二つ以上の疑問詞を用ひた疑問文</a></div><div class="col-2">228-229</div></div>');
document.write('<div class="row"><div class="col-2">39-30R</div><div class="col-8"><a href="../039/s0230.html">肯定形の侭の疑問文<br>［仏］疑問形式<br>Qu\'est-Ce que c\'est que ça?<br>［失］疑問文内の助辞<br>wo er in die Nachbarschaft hingegangen ist.<br>［疑問詞の他になほ詳しき規定］<br>soundsoviel, wievielstzt<br><br>編者注：このほか23件あり。<br></a></div><div class="col-2">230-244</div></div>');
document.write('<div class="row"><div class="col-2">39-31B</div><div class="col-8"><a href="../039/s0245.html">la particule interrogative</a></div><div class="col-2">245-252</div></div>');
document.write('<div class="row"><div class="col-2">39-32B</div><div class="col-8"><a href="../039/s0253.html">定形正置の質問文  doch nicht（まさか）は<br>必ず正置</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2">39-33B</div><div class="col-8"><a href="../039/s0254.html">特殊な疑問詞  wievielst?</a></div><div class="col-2">254-259</div></div>');
document.write('<div class="row"><div class="col-2">39-34B</div><div class="col-8"><a href="../039/s0260.html">疑問詞分類  どんな具合か？  とういうわけか？<br>何処？</a></div><div class="col-2">260-261</div></div>');
document.write('<div class="row"><div class="col-2">39-35R</div><div class="col-8"><a href="../039/s0262.html">疑問文の助詞一般論<br>denn eigentlich, nur, doch, zum Teufel. auch<br>Wie geht es ihr denn?<br>英語特有の疑問文章連結法。<br><br>編者注：このほか14件あり。</a></div><div class="col-2">262-269</div></div>');
document.write('<div class="row"><div class="col-2">39-36B</div><div class="col-8"><a href="../039/s0270.html">疑問文に関する一般問題</a></div><div class="col-2">270-272</div></div></div>');