document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">40-1B</div><div class="col-8">それ以上にも非ず、以下にも非ず：<br>nicht mehr, nicht weniger.</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">40-2B</div><div class="col-8">皮肉  Warum nicht gar ! Lieber gar !</a></div><div class="col-2">2-18</div></div>');
document.write('<div class="row"><div class="col-2">40-3B</div><div class="col-8"><u>lange</u> nicht</a></div><div class="col-2">19-22</div></div>');
document.write('<div class="row"><div class="col-2">40-4B</div><div class="col-8">そう大して、かくべつ  groß, Viel sonderlich<br>nicht weiter. Was hat es schon zu bedeuten?</a></div><div class="col-2">23-33</div></div>');
document.write('<div class="row"><div class="col-2">40-5B</div><div class="col-8">否定</a></div><div class="col-2">34-190</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］so wenig -----als.（daß）（wie）</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］二重否定 Das ist nicht ganz ohne.</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］nichts weniger ----als.</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］nichts so wenig----als.</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］um nicht, wenn nicht, daß ja nicht....</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］否定の強調。</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］準否定調</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］”必ずしも”の語順</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］二重の否定  nicht am wenigsten<br>nicht zu letzt.（nicht zum letzten）</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］nur kein, nur nichts （認容後の否定）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］二重の否定（wenn nicht）</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］nichts als等</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］nichts <u>mehr</u>. etc.</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］nein,----</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］nicht ein.</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］nicht einmal.（nichtmal）</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［17］nicht weniger als.... …を下らぬ</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［18］<u>sondern</u>.</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［19］mehr（モハヤ）は準否定詞お共に用ひる時は<br><u>noch</u>で表わす。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［20］den Teufel等</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［21］alles andere....als.</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［22］nicht --- の代りにkein----</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［23］nicht genug....können.<br>nie....zu....（könnenなくともよし）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［24］ニの否定（餘計）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［25］Nemoの積極概念化。 the noman等</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［26］....fand aber <u>keine</u>.<br>（代名詞とnichtとの代り）</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［27］感嘆文（疑問詞ある）のnichtは有っても<br>無くてもよし。</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［28］否定を強めるための、［auch nicht....、<br>selbst....の意の］nicht entfernt,<br>nicht im geringsten等</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［29］entfernt.  weit entfernt,----</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［30］<u>nichts weniger</u>をnichts Geringeres als<br>の代りに用ひること。</a></div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［31］云々ほど云々なものは無い。</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2">40-6B</div><div class="col-8">nicht,wieの構文［nichtの位置の問題］</a></div><div class="col-2">191-203</div></div>');
document.write('<div class="row"><div class="col-2">40-7B</div><div class="col-8">況んや…をや  viel weniger  なおさらのこと。<br>noch weniger いはんや</a></div><div class="col-2">204-213</div></div>');
document.write('<div class="row"><div class="col-2">40-8B</div><div class="col-8">反語  Er hätte mich ～ ?<br>was habe ich nicht alles gehört ?</a></div><div class="col-2">214-232</div></div>');
document.write('<div class="row"><div class="col-2">40-9B</div><div class="col-8">それ自身が既に否定的観念を含む動詞の規定句<br>wer weiß</a></div><div class="col-2">233-248</div></div>');
document.write('<div class="row"><div class="col-2">40-10R</div><div class="col-8">［英］Doubt thou, the stars are fire,<br>［羅典］quo secius = qus minus<br>肯定語を用ひるか否定語を用ひるか？<br>あいまいな場合<br>云々でないと誰が保せん?（反語）<br>obの場合は分ける。<br>sanndersの説明法</a></div><div class="col-2">249-262</div></div>');
document.write('<div class="row"><div class="col-2">40-11B</div><div class="col-8">nicht umhin können.  sich nicht enthalten können.</a></div><div class="col-2">263-276</div></div>');
document.write('<div class="row"><div class="col-2">40-12B</div><div class="col-8">比較に依って暗に否定  1.=ebensowenigと同じ<br>2.→皮肉</a></div><div class="col-2">277-282</div></div>');
document.write('<div class="row"><div class="col-2">40-13B</div><div class="col-8">［MHD］en=</a></div><div class="col-2">283-291</div></div>');
document.write('<div class="row"><div class="col-2">40-14B</div><div class="col-8">信じて疑はず</a></div><div class="col-2">292-301</div></div>');
document.write('<div class="row"><div class="col-2">40-15B</div><div class="col-8">［英］、［仏］否定の初歩事項一括</a></div><div class="col-2">302-311</div></div>');
document.write('<div class="row"><div class="col-2">40-16B</div><div class="col-8">kein考</a></div><div class="col-2">312-315</div></div>');
document.write('<div class="row"><div class="col-2">40-17R</div><div class="col-8">語形考：noch ein  nichein  einig<br>動詞のみの訂正的否定<br>nicht immer  immer nicht<br>Der Henker behalte alle ihre Namen !</a></div><div class="col-2">316-321</div></div>');
document.write('<div class="row"><div class="col-2">40-18B</div><div class="col-8"><u>letzt</u>  1. der letzte sein+ zu + <u>INF</u> →<br>der etste sein<br>2. nicht zuletzt →</a></div><div class="col-2">322-328</div></div>');
document.write('<div class="row"><div class="col-2">40-19R</div><div class="col-8">もはや（nicht mehr.）<br>nichtsの用法</a></div><div class="col-2">329-330</div></div>');
document.write('<div class="row"><div class="col-2">40-20B</div><div class="col-8">auf der Welt Gottes nicht等</a></div><div class="col-2">331-333</div></div>');
document.write('<div class="row"><div class="col-2">40-21B</div><div class="col-8">否定の返事  "Nichts wird umsonst gegeben !"<br>"nein."</a></div><div class="col-2">334-335</div></div>');
document.write('<div class="row"><div class="col-2">40-22B</div><div class="col-8">前綴  Un=とNicht=（諸項一括）</a></div><div class="col-2">336-349</div></div>');
document.write('<div class="row"><div class="col-2">40-23B</div><div class="col-8">否定意の動詞  ausbleiben, unterbleiben/<br>［英］fail to</a></div><div class="col-2">350-354</div></div>');
document.write('<div class="row"><div class="col-2">40-24R</div><div class="col-8">La mémoire me <u>fait défaut</u>.<br>lassen （=unterlassen）  fahren lassen<br>否定の意の動詞  schenken, dispenser<br>unterbleiben<br><br>編者注：このほか7件あり。</a></div><div class="col-2">355-360</div></div>');
document.write('<div class="row"><div class="col-2">40-25B</div><div class="col-8">kam und nicht 及び肯定形</a></div><div class="col-2">361-365</div></div>');
document.write('<div class="row"><div class="col-2">40-26B</div><div class="col-8">”毫も”</a></div><div class="col-2">366-377</div></div>');
document.write('<div class="row"><div class="col-2">40-27B</div><div class="col-8">beileibe</a></div><div class="col-2">378-379</div></div>');
document.write('<div class="row"><div class="col-2">40-28B</div><div class="col-8">nicht im <u>mindesten</u>  nicht im <u>geringsten</u></a></div><div class="col-2">380-382</div></div>');
document.write('<div class="row"><div class="col-2">40-29B</div><div class="col-8">weder....noch....考</a></div><div class="col-2">383</div></div>');
document.write('<div class="row"><div class="col-2">40-30B</div><div class="col-8">否定強調用のjeder, irgendwelche, alle等</a></div><div class="col-2">384-390</div></div>');
document.write('<div class="row"><div class="col-2">40-31B</div><div class="col-8">Kaum 否定的でない場合</a></div><div class="col-2">391-393</div></div>');
document.write('<div class="row"><div class="col-2">40-32R</div><div class="col-8">nicht bald  nicht leicht  さうざらには無い<br>nicht leicht</a></div><div class="col-2">394</div></div>');
document.write('<div class="row"><div class="col-2">40-33B</div><div class="col-8">否定意の名詞とその規定<br>Die Unmöglichkeit, etwas zu tun.</a></div><div class="col-2">395-398</div></div>');
document.write('<div class="row"><div class="col-2">40-34R</div><div class="col-8">［羅］nescio, ignosco, nequeo nolo等<br>否定を含む動詞 nequit<br>Nicht ich !  Ich nicht !  Not I !<br>決して  auf keinen Fall<br><br>縮者注：このほか23件あり。</a></div><div class="col-2">399-420</div></div>');
document.write('<div class="row"><div class="col-2">40-35B</div><div class="col-8">否定詞初歩例</a></div><div class="col-2">421-437</div></div>');
document.write('<div class="row"><div class="col-2">40-36B</div><div class="col-8">Nichts wie fort !</a></div><div class="col-2">438-439</div></div>');
document.write('<div class="row"><div class="col-2">40-37B</div><div class="col-8">weiterと否定詞（別に大して、等）</a></div><div class="col-2">440</div></div>');
document.write('<div class="row"><div class="col-2">40-38B</div><div class="col-8">断然不可！ とんでもない！<br>nimmer <u>und</u> nimmer  その他  nun <u>und</u> nimmer<br><u>nun</u> und <u>nimmermehr</u></a></div><div class="col-2">441-443</div></div>');
document.write('<div class="row"><div class="col-2">40-39R</div><div class="col-8">必ずしも  まんざら…<br>Not always.<br>nichts dergleichen geschieht.（ところがさに非ず）</a></div><div class="col-2">444-452</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">始まる、止む（haben支配は意型上の例外）<br>否定の「いづれも」 ［英］：neither<br>［独］：keine von beiden<br>［仏］：ni l\'un ni l\'autre.<br>［仏］否定形式としてのle moyen<br>Le moyen que ce soit autrement !<br>問投的否定句  Firlefanz !  Ja, Kuchen !<br>Quatsch !  Prost Mahlzeit !<br>he\'s <u>no good</u> for ～<br><br>編者注：このほか8件あり。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">40-40B</div><div class="col-8">否定に関する参考的見地  三重否定  局部否定<br>nicht minder und undurchdringlich</a></div><div class="col-2">453</div></div>');
document.write('<div class="row"><div class="col-2">40-41R</div><div class="col-8">二重否定による全称肯定強調  及び比較によるもの<br>keine Regel ohne Ausnahme.<br>keine Wirkung ohne Ursache.<br>云々しないにしては餘りに云々…<br>否定詞をふくむもの（nicht zu letztと一致）<br>おだやかな強調<br>und übrigens sei Neugierde <u>gar nicht</u> ihr Fehler.<br>C\'est là son moindre defaut.の説明用<br><br>編者注：このほか8件あり。</a></div><div class="col-2">454-465</div></div>');
document.write('<div class="row"><div class="col-2">40-42B</div><div class="col-8">nichts Geringeres als....</a></div><div class="col-2">466-473</div></div>');
document.write('<div class="row"><div class="col-2">40-43B</div><div class="col-8">否定強調を、何等かの局部にもってゆく  nichts他</a></div><div class="col-2">474</div></div>');
document.write('<div class="row"><div class="col-2">40-44R</div><div class="col-8">nichtsの用法  kein, nichts等の積極概念化の現象<br>bringt kein Glück.  碌なことはない<br><u>No good</u> can come from over the hills.<br>動詞そのものを強く否定せんがため<br>強調否定の<u>nichts</u></a></div><div class="col-2">475-476</div></div></div>');