document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">41-1B</div><div class="col-8"><a href="../041/s0001.html">分詞句  PARTIZIPIAL K0NSTRUKTI0N</a></div><div class="col-2">1-24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0002.html">［01］過去分詞（wenn--の文に等しくなる）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0004.html">［02］過去分詞句</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0005.html">［03］現在分詞句（副詞規定的）</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0006.html">［04］…［habend,tragend…］描写的述況言</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0008.html">［05］四格を伴ふ過去分詞句。</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0011.html">［06］四格補足語の分詞句（及分詞省略の句）</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0017.html">［07］…したところの彼は。（［代］名詞の分詞句）</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0020.html">［08］一格を伴ふ現在分詞句（自働詞の過去分詞）</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0022.html">［09］仮定強調の現在分詞句（も四格を取る。）</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0024.html">［10］したところの彼「を」（四格代名詞前の分詞句）</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0024.html">［11］省略文的Ein Schluck, ....ein Ruck等。</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0024.html">［12］名詞に後置される未来受働分詞句（述語）</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2">44-2B</div><div class="col-8"><a href="../041/s0025.html">過去分詞</a></div><div class="col-2">25-112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0027.html">［01］命令的用法、又は"Aufruf"<br>aufgemacht! 又はAufmachen!（開けろ！）</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0032.html">［02］聞投的に嘆稱又は警嘆する際の述語用法。<br>Teufel, das <u>ist</u> wenig <u>gefordert</u>.</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0036.html">［03］形容詞化せるP.P.</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0046.html">［04］形容詞化したるものにして、過去分詞のみしか<br>なきもの。</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0047.html">［05］Gespiungener Huf!</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0063.html">［06］Eine Kugel kam <u>geflogen</u>.</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0073.html">［07］ge=の附かぬもの。（-ierenに非ざる）</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0086.html">［08］仮定強調（断書）</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0086.html">［09］仮定的挿入（wohlgemerkt：等も）</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0098.html">［10］殆ど不定法名詞的に用ふ（諺）</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0101.html">［11］自働的過去分詞。  ein <u>abgelebter</u> Mann.</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">44-3B</div><div class="col-8"><a href="../041/s0113.html">未来受働分詞</a></div><div class="col-2">113-120</div></div>');
document.write('<div class="row"><div class="col-2">44-4B</div><div class="col-8"><a href="../041/s0121.html">現在分詞</a></div><div class="col-2">121-152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0122.html">［01］Attributiv （Progressiv）</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0130.html">［02］Attributiv u.nicht progressiv.</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0130.html">［03］zu....end.</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0132.html">［04］副詞的</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0134.html">［05］現在分詞の非進行的意味（Funktion）</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0140.html">［06］附加的。（常用形式として）常形</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0141.html">［07］助動詞_の現在分詞は稀。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0141.html">［08］述語として：</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0142.html">［09］vorhabende Reise  vorgehabtの代りの</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0151.html">［10］分詞（現在）とその主語の問題</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0152.html">［11］同時性的性質の説明用。</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../041/s0152.html">［12］同時性（進行と言ってもよい）の強調と現分詞の機能－云々する立場－</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2">44-5B</div><div class="col-8"><a href="../041/s0153.html">不定法形の過去分詞<br>Ich habe / in England viel ertragen <u>lernen</u>,<br>/Ich kann auch das verschmerzen.</a></div><div class="col-2">153-158</div></div>');
document.write('<div class="row"><div class="col-2">44-6B</div><div class="col-8"><a href="../041/s0159.html">冠飾句 at which there was a general silence and<br>consternation, and a by no means pleasant<br>look in Becky\'s eyes.</a></div><div class="col-2">159-176</div></div>');
document.write('<div class="row"><div class="col-2">44-7R</div><div class="col-8"><a href="../041/s0177.html">古典語の未来分詞<br>未来分詞（古典語）梵の第二未来<br>［梵］ Morituri te salutant.</a></div><div class="col-2">177-180</div></div>');
document.write('<div class="row"><div class="col-2">44-8B</div><div class="col-8"><a href="../041/s0181.html">schwer erreicht型<br>Wenn fern des schnellen Laufes Kranz<br>vom <u>schwer erreichten</u> Ziele winket.</a></div><div class="col-2">181-186</div></div>');
document.write('<div class="row"><div class="col-2">44-9B</div><div class="col-8"><a href="../041/s0187.html">義務分詞  ねばならぬ</a></div><div class="col-2">187-191</div></div>');
document.write('<div class="row"><div class="col-2">44-10R</div><div class="col-8"><a href="../041/s0192.html">［仏］過去分詞の性数表現  faitとfaite, faits<br>Car le plus grand châtiment d\'avoir <u>fait</u><br>une offense, c\'est de l\'avoir <u>faite</u>.<br>過分詞の形容詞化  verschlagen, verwegen, gewachsen<br>派生問題：全然副詞化するものあり：<br>編者注：このほか3件あり。</a></div><div class="col-2">192-195</div></div>');
document.write('<div class="row"><div class="col-2">44-11B</div><div class="col-8"><a href="../041/s0196.html">［英］GERUND［A］be ～ ing</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2">44-12B</div><div class="col-8"><a href="../041/s0197.html">［英］GERUNDと現在分詞との間が接する現象</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">44-13B</div><div class="col-8"><a href="../041/s0198.html">古典語の現在分詞構造</a></div><div class="col-2">198-199</div></div>');
document.write('<div class="row"><div class="col-2">44-14R</div><div class="col-8"><a href="../041/s0200.html">古典語・分詞の述語句的用法（現在分詞）<br>essenの過去分詞が変態なる事<br>過去分詞形の副詞  wiederholt, angestreugt<br>不定法の過去分詞。（lernen）</a></div><div class="col-2">200-202</div></div>');
document.write('<div class="row"><div class="col-2">44-15B</div><div class="col-8"><a href="../041/s0203.html">過去分詞一般（attributiv）</a></div><div class="col-2">203-204</div></div>');
document.write('<div class="row"><div class="col-2">44-16R</div><div class="col-8"><a href="../041/s0205.html">英仏的adnominalなる分詞句<br>名詞にSaxon genitiveをつける際の語順に注意せよ。<br>現在分詞の進行形的用法について<br>als,,..［述語たる句］には分詞句を用ひなければならぬ<br>lassenかgelassenか？</a></div><div class="col-2">205-206</div></div></div>');