document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">46-1B</div><div class="col-8">普通動詞の助動詞化  話法の助動詞</div><div class="col-2">1-76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］wollenの意味形態多し<br><u>gedenken</u>.<br>（wann gedenkst du weiter zu reisen?）</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］wissen</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］<u>übrig bleiben</u>.</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］Zuを伴はざるもの <u>machen</u></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］biauchen（必要なし）  nicht（又は…に<br>及ばぬ）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］brauchen（…しさえすれば）</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］brauchen（nicht....）…するとは限らない。</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］pflegen.</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］<u>helfen</u>.</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］lernen.</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］scheinen.</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］suchen, versuchen, streben, verlangen, wünschen.</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］wagen.</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］gedanken, denken.</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］lieben</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］verstehen.</div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［17］drohen.</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［18］glauben. meinen.</div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［19］geruhen, belieben.</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［20］コンマなく用ひて準助動詞するもの。［雑］</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［21］meinen    …かとおもった<br>云々しそうである。  wollen.<br>云々したつもりである。</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［22］heißen.（befehlen）</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［23］tun, tät,----</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［24］不定法形の過去分詞。</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［25］vermeinen  wähnen</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［26］「zu+不定句」を伴ふものが助動詞化する<br>中間現象。</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［27］beginnen, anfangen</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［28］<u>vermögen</u>.</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［29］hoffenその他</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［30］wünschen, belieben等</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［31］英、仏  deカàか</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2">46-2B</div><div class="col-8">二個の単文の融合 verbum sentiendi</div><div class="col-2">77-122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］Ich höre ihn singen.</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Ich habe ihn singen <u>hören</u>（<u>gehört</u>）</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］不定法の代りに形容詞、状況言。</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］特にwissenの用法。sehen<br>haben  glauben, wähnen,</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］四格名詞を宣告する述語。</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］不定法。（副文章の主語がmanの際はeinenと<br>して置き移すこともあれば、全然畧する事<br>もある。）</div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］不定法形の過去分詞（heißen）</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］四格とwie-の構造</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］四格と現在分詞の構造。<br>finden, tieffen, sehen等。</div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2">46-3B</div><div class="col-8">話法の助勤詞  一般論</div><div class="col-2">123-182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］不定法形の過去分詞</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］habenの前置（主文章に於ける）</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］定形の前置（副文章に於け）（主文章もあり）</div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］四個以上の動詞の始末</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］二個の不定形の後に助動詞が来る時<br>（定形前置の必要なき時）</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］gewordenとworden.</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］誤った語法（時稱の表現）</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］gehen, kommen等の省略。</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］独立用法の過去分詞の俗調的例外。</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］不必要な定形前置。（volkstümlich）</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］助動詞のみの独立用法。</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］werdenの重複を避けるための定形前置。</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］不定法形過去分詞（例外的語の）</div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］助勤詞を二個用ふ。普通の例。</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2">46-4B</div><div class="col-8">話法的意局</div><div class="col-2">183-191</div></div>');
document.write('<div class="row"><div class="col-2">46-5R</div><div class="col-8">lassenと三格支配<br>so laß er es doch <u>dem gnädigen Fräulein</u><br>nicht <u>entgelten</u>.<br>-toの有無と意型－  helfenの助動詞的用法<br>卜イツ語は他語よりも話法助動詞を多く用ふ<br>餘計な話法助動詞。</div><div class="col-2">192-194</div></div>');
document.write('<div class="row"><div class="col-2">46-6B</div><div class="col-8">［仏］à支配動詞</div><div class="col-2">195-200</div></div>');
document.write('<div class="row"><div class="col-2">46-7B</div><div class="col-8">［仏］de支配動詞</div><div class="col-2">201-206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［希・羅］<br>Cum maxma cura ultum ire injruas <u>festinat</u>.</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">46-8R</div><div class="col-8">過去分詞の両形に関する鉄則はlassenをも含む<br>（gelassenもあり、但しwurdenの前）<br>....gelten <u>gelassen</u> wurdeなど<br>形の上のこと  三人称単で独t（英s）の語尾を<br>つけぬこと<br>It no longer <u>need</u> be dreaded.<br>Ee braucht nicht mehr befürchtet zu werden.<br>fallen <u>lassen</u>   fallen <u>gelassen</u><br>［英］助動詞に不定法過去がないために起る<br>換形の問題<br>「二文合体」と「zu+不定句」との関係（一般問題<br>として）<br>二文合体には、代名詞の重畳を避けて一方を省く<br>場合が生じて来る。<br>［英］助動詞的なもの<br>I do not <u>mean to</u> say it is impossible.<br>［仏］finir par+Inf.<br>commençer<br>［英］needの語尾  －人稱変化－</div><div class="col-2">207-210</div></div>');
document.write('<div class="row"><div class="col-2">46-9B</div><div class="col-8">zu+不定句を要する半助動詞的動詞</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2">46-10B</div><div class="col-8">［英］will, can 等の不定法に関する参項</div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2">46-11B</div><div class="col-8">－廣義の－話法的色彩表現の動詞+zu 不定句。</div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2">46-12R</div><div class="col-8">話法助動詞が二つ以上使ひ分けてある場合にも最も<br>区別がはっきりする。<br>Da war gar kein Zweifel, von hier <u>mußte und</u><br><u>wollte</u> er fort.<br>二文合体に関する英語における習慣<br>We started at him in silence, <u>expecting him</u><br><u>to speak</u>.</div><div class="col-2">214</div></div></div>');