document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">48-1B</div><div class="col-8">接続法  間接話法</a></div><div class="col-2">1-100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］glauben, behaupten u.s.w.</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］<u>Gesetzt</u>, と  第二式 <u>angenommen</u><br>第一式</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］間接話法の主文章化。</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］名詞を引伸す間説文  obゃwasもあり！</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］直接法を用ひる際（daßの次に）</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］関係代名詞文の間接法。</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］I think, you are式</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］接続法を第二次以の副文章に延ばす事の可否。</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］強変化動詞の第二式はくだけてよし。<br>ginge, wäre, käme等。</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］特に第二式を用ふるは、願望文の聞接話法。</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］聞接話法と区別すベき直接話法の副文章</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］一人称について傳へる事実には問接法を用ひず。</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］daß....sei.等（説明用。）<br>「引用文」（如何にもsatz, theseらしき<br>もの）</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］第二次を特に接続法にする場合。<br></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（直接法にすれば引用法でなくなる）</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］疑問間接法。（obをも含む）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］反問。（間接話法的）</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［17］…なぞとは（懐疑的引用）</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［18］sagte er等の基礎文があるにも拘らず、間接<br>話法を用ふ</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［19］第三次以下の接続法（als ob, ....wäre, の次）</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2">48-2B</div><div class="col-8">接続法  第二式  KONJUNCTIVUS</a></div><div class="col-2">101-264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］（複合時稱を用ふ）意外であった、豫期に反し<br>たという意。</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］疑問文定形の第二式（wird）</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］言者の主観が否定せんが為めに假に作って見るも<br>の。［疑の意の一形態］…なぞとは（<u>daß</u>）</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］遠慮した主張。直接性を避けるため。<br>［lch wollte, er käme bald.］</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］関係文の中の第二式。 否定。</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>驚嘆</u>が交るために信じがたき意。（<u>安心の表現</u>）</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］過去と助動詞</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］もうすこしの所で…する所だった等。</a></div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］als ob ,als wenn.</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］als ob。－－まさか…でもあるまいし。</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］wie <u>wenn</u>と直接法</a></div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］statt daß....第二式<br>ohne daß</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］否定と合した全体を「非現実」か「現実」かと<br>考へなければならぬ。</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］wie wenn....?（と第二式）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］願望（daß--;と後置）</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］嘆息的「ぐち」wenn....! wer---!<br>希求の表現</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［17］so...., daß....<u>nicht</u> hätte.（sollte）</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［18］（zu）....als daßには第二式。</a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［19］従属文中の第二式。（主文章に否定ある時）</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［20］<u>Wenn</u> uns jemand <u>hörte</u>! （Wie, wenn....?）</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2">48-3B</div><div class="col-8">羅典語・佛式の間接話法可能法的－daß....の文で</a></div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2">48-4B</div><div class="col-8">助動詞 würde</a></div><div class="col-2">266-282</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］想像の未未（であらう）</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］受身の第二接続法。</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］約束法として。（約束法の未未性）</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］関係文内のwürde（でもあらう様な）</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］約束法の殊に結論部は弱変化動詞の際は第<br>二式よりもwürdeを可とす。</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］普通の約束法結論</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2">48-5B</div><div class="col-8">接続法  約束法  <u>Protasis</u> und <u>Apodosis</u></a></div><div class="col-2">283-389</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］結論のみ。</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］前提のみ（願望悔恨）<u>doch</u>と<u>nur</u></a></div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］後に重點のこもるもの。（wenn....II,）<br>「後続的従属文」<u>nur</u>に注意。</a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］前提の方の時稱表現<br>....ginge（現在） ....gehen würde（未）<br>geg.wären（過）</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］würdeを単に疑問の意に用ひる。</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］würdeを結論文に用ふ。</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］前提部と雖も、未未の意を利かせんとする時<br>にはwürdeを用ふ。</a></div><div class="col-2">359</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］元来の約束法の意に非ざる場合に、単なる<br>Hoflichkeitsformとして。（diplomatisch）</a></div><div class="col-2">360</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］さぞ…であらう！</a></div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］疑問詞と共に－－Was gäbe ich nicht darum,!</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］約束法的語法に非ずして第二式の一種の使ひ<br>方なる際（遠慮した主張）しかも約束法の<br>形式がととのへることあり。</a></div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］前提部の代りに何等かの言ひかへ。</a></div><div class="col-2">369</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］gernと共に。</a></div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2">48-6B</div><div class="col-8">接続法  要求話法</a></div><div class="col-2">390-480</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］願望・祈。（wolle, möge）及び <u>Stoßgebete</u><br><u>Exklamatorisch</u></a></div><div class="col-2">393</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］決心、決定、承認。（wolle, möge）</a></div><div class="col-2">430</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］wünschen, verlangen等を主文とする副文章に。<br>（Esperanto:--u! の語尾）</a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］命令法。</a></div><div class="col-2">440</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］要求を意味する名詞の附加分（其の他、間接）</a></div><div class="col-2">459</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>damit</u>には要求話法。<br>auf <u>daß</u>....及び単にdaß....!</a></div><div class="col-2">459</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］…として置かう。（約束話法の一筋道）<br>筆者のGeschäftzordnung</a></div><div class="col-2">465</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］認容的sei es［auch］</a></div><div class="col-2">476</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］認容的（mag---will）挑みの<br>に第一式を用ひる例</a></div><div class="col-2">477</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］<u>möge</u>（主文と副文）</a></div><div class="col-2">478</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］間接文中の要求話法（daßと目的<br>（必要、規則、鉄則、モットー等の内容）</a></div><div class="col-2">479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］stoßgebet, Fluch, Schwur.</a></div><div class="col-2">480</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］関係文内の要求話法。<u>佛語・ラテン語</u></a></div><div class="col-2">480</div></div>');
document.write('<div class="row"><div class="col-2">48-7B</div><div class="col-8">接続法  時稱  形態一般  ［動］<br>編者注：本袋内は2冊のノート<br>ブックに整理されてある。このため、ノー<br>卜ブックの番号を①、IIとし、各<br>章の番号を、例えば①-［01］等と付け<br>ことにした。</a></div><div class="col-2">481-516</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">①  時稱</a></div><div class="col-2">481-502</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［01］時稱の問題に非ずと雖も、第二式は、よく<br>第二式のmorphologischな欠点を補ふ<br>ために用ひらる。</a></div><div class="col-2">482</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［02］<u>als ob</u>とals<br>（第一、第二両方）</a></div><div class="col-2">491</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［03］第一式が中立的で、第二式が疑いなること<br>の証明となる可き文例。</a></div><div class="col-2">492</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［04］間接話法に、第一式の代りとして好んで<br>第二式を用ひるもの。（意味にかは<br>りなし） -kommen- <u>käme</u></a></div><div class="col-2">494</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［05］問接話法に好んで第二式を用ひる。（独立<br>主文にして同時にvolkstümlich）</a></div><div class="col-2">496</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［06］「好んで云々する」の意には、第二式現在<br>形の代りに第二式過去形を用ひる。Ich<br><u>spräche</u> gern ein Wörtchen mit dir.<br>Ich <u>hätte</u> gern, ein Wörtchen mit dir <u>gesprochen</u>.</a></div><div class="col-2">497</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［07］第二式の時に古くは第一式。</a></div><div class="col-2">501</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［08］過去的主文に對して第一式の問接話法。</a></div><div class="col-2">501</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［09］古き接続法</a></div><div class="col-2">501</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">①-［10］外国語に於ける時稱の一致</a></div><div class="col-2">502</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-形態</a></div><div class="col-2">503-516</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［01］kennte等</a></div><div class="col-2">504</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［02］gölte（stt. gälte）等</a></div><div class="col-2">504</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［03］弱変化のK.IIはとかく過去と誤られやすい：</a></div><div class="col-2">505</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［04］強化第二式は、間接話法に於ては第一式<br>と同じく用ひる。</a></div><div class="col-2">506</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［05］約束法等第二式に弱変化形を。</a></div><div class="col-2">507</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［06］<u>グリム</u>・<u>聖書式</u>時稱の一致<br>dass = auf daß（の場合、殊に多し）</a></div><div class="col-2">509</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［07］佛（約束話法の一種と見られる）</a></div><div class="col-2">513</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">②-［08］現在形（täte）の代りに過去形（hätte<br>getan）を用ひるのは<u>完結相</u>動詞である。</a></div><div class="col-2">516</div></div>');
document.write('<div class="row"><div class="col-2">48-8B</div><div class="col-8">可能法<br>［独（古}佛・羅と同じ可能法的間接話法。<br>sagen,daßは直接法<br>Das Unglück wollte, daß....<br>La malheur voulet que～KII.<br>［仏］可能法を用いる場合  jusqu\'à ce que--K.<br>編者注：このほか20件あり。</a></div><div class="col-2">517-559</div></div>');
document.write('<div class="row"><div class="col-2">48-9R</div><div class="col-8">間接話法表現に関する一般的考察の一つ<br>［羅］Konjunctivusの特徴</a></div><div class="col-2">560</div></div>');
document.write('<div class="row"><div class="col-2">48-10B</div><div class="col-8">Assimilationによって、従属文内まで接続法になる</a></div><div class="col-2">561-562</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">場合。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">48-11R</div><div class="col-8">［佛］独ならば間接話法</a></div><div class="col-2">563</div></div>');
document.write('<div class="row"><div class="col-2">48-12B</div><div class="col-8">接続法  第一式</a></div><div class="col-2">564-566</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］（「疑問文」）</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］als obと第一式</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］alsと第一式</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］認容文 Sei es....、so....</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］何を云々したらよかろうかと（探す）、等<br>（<u>sollen</u>）</a></div><div class="col-2">565</div></div>');
document.write('<div class="row"><div class="col-2">48-13B</div><div class="col-8">羅典文法の接続法（特有なもの）<br>II Kを要求する否定的基礎  geschweige daß....<br><u>nicht daß ich wüßte</u><br>「引用の「人の言」であることを特に利かせたい時<br>の引用文（間接）には特に第二式を用ひる。<br><br>編者注：このほか１６件あり。</a></div><div class="col-2">567-576</div></div>');
document.write('<div class="row"><div class="col-2">48-14B</div><div class="col-8">Es fehlte wenigとK II</a></div><div class="col-2">577-585</div></div>');
document.write('<div class="row"><div class="col-2">48-15B</div><div class="col-8">［MHD］Wer da....等とKIの定形<br>旨・趣・由の表現には接続詞<u>wie</u>をも用ふ：<br>”事の顛末・一伍一什”</a></div><div class="col-2">586-587</div></div>');
document.write('<div class="row"><div class="col-2">48-16B</div><div class="col-8">Oratio directa Oratio obliquaに関する参考事項<br>［英］direct speach. indirect speach.</a></div><div class="col-2">588-597</div></div>');
document.write('<div class="row"><div class="col-2">48-17R</div><div class="col-8">事傳てには第二式を用ふ<br>間接話法：Oratio obliqua中に直接の<u>呼びかけ<br>の二人称</u>を用いる例あり：（初歩根本問題）<br>間接話法に於ける代名詞、副詞等が直説法の場合<br>とちがってくる問題。<br><u>Wer</u> das <u>täte</u>!</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">48-18B</div><div class="col-8">英語に於ける接続の用法雑例［参考］</a></div><div class="col-2">602-603</div></div>');
document.write('<div class="row"><div class="col-2">48-19B</div><div class="col-8">Wer ～！（A）反語<br>（B）願望</a></div><div class="col-2">604-605</div></div>');
document.write('<div class="row"><div class="col-2">48-20B</div><div class="col-8">Wer weinte nicht? 誰か泣かざらん</a></div><div class="col-2">606-607</div></div></div>');