document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">50-1R</div><div class="col-8">命令法の表現－－雑考。  sagen wir（mettons）<br>schiltの代りにschelte!（弱変化に誤れる例）</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">50-2B</div><div class="col-8">命令法 ［動］</a></div><div class="col-2">2-51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］不定法の侭。</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］<u>ihr</u></a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］duの際</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］命令法に主語を特に入れる事<br>（殊に区別するとき）</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］二人称的 er,sieは接続法で。</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］mach, daß du fortkommst!</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］gebeut!</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］sieh zu ob----!</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］seinの命令形 sei! seid!</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］Lehre du mich meine Leute kennen!<br>（おまえなどには教わらないぞ）</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］wirの場合。</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">50-3R</div><div class="col-8">命令文に用いる助辞  1. nur immer- 2. immer heran!<br>命令形の前に目的語其の他を<br>Ach, wie ist\'s möglich dann,<br>Daß ich dich lassen kann,<br>hab dich von Herzen lieb,<br>Das glaube mir! （Treue Liebe）</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2">50-4B</div><div class="col-8">（A）こら、ちょっと待たんか？<br>（B）μη……σηζ等</a></div><div class="col-2">53-56</div></div>');
document.write('<div class="row"><div class="col-2">50-5R</div><div class="col-8">即時実現的命令  daß....直接法！<br>GehとGehe!の問題  "Gehe" statt "Geh"</a></div><div class="col-2">57-59</div></div>');
document.write('<div class="row"><div class="col-2">50-6B</div><div class="col-8">命令法に用ひる助詞  <u>nur</u>, <u>immer</u>, <u>mal</u>, <u>doch</u>,等</a></div><div class="col-2">60-61</div></div>');
document.write('<div class="row"><div class="col-2">50-7R</div><div class="col-8">［MHD］命令法の特にemphatischな語尾＝â<br><u>Sitzen sie</u> nicht da und <u>maulen</u>!.</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2">50-8B</div><div class="col-8">命令文に於いても一文肢を<u>先置</u>することあり。［語順］<br>Von mir, wahrhaftig, erwartet keinen Dank!</a></div><div class="col-2">63-64</div></div>');
document.write('<div class="row"><div class="col-2">50-9R</div><div class="col-8">［形態］werde! stirb und werde!</a></div><div class="col-2">65-67</div></div>');
document.write('<div class="row"><div class="col-2">50-10B</div><div class="col-8">［MHD］ではsollenをハッキリと命令法として用いて<br>いる！<br>［仏］命令法の諸問題  Donne-moiの代りにMe donne<br>命令法 <u>werden</u></a></div><div class="col-2">68-77</div></div>');
document.write('<div class="row"><div class="col-2">50-11R</div><div class="col-8">Hänschen, lauf und säume nicht!<br>省略文一般を用ふ。 keine Sorge! Keine Angst!<br>siehe! 参考<br>方向規定を伴う省略型<br>A cheval, mes amis, à cheval!<br>"On to the prison!"</a></div><div class="col-2">78-79</div></div>');
document.write('<div class="row"><div class="col-2">50-12B</div><div class="col-8">Wirの際。及びLaßt uns等。<br>［希］［羅］ergo bibamus!<br>独の普通例:Gehen wir auf einige<br>Einzelheiten ein.</a></div><div class="col-2">80-83</div></div>');
document.write('<div class="row"><div class="col-2">50-13R</div><div class="col-8">wollenによる表現  wollet（wolltと区別して）<br>会話調：wenn--?<br>従属内に命令文は不可能ということ<br>Halt da! 等<br>普通の構文  直接法で（Peremptorisch）<br>=ein, =ern形の命令法、備考<br>編者注： このほか12件あり。</a></div><div class="col-2">84-94</div></div>');
document.write('<div class="row"><div class="col-2">50-14B</div><div class="col-8">［希］［羅］穏やかな命令法（二人称の場合）</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2">50-15B</div><div class="col-8">要求話法の諸形態。（参考事項）</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2">50-16R</div><div class="col-8">社交儀禮的形式  sind gebeten等<br>命令法の名詞化<br>ob......!<br>命令法形式上の問題。<br>trockne! Widme! Wandre!<br>直接法現在で<br><u>助動詞の命令形</u><br>Hörst auf!（南独の）<br>非人私の命令形  Geschehe, was geschehen kann.<br>Auf Stainen hackt <u>man</u> nicht Holz!  禁止（man）<br>独白に於ける「云々しよう！」は主として二人称<br>で表現す</a></div><div class="col-2">97-100</div></div></div>');