document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0001.html"></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">52-1B</div><div class="col-8"><a href="../052/s0001.html">結果の挙述（Ergebnisangabe）</a></div><div class="col-2">1-36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0002.html">［01］<u>Zu Tode</u>  ［英］to death. He burned to death.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0005.html">［02］形容詞お伴ふもの。</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0017.html">［03］名詞の四格。（Akkusativの項）</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0023.html">［04］形容詞を用ひて新造する。</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0025.html">［05］前綴りを用ひlativischになるもの：</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0025.html">［06］<u>signer sa ruine</u></a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0026.html">［07］<u>Es</u> regnet Dukaten等</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0026.html">［08］文章関係では：</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0027.html">［09］名詞の四格（その場で造るもの）<u>machen</u></a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0030.html">［10］setzte dem <u>überraschten</u> Gatten noch einige<br>Kartoffeln vor.<u>附加語形容詞</u><br>述語句的なものも。</a></div><div class="col-2">30<div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0036.html">［11］必ずしも形容詞、名詞の四格のみに非ず。</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2">52-2B</div><div class="col-8"><a href="../052/s037-.html">搬動語法と方向の概念  bringenの形態［動］</a></div><div class="col-2">37-97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0038.html">［01］前綴の方向指示（結果挙述に属すべきもの多し）</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0045.html">［02］（再帰動詞化したもの）</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0060.html">［03］前置詞句（成句的）</a></div><div class="col-2">6052div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0074.html">［04］”招き寄せる”等の単純なもの：</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0077.html">［05］状況言的規定。</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0089.html">［06］Er half <u>mir</u> aus dem Wagen.（三格）</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0094.html">［07］Verschwommene latiriche Erfindungen.<br>編者注：上記文の一部は綴りが不明。</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../052/s0097.html">［08］意味としては「結果挙述」に属せしむ可き場合<br>あり。 Sich zum Tiere durchtrinken.</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2">52-3R</div><div class="col-8"><a href="../052/s098-.html">bringen型とmachen型との区別のつかぬもの<br>....aus dem Boden <u>stamphen</u>.<br>LATIVA的なるもの<br><u>bringen</u>型なることの説明<br>ドイツ特有の運動形態----参考<br>bekommen（get）型<br>英独共通のLATIVISCHな考え方に関する一般考察</a></div><div class="col-2">98-10052div></div>');
document.write('<div class="row"><div class="col-2">52-4B</div><div class="col-8"><a href="../052/s0101.html">英のLativa  intoによるもの<br>to lash oneself into a furry（or rage）</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">52-5B</div><div class="col-8"><a href="../052/s0102.html">結果挙述の四格［一般例］</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2">52-6B</div><div class="col-8"><a href="../052/s0103.html">machen形動詞  成句熟語的</a></div><div class="col-2">103-104</div></div>');
document.write('<div class="row"><div class="col-2">52-7B</div><div class="col-8"><a href="../052/s0105.html">再帰動詞と結果詞。</a></div><div class="col-2">105</div></div></div>');
