document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">52-1B</div><div class="col-8">結果の挙述（Ergebnisangabe）</div><div class="col-2">1-36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>Zu Tode</u>  ［英］to death. He burned to death.</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］形容詞お伴ふもの。</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］名詞の四格。（Akkusativの項）</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］形容詞を用ひて新造する。</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］前綴りを用ひlativischになるもの：</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>signer sa ruine</u></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］<u>Es</u> regnet Dukaten等</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］文章関係では：</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］名詞の四格（その場で造るもの）<u>machen</u></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］setzte dem <u>überraschten</u> Gatten noch einige<br>Kartoffeln vor.<u>附加語形容詞</u><br>述語句的なものも。</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］必ずしも形容詞、名詞の四格のみに非ず。</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2">52-2B</div><div class="col-8">搬動語法と方向の概念  bringenの形態［動］</div><div class="col-2">37-97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］前綴の方向指示（結果挙述に属すべきもの多し）</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］（再帰動詞化したもの）</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］前置詞句（成句的）</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］”招き寄せる”等の単純なもの：</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］状況言的規定。</div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］Er half <u>mir</u> aus dem Wagen.（三格）</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］Verschwommene latiriche Erfindungen.<br>編者注：上記文の一部は綴りが不明。</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］意味としては「結果挙述」に属せしむ可き場合<br>あり。 Sich zum Tiere durchtrinken.</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2">52-3R</div><div class="col-8">bringen型とmachen型との区別のつかぬもの<br>....aus dem Boden <u>stamphen</u>.<br>LATIVA的なるもの<br><u>bringen</u>型なることの説明<br>ドイツ特有の運動形態----参考<br>bekommen（get）型<br>英独共通のLATIVISCHな考え方に関する一般考察</div><div class="col-2">98-100</div></div>');
document.write('<div class="row"><div class="col-2">52-4B</div><div class="col-8">英のLativa  intoによるもの<br>to lash oneself into a furry（or rage）</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">52-5B</div><div class="col-8">結果挙述の四格［一般例］</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2">52-6B</div><div class="col-8">machen形動詞  成句熟語的</div><div class="col-2">103-104</div></div>');
document.write('<div class="row"><div class="col-2">52-7B</div><div class="col-8">再帰動詞と結果詞。</div><div class="col-2">105</div></div></div>');