document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">55-1B</div><div class="col-8"><a href="../055/s0001.html">附加語 文肢［1］adnominalとadverbal</a></div><div class="col-2">1-44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0003.html">［01］Apposition的用法の附加語（alle, anderes）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0028.html">［02］副詞規定が附加語として用ひられる。</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0028.html">［03］文肢から附加語への移り変り。</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0029.html">［04］文肢か附加語かわからぬ場合。</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0029.html">［05］形容詞「句」を後置することあり。（仏語）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0030.html">［06］附加語を文肢と誤解した際のAnsinn<br>（及びumgekehrt.）</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0031.html">［07］挿入的文肢を附加語と解すべからず。<br>（コンマの省略）</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0031.html">［08］冠詞と名詞との間が長くなる場合。</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0032.html">［09］als ob....等の附加語。（wennも）（daß）</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0033.html">［10］副詞句（二語以上）の附加語。</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0034.html">［11］後置する述語的附加語</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0034.html">［12］前置詞を伴うadnominal句の位置に関する考察：</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0043.html">［13］前置詞を介せず、Casus obliquiによって<br>adnominaliaを作ることは、独では不可、<br>他語には例がある；（三格と四格）</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0044.html">［14］邦語の問題</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2">55-2R</div><div class="col-8"><a href="../055/s0045.html">構造上から来る。  ［代名詞］主語省略（意味ある<br>主語を省く）</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2">55-3B</div><div class="col-8"><a href="../055/s0046.html">主語  文肢</a></div><div class="col-2">46-130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0048.html">［01］述語の主語化。</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0061.html">［02］中性、女性複数に於ては、主語に注意。（前が<br>四格）</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0063.html">［03］主語の強調（述語を後に、主語を先に）</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0065.html">［04］追加的主語</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0067.html">［05］名詞、代名詞以外の主語（名詞化）</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0070.html">［06］主語の移推。（voll, voller等）（wimmelt von<br>等も）</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0075.html">［07］主語の移推。（人の代りに物）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0081.html">［08］<u>Sachliches Subjekt</u> u. <u>Persöhnliches Objekt</u>.</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0115.html">［09］物稱動詞（schmecken, jucken）</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0118.html">［10］主語の移推。</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0119.html">［11］主語の省略（一息に云ふ。呪詛罵言）Hybris.</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0124.html">［12］主語省略（手紙、日記等の）geschätlich.</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0127.html">［13］<u>主語の省略</u>  （<u>独語的、beiseite für sich</u>）</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0130.html">［14］心<u>の中が</u>等［非人称主語］</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2">55-4B</div><div class="col-8"><a href="../055/s0131.html">状況言  文肢</a></div><div class="col-2">131-155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0132.html">［01］方向規定（1）語順</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0136.html">［02］描写的述語。（Kommaを打つ、重畳をいとはず、<br>挿入句的、芸術的）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0137.html">［03］位置規定（語順）</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0143.html">［04］場所規定が主語の位置を指すか目的語の位置を<br>指すか？</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0145.html">［05］追加詞を伴ふ前置詞の述語。</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0146.html">［06］動作の方向位置規定には、「人」が先で、「所」<br>が後。</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0148.html">［07］語順参考。</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0148.html">［08］…の中を探す、等</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0149.html">［09］Wie kam er <u>hier</u> <u>herein</u>?</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0153.html">［10］コンマなく、独式：</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0154.html">［11］<u>heute</u> nach dem abend Essen.</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2">55-5B</div><div class="col-8"><a href="../055/s0156.html">規定（限定）  Deteminans--Deteminatum</a></div><div class="col-2">156-164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0157.html">［01］副詞が名詞、代名詞等の規定となる。<br>（基の乗りかへ）（文肢が附加語となる経過）</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0158.html">［02］制限的規定（限定）</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0159.html">［03］「時間関係なき」結合的規定（修飾）</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0160.html">［04］時間関係ある結合的規定。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0160.html">［05］限定か修飾かで意味に大変化を来たす例。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0160.html">［06］限定関係の混乱推移変改。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0161.html">［07］hier, dort, da等の名詞を規定する例。</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0162.html">［08］<u>um</u>等の結果を指す場合。</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0162.html">［09］0hneが結果を指す時。（könnenの用法の一）</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0163.html">［10］文法的規定関係のはきちがヘ。［形の問題］</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0164.html">［11］Schnellzug <u>Berlin=Rom</u>.</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0164.html">［12］「規定」とも「言ひ換え」とも取れる場合、<br>Der Grund, warumなど<br>Art und Weise, wie....等</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2">55-6B</div><div class="col-8"><a href="../055/s0165.html">形式的分解  文肢の切り方</a></div><div class="col-2">165-169</div></div>');
document.write('<div class="row"><div class="col-2">55-7R</div><div class="col-8"><a href="../055/s0170.html">程度規定の状況言  einwenig, etwas, ganz,<br>主語文肢とその附加物<br>Beides ist unlogisch. Aber <u>welche Art Unlogik</u><br><u>wohl</u> ist die anständigere?</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2">55-8B</div><div class="col-8"><a href="../055/s0171.html">状況言の分類</a></div><div class="col-2">171-172</div></div>');
document.write('<div class="row"><div class="col-2">55-9B</div><div class="col-8"><a href="../055/s0173.html">AdnominalとAdverbal.</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2">55-10B</div><div class="col-8"><a href="../055/s0174.html">名詞附加句と名詞の前に</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0174.html"><u>In seinen Amen</u> <u>das Kind</u> war tot.</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">55-11B</div><div class="col-8"><a href="../055/s0175.html">［附加語］［2］  前置詞附加詞：über, an, auf, zu, in.<br>Principatus Galliae.:<br>0berherrschaft <u>über</u> Gallien.<br>copia frumenti:<br>Vorrat <u>an</u> Getreide.</a></div><div class="col-2">175-176</div></div>');
document.write('<div class="row"><div class="col-2">55-12B</div><div class="col-8"><a href="../055/s0177.html">定形補足  文肢<br>［01］定形と密接なる関係にある副詞（規定）は後置す<br></a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">55-13R</div><div class="col-8"><a href="../055/s0178.html">規定関係の移動<br>従属文は、本文の定形を規定する場合のみではなく、<br>特に<u>一文肢</u>を規定する場合がある。<br>古典（伊太利等）は、代名詞主語を省く。</a></div><div class="col-2">178-179</div></div>');
document.write('<div class="row"><div class="col-2">55-14B</div><div class="col-8"><a href="../055/s0180.html">純形式的誤読</a></div><div class="col-2">180-186</div></div>');
document.write('<div class="row"><div class="col-2">55-15B</div><div class="col-8"><a href="../055/s0187.html">文肢</a></div><div class="col-2">187-194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0187.html">［01］長い文肢</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0189.html">［02］二つの文肢か一つの文肢か？</a></div><div class="col-2">189~</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0191.html">［03］ニ文肢を一つによむ誤</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0191.html">［04］Modell=Sätze:</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0191.html">［05］ニ文肢の習憤的結合。 <u>Hinaus</u> <u>in die Natur</u> 等</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0193.html">［06］定形二個以上：</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0193.html">［07］長い文肢と、その切り所。</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0193.html">［08］1.文のSubstantivierung   の内部に於ける文肢機<br>2.冠飾句    構の研究も重要なり。</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../055/s0194.html">［09］der（女性二格か三格か）等の格の問題が這入って<br>来る文肢切り方の問題</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2">55-16B</div><div class="col-8"><a href="../055/s0195.html">物称形容詞と人称形容詞との混同：<br>Ich bin langweilig.</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2">55-17B</div><div class="col-8"><a href="../055/s0196.html">日本語傾向の規定順と近世西洋語の逆順</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2">55-18B</div><div class="col-8"><a href="../055/s0197.html">主語の見分け方に関する注意。（殊に述語との関係）</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">55-19B</div><div class="col-8"><a href="../055/s0198.html"><u>状況規定の例外的場合</u></a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2">55-20B</div><div class="col-8"><a href="../055/s0199.html">主格圏的と封格圏的<br>sich <u>als</u> ～ 動詞  格がAKKかN0Mかの問題。</a></div><div class="col-2">199-200</div></div>');
document.write('<div class="row"><div class="col-2">55-21B</div><div class="col-8"><a href="../055/s0201.html">文章を附加語に</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2">55-22R</div><div class="col-8"><a href="../055/s0202.html">文肢  文肢が動詞と結合して成句をなす際の<br>諸種の形態  熟語動詞<br>［01］前置詞を伴ふ名詞。<br>［02］不定法（kennen lernen,etc.）<br>［03］前置詞が次の名詞、形容詞等と一語をなすもの。<br>［04］名詞のみを伴ふもの。<br>［05］形容詞<u>附加語</u>をつけてはならぬ事。</a></div><div class="col-2">202-205</div></div></div>');