document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">54-1B</div><div class="col-8"><a href="../054/s0001.html">錯倒語法（Hypallage）</a></div><div class="col-2">1-37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0002.html">［01］故意のHypallage</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0003.html">［02］副詞の代りに形容訶（adverbal → adnominal）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0004.html">［03］Gesprungener  Huf</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0016.html">［04］sogenannt等。 would = be, going to = be</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0036.html">［05］ラテンの<u>Gerundivum</u>の用法</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0036.html">［06］Enàllage adiectivi</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0037.html">［07］部分と総体の倒錯  die <u>innere</u> Stadt.</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2">54-2B</div><div class="col-8"><a href="../054/s0038.html">移轍  形式上の錯構  主文章への移轍一般論<br>（Anakoluth）  Kontamination</a></div><div class="col-2">38-90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0042.html">［01］wenn, wie</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0057.html">［02］Keen Post so scheef, past doch \'n Deckl up.</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0076.html">［03］雑例。</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0078.html">［04］受働形に似たる文にdurch, von.</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0078.html">［05］其他の筋道に属する雑例。</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0080.html">［06］疑問文とals...</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0084.html">［07］darum doch等は  A. darum <u>nicht weniger</u><br>［n\'en est pas moins］<br>B. ....<u>doch</u>....</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0085.html">［08］Was---? so---</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0085.html">［09］二度目であるために、意味だけでつながるもの。<br>（意味形態の類似のために文法形態の<br>相違を無視す）</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0086.html">［10］［英］</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0087.html">［11］全く誤なるもの。</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0089.html">［12］述語句の有名な問題</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0089.html">［13］nicht....<u>sondern</u>....</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2">54-3B</div><div class="col-8"><a href="../054/s0091.html">二度目には用語を変える</a></div><div class="col-2">91-111</div></div>');
document.write('<div class="row"><div class="col-2">54-4B</div><div class="col-8"><a href="../054/s0112.html">暗喩  -zitate- （Anspielung）</a></div><div class="col-2">112-130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0113.html">［01］Tatsächlich （mit Benennung.）</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0120.html">［02］Vorbei=spielung  côtoyer.</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0124.html">［03］Phrasenfrgmente  <u>Zitate</u>.</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0130.html">［04］Populäre Vorstellungen.</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2">54-5B</div><div class="col-8"><a href="../054/s0131.html">戯作的換語  Das kommt gar nicht <u>in die tüte</u>!</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2">54-6B</div><div class="col-8"><a href="../054/s0132.html">擬音 Schallwort （Onomatopöce）</a></div><div class="col-2">132-182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0133.html">［01］fl-</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0156.html">［0Z］schn=</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0156.html">［03］schm=</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0156.html">［04］［仏］名詞的 brouhaha f1onflon</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0157.html">［05］schw.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0157.html">［06］kn= 編者注：文例無し。</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0157.html">［07］<u>Schl</u></a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0157.html">［08］kl=</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0157.html">［09］gr=</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0158.html">［10］klipp = klapp型  Schnickschnack, krimskrams,<br>Bimbam, Singsang.</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0169.html">［11］stripp, strapp, stroll型  Piff paff <u>puff</u>!<br>（Rooly toot Tourの訳として）</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0170.html">［12］Schurlemurle型［韻］</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0171.html">［13］動詞の部  zirpen, kracken</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0181.html">［14］使用動詞  <u>machte</u> miau! <u>ging</u> klipp klapp</a></div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0182.html">［15］<u>R</u>--</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0182.html">［16］Klapps. Glucks/</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2">54-7B</div><div class="col-8"><a href="../054/s0183.html">弱語強想 （Liotes）</a></div><div class="col-2">183-217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0184.html">［01］否定を伴ふもの。必ずしも（nicht immer）</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0206.html">［02］弱語強想には非ずして単に否定的語法なるもの</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0207.html">［03］特に<u>nicht zuletzt</u>について。</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0209.html">［04］［英］は説明的に完全：last, <u>but not least</u></a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0214.html">［05］nicht <u>der geringste</u>等</a></div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0215.html">［06］弱い、遠慮した、時として皮肉な段階（<u>nicht</u>,<br>gerade, eben等を伴ふを特徴とす。）</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0217.html">［07］否定を用ひる代りに故意と他の何等かの<br>Periphraseを用ふ：</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0217.html">［08］Diminutivと関係して、</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2">54-8B</div><div class="col-8"><a href="../054/s0218.html">Euphemismus其の他 ［猥］DAS HAUFCHEN.<br>糞、Zotenreißerei,<br>最も本格的・古典的なEuphemismus<br>Periphrase  Euphemismus等</a></div><div class="col-2">218-258</div></div>');
document.write('<div class="row"><div class="col-2">54-9B</div><div class="col-8"><a href="../054/s0259.html">異名  Adebar, Isegrim, Nobel, Reineke.<br>Meister Petz<br>換語 Pheriphrase単句  述語としての換語<br>（述語）<br>Das Reich der aufgehenden Sonne.<br>was lange Haare trägt.  Schürzen</a></div><div class="col-2">259-268</div></div>');
document.write('<div class="row"><div class="col-2">54-10B</div><div class="col-8"><a href="../054/s0269.html">hören und vernehmen<br>数語にて修辞効果（殊に古体）</a></div><div class="col-2">269-270</div></div>');
document.write('<div class="row"><div class="col-2">54-11B</div><div class="col-8"><a href="../054/s0271.html">誇張語法  Die Hyperbel</a></div><div class="col-2">271-279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0272.html">［01］Die Bescheidenheit selbst, etc.</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0272.html">［02］</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0273.html">［03］<u>Übertreibung</u></a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0278.html">［04］齟齬、不可能、</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0279.html">［05］成句化したもの。</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2">54-12B</div><div class="col-8"><a href="../054/s0280.html">Launenhafte Bezeichnung 貶詞と一致す。<br>［A］der Personen  FANT, GESLELE<br>［B］der Sachen</a></div><div class="col-2">280-293</div></div>');
document.write('<div class="row"><div class="col-2">54-13B</div><div class="col-8"><a href="../054/s0294.html">肉体諸部の装飾的状況言</a></div><div class="col-2">294-301</div></div>');
document.write('<div class="row"><div class="col-2">54-14B</div><div class="col-8"><a href="../054/s0302.html">人のMetonymie  Pars pro toto 一般</a></div><div class="col-2">302-318</div></div>');
document.write('<div class="row"><div class="col-2">54-15B</div><div class="col-8"><a href="../054/s0319.html">意の重点<br></a></div><div class="col-2">319-343</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0322.html">［01］<u>Sperrschrift</u>. <u>Gesperrt</u></a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0328.html">［02］Sperrschriftにはせずとも、</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0329.html">［03］Antithese</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0331.html">［04］約束法的語法、最後に来る仮構の部に意の重点<br>を置く。</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0331.html">［05］比較文と意の重点（廣汎な筋道）</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0332.html">［06］註釋用の考察（限定の問題）</a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0333.html">［07］（否定の際の）定形強調  肯定も然り。</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0338.html">［08］<u>It</u> is not you <u>that</u> have a right to complain!</a></div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0338.html">［09］一文肢（主語を含めて）強調手段は、仏と比較<br>せよ</a></div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0339.html">［10］doの用法</a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0343.html">［11］Ich sage.</a></div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0343.html">［12］助動詞の繰返し</a></div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2">54-16B</div><div class="col-8"><a href="../054/s0344.html">PLE0NASMUS  もう一度くりかえして申し上げます。<br>je le répète encore une fois....</a></div><div class="col-2">344-348</div></div>');
document.write('<div class="row"><div class="col-2">54-17B</div><div class="col-8"><a href="../054/s0349.html">Europäische Verdrehtheit</a></div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">54-18R</div><div class="col-8"><a href="../054/s0349.html">ナンセンス的延長<br>換語［露骨を避ける為］  隠語（verhüllend）</a></div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">54-19B</div><div class="col-8"><a href="../054/s0357.html">Volksetymologie</a></div><div class="col-2">357-358</div></div>');
document.write('<div class="row"><div class="col-2">54-20R</div><div class="col-8"><a href="../054/s0359.html">Antithesis<br>Oxymoron  Er schweigt in drei Sprachen.<br>Anthropomorphismus.</a></div><div class="col-2">359-360</div></div>');
document.write('<div class="row"><div class="col-2">54-21B</div><div class="col-8"><a href="../054/s0361.html"><u>Metapher</u>は一貫すべし</a></div><div class="col-2">361-364</div></div>');
document.write('<div class="row"><div class="col-2">54-22R</div><div class="col-8"><a href="../054/s0365.html">Rokoko式（Periphrase）<br><u>Oxymoron</u>  glänzendes Elend.<br>METONYMIE  <u>材料を以て</u><br>MET0NYMIE  ceut voiles（vaisseaux）<br>冗談は論理に合はなくてもよい</a></div><div class="col-2">365-368</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0365.html"><u>sprachdummheiten</u><br>［仏］十七世紀の宮廷時代<br>Vous avez pris jour pour un <u>lien si doux</u>.<br>（mariage）</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">54-23B</div><div class="col-8"><a href="../054/s0369.html">雅語  古語  詩語</a></div><div class="col-2">369-371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0369.html">［01］Eidam,（schwingersohn.） Ohm（0heim）</a></div><div class="col-2">369</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0370.html">［02］文例</a></div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0370.html">［03］Urständ,f. Auferstehung.<br>Urstätt,f</a></div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0371.html">［04］古語を滑稽に用ふ  erschröcklich gelahrt.<br>Gottesgelahrtheit.</a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../054/s0371.html">［05］固有名詞の換語<br>1. London（für englische Regierung）<br>2.人名</a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2">54-24R</div><div class="col-8"><a href="../054/s0372.html">抽象名詞を人に → Metonymie<br>［仏］qui était une célébrité.</a></div><div class="col-2">372</div></div>');
document.write('<div class="row"><div class="col-2">54-25B</div><div class="col-8"><a href="../054/s0373.html">同語の反覆使用<br>副詞反覆<br>定形反覆<br>形容詞</a></div><div class="col-2">373-374</div></div>');
document.write('<div class="row"><div class="col-2">54-26R</div><div class="col-8"><a href="../054/s0375.html">Metonymie  <u>換語</u><br>Deutsche Langatmigkeit<br>雅語<br>誇張的比喩  Venedig diese versteinerte<br><u>Geschichte</u>.<br>既存の語形を避けて（意味の区別のため）形を<br>変へて行かうとする傾向</a></div><div class="col-2">375-376</div></div>');
document.write('<div class="row"><div class="col-2">54-27B</div><div class="col-8"><a href="../054/s0377.html">別意</a></div><div class="col-2">377-378</div></div>');
document.write('<div class="row"><div class="col-2">54-28R</div><div class="col-8"><a href="../054/s0379.html"><u>Hyperbel</u>.<br>具体的、象徴的語法。<br><u>Repetitio</u>,（定形の反覆は、「度々」の強調。）<br>（その他）<br><u>J.P.Richterの拙いMetapher</u>.<br>MET0NYMIE  具体物の代りに抽象名詞。（それ自身<br>の如し）<br>［型］Herbst=Ernte（Metonymie）<br>Bildersprache  拍車を掛ける。<br>折紙をつけられる  頬かぶりして世を渡る<br><u>Alliteration</u><br>Metonymie（似た物）</a></div><div class="col-2">379-382</div></div></div>');