document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">56-1B</div><div class="col-8">因由型  因由範疇  理由、原因の形態。</div><div class="col-2">43492</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］文肢（als）</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］句（過去分詞叙述句）及形容詞</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］句、文肢（現在分詞）</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］文章（関係代名詞）</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］一般に前置詞の句（bei）</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］jung und fröhlig, wie Ich war.  so.... もあり</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］付帯描写のmit.</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］<u>ja</u></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］<u>und so</u>.</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］［und］=darum</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］単に並べたのみで.  ～［denn］～</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">56-2B</div><div class="col-8">相反的意味範疇  強い<u>und</u><br>［羅］idem, eademによる対立表現</div><div class="col-2">28-42</div></div>');
document.write('<div class="row"><div class="col-2">56-3B</div><div class="col-8">Kaum....als</div><div class="col-2">43-66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］Kaum....als....</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Kaum....so［da］....</div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Nicht so bald.... als....<br>Nicht eher....als....</div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］Gedacht, getan.</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］Denken und handeln war eins.</div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］....und（so）....</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］Noch gar nicht lange, <u>da</u></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］Kaum daß....</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］kaumを従属的接続詞に、</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］遂にはkaumの代りにkein....と全然否定になる</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］noch nicht...., als....</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］<u>Kaum gedacht</u>, （省略文）<br>war ～</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2">56-4B</div><div class="col-8">aliud....aliud</div><div class="col-2">67-83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］ein anderes....ein anderes</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］etwas anderes....etwas anderes</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］sein以外の場合。</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］anders...anders.<br>das andere....das andere....</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］其他</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>Eines</u> und <u>ein Anderes</u>.</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2">56-5B</div><div class="col-8">局部の<u>仮定強調</u>  或ひは制限強調  仮定と制限</div><div class="col-2">84-103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］um....zu....「もしも」</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］副詞現完（状況言）前置詞句</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］形容詞（大抵は先置）副詞旬</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］分詞句</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］成句化した過去分詞</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>Ende gut</u>, alles gut.</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］allein</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］副文章又は不定句の先置。</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］仮定強調副詞 ”…には”</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］Klopfet an, <u>und</u> es wird euch geöffnet.</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">56-6R</div><div class="col-8">名詞のみで（述語的）（但し、因由形態をも含む）<br>構文のみで<br>形容詞の選び方で。<br>Well fed, well bred型（衣食足って栄辱を知る）<br><u>現在分詞で</u>  en ～ ant.<br><u>主語</u>（特に仮定強調）</div><div class="col-2">104-106</div></div>');
document.write('<div class="row"><div class="col-2">56-7B</div><div class="col-8"><u>仮定文章</u></div><div class="col-2">107-130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］wenn.</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Inversion</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］wennの次の第二定形の正置</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］副文章の正置。</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］意味（Kontrast=wenn）</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］Entweder....oder....の特殊構造</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］nur....wenn....［nur dann....wenn］<br>erst....  erst....</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］Wenig fehlte, <u>so</u>....  <u>und</u></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］oder.  …でなければ<br>（müßte）<u>Jetzt oder nie</u>.  <u>sonst</u></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］Ich brauche...., so....</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］命令形、或ひはそれと類似のものを仮定部へ。<br><u>とund</u>（要求話法K）</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］<u>indem</u>その他<u>手段</u>的表現</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］indemが純粋に時の一致によって「…と」<br>ととなる。（soと共に）（indemが凡ゆる<br>形態に使へることの証拠と見る可し）</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2">56-8B</div><div class="col-8"><u>Es sei denn</u>  Es <u>wäre</u> denn.</div><div class="col-2">131-163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］普通のes sei denn［daß］</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Sie hätten ihn denn vor.</div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］es sei nun, daß</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］es müßte denn sein, daß....</div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］aus genommen, außer.</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］es sei denn等をohne daß....の意に用ひる<br>場合（反語）</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］es <u>wäre</u> denn</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］es müßte denn --- sein.</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］dennゃmüssenの説明用</div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］wenn nicht....で</div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］約束話法か要求話法か？</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］ne....que....で</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］［英］<u>short</u> <u>of</u> ～</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］［外国語］bis aufと同</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2">56-9B</div><div class="col-8">文肢  目的文章</div><div class="col-2">164-173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>auf daß</u>（接続法）</div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］damit（接続法と直接法）</div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］sollenで</div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］不定法を伴ふ諸形式 ［仏］à l\'effet de ～<br>afin de ～ ［英］in order to</div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］関係代名詞でFinalsatzを（羅・希）</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>ubi</u> ea poneretそれらを置く<u>可き</u>場所</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］未来分詞で目的表現</div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］前置詞其他</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2">56-10B</div><div class="col-8">副文章問題一括</div><div class="col-2">174-196</div></div>');
document.write('<div class="row"><div class="col-2">56-11B</div><div class="col-8">日本語にしかない文章形態<br>云々し<u>てまで</u>云々しようとは思わない。</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">56-12B</div><div class="col-8">文法範疇の不明  On annonça le dîner servi.</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2">56-13R</div><div class="col-8">文章の基本問題 <u>aussage</u><br>vielleicht, daß<br><u>附加語による方法</u><br>Apposition自由一括<br><u>denn</u>の挿入文と同じ<u>und</u><br>Das macht, ----!<br>文肢：<u>色々な前置詞句</u><br>Nomen actionisの句。</div><div class="col-2">199-202</div></div>');
document.write('<div class="row"><div class="col-2">56-14B</div><div class="col-8">二個のNexusの結合法の諸段階に関する参考事項</div><div class="col-2">203-204</div></div>');
document.write('<div class="row"><div class="col-2">56-15R</div><div class="col-8">結果の表現（A）<br>因由：同語対立。<br>すべてを因由形態で結びつけんとする傾向から来た<br>Unsinn.</div><div class="col-2">205-206</div></div>');
document.write('<div class="row"><div class="col-2">56-16B</div><div class="col-8">並立的意味範疇 <u>und zwar</u> mit, nämlich, das heißt.</div><div class="col-2">207-210</div></div></div>');