document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">60-1B</div><div class="col-8"><a href="../060/s0001.html"><u>連語ノート</u> （執筆用）<br>Blut und Boden  血縁と環境<br><br>編者注：本袋の資料はノートブック型に<br>なってはいないが、内容が多いので、<br>資料番号にしたがって目次を作るこ<br>とにした。<br><br></a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0002.html">（1）分解列挙と定形の数（主語が前に）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0003.html">（2）連語を単に扱う（抽象概含）<br>どうしても複数としか考えられぬ場合<br>Nach Kant sind <u>Raum und Zeit</u> Formen<br>der Erscheinungswelt.</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0003.html">（3）大勢の人間を考える  A1t und jung</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0004.html">（4）連語を単に扱う（抽象概念）<br>Ihm verging <u>Hören und Sehen</u>.<br>（dass ihm Hören und Sehen verging）</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0006.html">（5）連語を単に扱う（具体名詞）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0008.html">（6）zwischenと無冠詞</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0013.html">（7）rot <u>u</u>. gelbe  romantisch=sentimentale</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0015.html">（8）Wärme u. Kälte</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0017.html">（9）伸び縮み  寝起き  出来不出来  敵味方</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0030.html">（10）連語を関係代名詞で受ける際<br>近きに合せたか、それとも一括したか<br>Verlassen hab ich <u>Feld und Auen</u>.,<br>Die eine tiefe Nacht bedeckt.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0030.html">（11）［再録］一格・四格で必ず定冠詞を要する場合</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0031.html">（12）妙な区別  積極的－消極的  陽－陰  本－副</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0032.html">（13）反意語の対立  Freund und Feind<br>Himmel und Hölle  Gott und Teufel</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0034.html">（14）複数名詞  Knaben und Mädchen</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0035.html">（15）Zeit u. Ort</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0037.html">（16）同意語の対立  Zeit und Weile</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0039.html">（17）一語の場合</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0039.html">（18）Distiguo!</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0040.html">（19）連語の意味上の契機  区別せず、無差別<br>～も～も、  大して区別せぬとさ。</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0041.html">（20）Gegensatzt  Freund u. Feind</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0043.html">（21）単数名詞と複数名詞とを混用す<br>An Wasser, Feuer, Felsenwänden,<br>An <u>Tier und Vögeln</u> fehlt es nicht.</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0043.html">（22）halb:Die Meerweiber sind halb Mensch,<br>halb Fisch.</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">60-2B</div><div class="col-8"><a href="../060/s0045.html">頭韻を伴ふ二語一想  ［Alliteration］<br><br>編者注：本袋の資料はノートブック型に<br>なってはいないが、内容が多いので、<br>資料番号にしたがって目次を作るこ<br>とにした。</a></div><div class="col-2">45-87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0046.html">（1）</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0048.html">（2）mit Haut und Haar  Wohl und Wehe</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0056.html">（3）los und ledig Lust und Liebe</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0057.html">（4）tossed and tumbled   from stem to stern</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0062.html">（5）［仏］sain et sauf.</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0063.html">（6）羅典語の頭韻  virgis ac vimine</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0064.html">（7）文例  句をなす對語のanrein<br>Every bullet has his billet.</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0065.html">（8）［英］spick and span （brand-new）</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0065.html">（9）Sauf oder lauf!</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0071.html">（10）日本語   味噌も糞も一緒くた。<br>愛想もこそも盡きた。</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0072.html">（11）脚音員の聯語  Schutz und Trutz.</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0078.html">（12）toll und voll   ［英］<u>Might</u> is <u>right</u>.</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0080.html">（13）［仏］韻  prestes et lestes.</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0080.html">（14）句。\'  Schutz und Schirm</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0081.html">（15）韻の對を極端に弄んだ奇例：</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0081.html">（16）頭韻のいたずら。</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0082.html">（17）不完全な頭韻</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0081.html">（18）影も形も見えぬ   贔屓の引き到し</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0085.html">（19）頭音（au reim）を利用した詩の表現</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0085.html">（20）Stock uund Stein  参考</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0086.html">（21）不完全なる頭音  kurz und klar</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0087.html">（22）文をなすもの  Wahr ist Qual.</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2">60-3B</div><div class="col-8"><a href="../060/s0088.html">二語一想  （Hendiadyoin）</a></div><div class="col-2">88-114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0089.html">［01］単数として扱ふ証明（形合詞変化）</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0095.html">［02］Improvisierte Formen. （定形に注意）</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0101.html">［03］ニ格、三格の際には冠詞を附す。</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0103.html">［04］冠詞の省略  SandersのいはゆるSonderung.</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0103.html">［05］定形を複数にする例。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0104.html">［06］普通の例（文例）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0106.html">［07］成句の例  Schloß und Ringel</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0107.html">［08］聯句癖について。（二語づつ）</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0114.html">［09］聯句は（前置詞）<u>Flexionslos</u>.</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../060/s0114.html">［10］<u>形容詞</u>の聯語と、その<u>変化</u>。</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2">60-4R</div><div class="col-8"><a href="../060/s0115.html">聯語の第二語につく形容詞の変化。<br>［二格］男性と中性との好都合。<br>三格  女性とpl.</a></div><div class="col-2">115-116</div></div>');
document.write('<div class="row"><div class="col-2">60-5B</div><div class="col-8"><a href="../060/s0117.html">性数を近い方に合せる   附加語（冠詞類）</a></div><div class="col-2">117-122</div></div>');
document.write('<div class="row"><div class="col-2">60-6R</div><div class="col-8"><a href="../060/s0123.html">聯語とNennfall  殊にvonと<br>Seebär gegen Eisbär<br>Käpten Kork bindet uns einen E1sbären auf!<br>規定句（冠詞頬）を繰返す例。<br>（殊に聯「想」なき聯語は然り）<br>性のちかふ聯語と附加語形容詞（冠詞類の繰返し）<br>聯語と定形の数［単］<br>聯語の数（定形）［複数］<br>Sunufetarungo型</a></div><div class="col-2">123-128</div></div>');
document.write('<div class="row"><div class="col-2">60-7B</div><div class="col-8"><a href="../060/s0129.html">Barock流の同義語重畳（主として動詞同義語の重畳）<br>bombastischer Stil<br>強めるために聯語を用いる一般心理<br>（多少公式的、調子をあげる常套句）</a></div><div class="col-2">129-131</div></div>');
document.write('<div class="row"><div class="col-2">60-8R</div><div class="col-8"><a href="../060/s0132.html">［特］全然無意味なること明瞭な聯語<br><u>自由結合</u><br>聯語の特長  plの代りに単数名詞を<br>聯語の意味（単数形を以て複数概念を表現する）<br>語呂合せ Isologie<br>Grim und Gram  Scheuel und Greuel<br>日本語MEM0  重要を「重且つ要なり」なとといふ<br>こと。<br>聯語とApokopierung<br>［佛］佛の無冠詞聯語  Bêtes et gens<br>聯語の無冠詞と外国語<br><br>編者注：このほか8件あり。</a></div><div class="col-2">132-139</div></div>');
document.write('<div class="row"><div class="col-2">60-9B</div><div class="col-8"><a href="../060/s0140.html">真の二語一想  Hendiadys</a></div><div class="col-2">140-143</div></div></div>');