document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</a></div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">70-1R</div><div class="col-8">auf</a></div><div class="col-2">1-61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）線上のauf</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）auf <u>der</u> Stelle</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）所属疑問のauf</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）？ auf die Probe stellen</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）auf（…に就いて） von, über</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）auf den Fersen（所属不明のauf）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）通路のauf（=über）</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）auf der Straße  auf dem Meer</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）auf dem Rhein, etc.</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）［英］前置詞的up</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Ein Preis ist <u>auf seinen</u> Kopf gesetzt.</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）sich verstehen auf～</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［仏］au vu de....   au su de....</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）…に関係する  sich beziehen auf</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）auf=an die［数詞と］<br>「凡そ］,「…に至る」  bis, <u>gegen</u>.</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）auf der <u>Seite</u>   auf die <u>Seite</u>［特］</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）ein viertel auf zwölf</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）…に費消する（auf....）</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）warten aufに就いて  ［特項］</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）auf jems Seite  の所属如何？</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）［英］on strike  auf der Hut</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）auf der Hut sein</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）auf seinem Posten   auf seiner Hut</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）<u>auf der Wacht</u>  副詞規定と述語的</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）途上のaufから「状態のauf」（英に多し）<br>への移向</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）途上のaufの四格。</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）<u>auf dem</u> Schuggel<u>wege</u></a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）<u>auf</u> dem <u>Pfade</u> wandein<br><u>Wege</u></a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）<u>on a model</u>.  （独：nach）</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）sich auf ～ ［ver-］legen</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）sich auf ～ verlegen等</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）stoßen....auf</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2">70-2R</div><div class="col-8">auf</a></div><div class="col-2">62-133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）空間的原意。</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）場所のauf  Die Kühe werden <u>auf der Wiese</u>.</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）空間的原意のままの転用：<br>Verdacht auf ～ werfen.など</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）zeigen<br>auf....sehen<br>schlagen</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）空間的（表面付着的、乗る）  aufs Papier.</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）auf etwas <u>zu</u>=</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［Anschlag auf］   auf ～ los</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）「岸」のon（ob）  Frankfurt am Rhein.</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）verweisen <u>auf</u></a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）auf der Stelle</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）空間的を抽象的に（IV.）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）folgen suf （nach）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）auf Rehnen   auf=nach（auf ～ zu）</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）空間的を抽象的に（III）</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［重きものが荷になる］</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）<u>s\'appesantir</u> <u>sur</u>....<br>（Nachdruck legen auf） ［特項}<br>重みがかかる、時間が長びく</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）おしつける  auf ～ schieben  auf jmn. wälzen</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）verteilen auf ～ </a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）....に巻きつける（等）</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）形容詞のauf支配</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）<u>eine Satite au</u>f</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）Jagd auf....</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）Endungs =auf （auf....auslautend）</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）Wortspiel auf</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）auf gutes Gelingen!</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）<u>auf alle Fälle</u></a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）auf etwas Bescheid wissen.（…に対して）</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）重語  -auf-  （schwarz auf weiß.）</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）lautet auf....  steht auf（zeigt auf）目標</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）編者注：手紙の文例</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2">70-3R</div><div class="col-8">auf</a></div><div class="col-2">134-183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）auf den namen ～ hören<br>gehen</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）ein Viertel <u>auf</u> zehn.</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）居所一般  auf der Seite.  auf der Linken.</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）船上（an Bord des ....）</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>auf der Nase</u></a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Wieviel Hunde sind auf diesem Bilde?</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）樹</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）aufと四格と形容詞（auf ～ lüstern, erpicht）</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）paßt auf.... trifft zu auf ～</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）aufmerksam auf ～ auf....bedacht,</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>böse auf</u>....</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）auf etwas bestehen, beharren</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）auf etwes <u>pochen</u>.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）執着のauf  固執、固持  関心、尊重の対象。</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）軽蔑の対象</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Neid auf  Haß fassen auf ～</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）…に懸けて（bei） （auf-hin）</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2">70-4R</div><div class="col-8">auf</a></div><div class="col-2">184-270</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）aufs Papier.  auf dem Papier. 地（ぢ）</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Der Tot <u>steht</u> darauf.</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）etwas zu etwas machen  ［---bringen］</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）auf---bringenに対する三格形</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）auf diese Weise.（四格）</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）auf diese Weiseのaufの説明法：</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）身体の故障の局部的指示</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）楽器。  spielen.</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）auf etw. hoffen, spekulleren.</a></div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）rechnen auf ～  compter sur ～</a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>auf albeine Worte</u> sich fest nageln lassen.</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）将来の予定的一点  …を期して  anberaumen.</a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）auf heute = für heute.</a></div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）auf meine alten Tage</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）auf die Dauer   auf die Länge</a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）将来の期間のauf  auf....hinaus</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）時（点）のauf（古）</a></div><div class="col-2">251</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）auf den....tag（zuとanとに同じ）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）［仏］sur le moment「その瞬間は」</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Sur l\'heure（直ちに）  Sur-le-champs</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）on the stroke of 1.  一時をきいて<br>即広のaufの一種</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）auf allen Fall, auf alle Fälle.</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）auf den ersten Blick</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2">70-5R</div><div class="col-8">auf</a></div><div class="col-2">271-352</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）auf Schritt und Tritt  ［特］</a></div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>auf 100 Schritt</u>［hin］  「距り」</a></div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）最高級と。</a></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）auf den Kopf stelien. auf den Beinen stehen.<br>\'（人間、物体の中心を、彼自身と見る考え<br>方）</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）軸、蝶番等の場合<br>became the great hinge <u>upon</u> which every<br> thing turned.</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）<u>auf Flügeln</u> des Gesanges.</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）auf dem Fuße <u>folgen</u>, <u>eilen</u>, etc.  ［特］</a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）auf der Wellenlänge 40.05 funken</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）制限のauf  se borner à</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）auf gut Glück等  ［特］</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）auf Vorschuß  四格［で］</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>auf</u> gut <u>deutsch</u>.  <u>Auf Deutsch</u><br>（言語、メロディー等）</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）基礎のauf  beruhen, fußen, begründet sein</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）auf［……を基礎として］［で」<br>［英］一般的参考</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）詳しさの表現 auf die Minute</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）auf Leben und Tod.</a></div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）auf.--［hin］  auf Gedeih und Verderb.</a></div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2">70-6R</div><div class="col-8">auf</a></div><div class="col-2">353-417</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）auf--hin.</a></div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）即広のauf  殆ど無意味なlà-dessus,<br>（独でもDarauf hinと云いそうな場合）<br>「ではまあそう云うことにして」に当る。<br>（話を打切るとき）</a></div><div class="col-2">369</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）時間的：<u>これありたる上はもはや……</u></a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）…の結果、…の故に。</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）auf einen Gedanken kommen  移行のaufの一種</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）適合のauf  <u>auf</u>-<u>passen</u></a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）に対して  頭割に  Pro Kppf</a></div><div class="col-2">376</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）     <u>bei</u><br>三ツアリ  <u>auf</u> frischer Tat ertappen<br>über→</a></div><div class="col-2">387</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）sur le pier de....</a></div><div class="col-2">396</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）平等関係： on an equal footing</a></div><div class="col-2">408</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Er ist <u>auf dieses Thema</u>.</a></div><div class="col-2">408</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Anrecht auf</a></div><div class="col-2">409</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Rücksicht auf</a></div><div class="col-2">409</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）auf Kosten des</a></div><div class="col-2">410</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）auf die Rechhung<br>Kosten, Verantwortung.</a></div><div class="col-2">413</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Koste, Rechnung其の他に関する参考事項：<br>en être pour ses frais （seine Rechnung<br>finden zu Kosten kommenなど）  特項</a></div><div class="col-2">416</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）auf eigene Faust参考   ［特］</a></div><div class="col-2">416</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）auf seiten</a></div><div class="col-2">417</div></div>');
document.write('<div class="row"><div class="col-2">70-7R</div><div class="col-8">aus</a></div><div class="col-2">418-470</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）ausと時期概念</a></div><div class="col-2">418</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）殆どvonと同じaus</a></div><div class="col-2">422</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）普通（空間的）<u>aus</u></a></div><div class="col-2">424</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）aus Holz</a></div><div class="col-2">426</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）空間象徴的  <u>entspringt</u> aus～</a></div><div class="col-2">430</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）認識の出所  ergibt sich,geht hervor,<br>erkennen lassen（sich）, folgen, weissagen.<br>schöpfen.</a></div><div class="col-2">432</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）認識の出所源を指すaus（anと同意形）</a></div><div class="col-2">433</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）手段等の出所を指す aus allen Kräften, usw.<br>（durch,mit）</a></div><div class="col-2">439</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）ADNOMINAL  …出所、出身。</a></div><div class="col-2">446</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）出所.由来.出身のaus ～ist aus～<br>（aus ～ gebürtig）</a></div><div class="col-2">448</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）ある状態から（脱する）aus dem Schlaf.</a></div><div class="col-2">449</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Sie bringen uns ja ganz aus dem Reim.</a></div><div class="col-2">450</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）外す、外れる  bei,inの反対<br>aus（außer）Rand und Band［kommen］</a></div><div class="col-2">451</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）［英］out of ～   「奪ふ」のumの意型  特項</a></div><div class="col-2">464</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）構成要素のaus  besteht aus  ［特］<br><u>sich aus</u> ---- Elementen <u>zusammensetzen</u>.</a></div><div class="col-2">464</div></div>');
document.write('<div class="row"><div class="col-2">70-8R</div><div class="col-8">aus</a></div><div class="col-2">471-547</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）aus der Hand essen</a></div><div class="col-2">471</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［仏］à même = aus（に近し）</a></div><div class="col-2">472</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）aus voller Brust.</a></div><div class="col-2">473</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）全力を賭して、力のかぎり  aus allen Kräften</a></div><div class="col-2">477</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）aus dem Auge <u>sehen</u>等。<br>「口から漏れる、の如し」</a></div><div class="col-2">478</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）etwas aus etwas <u>machen</u>.</a></div><div class="col-2">479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）或る人のロを借りて。（ausと人格、人間）</a></div><div class="col-2">497</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）sich kein Gewissen <u>daraus</u> machen<br>make no scruple of ～ ing</a></div><div class="col-2">500</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）ich weiß nicht, was ich aus der Sache machen<br>soll. わからぬ</a></div><div class="col-2">506</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）aus Sparsamkeitsgründen. -rücksichten.</a></div><div class="col-2">513</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）副詞的aus dem ～</a></div><div class="col-2">518</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>aus</u>でも<u>von</u>でもよい</a></div><div class="col-2">519</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）副詞のex</a></div><div class="col-2">519</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）空間的 （二格支配:<u>außer Lande gehen</u>.）</a></div><div class="col-2">520</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）außer（inの反対として）in Ehe erzeugt<br>außer Ehe erzeugt. = <u>out of wedlock</u>.</a></div><div class="col-2">521</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）außer（三格）「以外に」</a></div><div class="col-2">522</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）außer all<u>en</u> Zweifel setzen.</a></div><div class="col-2">524</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）von Sinnenのvonと同  <u>beside</u></a></div><div class="col-2">527</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）（格支配せざる例をも含む）</a></div><div class="col-2">529</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）außerとの結合（es sei denn）</a></div><div class="col-2">536</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）außer（普通の）</a></div><div class="col-2">546</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）<u>außer Acht</u>其他熟成語  außerstande sein.</a></div><div class="col-2">547</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）außerの二格支配  <u>außer Landes gehen</u>.</a></div><div class="col-2">547</div></div></div>');