document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">71-1R</div><div class="col-8">bei</div><div class="col-2">1-44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）空間的bei   bei der Hand.</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）重語とbei   Stern bei Stern.<br>Welch reicher Himmer! <u>Stern bei Stern</u>.</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）bei Heller und Pfennig.</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）bei einem Haare</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Es handelt sich <u>bei</u> ～ <u>um</u> ～</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）bei（…によって、のために）</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［英］by～時の副詞句</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）「許」のbei  beim Militär  beim Theater<br>beim Film.</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）bei（許）は商店、書店、官衛等庁にも用ふ。</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）許（chez.）  apud. penes.</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）将に云々せんとす。  現に云々するところ</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）dabei sein ［<u>bei</u>wobnen］「臨場」のbei</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）意識で<u>臨</u>む  <u>従事</u>（精を出す）<br>［不定法と共にも］<br>（bei....sein）  Heideggerのbei ～</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）<u>Es steht</u> bei dir,<br>es kommt auf dich an.</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）bei Dutzenden = dutzendweise, Hunderten</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）bei Haufen = in Haufen</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）空間的  bei der Hand  <u>nahe bei</u> der Tür.</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）無冠詞の<u>bei Aktschluß</u>等</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）時間的概念と共に（…である<u>と</u>。をも）<br>meteorologischer Umstnd!<br>bei Tage arbeiten</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）<u>bei offenen Fenstern schlafen</u><br><u>しながら</u>  <u>しつつ</u>  の下に  1.瞬間的<br>2.持続的</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）bei seinen Leb<u>zeiten</u>   zu Lebzeiten des ～</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）Gelegenheit, Anlaß, Fallと共に</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）bei（差のumと同し、英by）</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）仮定強調（場合のbeiを）</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）bei ～ 「云々せんとするに際しては」</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）…と同時に 1.瞬間的</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2">71-2R</div><div class="col-8">bei</div><div class="col-2">45-87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）bei ihrem Anblick（瞬時的、即広的）<br>at the ～</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）際（普通）［一般的］</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Das wunderbare bei der Sache war....<br>（anと同じ）</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）…云々しながら、しつつ。（unter）</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）dabei, wobei等<br>純（即ち補足的）並列意味形態（u.zw.）</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）dabei    相反的（しかも）</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）dabei 同時に</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Es ist nichts Verwunderliches <u>dabei</u>.</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）…していると。…故<br>nomen actionis（のみならず）</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）dabei    相反的<br>bei alledem</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）dabei（…したのに！）  後続の認容相反型</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）把捉肢節のbei<br>Männer Muß man <u>bei der Ehre packen</u>,</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）bei der Handの抽象的場合  場所的表現局限化<br>wo ihr\'s nackt, da ist\'s interessant</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Beim Namen   <u>beim namen</u> nennen<br>bei der Hand fassen</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">71-3R</div><div class="col-8">bei</div><div class="col-2">88-176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）beim Namen</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Ich war nicht recht bei der Sache</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）παρά（…の許から）</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）人のLOKATIV  或人に向って等（auprè de....）</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）bei jem  einkehren<br>wiederkehren<br>anfragen, anklingeln</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）人間の人格を指す bei  bei ihm<br>L0CATIVISCH（subjektiv）</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）ES STEHT BEI JMM. it rests with him.</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）bei（或人の場合に於て）</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）その人の説によれば（書いたものでは）<br><u>für</u>, <u>nach</u>,及び単に三格とも関係す</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）bei sich（身に）</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）熟語 bei sich 心の中で</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>僕は</u>云々（殆ど主語したもの） L0CATIV</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）に関しては  を［……］するに際して<br>（の場合にあっては）  英の<u>with</u>→</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）beiは無支配（Dativを用ひず）  大約</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）…に懸けて（誓ふ、嘆願する）</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）bei Strafe（誓と嘆願---に対して脅迫）<br>無冠詞！！！（やはり<u>懸け</u>てなり）</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）beim <u>Lichte</u> besehen</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）bei einem Grog［sitzen］等</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）bei Wasser und Brot   特項</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）neben（…以外に、…を持つと同時にまた…<br>（…にも拘らず）へ移るもの</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）所有のbei   bei Trost, u.s.w.  bei Kraft.<br>bei Hoffnung.</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）<u>schwer</u> bei Leib.   <u>knapp</u> bei Gelde<br>von  と同じbei 所有のbeiと関係す<br>an</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）<u>bei</u> 100 ℃</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）bei ～ helfen   behilflichsein</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）bei lebendigem Leibe</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2">71-4R</div><div class="col-8">bis</div><div class="col-2">177-216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）bis zu  副詞的</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）bis zu....</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）普通のbis zu（空間、時間）</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）bis zu ～ ［～にも及ぶ］  十時間もかかる  数詞</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）乃至</div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）bisと名詞以外</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）bis+名詞（IV.）</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）beiと前置詞  bis an des Ende der Welt.</div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）von ～ bis ～</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）「…に至るまで」</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）「除いて」［仏］à -- près.</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>Bis auf weiteres</u></div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）bis in seine Einzelheiten［hinein］<br><u>bis in</u> die späteren Jahre <u>hinein</u>.</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）bis zu</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2">71-5R</div><div class="col-8">durch</div><div class="col-2">217-244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［MHD］durch = um ～ willen</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［中高独］［古高独］durch = um ～ willen<br>（目的）</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）仲介物</div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）= während</div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）普通の空間的durch</div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）［仏］par 空間的</div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）durch ---- hindurch=</div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）手段のdurch</div><div class="col-2">230</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）....の故に（理由、原因）  <u>wegen</u>と同じ</div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）受働文とdurch.</div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Er starb durch meine Hand.</div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>Agens</u>（wirkende Ursache） …によって、<br>のお蔭で。</div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）…を介して</div><div class="col-2">241</div></div></div>');