document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">72-1R</div><div class="col-8"><a href="../072/s0001.html">für</a></div><div class="col-2">1-74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0001.html">（1）述語のfür  etwas für etwas halten等！</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0002.html">（2）dankbar  für<br>erkenntlich</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0002.html">（3）Platz für ～</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0003.html">（4）［英］for+to+Infin.</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0003.html">（5）［英］for（all）…にも拘らず</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0004.html">（6）sorgen für ～  verantworten für ～</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0005.html">（7）abgestorben für等</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0009.html">（8）［英］for = against</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0009.html">（9）形容詞の支配するfür ....［reif für］</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0022.html">（10）gut für</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0024.html">（11）reit für</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0025.html">（12）形容詞のfür支配：geeignet für（目的！）</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0027.html">（13）こんなのはわしには向かぬ。</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0029.html">（14）envers  für eine Person（gegen）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0029.html">（15）berühmt <u>für</u>, <u>um</u>, <u>wegen</u></a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0030.html">（16）Kein Geheimnis  für Sie.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0031.html">（17）für den Fall des.... －－のためには</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0032.html">（18）合成語  <u>für 0perationszwecke</u>.</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0034.html">（19）該当（－に対する）  ausdruck für -</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0035.html">（20）何年<u>度</u>の</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0036.html">（21）für（云々するための）（<u>zu</u>）</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0036.html">（22）Erklärung für ,,,,</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0041.html">（23）命名用のfür ～<br>Bestimmung, Aufgabe.</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0043.html">（24）命名用のfür  ［失・補］</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0047.html">（25）ein Mittel  <u>für</u> ～ （=gegen）</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0047.html">（26）用途［adverbal］</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0047.html">（27）用途［adnominal］</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0048.html">（28）基本的：純目的</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0049.html">（29）基本的：に対して（感謝、を主に）<br>verpflichtet  verbunden, danken, dankbar</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0050.html">（30）statt（…の代りに…どころか）</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0051.html">（31）für =als  として</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0052.html">（32）zu Gunsten des....</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0056.html">（33）sich für etwas begeistern, interessieren</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0074.html">（34）熟語für sich = allein</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">72-2R</div><div class="col-8"><a href="../072/s0075.html">für</a></div><div class="col-2">75-129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0075.html">（1）云々<u>にとって</u>重要、等</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0076.html">（2）für meine Augen</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0076.html">（3）was für</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0077.html">（4）決定、賛成のfür. 味方する、有利</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0089.html">（5）<u>Tag</u> für <u>Tag</u>    day after day</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0089.html">（6）umと同じfür</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0090.html">（7）…に引換へて（價）  <u>umと同じ</u></a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0096.html">（8）…の故に（因由形無は<u>仏英</u>）<br>…に対する返報として<br>…に対する代償として</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0098.html">（9）その代り（その償ひとして）</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0099.html">（10）da fürだからまた…（auch）  だからこそまた<br>wofür seid ihr ein Arzt?</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0100.html">（11）何人分働く、等  幾莫「分」の（数詞と共に）</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0105.html">（12）何円<u>分</u>（がん！）</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0105.html">（13）保険額の場合  für?  auf?</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0106.html">（14）先づ…の所は  <u>für</u> <u>immer</u><br>幾莫「分」だけ（時間的）</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0122.html">（15）予定のfür =auf</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0125.html">（16）殆ど無意味な方：  <u>für gewöhnlich</u>等</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0129.html">（17）for the most part</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2">72-3R</div><div class="col-8"><a href="../072/s0130.html">für</a></div><div class="col-2">130-170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0130.html">（1）für tot等   für gewiß  として</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0138.html">（2）was....betrifft</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0139.html">（3）was....betrifft<br>Ich für mich［云々にかけては型多し］<br>［wegenの用法とも同じ］</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0147.html">（4）<u>in Bezug auf</u> was....betrifft  該当</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0156.html">（5）für =je, pro</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0156.html">（6）Gleiches <u>glit</u> <u>für</u> ～</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0156.html">（7）…としてなら（als）</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0157.html">（8）für sein Alter.年の割には…、にしては</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0164.html">（9）für =als  für etwas <u>halten</u>, <u>ausgeben</u>, <u>achten</u>,<br>nehmen, <u>gelten</u>.</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0167.html">（10）<u>verantwortlich</u> für <u>zuständig</u> für</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0167.html">（11）für ～ bürgen.</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0167.html">（12）fürchten  für ～<br>zittern</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0168.html">（13）FürとVorとについて   特</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0169.html">（14）Bestimmungsort.（何処其処向け）<br>en route for,   autobus für....等</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2">72-4R</div><div class="col-8"><a href="../072/s0171.html">für, gegen</a></div><div class="col-2">171-215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0171.html">（1）für甲を捨てて乙を採る  tauschen vorziehen</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0173.html">（2）方向のgegen［=gen］</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0173.html">（3）100 gegen eins等</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0177.html">（4）空間的原意</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0178.html">（5）対抗、敵対。</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0182.html">（6）に対して、に向って</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0182.html">（7）Dativ.</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0184.html">（8）約（近く） schier, fast, beinahe, nahezu</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0187.html">（9）gegen den Preis von....<br>［及び<u>交換のum</u>に近きもの］</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0189.html">（10）versus～対～  hie--hie</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0189.html">（11）<u>Mann gegen Mann</u> 副詞的成句</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0190.html">（12）重語</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0191.html">（13）頃（前）</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0195.html">（14）「人」…に対して（envers） <u>mit</u>, <u>zu</u> erga</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0203.html">（15）対して（<u>vor</u>に近し）  形容詞を含む</a></div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0205.html">（16）…に較べては  vergleichen mit</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0210.html">（17）～に反して。</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0211.html">（18）<u>Verstoß</u> gegen-</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0212.html">（19）不利・反対（ant: für）<br>gegen einen stimmen, auftreten.</a></div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0215.html">（20）....ist gegen ～ 述語的</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2">72-5R</div><div class="col-8"><a href="../072/s0216.html">hinter</a></div><div class="col-2">216-236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0216.html">（1）hinter....drein =（her）</a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0218.html">（2）hinter Schloß u.Riegel（…の中で）</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0Z24.html">（3）die Tür hinter sich zu wefen.</a></div><div class="col-2">Z24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0225.html">（4）「劣る」hinter</a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0225.html">（5）空聞より転用（象徴的）<br>Dahinter steckt etwas.</a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0226.html">（6）町はずれ（vor）</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0226.html">（7）hinter--［hervor］［auf］</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0227.html">（8）その向ふ側、…の次あたりで  jenseits.</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0231.html">（9）遠き彼方を指す  hinter,（=über）</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0232.html">（10）…を前に置いて（飲物等）bei</a></div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0236.html">（11）hinters Licht führen等</a></div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../072/s0236.html">（12）hinter ～ kommen  dahinter steckt etwas.</a></div><div class="col-2">236</div></div></div>');