document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">74-1R</div><div class="col-8">über<br>編者注：74-1R, 74-2R,ではüberの意味を<br>図形で説明している。</div><div class="col-2">1-46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）über = gegenüber</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）über einem Glase Wein</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）「襲ひ掛る」 über（überfall）</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）ein Scheck über....</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）über ～ herab  über = von</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）静止</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）überとaufの区別</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）…の上に超然として</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）低迷  hovering  planer  schweben</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Die Pumpe kann das Wasser nur um 10 m über<br>den Grundwasserspieger heben.</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>über die Tannenspitzen</u>   hinの機能</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）über die Haut等  全表面に広がる意。<br>（時間的・空間的）</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）被覆  <u>tragen</u>  （着物）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）掩ふ（III. IV.）</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）<u>quer</u> über</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）運動  auch: über die Straße</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）über -- <u>hinweg</u></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）über -- <u>hinweg</u></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）静止の動詞と運動</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）表面移動 ［下敷にして］</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）<u>via</u> Sibirien</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">74-2R</div><div class="col-8">über</div><div class="col-2">47-124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）über die Brücke  über die Straße</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>皮岸に</u>、 静止、 <br>über die Staße wohnt等<br>の静止形をも含む）</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）［heute］ über eine Woche</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）über und über   副詞</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）einmal über das andere.（umとは違ふ）</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）同語重畳</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）間投的（umもあり）  呪ひの間投句</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［時問的］後置句として  hindurch, durch.</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）über das Wochhenende  土曜から日、月曜<u>にか<br>けて</u></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）zeitüber  時間的、空間的 （前からずっと）</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）瞰下的、支配的、空間的（III）<br>北海に日が沈む</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）瞰下的、支配的、空間的（IV）</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）über...zusammenschlagen.   特</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）über den Haufen rennen</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）half <u>past</u> three</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）…以上、…も及ばず</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）その上更に［それ以外に］  über -- hinaus.</div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）über（IV.） 度をすごす。「以上」に</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）Deutschland über alles  「勝る」型</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）「うずくまる」姿勢一般<br>über den Büchern sitzen    附</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）über einer Missetat ertappen.<br>auf frischer Tat ertappen.</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）…を聞いて愕く  über （=ob）と三格</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）…の間に。…の後に。…のために。</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2">74-3R</div><div class="col-8">um</div><div class="col-2">125-173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>um</u>sonst  <u>um</u> nichts</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）間投句の<u>um</u></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）darum, daß目的  umとzu不定法と関係</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）es sei <u>darum</u>.</div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Es ist mir gar nicht <u>drum</u>.</div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）um（に就いて）  aboutの如し  Wissen um（von）</div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）sich um....（be）kümmern（scheren）  grämen<br><u>um</u> etwas <u>beneiden</u></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）es handelt sich um....<br>es ist um ihn <u>geschehen</u>.</div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）einem ist s.u.s <u>ums Herz</u>   warm weit</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）忌避、回避  einen großen Bogen machen um.<br>sich herumdrücken um ----</div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）周囲  rund um （round about）</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）um ～ her</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）<u>um sich</u>（greifen, schlagen, schießen）<br>mit Geld sich werfen  打ち<u>まくる</u></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）空間的um.（<u>中心</u>として）自転<br>Die Erde dreht sich um ihre<br>eigene Achse.</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）<u>um fünf Uhr</u></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）頃</div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）空間的：の辺［あたり］<br>um Herzもこれなり。</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）「凡そ」の<u>um</u></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）was <u>drnm und dran</u> ist</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）im Austausch gegen （Duden）  für（引換へて）<br>［英］<u>in exchange for</u></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）Aug um Aug 報復の<u>um</u>. Zahn um Zahn</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）um ～ <u>rechten</u></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）<ruby>遉<rp>（</rp><rt>さす</rt><rp>）</rp></ruby>がは云々 …故なきに非ず  nicht umsonst,</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）umsonst （gratis）</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）甲を捨てて乙<u>を</u>採る（見かへる）</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）um und um  副詞</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）<u>um das dritte Wort</u></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）一日置きに  einen Tag um den andern</div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）eins um das andere  überと対照<br>eins <u>nach</u> dem andernは、甲、乙、丙、丁…<br>eins um den andernは、甲、乙、甲、乙、</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）重要な区別  um meinet Willen</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）verdienen um     特</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2">74-4R</div><div class="col-8">unter</div><div class="col-2">174-208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）空間的unterと同じもの：</div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［着物］の下に［隠して］</div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）unter seinen Händen  zwischen型</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）leiden unter</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）日付とunter  untem 15ten, 等</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）<u>unter</u> andern Worten = <u>in</u>, <u>mit</u></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）unter Segel,［成句的］</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）unter Anklage</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）<u>迂言動詞</u>の<u>unter</u></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）être sous clé</div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）空間的原意。</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）下<u>から</u>   <u>weg</u>!  <u>hervor</u>!  <u>empor</u>!</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）unter Wasser  U=Boot, U=Bahn,  unter der Erde</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）unter der <u>Gestalt</u>....<br>sub specie aeternernitatis.<br>「の見地から」  様相のunter<br>形態様相のunter<br>仏式unter</div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）……以下（抽象的）  überの反対</div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）fast partitiv （<u>von</u>）</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）重いもののために  ieiden unter....</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Identitäts=unter</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）unter:語源<br>希：έντόｓ<br>羅：interとinfra<br>梵：antar（副）  中に、中間に。<br>antara： 内部の、中間の、<u>他の</u>。<br>「他の」ゆえ.、<u>ander</u>（他の），<br><u>other</u>と関係す。</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）unter:während<br>unterweilen （Dativ） etc.</div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）<u>neben</u>, <u>außer</u>と同じ</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）unter der Schürze</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）<u>unter</u> meine Augen   unter der Lupe.<br>unter seinen Händen （?）<br>（unterbreiten....）</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）云々しつつ<br>（但しnomen actionisに非ざるもの）</div><div class="col-2">206</div></div></div>');