document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">75-1R</div><div class="col-8"><a href="../075/s0001.html">von</a></div><div class="col-2">1-21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0001.html">（1）基礎的：…から（発して） <u>von</u> ～ <u>aus</u><br>von ～ an  von ～ ab</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0001.html">（2）<u>von</u> <u>ungefähr</u>  âventiure</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0002.html">（3）英 → 独  from behind, from under, from around<br>前置詞の三四格支配の項→</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0002.html">（4）［仏］…に…されて  épuisé de fatigue.<br>éreinté de fatigue.<br>rompu （de fatigue?）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0003.html">（5）davon = deien  仏 = en</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0004.html">（6）von partitirum   unterと同じ</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0007.html">（7）<u>vom</u> Standpunkt.   特項<br>［仏］au point de vue.</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0007.html">（8）<u>from</u>の特殊型  <u>aus</u>   from being<br>（…であったのが）</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0008.html">（9）partitiv = vonと人間<br>Es ist <u>nichts</u> <u>von ihm</u> zu sehen.</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0013.html">（10）von ～ nichts.  <u>Geld</u> hab ich <u>keins</u>. →<br>不定、語順</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0014.html">（11）Genitirus Partitivus的vonの基礎現象<br>wenig  <u>von</u>   all of them<br>viel</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0015.html">（12）abhängen von   independent of ～ 特項</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0016.html">（13）abhängig von  PARADIGMA</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0019.html">（14）ein Bündel von ～ </a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0019.html">（15）内容・型・種類・性質のvon<br>von dieser sorte, von dieser Art,</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0020.html">（16）von（-an等）「…から以後」<br>1.ab.  2.［仏］dès, à partir de,</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0020.html">（17）内容を示す  Genitivus Qualitatisに相当<br>するvon（或いは<u>aus</u>にかかる事あり）</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0021.html">（18）ein Mann von Wort</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0021.html">（19）ein Mann <u>von Wort</u></a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2">75-2R</div><div class="col-8"><a href="../075/s0022.html">von</a></div><div class="col-2">22-55</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0022.html">（1）<u>von</u> Anfangan <u>an</u>  時間的（seit）</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0024.html">（2）von Haus aus</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0025.html">（3）Genitivの代りにvon</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0029.html">（4）Die Frau vom Meer型（位置の前置詞を使う<br>ところを）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0029.html">（5）von....Aussehen</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0030.html">（6）Die Meerenge von Gibraltar</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0032.html">（7）<u>von zwei Stockwerken</u>.（数量規定と）</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0033.html">（8）GENITIV=VON  聯語の前で</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0033.html">（9）eine Hühe <u>von</u> tausend Meter.</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0034.html">（10）具体的「…から」 von der Stelle</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0036.html">（11）von ～ aus  depuis</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0036.html">（12）普通のvon（…から） （由来、根源、出所）</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0040.html">（13）…から<u>期待する</u>等</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0040.html">（14）from <u>among</u>等</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0040.html">（15）何人「中」何人のvon.</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0041.html">（16）普通の「離れる」のvon</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2">75-3R</div><div class="col-8"><a href="../075/s0056.html">von</a></div><div class="col-2">56-85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0056.html">（1）refrain <u>from</u>    prevent <u>from</u><br>abhalten, abstehen, absehen von<br>sich fernhalten von</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0059.html">（2）verschieden von   unterscheiden ～ von ～ </a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0065.html">（3）貴族のvon.（とzu）</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0067.html">（4）貴族</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0068.html">（5）von ～ bis ～（乃至）</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0069.html">（6）Du sublime au ridicule<br>il n\'y a qu\'un pas.</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0071.html">（7）von bis  von Wirbel bis zur Zehe.<br>Zehはder Zeh及びdie Zehe</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0075.html">（8）von---zu---  von Fall zu Fall</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0079.html">（9）von Meilenstein zu Meilenstein</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0079.html">（10）von Angesicht zu Angesicht</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0079.html">（11）von Mund zu Mund = jeden Mund.</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0080.html">（12）von--zu--  jedenと同じ</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0082.html">（13）von Tag zu Tag 日とともに（益々）</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0082.html">（14）Grüß ihn <u>von mir</u>. （von seiten）</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0082.html">（15）独ではGenitiv</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0083.html">（16）<u>Genitivisch</u></a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2">75-4R</div><div class="col-8"><a href="../075/s0086.html">von</a></div><div class="col-2">86-114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0086.html">（1）Genitivでもvonでもよいもの<br>an Stelle des  an Stelle von....<br>nördlich des  nördlich von....</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0086.html">（2）Die Herren von der Kommission</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0092.html">（3）être de semaine（週番）<br>être de faction<br>être de service （im Dienst）</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0093.html">（4）Der Ritter vom ～ 等</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0094.html">（5）von = über （に就いて）</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0095.html">（6）Das Lied <u>von</u>....</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0101.html">（7）eine Anzehl von</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0102.html">（8）数量的規定 von einer Höhe <u>von</u> 1000 Meter.</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0103.html">（9）eine Freund von ihm 物主代名詞代り<br>［un sien ami］</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">75-5R</div><div class="col-8"><a href="../075/s0115.html">von</a></div><div class="col-2">115-169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0115.html">（1）Es ist von ～ die Rede    Il est question de</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0115.html">（2）wollte nichts davon hören</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0116.html">（3）nichts von   rien de ce....</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0117.html">（4）von Glück reden<br>sagen</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0117.html">（5）…とか何とか云う<br>von etwas reden, sprechen.</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0127.html">（6）<u>von</u> der Seite meinr Mutter［her］</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0127.html">（7）vonとdaß.... （又はob）（又はKonj.）</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0154.html">（8）vonの離置。［dessen, derenの代り］関係句。<br>（dont）</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0156.html">（9）vonの離置。 「…の」<br>［von....<u>daß</u>....の省略別形として考え<br>られ、同時にMeinungのvonと関係する<br>もの］</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0156.html">（10）von以外の構造とdaß....   wieとals.</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0157.html">（11）<u>Meinung</u></a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0166.html">（12）<u>von</u> etwas Leben</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2">75-6R</div><div class="col-8"><a href="../075/s0170.html">von</a></div><div class="col-2">170-221</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0170.html">（1）von etwas wimmeln. （材科、内容）<br>充溢的内容のvon<br>von Leben <u>Überströmen</u>,<br>von Kraft strotzen.</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0201.html">（2）…の為めに、（原因、由来）von....［her］<br>Genitivisch    "durch"の意。</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2">75-7R</div><div class="col-8"><a href="../075/s0222.html">von</a></div><div class="col-2">222-272</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0222.html">（1）由来を指す   von....herstammend</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0228.html">（2）由来［I］…から持って来たもの（sein）</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0231.html">（3）Ich kenne ihn <u>von</u> <u>Gesicht</u>.</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0.html">（+ dem Namen <u>nach</u>.）</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0233.html">（4）Ich kenne ihn von Gesicht.<br>Namen, Hörensagen, Person</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0233.html">（5）rührt von ～ her    ［特］</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0234.html">（6）"aus" Erfahrungのausと同様  von....her</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0237.html">（7）物質名のvon.（仏 du, de, la） Partitiv<br>［etwas von....］</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0245.html">（8）ist vcn ～  Génititif partitif<br>（Partitio -- かかられる語の省略）</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0254.html">（9）von diesen Menschen war Egmont.</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0254.html">（10）Agens =von （I）  受働文に於けるvon.</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0256.html">（11）Agens =von 自働詞の場合  =<u>durch</u></a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0258.html">（12）Agens =von 形容詞の場合</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0259.html">（13）Agens =von （II）  sich lassenの場合</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0260.html">（14）Agens =von （III）  ist zu +不定法の場合<br>（及ぴ未来受働分詞の場合）</a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0260.html">（15）von =<u>de la part de</u></a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0261.html">（16）Agens =von （IV）  hören, sehen, 等の場合</a></div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0262.html">（17）Agens=von （IIV） 仏語のavoir faire à moi等<br>（an）</a></div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2">75-8R</div><div class="col-8"><a href="../075/s0273.html">von</a></div><div class="col-2">273-305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0273.html">（1）de ma façon  （……にかかはる）</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0283.html">（2）von etwas reinigen    frei von....</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0296.html">（3）<u>rein</u> von</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0299.html">（4）schwanger von   voll von</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0300.html">（5）失ふ、離れる （beiの反対）<br>von Sinnen （von =ohne）</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0301.html">（6）von Stein  -aus-</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0303.html">（7）von heute auf morgen.</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0303.html">（8）ein Mann von Ehre.</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0304.html">（9）<u>von ganzer Seele</u> lieben等</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0305.html">（10）57 Personen  von  1000<br>unter<br>aus<br>［auf］ 比例の表現</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0305.html">（11）</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0305.html">（12）［英］: change <u>from</u></a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2">75-9R</div><div class="col-8"><a href="../075/s0306.html">von</a></div><div class="col-2">306-316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0306.html">（1）vor Anker liegen</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0306.html">（2）vor den Kopf  （stoßen, usw.）</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0307.html">（3）Ich duselte <u>vor mich hin</u>.</a></div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0307.html">（4）von der Nase weg</a></div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0308.html">（5）空間的<u>vor</u></a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0312.html">（6）空間的（補）「隠す」</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0312.html">（7）時間的  嵐の前の静けさ</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0314.html">（8）地名、市名と、（及び要塞等）</a></div><div class="col-2">314</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0315.html">（9）=für</a></div><div class="col-2">315</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0316.html">（10）vor 2 Monaten  （eigtl: 2 Monats zuvor）</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../075/s0316.html">（11）仏語のavantの特殊用法より。  ？</a></div><div class="col-2">316</div></div></div>');