document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">76-1R</div><div class="col-8">während</div><div class="col-2">1-7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）während<u>dessen</u>  <u>währenddem</u>  参考</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）”～の間”の表現</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2">76-2R</div><div class="col-8">wegen</div><div class="col-2">8-52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）wegen = inforge （原因）</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>原因</u>と<u>理由</u>   in rücksicht auf</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）…の廉により（褒める時も含む、…の<br>功により）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）…の件なら（の件に関しては）<br>was ～ betrifft</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）entschludigen <u>wegen</u>  danken für  特項</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）meinet wegen!</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Meinet wegen! の説明用</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Meinet wegen等</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）halberと同じ  =um-willen（目的）</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2">76-3R</div><div class="col-8">wider</div><div class="col-2">53-59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）wider （contrairement à）</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）～ wider ～</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2">76-4R</div><div class="col-8">zu</div><div class="col-2">60-78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）zu Heller und Pfennig&gt; （<u>auf</u>, <u>bei</u>と同じ）</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）zuを件ふ不定形のzuに関する参考<br>梵は、約束、誓ひなどには<u>三格</u>を用う…</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）.... spricht zum.... …に向って</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）nötig   zu<br>notwendig</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）zuと抽象名詞</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）対人関係のzu （mitと同じ）</div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［英］zum Gebrauch = <u>for</u> use<br>for our own use.</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>zum Tode</u> betrübt</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）［英］<u>to</u>（<u>soviel</u> ich weiß等）</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）［英］to perfection   to the limit</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）［央］to 支配形容詞</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>Friend to</u> this ground</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）<u>Friend to</u> this ground</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）副詞化のat  ［仏］àはzuに</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）unerläßlich zu</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2">76-5R</div><div class="col-8">zu zur</div><div class="col-2">79-99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）傾向・目的のzu</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）der Hang zu.... 傾向   adnominal</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）zuの前置詞  <u>zu Füßen des</u> Bettes</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Bohnen <u>zum Ausschoten</u><br>zum <u>Ausschülsen</u></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Heftpflaster <u>zum Ankleben</u>.  adnominal</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）zuと不定法の名詞化（一般的）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）使命：zum Herrschen geboren, bestimmt, etc.</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Bestimmung, Destinatis<br>「として」のzuと同じ<br>zum Mittel <u>empfehren</u>, <u>eignen</u>, dienen</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）Fähigkeit <u>zu</u>....</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）対称・うつり・似合い （gegenに似たり）</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Verhältnis <u>zu</u> ～</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）zwei <u>zu</u> zwei  （je） zwei <u>und</u> zwei</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）drei zu eins   三対一</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）senkrecht zu....   parallel zu （od. Dativ）</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）<u>zu Genußzwecken</u>.</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）dienen zu</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Wozu denken?</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）<u>einen</u> zu Diensten stehen</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Es ist mir--zu Mute.  無冠詞</div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）味方する、忠誠   zu ～ schwören.</div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）gut zu....   freundlich zu.... （mitと同じ_）</div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）werden型zu</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）reif zu ～ （及びzu支配の形容詞）</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）単に考への上で…<u>になす</u>  zu etwas <u>machen</u><br>zu ～ werden. 結果の一種。</div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）Der lateinische Doppel-Dativ.</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2">76-6R</div><div class="col-8">zu</div><div class="col-2">100-143</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）ZU+ 不定句の略形</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）目的のzu + <u>Nomenactionis</u><br>（adverbalisch）  両方<br>（adnominal）</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）仮構性の含みと動作名詞    研究用</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）目的のzu + nomen-actionis （adnominal）</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）…のために（目的）  …に資せんとして<br>「として」のzuと同じ</div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）für</div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Doppelter Dativなzu  結果のzuへ!</div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）後置のzu</div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）zu Fuß, zu Pferd  on foot  afoot</div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）幾莫々々「の」 （mitのàとも接す→）<br>（àと同じ）</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）aufと同じzu  …と見積る、等々</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（12）zum Verwechseln ähnlich   <u>bis</u> zum →<br>…するほどの程度に（まで）</div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）zu....schwören  「味方する」のzu.</div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）町の名とzu  （inとの相違）</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［仏］tenir à la main</div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2">76-7R</div><div class="col-8">zu</div><div class="col-2">144-191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）--対して--  Was sagen Sie dazu?</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Glück wünschen <u>zum</u> （sagen zuと同じ）</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Stellungsnaahe <u>zu</u>....［～に対して］<br>Wie steht er zu dieser Frage?</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Zum Wohl?</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）zum （zurは？） Teufel!</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）予定のzu（Fürと同じ）</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）時の副詞規定</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Die Nacht zu....</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）zum ersten male  ［zuerst］</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）<u>Zum Schaden</u> auch noch den Spott.<br>添へる、附加する （hinzu）<br>二つあり：1.外のと一緒に<br>2.…の上に更に加へて</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）zuの合成詞   zuletzt, zuweilen, zuerst,<br><u>zupaar</u>, zuhause, zumute, zurück, zusammen,<br>zugrunde, zunächst, zumeist.</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）zu Gericht sitzen等</div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2">76-8R</div><div class="col-8">zu</div><div class="col-2">192-249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）空間的（静止）  wie: zu Hause.</div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）熟語   zu Feld ziehen等</div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）zu Gute［zugete］</div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）bei jemandem <u>zu Gaste sein</u>.<br>zu Gebote stehen, <u>zur</u> Verfügung.<br>zu Liebe. zu Gunsten. zu Rate halten.<br>zu Mute.</div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>zu</u> meinen <u>Füßen</u>.  zu Hause. zur Hand.</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）空間的接近（人に）</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）空間的接近  zu Grabe tragen</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）抽象と（空間的・到達）<br>=現象としては最も広汎=<br>zu etw. übergehen</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）zur Stelle等   ［静止］<br>zur Hand. zur Linken. zur Seite.<br>zur Zeit. zu Grunde liegen.</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）zu Wasser und Land    by land. by sea.</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）zu ～ greifen  Zuflucht nehmen zu ～</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）<u>zum</u> Herzen dringen, 等  身体諸部</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）<u>zur Schule</u>  （gehen）</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）<u>zur mir</u> （bei mirに対して）</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）空間的zuの熟語（但し静止）  zuhause.</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）zudritt = drittens  zuerst.</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）zu hunderten.  ［zur Genüge］</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）zum mindesten, zum höchsten, zumindest</div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）zum Teil  型</div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）分量の副詞：zur Genüge.<br>（程度のzuの一種）</div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）zu meiner Überraschung （<u>gerelchen</u>!）</div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）zu meiner Überraschung<br>［仏］ pour mon malheur</div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2">76-9R</div><div class="col-8">zu</div><div class="col-2">250-282</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）…に向く（先置するもの）  ein Mann <u>dazu</u>.</div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>zur</u> Türe <u>hinaus</u></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）傾向（adverbal）</div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）zum Frühstück<br>Mittagessen</div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）屋号・旅館等のzu （仏のà ～ なる可し）</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Der Mann <u>im Monde</u>.<br>Mind<u>wirt</u>, Löwen<u>wirt</u>.<br>Sonnen<u>wirt</u></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Das Verhältnis zu etwas.</div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）das Zeug zum ～  …の才能、天分</div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）zu aüßerst  zunächst, zutiefst.</div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）zum aller--sten.</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）zu deutsch</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）zur Ruhe einladen等  zum Reisen überreden</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）KASATIVISCH  zum Aufbruch ermahnen.</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）云々して……云々を求める等</div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）zu ～ verurteilen  zu ～ verdammen</div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）FAKTITIVISCH : ZUR DARSTELLUNG <u>Bringen</u></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）zu etw übergehen.</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）gehört zu （所属）</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）und pfeift <u>dazu</u></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）zu Ehren des...</div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2">76-10R</div><div class="col-8">zufolge</div><div class="col-2">283-284</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）infolgeの意の際</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）従っ<u>て</u>、従へ<u>ば</u>  zugemäß</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2">76-11R</div><div class="col-8">zugunsten</div><div class="col-2">285-287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）zugunsten</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2">76-12R</div><div class="col-8">zwischen</div><div class="col-2">288-294</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>Unterschied</u> zwischen ～ </div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）unter （among）の意に。（例外的）</div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）時間的</div><div class="col-2">290</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）空間的（III. IV.）及  raumsymbolisch.</div><div class="col-2">291</div></div></div>');