document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">78-1R</div><div class="col-8">be=</div><div class="col-2">1-32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）bestrebt等の過去分詞形容詞  bestrebt sein,</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）belesen等の形容詞  <u>belesenes</u> Frauenzimmer</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）心神総体的のbe  Bewußt.</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）紛体把捉的対称化   直接対象化のbe=</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）再帰動詞とbe=  sich betätigen</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）bei=から来たbe=に就いての注意<br><u>besonders</u>等</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）DENOMINATIVA beweibt.  bebrillt.</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Transitivierend.  （an=と接す）</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）transitivierungeの語例  普通のもの。<br>sorgen für:  besorgen</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）be=とmit</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Heideggerの<u>be</u>=deuten</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Ich will dich be=～!</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）bechampagnerte Männer.</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）形容詞化した過去分詞：berümt  betrunken</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2">78-2R</div><div class="col-8">bei=</div><div class="col-2">33-44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）bei= herbei   稀</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）bei-behalten.</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）bei kommen.</div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）<u>beibringen</u></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）寄与のbei=  beitragen.</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）bei-legen.  bei-messen.</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）beizähren, beirechnen.</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）bei=pflichten  Beifall.  beistimmen.</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）添へる、   Beiwagen</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Beitritt型  DAT.  beiwohnen.  beitreten.</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）助ける、赴援する</div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）radio aktive <u>Beimengen</u></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Bei=neben  Beiwagen Beirichter, Beirat</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）klein beigeben    特</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2">78-3R</div><div class="col-8">beiseite</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）beiseite   lay by = lay aside, lay away</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2">78-4R</div><div class="col-8">beizu</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）beizu（daneben ソレル）</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2">78-5R</div><div class="col-8">bevor=</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）bevor=</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）bevor=</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2">78-6R</div><div class="col-8">daher=  dahin-  daneben  dank-  dar=<br>davon=  dazwischen-  drauf  drein</div><div class="col-2">48-67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）－襲ひ来る。－えらい鼻息で、</div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>dahin</u>gegossen等  über--dahin.</div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）dahinsterben, dahinsiechen.</div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）dahin-sprengen.</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）滑らかな運動  dahinschweben.</div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）dahin=leben等</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）－外れる－  daneben-schießen</div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）danksagen.  Dank wissen.</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）darstellen, darbieten, dartun,</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）darnieder=</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）davon=weg.</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）den Sieg davon-tragen,</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）dazwischen-</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）draufgehen drauflegen</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）finstet <u>drei</u>nsehen<br><u>darein</u></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）物凄く（daher=と同じ）  drein-fahren.</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2">78-7R</div><div class="col-8">durch</div><div class="col-2">68-88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）durch führen   ……しぬく、通す。  特</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）分離  やっこらせと通過する。  lativisch.</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）分離  Das Geheimnis ist durch-gesickert</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）逓進（次から次へ）  先へ</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）再帰で分離  sich durch-ringen, käpfen等</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Aktionsartの上から見たdurch三型の区別：</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）分離（穿つ）  ＝非分離もあり＝</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）分離  貫いて（一回） quer. hindurch=</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）durch-sprechen</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）非分離  die Nacht <u>durch</u>-tanzen  （時間を）</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）非分離  1.他働詞なり。<br>2.durch und durch, kreuz und quer<br>「さんざんに」の意。（zer=）</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）非分離  1.他働詞<br>.2.一回貫く（<u>haben</u>）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）分離  durchgekostet.</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2">78-8R</div><div class="col-8">ein</div><div class="col-2">89-149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）das Netz einziehen（殆んどzurück=型）</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）空間的：中へ［入る］</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）空間的  eingeschlossen.</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）普通の「込む」「込める」の諸型。</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）ein handeln  背ひ<u>込む</u>、型</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）取り<u>入る</u>  sich einschmeicheln.</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）<u>ein=weihen</u>型</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）開始のein=  einreißen.</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）破壊闖入のein</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）萎縮 めり<u>入る</u>。  eingefroren.  einschlafen.</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Eingebung. einfallen.</div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）叩き込む（等）  mit Dativ   einschärfen.</div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）ein ～ （し込む）  他動的</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）習ひ<u>込む</u>  仕<u>込む</u>  einfliegen.</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）云々し<u>込む</u>（摺り込む）  einsalzen.</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）sich in- einfühlen.   LATIVISCH</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）jm. etwas eintränken.</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）auf jemanden ein=</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）helfend einspringen.</div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）［英］to chime in</div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）ぴったりと適合させる。  auf ～ ein=</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）inn=と同じein=  止める。</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）制限抑制のein= （auf～）  einschränken,</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）einschüchernとeinschrecken  凹ます。</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）eindringen  einreißen  抽象的</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）einkehren</div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）einrühren等  空間、抽象両方  eihbrocken.</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）嵌め込む、等</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）一致承諾のein=</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）<u>ein</u>schlafen.  睡眠</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）einfangen  把捉、補足</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">78-9R</div><div class="col-8">einher=</div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）einher</div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2">78-10R</div><div class="col-8">emp  ent</div><div class="col-2">151-175′</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）emp=  =  =ent=</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）empor=   hoch in die höhe</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）ent=はάντιか？  Verbindungslied:</div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）を除く、取り<u>去</u>る。  sich entleiben</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）entfesseln</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）取り去る、奪ふ   非一化  entmiliterisierte<br>Zone</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）enthüllen［具体的］</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）離格とent=</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）展開する  entfalten（déployer）</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）主観の側から見た<u>entgegen</u>=</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）entgegen=</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>entlang</u></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）entzwei=</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2">78-11R</div><div class="col-8">er</div><div class="col-2">176-201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）原始的空間関係の=er</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）der=  ver=    方言</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）er=müden等  （総心的）  erfreuen. erkranken.<br>身</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）er-schweren  er-leichtern（形容詞と）</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>wecken</u>と<u>erwecken</u></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）…響き「渡る」等。（徹底、浸潤、総感）<br>erstrahlen lassen  erklingen, ertönen.</div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）er（得る）  ［er=fechten］</div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）ertrinken等（終の=er）（死ぬ、参る。）</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）上品な用語としての =er=   Erforschung.</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）erlustieren  erspazieren</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2">78-12R</div><div class="col-8">EX=</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）archi  Ur-元</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2">78-13R</div><div class="col-8">EX=</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）EX=  ［仏］ex-fiançée</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2">78-14R</div><div class="col-8">fehl=</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）fehl=</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2">78-15R</div><div class="col-8">fertig   205</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）fertig   fertigbringen.</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2">78-16R</div><div class="col-8">fest-</div><div class="col-2">206-207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）fest-  sich festlegen.  sich festfahren.</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）fixer.（festsetzen）  sich festklammern</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）結果挙述のfest=</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2">78-17R</div><div class="col-8">fort=weg</div><div class="col-2">208-209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）fort=weg</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［英］on, along = fort  進行</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）－続けて、引きつづき－</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）fort=（し去る）  lativisch</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）片付ける、獲得の =weg と同じ<br>（特に印象、確信等の）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2">78-18R</div><div class="col-8">frei</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>fre</u>istehen  <u>fre</u>ilassen</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2">78-19R</div><div class="col-8">für</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［不定法と分詞以外に用ひられぬもの］半分離<br>fürbitten.  fürsorgen.</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）fürder   ［英］further, farther</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2">78-20R</div><div class="col-8">ge</div><div class="col-2">212-231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）ge= gi, ge, ga（AHD）</div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Ge=con  Gevatter  compater（Mitvater）</div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2">78-21R</div><div class="col-8">gegen-</div><div class="col-2">232-234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［不定法と分詞以外には用ひぬ?］半分離</div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Gegen=kaiser   anti=</div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）gegenüberと三格  PARADIGMA</div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2">78-22R</div><div class="col-8">gleich</div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>gleich</u>=kommen等</div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2">78-23R</div><div class="col-8">gut=</div><div class="col-2">236-237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）gut=  gutheißen,  gutgehen.</div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）gut=～  gutachten</div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2">78-24R</div><div class="col-8">heim  her=</div><div class="col-2">238-241</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）heim（一般）</div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）heimschicken, heimleuchten,</div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）普通例（<u>her</u>auf等）</div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2">78-25R</div><div class="col-8">darüber  her</div><div class="col-2">242-279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）darüber  her</div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）her-</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）hergeben, was....kann.</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）sich zu etwas <u>hergeben</u>. sich hergeben müssen</div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）herstellen.  her=rechnen.</div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）vor sich her=</div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）hinter--her  vor sich her</div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［von je］her  ずっと  seiher</div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）空間的（ズラリと）</div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）her = daher</div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）単調に（herunter）</div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）herabdrücken （=reduzieren）</div><div class="col-2">251</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）herunterと同じく、「容易」の意</div><div class="col-2">251</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）herab=</div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）auf ～ herab-</div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）heran=（搬動的）  herbei</div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）heran=züchten</div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）時と共に…</div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）空間的  heran: herzu: hinzu.</div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）herauf= heraufbeschwören: conjure up.</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）her<u>auf</u> 北へ  北へか、近くかは疑問</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）die Strße <u>herauf</u>  近づ（英のup）</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）空間的   Die Kerne herausnehmen.</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）heraus-fordern  挑み出す</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）言葉  herausstottern</div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）heraus-arbeiten</div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）heraus=  結果</div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）sich herausheben.</div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）hereinbrechen</div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）hernieder</div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）herüberklingen</div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）herüber</div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）herüber=</div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）sich mit ～ herum=</div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）umher=の意のherum=</div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）an....herum.</div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（37）sich herum=quälen.</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（38）sich herumsprechen, etc.</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（39）umを強めてherum=  （herumwerfen, das Ruder）<br>グイとカーブを切る  大衝突する<br>Kuswechsel</div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（40）「ごろごろしている」</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（41）herum  あの手この手と<u>いろいろと</u><br>ああでもない、こうでもないとかれこれ、<br>なんだかんだ、</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（42）回避のherum=</div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（43）普通のherum=（空間的）</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（44）sich mit jm. herumkeifen.</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（45）herunter=schrauben  程度を落とす、<br>引き下げる、（auf=の反対）</div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（46）herunterschneiden  切り取る</div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（47）her-  daher-  ab-  herb-   MEM0</div><div class="col-2">270</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（48）［ein Lied herunter=fiedeln］</div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（49）hernieder=</div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（50）siegreich <u>hervorgehen</u> aus ～  結果の表現</div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（51）hervor=   英:forth</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（52）herzu （=gelaufen kommen）</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2">78-26R</div><div class="col-8">hin</div><div class="col-2">280-324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）über ～ hin</div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）auf ～ hin=</div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）neben ～<br>hinter  herを<u>hin</u>で<br>vor</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）hin und her</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Denken hin, Denken her.     新</div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Göttin <u>her</u>, Göttin <u>hin</u>,</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）～ hin, ～ her.</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>～ von ～ hinten</u>    特</div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）man riet hin, man riet her</div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Wir denken <u>hin</u>, wir denken <u>her</u>.</div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）空間的（ズラリと）</div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）空間的移動のhin （along!）</div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）貝体的動作のhin</div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）貝体的動作の<u>hin</u>  sich hinstellen  完了形</div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）貝体性表現のhin=  hin-halten, usw.</div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）死す、滅びる。</div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）［Hin=gabe］</div><div class="col-2">295</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）hinnehmen.</div><div class="col-2">295</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）hinleben.  <u>ぼんやりと</u></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）時間の経過   Dahinleben.</div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）［leicht <u>hin</u>=skizzieren］</div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）vor sich hin=</div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）die Straße hinab=   -hinunterと同じ</div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）接近・離去の際の表現とhinunter, herauf</div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）hinab=</div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）hinab（南）</div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）hinan</div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）die Straße <u>hinauf</u></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）hinauf （北へ）</div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）普通のhinaus</div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）hinaus=schieben等</div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）da hinaus   dort hinaus  par là</div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）Lativisch    <u>sich</u> hindurch</div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）hindurch-</div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）sich hineingewöhnen （Lativisch:）</div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）<u>in</u> die Zukunft <u>hinein</u>. （blindlings）</div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（37）hintan helten （postpono） ----setzen</div><div class="col-2">314</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（38）非分離のhinter=  hintergehen （frauder la</div><div class="col-2">315</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">loi sur le société, etc）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（39）分離するhinter（後方へ）</div><div class="col-2">315</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（40）hinüber-</div><div class="col-2">315</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（41）hinüber</div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（42）hinunterと四格   herunter</div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（43）見わたすvistaの方向、遠望の表現<br>die Straße hinunter=型</div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（44）hinvor-</div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（45）über etw. hinweg=［konkr. u, abstr.］</div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（46）hinweg=fort, weg.</div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（47）den Abend <u>ver</u>trinkenのver-と同用法の<u>hinweg</u></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（48）hinzu=をhinまたはzu=の意に［稀］</div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（49）hinzu-</div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2">78-27R</div><div class="col-8">hoch-</div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）hoch=  =empor=</div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2">78-28R</div><div class="col-8">home</div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［英］home</div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2">78-29R</div><div class="col-8">inne</div><div class="col-2">327-329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）inne=halten（止める、）</div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）zwischen staatlich （international）</div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）inne=wohnen.</div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）inter=</div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2">78-30R</div><div class="col-8">Kon=  kund=  leer-  lieb-</div><div class="col-2">330-331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Kon  総体</div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）kund=</div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）leer laufen    in Leerlauf geraten kommen</div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）lieb=  liebgewinnen.</div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2">78-31R</div><div class="col-8">los=</div><div class="col-2">332-333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）auf ～ los=</div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）los = frei.</div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）los-   初める。始める</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［darauf］los=</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2">78-32R</div><div class="col-8">miß=</div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）miß=  ［仏］désapprouver （mißbilligen）</div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2">78-33R</div><div class="col-8">mit=</div><div class="col-2">335-340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Mit = mit sich  mit nehmen  mitbringen</div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）mitbestimmen</div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）einem übel <u>mitspielen</u></div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）mit=</div><div class="col-2">337</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>mit an</u>.  <u>mit unter</u>-</div><div class="col-2">337</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Mitbürger</div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Mitbürger</div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）mit ～ </div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2">78-34R</div><div class="col-8">nach=</div><div class="col-2">341-371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）服従・謙遜  nachgeben</div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Nachklang.  Nachruhm.   Nachgeschmack</div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）nachdenken, nachsinnen</div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）nach=schlagen 検べる</div><div class="col-2">346</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）補充のnach.  nachfüllen,</div><div class="col-2">348</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）<u>nach</u>-ahmen,  <u>nach</u> sagen,</div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）nachsagen.  nachrüen.  噂の</div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）aus zweiter Hand.   Sekundarität,<br>二次的、継発的  -nachträglich-</div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）追って   mit Dativ</div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）後から（空、時、ともに）  nach-drängen</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）nachstehen（劣る）と三格</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2">78-35R</div><div class="col-8">neben  ob=  ober=  nieder    preis-  pro=<br>rat-  raus  rück-  schuld  stand-<br>statt-  still-</div><div class="col-2">372-385</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）= bei   Nebensonne.  Nebenkaiser.</div><div class="col-2">372</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）nicht=</div><div class="col-2">372</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）niedermetzein  niederkonkurrieren.</div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）（niederkonkurrieren.）</div><div class="col-2">375</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）obwalten</div><div class="col-2">376</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）0bertöne.</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）nieder=legen［下に］</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［英］ para= pseudo= presque</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）preis=bieten</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）pro    prorussisch  antirussisch</div><div class="col-2">380</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）rat-schlagen</div><div class="col-2">380</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）raus（hinaus）  俗</div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）rück-</div><div class="col-2">382</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）schuld</div><div class="col-2">383</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）stand-</div><div class="col-2">383</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）statt</div><div class="col-2">384</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）still-  stillegen,  stillsetzen.</div><div class="col-2">385</div></div></div>');