document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">79-1R</div><div class="col-8"><a href="../079/s0001.html">über</a></div><div class="col-2">1-43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0001.html">（1）sich uberschneiden</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0002.html">（2）通過する、横切る、渡る  überqueren 非分離</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0002.html">（3）犯す。  überschreiten.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0003.html">（4）überprüfen.（一渡ざっと吟味する）  非分離</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0005.html">（5）<u>mit Dativ.</u> （Ant.:<u>unter</u>=）</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0005.html">（6）schlägt über［schlägt <u>um</u>］  「転」覆のüber</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0005.html">（7）餘冗のüber  Ueberbleibsel übrig.</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0006.html">（8）超過する   geht über--hinaus.  非分</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0007.html">（9）溢れる、超す。（分離、自働）</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0009.html">（10）移動、移転  （hinüber）  分離</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0011.html">（11）über=morgen.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0011.html">（12）序列の表現一般  übernächst.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0012.html">（13）分離  かぶせる、 darüber</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0013.html">（14）…で表面を俺ふ。  überschattet. （mit AKK.）</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0014.html">（15）上に冠せる（他働詞）</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0014.html">（16）（被る、カブセル）  非分離</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0015.html">（17）überfahren（轢く）</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0015.html">（18）über=dauern  時間的  überleben,</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0016.html">（19）übertreffen  …し負かす。凌駕する。<br>超す、凌ぐ。</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0027.html">（20）圧倒のüber=  非分離</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0028.html">（21）überkommen kommen über<br>其他「襲ふ」の表現一般</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2">79-2R</div><div class="col-8"><a href="../079/s0044.html">über</a></div><div class="col-2">44-86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0044.html">（1）über=iaschen  不意に</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0046.html">（2）sich überstudieren.  非分</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0054.html">（3）überlassen［任す］  移譲・譲渡・etc.</a></div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0055.html">（4）蹟く・倒す［失敗の意］  sich über-schnappen</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0059.html">（5）über（過）と形容詞、名詞  überkultiviert.</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0072.html">（6）「超」党派的、等</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0077.html">（7）überstunden（超過）  machen, leisten</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0077.html">（8）期限の切れた： überfällig</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0078.html">（9）…し逃がす。  übersehen.</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0082.html">（10）überfliegen［他働、非分離］</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0082.html">（11）überfliegen  さっと、ざっと</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0083.html">（12）überhängende Zweige. 分離</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0083.html">（13）überstehen（はみ出している）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0084.html">（14）切り換へる  über=<br>乗り換へる</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0085.html">（15）着物（上にかぶせて）</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0085.html">（16）übereinstimmen.  übereinkommen.</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0086.html">（17）über=  溢れる  von--, über--  分離</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0086.html">（18）überhandneumen</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">79-3R</div><div class="col-8"><a href="../079/s0087.html">um</a></div><div class="col-2">87-103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0087.html">（1）um-gehen  世に行われる、等</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0087.html">（2）場所を移す。（<u>ver</u>setzen）</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0088.html">（3）zu etw. umlüngen［変更］</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0094.html">（4）um=lernen.  自働的</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0094.html">（5）取り巻く （Untr.）</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0095.html">（6）取りまく。  非分離</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0098.html">（7）纏ふ、等（装身具に関するもの）  分離</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0099.html">（8）廻避する、めぐる（運動）  非分離</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0099.html">（9）抱く、包む、等</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0100.html">（10）避ける  周囲を廻る（Untr.）</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0101.html">（11）sich um=drehen.  （Tr.）  herum</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0102.html">（12）sich nach ～<u>umtun</u></a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0102.html">（13）ぶっくら返る</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0103.html">（14）umbringen  殺す</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0103.html">（15）umher.</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">79-4R</div><div class="col-8"><a href="../079/s0104.html">un=</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0104.html">（1）積極概念化のun= （nichtとの相違）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2">79-5R</div><div class="col-8"><a href="../079/s0105.html">inter=</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0105.html">（1）inter=  （相互に）</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2">79-6R</div><div class="col-8"><a href="../079/s0106.html">unter</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0106.html">（1）unterzeichnen</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2">79-7R</div><div class="col-8"><a href="../079/s0107.html">unter</a></div><div class="col-2">107-146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0107.html">（1）unter-mischen等\'</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0109.html">（2）unter-winden等  …に掛ける  非分離</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0110.html">（3）einem Dinge unterstellen  非分離</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0123.html">（4）負かす、負かされる、従属せしむ  非分離</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0125.html">（5）unterordnenは<u>分離</u>  （untergeordnet）</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0126.html">（6）<u>unter</u>=bringen  分離</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0127.html">（7）unter: herunter.  分離</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0128.html">（8）ひそかに  unterstüzt.  基礎</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0134.html">（9）ひそかに  mit unterlaufen  分離</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0138.html">（10）<u>unterliegen</u> succumb.to. succomber à  特</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0138.html">（11）untersagen  unterbleiben（否定的）  非分離</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0139.html">（12）unterschlagen  横領する  非分離</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0140.html">（13）<u>空間的</u>（分離）  unter-ge-stützt（下から）</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0141.html">（14）順列としての下位  <u>unter</u> kühlt［:überhitzt］</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0146.html">（15）Unter-mieter.  間借り、（問貸し）</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2">79-8R</div><div class="col-8"><a href="../079/s0147.html">up</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0147.html">（1）up 近づく</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0147.html">（2）英 up</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">79-9R</div><div class="col-8"><a href="../079/s0148.html">ur=</a></div><div class="col-2">148-149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0148.html">（1）ur=  原、本、元</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2">.</div><div class="col-8"><a href="../079/s0149.html">（2）ur=  sehr  urkomisch</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">79-10R</div><div class="col-8"><a href="../079/s0150.html">ver</a></div><div class="col-2">150-194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0150.html">（1）sich <u>verhalten</u>.（拉系語との関係）</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0150.html">（2）参考ver=</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0151.html">（3）ver= statt zer=  Süddeutsch--</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0151.html">（4）versechsfachen</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0152.html">（5）罵詈等の際の無意味なver=</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0153.html">（6）verdammen  verfluchen</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0153.html">（7）verdammt!</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0154.html">（8）－－－鍍金する</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0155.html">（9）ver=+形容詞（…化）</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0155.html">（10）ver=+形容詞比較級</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0156.html">（11）Stups--verkatert</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0157.html">（12）…化する。  verstaatlichen</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0166.html">（13）［仏］-fier  -iser   torréfier（le café）</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0166.html">（14）etwas verpassen</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0167.html">（15）［sich in eine Person <u>ver</u>=lieben］…し呆けた</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0171.html">（16）sich ver=irren</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0184.html">（17）誤る=ver  ［sich ver=sprechen］</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0192.html">（18）問違へる。迷フ。</a></div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2">79-11R</div><div class="col-8"><a href="../079/s0195.html">ver</a></div><div class="col-2">195-233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0195.html">（1）ver-stehen  ver = vor</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0196.html">（2）駄目にする。  verpfuschen,  verderben.</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0201.html">（3）versinken,  沈み去る。（陥入る）</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0201.html">（4）悪い意一般</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0202.html">（5）［ver=Wöhnen］悪くする（A）</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0204.html">（6）悪くなる、悪くする（B）  名詞より</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0204.html">（7）［ver=größern］</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0205.html">（8）［einen Abend <u>ver</u>=trinken］</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0211.html">（9）消耗・消費</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0212.html">（10）verhandeln  手ばなす  喪失のver</a></div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0213.html">（11）ver=</a></div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0213.html">（12）融合・混乱、等のver=  verwurzelt.</a></div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0216.html">（13）結合、接合  溶接</a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0216.html">（14）消滅のver=   （自働詞）  <u>ぼやける</u></a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0220.html">（15）消費（konsumtion）  ［ver=geuden］<br>使ひ果す。（金）</a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0224.html">（16）<u>sich</u>....<u>ver</u> ～ （云々し盡す）</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0224.html">（17）zer=型  verschlafen. （慰め去る）</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0226.html">（18）verschwitzen  <u>忘れ</u>る等</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0226.html">（19）ver=drängen  ［=weg］</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0227.html">（20）人手に渡す  verheiraten  vergeben</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0227.html">（21）<u>sich</u> dem Teufel <u>verschreiben</u>.  再帰</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0228.html">（22）lernen → <u>ver</u>lernen.</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0228.html">（23）隠す、塞ぐ、俺ふ（他）  消える（自動）</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0231.html">（24）南方方言er=の代りに=ver</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s023Z.html">（25）餘計なver=とieren語尾（古及び方言）</a></div><div class="col-2">23Z</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0232.html">（26）死す（ver-）</a></div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0233.html">（27）特項verstehenについて</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2">79-12R</div><div class="col-8"><a href="../079/s0234.html">voll-</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0234.html">（1）非分離のvoll</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0234.html">（2）voll=  充たす</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2">79113R</div><div class="col-8"><a href="../079/s0235.html">vonstatten-</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0235.html">（1）vonstatten-</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2">79-14R</div><div class="col-8"><a href="../079/s0236.html">vor-</a></div><div class="col-2">236-266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0236.html">（1）Vorstellung  表象  哲学的見地より<br>→ für sichと<u>vor</u>と（Hege）</a></div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0236.html">（2）Vorgeschmack</a></div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0237.html">（3）Vorurteil</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0237.html">（4）Vorrecht</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0238.html">（5）空間的vor=  前方へ（nach） vorn  vorstoß</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0240.html">（6）普通の時間的vor=  Vorschuß</a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0241.html">（7）<u>vor</u>=gestern</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0241.html">（8）非難の意のvor=</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0242.html">（9）vorzeigen 出して見せる。</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0243.html">（10）Vorwurch, Probrem, Projekt等に関する参考  特</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0243.html">（11）vorverlegen.  vordatieren.</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0244.html">（12）vor=handen  vorfindlich</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0245.html">（13）vor=wiegen</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0247.html">（14）mit Dativ （時間的に）</a></div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0253.html">（15）dem Werke vorstehen（三格支配）</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0253.html">（16）vor: hervor</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0254.html">（17）vorbinden（三格と四格）  具体的</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0254.html">（18）eine Rose <u>vor</u>stecken（着物に）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0255.html">（19）sich etw. vorsetzen</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0256.html">（20）面前につける意   <u>einem</u> <u>etwas</u> <u>vor</u>schreiben.</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0258.html">（21）閉ざす =vor =einen Vorhang vor=ziehen.</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0259.html">（22）［vor=täuschen］上べだけ（四格）［machen］型</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0261.html">（23）［vor=lassen］</a></div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2">79-15R</div><div class="col-8"><a href="../079/s0267.html">vor=</a></div><div class="col-2">267-299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0267.html">（1）…云々して見せる  vor=singen （zur Schau）</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0274.html">（2）vorletzt.</a></div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0274.html">（3）vor=ziehen （=Vorzug geben）</a></div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0275.html">（4）vor=  voranと同じ</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0275.html">（5）Unsere Fahne flattert uns voran!</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0276.html">（6）voranと三格</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0278.html">（7）voran=  vorwärts.</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0279.html">（8）vorauf. voran. voraus.</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0280.html">（9）<u>vorauf</u>.</a></div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0281.html">（10）vorausと三格</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0284.html">（11）an einander vorbei etc.</a></div><div class="col-2">284</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0287.html">（12）fehl=, daneben  無視、不注意。</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0291.html">（13）vorher-</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0291.html">（14）支配格の問題  vorüber</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0293.html">（15）（普通の場合）</a></div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0295.html">（16）vorweg=  vorweg-nehmen.</a></div><div class="col-2">295</div></div>');
document.write('<div class="row"><div class="col-2">79-16R</div><div class="col-8"><a href="../079/s0300.html">weg-</a></div><div class="col-2">300-312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0300.html">（1）…し去る（消す）  <u>Lativisch</u></a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0300.html">（2）über ～ weg.  無視</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0301.html">（3）weg-  普通</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0301.html">（4）von ～ weg  ab.</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0302.html">（5）frisch weg （完了、理解、解決、片づけ、獲得）</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0310.html">（6）云々してのける［片づける。］</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0312.html">（7）weg=［云々してのける］</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2">79-17R</div><div class="col-8"><a href="../079/s0313.html">weiter</a></div><div class="col-2">313-317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0313.html">（1）逓送のweiter=</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0314.html">（2）［英］on</a></div><div class="col-2">314</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0317.html">（3）weiterkommenやって行ける</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2">79-18R</div><div class="col-8"><a href="../079/s0318.html">wett</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0318.html">（2）wett（quitt）</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0318.html">（3）</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2">79-19R</div><div class="col-8"><a href="../079/s0319.html">wider-  wieder</a></div><div class="col-2">319-328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0319.html">（1）widerraten, widerlegen.</a></div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0319.html">（2）mit Dativ.</a></div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0320.html">（3）wieder= （元の位置へ）  = zurück=</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0322.html">（4）wieder: aufs neue.</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0322.html">（5）wieder=erkennen</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0322.html">（6）wiederhallen等</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0323.html">（7）Wieder=zumzweiten Male</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0326.html">（8）<u>かヘす</u></a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0328.html">（9）<u>wieder auf</u></a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2">79-20R</div><div class="col-8"><a href="../079/s0329.html">wohl-</a></div><div class="col-2">329-331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0329.html">（1）wohl-</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2">79-21R</div><div class="col-8"><a href="../079/s0330.html">zer-</a></div><div class="col-2">330-331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0330.html">（1）zerfallen.  zerwürfnis.</a></div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0330.html">（2）zer=</a></div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2">79-22R</div><div class="col-8"><a href="../079/s0332.html">zu-</a></div><div class="col-2">332-378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0332.html">（1）zuwenden  向ける  ［指向のzu］</a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0332.html">（2）Dem A1kohol <u>zusprechen</u></a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0332.html">（3）sich etwas <u>zulegen</u>等</a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0333.html">（4）<u>Hier noch jemand zugestiegen</u>?<br>----sagt der Schaffner.</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0334.html">（5）zu= =  hinzu=</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0338.html">（6）承認、承諾のzu   Zu-sage.  Zu-stimmung.</a></div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0339.html">（7）jemandem etwas <u>zuschieben</u></a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0341.html">（8）Den Rücken <u>zu</u> kehren型   mi Dativ.</a></div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0342.html">（9）zutrinken等</a></div><div class="col-2">342</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0344.html">（10）zuschauen  zuhören</a></div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0344.html">（11）ZU=RATEN  （Ant.:<u>ab</u>-raten）</a></div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0345.html">（12）附與する。許す。承諾する。配属せしめる。</a></div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0347.html">（13）einem etwas zu=teilen. 與へる</a></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0356.html">（14）Zumuten  Zutrauen</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0358.html">（15）（scharf）<u>zu</u>!</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0361.html">（16）zuführen</a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0362.html">（17）zu-leiten（廻す）  zu-gehen（廻わされる）<br>zu-kommen lassen</a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0365.html">（18）dem Untergange <u>zueilen</u>（mit Dativ）</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0367.html">（19）auf ～ zu=［…に向かって］</a></div><div class="col-2">367</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0368.html">（20）閉づ  sich die Ohren zu-halten.</a></div><div class="col-2">368</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0374.html">（21）［einem zu=flüstern］</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0376.html">（22）zubeleiten （zu=zurecht）  u-schneiden.<br>zu-stutzen</a></div><div class="col-2">376</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0378.html">（23）Zukost   Zukost（Beikost）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0378.html">（24）zutunlich, 等。</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2">79-23R</div><div class="col-8"><a href="../079/s0379.html">zugrunde=</a></div><div class="col-2">379-406</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0379.html">（1）zugrunde=</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0379.html">（2）zurecht</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0386.html">（3）zurechtweisen（たしなめる）</a></div><div class="col-2">386</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0386.html">（4）zurück</a></div><div class="col-2">386</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0387.html">（5）nach hinten （rückwärts）</a></div><div class="col-2">387</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0389.html">（6）zurückstellen</a></div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0389.html">（7）zurück=   開く   Vorhang,</a></div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0389.html">（8）一致のzusammen</a></div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0390.html">（9）<u>創造</u>、<u>捏造</u>する。<br>ein Gedicht zusammenreimen, etc.</a></div><div class="col-2">390</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0396.html">（10）粉砕、壊滅、等。<br>über den Hafen zusammenschmelzen</a></div><div class="col-2">396</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0397.html">（11）zusammenstürzen</a></div><div class="col-2">397</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0398.html">（12）総身</a></div><div class="col-2">398</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0399.html">（13）Nimm dich <u>zusammen</u>!</a></div><div class="col-2">399</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0400.html">（14）集める（具体的）</a></div><div class="col-2">400</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0402.html">（15）sich zusammennehmen.  収握</a></div><div class="col-2">402</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0403.html">（16）zusammen legen 畳む、収縮</a></div><div class="col-2">403</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0403.html">（17）収縮のzusammen</a></div><div class="col-2">403</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0404.html">（18）発生のzusammen</a></div><div class="col-2">404</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0404.html">（19）zuteil （werden,等）^404</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0405.html">（20）zuvor</a></div><div class="col-2">405</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0406.html">（21）zuwege-</a></div><div class="col-2">406</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0406.html">（22）zuwider=wider（そむく、反する）</a></div><div class="col-2">406</div></div>');
document.write('<div class="row"><div class="col-2">79-24R</div><div class="col-8"><a href="../079/s0407.html">zwischen=</a></div><div class="col-2">407-408</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0407.html">（1）zwischenstaatlich = international</a></div><div class="col-2">407</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../079/s0408.html">（2）zwischenschalten （Musikstunde）</a></div><div class="col-2">408</div></div></div>');