document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">87-1R</div><div class="col-8"></div><div class="col-2">1-2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）besuchen</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Der Teufel verführt den Menschen.</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2">87-2R</div><div class="col-8"></div><div class="col-2">3-8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Rom Tod Rot Kot Plan</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）定冠詞と名詞   begegnen, treffen,</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Das Pferd <u>rennt</u>.</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Sie <u>weint</u>.</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）antworten, arbeiten</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）動詞の人称変化のみ。 Ich danke.</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）die Frage stellen.</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=er, =el   Ich bedaure.</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）名詞の変化 （単数）<br> Das Wasser löscht das Feuer.</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Religion is the opium of the people.</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2">87-3R</div><div class="col-8"></div><div class="col-2">9-29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）人称変化、語尾の不規則  zweifeln.</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）satteln   schniegeln.</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）arheiten-  antworten  型</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）rechnen型</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）hassen型</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）其の他のZischlaute  tanzen wünschen</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）定冠詞と格変化<br> Der Krieg zerstört die Kultur.</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）弱変化男性  Christ.</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）不定冠詞  Ein Zufall rettet oft das Leben<br> des Menschen.</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）無冠詞と形容詞   In <u>schlechtem Kleid</u> wohnt<br>oft auch Weisheit.</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）複数形  Das Mensch ist das Maß aller Dinge.</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）複数形  Ein Friede ist besser als<br> zehn Siege.</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）形容詞の変化<br>music is an international language.</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）形容詞の名詞化  Der Arzt sagt <u>dem Kranken</u><br> nie die Wahrheit.</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）物主代名詞  Der Mensch ist Produkt <u>seiner</u></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">Umgebung.</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）人称代名訶二格  Er <u>bedarf</u> meiner.</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）受働  Radium wurde vor genau 80 Jahren<br> von Professor Curie entdeckt.</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）um....zu卜不定句</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）zuを伴ふ不定法</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）物主形容詞  Man kann mehr von seinen<br> Feinden als seinen Freunden lernen.</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）話法助動詞  Ich <u>muß</u> mich durch<br> Privatunterrrcht einähren.</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）分離動詞  Wir b<u>rachen</u> vor Morgengrauen auf.</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）［分離動詞語彙］ Diese Krankheit <u>steckt an</u></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）過去形</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）現在完了  seinとhaben<br>Das Salz <u>ist kristallisiert</u>.</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）再帰動詞  Der ganze Alltag spiegelt sich<br> im Tagebuch.</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）比較級・最高級  Das Wasserstoffgas ist<br> <u>14 mal leichter</u> als Luft.</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）定形倒置； Wenn=Satzの部</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）冠飾句</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）関係代名詞</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）語順説明用短文例</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）G0LDENE WORTE</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）Strom, Fuß, Bach.</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）テキス卜着想</div><div class="col-2">29</div></div></div>');