document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">87-1R</div><div class="col-8"><a href="../087/s0001.html"></a></div><div class="col-2">1-2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0001.html">（1）besuchen</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0002.html">（2）Der Teufel verführt den Menschen.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2">87-2R</div><div class="col-8"><a href="../087/s0003.html"></a></div><div class="col-2">3-8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0003.html">（1）Rom Tod Rot Kot Plan</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0003.html">（2）定冠詞と名詞   begegnen, treffen,</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0004.html">（3）Das Pferd <u>rennt</u>.</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0004.html">（4）Sie <u>weint</u>.</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0005.html">（5）antworten, arbeiten</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0005.html">（6）動詞の人称変化のみ。 Ich danke.</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0007.html">（7）die Frage stellen.</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0007.html">（8）=er, =el   Ich bedaure.</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0008.html">（9）名詞の変化 （単数）<br> Das Wasser löscht das Feuer.</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0008.html">（10）Religion is the opium of the people.</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2">87-3R</div><div class="col-8"><a href="../087/s0009.html"></a></div><div class="col-2">9-29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0009.html">（1）人称変化、語尾の不規則  zweifeln.</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0011.html">（2）satteln   schniegeln.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0012.html">（3）arheiten-  antworten  型</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0013.html">（4）rechnen型</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0013.html">（5）hassen型</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0014.html">（6）其の他のZischlaute  tanzen wünschen</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0014.html">（7）定冠詞と格変化<br> Der Krieg zerstört die Kultur.</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0015.html">（8）弱変化男性  Christ.</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0015.html">（9）不定冠詞  Ein Zufall rettet oft das Leben<br> des Menschen.</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0015.html">（10）無冠詞と形容詞   In <u>schlechtem Kleid</u> wohnt<br>oft auch Weisheit.</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0016.html">（11）複数形  Das Mensch ist das Maß aller Dinge.</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0018.html">（12）複数形  Ein Friede ist besser als<br> zehn Siege.</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0019.html">（13）形容詞の変化<br>music is an international language.</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0019.html">（14）形容詞の名詞化  Der Arzt sagt <u>dem Kranken</u><br> nie die Wahrheit.</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0019.html">（15）物主代名詞  Der Mensch ist Produkt <u>seiner</u></a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0019.html">Umgebung.</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0020.html">（16）人称代名訶二格  Er <u>bedarf</u> meiner.</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0020.html">（17）受働  Radium wurde vor genau 80 Jahren<br> von Professor Curie entdeckt.</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0021.html">（18）um....zu卜不定句</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0021.html">（19）zuを伴ふ不定法</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0022.html">（20）物主形容詞  Man kann mehr von seinen<br> Feinden als seinen Freunden lernen.</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0022.html">（21）話法助動詞  Ich <u>muß</u> mich durch<br> Privatunterrrcht einähren.</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0023.html">（22）分離動詞  Wir b<u>rachen</u> vor Morgengrauen auf.</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0024.html">（23）［分離動詞語彙］ Diese Krankheit <u>steckt an</u></a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0024.html">（24）過去形</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0024.html">（25）現在完了  seinとhaben<br>Das Salz <u>ist kristallisiert</u>.</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0025.html">（26）再帰動詞  Der ganze Alltag spiegelt sich<br> im Tagebuch.</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0025.html">（27）比較級・最高級  Das Wasserstoffgas ist<br> <u>14 mal leichter</u> als Luft.</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0026.html">（28）定形倒置； Wenn=Satzの部</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0026.html">（29）冠飾句</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0027.html">（30）関係代名詞</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0027.html">（31）語順説明用短文例</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0028.html">（32）G0LDENE WORTE</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0028.html">（33）Strom, Fuß, Bach.</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../087/s0029.html">（34）テキス卜着想</a></div><div class="col-2">29</div></div></div>');