document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">86-1R</div><div class="col-8"></div><div class="col-2">1-17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）男性で=nの複数（必ずしも弱に非ず）</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）仏英=ard</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）-ard</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［仏］ouragan=Orkan</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）［仏］樹名=ier</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=er式NOMEN AGENTIS</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）二綴り語の=e式複数</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）純独乙系語の=at</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）外来語の複数語尾=enに関する参考事項</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Satz-Sätze</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）eごの複数に関するMütter式</div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=E=  同音E式</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）例外Charakter =e</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Aal - Aale と Saal - Säle</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）=e式複数参考</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）E式の編音、不変音に関する参考。</div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=E  Plätze.</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Kranz,  Kränze</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2">86-2R</div><div class="col-8"></div><div class="col-2">18-37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）外来語の男性は困雜！  der Ballast等</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>EN式男性名詞</u>に関す参考文例</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）男と中の=en</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）男性弱変化</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）-ist.  -ant.  -loge 石の=it等は強弱不明</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=eseの弱変化男性  Chinese.</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）弱変化男性</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）男性弱変化名詞  分類し難きものの例 </div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）男性弱変化名詞（外来語の）=eに就いて</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）［仏］=logueなどと=log<u>iste</u>など</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）能働者と受働者の表現</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2">86-3R</div><div class="col-8"></div><div class="col-2">38-78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Gevatter</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Konsul.  pl. =Konsul-n型</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）der Ras<u>en</u> m.</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）der Rasen等の参考</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）der Gefallen対das Gegallen</div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）語幹男性名詞（動作名詞）</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）語幹男性名詞</div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）語幹動詞［<u>男</u>］</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）男性語幹名詞は～e式複数形</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）語幹男性名詞（擬音詞型）</div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）der Text</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）拉系語の平行現象</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）語幹男性例外（=r多し）</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［仏］</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）［仏］ =is</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）［男］el, =erのNomen actionis</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=mと性</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）=CKと性</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）=ianer （=ide）</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=er  nomen agentis</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）［G0T］</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）=or</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2">86-4R</div><div class="col-8"></div><div class="col-2">79-115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=erの俗間用法</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=er  酒名</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Sommefrisch<u>ler</u></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）=lingの語尾</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=ing</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）-em, am</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）-ich  -ch</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=ig =ich</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Grob<u>ian</u>.  Dummr<u>ian</u> 等</div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=bold.</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）-s, m.</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=0R.</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）=iker</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）=ikus.</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=iker（病者名もあり）</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）累系の=or</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=or  =eur</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）der Motoren  Motore</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=eur</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）=orの語尾</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）西班牙系=dor</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）［英］=ite, =an</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=ist</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）=ast</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）仏式  <u>Atelier</u>型</div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）=<u>ismus</u></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）=Ismus.</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2">86-5R</div><div class="col-8"></div><div class="col-2">116-154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）病名等の=ismus.（≒manie）</div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）MECHANISMUS等</div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）=smusの複数形</div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）=<u>us</u></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Kasus.  Casus</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）拉丁第四変化形： 具体象名詞  =us</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）ululatus.</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［仏］rut, m.</div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）us 語例</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）<u>Iltis</u>. <u>Ethos</u>, Logos</div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Autobus, ～ sse</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1Z）0tto→ Ottonen→</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=en［外来語］ （複数形）</div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Primas, m.</div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）中性の=<u>at</u></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）弱変化男性の歴史的関係</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=ist（と他型との関係）</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）男性の=at（弱）</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）Advokat  （Prädikat）</div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Schogun<u>at</u></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=tva, n.</div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）=antと=at［能働と受働］</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）=log, =graph, =oph, =nom,等</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）地名 → 人名 ～</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=et, =ot, =it, =yt, =eut, =aut, =ast</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）［英］=ite</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）弱変化男性=Summand型</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）=antと=entの男性</div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2">86-6R</div><div class="col-8"></div><div class="col-2">155-164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=ans, =ens</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=ar, =är</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）中性の=ier</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Parlament<u>a</u>rier</div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）［英］Blackmarketeer</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）0ffizier</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Bankier型</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=eur. =ieren → =eur.</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）動詞代りの名詞  He is a sound sleeper.</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=inで男性（宝石名）</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Bro<u>sam</u> Gehor<u>sam</u></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）石の名一般  Obsidian, m. 黒曜石</div><div class="col-2">164</div></div></div>');