document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">88-11R</div><div class="col-8"></div><div class="col-2">1-12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Ausprägung   sich herausbilden<br>（Vollentwicklung）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）文法形態</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）（1）定形はそれ自体が文章である。</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）（2）「動詞」と「定形」とはちがう。</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）（3）機構要求が動詞の本質なること。</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）構出と構入</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）文法形態は意味関係に関係なし</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）動詞に構入される文肢の図示法（?）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）支配</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）規定とは</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）冠詞といふ現象</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）文法形態と意味形態との齟齬</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）-ADNOMINAL- Apposition.</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Adnominal規定の分類</div><div class="col-2"></div></div></div>');