document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="/img/001/S0007.gif" class="luminous"><img src="/img/001/S0007.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<div style="width:3em;border:solid 1px #000;text-align:center;float:left;">蘭語</div><p style="clear:both;">Die Verwandtschaftsnamen werden im Holl. oft als Eigennemen gebraucht. Im Deuschen fügt man in diesem Fall gern den bestimmten Artikel hinyu, im Holl. nicht.</p>');
document.write('<div style="width:40%;float:left;">Der Vater ruft.<br>Ich gehe zum Onkel.<br><div style="width:4em;float:left;">　</div>zur Tante.<br>Das habe ich vom Großvater bekommen:</div><div style="width:40%;float:left;">vader roept.<br>ik gaa naar oom.<br><div style="width:2.5em;float:left;">　</div>naar tante.<br>Dat heb ik van grootvader gekregen.</div>');
document.write('<div style="clear:both;"></div><br><br><br>');
document.write('<h3 style="clear:both;">Hildeの二格<br>Hild<u>en</u>等</h3><br><div style="width:4em;border:solid 1px #000;text-align:center;float:left;">MHD</div><ol style="width:70%;float:left;"><li>dô sprach diu <u>Hilden</u> tohter:<br>(Kudrun 1632)</li></ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');