document.write('<div class="container">');
document.write('<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('      <a href="/img/001/S0001.gif" class="luminous"><img src="/img/001/S0001.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<h2>固有名詞でもあり普通名詞でもあり:</h2>');
document.write('<ol>');
document.write('<li>平原名（地理）→</li>');
document.write('<li>帝王名</li>');
document.write('<li>風名</li>');
document.write('<li>人名</li>');
document.write('</ol>');
document.write('<h2 style="margin-top: 2em;">平原</h2>');
document.write('<p>Die Pampas. Die Llianos. Die Steppe. Tundra, -en. Wüste,</p>');
document.write('<ol>');
document.write('<li>Die Gauchos reiten tagelang über die <u>Llianos</u>.<br>南米アマゾン以北の平原</li>');
document.write('</ol>');
document.write('<p>ヤノス（中）<br>ジャノス（南）<br>リャノス（北）</p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');