document.write('<div class="container">');
document.write('﻿﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('      <a href="/img/001/S0002.gif" class="luminous"><img src="/img/001/S0002.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<h2>名詞 固有名詞</h2>');
document.write('<p>12. ging Deutschlandの問題は形容の●●●●●●●<br>13.「誰彼」の意に任意の固有名詞を用ふ<br>－指示用</p>');
document.write('<ol>');
document.write('<li>固有の［1］</li>');
document.write('<li>Theseus\\\' Stadt等は「名詞、各変化」</li>');
document.write('<li>不定冠詞の場合は不定冠詞の項</li>');
document.write('<li>ein Davinci等</li>');
document.write('<li>Durch das Hessische等</li>');
document.write('<li>固有名と定冠詞（地名、人名）</li>');
document.write('<li>à la Kaiserの問題も加ふ可し。</li>');
document.write('<li>mendeln, marsen等、動詞</li>');
document.write('<li>「ein Bechstein m, ピヤノ」等は「性數」</li>');
document.write('<li>固有名として普通名を假に用ひる場合<br>（Freund Hain等の項）（Drei Käsehah等）</li>');
document.write('<li>固有人名のpl.は複數の冊</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');