document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="/img/001/S0013.gif" class="luminous"><img src="/img/001/S0013.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<p>');
document.write('=er');
document.write('</p>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">NB</div>');
document.write('<p>國名ではSchweizのみが～erか？</p>');
document.write('<ol>');
document.write('<li>Die <u>Schweizer</u> Mount-Everst-Expedition 1952.</li>');
document.write('<li>住民の=erは別紙</li>');
document.write('</ol>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">英</div>');
document.write('<p>America → America<u>n</u></p>');
document.write('<ol>');
document.write('<li>The <u>Incan</u> empire. (Inca, South America)</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');