document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="/img/001/S0010.gif" class="luminous"><img src="/img/001/S0010.gif" alt="" class="mw-100"/></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<p>Jan<u>enser</u> statt Janaer</p>');
document.write('<ol><li>Goethe hat einen leidlich gelungenen Ursuch gemacht, für die Weimarer Literaten und die <u>Janenser</u> Gelehrten einen ausgleichenden mittelpunkt zu schaffen. (Johannes Scherr: Menschliche Tragikomödie)</li>');
document.write('<li>Die 1 <sup>1/2</sup> Jahre in <u>Halle</u> waren für mich eine Zeit schöner förderlicher Arbeit. Für die nötige Erholung sorgte eine rege Gesellingkeit und einiger Sport. Sehr erfreulich awr auch der <u>Hallenser</u> Referendarvverein, in dem wir noch mano mal in studentischer Art fröhlich waren.<br />(Robert Hippel, in "Rechtswissenschaft in Selbstdarstellungen)</li>');
document.write('<p style="margin:1em 0 1em 0">Takaier等、酒名</p>');
document.write('<ol>');
document.write('<li>Den odlen Hochheimer, Bacheracher und Klingenberger gossen sie mit Kübelmässigen Gläsern in Magen hinunter.<br />(Simplizissimus 1. 30)</li>');
document.write('<li>An solchen Tagen floß auf der Hauptwache (Stadtgarde) eiteöl <u>Rüdesheimer</u> und <u>Aßmannahäuser</u> von den vortrefflichsten Jahrgängen, (Heine, Memoiren)</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');