document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="/img/001/S0017.gif" class="luminous"><img src="/img/001/S0017.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('=sche [2]<br>');
document.write('Kant-La Placesche Welttheorie.<br>');
document.write('Weilsche Krankheit ワイル氏病<br>');
document.write('Der Halleysche Komet.');
document.write('<ul><li>Die Magellansche Wolke<br>');
document.write('* Der großertigste der Sternnebel (Spiralnebel) ist die Magellansche Wolke am Südhimmel.<br>');
document.write('südlichen Himmel.</li></ul>');
document.write('<p>PARADIMA</p>');
document.write('Kölnisches Wasser<br>');
document.write('(Eau de Cologne)');
document.write('<ul><li><u>Gabelsbergersche</u> Stenographie<br>辞書より</li></ul>');
document.write('<div style="width:3em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">意味</div>');
document.write('<p>Churchill\'sに対して<u>Churchillian</u>は"チャーチル流の""チャーチル式の"</p>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">英</div>');
document.write('<ol><li>The coup caused whispers of favoritism among <u>Churchill\'s</u> press colleagues; yet behind it lay merely a typical <u>Churchillian</u> display of zest, an odd chance and the quick exploitation of a scrap of casual information.<br>');
document.write('(RD. 1953, feb. A. H. Z. Carr: How to attract good chance)');
document.write('Churchillが記者だったとき、偶然兵の中に手品術を発見して手●を●したこと。</li>');
document.write('<li>Das Möbiussche Band.<br>');
document.write('無限平面 二つに切ってもein Stück.</li>');
document.write('<li>Kardanische Aufhängung<br>');
document.write('（辞典）●ニ</li>');
document.write('</ol>');
document.write('<div style="width:2em;border:solid 1px #000;text-align:center;float:left;margin-right:1em;">NB</div>');
document.write('<div style="float:left;">Hitler=Rede<br>');
document.write('Dulles speech<br>');
document.write('Goethe Wort<br>');
document.write('→（合成語冊）</div>');
document.write('<p style="clear:both;"></p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');