document.write('<div class="container">');
document.write('<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('      <a href="/img/001/S0035.gif" class="luminous"><img src="/img/001/S0035.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<p><strong>Dr Richard Brodführer</strong>, der Herausgeber <u>des</u> im Verlag Karl Alber‚ Freiburg/München‚ erscheinenden, "<u>Orhis Academicus</u>", einer in vierzehn Bänden vorliegenden und auf siebzig Bände vorgesehenen Enzyklopädie‚ ist im Alter von 62 Jahren in Gauting bei München gestorben.</p>');
document.write('<h2>Das Eides Kolumbus型</h2>');
document.write('<p>アリストテレスの提灯？</p>');
document.write('<ol><u><li>Das Sieb des Eratosthenes</u>.<br />');
document.write('Es gibt kein bestimmtes Gesetz, nach welchem die Primzahlen unter den übrigen Zahlen vorkommen. Zu ihrer Ermittlung kann man ein schon im Altertum angewendetes Verfahren gebrauchen. Man schreibt die Zahlen der Reihe nach auf.<br />');
document.write('l 2 3 4 5 6 7 8 9 10<br />');
document.write('11 12 13 14 15 16 17 18 19 20<br />');
document.write('21 22 23 24 25 26 27 28 29 30<br />');
document.write('31 32 33 34 35 36 37 38 39 40<br />');
document.write('41 42 43 44 45 46 47 48 49 50</li>');
document.write('<li> Er (Kant) hat sein Werk gern und wiederholt mit dem <u>des Kopernikus</u> verglichen‚ wie Bacon das seinige mit dem <u>des Kolumbus</u>.<br />');
document.write('(Kuno Fischer, Gesch, de. neuer. Philosophie, Kant I)</li></ol>');
document.write('<div class="borderbox" style="width:3em">例外</div><p>Achilles Ferse (?)</p>');
document.write('<p style="clear:both"></p>');
document.write('<div class="borderbox" style="width:3em">英：</div><p>Achilles\' heel (?)</p>');
document.write('<h2><u>Das Prokrustesbett</u>.</h2>');
document.write('<div class="borderbox" style="width:2em">仏</div><p>le lit de Procuste<br />（Procristeともいふが･･･）</p>');
document.write('<div class="borderbox" style="width:2em">英</div><p>the Procrustean Bed.<br />旅人を床にねかせて、寸法に合はせてちぢめたりのばしたりした話（本名はPalypémonなととぞ）<br />procrustes（意は”のばす者”）<br />Theséeが征伐す</p></p>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');