document.write('<div class="container">');
document.write('﻿<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('<a href="/img/001/S0030.gif" class="luminous"><img src="/img/001/S0030.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<p>Akkusativで=n（2）</p>');
document.write('<ol start="18">');
document.write('<li>Und diese Nachricht vermochte <u>Wernern</u>, sein bischen Armut mit m1r zu teilen. (Minna I. 4)</li>');
document.write('<div style="border: 1px solid #000;width:4em;text-align:center; float:left;margin-right:2em;">MHD</div>');
document.write('<li>daz wir sô kûme lebende sweben in disen tobendeh ümden delst niwan von den sünden und von den untriuwen komen, daz wir <u>Tristanden</u> hân genomen sînen friunden rouplîche. (Tristan u. Isolde 2442) f)</li>');
document.write('<div style="border: 1px solid #000;width:4em;text-align:center; float:left;margin-right:2em;">MHD</div>');
document.write('<li><u>Tristanden</u> nâmen si sâ und sazten den ûz an daz lant.<br>(Tristan 2472 f)<br>');
document.write('Sie nahmen den Tristan sogleich und setzen ihn hinaus an das Land.</li>');
document.write('<div style="border: 1px solid #000;width:2em;text-align:center; float:left;margin-right:2em;">方</div>');
document.write('<li>BERTHA: Geh, August, frag <u>Ansorgen</u> (Ansorge), ob a nich will anleucht\'n. (Die Weber II)<br>アカリヲツケテクレナイカ</li>');
document.write('<div style="border: 1px solid #000;width:2em;text-align:center; float:left;margin-right:2em;">方</div>');
document.write('<li>');
document.write('Vater hat mußt <u>Ami\'n</u> mitnehmen. Wir miss\'u \'n schlacht‘n lass\'n, dass m\'r  oc reen wieder amal was in a Mag\'n krieg‘n. (Die Weber II)<br>Ami:  Hundsname.');
document.write('</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');