document.write('<div class="container">');
document.write('<div class="tab_change">');
document.write('  <!-- タブボタン部分 -->');
document.write('  <ul class="nav nav-tabs" style="list-style: none;">');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab1" class="nav-link active" data-toggle="tab">原本</a>');
document.write('    </li>');
document.write('    <li class="nav-item">');
document.write('      <a href="#tab2" class="nav-link" data-toggle="tab">翻刻</a>');
document.write('    </li>');
document.write('  </ul>');
document.write('  <!--タブのコンテンツ部分-->');
document.write('  <div class="tab-content">');
document.write('    <div id="tab1" class="tab-pane active">');
document.write('      <a href="/img/001/S0034.gif" class="luminous"><img src="/img/001/S0034.gif" alt="" class="mw-100"></a>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('    <div id="tab2" class="tab-pane">');
document.write('<h2>des Doktor Faust型</h2>');
document.write('<p>（Apposition →）</p>');
document.write('<ol>');
document.write('<li>Das Testament <u>des Dr. Mabuse</u>. （有名なKriminalroman）</li>');
document.write('<div style="border: #000 solid 1px;width:3em;text-align:center;float:left;">NB</div> 墺口では：<br />');
document.write('<li style="clear:both;">Auf Firmenschildern liest man in Oesterreich vielfach das bestimmte geschlechtswort vor Namen: <u>Krämerel des Joseß Richter</u>.<br />(A. Schirmer: Der Sprach- und Schriftverkehr der Wirtschaft. S.56)</li>');
document.write('<li>凍結系：<br />Die "alte Pariserin" und die "Kokotte", die Leibl während seines Pariser Aufenthaltes im Jahre 1869 malte, sind von jener malerischen Qualität, die jeden beeindruckt, und auch die Porträts der Folgezeit, vor allem das Bildnis <u>des Heinrich Pallenberg</u>, finden bereiteste Zustimmung, die sich jedoch vor den Spätwerken merklich abkühlt, deren sentimentales Genre als Rückfall ins Provinzielle empfunden wird, Könnte man hier verwandte Darstellungen von Courbet der zu Leibls großen Bewunderern zählte, zum Vergleich heranziehen, so fiele er trotzdem wohl zugunsten des Kölners aus, dessen Bauernbilder echte, innige Vertrautheit mit Land und Leuten seiner bayerischen Wahlheimant austtrömen, während den kostümierten Modellen Courbets meist eine gewisse theatralische Romantik anhaftet.</li>');
document.write('</ol>');
document.write('<br><br><a href="#" onclick="javascript:window.history.back(-1);return false;">Back</a>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');