document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">01-1B</div><div class="col-8"><a href="../001/s0001.html">At once proper noun and normal noun:</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">01-2B</div><div class="col-8"><a href="../001/s0002.html">Proper Noun</a></div><div class="col-2">2-49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0003.html">［01］Proper place name is, in general, neutral</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0004.html">［02］=s in genetiv</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0008.html">［03］Case inflection of Unter den Linden</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0009.html">［04］=e</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0014.html">［05］=sch</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0020.html">［06］s of plural</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0025.html">［07］=en, =e of plural</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0026.html">［08］-n、-en of Dativ (a manner without dative-governing preposition)</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0028.html">［09］=n、=en in Akkusativ.</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0031.html">［10］Meines Roderich</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0039.html">［11］Article and Proper Noun</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［12］=ens in Genetiv</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［13］des grossen Fritzen</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［14］des heutigen Deutschland</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［15］Apostroch（省字符）による二格</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［16］複数でdie～（=s無し）</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［17］Der alte Fritz, Der gruene Heinrich等も前出と同じ</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">01-3R</div><div class="col-8"><a href="../001/s0***.html">_</a></div><div class="col-2">50-51</div></div>');
document.write('<div class="row"><div class="col-2">01-4B</div><div class="col-8"><a href="../001/s0***.html">格変化</a></div><div class="col-2">52-108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［01］成句に限ってあうDativ, Fem, の=en</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［02］弱変化男性名詞</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［03］Name型</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［04］Des Papa型</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［05］Herz, Schmerz</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［06］gleiches Namens等</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［07］弱変化名詞の三四格以外（聯語） zu Mensch und Welt</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［08］単独のNennform（弱変化）（及びWille等）</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［09］Das Schwert des Demokles</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［10］表題の引用とその格（二通り）</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［11］Zur Erden等</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［12］Theseus'+"' Stadt, Dollfuss'"+' Beisetzung</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［13］弱変化男性の=enの例外的省略</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［14］Friede, Gedanke, Funke.</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［15］des Sturm und Dranges －－数語を一括して一個の名詞と見る。－－</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../001/s0***.html">［16］Euer Gnaden (EW)の各格</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2">01-5</div><div class="col-8"><a href="../001/s0***.html">_</a></div><div class="col-2">109-134</div></div>');
document.write('</div>');