document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">05-1R</div><div class="col-8"><a href="../005/s0001.html">それ自身としてはまだ格を決めるわけに行かないもの<br />は一格を以てNeuefallとして持ちふ。（内的格と対外格との問題）。掲称・列挙の一格→無冠詞（掲称）。Nenn=Nominativ.四格使用の例外として。Vocativと物主形容詞との関係：Unser Vater, Mein Vater, はあるがSein Verter, Dein Vater etcは<u>存在せず</u>！ Apposition代りの一格</a></div><div class="col-2">1-6<br /> <br /> <br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">05-2B</div><div class="col-8"><a href="../005/s0007.html">描写・列挙の際の一格</a></div><div class="col-2">7-8</div></div>');
document.write('<div class="row"><div class="col-2">05-3B</div><div class="col-8"><a href="../005/s0009.html">alsの次のNenn=Nominativ</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2">05-4R</div><div class="col-8"><a href="../005/s0010.html">定形中心文法の基礎問題「伯父の到着」＝「伯父が到<br />着した」（日誌文体など）。副詞的一格。「羅」古きLocativ。罵言は呼掛け（Vokativ）とは違うから<u>定冠詞</u>をつける。alsとNenn=Nominativ</a></div><div class="col-2">10-11<br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">05-5B</div><div class="col-8"><a href="../005/s0012.html">名詞 Nominativ</a></div><div class="col-2">12-52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0014.html">［01］<u>freier Nominativ</u>（これも述語なり）</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0027.html">［02］Nenn=Nominativ</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0032.html">［03］<u>Ein rascher Griff</u>, und alles ist getan</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0037.html">［04］省略された文章としての Nenn=Nominativ.</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0039.html">［05］主語以外の一格文肢（副詞的）</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0045.html">［06］表題等の引用に於ける格の問題（一格及びその他）</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0048.html">［07］fünf Mark die Flasche</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0050.html">［08］<u>Vokativ</u></a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0052.html">［09］die Fülle und die Menge など量の規定。</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../005/s0053.html">［10］Apposition（正置）の際の無格</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2">05-6B</div><div class="col-8"><a href="../005/s0054.html">先置するNenn=Nominativ。vonと挙形（諸種の問題を一括）</a></div><div class="col-2">54-55</div></div>');
document.write('<div class="row"><div class="col-2">05-7B</div><div class="col-8"><a href="../005/s0056.html">状況言的無格。Angabe=Nominativ.</a></div><div class="col-2">56-58</div></div>');
document.write('<div class="row"><div class="col-2">05-8B</div><div class="col-8"><a href="../005/s0059.html">間投的一格 Feuer! Fluch!等の格の問題</a></div><div class="col-2">59-60</div></div></div>');