document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">06-1B</div><div class="col-8"><a href="../006/s0001.html">Genitiv</a></div><div class="col-2">1-283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0004.html">[01]Genitivs Abusolutus</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0044.html">[02]Genitivs Abusolutus 副詞的規定</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0057.html">[03]内容、性質、種類等の規定（形容詞的）</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0072.html">[04]Gentivs Qualitatis proprius.</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0086.html">[05]掲称的二格、掲称的附置規定に等しきもの</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0100.html">[06]Subjekt=Genitiv.</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0101.html">[07]Objekt=Genitiv（物質代名詞にも此の区別あり）</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0123.html">[08]Genitivs Partitivusの最も純粋なるもの。</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0124.html">[09]Du bist des Todes（述語用法の疑問系）</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0128.html">[10]不定法名詞の二格</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0137.html">[11]熟語化した二格副詞</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0142.html">[12]見地の二格</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0153.html">[13]<u>des Inhalts</u>, <u>der Art</u></a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0157.html">[14]述語的Gen. Abs.の熟語（von---）</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0164.html">[15]des Weiteren等（比較級が主）</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0168.html">[16]Namens, sein zeichens.（nach---）</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0175.html">[17]ein glas Weinに形容詞がつくとein glas &lt;uとなる事。&lt;/u</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0175.html">[18]Gen.Abs.の形容詞的用法（熟語には非ざるもの）</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0176.html">[19]Zeitliche Erstreckung（Akkusativの代わり）</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0179.html">[20]数詞、量詞と共に。</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0216.html">[21]拉典式。--- des Kaisere sein</a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0229.html">[22]<u>seines Weges gehen</u>. 等の熟語</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0235.html">[23]seines Orts. höheren Orts等。</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0238.html">[24]時の副詞（二格形） eines schönen Tages.</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0246.html">[25]Saxon Genitiveを用いなければならぬ場合。(für sein und der Seinigen Wohl)</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0249.html">[26]"Saxon Genitive"(Sprich Wörtlich)</a></div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0270.html">[27]間投のGenitiv(über---!)</a></div><div class="col-2">270</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0277.html">[28]ein wenig Wassers</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../006/s0283.html">[29]二格（関係代名詞）離置。</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2">06-2B</div><div class="col-8"><a href="../006/s0284.html"><u>Manns</u> <u>Genug</u></a></div><div class="col-2">284-287</div></div>');
document.write('<div class="row"><div class="col-2">06-3B</div><div class="col-8"><a href="../006/s0288.html">METAPHERと共に用ひるGENITIV.</a></div><div class="col-2">288-295</div></div>');
document.write('<div class="row"><div class="col-2">06-4B</div><div class="col-8"><a href="../006/s0296.html">ubi locorum等</a></div><div class="col-2">296-305</div></div>');
document.write('<div class="row"><div class="col-2">06-5B</div><div class="col-8"><a href="../006/s0306.html"><u>des Weines</u> trinken GENITIVUS PARTITIVUS</a></div><div class="col-2">306-310</div></div>');
document.write('<div class="row"><div class="col-2">06-6B</div><div class="col-8"><a href="../006/s0311.html">des（そのため）</a></div><div class="col-2">311-321</div></div>');
document.write('<div class="row"><div class="col-2">06-7B</div><div class="col-8"><a href="../006/s0322.html">否定と二格との関係</a></div><div class="col-2">322-328</div></div>');
document.write('<div class="row"><div class="col-2">06-8R</div><div class="col-8"><a href="../006/s0329.html">[MHD]nichts考。通り言葉の二格。deinの代わりに<br />名詞の二格。Genitiv の収縮文に於ける機能は重要な<br />り。Die Germanen <u>des Tacitus</u>型（編者注：ほか4件）</a></div><div class="col-2">329-334</div></div>');
document.write('<div class="row"><div class="col-2">06-9B</div><div class="col-8"><a href="../006/s0335.html">Genitivの意味に閏する一般考察。</a></div><div class="col-2">335-338</div></div>');
document.write('<div class="row"><div class="col-2">06-10R</div><div class="col-8"><a href="../006/s0339.html">それは不可能。 Eines Bogenschulusses weit.二格の語形[MHD]では閏係で充分わかるが[NHD]では</a></div><div class="col-2">339-353</div></div>');
document.write('<div class="row"><div class="col-2">06-11R</div><div class="col-8"><a href="../006/s0354.html">Gentivの重畳</a></div><div class="col-2">354-366</div></div></div>');