document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">03-1B</div><div class="col-8"><a href="../003-1/s0001.html">er, el, en n型（複数及び性）</a></div><div class="col-2">1-17</div></div>');
document.write('<div class="row"><div class="col-2">03-2B</div><div class="col-8"><a href="../003-1/s0018.html">性</a></div><div class="col-2">18-91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0020.html">［01］複合名詞の性はその最後の字によって決める－－といふ規則についての注意</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0021.html">［02］人格と見なすものは他品詞の名詞化でも男性</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0040.html">［03］自然の性と一致せざるもの。</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0044.html">［04］自然の性と一致せざるものの受け方。（関係代名詞、物主代名詞）</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0055.html">［05］異性異意</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0056.html">［06］Scheibare Inkongruenzen 指示代名詞、男女無差別の男性（der-等）</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0057.html">［07］女を男性普通名で指すとき。（性・数両方）（主語に非ずして客語的位置にある時）</a></div><div class="col-2">57<br /> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0080.html">［08］MutとWehmut</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-1/s0089.html">［09］eines, keines, yedes（男女混れる時）”中性視”</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2">03-3B</div><div class="col-8"><a href="../003-1/s0092.html">地名の性 及び定冠詞の問題</a></div><div class="col-2">92-122</div></div>');
document.write('<div class="row"><div class="col-2">03-4R</div><div class="col-8"><a href="../003-1/s0123.html">複数形の随一の例外：Sporen =en が男性語Par. Excelanceなることの備考。女性固有名詞のpl.=en</a></div><div class="col-2">123-125<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-5R</div><div class="col-8"><a href="../003-1/s0126.html">Zeppelin=eその他 =e 一般</a></div><div class="col-2">126-146</div></div>');
document.write('<div class="row"><div class="col-2">03-6B</div><div class="col-8"><a href="../003-1/s0147.html">性数格を近い方に合わす。性数のKongruenz一般</a></div><div class="col-2">147-156</div></div>');
document.write('<div class="row"><div class="col-2">03-7B</div><div class="col-8"><a href="../003-1/s0155.html">性数の二つ以上あるもの性の誤をも含む!!!</a></div><div class="col-2">155-180</div></div>');
document.write('<div class="row"><div class="col-2">03-8B</div><div class="col-8"><a href="../003-1/s0181.html">Zirkus-se</a></div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2">03-9B</div><div class="col-8"><a href="../003-1/s0182.html">Pluralia tantum等</a></div><div class="col-2">182-266</div></div>');
document.write('<div class="row"><div class="col-2">03-10B</div><div class="col-8"><a href="../003-1/s0267.html">der Flirt その他 酒・衣服、etc</a></div><div class="col-2">267-290</div></div>');
document.write('<div class="row"><div class="col-2">03-11B</div><div class="col-8"><a href="../003-1/s0291.html">女性語尾 = in</a></div><div class="col-2">291-304</div></div>');
document.write('<div class="row"><div class="col-2">03-12B</div><div class="col-8"><a href="../003-2/s0305.html">数</a></div><div class="col-2">305-448</div></div>');
document.write('<div class="row"><div class="col-2">03-13B</div><div class="col-8"><a href="../003-2/s0310.html">［01］=heiten, =Kkeitenが「性質」でなく「性質を帯びたもの」即ち言語又は動作又は物体等を指す傾向</a></div><div class="col-2">310<br /> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0318.html">［02］Pluralia tantum</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0326.html">［03］複数が別意を持つもの</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0328.html">［04］好んで複数を用いるもの。</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0328.html">［05］=ma:pl=men, =a-・=en</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0329.html">［06］generelier Singular.（中性の場合も然り）</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0344.html">［07］Kollektiva</a></div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0366.html">［08］共有の単数（複数を用ひる代り）</a></div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0371.html">［09］Singularia tantum</a></div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0379.html">［10］物質的取扱のSingularia tantum</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0379.html">［11］Schein Plural</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0381.html">［12］共通の単数のKopulaが複数の例。</a></div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0388.html">［13］単位扱いのplは単数形</a></div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0388.html">［14］Dinger.等</a></div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0388.html">［15］Die Jas =s</a></div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0389.html">［16］das Auge, Ohr Hand, 等（Augen, Ohren, Haendenの代わり）</a></div><div class="col-2">389</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0398.html">［17］純共有の単数（distributiv, 各々）</a></div><div class="col-2">398</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0410.html">［18］主語がplで客語が \'s. （及びその反対）</a></div><div class="col-2">410</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0420.html">［19］尊称的単数名詞にはplの定型を用ふ</a></div><div class="col-2">420</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0422.html">［20］複数名詞が「習憤的」事実の暗示に用いられる際</a></div><div class="col-2">422</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0424.html">［21］聯語には単数を用ふ。</a></div><div class="col-2">424</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0425.html">［22］Die Feuer etc.（意味がnomen materieより転化せり）</a></div><div class="col-2">425</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0435.html">［23］die Salze, die Fette, die zZucker等</a></div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0436.html">［24］聯語と定型。（pl. の際）</a></div><div class="col-2">436</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0437.html">［25］倒置定形の単数形と二個以上の単数主語。</a></div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../003-2/s0438.html">［26］数的主語はpl.</a></div><div class="col-2">438</div></div>');
document.write('<div class="row"><div class="col-2">03-13R</div><div class="col-8"><a href="../003-2/s0449.html">男性、人名より普通名へ Die Schumanns- 家族夫妻、=sかGenetiv=sなること 古代には複数が貧弱で単と同形か多かったということ。複数形におけるアクセン卜の移動。. aus Wohlklangsrurcksichten. 概念としては明らかにpl.なるものを単として扱ふ独の癖（古典語と比べて） Alle Mann hielten<br />編者注 : ほかに25件あり</a></div><div class="col-2">449-476<br /> <br /> <br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-14B</div><div class="col-8"><a href="../003-2/s0477.html">der Sofa der Pult等</a></div><div class="col-2">477-480</div></div>');
document.write('<div class="row"><div class="col-2">03-15B</div><div class="col-8"><a href="../003-2/s0481.html">抽象名詞のpl.種々の場合を想起せしめる効果あり</a></div><div class="col-2">481</div></div>');
document.write('<div class="row"><div class="col-2">03-16B</div><div class="col-8"><a href="../003-2/s0482.html">Dualis</a></div><div class="col-2">482-484</div></div>');
document.write('<div class="row"><div class="col-2">03-17B</div><div class="col-8"><a href="../003-2/s0485.html">複雑な内容を含むと推察される抽象概念には好んでPLを用いる</a></div><div class="col-2">485-487</div></div>');
document.write('<div class="row"><div class="col-2">03-18B</div><div class="col-8"><a href="../003-2/s0488.html">Zeugs Dings Krams</a></div><div class="col-2">488-489</div></div>');
document.write('<div class="row"><div class="col-2">03-19B</div><div class="col-8"><a href="../003-2/s0490.html">「仏」物の集約名詞</a></div><div class="col-2">490</div></div>');
document.write('<div class="row"><div class="col-2">03-20B</div><div class="col-8"><a href="../003-2/s0491.html">代名詞の中性化傾向</a></div><div class="col-2">491-495</div></div>');
document.write('<div class="row"><div class="col-2">03-21R</div><div class="col-8"><a href="../003-2/s0496.html">人問の中性扱い</a></div><div class="col-2">496-501</div></div>');
document.write('<div class="row"><div class="col-2">03-22R</div><div class="col-8"><a href="../003-2/s0502.html">英語でも、例えば蜜蜂（bee）などは女性扱いにする！ Tausennd und eine Nacht 英は拉式複数形多し。 商品名の性Die Leica等。 勤物名中性。<br />編者注：ほかに40件あり</a></div><div class="col-2">502-540<br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-23B</div><div class="col-8"><a href="../003-2/s0541.html">Die Dpktos, Die Kerls等 =s 語尾のpl.</a></div><div class="col-2">541-551</div></div>');
document.write('<div class="row"><div class="col-2">03-24B</div><div class="col-8"><a href="../003-2/s0552.html">複数形、Die Warumsか？ Die Warumか？</a></div><div class="col-2">552-558</div></div>');
document.write('<div class="row"><div class="col-2">03-25R</div><div class="col-8"><a href="../003-2/s0559.html">Die Theorie von den zwei China. 固有名詞の無語尾複数</a></div><div class="col-2">559-560<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-26B</div><div class="col-8"><a href="../003-2/s0561.html">Dinge</a></div><div class="col-2">561-582</div></div>');
document.write('<div class="row"><div class="col-2">03-27B</div><div class="col-8"><a href="../003-2/s0583.html">外来語の複数語尾としての =s</a></div><div class="col-2">583-589</div></div>');
document.write('<div class="row"><div class="col-2">03-28B</div><div class="col-8"><a href="../003-2/s0590.html">「仏」 仏独「性」の相違</a></div><div class="col-2">590-593</div></div>');
document.write('<div class="row"><div class="col-2">03-29R</div><div class="col-8"><a href="../003-2/s0594.html">Kongruenzfrageの一覧。失後、Zwei mann=Tank等。音響名（Schallwort）"Knacks"の男性</a></div><div class="col-2">594-603<br /> </div></div>');
document.write('<div class="row"><div class="col-2">03-30B</div><div class="col-8"><a href="../003-2/s0604.html">「船名・その他一括</a></div><div class="col-2">604-621</div></div>');
document.write('<div class="row"><div class="col-2">03-31B</div><div class="col-8"><a href="../003-2/s0622.html">=ien, =en複数語尾　外来語</a></div><div class="col-2">622-635</div></div>');
document.write('<div class="row"><div class="col-2">03-32B</div><div class="col-8"><a href="../003-2/s0636.html">Das Blau 色彩その他</a></div><div class="col-2">636-640</div></div>');
document.write('<div class="row"><div class="col-2">03-33B</div><div class="col-8"><a href="../003-2/s0641.html">Muskeln型</a></div><div class="col-2">641-645</div></div></div>');