document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">04-1B</div><div class="col-8">三格支配の動詞</div><div class="col-2">1-23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］dienen, ähnlich sehen, folgen, gehorchen, ets</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］zu=entgegen=, nach=を伴ふ動詞</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］熟語。物の主語と人の三格。特例Liebkosen等。<br />Ihm ward(Zuteil), 及び類似のもの。<br /><u>folgen</u> <u>auf</u>と<u>三格直結</u></div><div class="col-2">20<br /> <br /> </div></div>');
document.write('<div class="row"><div class="col-2">04-2B</div><div class="col-8">数個の補足語を採る勁詞</div><div class="col-2">24-38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］3格と4格</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2">04-3R</div><div class="col-8">初歩用。 梵 yacch与える</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2">04-4B</div><div class="col-8"> </div><div class="col-2">40-42</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］四格と奪格的三格</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］geben型動詞</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］二重四格、参考。</div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2">04-5B</div><div class="col-8">日本語とは格支配の閏係を異にするもの</div><div class="col-2">43-47</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］<u>berühren</u>. <u>helfen</u>. <u>grüssen</u>. etc.</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］に耐える、 及第する。</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03〕</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］「英」 三、四格の区別が独ではあるが英では<br />単に目的語（即ちAKK）</div><div class="col-2">47<br /> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］前綴との関係</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2">04-6B</div><div class="col-8">二格支配 形容詞</div><div class="col-2">48-118</div></div>');
document.write('<div class="row"><div class="col-2">04-7B</div><div class="col-8">二格支配 動詞</div><div class="col-2">119-170</div></div>');
document.write('<div class="row"><div class="col-2">04-8B</div><div class="col-8">三格支配 形容詞</div><div class="col-2">171-224</div></div>');
document.write('<div class="row"><div class="col-2">04-9B</div><div class="col-8">二格支配 動詞（特に「独」の分冊）</div><div class="col-2">225-265</div></div>');
document.write('<div class="row"><div class="col-2">04-10B</div><div class="col-8">四格支配の動詞</div><div class="col-2">266-275</div></div>');
document.write('<div class="row"><div class="col-2">04-11B</div><div class="col-8">四格支配の熟語成句</div><div class="col-2">276-280</div></div>');
document.write('<div class="row"><div class="col-2">04-12B</div><div class="col-8">in支配。</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2">04-13B</div><div class="col-8">前置詞支配の形容詞</div><div class="col-2">282-284</div></div>');
document.write('<div class="row"><div class="col-2">04-14B</div><div class="col-8">三格支配か四格支配の問題。 j.versichern.nützen</div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2">04-15B</div><div class="col-8">形容詞の前置詞句支配 auf.an.zu.</div><div class="col-2">286-287</div></div>');
document.write('<div class="row"><div class="col-2">04-16B</div><div class="col-8">「態」一般　相・法・式・時・様の置き場所</div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2">04-17B</div><div class="col-8">支配異なれば意味異なる。 folgen dem<br />                              auf</div><div class="col-2">289<br /> </div></div>');
document.write('<div class="row"><div class="col-2">04-18B</div><div class="col-8">一格支配の動詞</div><div class="col-2">290-302</div></div>');
document.write('<div class="row"><div class="col-2">04-19B</div><div class="col-8">四格支配 形容詞</div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2">04-20B</div><div class="col-8">非人称動詞の二格支配</div><div class="col-2">304</div></div></div>');