document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">12-1B</div><div class="col-8"><a href="../012/s0001.html">本編の主人公 unser 問題の男、etc.</a></div><div class="col-2">1-8</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0009.html">物主形容詞</a></div><div class="col-2">9-83</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0011.html">[01]直前を受けるもの。（物）再帰物主形容詞なり</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0018.html">[02]物主代名詞を用いざる場合。</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0019.html">[03]直前を受けるもの（人）殆ど無意</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0035.html">[04]例の、おきまりの。</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0036.html">[05]名詞を略する際。</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0041.html">[06]zu seiner Zeit,\' seinerzeit,\' an seinem Orte.</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0047.html">[07]mein,\' dein,\' sein (adverba1)とnennen<br />特に<u>mein eigen</u>なる形に注意せよ：</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0049.html">[08]das seinige (Absolut) sein Teil</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0057.html">[09]物主代名詞の代りに<u>von mir</u>等。</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0057.html">[10]主語を受ける無意味な物主代名詞の熟語。</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0058.html">[11]Das ist mein.</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0064.html">[12]Dieser sein等。</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0066.html">[13]豫め受ける物主代名詞。－文の全体主語に限る－</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0067.html">[14]物主代名詞の前に附け得る冠飾語 <u>alle</u> seine<br />とdiese(jene) seine.</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0071.html">[15]<u>Ihro</u> Majestät. <u>höchstdero</u> aller-</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0074.html">[16]味方、身内 Die Unsrigen（単もあり） <u>unsern</u> <br />Die Unsern</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0076.html">[17]<u>Euer</u>（Gnaden）の各格。</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0079.html">[18]物主代名詞を名詞の後に。</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2">12-2B</div><div class="col-8"><a href="../012/s0081.html">[19]<u>Dem</u> Franzel <u>sein</u> Vater. （(三格と） <u>Meines</u> Vater sein Sohn.（二格と）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2">12-3R</div><div class="col-8"><a href="../012/s0084.html">物主形容詞の補強。英の<u>0f his</u>と仏の<u>à elle</u><br />一般称の三人称 英のone\'s. 独、仏：sein, \' son.</a></div><div class="col-2">84-87</div></div>');
document.write('<div class="row"><div class="col-2">12-4B</div><div class="col-8"><a href="../012/s0088.html">間投的：Ma tête, Ma pauvre tête!</a></div><div class="col-2">88-92</div></div>');
document.write('<div class="row"><div class="col-2">12-5R</div><div class="col-8"><a href="../012/s0093.html">後置のdein, sein. 人代名詞の二格のir(ihrer)など</a></div><div class="col-2">93-95</div></div>');
document.write('<div class="row"><div class="col-2">12-6B</div><div class="col-8"><a href="../012/s0096.html">価格見積の際（価値のみに非ず）</a></div><div class="col-2">96-100</div></div>');
document.write('<div class="row"><div class="col-2">12-7B</div><div class="col-8"><a href="../012/s0101.html">再帰物主形容詞一般論</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">12-8B</div><div class="col-8"><a href="../012/s0102.html"><u>il</u> mio padre式</a></div><div class="col-2">102-110</div></div>');
document.write('<div class="row"><div class="col-2">12-9B</div><div class="col-8"><a href="../012/s0111.html">Mein Mann,\' Meine Frau,\'etc.</a></div><div class="col-2">111-113</div></div>');
document.write('<div class="row"><div class="col-2">12-10R</div><div class="col-8"><a href="../012/s0114.html">sein eigener Arzt. 再帰物主冠詞（補）（自主自足<br />性の顕著なもの）。「MHD」物主冠詞の諸種の形<br />。物主形容詞代りに人代名詞の二格を。<br />編者注：このほか22件あり</a></div><div class="col-2">114-134</div></div></div>');