document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">08-1B</div><div class="col-8"><a href="../008/s0001.html">間投的四格。</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0002.html">四格 Akkusativ</a></div><div class="col-2">2-156</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0006.html">[01]umliche Erstreckung. 編者注:?</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0006.html">[02]Zeitliche Erstreckung. Meine Tage等</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0025.html">[03]測定的。（主として比較級の前に）</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0038.html">[04]測定定。（weiter, voraus等を伴わぬ場合） <u>副詞的</u></a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0039.html">[05]時の副詞。<u>Zeitpunkt</u></a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0040.html">[06] [02]と同じ ...über, durch.</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0046.html">[07]四格の副詞化。 nichts.（ονδεν, πολ<br />υ）</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0071.html">[08]結果挙述の四格</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0074.html">[09]結果挙述四格の一種</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0088.html">[10]Erstreckungusakkusativ mit Nachadverb通過のAkkusativ（<u>hinau</u>等と）</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0091.html">[11]drei Meter hoch等。</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0103.html">[12]「差のum」＋比較級の代りに単に四格。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0106.html">[13]Inneres Objekt. 〔外国語〕</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0107.html">[14]Lassenと二個の四格</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0109.html">[15]数量四格を支配する動詞。～betragen,<br />～messen, ～zähLen</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0110.html">[16]be= と四格。</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0110.html">[17]eine Zeit <u>lang</u> 「langを前置詞に扱っては？〕</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0111.html">[18]<u>einen Strich</u> malen. 量的規定の四格。</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0114.html">[19]二菫四格（nennen, schelten)</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0123.html">[20]特 「lehren, 其他」</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0134.html">[21]結果挙述。退去を命ずる等。</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0146.html">[22]挙形（又は省略形は一格又は四格）</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0147.html">[23]Wache stehenに対する一格形</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0152.html">[24]<u>seinen</u> <u>Mann</u> stehen=sich Bewähren</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2">08-2B</div><div class="col-8"><a href="../008/s0154.html">[25]Karussel fahren等</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2">08-3B</div><div class="col-8"><a href="../008/s0157.html">数値の四格。 aufと関係</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0158.html">文肢。Inneres Objekt</a></div><div class="col-2">158-191</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0159.html">[01]Genitiv.</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0160.html">[02]四格の例</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0173.html">[03]Funken sprühen等（結果の四格と似て非なこと）</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0177.html">[04]代名詞四格のInneres Objektは、普通のものより<br />は目に立たざる故、用ひられる事多し。</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0177.html">[05]特別に拵へるもの。</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0177.html">[06]lassenと二つの四格</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0178.html">[07]einen Strich streichen ひとこすりする。</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0179.html">[08]<u>夢が</u>夢みる。（主語とinneres Verbum）</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2">08-4B</div><div class="col-8"><a href="../008/s0180.html">[09]希・羅</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2">08-5R</div><div class="col-8"><a href="../008/s0192.html">特に人聞の四格に閲する注意：「その人の言う事を」<br />「その人の考えていることを」など。 Guten Morgen<br />! の完全形。 den <u>Weg gehen</u>, die <u>Strasse</u> ziehen<br />等。 Den Herrn Spielen等<br />編者注：このほか9件</a></div><div class="col-2">192-199</div></div>');
document.write('<div class="row"><div class="col-2">08-6B</div><div class="col-8"><a href="../008/s0200.html"><u>Was</u> andere <u>tanzen</u>, muss er schätzen.</a></div><div class="col-2">200-202</div></div></div>');