document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">11-1B</div><div class="col-8">病名と冠詞</div><div class="col-2">1-9</div></div>');
document.write('<div class="row"><div class="col-2">11-2B</div><div class="col-8">Dieserの意(tonlos)</div><div class="col-2">10-15</div></div>');
document.write('<div class="row"><div class="col-2">11-3B</div><div class="col-8">Dieserと同じでしかもtonlos、即ち完全に定冠詞なる<br />もの</div><div class="col-2">16-28</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">定冠詞</div><div class="col-2">29-120</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[01]たとえ熟語と雖も</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[02]固有事象人物を指すとき</div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[03]固有名と雖も二格等の規定ある際</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[04]必ず定冠詞を伴う成句</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[05]文脈全般に亙って問題になっているもの</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[06]viel=, wenig=等の前にも定冠詞を据える</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[07]改めて紹介する際と雖も現在相手が知って居る<br />か、思っているかと言ったようなとき。</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[08]二個の名詞の前に一つの定冠詞。（不定冠詞）</div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[09]定冠詞の有無で意味の相違</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[10]最高級と定冠詞（及び例外）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[11]数詞の前につく例</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[12]ニ語の前で冠詞（定・不定〉の省略</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[13]抽象名詞（抑、－－なるもの）</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[14]一般（überhaupt）</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[15]数語一括の際と雖も規定あれば定冠詞</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[16]定冠詞省略の不可なるもの</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[17]女性複数の国名は複数</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[18]一個についていくら（die Flasche）</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[19]必ず定冠詞を要する熟語</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[20]Neinnsatzの主語と述語</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[21]Der düstere, pathetische <u>Othello</u></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[22]die verderbliche, Epitheton ornanns.</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[23]人代名詞にかはるべき、述語的名詞</div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[24]inとim</div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2">11-4B</div><div class="col-8">[25]固有名詞と定冠詞</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2">11-5B</div><div class="col-8">Das grosse Wort Das grosse Los Der grosse Augenblick</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2">11-6B</div><div class="col-8">最高級と定冠詞、序数をも含めて das gleiche～も</div><div class="col-2">122-136</div></div>');
document.write('<div class="row"><div class="col-2">11-7R</div><div class="col-8"> </div><div class="col-2">137-145</div></div>');
document.write('<div class="row"><div class="col-2">11-8B</div><div class="col-8">形式的定冠詞</div><div class="col-2">146-157</div></div>');
document.write('<div class="row"><div class="col-2">11-9B</div><div class="col-8">形容詞の際起こる問題</div><div class="col-2">158-161</div></div>');
document.write('<div class="row"><div class="col-2">11-10B</div><div class="col-8">時と処の一般的規定は原則として定冠訶を温存する傾向あり</div><div class="col-2">162-189</div></div>');
document.write('<div class="row"><div class="col-2">11-11B</div><div class="col-8">前置詞との結合一般</div><div class="col-2">190-192</div></div>');
document.write('<div class="row"><div class="col-2">11-12B</div><div class="col-8">ins Gefängnis （stecken...） オランダ語あり</div><div class="col-2">193-195</div></div>');
document.write('<div class="row"><div class="col-2">11-13B</div><div class="col-8">形容詞概念の迂言的表現</div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2">11-14B</div><div class="col-8">迂言動詞 Nach1ese</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">11-15B</div><div class="col-8">元来は無冠の筈の所て<u>特殊通念</u>が来ると定冠詞を付ける</div><div class="col-2">198-208</div></div>');
document.write('<div class="row"><div class="col-2">11-16B</div><div class="col-8">無綴定冠詞、im, am, ins, in\'s Teufels Nemen!</div><div class="col-2">209-212</div></div>');
document.write('<div class="row"><div class="col-2">11-17B</div><div class="col-8">Muster</div><div class="col-2">213-249</div></div>');
document.write('<div class="row"><div class="col-2">11-18B</div><div class="col-8">対象性を喪失した名詞は素朴類型概念として扱い定冠詞を付す</div><div class="col-2">250-257</div></div>');
document.write('<div class="row"><div class="col-2">11-19B</div><div class="col-8">迂言前置詞の準備</div><div class="col-2">258-271</div></div>');
document.write('<div class="row"><div class="col-2">11-20B</div><div class="col-8">格を明示するための定冠詞</div><div class="col-2">272-279</div></div>');
document.write('<div class="row"><div class="col-2">11-21R</div><div class="col-8">複数無冠詞</div><div class="col-2">280-281</div></div>');
document.write('<div class="row"><div class="col-2">11-22B</div><div class="col-8">間投的：La vieille</div><div class="col-2">282-287</div></div>');
document.write('<div class="row"><div class="col-2">11-23R</div><div class="col-8"> </div><div class="col-2">288-289</div></div>');
document.write('<div class="row"><div class="col-2">11-24B</div><div class="col-8">一般宣言の八式とその微差</div><div class="col-2">290-293</div></div>');
document.write('<div class="row"><div class="col-2">11-25B</div><div class="col-8">固有名詞と定冠詞（人名と地名）</div><div class="col-2">294-301</div></div>');
document.write('<div class="row"><div class="col-2">11-26B</div><div class="col-8">150 Schläge in der Minute</div><div class="col-2">302-313</div></div>');
document.write('<div class="row"><div class="col-2">11-27R</div><div class="col-8"><u>希</u> 定冠詞参考</div><div class="col-2">314-315</div></div>');
document.write('<div class="row"><div class="col-2">11-28B</div><div class="col-8">Saxon genitiveの後における冠詞の省略に就いて</div><div class="col-2">316-317</div></div>');
document.write('<div class="row"><div class="col-2">11-29B</div><div class="col-8">冠詞の省略 二格規定を前に伴ふ時</div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2">11-30B</div><div class="col-8">素朴類型単数 Das Blut, der Schweiss, 等</div><div class="col-2">319-325</div></div>');
document.write('<div class="row"><div class="col-2">11-31B</div><div class="col-8">Der Schnee fiel in grossen F1ocken</div><div class="col-2">326-330</div></div>');
document.write('<div class="row"><div class="col-2">11-32B</div><div class="col-8">世の中に一つしかないものの定冠詞</div><div class="col-2">331-337</div></div>');
document.write('<div class="row"><div class="col-2">11-33B</div><div class="col-8">定冠詞　<u>例の…という奴</u> liebと関係</div><div class="col-2">338-342</div></div>');
document.write('<div class="row"><div class="col-2">11-34B</div><div class="col-8">風の名は男性</div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2">11-35B</div><div class="col-8">既に紹介済の事物に就いて</div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2">11-36B</div><div class="col-8">非明示的規定と定冠詞</div><div class="col-2">345-350</div></div>');
document.write('<div class="row"><div class="col-2">11-37B</div><div class="col-8">直前と関係する定冠詞</div><div class="col-2">351-357</div></div>');
document.write('<div class="row"><div class="col-2">11-38B</div><div class="col-8">”問題の”型</div><div class="col-2">358-362</div></div>');
document.write('<div class="row"><div class="col-2">11-38B</div><div class="col-8">規定あるかための定冠詞</div><div class="col-2">363-375</div></div>');
document.write('<div class="row"><div class="col-2">11-40B</div><div class="col-8">元来ならば無冠詞の筈の語にも規定あれは定冠詞を付<br />する</div><div class="col-2">376-378</div></div>');
document.write('<div class="row"><div class="col-2">11-41B</div><div class="col-8">代名詞的述語と定冠詞の機能</div><div class="col-2">379-402</div></div>');
document.write('<div class="row"><div class="col-2">11-42B</div><div class="col-8">Der Wandere型</div><div class="col-2">403-417</div></div>');
document.write('<div class="row"><div class="col-2">11-43B</div><div class="col-8">唯一、第一、最後の定冠詞</div><div class="col-2">418</div></div>');
document.write('<div class="row"><div class="col-2">11-44B</div><div class="col-8">序数も当然問題になる。</div><div class="col-2">419</div></div>');
document.write('<div class="row"><div class="col-2">11-45R</div><div class="col-8"><u>ein</u> bisschen → <u>das</u> bisschen</div><div class="col-2">420-425</div></div>');
document.write('<div class="row"><div class="col-2">11-46B</div><div class="col-8"><u>Der Schalk</u> sleht lhm aus den Augen</div><div class="col-2">426-429</div></div>');
document.write('<div class="row"><div class="col-2">11-47R</div><div class="col-8">「定」の方の定冠詞には：ihm dle Handなどを加<br />える要あり</div><div class="col-2">430-432</div></div>');
document.write('<div class="row"><div class="col-2">11-48B</div><div class="col-8">冠詞用法に関する、他の項目との関係〈一括）目次.</div><div class="col-2">433</div></div>');
document.write('<div class="row"><div class="col-2">11-49R</div><div class="col-8">英独と比較して<u>仏の定冠詞癖</u></div><div class="col-2">434-435</div></div></div>');