document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">16-1B</div><div class="col-8"><a href="../016/s0001.html">比較、形容詞、比較級</a></div><div class="col-2">1-187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0007.html">［01］普通の用法。（述語的）（附加語的）</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0021.html">［02］alsを省いて突然比較級を使ふ際。</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0030.html">［03］Nichts....ais, kein....als等。（程…なもの<br />はない。</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0039.html">［04］[eben] so gut wie, so viel wie.（als）…も同然</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0047.html">［05］（eben）so gut（wohl）.....wie（als）<br />（so wohl...als auch）</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0048.html">［06］<u>mehr aLs</u>.（前置接続詞的） weniger als</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0052.html">［07］so....wie, ebenso....wie（als）</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0060.html">［08］um so....., desto <u>als</u>なしにもちひる場合<br /><u>je</u>と対照せずして</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0072.html">［09］比較級を規定する副詞 immer（ますます）</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0073.html">［10］比較級の重複。（ますます）<br />1. tiefer und tiefer. 2. tief und tiefer.</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0084.html">［11］程度のみの比較（相違せる二概念の）</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0088.html">［12］weniger....als....（vielmehr）</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0091.html">［13］<u>noch</u></a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0103.html">［14］<u>gein\', lieber, liebsten</u> eher, am ehesten.</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0105.html">［15］普通の用法（附加的）als, als wieとwie, denn<br />との用法。</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0111.html">［16］「難」（否定句が入ることあり）<br />alsの次に来る文に注意。</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0115.html">［17］「難」<u>wie</u>（nur）と同形容詞の反復<br />wie以下の方に形容詞をおく。<br />mehr..X als..Y［<u>むしろ</u>］</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0120.html">［18］比較級の代りにmehrを用ひた方がよい時。</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0131.html">［19］<u>mehr oder weniger</u></a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0132.html">［20］bei weitem, weit, viel, lange nicht 等</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0139.html">［21］<u>絶対比較級</u> <u>näher</u> bezeichnen früher schon.</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0152.html">［22］比較級とals....je(irgend)etc.</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0153.html">［23］差を示すにはum---又は単に四格。（量的なもの<br />に限る。）</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0154.html">［24］<u>Mehr</u>の持つ価値的意義（wenigerも）</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0162.html">［25］二個の動詞定形を比ベる<u>wie</u></a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0163.html">［26］<u>als</u>の次の代名詞省略</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0166.html">［27］...wie nie(je) einer war…等。</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0169.html">［28］alsの次の指示代名詞省略（〃接続詞〃にも）</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0178.html">［29］Doppelt so....noch eimal so....<br />比較級を用ひず</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0180.html">［30］<u>ebensowenig</u> 二個所の否定（sowenig wie.）</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0184.html">［31］wieと人代名詞の関係文中の比較級。</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0184.html">［32］alsの次の格の問題</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0185.html">［33］je（desto, immer）---, je um so.</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0186.html">［34］zu（餘りに）, allzu,, viel zu, vier zu viel<br />等。 <u>genug</u></a></div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0187.html">［35］nicht weniger....als</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2">16-2B</div><div class="col-8"><a href="../016/s0188.html">schwerstzubehandelnde....及び<br />der bestmögliche Ausdruck..</a></div><div class="col-2">188-193</div></div>');
document.write('<div class="row"><div class="col-2">16-3B</div><div class="col-8"><a href="../016/s0194.html">どれも互いに劣らぬ、の意に比較級を。</a></div><div class="col-2">194-195</div></div>');
document.write('<div class="row"><div class="col-2">16-4B</div><div class="col-8"><a href="../016/s0196.html">autant vautこの比較級がmieux vaut<br />könnte ebenso gut. pourrait tout aussi bien</a></div><div class="col-2">196-202</div></div>');
document.write('<div class="row"><div class="col-2">16-5B</div><div class="col-8"><a href="../016/s0203.html">最高級</a></div><div class="col-2">203-315</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0205.html">［01］述語的用法。（他と較ベる際）</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0211.html">［02］述語的用法。（自己と較ベる際）</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0221.html">［03］附加語的用法。</a></div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0224.html">［04］認容的意味をもつ傾向（auch）<br />auchなきこともあり。</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0230.html">［05］定冠詞なく用ひる際（非常に、）</a></div><div class="col-2">230</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0231.html">［06］der....-steとam....stenとの区別に関する普通<br />の規則が必ずしも絶対的ならざる証明。<br />他と較べる際でも<u>am</u>=stenがよき場合あり。</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0234.html">［07］関係代名詞を伴う最高級。<br />（…した中の一番…）wasの先行詞を<br />伴うなり。</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0235.html">［08］"bei weitem"等。"weitaus"</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0239.html">［09］最高級のPeriphrase（wie…nichts in der Welt等（否定を伴う場合）</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0243.html">［10］von, unterの用法。</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0247.html">［11］=st副詞の結成形=（aufs--ste）</a></div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0252.html">［12］---von der Welt.等（最高級の強調）</a></div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0255.html">［13］je等を伴ふ規定。（不定詞）</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0268.html">［14］－stens.（aufs-steの代り）</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0270.html">［15］－stensの「最大限度」指示。</a></div><div class="col-2">270</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0287.html">［16］aufs--ste.とzum～sten.</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0295.html">［17］Gründlichst = aufs gründlichste</a></div><div class="col-2">295</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0301.html">［18］<u>Das Mindeste, was</u>...（又は<u>des</u>）<br />［nichits, Geringeres, ais....］</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0302.html">［19］aller=schönst</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0305.html">［20］<u>erst best</u>.</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../016/s0312.html">［21］auf--steを=ensの代りに。</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2">16-6B</div><div class="col-8"><a href="../016/s0313.html">［羅］satius est ［梵］varam, ［etc］</a></div><div class="col-2">313-315</div></div>');
document.write('<div class="row"><div class="col-2">16-7B</div><div class="col-8"><a href="../016/s0316.html">比較級の<u>変音</u>の問題 zarterかzärterか</a></div><div class="col-2">316-319</div></div>');
document.write('<div class="row"><div class="col-2">16-8B</div><div class="col-8"><a href="../016/s0320.html">nur eben gerade....genug<br />辛うじて、緩やかに....やっと</a></div><div class="col-2">320-323</div></div>');
document.write('<div class="row"><div class="col-2">16-9B</div><div class="col-8"><a href="../016/s0324.html">比較のals（参考事項）</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2">16-10B</div><div class="col-8"><a href="../016/s0325.html"><u>出来るだけ</u>325-340</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">16-11B</div><div class="col-8"><a href="../016/s0341.html"><u>およそ....なりとせぱ之れならめ<br />最高級表現の一形式</u></a></div><div class="col-2">341-344</div></div>');
document.write('<div class="row"><div class="col-2">16-12R</div><div class="col-8"><a href="../016/s0345.html">二者を比較して最高級を用ふ</a></div><div class="col-2">345-348</div></div>');
document.write('<div class="row"><div class="col-2">16-13B</div><div class="col-8"><a href="../016/s0349.html">構文の問題 eine nöheren Druck als 760mm</a></div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">16-14B</div><div class="col-8"><a href="../016/s0353.html">Zweitbest</a></div><div class="col-2">353-364</div></div>');
document.write('<div class="row"><div class="col-2">16-15B</div><div class="col-8"><a href="../016/s0365.html">öfter=絶対比較級（形）<br />öfterer= 比較級（副）365-367</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">16-16R</div><div class="col-8"><a href="../016/s0368.html">形式化した比較級 inner=等<br />nicht<u>eher</u>....als 云々するより前には云々しない<br />was....als...? was....wenn nicht....? 移轍<br />最高級の飾り、（関係代名詞）</a></div><div class="col-2">368-372</div></div>');
document.write('<div class="row"><div class="col-2">16-17B</div><div class="col-8"><a href="../016/s0373.html">「むしろ」<u>cher</u> <u>lieber</u></a></div><div class="col-2">373-379</div></div>');
document.write('<div class="row"><div class="col-2">16-18R</div><div class="col-8"><a href="../016/s0380.html">frei-e-st! sovie1....wie（als）....dass<br />....［um］....zu不定法 <u>程度の制限</u> 及び<br /><u>同数の表現</u></a></div><div class="col-2">380-390</div></div>');
document.write('<div class="row"><div class="col-2">16-19R</div><div class="col-8"><a href="../016/s0391.html">genug....（と名詞）<br />比較の<u>als</u>, <u>wie</u>と倍数半数その他お数詞<br />絶対最高級の冠置用法<br /><u>絶対最高級</u> ラテン式 附加語に用いるのが特有<br />only, first, last等か最高級の一種なること<br />絶対最高級の附加語用法は独ではあまり用いないが、<br />羅典系語では存在する。</a></div><div class="col-2">391-393</div></div>');
document.write('<div class="row"><div class="col-2">16-20B</div><div class="col-8"><a href="../016/s0394.html">denkbar～st menschenmöglich 等</a></div><div class="col-2">394-396</div></div>');
document.write('<div class="row"><div class="col-2">16-21B</div><div class="col-8"><a href="../016/s0397.html">mehr, mehrer, mehrest等の現象</a></div><div class="col-2">397-399</div></div>');
document.write('<div class="row"><div class="col-2">16-22B</div><div class="col-8"><a href="../016/s0400.html">nicht mehr u. nicht weniger<br />以上にも非ず以下にも非ず。</a></div><div class="col-2">400-402</div></div>');
document.write('<div class="row"><div class="col-2">16-23B</div><div class="col-8"><a href="../016/s0403.html">denn（=a1s）［MHD］dan</a></div><div class="col-2">403</div></div>');
document.write('<div class="row"><div class="col-2">16-24B</div><div class="col-8"><a href="../016/s0404.html"><u>Gern</u>, lieber, liebst</a></div><div class="col-2">404-406</div></div>');
document.write('<div class="row"><div class="col-2">16-25B</div><div class="col-8"><a href="../016/s0407.html">Der Wunder höchstes</a></div><div class="col-2">407-412</div></div>');
document.write('<div class="row"><div class="col-2">16-26B</div><div class="col-8"><a href="../016/s0413.html">Alsの次の構文 及びstattも、</a></div><div class="col-2">413-422</div></div>');
document.write('<div class="row"><div class="col-2">16-27R</div><div class="col-8"><a href="../016/s0423.html">zuとall zu［餘りにも］nimis<br />［英］<u>any</u> bette等 no good.<br />［英］as many as high as late as</a></div><div class="col-2">423-425</div></div>');
document.write('<div class="row"><div class="col-2">16-28B</div><div class="col-8"><a href="../016/s0426.html">comme autant de</a></div><div class="col-2">426-431</div></div>');
document.write('<div class="row"><div class="col-2">16-29R</div><div class="col-8"><a href="../016/s0432.html">mehr oder weniger［more or less］</a></div><div class="col-2">432-433</div></div>');
document.write('<div class="row"><div class="col-2">16-30B</div><div class="col-8"><a href="../016/s0434.html">so gut er eben kann.（曲かったなりにも）</a></div><div class="col-2">434-436</div></div>');
document.write('<div class="row"><div class="col-2">16-31R</div><div class="col-8"><a href="../016/s0437.html">［英］more often <u>than not</u>.<br />「…と同じ」のとの二つお表現法:<br />（A）関係代名詞<br />（B）als, wie<br />［英］in=<u>most</u><br />［英］The lowest of the low等<br />［英］比較級の=erとmore～<br />最高級の=estとmpst～<br />=譬喩援用＝　認容的KⅡ約束話法と比較級<br />（又はso.等）<br />編者注：このほか5件あり。</a></div><div class="col-2">437-447</div></div>');
document.write('<div class="row"><div class="col-2">16-32B</div><div class="col-8"><a href="../016/s0448.html">比較文のそもそも <u>ais</u> 及ひ GENITIVとvon</a></div><div class="col-2">448-450</div></div>');
document.write('<div class="row"><div class="col-2">16-33B</div><div class="col-8"><a href="../016/s0451.html">…の一つや二つ多かろうと少なかろうと…<br />1.à ～ près<br />2.es kommt an～</a></div><div class="col-2">451-452</div></div>');
document.write('<div class="row"><div class="col-2">16-34R</div><div class="col-8"><a href="../016/s0453.html">［希］比較文参考 <u>That</u> LONG<br />「…と同じ」の構文<br />原級（positiv）なき比較級・最高級の形<br />［羅］quamを省いて<br />Non amplius mille passuum abest.<br />「云々ほど好いものは無い」の表現<br />［英］ best suited<br />［仏］meilleur, pire, pis<br />［英］The best <u>runner</u><br />編者注：このほか28件あり。</a></div><div class="col-2">453-472</div></div>');
document.write('<div class="row"><div class="col-2">16-35B</div><div class="col-8"><a href="../016/s0473.html">形式の問題（最高級）eをはさまぬ <u>bedeutendst</u></a></div><div class="col-2">473</div></div>');
document.write('<div class="row"><div class="col-2">16-36R</div><div class="col-8"><a href="../016/s0474.html">Allerbestとin <u>aller</u> Frühe等<br />編者注：このほか10件あり。</a></div><div class="col-2">474-477</div></div></div>');