document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">14-1B</div><div class="col-8">=froh, =freudig, =lustig, =lüstern, =süchtig</div><div class="col-2">1-5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">=begerig(Gierig??)</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2">14-2B</div><div class="col-8">=gerecht</div><div class="col-2">6-11</div></div>');
document.write('<div class="row"><div class="col-2">14-3B</div><div class="col-8">beifallumraucht.</div><div class="col-2">12-34</div></div>');
document.write('<div class="row"><div class="col-2">14-4B</div><div class="col-8">wohlbesetzte Mittagtafel.</div><div class="col-2">35-53</div></div>');
document.write('<div class="row"><div class="col-2">14-5B</div><div class="col-8">特殊化規定を伴う形容詞一般の部<br />云々が云々なるwesensgleich型。<br />lichtempfindlich kniehoch型。Schneeblind,<br />farbenblind型 lebens=<u>nah</u>等 =fern, fremt<br />雑 <u>wutverdächtige</u> Hunde<br />wurzelecht型。 staatsgefährlivh. kriegswichtig</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">14-6B</div><div class="col-8">=artig</div><div class="col-2">79-83</div></div>');
document.write('<div class="row"><div class="col-2">14-7B</div><div class="col-8">=weise 副詞語尾。<br />「仏」par exception =ausnahmsweise<br />weiseとすれはよかりそうな場合<br />weiseの語尾<br />「英」 -wise <u>slantwise</u> over her curls.</div><div class="col-2">84-101</div></div>');
document.write('<div class="row"><div class="col-2">14-8B</div><div class="col-8">deutsch-japanisch型</div><div class="col-2">102-112</div></div>');
document.write('<div class="row"><div class="col-2">14-9B</div><div class="col-8">schneeweiss</div><div class="col-2">113-128</div></div>');
document.write('<div class="row"><div class="col-2">14-10B</div><div class="col-8">=bereit, =fertig, =klar.</div><div class="col-2">129-137</div></div>');
document.write('<div class="row"><div class="col-2">14-11B</div><div class="col-8">外末語糸統の形容詞。 momentan.</div><div class="col-2">138-162</div></div>');
document.write('<div class="row"><div class="col-2">14-12B</div><div class="col-8">=fest, =dicht etc, etc</div><div class="col-2">163-185</div></div>');
document.write('<div class="row"><div class="col-2">14-13B</div><div class="col-8">語幹形容詞 oranzig=「英」 rancid（butter）すえた。<br />［MHD］では=e語尾が多い！（副詞もしかり）<br /><u>語幹形容詞</u>。 lumm, (odd.), schlaf, straub（südd）<br />borstig.（sträuben, 毛を逆立てる）<br />外来系語：null, vage, strikt等。 ring, a<br />fehl, adv. 副詞。 外来・語幹形容詞</div><div class="col-2">186-204</div></div>');
document.write('<div class="row"><div class="col-2">14-14B</div><div class="col-8">geosskalibrig 数規定</div><div class="col-2">205-208</div></div>');
document.write('<div class="row"><div class="col-2">14-15B</div><div class="col-8">物質名その他の =ern語尾</div><div class="col-2">209-216</div></div>');
document.write('<div class="row"><div class="col-2">14-16B</div><div class="col-8">殆ど型のない合成形容詞 <u>siegrückkehrendes</u> Schiff</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2">14-17B</div><div class="col-8">zeitraubend型 ANT.: zeitsparend.</div><div class="col-2">218-222</div></div>');
document.write('<div class="row"><div class="col-2">14-18B</div><div class="col-8">性状の=ig及ひ類似形 1.=ös, =os<br />2. =英 callous, calleux, schwielig.</div><div class="col-2">223-233</div></div>');
document.write('<div class="row"><div class="col-2">14-19B</div><div class="col-8">spaltenlang ---数段抜きの---</div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2">14-20B</div><div class="col-8">=wert, =würdig. エスペラント =inda.</div><div class="col-2">235-240</div></div>');
document.write('<div class="row"><div class="col-2">14-21B</div><div class="col-8">余計な =lich</div><div class="col-2">241-245</div></div>');
document.write('<div class="row"><div class="col-2">14-22B</div><div class="col-8">=Widrig</div><div class="col-2">246-248</div></div>');
document.write('<div class="row"><div class="col-2">14-23B</div><div class="col-8">grünlich</div><div class="col-2">249-257</div></div>');
document.write('<div class="row"><div class="col-2">14-24B</div><div class="col-8">=bar及び「可能」の=lich</div><div class="col-2">258-274</div></div>');
document.write('<div class="row"><div class="col-2">14-25B</div><div class="col-8">=losと=leer</div><div class="col-2">275-280</div></div>');
document.write('<div class="row"><div class="col-2">14-26R</div><div class="col-8">=selig, \'ähnlich 1.「の如く」はähnlich wie...<br />が多い。</div><div class="col-2">281-288</div></div>');
document.write('<div class="row"><div class="col-2">14-27B</div><div class="col-8">=reich, =arm, =frei</div><div class="col-2">289-300</div></div>');
document.write('<div class="row"><div class="col-2">14-28B</div><div class="col-8">wesen<u>t</u>lichの<u>t</u></div><div class="col-2">301-306</div></div>');
document.write('<div class="row"><div class="col-2">14-29B</div><div class="col-8">=sam</div><div class="col-2">307-321</div></div>');
document.write('<div class="row"><div class="col-2">14-30B</div><div class="col-8"><u>hoch</u>t<u>raubend</u> <u>gutgehendes</u> Geschäft<br />schwerwiegender Beschluss</div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2">14-31B</div><div class="col-8">=mässig, =gemäss, =massen</div><div class="col-2">323-338</div></div>');
document.write('<div class="row"><div class="col-2">14-32B</div><div class="col-8">=lichと変音の問題</div><div class="col-2">339-342</div></div>');
document.write('<div class="row"><div class="col-2">14-33B</div><div class="col-8">=haft</div><div class="col-2">343-348</div></div>');
document.write('<div class="row"><div class="col-2">14-34B</div><div class="col-8">fähig</div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">14-3RB</div><div class="col-8">reif, =erlich</div><div class="col-2">353-354</div></div>');
document.write('<div class="row"><div class="col-2">14-36B</div><div class="col-8">=bedürftig</div><div class="col-2">355-357</div></div>');
document.write('<div class="row"><div class="col-2">14-37B</div><div class="col-8">=schwarzäugig</div><div class="col-2">358-373</div></div>');
document.write('<div class="row"><div class="col-2">14-38B</div><div class="col-8">Genauigkeit Geschwindigkeit等の中聞<u>ig</u></div><div class="col-2">374-375</div></div>');
document.write('<div class="row"><div class="col-2">14-3RB</div><div class="col-8">=kundig, =unkundig</div><div class="col-2">376-378</div></div>');
document.write('<div class="row"><div class="col-2">14-40B</div><div class="col-8">=ischの諸型</div><div class="col-2">379-380</div></div>');
document.write('<div class="row"><div class="col-2">14-41R</div><div class="col-8">英仏の拉（希）形容詞とその困難さ<br />「仏」<u>形容詞語尾</u><br />「雑」verständnis=innig等<br />=begeistert, verrückt, etc. süchtig, the <u>near</u> by office等</div><div class="col-2">381-384</div></div>');
document.write('<div class="row"><div class="col-2">14-42B</div><div class="col-8">=förmig</div><div class="col-2">385-388</div></div>');
document.write('<div class="row"><div class="col-2">14-43R</div><div class="col-8">「仏」 ventr<u>u</u><br />外来名詞から形容詞ヘ（種々の場合）<br />「英仏」 動物その他の=in[e]型 =scheu, =feindlich. =haitig<br />［英］=y perky. socky. <br />a <u>gawky boy</u> might be a spy<br />［仏］une étoffe <u>soie eet coton</u><br />rot-und gelbes Tulpenbeet。 ［英］=like<br />=voll =gleich。 仏=able 英=ible<br />エスペ:=ella. 独の=istischと英仏の=ist（e）<br />=istisch（人間を考えず）。形容詞の構成法<p> </p><p>編者注：このほか27件あり。</p></div><div class="col-2">389-421</div></div></div>');