document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">17-1B</div><div class="col-8">［仏］…<u>et</u> qui</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">17-2B</div><div class="col-8">［仏］関係代名詞（一般、雑）</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2">17-3B</div><div class="col-8">先行詞と関係代名詞 受け方の問題<br />関係文の受け方の一つの場合（単か複か）</div><div class="col-2">3-17</div></div>');
document.write('<div class="row"><div class="col-2">17-4B</div><div class="col-8">関係代名詞</div><div class="col-2">18-209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］wer, -der. da…及び、wo…</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］der, welcher.（一般、普通の場合）</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］文意を受けるwas及びwozu等。</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］wieと人代名詞。<br />（先づ、wieを接続詞として考う可き場合）<br />（全然関係代名詞化したもの）</div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］<u>wovon</u> 関係文其者が他の挿入文の副文章になる時。（...das, ...ob等）</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］was, <u>wessen</u>, ［<u>wem</u>］, was, （先行詞なし）</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］文意を受けるwasに相当する<u>wie…es</u>…</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］附加語的関係代名詞（welcher）</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］die, der等</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］das, was__ Wasと先行詞<br />dejenige, <br />desselben</div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］"wie....ihn"等の代りにdergleichenを用ひる例。</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］関係代名詞の古形 so等 （daも然り）</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］was....alles（等）</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］wie....ihn（等）....になほ比較級等を伴ふ場合</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］was ich kann等。</div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］一人称二人称（人代名詞の繰返し、及び三人称扱ひ）</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］<u>wo</u>とその結合（及びda.）</div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］附加的関係代名詞の副文章延長。</div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］「人を指すwas.　Alles, was.（動物を含む際は更に然り）</div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］文意を受けるWasの「前置」</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］deren（又はvon denen）の隔離先置。</div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］wie ihn <u>nur</u>....（....にして始めて....）</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］worumの代りにum <u>was</u>等</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］wie...とein solches, es.</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］二格welches welcherの例。</div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［26］welcherの使ひ方</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［27］<u>was</u> mich <u>betrifft</u>.等（mich betreffend）</div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［28］語順（主文章末に］ruhende Formをおく件）</div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［29］<u>als</u> welcher等（理由をさす）</div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［30］先行詞なきder, die, das.（及ひwelcher）</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［31］wer----, <u>den</u>----.（den, demは省き得る）</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［32］des（dessenの代り）</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［33］welch letzterer, welcher letztere等</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2">17-5B</div><div class="col-8">Ihr dummer Kerl, Ihr, das Ihr seid!</div><div class="col-2">210-220</div></div>');
document.write('<div class="row"><div class="col-2">17-6B</div><div class="col-8">Gesprungener Huf式を関係文で表現し得る！</div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2">17-7B</div><div class="col-8">英語：関係文の構造</div><div class="col-2">222-250</div></div>');
document.write('<div class="row"><div class="col-2">17-8B</div><div class="col-8">関係文の省略としてのdarunter.<br /><u>eingerechnet</u> <u>mit ein gerechnet</u></div><div class="col-2">251-254</div></div>');
document.write('<div class="row"><div class="col-2">17-9B</div><div class="col-8">梵語・羅典等に多い関係文構造<br />関係文と先行詞との位置</div><div class="col-2">255-265</div></div>');
document.write('<div class="row"><div class="col-2">17-10B</div><div class="col-8">Attraktion des Rerativs.<br />希的関係代名詞と同化<br />［独］迫加述語 （独立評辞） 四格</div><div class="col-2">266-271</div></div>');
document.write('<div class="row"><div class="col-2">17-11B</div><div class="col-8">NB 関代 変態的な場合</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2">17-12B</div><div class="col-8">副詞句を関係文にほといたもの（訳出の困難）</div><div class="col-2">273-278</div></div>');
document.write('<div class="row"><div class="col-2">17-13B</div><div class="col-8">関代二格の文法</div><div class="col-2">279-283</div></div>');
document.write('<div class="row"><div class="col-2">17-14B</div><div class="col-8"><u>それは</u>…何々か、云々した<u>のてす</u>。</div><div class="col-2">284-285</div></div>');
document.write('<div class="row"><div class="col-2">17-15B</div><div class="col-8">関係文内の<u>da</u></div><div class="col-2">286-293</div></div>');
document.write('<div class="row"><div class="col-2">17-16B</div><div class="col-8">羅典式の所謂る Reiat1vische Anknüpfung及ひ二重接続</div><div class="col-2">294-300</div></div>');
document.write('<div class="row"><div class="col-2">17-17B</div><div class="col-8">複雑な関係句</div><div class="col-2">301-310</div></div>');
document.write('<div class="row"><div class="col-2">17-18B</div><div class="col-8">関係文を、然らざる他の副文章によって延長する形式［Anakoluthie］</div><div class="col-2">311-317</div></div>');
document.write('<div class="row"><div class="col-2">17-19B</div><div class="col-8">関係代名詞の音味形態</div><div class="col-2">318-347</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］weilの意。（denn）因由形態も</div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］後続的。（dann, denn）</div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］後続的。（dannもdennも無し）</div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］主文章よりも過去の事実をさす。後続的的といふよりは、<u>説明的</u>。</div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］doch（aduersativ）</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］C\'est....que....形態。</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］規定的、限定的</div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］仮定的</div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］因由的.</div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］目的的.羅の場合 utの代り</div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］［移轍］或ひは其他の特別の筋路によって説明する必要あるもの：</div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］最髙級を規定する関係文型。</div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2">17-20R</div><div class="col-8">云々するところの最も…云々（最髙級と閲係した場合）が問題！！<br />最高級概念を受ける関係文（独では問題はないが、英仏では「不定表現」をする：</div><div class="col-2">348-349</div></div>');
document.write('<div class="row"><div class="col-2">17-21B</div><div class="col-8"><u>Alles, was recht ist</u></div><div class="col-2">350-352</div></div>');
document.write('<div class="row"><div class="col-2">17-22B</div><div class="col-8">etwasを<u>das</u>で受ける際は、特に指す何物かなり。</div><div class="col-2">353-358</div></div>');
document.write('<div class="row"><div class="col-2">17-23B</div><div class="col-8">［MHD］先行詞ある関代名詞</div><div class="col-2">359</div></div>');
document.write('<div class="row"><div class="col-2">17-24B</div><div class="col-8">welcher Baum+定形後置（古）<br />名詞を伴ふ不定関係代名詞</div><div class="col-2">360-361</div></div>');
document.write('<div class="row"><div class="col-2">17-25R</div><div class="col-8"><u>weiを受けるder</u></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2">17-26B</div><div class="col-8">Wes dergleichen Dinge mehr sind.<br /><u>oder was es ist</u>.－－だか何だが知らんが－－</div><div class="col-2">363-370</div></div>');
document.write('<div class="row"><div class="col-2">17-27R</div><div class="col-8">wer=どちらが<br />いづれが<br />関係代名詞としてのda（wo）...mit...など（英文→）<br />［仏］à cause de l\'impatience <u>qu\'elle avait</u>=<br />parce qu\'elle avait l\'impatience.<br />普通の<u>Was</u>.<br />dass....等の文の部分的名詞化に伴ふ関係代名詞の用法。<br />das, was...の文法［先行詞と関係代名詞との融合］関係代名詞の代りに疑問詞等を用い得る場合。<br />不定関係代名詞には種類多&lt;、認容形をの合えるべし</div><div class="col-2">371-375</div></div>');
document.write('<div class="row"><div class="col-2">17-28B</div><div class="col-8">Wer nicht kam, das war <u>er</u></div><div class="col-2">376-378</div></div>');
document.write('<div class="row"><div class="col-2">17-29B</div><div class="col-8">［希］関係代名詞一般参考</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2">17-30B</div><div class="col-8">［仏］関係代名詞諸問題</div><div class="col-2">380-383</div></div>');
document.write('<div class="row"><div class="col-2">17-31B</div><div class="col-8">関係代名詞を二度繰返す場合（同一の先行詞で）</div><div class="col-2">384-385</div></div>');
document.write('<div class="row"><div class="col-2">17-32B</div><div class="col-8"><u>welcher</u><br />並立の関係文をderとwelcherとでvariierenする傾向あり。</div><div class="col-2">386-392</div></div>');
document.write('<div class="row"><div class="col-2">17-33B</div><div class="col-8">［英］whatever, wheever, wherever等</div><div class="col-2">393-394</div></div>');
document.write('<div class="row"><div class="col-2">17-34B</div><div class="col-8">［英］独の<u>das, was</u>...に該当する<u>what</u></div><div class="col-2">395</div></div>');
document.write('<div class="row"><div class="col-2">17-35R</div><div class="col-8">worin等の代りにdarin等<br />不定関係代名詞としての附加語的welchei Welches Teil den andern...., der…</div><div class="col-2">396-398</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（した方の側が〉<br />wer, was等不定関係代名詞と同じ<br />derselbeを関係代名詞として用ひた異例<br />わざと拙を狙った関係文の重畳<br />welcheの普通な例</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">17-36B</div><div class="col-8">時・處を先行詞とする関係文</div><div class="col-2">399-400</div></div>');
document.write('<div class="row"><div class="col-2">17-37R</div><div class="col-8"><u>dergleichen</u>.（wieと人代名詞に同）<br />不定関係代名詞wasと名詞の二格。<br />was....an[von]と同じ。</div><div class="col-2">401-402</div></div>');
document.write('<div class="row"><div class="col-2">17-38B</div><div class="col-8"><u>was</u> man <u>so</u>～<u>nennt</u>.<br /><u>w1e</u></div><div class="col-2">403-405</div></div>');
document.write('<div class="row"><div class="col-2">17-39R</div><div class="col-8">welches alles 多くの先行訶を受けるwas.<br />welch alles<br />Was wir lieben!<br />worum の代りにwarum.<br />um was<br /><u>welches</u>と<u>das</u>（無方針な例）<br />述語の規定詞となる関係句。<br />wo及ひwoselbst<br />一格と四格とは共通にすへからさる事。<br />関係代名詞に関する歴史的考察資料［希・羅］<br />疑問詞に附加される関係句［<u>wer, der</u>］<br /><u>関係文とzu+不定句との中間形態<br />［英］w1th whitch to defend themselves等<br /><u>関係代名詞一般論</u><br />ラテンても、名詞の前に置くことあり。<br />前に<u>der</u>かある時に後を<u>welcher</u>に<br /><u>間投文を関係代名詞で二部分に分解</u><br />...., um <u>darin</u> zu atmen<br />云々するための（adnominal）<br />werの用法の異例。（derの代りに）<br />誰でも・・・ものは（welcher）<br />不定関係代名詞として用ひる<br /><u>附加語的welcher</u><br />名詞的<u>welcher</u><br />関係代名詞と人代名詞とを並べて関係句を作る例。－<u>was</u> ich sagen wollte.<br />編者注：このほか10件あり。</u></div><div class="col-2">406-415</div></div></div>');