document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">17-1B</div><div class="col-8"><a href="../017/s0001.html">［仏］…<u>et</u> qui</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">17-2B</div><div class="col-8"><a href="../017/s0002.html">［仏］関係代名詞（一般、雑）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2">17-3B</div><div class="col-8"><a href="../017/s0003.html">先行詞と関係代名詞 受け方の問題<br />関係文の受け方の一つの場合（単か複か）</a></div><div class="col-2">3-17</div></div>');
document.write('<div class="row"><div class="col-2">17-4B</div><div class="col-8"><a href="../017/s0018.html">関係代名詞</a></div><div class="col-2">18-209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0020.html">［01］wer, -der. da…及び、wo…</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0029.html">［02］der, welcher.（一般、普通の場合）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0036.html">［03］文意を受けるwas及びwozu等。</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0053.html">［04］wieと人代名詞。<br />（先づ、wieを接続詞として考う可き場合）<br />（全然関係代名詞化したもの）</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0070.html">［05］<u>wovon</u> 関係文其者が他の挿入文の副文章になる時。（...das, ...ob等）</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0075.html">［06］was, <u>wessen</u>, ［<u>wem</u>］, was, （先行詞なし）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0084.html">［07］文意を受けるwasに相当する<u>wie…es</u>…</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0088.html">［08］附加語的関係代名詞（welcher）</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0094.html">［09］die, der等</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0095.html">［10］das, was__ Wasと先行詞<br />dejenige, <br />desselben</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0103.html">［11］"wie....ihn"等の代りにdergleichenを用ひる例。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0106.html">［12］関係代名詞の古形 so等 （daも然り）</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0109.html">［13］was....alles（等）</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0111.html">［14］wie....ihn（等）....になほ比較級等を伴ふ場合</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0112.html">［15］was ich kann等。</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0120.html">［16］一人称二人称（人代名詞の繰返し、及び三人称扱ひ）</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0135.html">［17］<u>wo</u>とその結合（及びda.）</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0151.html">［18］附加的関係代名詞の副文章延長。</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0152.html">［19］「人を指すwas.　Alles, was.（動物を含む際は更に然り）</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0158.html">［20］文意を受けるWasの「前置」</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0160.html">［21］deren（又はvon denen）の隔離先置。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0162.html">［22］wie ihn <u>nur</u>....（....にして始めて....）</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0163.html">［23］worumの代りにum <u>was</u>等</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0164.html">［24］wie...とein solches, es.</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0165.html">［25］二格welches welcherの例。</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0169.html">［26］welcherの使ひ方</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0170.html">［27］<u>was</u> mich <u>betrifft</u>.等（mich betreffend）</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0175.html">［28］語順（主文章末に］ruhende Formをおく件）</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0176.html">［29］<u>als</u> welcher等（理由をさす）</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0184.html">［30］先行詞なきder, die, das.（及ひwelcher）</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0197.html">［31］wer----, <u>den</u>----.（den, demは省き得る）</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0205.html">［32］des（dessenの代り）</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0207.html">［33］welch letzterer, welcher letztere等</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2">17-5B</div><div class="col-8"><a href="../017/s0210.html">Ihr dummer Kerl, Ihr, das Ihr seid!</a></div><div class="col-2">210-220</div></div>');
document.write('<div class="row"><div class="col-2">17-6B</div><div class="col-8"><a href="../017/s0221.html">Gesprungener Huf式を関係文で表現し得る！</a></div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2">17-7B</div><div class="col-8"><a href="../017/s0222.html">英語：関係文の構造</a></div><div class="col-2">222-250</div></div>');
document.write('<div class="row"><div class="col-2">17-8B</div><div class="col-8"><a href="../017/s0251.html">関係文の省略としてのdarunter.<br /><u>eingerechnet</u> <u>mit ein gerechnet</u></a></div><div class="col-2">251-254</div></div>');
document.write('<div class="row"><div class="col-2">17-9B</div><div class="col-8"><a href="../017/s0255.html">梵語・羅典等に多い関係文構造<br />関係文と先行詞との位置</a></div><div class="col-2">255-265</div></div>');
document.write('<div class="row"><div class="col-2">17-10B</div><div class="col-8"><a href="../017/s0266.html">Attraktion des Rerativs.<br />希的関係代名詞と同化<br />［独］迫加述語 （独立評辞） 四格</a></div><div class="col-2">266-271</div></div>');
document.write('<div class="row"><div class="col-2">17-11B</div><div class="col-8"><a href="../017/s0272.html">NB 関代 変態的な場合</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2">17-12B</div><div class="col-8"><a href="../017/s0273.html">副詞句を関係文にほといたもの（訳出の困難）</a></div><div class="col-2">273-278</div></div>');
document.write('<div class="row"><div class="col-2">17-13B</div><div class="col-8"><a href="../017/s0279.html">関代二格の文法</a></div><div class="col-2">279-283</div></div>');
document.write('<div class="row"><div class="col-2">17-14B</div><div class="col-8"><a href="../017/s0284.html"><u>それは</u>…何々か、云々した<u>のてす</u>。</a></div><div class="col-2">284-285</div></div>');
document.write('<div class="row"><div class="col-2">17-15B</div><div class="col-8"><a href="../017/s0286.html">関係文内の<u>da</u></a></div><div class="col-2">286-293</div></div>');
document.write('<div class="row"><div class="col-2">17-16B</div><div class="col-8"><a href="../017/s0294.html">羅典式の所謂る Reiat1vische Anknüpfung及ひ二重接続</a></div><div class="col-2">294-300</div></div>');
document.write('<div class="row"><div class="col-2">17-17B</div><div class="col-8"><a href="../017/s0301.html">複雑な関係句</a></div><div class="col-2">301-310</div></div>');
document.write('<div class="row"><div class="col-2">17-18B</div><div class="col-8"><a href="../017/s0311.html">関係文を、然らざる他の副文章によって延長する形式［Anakoluthie］</a></div><div class="col-2">311-317</div></div>');
document.write('<div class="row"><div class="col-2">17-19B</div><div class="col-8"><a href="../017/s0318.html">関係代名詞の音味形態</a></div><div class="col-2">318-347</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0320.html">［01］weilの意。（denn）因由形態も</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0321.html">［02］後続的。（dann, denn）</a></div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0325.html">［03］後続的。（dannもdennも無し）</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0326.html">［04］主文章よりも過去の事実をさす。後続的的といふよりは、<u>説明的</u>。</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0333.html">［05］doch（aduersativ）</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0333.html">［06］C\'est....que....形態。</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0334.html">［07］規定的、限定的</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0339.html">［08］仮定的</a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0340.html">［09］因由的.</a></div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0341.html">［10］目的的.羅の場合 utの代り</a></div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0345.html">［11］［移轍］或ひは其他の特別の筋路によって説明する必要あるもの：</a></div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0347.html">［12］最髙級を規定する関係文型。</a></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2">17-20R</div><div class="col-8"><a href="../017/s0348.html">云々するところの最も…云々（最髙級と閲係した場合）が問題！！<br />最高級概念を受ける関係文（独では問題はないが、英仏では「不定表現」をする：</a></div><div class="col-2">348-349</div></div>');
document.write('<div class="row"><div class="col-2">17-21B</div><div class="col-8"><a href="../017/s0350.html"><u>Alles, was recht ist</u></a></div><div class="col-2">350-352</div></div>');
document.write('<div class="row"><div class="col-2">17-22B</div><div class="col-8"><a href="../017/s0353.html">etwasを<u>das</u>で受ける際は、特に指す何物かなり。</a></div><div class="col-2">353-358</div></div>');
document.write('<div class="row"><div class="col-2">17-23B</div><div class="col-8"><a href="../017/s0359.html">［MHD］先行詞ある関代名詞</a></div><div class="col-2">359</div></div>');
document.write('<div class="row"><div class="col-2">17-24B</div><div class="col-8"><a href="../017/s0360.html">welcher Baum+定形後置（古）<br />名詞を伴ふ不定関係代名詞</a></div><div class="col-2">360-361</div></div>');
document.write('<div class="row"><div class="col-2">17-25R</div><div class="col-8"><a href="../017/s0362.html"><u>weiを受けるder</u></a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2">17-26B</div><div class="col-8"><a href="../017/s0363.html">Wes dergleichen Dinge mehr sind.<br /><u>oder was es ist</u>.－－だか何だが知らんが－－</a></div><div class="col-2">363-370</div></div>');
document.write('<div class="row"><div class="col-2">17-27R</div><div class="col-8"><a href="../017/s0371.html">wer=どちらが<br />いづれが<br />関係代名詞としてのda（wo）...mit...など（英文→）<br />［仏］à cause de l\'impatience <u>qu\'elle avait</u>=<br />parce qu\'elle avait l\'impatience.<br />普通の<u>Was</u>.<br />dass....等の文の部分的名詞化に伴ふ関係代名詞の用法。<br />das, was...の文法［先行詞と関係代名詞との融合］関係代名詞の代りに疑問詞等を用い得る場合。<br />不定関係代名詞には種類多&lt;、認容形をの合えるべし</a></div><div class="col-2">371-375</div></div>');
document.write('<div class="row"><div class="col-2">17-28B</div><div class="col-8"><a href="../017/s0376.html">Wer nicht kam, das war <u>er</u></a></div><div class="col-2">376-378</div></div>');
document.write('<div class="row"><div class="col-2">17-29B</div><div class="col-8"><a href="../017/s0379.html">［希］関係代名詞一般参考</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2">17-30B</div><div class="col-8"><a href="../017/s0380.html">［仏］関係代名詞諸問題</a></div><div class="col-2">380-383</div></div>');
document.write('<div class="row"><div class="col-2">17-31B</div><div class="col-8"><a href="../017/s0384.html">関係代名詞を二度繰返す場合（同一の先行詞で）</a></div><div class="col-2">384-385</div></div>');
document.write('<div class="row"><div class="col-2">17-32B</div><div class="col-8"><a href="../017/s0386.html"><u>welcher</u><br />並立の関係文をderとwelcherとでvariierenする傾向あり。</a></div><div class="col-2">386-392</div></div>');
document.write('<div class="row"><div class="col-2">17-33B</div><div class="col-8"><a href="../017/s0393.html">［英］whatever, wheever, wherever等</a></div><div class="col-2">393-394</div></div>');
document.write('<div class="row"><div class="col-2">17-34B</div><div class="col-8"><a href="../017/s0395.html">［英］独の<u>das, was</u>...に該当する<u>what</u></a></div><div class="col-2">395</div></div>');
document.write('<div class="row"><div class="col-2">17-35R</div><div class="col-8"><a href="../017/s0396.html">worin等の代りにdarin等<br />不定関係代名詞としての附加語的welchei Welches Teil den andern...., der…</a></div><div class="col-2">396-398</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../017/s0397.html">（した方の側が〉<br />wer, was等不定関係代名詞と同じ<br />derselbeを関係代名詞として用ひた異例<br />わざと拙を狙った関係文の重畳<br />welcheの普通な例</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">17-36B</div><div class="col-8"><a href="../017/s0399.html">時・處を先行詞とする関係文</a></div><div class="col-2">399-400</div></div>');
document.write('<div class="row"><div class="col-2">17-37R</div><div class="col-8"><a href="../017/s0401.html"><u>dergleichen</u>.（wieと人代名詞に同）<br />不定関係代名詞wasと名詞の二格。<br />was....an[von]と同じ。</a></div><div class="col-2">401-402</div></div>');
document.write('<div class="row"><div class="col-2">17-38B</div><div class="col-8"><a href="../017/s0403.html"><u>was</u> man <u>so</u>～<u>nennt</u>.<br /><u>w1e</u></a></div><div class="col-2">403-405</div></div>');
document.write('<div class="row"><div class="col-2">17-39R</div><div class="col-8"><a href="../017/s0406.html">welches alles 多くの先行訶を受けるwas.<br />welch alles<br />Was wir lieben!<br />worum の代りにwarum.<br />um was<br /><u>welches</u>と<u>das</u>（無方針な例）<br />述語の規定詞となる関係句。<br />wo及ひwoselbst<br />一格と四格とは共通にすへからさる事。<br />関係代名詞に関する歴史的考察資料［希・羅］<br />疑問詞に附加される関係句［<u>wer, der</u>］<br /><u>関係文とzu+不定句との中間形態<br />［英］w1th whitch to defend themselves等<br /><u>関係代名詞一般論</u><br />ラテンても、名詞の前に置くことあり。<br />前に<u>der</u>かある時に後を<u>welcher</u>に<br /><u>間投文を関係代名詞で二部分に分解</u><br />...., um <u>darin</u> zu atmen<br />云々するための（adnominal）<br />werの用法の異例。（derの代りに）<br />誰でも・・・ものは（welcher）<br />不定関係代名詞として用ひる<br /><u>附加語的welcher</u><br />名詞的<u>welcher</u><br />関係代名詞と人代名詞とを並べて関係句を作る例。－<u>was</u> ich sagen wollte.<br />編者注：このほか10件あり。</u></a></div><div class="col-2">406-415</div></div></div>');