document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">19-1B</div><div class="col-8"><a href="../019/s0001.html">副詞、主要なる副詞</a></div><div class="col-2">1-106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0002.html">［01］代名詞的副詞（述語）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0004.html">［02］間投的副詞あり。</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0005.html">［03］<u>überrhein</u>, rheinüber. main über</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0006.html">［04］halb und halb（薄々）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0009.html">［05］<u>überhaupt</u>.</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0023.html">［06］hintenauf. nebenan.等</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0028.html">［07］all=bereits型</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0030.html">［08］<u>vorderhand</u>.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0031.html">［09］<u>schlankweg</u>.</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0050.html">［10］weiterhin, späterhin, daraufhin, mithin, vorhin（nebenhin）</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0062.html">［11］meerab等。 querfeidein</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0062.html">［12］schliesslich, am Ende.（論理的）</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0071.html">［13］tagaus, tagein等。 明けても暮れても。<br />［英］［day in, day out］</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0076.html">［14］Wand an Wand mit....</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0078.html">［15］holterdiploter, usw. 擬音的副詞句。</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0087.html">［16］<u>Hals, übeir Kopf</u>等の句。</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0106.html">［17］二格形の結成形</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0106.html">［18］現在は完全に副詞なる筈のものを、語尾を取りたる例外。</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0106.html">［19］=hei beiher, seither, nebenher, anher（O） weither, nachher, vorher</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2">19-2B</div><div class="col-8"><a href="../019/s0107.html">論理関係の副詞 gern. 無意識に、知らず知らず。やむを得ず im gegenteil. allenfalls そうでなくてさえ。ほか38件</a></div><div class="col-2">107-158</div></div>');
document.write('<div class="row"><div class="col-2">19-3B</div><div class="col-8"><a href="../019/s0159.html">副詞 一般的法則</a></div><div class="col-2">159-220</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0160.html">［01］時の副詞</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0161.html">［02］auf "=st"</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0162.html">［03］成句的副詞。</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0164.html">［04］副詞（所）を主語にできない所から起る一種の言い回し</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0186.html">［05］genugと語順</a></div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0187.html">［06］hinnen, dannen, wannen, 等</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0199.html">［07］<u>inne</u>（innenと区別して）</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0199.html">［08］形容詞を規定する副詞</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0200.html">［09］beruflich=Berus wegen</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0200.html">［10］動詞を規定する際。</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0201.html">［11］<u>見地より</u>（意味の問題）nachと同じものあり。</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0211.html">［12］numen agentisを言いかえる副詞<br />（polizeihlich hÖheienorts.）</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0220.html">［13］副詞の<u>制限的</u></a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2">19-4B</div><div class="col-8"><a href="../019/s0221.html">時間の副詞<br />たまたま（von ungefähr）。<br />何らかの‥irgendwie geartet. 直ちに。<br />先刻、先程、今しがた。まだ（noch nicht）<br />昨夜（diese nacht）。だしぬけに、唐突に<br />編者注：このほか34件あり。</a></div><div class="col-2">221-246</div></div>');
document.write('<div class="row"><div class="col-2">19-5B</div><div class="col-8"><a href="../019/s0247.html">方向の考え方。 kommen, gehen, hinとher</a></div><div class="col-2">247-275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0248.html">［01］kommenの逆用（kommenの意味）</a></div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0255.html">［02］<u>gehen</u></a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0255.html">［03］英語との比較</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0256.html">［04］hin, hei等の参考。</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0266.html">［05］Akkusativで</a></div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0268.html">［06］古典特有の「通過方向」表現の副詞。<br />π，η，qua，</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0273.html">［07］b1eibe <u>dort</u> weg!</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2">19-6B</div><div class="col-8"><a href="../019/s0276.html">副詞的接続詞の用法、特有性</a></div><div class="col-2">276-305</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0277.html">［01］darum, deshalb, des wegen,<br />さうかと言って。 そのためになにも。</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0285.html">［02］<u>darein</u></a></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0285.html">［03］Dafür.（そのために）</a></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0285.html">［04］übel <u>daran</u> sein.</a></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0286.html">［05］<u>dahin</u>. = <u>so</u>と同意の。</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0292.html">［06］dabeiそれにも拘ず。</a></div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0292.html">［07］deshalb（其の件に関して）</a></div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0292.html">［08］dafür（um diesen Preis.）</a></div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0293.html">［09］dafüber（それに関して）</a></div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0293.html">［10］<u>In</u> der Kanne ist noch Kaffee <u>drin</u>.</a></div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0294.html">［11］<u>daneben</u>.（それる、）</a></div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0294.html">［12］<u>darum</u>, <u>deshalb</u>, deswegen</a></div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0296.html">［13］熟語の要素としてのdaran, drauf, dahin</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0296.html">［14］dessenungeachtet. demungeachtet.</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0297.html">［15］<u>drin</u>（darinに非ず）</a></div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0297.html">［16］hiermitこれで・・これを以て</a></div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0298.html">［17］und damit, ［それと同時に］ 従ってまた</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0299.html">［18］必ず省略形（dr～）をようするもの</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0300.html">［19］dazu, hierzu 加うるに。</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0301.html">［20］［英］のthere～ therefore</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0304.html">［21］dafürの代りにfür等</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../019/s0305.html">［22］そもそもdar～が「こと」を受ける傾向があって「もの」には不適であると言うこと：</a></div><div class="col-2">305</div></div>');
document.write('<div class="row"><div class="col-2">19-7B</div><div class="col-8"><a href="../019/s0306.html">副詞の形<br />, ［AHD］ofto, gerno, 等<br />［MHD］dick<u>e</u>等 =e 多し<br />mit+抽象名 avec précaution<br />編者注：このほか33件あり。</a></div><div class="col-2">306-344</div></div>');
document.write('<div class="row"><div class="col-2">19-8B</div><div class="col-8"><a href="../019/s0345.html">=lings</a></div><div class="col-2">345-350</div></div>');
document.write('<div class="row"><div class="col-2">19-9B</div><div class="col-8"><a href="../019/s0351.html">空間関係副詞<br />簡単なもの …の中ほどの所<br />［英］あちら、（こちら） <u>over</u> yonder <u>over</u> there<br />anderswo sonstwo [a-] anderweit 等 ［英］up huer<br />到る處 allewärts allerwegen überall allerorten<br />遠くから von weitem. aus der Ferne.<br />印刷物中の空間指定<br />あちこち</a></div><div class="col-2">351-358</div></div>');
document.write('<div class="row"><div class="col-2">19-10B</div><div class="col-8"><a href="../019/s0359.html">現在の副詞と話の中の副詞</a></div><div class="col-2">359-363</div></div>');
document.write('<div class="row"><div class="col-2">19-11B</div><div class="col-8"><a href="../019/s0364.html">程度の副詞</a></div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2">19-12R</div><div class="col-8"><a href="../019/s0365.html">独特有の間投的副詞 <u>leider</u> 等<br />心理関係副詞<br />von ungefähr（ふと）<br />副詞の名詞的表現 Il arriva <u>le premier</u>. hier=→ h = hüben, haussen insgesamt allesamt samt und sonders等<br />wohl oder übel schlecht und recht früher oder später等の句<br />schlecht und recht<br />無冠詞名詞の副詞的用法<br />編者注：このほか6件あり。</a></div><div class="col-2">365-374</div></div></div>');