document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">21-1B</div><div class="col-8"><a href="../022/s0001.html">［雑］<u>doch</u>1-102</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0002.html">副文章内のdoch（…筈の、…の癖に）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0005.html">doch［woh1］勿論…だらうじゃないか。</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0007.html">どうも！</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0009.html">その癖。 <u>doch</u>, <u>und doch</u> それでもやはり</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0014.html">不審る。（主文章）…のだがなあ。</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0015.html">「やっぱり。」</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0022.html">trotzdem. やはり。 さすがだ</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0025.html">doch［wohl］nicht.（まさか）</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0030.html">doch（zu...）いくらなんでもあまり</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0031.html">jaと同じ（強めるため）…つてば！ etc.</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0034.html">願望の意（konj.）</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0036.html"><u>どうぞ</u> <u>bitte</u>. （f1ehend.）</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0037.html">Lteinisches "Nonne"</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0040.html">転置とdochが、dennを用ふるに等しくなる。</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0041.html">不審りのdoch（疑問文に）不審、間投的</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s00101.html">doch語考</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2">22-2B</div><div class="col-8"><a href="../022/s0103.html">［雑］<u>da</u></a></div><div class="col-2">103-135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0104.html"><u>vergegenwärtigend</u></a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0106.html">其處へ持って来ると。</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0108.html">関係文中の_____</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0109.html">それはどうも.…さうだとすると…これは…</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0110.html">関係文中（fast p1eonastisch）</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0111.html">具体的叙述を開始するための機みの da.</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0121.html">da ”<u>その點なら</u>。”</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0122.html">voilà.</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0122.html">da....also....さうするとつまり</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0123.html">vergegenwärtigend <u>Le voilà</u></a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0125.html"><u>Da</u> hingisch<br />（und war\'s mir mit grausen bewusst）</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0129.html">hierと同じ</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0129.html">darauf, darin等のdar-に関する一般問題</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0133.html">［雜］<u>das</u></a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0134.html">感嘆的das.感嘆的非人称主語のdas</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0134.html">dass....das</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0134.html">Das ist alles. voilà tout.</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0135.html">Das ist eine Schmied <u>hier</u></a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0135.html">強い das ist ［仏］＝C\'est là.</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2">22-3B</div><div class="col-8"><a href="../022/s0136.html"><u>alle</u></a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2">22-4B</div><div class="col-8"><a href="../022/s0137.html"><u>Also</u>（接続詞に）</a></div><div class="col-2">137-146</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0138.html">説明（…というのは即ち）</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0142.html">繰返しの際のalso</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0143.html">also wieder auf sein Thema kommend:</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2">22-5B</div><div class="col-8"><a href="../022/s0147.html"><u>auch</u> Das war auch alles.<br />しかしそれだけのことだった。</a></div><div class="col-2">147-152</div></div>');
document.write('<div class="row"><div class="col-2">22-6B</div><div class="col-8"><a href="../022/s0153.html">auch</a></div><div class="col-2">153-216</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0154.html">［希］καιの微妙な用法<br />日本語の「も」と対比して<br />それに、しやっくり「も」止んだしするから…云々</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0156.html">前置的普通のauch</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0158.html">0h....auch?</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0160.html"><u>同概念を対照するauch</u>.</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0167.html">auch -- nuch. ［も」、「なほ」</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0168.html">auch それが<u>また</u>本当だ</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0172.html">（dann）auch <u>dann</u>の意。（その上に又、）</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0177.html">auch noch おまけに 時間的</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0179.html">denn <u>auch</u>［果たして］の略 予期したごとく。（<u>道理</u>でというauch）</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0184.html">den Teufel <u>auch</u>!</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0187.html"><u>aber auch</u></a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0189.html">疑問詞とauch.（denn）</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0194.html">auch nur（或はauch, 又は単にnur）</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0201.html">auch（それに）並列的接続詞と倒置<br />それに…云々しなければなりませんし。</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0206.html">反語的な間投文に（spöttelnd）</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0207.html">間投文に。（皮肉モコモルコトアリ）批評的。</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0213.html"><u>wenn</u>....auch....!（但し…）［Wunschsatz］<br />auch=nur</a></div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0214.html">だからまた。（多少<u>因由</u>的）</a></div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2">22-7B</div><div class="col-8"><a href="../022/s0217.html">［雑］<u>auch</u></a></div><div class="col-2">217-244</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0218.html">aber auch（wirklich） 懸値なし！</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0223.html">…です<u>が</u>。（極く軽きaber）</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0224.html">（nun）aber ところで、（対照の）</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0228.html">oder aber（それとも）</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0230.html">aber= und zwar</a></div><div class="col-2">230</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0231.html">aber auch（然し同時にまた…）</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0233.html">間投の<u>aber</u>（ja aber）</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0243.html">aber= <u>und</u> autem</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0244.html">aber= <u>sondern</u> wohr aber</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2">22-18B</div><div class="col-8"><a href="../022/s0245.html"><u>Aber</u></a></div><div class="col-2">245-276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0246.html">まことに失礼ではございますが等</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0259.html"><u>denn</u></a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0260.html">如何となれぱ</a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0261.html">---たい（？）</a></div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0264.html"><u>denn auch</u> 期待に違はざるを謂ふ<br />もちろん、当然、安の條、いよいよ</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0266.html">後続的（dann）の意を強める denn</a></div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0268.html">後続のdennの代りにdannを用ひた例</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0269.html">denn=also.さらば、然らば、 ［so....denn］</a></div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0272.html">denn {durchaus doch auch}</a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0273.html">so....denn.</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0273.html">so....denn!<br />さう言ふわけで、とにかくまあさういふ風にして…</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0275.html">［雑］<u>dann</u></a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0276.html">fas tp1eonastisch</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0276.html">dann 仏の<u>ensuite</u></a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../022/s0276.html">dann: =so</a></div><div class="col-2">276</div></div></div>');