document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">21-1B</div><div class="col-8"><a href="../021/s0001.html"><u>immer</u></a></div><div class="col-2">1-20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0002.html">immer 常に。</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0003.html">認容的<u>immer</u></a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0006.html">jedenfalls. immerhin（併しいづれにせよ）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0010.html">immer（toujours）<u>やはり</u> 今までに従って、<br />gleichfalls.</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0015.html">命令法と共に。</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0017.html">空間的。（immer gradaus）</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0018.html">immer = je 各々</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0020.html">［雑］irgend（＝） nirgend（s）</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">21-2B</div><div class="col-8"><a href="../021/s0021.html">［雑］<u>mal</u>と<u>einmal</u></a></div><div class="col-2">21-49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0022.html">（nun）einmal「どうせ」</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0023.html">erst mal wieder mal</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0024.html">zunächst einmal. erst einmal vorläufig einmal</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0025.html">nlcht einmal</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0028.html">wieder einmal（erst einmal）</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0030.html"><u>nicht einmal</u>.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0035.html">endlich einmal schliesslich einmal</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0041.html">gerade einmal gelegentlich einmal<br />später einmal たまに いつか一度</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0043.html">vorlänglig einmal zunächst einmal</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">21-3B</div><div class="col-8"><a href="../021/s0050.html">［雑］<u>ja</u></a></div><div class="col-2">50-87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0051.html">…ja…！（どうも畏れ入った）　実に！</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0053.html">自明の事柄として言ふ際。</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0059.html">「否むしろ」（wo nicht gar, と同じ）<br />Man könnte fast sagen.→（並列接続的）</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0067.html"><u>ja</u> nicht.（金輪際） ja（命令法と）<br /><u>nur ja</u></a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0071.html">関係文中のja（doch）</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0072.html">疑問文の先頭に（せき込むトキ） ja［aber］</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0073.html">如何となれば…、それが証拠に。 auchに似たり</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0075.html">反語的「…ではないか！」（助勢詞）「ハア」</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0076.html">肯定命令法とja.</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0082.html">［雑］<u>je</u></a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0083.html">von je, von jeher.</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0083.html">je nachdem，（副詞的、接続詞的）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0083.html">je（nieの反対）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0086.html">je <u>各々</u> <u>respektive</u>.ja wohl? da ja....<br />ja（うるさいとき、よい加減な返事）<br /><u>ja aber</u></a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2">21-4B</div><div class="col-8"><a href="../021/s0088.html"><u>gerade</u></a></div><div class="col-2">88-119</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0089.html">noch gerade....［genug.］</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0090.html">just.（前置的） ちようど</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0092.html">かへって…が 「が」</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0094.html">丁度（偶然） <u>ausgerechnet</u>.</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0099.html">nicht gerade必ずしも…と言ふ程ではない。<br />-1itotes- まさか…に非ず</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0102.html">普通の場合（時間的）ちようど</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0105.html">ちようど直ぐ right here.</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0105.html">gerade deshlb, weil 等（前置的接続詞）</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0106.html">gerade....皮肉 仏の<u>bien</u></a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0106.html">gerade so wie～</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0107.html">ちょうど（時間的ならざるもの）</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0108.html">gar</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0109.html">Adverbal さヘ一一一する。</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0109.html">überhaupt nicht = gar nicht</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0110.html"><u>nicht gar</u> nicht so gar.<br />ganzと同じ（肯定の際）<br />und gar = nun gar, vollends.</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0112.html"><u>gar</u></a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0113.html">gar zuとgar so gal=sogar.gar［sogar］［wohigar］.</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0114.html">sogar wohl gar</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0115.html">so gar gar nicht.</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0117.html">［雑］ ganz</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0118.html">gar nicht gar kein ganz und gar gut.（nicht....gut）</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2">21-5B</div><div class="col-8"><a href="../021/s0120.html">［雜］<u>erst</u></a></div><div class="col-2">120-165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0121.html">わざわざ <u>vollende</u>（否定の強調）</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0123.html">それこそ（大変なことになる） vollends.<br />況ンヤ、ニ至ッテハ</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0125.html">先以て…して掛かる。（時聞的） erst <u>noch</u></a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0126.html">「やっと」</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0132.html">erst recht. 又はerstのみ。 nun erst recht.</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0134.html">wenn....［nur］erst 云々した暁にはが最後</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0136.html">試みに…せしめよ。（まづ…）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0137.html">erst「はやく」に近し</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0138.html">eben</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0139.html">eben（最も軽い場合）ほとんど無意味=nur<br />［雑］ <u>eben</u></a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0141.html">eben（Litotes）あながち…に非ず。<br />大して、…といふほどでもない。<br />否定詞を伴ふもの。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0143.html">つまり、とりも直ず。</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0145.html">というのは（denn） つまり（大した仕細なし!）</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0149.html">nicht eben（大して）（必ずしも）</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0150.html">eben doch.（つまりやっぱり）</a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0151.html">同じ概念に逆戻って強調するeben.<br />［それより言ひ様がない」時</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0153.html">申すまでもなく。</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0157.html">eben=gerade.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0160.html">［雑］<u>etwa</u></a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0161.html">nicht etwa....sondern.</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0161.html">etwa ....なぞと（結局が否定）</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0162.html">…とでも（思ふか、等）=疑問文の</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0163.html">eventuell.（疑問文に非ざる場合）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0163.html">etwa=sagen wirたとへば</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0163.html">概ね、凡そ。</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0164.html">殆ど無くてもよい際の erst</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../021/s0165.html">［雑］<u>etwas</u></a></div><div class="col-2">165</div></div></div>');