document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">30-1R</div><div class="col-8"><a href="../030/s0001.html">時日（Datum）の挙げ方。 年令。</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">30-2B</div><div class="col-8"><a href="../030/s0002.html">数詞 一般事項</a></div><div class="col-2">2-38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0004.html">［01］不定冠詞と共に用ひる時。<br />vor <u>etlichen hundert</u> Jahren.</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0020.html">［02］Ein Glas Bier = Typus.</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0025.html">［03］種数auf "=erlei"</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0026.html">［04］beideの用法。 （複数形は人が主なり）</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0026.html">［05］基数の語尾変化 dreien等。</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0034.html">［06］einer,keiner.</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0035.html">［07］Hunderte, Tausende（名詞的用法）</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0038.html">［08］ein Stoß <u>von</u> Akten =型</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0038.html">［09］in ein［em?］ oder zwei Akten.</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0038.html">［10］指示代名詞的用法 eines,zweierlei,dreierlei.</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0038.html">［11］数を一語に害く。</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0038.html">［12］viele,wenige,manche,mehrere 名詞的用法</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2">30-3B</div><div class="col-8"><a href="../030/s0039.html">Eine Anzahlと四式</a></div><div class="col-2">39-54</div></div>');
document.write('<div class="row"><div class="col-2">30-4B</div><div class="col-8"><a href="../030/s0055.html">序数 0RDNUNGSZAHLEN</a></div><div class="col-2">55-72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0056.html">［01］ein Dritter</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0057.html">［02］jeden zehnten等。</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0059.html">［03］zu dritt等</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0060.html">［04］selbdritt（Selbfünfziger） = zudritt,<br />zu dreien. 仏 douzaine</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0065.html">［05］am dritten <u>Ort</u>.「別な所で」</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0066.html">［06］milliont等。</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0066.html">［07］drittgrößt</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0067.html">［08］hundertund<u>eint</u>.</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0068.html">［09jerstens,zweitens.</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0068.html">［10］vorletzt等 last but one</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0069.html">［11］Die erste Million ［基数ノ代リニ序数］</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0070.html">［12］wieviel（s）t, so und soviel（s）t nullt.</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0071.html">［13］序数によって時間の全長を示す</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0072.html">［14］普通例</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2">30-5B</div><div class="col-8"><a href="../030/s0073.html">基数 KARDINALZAHLEN</a></div><div class="col-2">73-134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0074.html">［01］<u>ein bis Zwei stunden</u>型（einの無語尾）</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0076.html">［02］附加語的<u>ein</u>.</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0080.html">［03］ein und <u>ander</u>（zweiの代り）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0081.html">［04］名詞としては女性</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0084.html">［05］名詞としてのeiner,eines</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0087.html">［06］alle drei Tage型 jeden dritten Tag.<br />［仏］quatre cents ans</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0087.html">［07］rund. おどろくなかれ、<u>なんと</u><br />sage und schreibe（mit Worten）</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0091.html">［08］Million, Billion,Tr～等に就ての参考</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0093.html">［09］百有餘。数百</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0102.html">［10］beideとdie beiden（無冠詞の方）</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0102.html">［11］beideとdie beiden alle beide.<br />仏語はdeux, tous les deux.</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0102.html">［12］ein paar</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0104.html">［13］gut （od. <u>gut und gern</u>）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0110.html">［14］zwei=er等。（二格）</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0111.html">［15］ihr <u>eines</u> Bein等</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0115.html">［16］名詞用法と語尾。（=e）語尾はarchaist.<br />Die drei von der Tankstelle.</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0123.html">［17］=er 何年臺=en（年令と年代）</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0125.html">［18］～ er. 第何聯隊。 或は酒（年代別）</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0126.html">［19］<u>hundert und eine</u> <u>Seite</u>.</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0129.html">［20］<u>eine</u> Stunde oder <u>zwei</u>.</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0130.html">［21］<u>Dreier</u>=Ausschuß等</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0134.html">［22］<u>multi</u>million<br />with <u>multimillion</u> dollar losses.</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2">30-6B</div><div class="col-8"><a href="../030/s0135.html">数詞 時刻、日附、等</a></div><div class="col-2">135-147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0136.html">［01］<u>um</u>と時間。</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0136.html">［02］gegenと時間</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0137.html">［03］年配 <u>Dreißiger</u></a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0138.html">［04］年代（十年代）</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0138.html">［05］halb elf等</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0138.html">［06］時の規定</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0139.html">［07］何時何分過ぎ。 <u>vorbei</u>, <u>auf</u>等</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0140.html">［08］年号に附く色んなもの。</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0140.html">［09］in Jahre l935 又は単に1935</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0141.html">［10］時刻を問ふ。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0141.html">［11］曰を問ふ。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0142.html">［12］Dreißiger等をdas Alterそのものとして<br />用ひる：又はdie Dreißig.</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0144.html">［13］Voracht und vierzig<u>er</u>（何年型の人間、物etc）</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0144.html">［14］acht Tage 一週間 vierzehn Tage. 二週間</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0145.html">［15］die dreißig等、年齢、</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0147.html">［16］<u>Menschenalter</u> lustium, Biennium等</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0147.html">［17］一般文例</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">30-7R</div><div class="col-8"><a href="../030/s0148.html">［英］eight-year-old daughter<br />以上以下の表現 über, mehr, als, unter, weniger als</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2">30-8B</div><div class="col-8"><a href="../030/s0149.html">集約名詞 Sammelzahl</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">30-9R</div><div class="col-8"><a href="../030/s0150.html"><u>集団数</u> Sammelzahl</a></div><div class="col-2">150-151</div></div>');
document.write('<div class="row"><div class="col-2">30-10B</div><div class="col-8"><a href="../030/s0152.html">不定数詞及び量詞 ein wenig</a></div><div class="col-2">152-167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0154.html">［01］程度の比較、変化。（名詞補足を前に置く）<br />語順!</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0155.html">［02］二格を支配せざるもの。</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0155.html">［03］量詞は二格支配。（同時に数詞）</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0155.html"> </a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0156.html">［04］ein Glas <u>Wein</u>, ein Glas <u>frischen Weins</u>.<br />（及びvon,an.）無冠詞</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0157.html">［05］ein paarとein Paar</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0158.html">［06］格語尾なきviel,wenig,weniger,mehr,etwas.</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0161.html">［07］vierとvieles,wenigとweniges</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0161.html">［08］weniges,mehreres,vieles,manches,beides,</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0162.html">［09］einige,etliche,etwelche,</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0162.html">［10］genugと名詞（述語）=s. <u>Zeit genug</u>等</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0162.html">［11］une poigné gorgée 等はEin Glas Bierの部に</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0163.html">［12］<u>Ein</u> Glas oder <u>zwei</u>.（einige）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0163.html">［13］einigとeinzelnをeinzigの意に。</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0163.html">［14］welcher=einige.</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0166.html">［15］Das viele Suchen.（非常な）</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2">30-11B</div><div class="col-8"><a href="../030/s0168.html">分数、回数、分類数、種類数、倍数<br />集約数（onzaine, bini等）<br />（Bruchzahlen,etc.）</a></div><div class="col-2">168-256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0169.html">［01］分数 Drittel. Dritteil.</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0179.html">［02］anderthalb等 =ein einhalb</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0183.html">［03］ein und ein=halb= 後は単数にする。</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0188.html">［04］vierein halb等</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0190.html">［05］Teil</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0193.html">［06］der <u>zehnte</u> Mann等</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0194.html">［07］drei Vierteljahreと考える（<u>pl</u>!）<br />［dreivieitel Jahre］</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0194.html">［08］<u>Prozentsatz</u> （vo<u>m</u> Hundert）v.H.</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0195.html">［09］4,5等、雑例、小数</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0196.html">［10］Hälfte</a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0200.html">［11］回数</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0203.html">［12］<u>einmal übers andre</u>.</a></div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0203.html">［13］sovielmal soviel</a></div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0204.html">［14］分類数</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0205.html">［15］zudritt=<u>drittens</u></a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0205.html">［16］je ein ～</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0206.html">［17］種類数</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0209.html">［18］=erlei 語尾を二格に用ひ得る場合。</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0209.html">［19］集約数（或ひは<u>名詞</u>）</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0209.html">［20］集約数の参考項<br /><u>zu</u> Dutzendenのzu （by the dozens）</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0210.html">［21］malの特殊用法 einmal Kaffee!</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0211.html">［22］=fachの用法（"…の何倍"－"の"の表現）</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0213.html">［23］<u>um das Dreifache</u> 等</a></div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0215.html">［24］zweimal gehen等。</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0219.html">［25］mal <u>so</u> groß <u>wie</u>....</a></div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0235.html">［26］doppeltの単数扱ひ［種類も］</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0241.html">［27］dreidoppelt</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0242.html">［28］［乗と根］</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0243.html">［29］verdoppein, verhundeitfachen等</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0245.html">［30］doppeltにはwieなど要せぬことあり</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0246.html">［31］dreimal heilig, neunmal klug等</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0251.html">［32］縦と横 （其の他☓） 3☓4</a></div><div class="col-2">251</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0255.html">［33］たとへ如何に</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0255.html">［34］abertausend</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0256.html">［35］倍数表現の別形式</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2">30-12B</div><div class="col-8"><a href="../030/s0257.html">度量衡</a></div><div class="col-2">257-279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0258.html">［01］Fünf <u>Fuß</u>（単数の度量衡詞）</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0269.html">［02］Fünf <u>Ellen</u>［複数の度量衡詞］<br />時・日・月・年は複数形を用ふ。</a></div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0273.html">［03］度、分、秒</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0273.html">［04］mit <u>wenigen</u> <u>Mann</u>.</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0273.html">［05］was ist die Uhr?</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0274.html">［06］von 1 Meterなどの1の読み方。</a></div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0274.html">［07］一般</a></div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0275.html">［08］unter Brüdern［wert］</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0275.html">［09］zwanzig Meter <u>Dicke</u></a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0275.html">［10］度量衡の略字（abkürzen. ant:aussetzen） %等</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0276.html">［11］=sを附す：zwanzig Waggins Rohöl.</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0276.html">［12］MeterかMeternかの問題に就て。</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0276.html">［13］zwei Meter hoch（四格の項）</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0277.html">［14］人数の表現</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0277.html">［15］戸数の表現 世帯</a></div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0278.html">［16］年齢</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0279.html">［17］西暦年の読方</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0279.html">［18］一枚、一臺、一張り、一脚、一本、等</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0279.html">［19］光年、時速等の合成の概念</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2">30-13B</div><div class="col-8"><a href="../030/s0280.html">数詞 特殊事項</a></div><div class="col-2">280-301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0281.html">［01］"zwanzig Meter breit"<br />einige Bogenschüsse weit von der Burg.</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0281.html">［02］für Entfernungen im Radius von 10 Kilometer.</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0281.html">［03］数詞を伴ふ度量衡の普通名は、二以上は複数として動詞の数を現定す。</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0282.html">［04］ein paarとein Paar.</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0283.html">［05］fünf Mark die Flasche等。</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0283.html">［06］fast, beinnahe, schier,an die, gut, reichlich等</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0283.html">［07］soviel（<u>autant de</u>....）</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0283.html">［08］<u>Die Drei</u>等</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0284.html">［09］<u>schock</u>,<u>Mandel</u>,<u>Dutzend</u>等、特殊な数を指す用法。<br />Eine stiege Eier=20個</a></div><div class="col-2">284</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0286.html">［10］Einer一位数 Zehner 十位数</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0287.html">［11］”凡そ”と”殆ど”</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0301.html">［12］sage und schreibe（おどろくなかれ）</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../030/s0301.html">［13］Zwilling Drilling</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2">30-14R</div><div class="col-8"><a href="../030/s0302.html">billionシステムの異同について<br />Prozentsatz</a></div><div class="col-2">302-303</div></div>');
document.write('<div class="row"><div class="col-2">30-15B</div><div class="col-8"><a href="../030/s0304.html">zwo, zween 等 ［MHD］.［AHD］</a></div><div class="col-2">304-309</div></div>');
document.write('<div class="row"><div class="col-2">30-16R</div><div class="col-8"><a href="../030/s0310.html">biennium, biduum,etc.</a></div><div class="col-2">310-313</div></div>');
document.write('<div class="row"><div class="col-2">30-17B</div><div class="col-8"><a href="../030/s0314.html">Triumvirat其他数に関する具体的用語<br />（古典語と関係）<br />三羽烏、三頭政治、三巨頭、三幅對等</a></div><div class="col-2">314-315</div></div>');
document.write('<div class="row"><div class="col-2">30-18B</div><div class="col-8"><a href="../030/s0316.html">少し、僅か、等の表現</a></div><div class="col-2">316-317</div></div>');
document.write('<div class="row"><div class="col-2">30-19R</div><div class="col-8"><a href="../030/s0318.html">［英］<u>as little as</u>等<br />数字の前につける副詞に就いて<br />An die 30<br />soundsoviel<br />数学用語集<br />KommaとPunktと 各国語で習憤がちがふ！<br />平方と立方の表現<br />小数の表現<br />wievielt, soundsovielt</a></div><div class="col-2">318-322</div></div>');
document.write('<div class="row"><div class="col-2">30-20B</div><div class="col-8"><a href="../030/s0323.html">数詞一般文例集</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2">30-21R</div><div class="col-8"><a href="../030/s0324.html">viermotorig等の合成語<br />mehrere,<u>mehre</u>.<br />vier= wenig=の語尾の有無の問題<br />－量詞に非ざる有数名詞について-<p> </p><p>編者注：このほか16件あり。</p></a></div><div class="col-2">324-333</div></div>');
document.write('<div class="row"><div class="col-2">30-22B</div><div class="col-8"><a href="../030/s0334.html">the fifth column 第五列</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2">30-23R</div><div class="col-8"><a href="../030/s0335.html">数表現に関する奇例 減算的表現<br />数詞参考 ［他国語］<br />初歩 hundert［und］fünfzig（undの問題）<br /><u>階の問題</u><br />［英］<u>Einerを前に</u><br />mehr als ein=</a></div><div class="col-2">335-336</div></div></div>');