document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">30-1R</div><div class="col-8">時日（Datum）の挙げ方。 年令。</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">30-2B</div><div class="col-8">数詞 一般事項</div><div class="col-2">2-38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］不定冠詞と共に用ひる時。<br />vor <u>etlichen hundert</u> Jahren.</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］Ein Glas Bier = Typus.</div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］種数auf "=erlei"</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］beideの用法。 （複数形は人が主なり）</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］基数の語尾変化 dreien等。</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］einer,keiner.</div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］Hunderte, Tausende（名詞的用法）</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］ein Stoß <u>von</u> Akten =型</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］in ein［em?］ oder zwei Akten.</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］指示代名詞的用法 eines,zweierlei,dreierlei.</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］数を一語に害く。</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］viele,wenige,manche,mehrere 名詞的用法</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2">30-3B</div><div class="col-8">Eine Anzahlと四式</div><div class="col-2">39-54</div></div>');
document.write('<div class="row"><div class="col-2">30-4B</div><div class="col-8">序数 0RDNUNGSZAHLEN</div><div class="col-2">55-72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］ein Dritter</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］jeden zehnten等。</div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］zu dritt等</div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］selbdritt（Selbfünfziger） = zudritt,<br />zu dreien. 仏 douzaine</div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］am dritten <u>Ort</u>.「別な所で」</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］milliont等。</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］drittgrößt</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］hundertund<u>eint</u>.</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09jerstens,zweitens.</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］vorletzt等 last but one</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］Die erste Million ［基数ノ代リニ序数］</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］wieviel（s）t, so und soviel（s）t nullt.</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］序数によって時間の全長を示す</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］普通例</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2">30-5B</div><div class="col-8">基数 KARDINALZAHLEN</div><div class="col-2">73-134</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］<u>ein bis Zwei stunden</u>型（einの無語尾）</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］附加語的<u>ein</u>.</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］ein und <u>ander</u>（zweiの代り）</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］名詞としては女性</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］名詞としてのeiner,eines</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］alle drei Tage型 jeden dritten Tag.<br />［仏］quatre cents ans</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］rund. おどろくなかれ、<u>なんと</u><br />sage und schreibe（mit Worten）</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］Million, Billion,Tr～等に就ての参考</div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］百有餘。数百</div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］beideとdie beiden（無冠詞の方）</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］beideとdie beiden alle beide.<br />仏語はdeux, tous les deux.</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］ein paar</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］gut （od. <u>gut und gern</u>）</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］zwei=er等。（二格）</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］ihr <u>eines</u> Bein等</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］名詞用法と語尾。（=e）語尾はarchaist.<br />Die drei von der Tankstelle.</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］=er 何年臺=en（年令と年代）</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］～ er. 第何聯隊。 或は酒（年代別）</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］<u>hundert und eine</u> <u>Seite</u>.</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］<u>eine</u> Stunde oder <u>zwei</u>.</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］<u>Dreier</u>=Ausschuß等</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］<u>multi</u>million<br />with <u>multimillion</u> dollar losses.</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2">30-6B</div><div class="col-8">数詞 時刻、日附、等</div><div class="col-2">135-147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］<u>um</u>と時間。</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］gegenと時間</div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］年配 <u>Dreißiger</u></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］年代（十年代）</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］halb elf等</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］時の規定</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］何時何分過ぎ。 <u>vorbei</u>, <u>auf</u>等</div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］年号に附く色んなもの。</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］in Jahre l935 又は単に1935</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］時刻を問ふ。</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］曰を問ふ。</div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］Dreißiger等をdas Alterそのものとして<br />用ひる：又はdie Dreißig.</div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］Voracht und vierzig<u>er</u>（何年型の人間、物etc）</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］acht Tage 一週間 vierzehn Tage. 二週間</div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］die dreißig等、年齢、</div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］<u>Menschenalter</u> lustium, Biennium等</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］一般文例</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">30-7R</div><div class="col-8">［英］eight-year-old daughter<br />以上以下の表現 über, mehr, als, unter, weniger als</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2">30-8B</div><div class="col-8">集約名詞 Sammelzahl</div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">30-9R</div><div class="col-8"><u>集団数</u> Sammelzahl</div><div class="col-2">150-151</div></div>');
document.write('<div class="row"><div class="col-2">30-10B</div><div class="col-8">不定数詞及び量詞 ein wenig</div><div class="col-2">152-167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］程度の比較、変化。（名詞補足を前に置く）<br />語順!</div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］二格を支配せざるもの。</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］量詞は二格支配。（同時に数詞）</div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"> </div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］ein Glas <u>Wein</u>, ein Glas <u>frischen Weins</u>.<br />（及びvon,an.）無冠詞</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］ein paarとein Paar</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］格語尾なきviel,wenig,weniger,mehr,etwas.</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］vierとvieles,wenigとweniges</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］weniges,mehreres,vieles,manches,beides,</div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］einige,etliche,etwelche,</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］genugと名詞（述語）=s. <u>Zeit genug</u>等</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］une poigné gorgée 等はEin Glas Bierの部に</div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］<u>Ein</u> Glas oder <u>zwei</u>.（einige）</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］einigとeinzelnをeinzigの意に。</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］welcher=einige.</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］Das viele Suchen.（非常な）</div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2">30-11B</div><div class="col-8">分数、回数、分類数、種類数、倍数<br />集約数（onzaine, bini等）<br />（Bruchzahlen,etc.）</div><div class="col-2">168-256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］分数 Drittel. Dritteil.</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］anderthalb等 =ein einhalb</div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］ein und ein=halb= 後は単数にする。</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］vierein halb等</div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］Teil</div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］der <u>zehnte</u> Mann等</div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］drei Vierteljahreと考える（<u>pl</u>!）<br />［dreivieitel Jahre］</div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］<u>Prozentsatz</u> （vo<u>m</u> Hundert）v.H.</div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］4,5等、雑例、小数</div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］Hälfte</div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］回数</div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］<u>einmal übers andre</u>.</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］sovielmal soviel</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］分類数</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］zudritt=<u>drittens</u></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］je ein ～</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］種類数</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］=erlei 語尾を二格に用ひ得る場合。</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］集約数（或ひは<u>名詞</u>）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］集約数の参考項<br /><u>zu</u> Dutzendenのzu （by the dozens）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］malの特殊用法 einmal Kaffee!</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］=fachの用法（"…の何倍"－"の"の表現）</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］<u>um das Dreifache</u> 等</div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］zweimal gehen等。</div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］mal <u>so</u> groß <u>wie</u>....</div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［26］doppeltの単数扱ひ［種類も］</div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［27］dreidoppelt</div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［28］［乗と根］</div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［29］verdoppein, verhundeitfachen等</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［30］doppeltにはwieなど要せぬことあり</div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［31］dreimal heilig, neunmal klug等</div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［32］縦と横 （其の他☓） 3☓4</div><div class="col-2">251</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［33］たとへ如何に</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［34］abertausend</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［35］倍数表現の別形式</div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2">30-12B</div><div class="col-8">度量衡</div><div class="col-2">257-279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］Fünf <u>Fuß</u>（単数の度量衡詞）</div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］Fünf <u>Ellen</u>［複数の度量衡詞］<br />時・日・月・年は複数形を用ふ。</div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］度、分、秒</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］mit <u>wenigen</u> <u>Mann</u>.</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］was ist die Uhr?</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］von 1 Meterなどの1の読み方。</div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］一般</div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］unter Brüdern［wert］</div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］zwanzig Meter <u>Dicke</u></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］度量衡の略字（abkürzen. ant:aussetzen） %等</div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］=sを附す：zwanzig Waggins Rohöl.</div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］MeterかMeternかの問題に就て。</div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］zwei Meter hoch（四格の項）</div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］人数の表現</div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］戸数の表現 世帯</div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］年齢</div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］西暦年の読方</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］一枚、一臺、一張り、一脚、一本、等</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］光年、時速等の合成の概念</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2">30-13B</div><div class="col-8">数詞 特殊事項</div><div class="col-2">280-301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］"zwanzig Meter breit"<br />einige Bogenschüsse weit von der Burg.</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］für Entfernungen im Radius von 10 Kilometer.</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］数詞を伴ふ度量衡の普通名は、二以上は複数として動詞の数を現定す。</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］ein paarとein Paar.</div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］fünf Mark die Flasche等。</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］fast, beinnahe, schier,an die, gut, reichlich等</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］soviel（<u>autant de</u>....）</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］<u>Die Drei</u>等</div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］<u>schock</u>,<u>Mandel</u>,<u>Dutzend</u>等、特殊な数を指す用法。<br />Eine stiege Eier=20個</div><div class="col-2">284</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］Einer一位数 Zehner 十位数</div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］”凡そ”と”殆ど”</div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］sage und schreibe（おどろくなかれ）</div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］Zwilling Drilling</div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2">30-14R</div><div class="col-8">billionシステムの異同について<br />Prozentsatz</div><div class="col-2">302-303</div></div>');
document.write('<div class="row"><div class="col-2">30-15B</div><div class="col-8">zwo, zween 等 ［MHD］.［AHD］</div><div class="col-2">304-309</div></div>');
document.write('<div class="row"><div class="col-2">30-16R</div><div class="col-8">biennium, biduum,etc.</div><div class="col-2">310-313</div></div>');
document.write('<div class="row"><div class="col-2">30-17B</div><div class="col-8">Triumvirat其他数に関する具体的用語<br />（古典語と関係）<br />三羽烏、三頭政治、三巨頭、三幅對等</div><div class="col-2">314-315</div></div>');
document.write('<div class="row"><div class="col-2">30-18B</div><div class="col-8">少し、僅か、等の表現</div><div class="col-2">316-317</div></div>');
document.write('<div class="row"><div class="col-2">30-19R</div><div class="col-8">［英］<u>as little as</u>等<br />数字の前につける副詞に就いて<br />An die 30<br />soundsoviel<br />数学用語集<br />KommaとPunktと 各国語で習憤がちがふ！<br />平方と立方の表現<br />小数の表現<br />wievielt, soundsovielt</div><div class="col-2">318-322</div></div>');
document.write('<div class="row"><div class="col-2">30-20B</div><div class="col-8">数詞一般文例集</div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2">30-21R</div><div class="col-8">viermotorig等の合成語<br />mehrere,<u>mehre</u>.<br />vier= wenig=の語尾の有無の問題<br />－量詞に非ざる有数名詞について-<p> </p><p>編者注：このほか16件あり。</p></div><div class="col-2">324-333</div></div>');
document.write('<div class="row"><div class="col-2">30-22B</div><div class="col-8">the fifth column 第五列</div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2">30-23R</div><div class="col-8">数表現に関する奇例 減算的表現<br />数詞参考 ［他国語］<br />初歩 hundert［und］fünfzig（undの問題）<br /><u>階の問題</u><br />［英］<u>Einerを前に</u><br />mehr als ein=</div><div class="col-2">335-336</div></div></div>');