document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">29-1B</div><div class="col-8">subsumptions=Unter.</div><div class="col-2">1-8</div></div>');
document.write('<div class="row"><div class="col-2">29-2R</div><div class="col-8">…の下に隠れて、…を掲げて。<br />「云々の美名にかくれて」</div><div class="col-2">9-12</div></div>');
document.write('<div class="row"><div class="col-2">29-3R</div><div class="col-8">among, aumilieu de.</div><div class="col-2">13-21</div></div>');
document.write('<div class="row"><div class="col-2">29-4R</div><div class="col-8">unter der Flagge.</div><div class="col-2">22-32</div></div>');
document.write('<div class="row"><div class="col-2">29-5B</div><div class="col-8">の美名にかくれて</div><div class="col-2">33-35</div></div>');
document.write('<div class="row"><div class="col-2">29-6B</div><div class="col-8">迂言前置詞のunter～ unter Einschluss von～</div><div class="col-2">36-45</div></div>');
document.write('<div class="row"><div class="col-2">29-7R</div><div class="col-8">警戒の<u>vor</u> Die Sterne <u>erbleichen vor</u> der Sonne.</div><div class="col-2">46-68</div></div>');
document.write('<div class="row"><div class="col-2">29-8B</div><div class="col-8">vor</div><div class="col-2">69-115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］…の餘り。（無冠詞）</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］…を差し置いて、…を駆けぬけて<br />…よりも秀れて。</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］警戒のvor</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］vor sich（hin） Für sich hin.</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］時間的に「前」</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］圧倒的因由のvor …を迎えて、に臨んで<br />（「原因」的）</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］云々に面する、臨む、さし向かふ vis-à-vis, en face de</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］［膳」（bei einem Glas Bier）</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］の前に立って。（裁く者の）</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］vor einer <u>Festung</u>, einer <u>Stadt</u>.（の外）</div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］空間的（下） unter</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］下から（hinter, Zwischen等と）</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］…の下（もと）に（何か支配的なる事情に<br />壓せられつつ）</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］治下、代、（unter Trajan等）及び誰々「の下で」（働く等）</div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］概念の内容 verstehen.</div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］…されつつ、しつつ mit nomen avtionis.</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2">29-9B</div><div class="col-8">警戒のvorと二格との関係 Horror vacui.</div><div class="col-2">116-120</div></div>');
document.write('<div class="row"><div class="col-2">29-10B</div><div class="col-8">vor Wut等 Kohlhaas schäumte vor Wut.</div><div class="col-2">121-138</div></div>');
document.write('<div class="row"><div class="col-2">29-11R</div><div class="col-8">über そんなことをしていたら。<br />（vergessen等と）<br />原因（四格の際は<u>um</u>等に近い）<br />anとinとの差 哲学的立場から</div><div class="col-2">139-142</div></div>');
document.write('<div class="row"><div class="col-2">29-12B</div><div class="col-8">乗り越える。克つ。</div><div class="col-2">143-146</div></div>');
document.write('<div class="row"><div class="col-2">29-13B</div><div class="col-8">－に就いて－ er sprocht von～と<br />er spricht über～との^区別</div><div class="col-2">147-163</div></div>');
document.write('<div class="row"><div class="col-2">29-14B</div><div class="col-8">運命のüber über jem. schweben.</div><div class="col-2">154-159</div></div>');
document.write('<div class="row"><div class="col-2">29-15R</div><div class="col-8">原因のüber（三格？） 或時は<u>vor</u>と同じ。<br />理由。über</div><div class="col-2">160-162</div></div>');
document.write('<div class="row"><div class="col-2">29-16B</div><div class="col-8">nach（über Nacht,etc）</div><div class="col-2">163-170</div></div>');
document.write('<div class="row"><div class="col-2">29-17B</div><div class="col-8">währennd（nachも同じ） 真のwährenndもあり</div><div class="col-2">171-173</div></div>');
document.write('<div class="row"><div class="col-2">29-18B</div><div class="col-8">場所のauf（基本） 「席上で」など</div><div class="col-2">174-184</div></div>');
document.write('<div class="row"><div class="col-2">29-19B</div><div class="col-8">über,auf</div><div class="col-2">185-275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］über「見渡す見おろす」は四格（死命を制し、支配する意）</div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］währennd.</div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］［…に応じて」 aufeinanerfolgen.</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］目標、方向（狙ふ対称）四格</div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］auf....着眼点、問題にせんとする点。</div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］働き掛けのauf［…に及ぶ、届く、達する］</div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］auf,到着する地点「思い出す」</div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］auf, 公開的な、人寄りの場所。</div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］auf die Nase fallen.</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］auf eigene Faust,etc.（複） on his own,</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］auf....los（空間的に）</div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］über 表面移動</div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2">29-20B</div><div class="col-8"> </div><div class="col-2">276-290</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］auf,に掛け誓ふ。</div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］Zeitdauer. （四格、又はfür,währennd.）<br />auf immer=für ewig.<br />à jamais pour toujours</div><div class="col-2">277</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］重複のauf.</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］…しに行く。 auf ～ <u>aus</u> sein,<u>aus</u>gehen</div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2">29-21B</div><div class="col-8">即應のauf 因由に転用可能</div><div class="col-2">291-304</div></div>');
document.write('<div class="row"><div class="col-2">29-22B</div><div class="col-8">betragen（ohne"auf"） to reach, to total<br />betragenの表現 est <u>de</u><br />［英］一般的宣告の無冠詞（複数のGattungsnamen）<br /><u>Flowers</u> are sweet. <u>Cats</u> kill birds.<br /><u>Die</u> Katzen töten die vögel.</div><div class="col-2">305-332</div></div>');
document.write('<div class="row"><div class="col-2">29-23B</div><div class="col-8">Betragの表現参考 in die Tausende gehen.</div><div class="col-2">333-335</div></div>');
document.write('<div class="row"><div class="col-2">29-24R</div><div class="col-8">擧文のauf<br />限度、程度、境界を劃するauf bis auf....<br />auf（島、星の世界、等々）<br />Auf Java sind die Mädels braun.</div><div class="col-2">336-342</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">einen am Narrenseil führen.etc.</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-25B</div><div class="col-8">性質のan 具有性のan</div><div class="col-2">343-358</div></div>');
document.write('<div class="row"><div class="col-2">29-26B</div><div class="col-8"><u>Am</u> <u>Narrensell</u>で手段</div><div class="col-2">359-361</div></div>');
document.write('<div class="row"><div class="col-2">29-27B</div><div class="col-8">最も普通なる空間的an.</div><div class="col-2">362-369</div></div>');
document.write('<div class="row"><div class="col-2">29-28B</div><div class="col-8">享受、受益のan Die Lust am Schein.</div><div class="col-2">370-381</div></div>');
document.write('<div class="row"><div class="col-2">29-29B</div><div class="col-8">増減（部分の） an Gesundheit zu nehmen.</div><div class="col-2">382-384</div></div>');
document.write('<div class="row"><div class="col-2">29-30B</div><div class="col-8">結果のan sich <u>daran</u> zu Tode trinken.</div><div class="col-2">385-386</div></div>');
document.write('<div class="row"><div class="col-2">29-31B</div><div class="col-8">「増減と」an</div><div class="col-2">387-389</div></div>');
document.write('<div class="row"><div class="col-2">29-32B</div><div class="col-8">an ～zu ～habenはgenug等の<u>量詞規定ある</u>こと多し<br />これが現象の-Momentなり</div><div class="col-2">390-392</div></div>');
document.write('<div class="row"><div class="col-2">29-33B</div><div class="col-8">一部分が段々減って行く。（…し「で」がある等）</div><div class="col-2">393-396</div></div>');
document.write('<div class="row"><div class="col-2">29-34B</div><div class="col-8">部分的処理完成のan</div><div class="col-2">397-402</div></div>');
document.write('<div class="row"><div class="col-2">29-35B</div><div class="col-8">内容を示すan. adnominalとadverbal.（genug an）</div><div class="col-2">403-413</div></div>');
document.write('<div class="row"><div class="col-2">29-36R</div><div class="col-8">内容のan. －明らかにadnominal－<br />was....<u>an</u>と同じ。</div><div class="col-2">414-415</div></div>');
document.write('<div class="row"><div class="col-2">29-37B</div><div class="col-8">失ふ対象のum</div><div class="col-2">416-419</div></div>');
document.write('<div class="row"><div class="col-2">29-38B</div><div class="col-8">内容のan lack of materials</div><div class="col-2">420-427</div></div>');
document.write('<div class="row"><div class="col-2">29-39B</div><div class="col-8"> </div><div class="col-2">428-438</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］um …を得るために。<br />…を中心として</div><div class="col-2">428</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］忌避の対象に。［um....herum=］</div><div class="col-2">430</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］----を中心として。 －関心の対象、問題。<br />sich um ～ kümmern,（fragen）</div><div class="col-2">431</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］ある者「ゆえに」苦労する。心配する等。<br />einen <u>um</u> etwas tadeln.</div><div class="col-2">432</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］時刻を指すum.（頃、時刻）</div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］失う対象のum.</div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2">29-40B</div><div class="col-8">…を中心として</div><div class="col-2">439-448</div></div>');
document.write('<div class="row"><div class="col-2">29-41B</div><div class="col-8">um（得るために）</div><div class="col-2">449-452</div></div>');
document.write('<div class="row"><div class="col-2">29-42B</div><div class="col-8">…を得るために。…<u>を賭して</u><br />jemand um Beistand <u>anrufen</u>.</div><div class="col-2">453-455</div></div>');
document.write('<div class="row"><div class="col-2">29-43B</div><div class="col-8">英語の<u>for</u></div><div class="col-2">456-459</div></div>');
document.write('<div class="row"><div class="col-2">29-44B</div><div class="col-8">［<u>um</u> die <u>Wette</u>］ à l\'envi avec émulation</div><div class="col-2">460-463</div></div>');
document.write('<div class="row"><div class="col-2">29-45R</div><div class="col-8">身辺［君］側. 等 身辺のum</div><div class="col-2">464-470</div></div>');
document.write('<div class="row"><div class="col-2">29-46B</div><div class="col-8">Logisches Subjektのum</div><div class="col-2">471-477</div></div>');
document.write('<div class="row"><div class="col-2">29-47B</div><div class="col-8">失う。 奪う。（einen um etwas prellen,etc）</div><div class="col-2">478-481</div></div>');
document.write('<div class="row"><div class="col-2">29-48B</div><div class="col-8">失う。 奪う。 の<u>um</u></div><div class="col-2">482-483</div></div>');
document.write('<div class="row"><div class="col-2">29-49B</div><div class="col-8">差のum ［英］<u>preceeded</u> him <u>by</u> a few seconds</div><div class="col-2">484-502</div></div>');
document.write('<div class="row"><div class="col-2">29-50B</div><div class="col-8">um 陸続と。 Auto um Auto rollt an.</div><div class="col-2">503-505</div></div>');
document.write('<div class="row"><div class="col-2">29-51R</div><div class="col-8">in 時間的階梯（段階）の局限</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">或る状態に置き移す。状態、心理状態<br />「點」で、「…する事に於て」<br />in ～ setzen in ～ treten in geraten <br />in ～bringen Zug um Zug in ～ versetzen. <br />in Gebrauch kommmen. in ～ verfallen<br />［英］to fall in love with ～</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-52B</div><div class="col-8">teilen in ～ 分析、分解</div><div class="col-2">533-539</div></div>');
document.write('<div class="row"><div class="col-2">29-53B</div><div class="col-8">時問的に（後続する）距たりを示す。<br />（nach）nach verlauf von.</div><div class="col-2">540-541</div></div>');
document.write('<div class="row"><div class="col-2">29-54B</div><div class="col-8">in 3 stunden</div><div class="col-2">542-558</div></div>');
document.write('<div class="row"><div class="col-2">29-55R</div><div class="col-8">in： Maß, Ausmaß, Grad, Umfang</div><div class="col-2">559-563</div></div>');
document.write('<div class="row"><div class="col-2">29-56B</div><div class="col-8">in Ruhe. in Ehren. （im Grunde）（im Gegenteil）</div><div class="col-2">564-571</div></div>');
document.write('<div class="row"><div class="col-2">29-57B</div><div class="col-8">in「和平裡に」の裡。（次に抽象名詞）</div><div class="col-2">572-576</div></div>');
document.write('<div class="row"><div class="col-2">29-58B</div><div class="col-8">in［形を描いて］</div><div class="col-2">577-585</div></div>');
document.write('<div class="row"><div class="col-2">29-59B</div><div class="col-8">in 極限化のin （部分と性質とあり）</div><div class="col-2">586-600</div></div>');
document.write('<div class="row"><div class="col-2">29-60R</div><div class="col-8">für Gefühl für等</div><div class="col-2">601-606</div></div>');
document.write('<div class="row"><div class="col-2">29-61B</div><div class="col-8">für （mot à mot） 徐々と、逐一、順を追って</div><div class="col-2">607-618</div></div>');
document.write('<div class="row"><div class="col-2">29-62R</div><div class="col-8">für 期間のfür<br />geführ für等<br />賛成のfür<br />単に三格。（…に取って）</div><div class="col-2">619-623</div></div>');
document.write('<div class="row"><div class="col-2">29-63B</div><div class="col-8">identitäts=in</div><div class="col-2">624-633</div></div>');
document.write('<div class="row"><div class="col-2">29-64B</div><div class="col-8">～ für ～ step by step one by one</div><div class="col-2">634-638</div></div>');
document.write('<div class="row"><div class="col-2">29-65B</div><div class="col-8">zu=als</div><div class="col-2">639-660</div></div>');
document.write('<div class="row"><div class="col-2">29-66R</div><div class="col-8">zum Raub → Raub 古典語では<u>熟語的同格</u>を以て<br />表現す<br />by way of</div><div class="col-2">661-664</div></div>');
document.write('<div class="row"><div class="col-2">29-67B</div><div class="col-8">zu Befehl zum Abmarsch（=<u>Abmarsch befehl</u>）</div><div class="col-2">665-671</div></div>');
document.write('<div class="row"><div class="col-2">29-68R</div><div class="col-8">zum----en.<br />dazu noch<br />al（として） 結果のzuに通ず。<br />zum Scherz=scherzweise「冗談に」の「に」</div><div class="col-2">672-684</div></div>');
document.write('<div class="row"><div class="col-2">29-69B</div><div class="col-8">zu［付属、対立のzu］意見のzu</div><div class="col-2">685-698</div></div>');
document.write('<div class="row"><div class="col-2">29-70R</div><div class="col-8">zu 結果のzu（不定冠詞）<br />価格で、…価格の… <br />um....zu の文章と同意。（adnominaL u. adverbal）<br />目的（adnominaL u. adverbal）zu diesem Zwecke.</div><div class="col-2">699-705</div></div>');
document.write('<div class="row"><div class="col-2">29-71B</div><div class="col-8">結果のzu</div><div class="col-2">706-717</div></div>');
document.write('<div class="row"><div class="col-2">29-72B</div><div class="col-8">anと同じ（ce qu\'il y a de....）</div><div class="col-2">718-721</div></div>');
document.write('<div class="row"><div class="col-2">29-73R</div><div class="col-8">von はなれている意（静止的）</div><div class="col-2">722-729</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">von ［先置する］Gen1tivus partitivus</div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">29-74R</div><div class="col-8">von 副詞、形容詞化的、（冠詞なし） par....<br />von von Beruf等 by trade by calling<br />von seiten.... von jemandes Seite<br />von 著作。<br />von der Arbeit ausruhen.<br />von einer Krankheit genesen.<br />von etwas abkommen.<br />（仏 <u>revenir</u> <u>sur</u> son opinion）<br />von …に就いて、…に関して。</div><div class="col-2">730-762</div></div>');
document.write('<div class="row"><div class="col-2">29-75B</div><div class="col-8">von schwer von Begriff. schwer von Begriffen.</div><div class="col-2">763-784</div></div>');
document.write('<div class="row"><div class="col-2">29-76R</div><div class="col-8">von 或る性質を有する。（von Belang, von <br />nutzen sein.）<br />形容のvon</div><div class="col-2">785-810</div></div>');
document.write('<div class="row"><div class="col-2">29-77R</div><div class="col-8">nach nach etwas schmecken等。（らしい）<br />nach 従へば（仮定強調）</div><div class="col-2">811-822</div></div>');
document.write('<div class="row"><div class="col-2">29-78R</div><div class="col-8">nach 時間的（普通のnach）<br />nach 空間的（普通のnach）</div><div class="col-2">823-844</div></div>');
document.write('<div class="row"><div class="col-2">29-79B</div><div class="col-8">nach nemen <u>nach</u></div><div class="col-2">845-853</div></div>');
document.write('<div class="row"><div class="col-2">29-80B</div><div class="col-8">nach 適、不適（嗜好の問題）添ふ</div><div class="col-2">854-889</div></div>');
document.write('<div class="row"><div class="col-2">29-81R</div><div class="col-8">mit 言説をauffangenするmit<br />反発のmit</div><div class="col-2">890-898</div></div>');
document.write('<div class="row"><div class="col-2">29-82R</div><div class="col-8">mit Gegenstand, womit, man so umgeht.<br />gegen für［Ayer pitié avec moi ! ］</div><div class="col-2">899-905</div></div>');
document.write('<div class="row"><div class="col-2">29-83B</div><div class="col-8">mit 交渉・従事のmit</div><div class="col-2">906-913</div></div>');
document.write('<div class="row"><div class="col-2">29-84B</div><div class="col-8">mit 「人」の時はいいが、「物の時はlogisches <br />0bjektを一致す</div><div class="col-2">914-937</div></div>');
document.write('<div class="row"><div class="col-2">29-85B</div><div class="col-8">mit es steht so und so mit----.</div><div class="col-2">938-940</div></div>');
document.write('<div class="row"><div class="col-2">29-86R</div><div class="col-8">mit esとmit<br />英語 matters, things, case<br />Esの代りに<u>was</u>等<br />編者注：このほか7件あり。</div><div class="col-2">941-953</div></div>');
document.write('<div class="row"><div class="col-2">29-87B</div><div class="col-8">mit副詞的用法。<br />mit zugreifen（手つだふ） anpacken.</div><div class="col-2">954-992</div></div>');
document.write('<div class="row"><div class="col-2">29-88R</div><div class="col-8">mit 附帯描写のmit</div><div class="col-2">993-1003</div></div>');
document.write('<div class="row"><div class="col-2">29-89B</div><div class="col-8">mit 誰それの言葉通りに。（mit N.N. zu reden）</div><div class="col-2">1004-1008</div></div>');
document.write('<div class="row"><div class="col-2">29-90B</div><div class="col-8">bei 或る人の「許」（家）</div><div class="col-2">1009-1044</div></div>');
document.write('<div class="row"><div class="col-2">29-91B</div><div class="col-8">動機のaus aus politischen Beweg gründen.</div><div class="col-2">1045-1073</div></div></div>');