document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">32-1B</div><div class="col-8"><a href="../032/s0001.html">Zuを伴ふ不定法</a></div><div class="col-2">1-252</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0005.html">［01］動詞の直接補足（四格的）となるzu+inf.</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0006.html">［02］名詞の附加語（限定）となるzu+inf.</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0024.html">［03］主語esを受けるzu+不定法。</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0033.html">［04］名詞以外（das, darin等）附加語となるもの</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0034.html">［05］形容詞の附加語となるもの。（bereit等）</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0044.html">［06］述語（es）を説明するもの。</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0049.html">［07］四格esを受けるzu+不定法</a></div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0053.html">［08］zu+INF.</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0092.html">［09］zu+Infとhaben.</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0113.html">［10］zu+不定法+geben.</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0114.html">［11］関係文中に入り組んだzu+不定法。</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0120.html">［12］関係文中のzu+不定法（定形中置、コンマ）</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0130.html">［13］genug---［um］zu.</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0141.html">［14］zu+不定法が名詞的なる事の例。</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0142.html">［15］（um zu）…のために（umの省略）</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0143.html">［16］schön anzusehen.</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0176.html">［17］zu....、als daß....</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0177.html">［18］zu+不定法とkommen.（venir de....と比較）</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0191.html">［19］名詞化した不定法を伴ふzu</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0192.html">［20］zu+不定法とbekommen.</a></div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0195.html">［21］zu+不定法とes gibt.</a></div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0199.html">［22］［an］statt---zu.</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0199.html">［23］ohne---zu</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0200.html">［24］zu+不定法とfinden<br />sehen</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0202.html">［25］zu+不定法とbleiben, (zu tun bleiben)</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0206.html">［26］so viel....［um］ zu.</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0208.html">［27］zu+不定法とgeben.bieten, bringen.</a></div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0217.html">［28］zu+不定法の句には主語一格なし。<br />それに関する異例その他</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0219.html">［29］不定区の代りに<u>und</u>を用ひて正文を置く。</a></div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0220.html">［30］_____ nict zu vergessen, nicht zu rechen. zu schweigen.（認容的）</a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0227.html">［31］ohne....zu.</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0227.html">［32］名詞附加的［um］zu不定法。<br />－名詞附加は<u>um</u> zuのみなり－</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0228.html">［33］文肢の先置から起る不定句の遊離。</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0229.html">［34］<u>未来分詞？</u> <u>Gerundivum</u>. 附加語的</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0233.html">［35］成句の附加語となるzu+不定法。</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0237.html">［36］附加語となるもの。（Deine Art zu sein）</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0241.html">［37］Zuを伴ふ不定法の重畳。</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0241.html">［38］<u>an</u> etw......zu ～ haben.</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0241.html">［39］istを省いた....zu+不定法</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0242.html">［40］zu不定法とstehen.（=sein）</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0248.html">［41］［über］jm.schlecht <u>zu sprechen sein</u>.</a></div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0250.html">［42］zu....machen 等。sich zu schaffen machen.<br />zu wissen tun</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0252.html">［43］à constater que.... …して<u>は</u>、</a></div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0252.html">［44］zu不定法+mitbringen［其他］ <br />schicken</a></div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2">32-2B</div><div class="col-8"><a href="../032/s0253.html">英語のto+不定法の可能範囲に関する参考</a></div><div class="col-2">253-282</div></div>');
document.write('<div class="row"><div class="col-2">32-3B</div><div class="col-8"><a href="../032/s0283.html">不定法</a></div><div class="col-2">283-403</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0285.html">［01］不定法のみの独立用法（<u>heißen</u>）等</a></div><div class="col-2">285</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0304.html">［02］定形なき時はein Rat.（命令指示）</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0306.html">［03］［zuを伴ふ］不定法の名詞的用法</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0308.html">［04］stehen <u>haben</u>, u.s.w.（wissenもあり）</a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0313.html">［05］sitzen <u>bleiben</u>. （自動詞と結合して）</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0316.html">［06］似而非不定法。（名詞化の如く見ゆ）</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0317.html">［07］ist....不定法</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0325.html">［08］過去の不定法。（zuを伴ふ場合も）</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0327.html">［09］gut....不定法....haben.（認容。）</a></div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0332.html">［10］auf ihn ist kein Verlaß.<br />（ist gut 不定法と同意）</a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0334.html">［11］schlafen <u>lagen</u>.（稀に<u>liegen</u>も）</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0335.html">［12］aus dem <u>es</u> so leicht <u>kein Herausfinden</u> <u>gäbe</u>.<br />［es gibt, sein］否定。</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0346.html">［13］jedes,allesと共に用ふる名詞用法。</a></div><div class="col-2">346</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0347.html">［14］schlafen <u>gehen</u>.</a></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0364.html">［15］schlafen <u>schicken</u>.</a></div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0366.html">［16］Das ist ein Geigen und Flöten.!</a></div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0367.html">［17］疑問文の不定句。</a></div><div class="col-2">367</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0370.html">［18］helfen kommen（Supinisch）</a></div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0377.html">［19］Ein hartes Schicksal, <u>aufgeopfert werden</u>.</a></div><div class="col-2">377</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0379.html">［20］heißen 命ずる</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0379.html">［21］es heißt …云々せざるべからず</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0380.html">［22］führenを基部とするもの spazieren führen</a></div><div class="col-2">380</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0380.html">schlafen führen</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0381.html">［23］einkaufen <u>gewesen sein</u></a></div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0385.html">［24］brauchen（例外的）俗語</a></div><div class="col-2">385</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0385.html">［25］tun,（tät）</a></div><div class="col-2">385</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0386.html">［26］名詞的用法 （特に作為的なるもの）</a></div><div class="col-2">386</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0387.html">［27］不定句全部の名詞化。</a></div><div class="col-2">387</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0392.html">［28］Soldatentochter <u>und</u> <u>weinen</u> !</a></div><div class="col-2">392</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0400.html">［29〕疑問詞十zu不定法。（の代りにzuを省いて用ふ）</a></div><div class="col-2">400</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0403.html">［30］名詞化</a></div><div class="col-2">403</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../032/s0403.html"> </a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">32-4B</div><div class="col-8"><a href="../032/s0404.html">未然表現（目的表現）としての不定形（参考）</a></div><div class="col-2">404</div></div>');
document.write('<div class="row"><div class="col-2">32-5B</div><div class="col-8"><a href="../032/s0405.html">zu vermieten</a></div><div class="col-2">405</div></div>');
document.write('<div class="row"><div class="col-2">32-6B</div><div class="col-8"><a href="../032/s0410.html">挿入句的zu+Inf. à enjuger par....</a></div><div class="col-2">410-417</div></div>');
document.write('<div class="row"><div class="col-2">32-7B</div><div class="col-8"><a href="../032/s0418.html">聞いて、 泣く、及び：「云々するに当っては」</a></div><div class="col-2">418-426</div></div>');
document.write('<div class="row"><div class="col-2">32-8B</div><div class="col-8"><a href="../032/s0427.html">sagen等とzu+Inf文</a></div><div class="col-2">427-430</div></div>');
document.write('<div class="row"><div class="col-2">32-9B</div><div class="col-8"><a href="../032/s0431.html">ACCUSAT. cum Infinitivo</a></div><div class="col-2">431-451</div></div>');
document.write('<div class="row"><div class="col-2">32-10B</div><div class="col-8"><a href="../032/s0452.html">間投的 was lieben ! （愛するところの騒ぎか）<br />絶対的 ach lieben !</a></div><div class="col-2">452</div></div>');
document.write('<div class="row"><div class="col-2">32-11B</div><div class="col-8"><a href="../032/s0453.html">zuに関する考察 zuと三格語尾=e.</a></div><div class="col-2">453-462</div></div>');
document.write('<div class="row"><div class="col-2">32-12B</div><div class="col-8"><a href="../032/s0463.html">［MHD］直接不定法</a></div><div class="col-2">463-467</div></div>');
document.write('<div class="row"><div class="col-2">32-13B</div><div class="col-8"><a href="../032/s0468.html">start ～ ing, burst ～ ing 等 開始過程其の他</a></div><div class="col-2">468-488</div></div>');
document.write('<div class="row"><div class="col-2">32-14B</div><div class="col-8"><a href="../032/s0489.html"><u>不定法直結</u> 古典語を主に、 仏をも含む。</a></div><div class="col-2">489-503</div></div>');
document.write('<div class="row"><div class="col-2">32-15B</div><div class="col-8"><a href="../032/s0504.html">Historical Infinitive</a></div><div class="col-2">504</div></div>');
document.write('<div class="row"><div class="col-2">32-16B</div><div class="col-8"><a href="../032/s0505.html">im Stande sein+ zu+Inf.</a></div><div class="col-2">505-508</div></div>');
document.write('<div class="row"><div class="col-2">32-17B</div><div class="col-8"><a href="../032/s0509.html">「…とは…」</a></div><div class="col-2">509-516</div></div>');
document.write('<div class="row"><div class="col-2">32-18B</div><div class="col-8"><a href="../032/s0517.html">zu+Inf. 主語関係の会はざるもの</a></div><div class="col-2">517-525</div></div>');
document.write('<div class="row"><div class="col-2">32-19B</div><div class="col-8"><a href="../032/s0526.html">geben + Infinit mit zu<br />［希式文法］云々すべく与える</a></div><div class="col-2">526</div></div>');
document.write('<div class="row"><div class="col-2">32-20B</div><div class="col-8"><a href="../032/s0527.html">Nicht umhin können.</a></div><div class="col-2">527-535</div></div>');
document.write('<div class="row"><div class="col-2">32-21R</div><div class="col-8"><a href="../032/s0536.html">［MHD］いったいun- の結合が多いということ！<br />挙形［絶対用法］ ”云々すること”</a></div><div class="col-2">536</div></div>');
document.write('<div class="row"><div class="col-2">32-22B</div><div class="col-8"><a href="../032/s0537.html">adnominal 関係文を用いるに同じzu +不定句</a></div><div class="col-2">537-562</div></div>');
document.write('<div class="row"><div class="col-2">32-23R</div><div class="col-8"><a href="../032/s0563.html">anfangen等とzu +不定法 －構文の問題－<br />Aufgabeの用語”云々せよ”（<u>命令法</u>に関係す）<br />DELIBERATIV<br />Ich weiß nicht <u>wo</u> anzufanngen.<br />zu +不定法をzum <u>Ankleben</u> などとすること</a></div><div class="col-2">563-565</div></div>');
document.write('<div class="row"><div class="col-2">32-24B</div><div class="col-8"><a href="../032/s0566.html">不定形名詞 Blutvergießen Entgegenkommen</a></div><div class="col-2">566-569</div></div>');
document.write('<div class="row"><div class="col-2">32-25B</div><div class="col-8"><a href="../032/s0570.html">zuを伴ふ不定句とDavon,darin等の省略、或ひは<br />Kontaminationで説明す可き結合。</a></div><div class="col-2">570-574</div></div>');
document.write('<div class="row"><div class="col-2">32-26B</div><div class="col-8"><a href="../032/s0575.html">不定句の絶対用法 das ist ： 型</a></div><div class="col-2">575</div></div>');
document.write('<div class="row"><div class="col-2">32-27B</div><div class="col-8"><a href="../032/s0576.html">云々して以て云々する</a></div><div class="col-2">576</div></div>');
document.write('<div class="row"><div class="col-2">32-28R</div><div class="col-8"><a href="../032/s0577.html">zu+ INF.のzuが仏ではdeまたはàなることに関する<br />参考事項。<br />約束話法の前提部をzu+不定句で表現し得。<br />過去の不定形<br />zu+不定形を一語に書いた時代がある。</a></div><div class="col-2">577-578</div></div>');
document.write('<div class="row"><div class="col-2">32-29B</div><div class="col-8"><a href="../032/s0579.html">Quel mal y-a-t-il à faire cela?</a></div><div class="col-2">579-584</div></div>');
document.write('<div class="row"><div class="col-2">32-30B</div><div class="col-8"><a href="../032/s0585.html"><u>mit Respekt zu melden</u>.</a></div><div class="col-2">585-587</div></div>');
document.write('<div class="row"><div class="col-2">32-31R</div><div class="col-8"><a href="../032/s0588.html">再帰勤詞の ［中性］名詞化にはsichを省く。<br />zu+ Inf. に相当するGERUNDIVUMとGERUNDIUMに就いて<br />非人称のesと、zu+ 不定句の関係及び移轍的現象<br />［初歩］zu+ 不定句には主語なし</a></div><div class="col-2">588-589</div></div>');
document.write('<div class="row"><div class="col-2">32-32B</div><div class="col-8"><a href="../032/s0590.html">WARUM Infin.?<br />WOZU<br />what\'s the use of ....ing ?</a></div><div class="col-2">590</div></div>');
document.write('<div class="row"><div class="col-2">32-33R</div><div class="col-8"><a href="../032/s0591.html">［仏］あいまいな結合のde+不定法<p> </p><p>［仏］Je les connais de les voir tous les jours.<br />Auxiliare Formeln<br />英語のGerund<br />［仏］finir par ～<br />独のdazu beitragen, ....zu,（またはes....、....zu ～）は仏ではà（de）+ 不定形<br />zu+不定法の代りのdassの文［古］<br />編者注：このほか4件あり。</p></a></div><div class="col-2">591-595</div></div>');
document.write('<div class="row"><div class="col-2">32-34B</div><div class="col-8"><a href="../032/s0596.html">［英］Gerundの名詞的用法</a></div><div class="col-2">596</div></div>');
document.write('<div class="row"><div class="col-2">32-35B</div><div class="col-8"><a href="../032/s0597.html">［仏］不定法のみの用法 Autant en profiter<br />どうせ…なら…いっそ…</a></div><div class="col-2">597</div></div>');
document.write('<div class="row"><div class="col-2">32-36R</div><div class="col-8"><a href="../032/s0599.html">不定法の名詞化には殊に行事、挙動、Verrichtung<br />所作多し。<br />編者注：このほか5件あり。</a></div><div class="col-2">598-600</div></div>');
document.write('<div class="row"><div class="col-2">32-37B</div><div class="col-8"><a href="../032/s0601.html">zu+不定句と本文との融合</a></div><div class="col-2">601</div></div>');
document.write('<div class="row"><div class="col-2">32-38R</div><div class="col-8"><a href="../032/s0602.html">間投的絶対用法の不定句<br />［英］There is no use denying 等<br /><u>zu+ 不定法</u>、［参考］<br />daßが重なる時にzu+不定法。<br />zu 不定法+haben.ねばならぬ（四格無きを純<br />とす。）<br />編者注：このほか14件あり。</a></div><div class="col-2">602-611</div></div></div>');