document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">34-1B</div><div class="col-8"><a href="../034/s0001.html">時称 過去</a></div><div class="col-2">1-51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0002.html">［01］durativisch.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0009.html">［02］Iterative Aktion. 習慣（pflegte zu ....）</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0011.html">［03］immer nimmer等を伴ふ際。<br />（少し客観的に見る）</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0011.html">［04］Iterative Aktion <u>oft</u></a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0018.html">［05］過去中の未来。（<u>iturus</u> essem, usw.）</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0018.html">［06］間接話法としての過去形</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0022.html">［07］約束法の代り。（würde?）未来の代り</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0028.html">［08］前にさう言ふ事を述べて置いた。</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0031.html">［09］Das war ein Wort! ［味わった後、感じの判断<br />をロにする時に用ひる過去］</a></div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0036.html">［10］Gnomischer Aorist.（現在完了もあり）</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0043.html">［11］現在完了代りに用ひるもの。</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0048.html">［12］終熄的現完了に似たる用法。</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2">34-2B</div><div class="col-8"><a href="../034/s0052.html">時称 未未</a></div><div class="col-2">52-97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0055.html">［01］普通の例（確実さの約束－－のタイプなり。）</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0060.html">［02］単に推察の意。</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0064.html">［03］例証的想像（sagen....wir....）一般的宣言<br />wirt so tun....wenn der Fall wirklich eintritt.</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0080.html">［04］命令法的用法</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0083.html">［05］現在形で表現。（殊にwenn-）</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0085.html">［06］決心の表現（<u>きっぱり</u>と） 予言</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0090.html">［07］勿論…だらうね？</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0091.html">［08］wennの場合</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0092.html">［09］如何にも<u>未来</u>らしき時に用ふ（ausdrücklicher<br />Zukunft begriff）</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0093.html">［10］sollenと同じ、（自己の決心決菅をいふ）<br />仏は必ず未来</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0094.html">［11］Konjunctivus Diplomaticusと殆ど同じ用法。</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0095.html">［12］<u>sollte</u>と同じ用法</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0095.html">［13］未来時称に不定形はないか挙形としては可能：</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0097.html">［14］反問のII.Kと同じもの。疑問詞とと共に。<br />（別に間投詞には非ざるもの）</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2">34-3B</div><div class="col-8"><a href="../034/s0098.html">編者注：本袋「34-3B」内は二つの<br />ノート・ブックに整理されている</a></div><div class="col-2">98-125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0098.html">ので、これを記号①、②で示すこ<br />とにした。</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0098.html">扮役的直接法</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0100.html">①［01］Nesthäkchen und der Weltkrieg</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0110.html">①［02］<u>現在時称</u>の場合<br />（会話文に多し、嘸ぞ…でしょうよ、など）</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0113.html">①［03］<u>Praesens mimicum</u></a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0115.html">①［04］副文章内に現れる（関係文が主）ものにして、<br />元来は接続法たる可きものが、扮役の意味<br />で直接法の過去になるもの。</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0115.html">①［05］一語が扮役的なるもの。</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0116.html">①［06］間接話法の独立用法（そのまま直接法過去に<br />すればMimicusになる）<br />欺瞞的直接法 ［Indicativus hypocriticus］<br />wollen,sollenの問題に関係す。（”であった<br />事にしてしてしまふ等。）</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0118.html">②［01］</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0124.html">②［02］［仏］間接話法の独立文化と同意のもの</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2">34-4B</div><div class="col-8"><a href="../034/s0126.html">時称 現在完了</a></div><div class="col-2">126-214</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0129.html">［01］niemals, immerを伴ふ場合。（過去総体を一括<br />して）</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0138.html">［02］…した「のである」（言者の判断）</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0145.html">［03］jeを伴ふ場合</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0146.html">［04］現在そのものを指す。</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0157.html">［05］過去を偲ぶ現在完了。［einst］</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0161.html">［06］「しまふ」とは譯せない。今までずっと<br />働いていて、その影響が現在も残っている。<br />（statische Aktionの動詞）</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0162.html">［07］「結果が現在に残る」といふ例。</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0165.html">［08］結果が現在に残る、他の例。<br />－した経験をもっている。－</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0165.html">［09］一般的に「…の例がある」と普遍化して言ふ際</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0166.html">［10］現在完了、又は過去完了、未来完了に代り得る<br />Durativa.</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0167.html">［11］bis, sobaldは好んで「完了。」（状態）</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0173.html">［12］habenを用ふることの説明。</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0175.html">［13］終熄の現在完了</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0184.html">［14］…云々であった事にしてしまふ。</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0193.html">［15］現在を使っても同じになる。<br />ist geblieben, hat sich erhalten.</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0199.html">［16］habenのみと同意になる（過去分詞を除いても<br />同じ）</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0200.html">［17］seinと同意になる。（er <u>ist</u> um die Ecke等と関係して）</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0201.html">［18］jetzt等と共に。（しまっている）（しまった）</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0202.html">［19］Gern geschehen! Ist bald gesagt!</a></div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0207.html">［20］seitの際は？ <u>状態詞</u>は現在<br />動作詞は完了</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0208.html">［21］未来完了の代りに（確認的現完に近きものあり）</a></div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0210.html">［22］Gnomischer Aorist. 過去もあり。</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2">34-5B</div><div class="col-8"><a href="../034/s0215.html">時称 過去完了</a></div><div class="col-2">215-249</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0216.html">［01］例。（過去たる事の一目瞭然たる）</a></div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0226.html">［02］過去の或瞬問に於ける「状態」を指す。</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0227.html">［03］Nachdem.</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0228.html">［04］hatteの説明に。（持っていた）</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0228.html">［05］終煌（nicht mehr!）</a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0229.html">［06］迅速さを示す完了形（又はStativa）</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0231.html">［07］alsと過去完了。</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0231.html">［08］現在・對・過去完了</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0237.html">［09］時問を飛ばして状態に移るもの。</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0237.html">［10］kaum型意型（als....）</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0238.html">［11］云々しつつあった。／<u>していた</u>。</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2">34-6R</div><div class="col-8"><a href="../034/s0250.html">直前過去 ［仏］venir d\'arriver<br />［西］acabar de llegar<br />逼迫的未来 FUTURUM IMMINENS</a></div><div class="col-2">250-254</div></div>');
document.write('<div class="row"><div class="col-2">34-7B</div><div class="col-8"><a href="../034/s0255.html">時称 現在</a></div><div class="col-2">255-295</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0256.html">［01］一般宣告の現在。</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0257.html">［02］進行形現在。</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0259.html">［03］未来代りの現在。</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0262.html">［04］要求的現在（現在とは限らず、完了）</a></div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0263.html">［05］現完的。ich komme! （未来的）<br />da kommt er!</a></div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0281.html">［06］Historisches Präsens. ［Narrativisch］</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0282.html">［07］将に云々せんとする。（er stirbt!）</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0283.html">［08］所謂Historisches Präsensは、或種の出来事の<br />系列を一完した劇的局面としてまとめて描<br />出して相手の全体的把握に訴へるときにも<br />用ひる。（sich davon ein Bild machen）</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0288.html">［09］未来のことを取極める際の相談。（叙述的）</a></div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0289.html">［10］We <u>have been</u> married now for a year.</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0295.html">［11］直前過去：Il me vient une idée.</a></div><div class="col-2">295</div></div>');
document.write('<div class="row"><div class="col-2">34-8B</div><div class="col-8"><a href="../034/s0296.html">過去完了<br />物語調の現完<br />通俗調の Perfectum historikum<br />過去の代り（Erzählungsstil） 俗調</a></div><div class="col-2">296-303</div></div>');
document.write('<div class="row"><div class="col-2">34-9R</div><div class="col-8"><a href="../034/s0304.html">［MHD］完了形（殊に助動詞）は単に過去で<br />［MHD］の未来形</a></div><div class="col-2">304-307</div></div>');
document.write('<div class="row"><div class="col-2">34-10B</div><div class="col-8"><a href="../034/s0308.html">時称 未来完了</a></div><div class="col-2">308-317</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0309.html">［01］例</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0313.html">［02］現在完了を以て代ふ。</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0315.html">［03］想像のwerden.</a></div><div class="col-2">315</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0316.html">［04］単なる未来と同じになる。</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0316.html">［05］werdenの「確言的用法」にあたるもの。</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0317.html">［06］antizipierend</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0317.html">［07］wemの場合はwerdenを省く</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2">34-11B</div><div class="col-8"><a href="../034/s0318.html">現在完了の重要形態：－云々している－</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2">34-12B</div><div class="col-8"><a href="../034/s0319.html">Er ist um die Ecke等</a></div><div class="col-2">319-324</div></div>');
document.write('<div class="row"><div class="col-2">34-13B</div><div class="col-8"><a href="../034/s0325.html">Konstatieren der Aorist</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2">34-14B</div><div class="col-8"><a href="../034/s0326.html">現在完了 「云々していた」 「云々しつつあった」</a></div><div class="col-2">326-330</div></div>');
document.write('<div class="row"><div class="col-2">34-15B</div><div class="col-8"><a href="../034/s0331.html">未来表現</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2">34-16B</div><div class="col-8"><a href="../034/s0332.html">英語の現在完了</a></div><div class="col-2">332-334</div></div>');
document.write('<div class="row"><div class="col-2">34-17B</div><div class="col-8"><a href="../034/s0335.html">［仏］venir de 時称 －直前過去－</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2">34-18B</div><div class="col-8"><a href="../034/s0336.html">現在・未来と対照する過去対称</a></div><div class="col-2">336-341</div></div>');
document.write('<div class="row"><div class="col-2">34-19B</div><div class="col-8"><a href="../034/s0342.html">現完PARADIGMA集</a></div><div class="col-2">342-345</div></div>');
document.write('<div class="row"><div class="col-2">34-20B</div><div class="col-8"><a href="../034/s0346.html">［羅］書簡で過去形 <u>Perfectum</u></a></div><div class="col-2">346</div></div>');
document.write('<div class="row"><div class="col-2">34-21B</div><div class="col-8"><a href="../034/s0347.html">完了形助動詞habenにっいての参考</a></div><div class="col-2">347</div></div>');
document.write('<div class="row"><div class="col-2">34-22B</div><div class="col-8"><a href="../034/s0348.html">たとえ現在時称文肢でも、過去の出来事を一つ抽出し<br />て報告する時（英は過去）</a></div><div class="col-2">348-349</div></div>');
document.write('<div class="row"><div class="col-2">34-23R</div><div class="col-8"><a href="../034/s0350.html">現完の意局果たすべき義務としての行為が問題にな<br />る場合<br />希羅のPerfectumと <u>Präterio-Praesentia的意型</u><br />英の現在完了と過去副詞との関係</a></div><div class="col-2">350-351</div></div>');
document.write('<div class="row"><div class="col-2">34-24B</div><div class="col-8"><a href="../034/s0352.html">完了形の不定法 （総括的）</a></div><div class="col-2">352-353</div></div>');
document.write('<div class="row"><div class="col-2">34-25B</div><div class="col-8"><a href="../034/s0354.html">真に現在に至って完成したもの</a></div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2">34-26R</div><div class="col-8"><a href="../034/s0355.html">独では現完・英では過去<br />脚本卜ガキ中の過去に遡る時の現在完了<br />［仏］<u>Passé antéreur</u><br />［仏］Passé définiとPassé indéfini</a></div><div class="col-2">355-364</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8"><a href="../034/s0355.html">編者注：このほか13件あり。</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2">34-27B</div><div class="col-8"><a href="../034/s0365.html">Stativa（lieben, hassen等）の代りに完了形を用ふる<br />熟語</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2">34-28R</div><div class="col-8"><a href="../034/s0366.html">簡潔ならんがための過去の自由な用法。<br />過去時称（<u>Einmaligkeit</u>の強調）<br />Ohne....zu haben<br />受勤状態の完了形（後傾性）<br />wir sind gefangen !<br />現在完了でも過去でも好い際<br />過去 gehalt haben と過去分詞。<br />gewessen sein<br />云々していたことがあった。<br /><u>現在完了</u>。<br />［芝居のAnweisungに於て、現在形の文脈中に<br />現れる場合。<br />完了形の説明。（日本語）<br />僕はくたびれ<u>た</u>。 ich bin müde.<br />Davon, habe ich nichts gehört.</a></div><div class="col-2">366-369</div></div></div>');