document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">35-1B</div><div class="col-8">編者注：本袋「35-1B」内は資科数<br />が多いのて資科番号、（1）,（2）<br />…に対応した目次を付けてある。</a></div><div class="col-2">1-177</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">述語句</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（1）Genitivus absolutus</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（2）［seiend形態］省略文的 bei offenem Fenster.</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（3）成句的なるもの eingerechnet....</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（4）述語句の自由描写的タイプ<br />Appositive, Supplementativ</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（5）仮定的、挿入的なものは分ける可し。</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（6）Zwanzig Männer verbunden, 等の句</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（7）Partizipium Präs. statt eines ganzen Satzes.</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（8）<u>mit</u> meinem Willen（=me volente）</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（9）Adnominalな熟語句</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（10）<u>コンマの問題</u> 仏では副詞化するので省くこと<br />が多い</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（11）一格、四格主語と現在分詞の句。</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（12）省略主文に附く熟語句</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（13）einmal:</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（14）前置詞附一文肢の如くにして実は熟語句なるもの</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（15）－語順－ 述語句に於ける基語を前に置く</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（16）仏：現在分詞の「形容詞性」は女性の際に明瞭：<br />Palpitant<u>e</u></a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（17）非人称主語文（又はes）と述語句。</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（18）短かい熟語句</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（19）其の他の熟語句的文肢</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（20）四格と過去分詞及び0省略句。</a></div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（21）迅速なる描写の過去分詞</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（22）述語の前にobgleich等基礎的要素を附するもの</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（23）熟語句総論（参考）</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（24）現在分詞句の特殊用法：－左手を眺むれば、等－</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（25）Kommaなしに附ける簡単な熟語句</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（26）habend, seiend, sollend等を実際入れた例</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（27）書簡の終句と現在分詞句</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（28）受働的語法の場合</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（29）熟語句の位置に関係代名詞文を用ふ</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（30）so schwatzend und malend verging die Zeit</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（31）述語句</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（32）拉丁語の現在分詞句（格変化する実例）</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（33）述語句一般の説明に必要なもの。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（34）tragennd形態（省略形）</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（35）附加語的述語を名詞の前に置く例。</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（36）省略述語句と見られるもの。 Aug in Auge.</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（37）簡単な過去分詞（特）</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（38）英仏語の述語句 having,being. ce disant.</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（39）habend形態（省略形）</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（40）［英］thoughや、whenと省略語句</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（41）予備部（あらゆる形態を含む）</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（42）稀な非人称動詞の分詞句</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（43）意味形態の上から見た述語句の分類</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（44）現在分詞を基礎とするもの</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（45）過去分詞を基礎に</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（46）述語句、einmal.... sobald...</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（47）Dies geschehen. cela fait.</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（48）［英］述語句が前置詞を伴う場合<br />Upon the door being opend（扉が開くと）</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（49）因由的</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（50）述語名詞（即ちApposition）</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（51）GerundかAbsolutiveか 連続體</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（52）形容詞を基礎とするもの</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（53）荘重なる現在分詞の使用例</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（54）未来分詞を基礎とするもの</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（55）一格以外を主語とする述語句</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2">35-2R</div><div class="col-8">Adnominal用法ある前置詞の諸型は、seinを介して、<br />其の侭adverbal用法に移し得<br />MET0NYMIE<br />up to,in on,in for等の結合<br />［仏］loin,bien,mal等 副詞述語に<br />［仏］debout<br />大範疇をなすPrädicativ paradoxiae causaの一般例</a></div><div class="col-2">178-181</div></div>');
document.write('<div class="row"><div class="col-2">35-3B</div><div class="col-8">編者注：本袋「35-3B」内は資料数<br />が多いので、資料番号、<br />（1）,（2）<br />…に対応した目次を付けてある。<br />…を…と 及びzu,seinをも</a></div><div class="col-2">182-267</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（1）「を…と」型</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（2）独の場合（als,fürを介せざる結合）</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（3）Er glaubt <u>mich</u> <u>tot</u>.</a></div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（4）zu（として）型多し</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（5）「を…と」と不定法</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2">35-4B</div><div class="col-8">編者注：本袋「35-4B」内は資料数<br />が多いので、資料番号、（1）,（2）<br />…に対応した目次を付けてある。</a></div><div class="col-2">268-361</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">変態的述語</a></div><div class="col-2"> </div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（1）Ihr wart sonst <u>eine</u> <u>freie Stadt</u> ?</a></div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（2）A ist B （bedeutet）（hat zur Folge）</a></div><div class="col-2">275</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（3）Die Zeit ist <u>um</u>.</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（4）Und Berlin war schon eine <u>Bescheidung</u>.</a></div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（5）…ist eine Unmöglichkeit=unmöglich</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（6）Ihr erster Gang <u>war</u> nach dem Bach.</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（7）変態的述語とKopula</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（8）Hin ist hin.</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（9）Paradoxiae causa <u>何々そのものである</u></a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（10）He was the <u>color</u> of cheese</a></div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（11）Verweisungen:</a></div><div class="col-2">350</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（12）....war <u>freier Wille</u>.<br />=....war Folge eines freien Willens.</a></div><div class="col-2">350</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（13）C\'est ce ～ 「…の件がある」</a></div><div class="col-2">351</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（14）花は桜木人は武士</a></div><div class="col-2">351</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（15）Glück = glückssache 或はGegenstand....?</a></div><div class="col-2">352</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（16）Kapazität</a></div><div class="col-2">352</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（17）［仏］Quel jour sommes-nous aujourd\'hui?</a></div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（18）Er ist <u>ein grosser Geist</u> → 人のMetonymie</a></div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（19）The child is three （sc.years old）</a></div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（20）palam est</a></div><div class="col-2">354</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（21）Erfindung等</a></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（22）Paradoxiae causa</a></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（23）基礎項の一つ（わかり易いもの）</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（24）雑</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（25）The pressure <u>was</u> on Germeny.</a></div><div class="col-2">357</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">（26）Es war zur Zeit der …云々<br />（daßの文の省略）</a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2">35-5B</div><div class="col-8">述語</a></div><div class="col-2">362-546</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［01］___を受ける追加的名詞述語。 不定冠詞</a></div><div class="col-2">368</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［02］述語の状況的用法。（形容詞の副詞的位置）</a></div><div class="col-2">387</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［03］過去分詞四格述語がhabenを伴ふ場合（wollen）</a></div><div class="col-2">396</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［04］名詞述語に用ふる筈のalsを形容詞にも冠せる。</a></div><div class="col-2">399</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［05］fürを用ひる場合。</a></div><div class="col-2">400</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［06］was für ein.</a></div><div class="col-2">401</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［07］a1sと名詞。</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［08］述語（名詞、形容詞）のみの主文章</a></div><div class="col-2">402</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［09］文中の四格を宣言する述語的形容詞</a></div><div class="col-2">413</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［10］<u>K0PULA</u>とは何ぞや。</a></div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［11］ich habe es <u>heraus</u>.</a></div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［12］<u>was</u>が述語になる事。</a></div><div class="col-2">437</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［13］述語文の代りにbedeuten, vorstellen, abgeben</a></div><div class="col-2">438</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［14］bleibenの用法</a></div><div class="col-2">454</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［15］…であった所の彼は、等。</a></div><div class="col-2">455</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［16］das,was....の述語</a></div><div class="col-2">457</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［17］関係代名詞<u>der</u>, <u>was</u>の述語。</a></div><div class="col-2">458</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［18］<u>als</u>の省略。（Freies Prädikat）</a></div><div class="col-2">465</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［19］welchesの述語（疑問詞）<u>was</u></a></div><div class="col-2">466</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［20］welchesの述語（関係代名詞）</a></div><div class="col-2">467</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［21］述語</a></div><div class="col-2">467</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［22］es <u>so</u> haben ［od.wissen］wollen</a></div><div class="col-2">468</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［23］主語、述語関係に非ずして、存在のseinによって<br />つながれる筈の主語と副詞規定をglauben、<br />vermuten等で一文にする。</a></div><div class="col-2">482</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［24］完了形と区別しがたき場合。</a></div><div class="col-2">492</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［25］Nennsatzの諸形態。（使用の動詞）</a></div><div class="col-2">493</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［26］「wie + 代名詞」の述語的関係代名詞。</a></div><div class="col-2">494</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［27］etwas für etwas nehmen.<br />halten.<br />ausgeben.</a></div><div class="col-2">496</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［28］形容詞述語の先置</a></div><div class="col-2">531</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［29］<u>Repetitio</u>.</a></div><div class="col-2">532</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［30］附加詞的述語</a></div><div class="col-2">534</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［31］werden等と四格。（lassen） <u>sich</u></a></div><div class="col-2">536</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［32］「と」四格述語支配（命令文） 一格の異例。</a></div><div class="col-2">539</div></div>');
document.write('<div class="row"><div class="col-2"> </div><div class="col-8">［33］einem sich dünken, sich vork0mmen, scheinen</a></div><div class="col-2">541</div></div></div>');