document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">42-1B</div><div class="col-8">前綴  複合動詞</a></div><div class="col-2">1-82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］形容詞。 Die, die der Biologie fernstehen.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］名詞 heim-gehen  statt finden</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］分離前綴を副文章の後に後置せざるを可と<br>する場合。</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］具體的動作にhin等の必要な場合</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］<u>vonstatten gehen</u>等（前置詞に）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>anheim</u>, <u>zugrunde</u>,等</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］<u>wieder</u>は副詞なるか前綴なるかアイマイなり。<br>一字に書く習憤を訳むるのみ（其他此の種<br>のもの多し）</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］前綴は、前置詞の位置の変りたるものなること<br>あり。</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］auf zum Himmel</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］前綴でもあり副詞でもあり…</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2">42-2B</div><div class="col-8">分離動詞</a></div><div class="col-2">10-34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］分綴がずっと後に来る例。</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］<u>Im</u> Kaffee ist kein Zucker <u>drin</u>.</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］英語、似た場合。  He <u>smuggled</u> wine <u>in</u>.</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］前綴の副詞的語局回復<br><u>hinaus in</u> die Natur.等</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］<u>Tmesis</u></a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］名詞前綴。  stattfinden</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］<u>näherkommen</u>等の書方</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］前綴が前直詞と誤解され易い語順。</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］vonnöten等  zugute kommen  fürlieb nehmen</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2">42-3B</div><div class="col-8">非分離動詞  複合動詞</a></div><div class="col-2">35-80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>radebrechen</u></a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］frohlocken型（文例の部）</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］frohlocken型（単語）</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］<u>be</u>mitleiden型（新造）</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］<u>中間現象一般</u></a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］<u>nebenbuhlen</u>.</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］be=anspruchen  名詞より</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］人称変化が基語とは違ふ  er <u>willfahrte</u></a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］geschriftstellert.</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］selbst<u>schaffen</u>, recht<u>schaffen</u>等の現象</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］überan<u>ge</u>steengt等</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］<u>aus</u> gekundschaftet</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］ver=を分離に［特］</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］特にoffenbaienに関して。</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］主として現在分詞形及ぴ不定形<br>zähne knirschend</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2">42-4B_</div><div class="col-8">über  分離=hinüberの意<br>herüber</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2">42-5B</div><div class="col-8">或ひは分離し或ひは分離せざる前綴  複合動詞</a></div><div class="col-2">82-109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>um</u> 不分離</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］anerbietenを非分離に</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］unterlaufenを非分離に。</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］obliegenを非分離に。</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］voll=非分</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］vorenthaltenを非分離に。</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］anvertrauen等を非分離に</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］unterlegenを非分離に。</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］<u>wieder</u>=（<u>wiederkäuen</u>等）</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］miß=verstehen等</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］übertragen（翻訳）を分離に</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］vorkühlen等を非分離に</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">42-6B</div><div class="col-8">［英］分離動詞と平行する諸形態<br>分離動詞の名詞化</a></div><div class="col-2">110-119</div></div>');
document.write('<div class="row"><div class="col-2">42-7R</div><div class="col-8">über=超の場合は単にアクセン卜で決まる！<br>über<u>völ</u>kert  <u>über</u>belichtet  überspannt<br>前綴の具体的<u>描写効果</u> Andröhnt die Glocke.<br>Hin gleitet der Kahn.  Abstürzt der....<br>日本語  買いあさる（漁）  賣り払ふ<br>溜める  損う<br>付ける  はぐれる<br>戻す  とぱす<br>電報文では分離せずに用ふ<br>Es fängt zu regnen <u>an</u><br>［英］関係文と分離動詞<br>［英］to <u>clear</u> the matter <u>up</u>.<br>前置詞支配と分離（非分離）前綴との一致する場合<br>überkam sie = kam über sie<br><br>編者注：このほか17件あり。</a></div><div class="col-2">120-134</div></div></div>');