document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">43-1B</div><div class="col-8"><a href="../043/s0001.html">Es gibt   Es gibt と Es ist<br></a></div><div class="col-2">1-40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0003.html">［01］es gibt. （一般的存在）現在時称</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0010.html">［02］一般的存在ならざるes gibt.  <u>setzt</u>....<br><u>geht....ab</u>（何か変わった事がある等）</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0020.html">［03］es gab, es hat gegeben.</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0021.html">［04］両者が完全に一致する場合。（<u>möglich sein</u>.）<br>（gibt!）</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0029.html">［05］es setzt etwas.（=es gibt etwas）</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0033.html">［06］Es Besteht （eine Gefahr）  es liegt-vorも</a></div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0034.html">［07］es gibt keine（云々する餘地なし） möglich</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2">43-2B</div><div class="col-8"><a href="../043/s0041.html">非人称動詞</a></div><div class="col-2">41-128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0042.html">［01］天候でもなく気持でもなき非人称動詞。</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0046.html">［02］気持。（leidende Aktion was man <u>erleidet</u>）</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0062.html">［03］気持に関するものの際のesの省略</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0065.html">［04］非人称熟語</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0067.html">［05］非人称句</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0071.html">［06］Dasを主語とする感嘆的非人称句。</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0073.html">［07］Das ist ein Geigen und Flöten!</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0074.html">［08］文の非人称化</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0009.html">［09］普通動詞の非人称化（音、運動、體感）</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0096.html">［10］Unheimliche Geräusche u. Er scheinungen.<br>（esは省き難し）</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0097.html">［11］Es <u>wird</u>.... Es <u>bleibt</u></a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0099.html">［12］Es ist mir zumute.  zu sinn<br>Es wird mir zumute. ums Herz</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0102.html">［13］Es ist....（存在のseinをも含めて）</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0111.html">［14］不定法の名詞化と不定冠詞。</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0111.html">［15］非人称句の基に助動詞的動詞が入る時</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0112.html">［16］天候気象等（meteorologische Impersonalia）</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0122.html">［17］ニ格を取るもの。</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0122.html">［18］Esこそ取らね、schmecken等も非人称である。<br>それがまた、ich等の主語を取ることがある。<br>（例外的現象）</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0123.html">［19］人工的非人称語法。（人間の中）</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0123.html">［20］論理的主語の指示代名詞なるもの。</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0124.html">［21］倒置とesの省略。</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0125.html">［22］人間の三、四格を取るもの。</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0125.html">（主語はesに限らず）</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0126.html">［23］es läßt sich ----.</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0128.html">［24］<u>Mit</u> dem <u>war</u> nicht <u>zu scherzen</u>.<br>（Esを省略するものとせざるものと）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2">43-3B</div><div class="col-8"><a href="../043/s0129.html">Es <u>kommt</u> <u>zu</u> etwas.  etwas geschieht.<br>es wirt （getanzt）&gt;</a></div><div class="col-2">129-134</div></div>');
document.write('<div class="row"><div class="col-2">43-4R</div><div class="col-8"><a href="../043/s0135.html">私もそうなのよ。  Mir <u>geht es</u> so.<br>Es beliebt. ［羅］Si libet,licet.</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2">43-5B</div><div class="col-8"><a href="../043/s0136.html">es heißt.</a></div><div class="col-2">136-139</div></div>');
document.write('<div class="row"><div class="col-2">43-6B</div><div class="col-8"><a href="../043/s0140.html">偶然の表現  Es fügte sich</a></div><div class="col-2">140-153</div></div>');
document.write('<div class="row"><div class="col-2">43-7B</div><div class="col-8"><a href="../043/s0154.html">Es <u>hält</u> schwer<br><u>fällt</u>（wird）<br><u>hat</u><br>Es <u>nimmt</u> wunder  （sein以外のkopula）</a></div><div class="col-2">154-159</div></div>');
document.write('<div class="row"><div class="col-2">43-8B</div><div class="col-8"><a href="../043/s0160.html">Es <u>hat</u>....</a></div><div class="col-2">160-163</div></div>');
document.write('<div class="row"><div class="col-2">43-9B</div><div class="col-8"><a href="../043/s0164.html">［エ］非人私Esの主語の時、述語形容詞は -e.</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2">43-10B</div><div class="col-8"><a href="../043/s0165.html">存在を意味する動詞とその微妙な使い分け<br>STATIVAの研究</a></div><div class="col-2">165-172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0166.html">［01］stehen.</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0167.html">［02］<u>liegen</u>.</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0168.html">［03］bleiben.</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0168.html">［04］stecken.</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0169.html">［05］sitzen.</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0171.html">［06］hängen.</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0171.html">［07］sich befinden.</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0171.html">［0B］vorliegen.</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0171.html">［09］bestehen.</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0172.html">［10］vorhanden sein.</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0172.html">［11］wohnen.</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0172.html">［12］<u>stehen</u>（具体的）</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../043/s0172.html">［13］<u>befindlich</u></a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2">43-11B</div><div class="col-8"><a href="../043/s0173.html">Es handelt sich um ～</a></div><div class="col-2">173-177</div></div>');
document.write('<div class="row"><div class="col-2">43-12B</div><div class="col-8"><a href="../043/s0178.html">非人称主語と内容あるesとの問題</a></div><div class="col-2">178-181</div></div>');
document.write('<div class="row"><div class="col-2">43-13R</div><div class="col-8"><a href="../043/s0182.html">es ist einem um ～ zu tun.<br>［羅］praestat....INF.</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2">43-14B</div><div class="col-8"><a href="../043/s0183.html">古代中世の非人称動詞</a></div><div class="col-2">183-211</div></div>');
document.write('<div class="row"><div class="col-2">43-15B</div><div class="col-8"><a href="../043/s0212.html">［調子、景況］Es geht so und so.<br>Beim Mahre ging es hoch her.</a></div><div class="col-2">212-217</div></div>');
document.write('<div class="row"><div class="col-2">43-16B</div><div class="col-8"><a href="../043/s0218.html">Es geht einem so und so.  運命、成り行き<br>Es wider fährt einem～. Es geschiet einem ～</a></div><div class="col-2">218-221</div></div>');
document.write('<div class="row"><div class="col-2">43-17R</div><div class="col-8"><a href="../043/s0222.html">非人称現象の説明用に Das <u>quält mich</u>.<br>wieを伴う際［alles,nichtsを伴ふもの。］</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2">43-18B</div><div class="col-8"><a href="../043/s0223.html">天候気象気持等の範疇に属せざるもの：<br>（es stimmt, es klappt等）</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2">43-19R</div><div class="col-8"><a href="../043/s0224.html">現象とは何ぞや？<br>HeideggerのVorhandenとZuhanden.<br>（故障が起こるとそのVorhandenheitが発見<br>されること）<br>編者注：このほか14件あり。</a></div><div class="col-2">224-233</div></div>');
document.write('<div class="row"><div class="col-2">43-20B</div><div class="col-8"><a href="../043/s0234.html">es geziemt, es gehört sich.</a></div><div class="col-2">234-236</div></div>');
document.write('<div class="row"><div class="col-2">43-21R</div><div class="col-8"><a href="../043/s0237.html">普通は省かれる非人称"es"に関する参考：<br>（1）非人私受働形<br>（2）ist zu ～ 不定形<br>特に入れた例（意味あり：）<br>誰にも責任なし、esに責任あり…など…<br>避人稱と社会心理<br>Es ist von ～ die Rede （Frage）.<br>Es kam von ～ nicht die rede sein.<br>esと字母の頻繁律的考察  Enistarda<br>es genügt<br>es gehtans + <u>Inf</u>.<u>が始まる</u></a></div><div class="col-2">237-242</div></div>');
document.write('<div class="row"><div class="col-2">43-22B</div><div class="col-8"><a href="../043/s0243.html">Es geht = es wird gegengen<br>man geht<br>地形を述べるes geht等。時に関するes geht ～</a></div><div class="col-2">243-248</div></div>');
document.write('<div class="row"><div class="col-2">43-23R</div><div class="col-8"><a href="../043/s0249.html">非人稱総論<br>分離不可能なもの［雑］<br>Es wird einem so und so.（運命）<br>編者注：このほか6件あり。</a></div><div class="col-2">249-260</div></div>');
document.write('<div class="row"><div class="col-2">43-24B</div><div class="col-8"><a href="../043/s0261.html">Es setzt etwas</a></div><div class="col-2">261-264</div></div>');
document.write('<div class="row"><div class="col-2">43-25B</div><div class="col-8"><a href="../043/s0265.html">Es kommt auf ～ an</a></div><div class="col-2">265-270</div></div>');
document.write('<div class="row"><div class="col-2">43-26B</div><div class="col-8"><a href="../043/s0271.html">Es liegt einem daran.<br>Es ist einem viel daran gelegen.</a></div><div class="col-2">271-272</div></div>');
document.write('<div class="row"><div class="col-2">43-27B</div><div class="col-8"><a href="../043/s0273.html">Es denkt in mirなど</a></div><div class="col-2">273-275</div></div>');
document.write('<div class="row"><div class="col-2">43-28B</div><div class="col-8"><a href="../043/s0276.html">運命（παθοζ）一般</a></div><div class="col-2">276</div></div></div>');