document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">47-1B</div><div class="col-8"><a href="../047/s0001.html"><u>Sollen</u></a></div><div class="col-2">1-152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0004.html">［01］基本的：何人かの<u>意志</u><br>Sie <u>sollen</u> eine gute Note erhalten.</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0025.html">［02］Wenn....soll.［目的］ 1.andersの機能<br>2.［もし…せしめんとならば］</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0032.html">［03］意志の主体が道義律、習慣其の他一般に認めら<br>れたもの。（<u>判断</u>が加はる）</a></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0038.html">［04］疑問文に現われるsollenとsollte<br>［sollte ich....?］</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0042.html">［05］疑問文に伴ふsollen, sollte.<br><u>Wie sollte ich</u> wohl?</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0047.html">［06］Prädestination.［sollte］ <u>直接法過去</u>。</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0061.html">［07］glauben, meinen, vermuten等と共に：</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0073.html">［08］同主語でwollenをも用ひられそうなもの：<br>Modus deliberativus.</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0090.html">［09］…の由（<u>wird behauptet</u>）</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0097.html">［10］<u>falls</u>....sollte,等 －”ひよっと”－</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0101.html">［11］（？）項</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0103.html">［12］否定的音局。［<u>II.K的</u>］</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0114.html">［13］<u>云々して見るか好い</u>！</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0116.html">［14］und sollte ich....!  認容・挑み</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0120.html">［15］不當の壓迫の引用。</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0129.html">［16］was <u>soll</u> das ［heißen］?</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0130.html">［17］Mir ist, <u>als ob</u> ich die Hände aufs Haupt dir<br>legen sollt\'....</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0132.html">［18］直接法本動詞のままで表現する受身の場合<br>－（一見地）－</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0133.html">［19］sollte（元来……す可き筈のものだ）</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0135.html">［20］本動詞を省く（方向規定）</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0136.html">［21］外交的接続法の代り。<br>（時としては<u>würde</u>に同じ）<br><u>Es sollte mir leid tun</u>等</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0137.html">［22］<u>Drohung</u>, Schwäre  （Apokopeに多し）</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0142.html">［23］特に<u>Warum</u> <u>sollte</u>（soll） ich nicht....?<br>Wen sonst....?</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0143.html">［24］Wie sollte ich--?  云々してよかろうか！<br>何で…しようぞ！</a></div><div class="col-2">143</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0145.html">［25］Aberdassollnichtheißen....<br>［daswillheißenの逆］<br>…のつもり<br>…の意味<u>gemeint</u></a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0146.html">［26］<u>Es soll mich freuen</u>, wenn....</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0147.html">［27］特に：…したつもりである。</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0148.html">［28］<u>Soll</u> man da nicht Kopfscheu werden?<br>こうなると一寸おじけづかざるを得ないじゃ<br>ありませんか！</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0149.html">［29］目的、使命（即ち意図）</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2">47-12B</div><div class="col-8"><a href="../047/s0153.html">Wollen  助動詞 <u>Wollen</u></a></div><div class="col-2">153-190</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0156.html">［01］意志なきものを主語にする際。</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0160.html">［02］独立用法。</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0164.html">［03］意志なきものを主語にする際の第二。<br>muß....werdenの意のwill....sein.</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0167.html">［04］pte....</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0170.html">［05］…しないと承知ができないし、治まらない。</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0170.html">［06］…の必要がある。（時には本動詞）</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0171.html">［07］當り前のwollen.</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0173.html">［08］Schwur（過去不定法と共に<u>が多し</u>）</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0178.html">［09］<u>将に云々せんとす</u>。</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0181.html">［10］外交的接続法。  wollte.</a></div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0184.html">［11］wissen wollen.</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0185.html">（12）won etwas nichts wissen wollen.<br>hören<br>問題にせぬ。</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0185.html">（13）敬語としてのwollen</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0186.html">（14）Ich will dich stolzieren! 等<br>編者注：（12）…（14）は、ノートブックの<br>巻末に挿入されていたものである<br>が、ノートブックのいずれのペー<br>ジに属するかが不明である。</a></div><div class="col-2">186</div></div>');
document.write('<div class="row"><div class="col-2">47-3B</div><div class="col-8"><a href="../047/s0191.html">lassen 助動詞 <u>lassen</u></a></div><div class="col-2">191-264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0194.html">［01］leidende Handlung.（mit sich）</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0226.html">［02］leidende Handlung mit sich （4）</a></div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0239.html">［03］四格を省いて用ひるlassen.</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0240.html">［04］es jemande<u>m</u> sehen lassen.</a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0246.html">［05］machenを用ふ可き場合（Faktitiv）  Kausativ</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0247.html">［06］許して置く、敢えて禁止せず、任せておく。<br>放置する。</a></div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0254.html">［07］Das ist ein Angebot, das sich hören läßt.（耳寄りな話）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0255.html">［08］lassenの熟語的結成（leave）</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0263.html">［09］許す。</a></div><div class="col-2">263</div></div>');
document.write('<div class="row"><div class="col-2">47-4B</div><div class="col-8"><a href="../047/s0265.html"><u>müssen</u></a></div><div class="col-2">265-335</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0267.html">［01］必然性の純なるもの。［事実的必然性］</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0274.html">［02］必然性を<ruby>喞<rt>かこ</rt></ruby>つ場合即ち <u>偶然性</u></a></div><div class="col-2">274</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0276.html">［03］常感・常識の<u>心理的</u>必然性</a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0276.html">［04］必要性（目的を基礎として）<br>云々するを以て<u>得策となす</u></a></div><div class="col-2">276</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0280.html">［05］論理的帰結及び推測・想像</a></div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0286.html">［06］…せずのは置かぬ。<br>（如何なる種類の必然たるとを問はずその<br>勢の強きもの）</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0287.html">［07］他人（等）の心理的必然性を<ruby>喞<rt>かこ</rt></ruby>つもの。<br>（困ったものだ！）［癖］</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0292.html">［08］要求・命令・嘆願・強請<br>（<u>必然性</u>の強きもの）<br>（<u>sollen</u>を強めて）</a></div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0296.html">［09］否定と共に：braucht nicht....（<u>必要</u>なし）</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0299.html">［10］…しさえすれば（好い）…<br><u>nur</u>（brauchen, düchenと同じ）</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0301.html">［11］云々するものではない。云々してはいけない。</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0303.html">［12］将に云々せんとす。</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0304.html">［13］日本語では全然不要の時に用ひる</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0307.html">［14］云々させられた。［受働的］［受意的］</a></div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0312.html">［15］特にherhalten müssen等に就て。</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0317.html">［16］müßte［餘程云々ででもなければ］［仮定的］</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0328.html">［17］<u>思わず</u>…云々する。<br><u>つい</u>…云々する。</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0329.html">［18］…云々す可きだ。（müssen,müßte,=sollte）<br>［弱きもの：］<u>sollen</u> ought.</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0329.html">［19］歴史上の必然性を描写するもの。</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0330.html">［20］als müßte ich....<br><u>云々したくなる</u>、云々しさうだ。</a></div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0333.html">［21］damit <u>muß</u> man geboren sein.<br>［subintellige; <u>um</u>....usw.］</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0333.html">［22］心理的必然性</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0334.html">［23］熟語；</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0335.html">［24］「告白、認容」と動詞につき物のmüssen</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2">47-5B</div><div class="col-8"><a href="../047/s0336.html">dürfen  助勤詞</a></div><div class="col-2">336-361</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0337.html">［01］権利あり、自由あり <u>statthaft</u>.</a></div><div class="col-2">337</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0343.html">［02］nicht dürfen  禁止</a></div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0345.html">［03］nicht dürfen<br>dürfen</a></div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0348.html">［04］allgemeine Betrachtung.</a></div><div class="col-2">348</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0349.html">［05］darf nicht = braucht nicht =<br>müssenにも此用法あり。<br>darf = braucht.</a></div><div class="col-2">349</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0352.html">［06］dürfte = könnte.</a></div><div class="col-2">352</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0355.html">［07］安心して<u>よろしい</u>、等（können）</a></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0356.html">［08］憤慨、慨嘆の際<br>（<u>dare</u>, 又は和蘭のdurven）</a></div><div class="col-2">356</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0357.html">［09］<u>wagen</u></a></div><div class="col-2">357</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0361.html">［10］darf nicht.（…する必要なし）</a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2">47-6R</div><div class="col-8"><a href="../047/s0362.html">zu+不定法の場合には独の特癖として話法助動詞<br>のzu+INFを好む。<br>［羅］Patiorのlassen的用法（放任より「せしめる」<br>ヘ）<br>lassenの述語<br>sich lassen = have<br>lassen（…任せる）<br>können 類似の表現<br>in der Lage sein<br>im stande sein （außerstande sein）</a></div><div class="col-2">362-364</div></div>');
document.write('<div class="row"><div class="col-2">47-7B</div><div class="col-8"><a href="../047/s0365.html">既に何等かの語によって話法色彩が示されている<br>際になほ且つ話法助動詞を用いる習慣</a></div><div class="col-2">365-367</div></div>');
document.write('<div class="row"><div class="col-2">47-8R</div><div class="col-8"><a href="../047/s0368.html">läßt grüßen等（事傳てのlassen）<br>müssenの意の<u>mögen</u>（つまりkönnenにもある現象）<br>sollenに多きapokope<br>sollen（wir wollen）<br>…<u>といふことにしようではないか</u>。<br>als obとmüßte</a></div><div class="col-2">368-370</div></div>');
document.write('<div class="row"><div class="col-2">47-9B</div><div class="col-8"><a href="../047/s0371.html"><u>Können</u>  助動詞</a></div><div class="col-2">371-431</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0373.html">［01］"<u>könnte</u>"</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0378.html">［02］Fähigkeit.</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0382.html">［03］Möglichkeit（wahrscheinlich）<br>云々する惧れあり 惧れなし</a></div><div class="col-2">382</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0392.html">［04］そんな事が抑々あり得ようか？ －－という意<br>（あらう事かあるまい事か。）</a></div><div class="col-2">392</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0405.html">［05］渋々認める意。（成句）Gleichgültigkeitの表現</a></div><div class="col-2">405</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0452.html">［06］事情がこれを許す。 on ne saurait<br>差支へ、支障がない。  わけにゆかぬ</a></div><div class="col-2">452</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0410.html">［07］wenn du <u>willst</u>, man <u>will</u>をつけたも同じ<br>（命令的、時には皮肉に）［müssen!］</a></div><div class="col-2">410</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0414.html">［08］Es ist möglich.（…と云ふ事が往々ある。等）</a></div><div class="col-2">414</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0421.html">［09］その過去形（動ともすれば…云々する事<br>があった）</a></div><div class="col-2">421</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0431.html">［10］nicht genug....können.</a></div><div class="col-2">431</div></div>');
document.write('<div class="row"><div class="col-2">47-10B</div><div class="col-8"><a href="../047/s0432.html">mögen  助動詞</a></div><div class="col-2">432-479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0435.html">［01］möchte（…しさうだ）=wollen, <u>können</u></a></div><div class="col-2">435</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0436.html">［02］möchte（…しはしないか）危惧<br>（könnte, dürfte）</a></div><div class="col-2">436</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0441.html">［03］mögeの代りにmöchte.云々する「やう」に。<br>（soll）</a></div><div class="col-2">441</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0444.html">［04］Should likeのmöchte（would like）</a></div><div class="col-2">444</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0449.html">［05］願望祈りのmöge, möchte.</a></div><div class="col-2">449</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0452.html">［06］…云々することを好む。（独立用法）<br>（助動詞用法）</a></div><div class="col-2">452</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0454.html">［07］認容（…云々「かも知れぬが」）</a></div><div class="col-2">454</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0455.html">［08］全然könnenと同じ。（古？）<u>dürfen</u></a></div><div class="col-2">455</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0462.html">［09］können即ちwollen.（…気になれる）</a></div><div class="col-2">462</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0463.html">［10］…云々したくなる。<u>hätte mögen</u><br>しさうだ（könnenと同用法）</a></div><div class="col-2">463</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0467.html">［11］云々するが好い。（要求的第一式Kと同じ）<br>決心 sollen</a></div><div class="col-2">467</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0470.html">［12］接続法。（想像）könnenより。「だらう」<br>「でもあらう」</a></div><div class="col-2">470</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0476.html">［13］Das mag Gott wissen!</a></div><div class="col-2">476</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../047/s0476.html">［14］［gern］leiden mögen</a></div><div class="col-2">476</div></div>');
document.write('<div class="row"><div class="col-2">47-11R</div><div class="col-8"><a href="../047/s0480.html">［mögen］mußteと同じmochte［konnteもあり］<br>We will see = Ler us see<br>will <u>heißen</u>, <u>sagen</u>, <u>bedeuten</u>. 意味する所がある。<br><br>編者注:このほか6件あり。</a></div><div class="col-2">480-482</div></div></div>');