document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">54-1B</div><div class="col-8">錯倒語法（Hypallage）</div><div class="col-2">1-37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］故意のHypallage</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］副詞の代りに形容訶（adverbal → adnominal）</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Gesprungener  Huf</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］sogenannt等。 would = be, going to = be</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］ラテンの<u>Gerundivum</u>の用法</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］Enàllage adiectivi</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］部分と総体の倒錯  die <u>innere</u> Stadt.</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2">54-2B</div><div class="col-8">移轍  形式上の錯構  主文章への移轍一般論<br>（Anakoluth）  Kontamination</div><div class="col-2">38-90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］wenn, wie</div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Keen Post so scheef, past doch \'n Deckl up.</div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］雑例。</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］受働形に似たる文にdurch, von.</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］其他の筋道に属する雑例。</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］疑問文とals...</div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］darum doch等は  A. darum <u>nicht weniger</u><br>［n\'en est pas moins］<br>B. ....<u>doch</u>....</div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］Was---? so---</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］二度目であるために、意味だけでつながるもの。<br>（意味形態の類似のために文法形態の<br>相違を無視す）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］［英］</div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］全く誤なるもの。</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］述語句の有名な問題</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］nicht....<u>sondern</u>....</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2">54-3B</div><div class="col-8">二度目には用語を変える</div><div class="col-2">91-111</div></div>');
document.write('<div class="row"><div class="col-2">54-4B</div><div class="col-8">暗喩  -zitate- （Anspielung）</div><div class="col-2">112-130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］Tatsächlich （mit Benennung.）</div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Vorbei=spielung  côtoyer.</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Phrasenfrgmente  <u>Zitate</u>.</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］Populäre Vorstellungen.</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2">54-5B</div><div class="col-8">戯作的換語  Das kommt gar nicht <u>in die tüte</u>!</div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2">54-6B</div><div class="col-8">擬音 Schallwort （Onomatopöce）</div><div class="col-2">132-182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］fl-</div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［0Z］schn=</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］schm=</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］［仏］名詞的 brouhaha f1onflon</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］schw.</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］kn= 編者注：文例無し。</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］<u>Schl</u></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］kl=</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］gr=</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］klipp = klapp型  Schnickschnack, krimskrams,<br>Bimbam, Singsang.</div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］stripp, strapp, stroll型  Piff paff <u>puff</u>!<br>（Rooly toot Tourの訳として）</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］Schurlemurle型［韻］</div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］動詞の部  zirpen, kracken</div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］使用動詞  <u>machte</u> miau! <u>ging</u> klipp klapp</div><div class="col-2">181</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］<u>R</u>--</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］Klapps. Glucks/</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2">54-7B</div><div class="col-8">弱語強想 （Liotes）</div><div class="col-2">183-217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］否定を伴ふもの。必ずしも（nicht immer）</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］弱語強想には非ずして単に否定的語法なるもの</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］特に<u>nicht zuletzt</u>について。</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］［英］は説明的に完全：last, <u>but not least</u></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］nicht <u>der geringste</u>等</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］弱い、遠慮した、時として皮肉な段階（<u>nicht</u>,<br>gerade, eben等を伴ふを特徴とす。）</div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］否定を用ひる代りに故意と他の何等かの<br>Periphraseを用ふ：</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］Diminutivと関係して、</div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2">54-8B</div><div class="col-8">Euphemismus其の他 ［猥］DAS HAUFCHEN.<br>糞、Zotenreißerei,<br>最も本格的・古典的なEuphemismus<br>Periphrase  Euphemismus等</div><div class="col-2">218-258</div></div>');
document.write('<div class="row"><div class="col-2">54-9B</div><div class="col-8">異名  Adebar, Isegrim, Nobel, Reineke.<br>Meister Petz<br>換語 Pheriphrase単句  述語としての換語<br>（述語）<br>Das Reich der aufgehenden Sonne.<br>was lange Haare trägt.  Schürzen</div><div class="col-2">259-268</div></div>');
document.write('<div class="row"><div class="col-2">54-10B</div><div class="col-8">hören und vernehmen<br>数語にて修辞効果（殊に古体）</div><div class="col-2">269-270</div></div>');
document.write('<div class="row"><div class="col-2">54-11B</div><div class="col-8">誇張語法  Die Hyperbel</div><div class="col-2">271-279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］Die Bescheidenheit selbst, etc.</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］</div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］<u>Übertreibung</u></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］齟齬、不可能、</div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］成句化したもの。</div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2">54-12B</div><div class="col-8">Launenhafte Bezeichnung 貶詞と一致す。<br>［A］der Personen  FANT, GESLELE<br>［B］der Sachen</div><div class="col-2">280-293</div></div>');
document.write('<div class="row"><div class="col-2">54-13B</div><div class="col-8">肉体諸部の装飾的状況言</div><div class="col-2">294-301</div></div>');
document.write('<div class="row"><div class="col-2">54-14B</div><div class="col-8">人のMetonymie  Pars pro toto 一般</div><div class="col-2">302-318</div></div>');
document.write('<div class="row"><div class="col-2">54-15B</div><div class="col-8">意の重点<br></div><div class="col-2">319-343</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>Sperrschrift</u>. <u>Gesperrt</u></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Sperrschriftにはせずとも、</div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Antithese</div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］約束法的語法、最後に来る仮構の部に意の重点<br>を置く。</div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］比較文と意の重点（廣汎な筋道）</div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］註釋用の考察（限定の問題）</div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］（否定の際の）定形強調  肯定も然り。</div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］<u>It</u> is not you <u>that</u> have a right to complain!</div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］一文肢（主語を含めて）強調手段は、仏と比較<br>せよ</div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］doの用法</div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］Ich sage.</div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］助動詞の繰返し</div><div class="col-2">343</div></div>');
document.write('<div class="row"><div class="col-2">54-16B</div><div class="col-8">PLE0NASMUS  もう一度くりかえして申し上げます。<br>je le répète encore une fois....</div><div class="col-2">344-348</div></div>');
document.write('<div class="row"><div class="col-2">54-17B</div><div class="col-8">Europäische Verdrehtheit</div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">54-18R</div><div class="col-8">ナンセンス的延長<br>換語［露骨を避ける為］  隠語（verhüllend）</div><div class="col-2">349-352</div></div>');
document.write('<div class="row"><div class="col-2">54-19B</div><div class="col-8">Volksetymologie</div><div class="col-2">357-358</div></div>');
document.write('<div class="row"><div class="col-2">54-20R</div><div class="col-8">Antithesis<br>Oxymoron  Er schweigt in drei Sprachen.<br>Anthropomorphismus.</div><div class="col-2">359-360</div></div>');
document.write('<div class="row"><div class="col-2">54-21B</div><div class="col-8"><u>Metapher</u>は一貫すべし</div><div class="col-2">361-364</div></div>');
document.write('<div class="row"><div class="col-2">54-22R</div><div class="col-8">Rokoko式（Periphrase）<br><u>Oxymoron</u>  glänzendes Elend.<br>METONYMIE  <u>材料を以て</u><br>MET0NYMIE  ceut voiles（vaisseaux）<br>冗談は論理に合はなくてもよい</div><div class="col-2">365-368</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><u>sprachdummheiten</u><br>［仏］十七世紀の宮廷時代<br>Vous avez pris jour pour un <u>lien si doux</u>.<br>（mariage）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">54-23B</div><div class="col-8">雅語  古語  詩語</div><div class="col-2">369-371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］Eidam,（schwingersohn.） Ohm（0heim）</div><div class="col-2">369</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］文例</div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Urständ,f. Auferstehung.<br>Urstätt,f</div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］古語を滑稽に用ふ  erschröcklich gelahrt.<br>Gottesgelahrtheit.</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］固有名詞の換語<br>1. London（für englische Regierung）<br>2.人名</div><div class="col-2">371</div></div>');
document.write('<div class="row"><div class="col-2">54-24R</div><div class="col-8">抽象名詞を人に → Metonymie<br>［仏］qui était une célébrité.</div><div class="col-2">372</div></div>');
document.write('<div class="row"><div class="col-2">54-25B</div><div class="col-8">同語の反覆使用<br>副詞反覆<br>定形反覆<br>形容詞</div><div class="col-2">373-374</div></div>');
document.write('<div class="row"><div class="col-2">54-26R</div><div class="col-8">Metonymie  <u>換語</u><br>Deutsche Langatmigkeit<br>雅語<br>誇張的比喩  Venedig diese versteinerte<br><u>Geschichte</u>.<br>既存の語形を避けて（意味の区別のため）形を<br>変へて行かうとする傾向</div><div class="col-2">375-376</div></div>');
document.write('<div class="row"><div class="col-2">54-27B</div><div class="col-8">別意</div><div class="col-2">377-378</div></div>');
document.write('<div class="row"><div class="col-2">54-28R</div><div class="col-8"><u>Hyperbel</u>.<br>具体的、象徴的語法。<br><u>Repetitio</u>,（定形の反覆は、「度々」の強調。）<br>（その他）<br><u>J.P.Richterの拙いMetapher</u>.<br>MET0NYMIE  具体物の代りに抽象名詞。（それ自身<br>の如し）<br>［型］Herbst=Ernte（Metonymie）<br>Bildersprache  拍車を掛ける。<br>折紙をつけられる  頬かぶりして世を渡る<br><u>Alliteration</u><br>Metonymie（似た物）</div><div class="col-2">379-382</div></div></div>');