document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">57-1B</div><div class="col-8"><a href="../057/s0001.html">語順  一般的事項</a></div><div class="col-2">1-129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0004.html">［01］指示代名詞と物主代名詞</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0011.html">［02］故意に行ふ主語の後置</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0019.html">［03］［Chiasmus］</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0030.html">［04］Goethe und Schiller, und Schller und Goethe.</a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0036.html">［05］関係代名詞を引くものはverbales Prädikatの<br>後に来る。</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0039.html">［06］強調的先置。（動詞以外）</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0040.html">［07］強調的先置。（動詞、過去分詞）</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0040.html">［08］強調的先置。（不定法）</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0040.html">［09］強調的先置。（定形）</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0041.html">［10］後にnichtを残す先置。  so....nicht.</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0044.html">［11］nur, allein等の中置（先置より生ずるもの）</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0046.html">［12］副詞等の外置。（一語）<br>Ich kann auch gehen <u>allein</u>.</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0071.html">［13］冠置的附加語の語順（形容詞的なるもの）<br>（<u>一語を先に、長きものを後に</u>）</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0075.html">［14］<u>Chiasmus</u>.</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0077.html">［15］es sich---sich\'s, mich\'s</a></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0079.html">［16］前綴の中置。（強音のある文肢に曳かれる）</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0080.html">［17］前綴等の中置（聯句を切るもの）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0080.html">［18］前置詞に非ざるものの外置<br>（しかも関係句を伴はざるもの）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0081.html">［19］erst, nur等とweil, wenn等の離置。</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0086.html">［20］Dativの次にAkkusativ.（名詞の場合）<br>（物主代名詞代りの三格はすべて然り。）</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0093.html">［21］倒置文の主語と定形の間に入れる短綴<br>－但し文頭倒置のみ－</a></div><div class="col-2">93</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0095.html">［22］mir ihn; mir es等。</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0103.html">［23］不定句に於けるzu+不定法の先置。<br>（willkürlich, weihevoll.）</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0104.html">［24］etwas ganz の代りに ganz etwas<br>ein gar    gar ein<br>solch einも同じ</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0108.html">［25］Das Haus hierの代りにHier das Haus</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0119.html">［26］Jetzt, nochの先置とその意味</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0120.html">［27］関係代名詞と、erst, nur等の中置。</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0124.html">［28］Ich meinesteils habe....等</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0125.html">［29］aber, nun等の貶置</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2">57-2R</div><div class="col-8"><a href="../057/s0130.html">消極的<u>には</u>云々…等  強調・假定に似た場合の語順<br>質問文に於ても、主要なるものを最後に<br>思想の自然の順に従ふ。（一般論）<br>－どちらを先に云った方がわかり易いか？－<br><br>編者注：このほか5件あり。</a></div><div class="col-2">130-132</div></div>');
document.write('<div class="row"><div class="col-2">57-3B</div><div class="col-8"><a href="../057/s0133.html">最後に来る文脈の諸形態。</a></div><div class="col-2">133-135</div></div>');
document.write('<div class="row"><div class="col-2">57-4B</div><div class="col-8"><a href="../057/s0136.html">事実関係の逆にならべる中古様式</a></div><div class="col-2">136-138</div></div>');
document.write('<div class="row"><div class="col-2">57-5B</div><div class="col-8"><a href="../057/s0139.html"><u>Das Mauscheln</u>［語りj順］</a></div><div class="col-2">139-141</div></div>');
document.write('<div class="row"><div class="col-2">57-6B</div><div class="col-8"><a href="../057/s0142.html">selbstの意味と位置</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2">57-7B</div><div class="col-8"><a href="../057/s0143.html">限者を被限者の後に（及びその例外）  一般法則</a></div><div class="col-2">143-144</div></div>');
document.write('<div class="row"><div class="col-2">57-8R</div><div class="col-8"><a href="../057/s0145.html">命令法の位置</a></div><div class="col-2">145-146</div></div>');
document.write('<div class="row"><div class="col-2">57-9B</div><div class="col-8"><a href="../057/s0147.html">［仏］語順（雑）</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2">57-10R</div><div class="col-8"><a href="../057/s0148.html"><u>en</u> vouloir venir  vouloir <u>en</u> venir<br>挿入文の位置（定形の前か後か、等の問題）<br>56 Tage <u>jährlich</u><br>［定形正置ニ於テハ文肢挿入不可能］<br>その例外のごとくみえるもの：<br>Wir <u>beide</u> sind Freunde miteinander.<br><br>編者注：このほか15件あり。</a></div><div class="col-2">148-158</div></div>');
document.write('<div class="row"><div class="col-2">57-11B</div><div class="col-8"><a href="../057/s0159.html">定形倒置・後置文における<u>主語の後置</u></a></div><div class="col-2">159-164</div></div>');
document.write('<div class="row"><div class="col-2">57-12R</div><div class="col-8"><a href="../057/s0165.html">邦語と同語順</a></div><div class="col-2">165-167</div></div>');
document.write('<div class="row"><div class="col-2">57-13B</div><div class="col-8"><a href="../057/s0168.html">zum Bahnhof <u>hinüber</u>と  <u>hinüber</u> zum Bahnhof.</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2">57-14B</div><div class="col-8"><a href="../057/s0169.html">Schwanzlastigkei（尻重）に対する自然な反逆<br>としての諸現象</a></div><div class="col-2">169-170</div></div>');
document.write('<div class="row"><div class="col-2">57-15R</div><div class="col-8"><a href="../057/s0171.html">［仏］不定法・過去分詞前に副詞其他を<br>Elle avait <u>tout</u> tenté型<br>Wo sind <u>denn</u> Sie....?  代名詞の強調法の一つ<br>nichtは打消さるベき概念の直前に！<br>代名詞主語は、強調せんとするときには後へ移す<br>物主形容詞の位置</a></div><div class="col-2">171-175</div></div>');
document.write('<div class="row"><div class="col-2">57-16B</div><div class="col-8"><a href="../057/s0176.html">［仏］sans mains mettre型  熟語</a></div><div class="col-2">176-180</div></div>');
document.write('<div class="row"><div class="col-2">57-17B</div><div class="col-8"><a href="../057/s0181.html">一文肢の先置に関して。</a></div><div class="col-2">181-184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0182.html">［01］ニ個以上の文肢の先置</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0182.html">［02］also, freilich, nun等が先置される際は、むしろ</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0182.html">間投的なるが故に、その次は正置の事もあ<br>り、又一文肢を改めて先置することもあり。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0182.html">［03］時又は空間の文肢（二文肢の如く見ゆるもの）</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0183.html">［04］定義的文肢先置</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0183.html">［05］不定「句」の先置</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../057/s0184.html">［06］佛は、あとで代名詞</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2">57-18R</div><div class="col-8"><a href="../057/s0185.html">疑問文における一文肢の強調先置<br>Und das <u>wagen Sie</u> mit solchem Zynismus<br>auszusprechen?</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2">57-19B</div><div class="col-8"><a href="../057/s0186.html"><u>Geld</u> habe ich <u>keins</u>  語順問題</a></div><div class="col-2">186-189</div></div>');
document.write('<div class="row"><div class="col-2">57-20B</div><div class="col-8"><a href="../057/s0190.html">［佛］L\'<u>idée</u> lui vint <u>de</u> ～</a></div><div class="col-2">190-193</div></div>');
document.write('<div class="row"><div class="col-2">57-21B</div><div class="col-8"><a href="../057/s0194.html">附加冠飾句の語順の問題：（外圍的）</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2">57-22B</div><div class="col-8"><a href="../057/s0195.html">万国共通の、定形の前に否定句</a></div><div class="col-2">195-196</div></div>');
document.write('<div class="row"><div class="col-2">57-23B</div><div class="col-8"><a href="../057/s0197.html">説明用：アクセン卜と関係あり</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">57-24B</div><div class="col-8"><a href="../057/s0198.html">Prolepsis</a></div><div class="col-2">198-206</div></div>');
document.write('<div class="row"><div class="col-2">57-25B</div><div class="col-8"><a href="../057/s0207.html">Dichterische Freiheiten</a></div><div class="col-2">207-209</div></div>');
document.write('<div class="row"><div class="col-2">57-26B</div><div class="col-8"><a href="../057/s0210.html">Wenn wir Lust haben und Zeit<br>（但し、しかも、そして同時に）</a></div><div class="col-2">210-216</div></div>');
document.write('<div class="row"><div class="col-2">57-27B</div><div class="col-8"><a href="../057/s0217.html">Wortstellung  nichtの位置</a></div><div class="col-2">217-249</div></div>');
document.write('<div class="row"><div class="col-2">57-28B</div><div class="col-8"><a href="../057/s0250.html">文の序列は思想の序列に従ふ。<br>（訳出もこれに従ふ可し）</a></div><div class="col-2">250-252</div></div>');
document.write('<div class="row"><div class="col-2">57-29B</div><div class="col-8"><a href="../057/s0253.html"><u>Hand</u> <u>an</u> etw. legen, etc</a></div><div class="col-2">253-259</div></div>');
document.write('<div class="row"><div class="col-2">57-30B</div><div class="col-8"><a href="../057/s0260.html">proklitischとenklitisch  語順の心理的法則</a></div><div class="col-2">260-269</div></div>');
document.write('<div class="row"><div class="col-2">57-31B</div><div class="col-8"><a href="../057/s0270.html">日本文に訳してみて、全部逆になるのが西洋語<br>の一般的傾向である。</a></div><div class="col-2">270</div></div>');
document.write('<div class="row"><div class="col-2">57-32B</div><div class="col-8"><a href="../057/s0271.html">文肢の語順</a></div><div class="col-2">271-295</div></div>');
document.write('<div class="row"><div class="col-2">57-33R</div><div class="col-8"><a href="../057/s0296.html">主語の後行と代名詞の先置<br>［仏］Une bonne arme, cette canne.<br>Seit <u>fast</u> 20 Jahrenなど、（前置詞の後に副詞）<br>［一般化すると、前置詞と名詞との間には<br>どんなものが入り得るか…？　という点に</a></div><div class="col-2">296-301</div></div></div>');