document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">56-1B</div><div class="col-8"><a href="../056/s0001.html">因由型  因由範疇  理由、原因の形態。</a></div><div class="col-2">43492</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0003.html">［01］文肢（als）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0010.html">［02］句（過去分詞叙述句）及形容詞</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0011.html">［03］句、文肢（現在分詞）</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0012.html">［04］文章（関係代名詞）</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0012.html">［05］一般に前置詞の句（bei）</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0013.html">［06］jung und fröhlig, wie Ich war.  so.... もあり</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0014.html">［07］付帯描写のmit.</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0015.html">［08］<u>ja</u></a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0015.html">［09］<u>und so</u>.</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0017.html">［10］［und］=darum</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0020.html">［11］単に並べたのみで.  ～［denn］～</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2">56-2B</div><div class="col-8"><a href="../056/s0028.html">相反的意味範疇  強い<u>und</u><br>［羅］idem, eademによる対立表現</a></div><div class="col-2">28-42</div></div>');
document.write('<div class="row"><div class="col-2">56-3B</div><div class="col-8"><a href="../056/s0043.html">Kaum....als</a></div><div class="col-2">43-66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0044.html">［01］Kaum....als....</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0048.html">［02］Kaum....so［da］....</a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0050.html">［03］Nicht so bald.... als....<br>Nicht eher....als....</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0053.html">［04］Gedacht, getan.</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0054.html">［05］Denken und handeln war eins.</a></div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0058.html">［06］....und（so）....</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0058.html">［07］Noch gar nicht lange, <u>da</u></a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0059.html">［08］Kaum daß....</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0061.html">［09］kaumを従属的接続詞に、</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0062.html">［10］遂にはkaumの代りにkein....と全然否定になる</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0064.html">［11］noch nicht...., als....</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0066.html">［12］<u>Kaum gedacht</u>, （省略文）<br>war ～</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2">56-4B</div><div class="col-8"><a href="../056/s067-.html">aliud....aliud</a></div><div class="col-2">67-83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0068.html">［01］ein anderes....ein anderes</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0076.html">［02］etwas anderes....etwas anderes</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0080.html">［03］sein以外の場合。</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0080.html">［04］anders...anders.<br>das andere....das andere....</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0081.html">［05］其他</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0083.html">［06］<u>Eines</u> und <u>ein Anderes</u>.</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2">56-5B</div><div class="col-8"><a href="../056/s0084.html">局部の<u>仮定強調</u>  或ひは制限強調  仮定と制限</a></div><div class="col-2">84-103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0085.html">［01］um....zu....「もしも」</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0086.html">［02］副詞現完（状況言）前置詞句</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0088.html">［03］形容詞（大抵は先置）副詞旬</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0084.html">［04］分詞句</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0102.html">［05］成句化した過去分詞</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0102.html">［06］<u>Ende gut</u>, alles gut.</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0102.html">［07］allein</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0103.html">［08］副文章又は不定句の先置。</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0103.html">［09］仮定強調副詞 ”…には”</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0103.html">［10］Klopfet an, <u>und</u> es wird euch geöffnet.</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2">56-6R</div><div class="col-8"><a href="../056/s0104.html">名詞のみで（述語的）（但し、因由形態をも含む）<br>構文のみで<br>形容詞の選び方で。<br>Well fed, well bred型（衣食足って栄辱を知る）<br><u>現在分詞で</u>  en ～ ant.<br><u>主語</u>（特に仮定強調）</a></div><div class="col-2">104-106</div></div>');
document.write('<div class="row"><div class="col-2">56-7B</div><div class="col-8"><a href="../056/s0107.html"><u>仮定文章</u></a></div><div class="col-2">107-130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0108.html">［01］wenn.</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0108.html">［02］Inversion</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0109.html">［03］wennの次の第二定形の正置</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0109.html">［04］副文章の正置。</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0109.html">［05］意味（Kontrast=wenn）</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0110.html">［06］Entweder....oder....の特殊構造</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0110.html">［07］nur....wenn....［nur dann....wenn］<br>erst....  erst....</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0111.html">［08］Wenig fehlte, <u>so</u>....  <u>und</u></a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0114.html">［09］oder.  …でなければ<br>（müßte）<u>Jetzt oder nie</u>.  <u>sonst</u></a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0123.html">［10］Ich brauche...., so....</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0124.html">［11］命令形、或ひはそれと類似のものを仮定部へ。<br><u>とund</u>（要求話法K）</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0130.html">［12］<u>indem</u>その他<u>手段</u>的表現</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0130.html">［13］indemが純粋に時の一致によって「…と」<br>ととなる。（soと共に）（indemが凡ゆる<br>形態に使へることの証拠と見る可し）</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2">56-8B</div><div class="col-8"><a href="../056/s0131.html"><u>Es sei denn</u>  Es <u>wäre</u> denn.</a></div><div class="col-2">131-163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0132.html">［01］普通のes sei denn［daß］</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0146.html">［02］Sie hätten ihn denn vor.</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0151.html">［03］es sei nun, daß</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0152.html">［04］es müßte denn sein, daß....</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0154.html">［05］aus genommen, außer.</a></div><div class="col-2">154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0156.html">［06］es sei denn等をohne daß....の意に用ひる<br>場合（反語）</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0156.html">［07］es <u>wäre</u> denn</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0157.html">［08］es müßte denn --- sein.</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0159.html">［09］dennゃmüssenの説明用</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0159.html">［10］wenn nicht....で</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0160.html">［11］約束話法か要求話法か？</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0160.html">［12］ne....que....で</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0161.html">［13］［英］<u>short</u> <u>of</u> ～</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0162.html">［14］［外国語］bis aufと同</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2">56-9B</div><div class="col-8"><a href="../056/s0164.html">文肢  目的文章</a></div><div class="col-2">164-173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0165.html">［01］<u>auf daß</u>（接続法）</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0166.html">［02］damit（接続法と直接法）</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0166.html">［03］sollenで</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0166.html">［04］不定法を伴ふ諸形式 ［仏］à l\'effet de ～<br>afin de ～ ［英］in order to</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0167.html">［05］関係代名詞でFinalsatzを（羅・希）</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0169.html">［06］<u>ubi</u> ea poneretそれらを置く<u>可き</u>場所</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0170.html">［07］未来分詞で目的表現</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../056/s0173.html">［08］前置詞其他</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2">56-10B</div><div class="col-8"><a href="../056/s0174.html">副文章問題一括</a></div><div class="col-2">174-196</div></div>');
document.write('<div class="row"><div class="col-2">56-11B</div><div class="col-8"><a href="../056/s0197.html">日本語にしかない文章形態<br>云々し<u>てまで</u>云々しようとは思わない。</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">56-12B</div><div class="col-8"><a href="../056/s0198.html">文法範疇の不明  On annonça le dîner servi.</a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2">56-13R</div><div class="col-8"><a href="../056/s0199.html">文章の基本問題 <u>aussage</u><br>vielleicht, daß<br><u>附加語による方法</u><br>Apposition自由一括<br><u>denn</u>の挿入文と同じ<u>und</u><br>Das macht, ----!<br>文肢：<u>色々な前置詞句</u><br>Nomen actionisの句。</a></div><div class="col-2">199-202</div></div>');
document.write('<div class="row"><div class="col-2">56-14B</div><div class="col-8"><a href="../056/s0203.html">二個のNexusの結合法の諸段階に関する参考事項</a></div><div class="col-2">203-204</div></div>');
document.write('<div class="row"><div class="col-2">56-15R</div><div class="col-8"><a href="../056/s0205.html">結果の表現（A）<br>因由：同語対立。<br>すべてを因由形態で結びつけんとする傾向から来た<br>Unsinn.</a></div><div class="col-2">205-206</div></div>');
document.write('<div class="row"><div class="col-2">56-16B</div><div class="col-8"><a href="../056/s0207.html">並立的意味範疇 <u>und zwar</u> mit, nämlich, das heißt.</a></div><div class="col-2">207-210</div></div></div>');