document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">58-1B</div><div class="col-8">主観曝露</a></div><div class="col-2">1-68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］副詞的規定（批評と結果とを区別せよ）<br>--maßen, --weise.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］批評的副詞（句）は意の重点を有するものなる<br>も、意の重点を有せざる時には、少し軽い<br>主観曝露が起る。（wie bekannt ist.）</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］「  」を指すもの。（語る者の主観）</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］［英］as....で</a></div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］結果mit, zu.</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］特：preferably  挿入句的<br>vorzugsweise? できることなら、なるべく、<br>なるたけ</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］結果（soundso <u>ausfallen</u>）</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］名詞（主語その他）</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］<u>wie</u> billig<br>wie ich anerkenne = anerkanntermaßen</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］merkwürdig <u>genug</u></a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］was....ist.... （noch schlimmer等）</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］附加詞、形容詞にもあり。</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］佛のpar---</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］in seiner Unschuld  無邪気（千万）にも</a></div><div class="col-2">65</div></div></div>');