document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">63-1B</div><div class="col-8">Nachdruckによる力点の後退</div><div class="col-2">1-4</div></div>');
document.write('<div class="row"><div class="col-2">63-2B</div><div class="col-8">母音  発音</div><div class="col-2">5-21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］<u>Rückumlaut</u>の例</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Trema.及びTremaを省くもの</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］<u>ŭとū</u></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］ōとŏ</div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］ēとĕ</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］īとĭ</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］ǖとǚ</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］āとăは同じ</div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］ö-とöv</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］［y］=ü</div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］ä-とē</div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］ävとĕ（同）</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］外来語の中間に現はれるə</div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］Stppp-uhr</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］長・中・短  マッチ・町・March<br>敵機・敵・定期<br>突起・時・陶器</div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2">63-3B</div><div class="col-8">綴りの長短  発音</div><div class="col-2">22-33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］”ER”について</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］長綴：語源的＝明瞭</div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］長綴（補足）</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］元と異る短綴</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］外来語に現れる意外な短綴</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］短綴  kolmar</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］geomĕ trieに対してgeomĕ trisch等</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］開 Auslautende Vokale</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］<u>KK</u>と<u>CK</u></div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］類似のもの</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］長と半長と短</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］=lin</div><div class="col-2">33</div></div>');
document.write('<div class="row"><div class="col-2">63-4B</div><div class="col-8">Brennessel  子音の省略</div><div class="col-2">34-36</div></div>');
document.write('<div class="row"><div class="col-2">63-5B</div><div class="col-8">子音  発音</div><div class="col-2">37-88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］s←→r  hier→hiesig</div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］ew\'geの［g］</div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］königlichのg.</div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］R  （schnurren）</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］<u>RとL</u>（weitere Beispiele）</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］g=dg</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］tlとdl, tn</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］L</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］gl=</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］wとb.</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］Stadt=tor等、子音の衝突</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］=ngの鼻音ならざるもの（例外）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］V（f.）</div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］ch←→f.</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］Kakophonie</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2">63-6R</div><div class="col-8">g=dz,z  Prestige Regie. Regisseur<br>kkで書く語  Marokko Mekka<br>lとschl<br>rとstr  等<br>wとschw<br>語尾=e（e\'）<br>多くの子音の近接<br><u>aa</u>  der Haag Aachen Saal<br>y  Nymphe  Rhythmus<br>力点後退  備考<br>直ちに、さっそく  unverw<u>eil</u>t unverz<u>ü</u>glich</div><div class="col-2">89-93</div></div>');
document.write('<div class="row"><div class="col-2">63-7B</div><div class="col-8">力点後退備考  直ちに。さっそく unvemeilt<br>ひどい！  あんまりだ！<br>Nachdruck雑考</div><div class="col-2">94-97</div></div>');
document.write('<div class="row"><div class="col-2">63-8B</div><div class="col-8">強音   発音</div><div class="col-2">98-105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］力点の如何によって意味の変る場合</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］定形を強める。肯定・否定とも</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］複数で強音の移るもの</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］基礎部に強音をおく  区別の為め</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］\'augenblicklich等の型</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］外来語に於ける強音の例外</div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］前置詞と名詞</div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］外来語その他で、前へ力点が移る一般傾向</div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］三綴の法則</div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］dreihunndert</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2">63-9R</div><div class="col-8">aa→ä Haar:hären（härenes Kleid）<br>Ma<u>ßs</u>tab等<br>分綴 <u>st</u>の例外  Diens-Tag.（火曜）</div><div class="col-2">106-108</div></div>');
document.write('<div class="row"><div class="col-2">63-10B</div><div class="col-8">濁音化の癖</div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2">63-11R</div><div class="col-8">複数で力音後退<br>METATHESE  ［仏］Fromago ［伊］formaggio.</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">63-12B</div><div class="col-8">Euphonisches"E"に関する問題<br>gerne, alleine<br>詩などの、一種のsproßvokal</div><div class="col-2">111-113</div></div>');
document.write('<div class="row"><div class="col-2">63-13R</div><div class="col-8">ForumとForum -u-に関して<br>合成語アクセント例外</div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2">63-14B</div><div class="col-8">分綴</div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2">63-15B</div><div class="col-8">子音の象徴力</div><div class="col-2">116-118</div></div>');
document.write('<div class="row"><div class="col-2">63-16B</div><div class="col-8">正字法</div><div class="col-2">119-121</div></div>');
document.write('<div class="row"><div class="col-2">63-17B</div><div class="col-8">P=B, T=G, K=G</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2">63-18B</div><div class="col-8"><u>Früh=Neuhochdeutsch</u></div><div class="col-2">123-125</div></div>');
document.write('<div class="row"><div class="col-2">63-19B</div><div class="col-8">語尾による分類  un=と力点</div><div class="col-2"> 126-132</div></div>');
document.write('<div class="row"><div class="col-2">63-20B</div><div class="col-8">un=の力点に関して</div><div class="col-2">133-145</div></div>');
document.write('<div class="row"><div class="col-2">63-21R</div><div class="col-8">日本固有名その他を移すとき、英書する癖あり：<br>yに就いて<br>日本人のくせ  su?  s?  si<br>独には=en語尾が多いといふことの例：<br>［英］<u>wel</u>-come<br>Anlautの母音（文例の部）</div><div class="col-2">146-149</div></div>');
document.write('<div class="row"><div class="col-2">63-22B</div><div class="col-8">Tutu.bobo.etc.</div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2">63-23B</div><div class="col-8">子音の神話</div><div class="col-2">151-154</div></div>');
document.write('<div class="row"><div class="col-2">63-24R</div><div class="col-8">uu, ee, ooなどの重複した同母音の件<br>［羅］，［仏］amicus, inimicus<br>流動子音前の（sch,st）の消失<br>英仏独発音の比較<br>Inversion<br>長短の基礎問題（子音の数）</div><div class="col-2">155-157</div></div>');
document.write('<div class="row"><div class="col-2">63-25B</div><div class="col-8">図表による母音の系統的説明</div><div class="col-2">158-159</div></div>');
document.write('<div class="row"><div class="col-2">63-26R</div><div class="col-8">文頭大書の例外<br>古典語（及英仏）のUmlaut扱ひ  Umlaut論<br>短綴は鋭く発音せよ！<br>e--i（Brechung）<br>［韻］女性韻の例外</div><div class="col-2">160-162</div></div>');
document.write('<div class="row"><div class="col-2">63-27B</div><div class="col-8">古形、亦は別形</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2">63-28R</div><div class="col-8">［羅］，［仏］amicus, inimicus<br>軽く発音するumの問題<br>［仏］<u>gu</u><br>［独英］<u>w</u><br>in<u>k</u>, glass インキ ガラス  母音性の問題</div><div class="col-2">164-168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">＝文章の発音＝<br>母音： Explosiv.<br>HIATUS<br>母音長短（雑）<br>（母音）eの長短<br>仏系ä<br>ä<br>仏のai=ä<br>廃れた正字法別葉  Melod<u>ei</u>（Melodie）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">63-29B</div><div class="col-8">Honomym.</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2">63-30R</div><div class="col-8"><u>ee</u>  Speer<br>aaの変音はäなること<br>ドイツ活字の相似<br>和蘭陀語（まぎらはしき語）<br>仏系のü<br>Diaeresis（Tréma）<br>［MHD］のKrasis<br>īとī ē</div><div class="col-2">170-173</div></div>');
document.write('<div class="row"><div class="col-2">63-31B</div><div class="col-8">個々の子音</div><div class="col-2">174-182</div></div>');
document.write('<div class="row"><div class="col-2">63-32R</div><div class="col-8">Hoheit Roheit<br>h←→ch</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2">63-33B</div><div class="col-8">分綴</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2">63-34R</div><div class="col-8">ローマ字通によむもの<br>韻ののために綴をかへる例</div><div class="col-2">185-187</div></div>');
document.write('<div class="row"><div class="col-2">63-35B</div><div class="col-8">Rと母音との転倒現象</div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2">63-36R</div><div class="col-8">GüldenとGolden<br>ea---［o］<br><u>uとo</u>の両方あるもの。<br>o----［ei］  英独比較<br>陰気なu<br>Kr, Gr<br>Initiale. 文章の書始めは大文字。<br>［但しその例外は：］<br>Kam<u>e</u>ra  Künstl<u>e</u>risch<br>Kam<u>er</u>ad!</div><div class="col-2">189-194</div></div>');
document.write('<div class="row"><div class="col-2">63-37B</div><div class="col-8">印刷法について 語と語の間隔</div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2">63-38R</div><div class="col-8">Ge-<u>s</u>tirnとge<u>s</u>tern<br>klarmachenとklar machen<br>kan=haben其他<br></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2">63-39B</div><div class="col-8">綴りと分綴  発音</div><div class="col-2">197-198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］=skとsmの問題</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］呟音=eの自由な省き方について</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Be<u>tt</u>uch等。</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］Fetttröpchen  stickstofffrei等</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2">63-40B</div><div class="col-8">発音一般例語</div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2">63-41R</div><div class="col-8">=sk, sphの問題 （sm）（sn）<br>長  ö<br>Homophthong（?）<br>［仏］名詞の大書<br>Bordell → brothel［Inversion］<br>i</div><div class="col-2">200-204</div></div>');
document.write('<div class="row"><div class="col-2">63-42B</div><div class="col-8">正字法  廃れた正字法  及正字法の例外</div><div class="col-2">205-212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］重複子音の省略</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］Molluske, f. 軟体動物。</div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］<u>eとä</u>z, eiとäu</div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］ öとe.</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］üとi</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］Litteratur（statt Literatur）<br>allmählig（statt=ich）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］<u>ie</u>（i）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］=<u>niß</u>（statt:nis）</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］aa  ee</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］ai（statt ei）  Haide.</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］th  Werth.  Thal.  North.  Thräne.</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［12］euとei  Reiterei（Reuterei）</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［13］<u>dt</u>  tödten  todt</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［14］Tinte - Dinte</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［15］mit Eins（stadt mit eins） in Einem fahrt.</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［16］oとu. Hopser, Hupser.</div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2">63-43B</div><div class="col-8">strikte  statt:strikt（其他=eに就て）</div><div class="col-2">213</div></div></div>');