document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">61-1B</div><div class="col-8">定形なき文の一型<br />besser--als--  je--umso--</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2">61-2B</div><div class="col-8">事務調の定形、動詞省略</div><div class="col-2">2-20</div></div>');
document.write('<div class="row"><div class="col-2">61-3B</div><div class="col-8">簡潔を尚ぶ場合、標語的其他</div><div class="col-2">21-25</div></div>');
document.write('<div class="row"><div class="col-2">61-4B</div><div class="col-8">esの省略<br />特殊な場合<br />Mir bleibt reichlich zu tun übrig.<br />［英］［仏］esの省略に相当するもの<br />（成句に限る）oú bon me semble.<br />Verweisungen<br />要求話法的命令文の場合<br /><u>Geschehe</u> denn nach deinen Willen!<br />lassenと非人称動詞<br />主語の四格esは省かす！<br />Er hörte acht Uhr schlagen.  esを省く<br /><br />編者注：このほか21件あり。</div><div class="col-2">26-51</div></div>');
document.write('<div class="row"><div class="col-2">61-5B</div><div class="col-8">判断・確認の省略文</div><div class="col-2">52-60</div></div>');
document.write('<div class="row"><div class="col-2">61-6B</div><div class="col-8">省略  Elipse</div><div class="col-2">61-90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］［Bühnen anweisung.］</div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］副文章の省畧。</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］Umganngssprache:<br />im ersten Stock → ersten Stock.</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］人代名詞主語の省略</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］愕き、憤慨、不審の際には定形を略す。</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］daher等の後の定形省略。</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］Apokope. Drohung. Daß dich!</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］haben, seinの省畧。（完了形の）</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2">61-7B</div><div class="col-8">同類項省畧</div><div class="col-2">91-153</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］</div><div class="col-2">94</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］主語の省略（普通の場合）</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］<u>wie</u>の次の定形群省畧。</div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］＝による同類項の省畧</div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］省畧せざる場合（18世紀）会話調、俗調</div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］als, の次の省文<br />wie</div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］als,  の吹の省畧（関係代名詞の前の<br />wie     指示代名詞を省く）</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］力強<云ふ時の主語省畧。（動詞定形の強調）</div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］省畧しない方が有効な時には省畧しない。</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［10］同概念の反覆（省畧せざるもの）力強し<br />=効果的反覆=</div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［11］Yes, he has等に相当する返辞。</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2">61-8R</div><div class="col-8">われも去る者、等  定形なき文の一変態<br />急がしい、schlagfertig乃至感情の切迫等で<br />説明し得る形態）すかさず申しける様<br />wennと省畧文 -及び他の従属文-</div><div class="col-2">154-155</div></div>');
document.write('<div class="row"><div class="col-2">61-9B</div><div class="col-8"><u>und das</u> aus folgendem Grunde</div><div class="col-2">156-168</div></div>');
document.write('<div class="row"><div class="col-2">61-10R</div><div class="col-8">無主語の文なる見地<br />主語の省畧（代名詞の）  Geschieht ihm recht!等<br />vice versa    und（ es） <u>umgekehrt</u> 逆も真なり。<br />und （nicht） <u>umgekehrt</u><br />was belieben zu meinen?</div><div class="col-2">169-172</div></div>');
document.write('<div class="row"><div class="col-2">61-11B</div><div class="col-8">Sitzen sie nicht da und <u>maulen</u>!</div><div class="col-2">173-175</div></div>');
document.write('<div class="row"><div class="col-2">61-12B</div><div class="col-8">代名詞目的語は省畧せず！（述語も）</div><div class="col-2">176-189</div></div>');
document.write('<div class="row"><div class="col-2">61-13B</div><div class="col-8">［MHD］</div><div class="col-2">190-192</div></div>');
document.write('<div class="row"><div class="col-2">61-14B</div><div class="col-8">Verweisungen: je ～ desto ～には省畧多し：</div><div class="col-2">193-198</div></div>');
document.write('<div class="row"><div class="col-2">61-15R</div><div class="col-8">wieと省畧文  wie lannge nicht<br />両意（または異局的）の語を基礎としたZeugma<br />（主としてWortspiel）</div><div class="col-2">199-200</div></div>');
document.write('<div class="row"><div class="col-2">61-16B</div><div class="col-8">畧語 ［英］ the flu（influenza）</div><div class="col-2">201-205</div></div>');
document.write('<div class="row"><div class="col-2">61-17B</div><div class="col-8">wennと同類項省畧  wenn auch等</div><div class="col-2">206-213</div></div>');
document.write('<div class="row"><div class="col-2">61-18B</div><div class="col-8">定形の多少無理な省畧  －主としてsein－</div><div class="col-2">214-217</div></div>');
document.write('<div class="row"><div class="col-2">61-19B</div><div class="col-8">迅速な躍如たる舒述體における省畧</div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2">61-20B</div><div class="col-8">Einfache Zeugmata</div><div class="col-2">219-234</div></div>');
document.write('<div class="row"><div class="col-2">61-21B</div><div class="col-8">等々  ainsi de suite.  und alles. und so.<br />und dergleichen.  u.s.f.,  u.s.w.<br />und ähnliches.  und anderes.</div><div class="col-2">235-237</div></div>');
document.write('<div class="row"><div class="col-2">61-22B</div><div class="col-8">ich,duの省畧について</div><div class="col-2">238-239</div></div>');
document.write('<div class="row"><div class="col-2">61-23R</div><div class="col-8">省畧という語を用いては不可ない場合<br />「省畧」と「無」とは違う！<br />冠詞類を反覆するか畧するか。<br />  仏語は冠詞類をくりかえすこと多し。<br />二度目の<u>冠詞</u>の省畧  と形容詞の格変化<br />佛に<u>申し</u>て<u>申さく</u><br />wie...., so auch等の省畧。</div><div class="col-2">240-244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">so....と省畧文  （wenn=Satz後の）<br />強い否定の場合は自然に動詞省畧<br />（否定で充分わかるから）<br /><u>Not</u> a word of apology or explanation.</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2">61-24R</div><div class="col-8">lick mi im A....!<br />obgleich  等と定形省畧<br />wenn auch<br />名詞基礎の文章  so ［geschieht es］等<br />名詞基礎の文章<br />soと省畧文<br />Abbrechung 中断・中絶<br />迅速な描出と諸種の省畧：<br />時間概念の接続詞と省畧文（分詞其の他）<br />ApostropheとApokopiert<br />hab\'とhab  apostrophierenとapokopieren<br />und das mit Recht式の基底文省畧<br />正置定形の省畧”みだし”等<br />anders....其他と定形省畧  aber vergebens<br />unumgekehrt, vice versa and conversely.</div><div class="col-2">245-253</div></div>');
document.write('<div class="row"><div class="col-2">61-25B</div><div class="col-8">［英］thatの省畧  so［that］  I think you are.</div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2">61-26B</div><div class="col-8">古典に多い同一助詞の反覆使用</div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2">61-27R</div><div class="col-8">不審・憤慨の定形省畧  Ihr noch hier?<br />Er und prahlen?<br />ihrnochhier?<br /><u>wie folgt</u>.<br />某々方面  ○○方面  Herr N.N.<br />現の證據は云々<br />［佛］chacun son goût  Geschmackssache.<br />ja, neinの省畧文<br />Wozu das Gerede?<br />会話調の定形省畧<br />istとhatなどは一を以て他を省畧する事を得ず<br />比較のalsの次に於ては指示代名詞を省畧して<br />「直－」に関係代名詞をおく<br />［英］We can perceive it if we try <u>to</u>.<br />同類項ならざるApokope的省畧。<br /><br />編者注：このほか5件あり。</div><div class="col-2">256-263</div></div>');
document.write('<div class="row"><div class="col-2">61-28B</div><div class="col-8">Apostrophierung 一般 ［佛］s\'élider（l\'e s\'élide）</div><div class="col-2">264-267</div></div></div>');