document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">62-1B</div><div class="col-8">挿入句</a></div><div class="col-2">1-38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［01］過去分詞。（簡単な例） genau betrachtet,<br>alles in allem genommen,</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［02］<u>um</u>とzu  <u>sozusagen</u><br>wenn（一概念を注釈する）</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［03］過去分詞。（成句的）</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［04］zuを伴ふ不定法の挿入句（成句的の考）<br>（……は申すに及ばず）</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［05］was----betrefft.  ［英］<u>as regards</u></a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［06］例外的にdaß---を用ふ。</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［07］undを用ひる挿入句（文）=dennと同</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［08］Repetitio（sage ich.）</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">［09］独立文の挿入。</a></div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2">62-2R</div><div class="col-8">was sag\' ich?  ...., sage ich? （que dis-je?）<br>過去分詞またはzu+不定法を省いた形：<br>offen heraus,<br>間投的挿入句<br>過去分詞を省畧したもの  gesagt多し<br>基礎文の挿入  <u>sagte er</u>など<br>wennによる挿入句<br>挿入句、挿入詞は最も緊密なる関係に立つ部分<br>を中断するを可とす：<br>was（文意を受ける）の文の省畧形<br>［英］現在分詞による法<br><u>du weißt</u>  you know<br>［仏］à n\'en pas douter<br>疑ふ余地もなくたしかに<br>alles in allem genommen<br>主語を含む述語句型。<br>dennの挿入文<br>挿入的Stoßgebete<br>Gott weiß was....   weiß Gott,<br>Ich weiß nicht welcherm<br>基礎的挿入句（sag ich）<br>Mit Verlaub（zu sagen, gesagt.）<br>Was gilt\'s?</a></div><div class="col-2">39-63</div></div></div>');