document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">69-1R</div><div class="col-8">an</div><div class="col-2">1-60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［AHD］ an=in</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［MHD］現代の<u>in</u>に当る<u>an</u></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）［MHD］のan</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）prose our hold on   手がかり、足がかり。</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>schuld</u> an ～</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）sich gewöhnen an ～</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）an die（約）</div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>bei</u>（umをも用ふ：umを見よ）</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）an die（凡そ）</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）最高級と共に用いるan <u>am</u> größten</div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）an Bord  参考  á bord</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）in the occasion</div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［英］dream on   dote in</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）to feed <u>on</u>（型：an ～ nagen型 接動のan）</div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）to live on ～    to graze on ～</div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）［英］severe drain <u>on</u> …</div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）spend on</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）on the river  仏  <u>sur</u> la Seine</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）身につけて on, upon, about</div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）ändern   an ～</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）<u>reich</u>, <u>arm</u>   an... 形容詞の規定</div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）am Rande</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）場所一般のan  am Platzt.</div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）日本語の「気」は<u>心頭</u>（こころさき）なるべし<br>怒り心頭に発す。</div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）［特］心頭（こころの<u>ほとり</u>）こころさき<br>Es wurde mir schwer ums Herz zumute.</div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）活動、参与の対象としての<u>場所</u>  何処去々「で」</div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）an der Universität.</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）空間的（基本的）</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2">69-2R</div><div class="col-8">an</div><div class="col-2">61-118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）所を指すan.  進度の<u>an</u>が混ず。</div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）城頭、指頭、街頭、…</div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）auf BSA wird <u>an</u> der Zeitkontrolle</div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）<u>am</u> Alexanderplatz</div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）時点のan  <u>An der Wende</u> des alten Jahres</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Vergegenwärtigte Räumlichkeit</div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）脅威的接近のan  jmm <u>an den Leib</u></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）am Himmel   dans le Ciel</div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）具体的  sich woran stechen.<br>抽象的  am ～ Anstoße nehmen</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）am Leben sein, bleiben.</div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）時の概念とan</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）am Tage  Die Nachteule ist blind <u>am Tege</u>.</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）<u>am Schluss</u></div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）「云々に触れて」  空間的  an der Sonne</div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）空間的  an den Fingern her zähren.</div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）～ <u>an</u> etwas <u>messen</u></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）an ---- <u>vorbei</u>.<br>vorüber</div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）an ～ entlang  an ～ vorüber</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）「空間的」の特項  <u>sich an</u> einem Gegenstand<br><u>zu</u> <u>schaffen</u> <u>machen</u><br>しきりに何かごそごそやっている。</div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）<u>Am Brunnen</u> vor dem Tore<br>机等に「着席する」。</div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）河畔  Die Wacht am Rhein.</div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）「端」に</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）空間より象徴への移行、（雑例）<br>まだinnere Spracheを存するもの。</div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）付属物のan Das Rad <u>am</u> Wagen</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）接して行はれる動作（四格と）  rühren, stoßen,<br>klopfen,</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）接して行はれる動作  an etwas ziehen.</div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）an....herum  あっちやこっちを</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）<u>woran</u> man <u>mit</u> einem ist    wissenと共に</div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2">69-3R</div><div class="col-8">an</div><div class="col-2">119-168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）alles daran setzen  ［um?］....zu....<br>全力を賭する</div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）熟語的  daran <u>müssen</u>   dran <u>sein</u></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）dran glauben müssen</div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）am übelsten dran sein  sehr übel dran sein</div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）［特］<u>daran</u>（sein Leben ～ setzen）</div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）<u>tut gut deran</u></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Es ist an dem.   Es ist doch etwes daran.</div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）Das liegt an mir.<br>Daran ist mir nicht gelegen.</div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）am Geschäft.（bei）  an der Reihe  am Zug</div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）am（+nomenaxtionis）sein<br>（in Begriff sein, etwas zu tun.）</div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）anと不定法＋sein<br><u>war</u> gerade <u>daran</u>, etw. zu tun.</div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）es geht ans ～   sich daran machen.</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Es ist <u>an der Zeit</u>（時宜を得たり）</div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Reihe（…の番）</div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）進度のan ［beiと同じ］</div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）把捉肢節のan</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）j.an ～ <u>strafen</u>  An der Beziehung</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2">69-4R</div><div class="col-8">an</div><div class="col-2">169-242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）見地のan   an....verschieden等（von）</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）主語又は四格の、身体の一部を極限す。</div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）sich <u>am Munde</u> ersparen.</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）an Zahl überlegen  sieben an der Zahl.</div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）責任の所在を指すan  was an mir liegt.</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Anteil, Schuld, Inteiesse an Ursache an</div><div class="col-2">202</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）関心・参加・参与   sich woran beteiligen.</div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Mit<u>erbe</u> sein <u>an</u> jemm.</div><div class="col-2">208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）jmdm <u>am Sprechen verhindern</u>.</div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）～ an ～ （同語重畳）</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）或物に「就て」或事を行ふ。（adnominal）</div><div class="col-2">213</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）所有の移転先、（売り<u>渡す</u>）</div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）意義集中の対象  Andacht</div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）denken<br>erinnern  an.<br>（ge=）mahnen</div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Glaube an...</div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）人……に宛てて  telefonieren</div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2">69-5R</div><div class="col-8">an</div><div class="col-2">243-319</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）anと三格（或る人に対する<u>仕打ち</u>）</div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）was....an  ce qu\'il y a <u>de</u>（vonと同じ）</div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）…に衝つて…［砕ける等］</div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）破滅の原因  an etw. leiden.</div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）irre an jemandem werden.</div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2">69-6R</div><div class="col-8">an</div><div class="col-2">320-383</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［識別の<u>手がかり</u>のan］</div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">…に則して、<u>就</u>いて  …云々を観察しつつ。<br></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）an....scheiternと同形態<br>durch云「で」  或物と「共に」（同時に）<br>他の随伴現象が生ずることを指す。</div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）結果挙述とan Den Narren an jm. fressen.</div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）拠点のan.即・基のan……を試練台にして。<br>……に縋って、頼って。［an hand des....］</div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）実験材料、試練台  ［仕打のanと拠点のanとの<br>中間］<u>mit</u></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）識別点（in）</div><div class="col-2">360</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［英］by  A bird is <u>known by</u> its note, and<br>a man by his talk.</div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>IDENTITÄTS=AN</u></div><div class="col-2">370</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）（前項と同じ）人間の場合。</div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）場合のbeiと同じan</div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）an....genug.  identitäts=Anに近し。</div><div class="col-2">380</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）etwas <u>ändern</u> <u>an</u></div><div class="col-2">383</div></div></div>');