document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">72-1R</div><div class="col-8">für</div><div class="col-2">1-74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）述語のfür  etwas für etwas halten等！</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）dankbar  für<br>erkenntlich</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Platz für ～</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［英］for+to+Infin.</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）［英］for（all）…にも拘らず</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）sorgen für ～  verantworten für ～</div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）abgestorben für等</div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［英］for = against</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）形容詞の支配するfür ....［reif für］</div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）gut für</div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）reit für</div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）形容詞のfür支配：geeignet für（目的！）</div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）こんなのはわしには向かぬ。</div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）envers  für eine Person（gegen）</div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）berühmt <u>für</u>, <u>um</u>, <u>wegen</u></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Kein Geheimnis  für Sie.</div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）für den Fall des.... －－のためには</div><div class="col-2">31</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）合成語  <u>für 0perationszwecke</u>.</div><div class="col-2">32</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）該当（－に対する）  ausdruck für -</div><div class="col-2">34</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）何年<u>度</u>の</div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）für（云々するための）（<u>zu</u>）</div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）Erklärung für ,,,,</div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）命名用のfür ～<br>Bestimmung, Aufgabe.</div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）命名用のfür  ［失・補］</div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）ein Mittel  <u>für</u> ～ （=gegen）</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）用途［adverbal］</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）用途［adnominal］</div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）基本的：純目的</div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）基本的：に対して（感謝、を主に）<br>verpflichtet  verbunden, danken, dankbar</div><div class="col-2">49</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）statt（…の代りに…どころか）</div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）für =als  として</div><div class="col-2">51</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）zu Gunsten des....</div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）sich für etwas begeistern, interessieren</div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）熟語für sich = allein</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2">72-2R</div><div class="col-8">für</div><div class="col-2">75-129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）云々<u>にとって</u>重要、等</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）für meine Augen</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）was für</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）決定、賛成のfür. 味方する、有利</div><div class="col-2">77</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）<u>Tag</u> für <u>Tag</u>    day after day</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）umと同じfür</div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）…に引換へて（價）  <u>umと同じ</u></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）…の故に（因由形無は<u>仏英</u>）<br>…に対する返報として<br>…に対する代償として</div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）その代り（その償ひとして）</div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）da fürだからまた…（auch）  だからこそまた<br>wofür seid ihr ein Arzt?</div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）何人分働く、等  幾莫「分」の（数詞と共に）</div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）何円<u>分</u>（がん！）</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）保険額の場合  für?  auf?</div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）先づ…の所は  <u>für</u> <u>immer</u><br>幾莫「分」だけ（時間的）</div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）予定のfür =auf</div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）殆ど無意味な方：  <u>für gewöhnlich</u>等</div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）for the most part</div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2">72-3R</div><div class="col-8">für</div><div class="col-2">130-170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）für tot等   für gewiß  として</div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）was....betrifft</div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）was....betrifft<br>Ich für mich［云々にかけては型多し］<br>［wegenの用法とも同じ］</div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）<u>in Bezug auf</u> was....betrifft  該当</div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）für =je, pro</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Gleiches <u>glit</u> <u>für</u> ～</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）…としてなら（als）</div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）für sein Alter.年の割には…、にしては</div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）für =als  für etwas <u>halten</u>, <u>ausgeben</u>, <u>achten</u>,<br>nehmen, <u>gelten</u>.</div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）<u>verantwortlich</u> für <u>zuständig</u> für</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）für ～ bürgen.</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）fürchten  für ～<br>zittern</div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）FürとVorとについて   特</div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Bestimmungsort.（何処其処向け）<br>en route for,   autobus für....等</div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2">72-4R</div><div class="col-8">für, gegen</div><div class="col-2">171-215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）für甲を捨てて乙を採る  tauschen vorziehen</div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）方向のgegen［=gen］</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）100 gegen eins等</div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）空間的原意</div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）対抗、敵対。</div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）に対して、に向って</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Dativ.</div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）約（近く） schier, fast, beinahe, nahezu</div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）gegen den Preis von....<br>［及び<u>交換のum</u>に近きもの］</div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）versus～対～  hie--hie</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>Mann gegen Mann</u> 副詞的成句</div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）重語</div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）頃（前）</div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）「人」…に対して（envers） <u>mit</u>, <u>zu</u> erga</div><div class="col-2">195</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）対して（<u>vor</u>に近し）  形容詞を含む</div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）…に較べては  vergleichen mit</div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）～に反して。</div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）<u>Verstoß</u> gegen-</div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）不利・反対（ant: für）<br>gegen einen stimmen, auftreten.</div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）....ist gegen ～ 述語的</div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2">72-5R</div><div class="col-8">hinter</div><div class="col-2">216-236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）hinter....drein =（her）</div><div class="col-2">216</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）hinter Schloß u.Riegel（…の中で）</div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）die Tür hinter sich zu wefen.</div><div class="col-2">Z24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）「劣る」hinter</div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）空聞より転用（象徴的）<br>Dahinter steckt etwas.</div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）町はずれ（vor）</div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）hinter--［hervor］［auf］</div><div class="col-2">226</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）その向ふ側、…の次あたりで  jenseits.</div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）遠き彼方を指す  hinter,（=über）</div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）…を前に置いて（飲物等）bei</div><div class="col-2">232</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）hinters Licht führen等</div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）hinter ～ kommen  dahinter steckt etwas.</div><div class="col-2">236</div></div></div>');