document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">73-1R</div><div class="col-8">mit</a></div><div class="col-2">1-27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）述語句と関係して <u>mit dem Hute</u> in der Hand.</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Es geschieht mit meinem Willen等</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）…で始める beginnen mit<br>schließen mit<br>enden</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）sich beschärtigen mit</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）述語句と同じもの <u>mit niedergeschlagenen</u><br><u>Augen</u> dastehen  眼を伏せて</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）云々と推定する  nimmt man <u>mit</u> 6000 ° an</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）比較する際に数規定を挙げるmit</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）普通の［…をもって］ 手段  <u>Instrumentalis</u></a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）…とともに、…と一緒に</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）純Instrumentalis</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）［仏］à=mit 手段、材料</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）mitとnomenactionis  unterと同型</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［zugleich］mit （unterも用ひる）</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）交通機関のmit  <u>auf</u> der Eisenbahn fahren mit</a></div><div class="col-2">26</div></div>');
document.write('<div class="row"><div class="col-2">73-2R</div><div class="col-8">mit</a></div><div class="col-2">28-75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）mit Erstaunen（副詞的）</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）副詞（抽象名詞と）</a></div><div class="col-2">35</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）保有描写のmit 仏のà</a></div><div class="col-2">50</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）保有描写のmit<br>ein Haus mit rotem Ziegeldach</a></div><div class="col-2">52</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）mit Zurückhaltung等  副詞的</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）mit der Geschwindigkeit  ［英］=at</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）mit ....Geschwindigkelt ［英］：at</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）身体の一部、又は帽子の一部   （無冠詞）</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2">73-3R</div><div class="col-8">mit</a></div><div class="col-2">76-124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）…をもって（物体物）</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）mit einer ～Stimme等<br>（身体の一部以外のもの）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）mit einem Satz = in</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［云々の結果を伴って］ 又は<br>［云々の感じを伴ひつつ］  主観的</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）批評、結果のmit.</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）後に残すmit［unter］  條件のmit</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）mit = indem</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）云々を伴ふ云々。 adnominal</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）形容詞のmit支配  zufrieden型<br>sich benügen mit  sich abfinden（mit?）</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）形容詞のmit支配  identisch mit,etc.</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）…と一致す  及び「比較」</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Die Verwandtschaft des----mit----</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2">73-4R</div><div class="col-8">mit</a></div><div class="col-2">125-126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）形容詞のmit支配  zufrieden, vertraut,<br>einverstanden, verbunden, verwandt.<br>familiar with ～</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）mit支配 schwanger gehen mit ～</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）形容詞とmit.（in） <u>behend</u> mit der Zunge.</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）inneres Objektに等し。  mit der....lieben.</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Par的mit（動作形式のinと同じ型）</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）mit（Namen）....heißen等<br>（mit der Vorderseite..,,）</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）mit Namen  ［namens］［geheißen］</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）nicht mit einem <u>Wort</u> geklagt</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）命令語副詞とmit.<br>目的語（Logisches Objektと関係す）</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）命令文とは限らず迅速なる描写一般</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Wohin mit verfügbarem Geld?</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）疑問詞その他etwas, nichts等とmit</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Was willst du <u>damit</u> sagen?</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）附帯描写のmit  Sie sind mit ihrer<br>Unnahbarkeit ein ungemüte Mensch.</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）with（述語句形態） 一般論</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）附帯描写のmit  因由的（beiなるべし）</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）with（仮定的）</a></div><div class="col-2">170</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）仮定文代りのwith</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）with（結果的形態）</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）with（併立的形態）</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）希語の附帯事態のέπί.</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2">73-5R</div><div class="col-8">mit</a></div><div class="col-2">175-221</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）with（相反的）</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）附帯描写のmit 相反的mit</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）（時期を指す）［同時］ mit der Zeit.</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）附帯描写のmit  仮定的mit</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）同時のmit</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）mit diesen Worten</a></div><div class="col-2">190</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）anfangen, beginnenには二つのmitあり<br>［A］<u>から</u>始める、で初める<br>［B］<u>を</u>始める。</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>anfangen mit</u></a></div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）転化終結のmit  ［英］end by<br>［仏］finir par  ［独］enden mit</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）比例の表現  と共に増す  <u>zugleich mit</u><br>je desto</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）準主語（esの際以外）</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）手段    仮定 → 結論   手段 → 達成<br>（さうしたところで…しない）<br>（さうすれば、）</a></div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）die Geschichte mit....<br>die Szene mit....</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2">73-6R</div><div class="col-8">mit</a></div><div class="col-2">222-280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）當事局部のmit  mit der Vorderseite<br>（前部を、は等）<br>［Logisches Objektの一種］</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Mit der Vorderseite分項<br>mit Haut und Haar.</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）<u>Logisches Objekt</u>.</a></div><div class="col-2">234</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）mit（sich brünsten）</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）「を提げて現れる」等<br>mit etw. dienen können</a></div><div class="col-2">278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）附帯描写のmitに近きもの（物主形容詞を伴ふ）</a></div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）前項の補追  inとの関係</a></div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2">73-7R</div><div class="col-8">mit</a></div><div class="col-2">281-328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）反撥のmit<br>言説をauffangenするmitと略同じもの。</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［目的語的］具体的動作<br>mit etwas <u>klappern</u>, u.s.w.</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）似たもの：<u>in</u> ～<br>in die Trompete blasen, schmettern.<br>in die Hände klatschen</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Es geht einem so mit einem.</a></div><div class="col-2">290</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）einen <u>mit</u> ～ aufziehen</a></div><div class="col-2">290</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）einen mit etwas <u>beschenken</u>, etc.</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）von....getragen<br>von....durchdrungen</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）材料のmit.（普通の場合）</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）inと同じ（文肢になる際）</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）相手（普通の場合）</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）相手のmit.（と、sich duellieren等）</a></div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Mitm einem Willen...</a></div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）mit Haut und Haar, mit ganzer Seele,</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）jm. <u>mit</u> Nachreden  zusetzen, etc.</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）mit Verlaub  －挿入句－</a></div><div class="col-2">328</div></div>');
document.write('<div class="row"><div class="col-2">73-8R</div><div class="col-8">nach</a></div><div class="col-2">329-354</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）後置のnach  =weise式<br>der Länge nach, （～weise）</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）時間的nach  副詞的になる</a></div><div class="col-2">329</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）allem Anscheine <u>nach</u></a></div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）…に従えば（補頂）</a></div><div class="col-2">330</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）nach neiner Meinung. à mon sens.</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）dem Namen nach</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）殆んど<u>durch</u>  <u>mittels</u></a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>nach holländischen Meistein</u>.</a></div><div class="col-2">332</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）…のままに、…の真似をして<br>（云々する、etc）</a></div><div class="col-2">333</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）nach = hinter</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）普通のnach（時間的）</a></div><div class="col-2">334</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）überと同じ</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）nach dem Rechten sehen, usw.<br>nach etwas fragen</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）普通の、方向を指す<u>nach</u>.</a></div><div class="col-2">335</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）動作の方向（aufと微差）<br>nach ～ schießen等</a></div><div class="col-2">336</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）nach ～ fragen（…を探る、知ろうとする）</a></div><div class="col-2">338</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）<u>気持の傾向</u>を指すnach</a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）nach 2 Monaten</a></div><div class="col-2">339</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）…の次には、…に次いで</a></div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）nach Hunderten（weise）</a></div><div class="col-2">342</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）最高度の表現  nach Möglichkeit   à son gré<br>できる「かぎり」</a></div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2">73-9R</div><div class="col-8">nach</a></div><div class="col-2">355-374</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）nach....<u>zu</u>［…寄りに］</a></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［je］nach</a></div><div class="col-2">355</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）見地のnach</a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）hinsichtlich des....</a></div><div class="col-2">363</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）nach Gramm geeicht</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）dem Namen nach  …で聞いて<br>（durch,.....weise）</a></div><div class="col-2">373</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）錯倒語法に関係するnachの用法</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>前置句</u>的（無冠詞を特徴とする）<br>-Nomen actionisと共に-</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）述語として：<br>Es ist nicht <u>nach meinem Geschmack</u>.</a></div><div class="col-2">374</div></div>');
document.write('<div class="row"><div class="col-2">73-10R</div><div class="col-8">neben</a></div><div class="col-2">375-380</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）neben</a></div><div class="col-2">375</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）空間的</a></div><div class="col-2">376</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）neben（と較べては）  （gegen）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）neben（と並べて）</a></div><div class="col-2">378</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）…と並んで、…以外に、…の外<br>außer.</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2">73-11R</div><div class="col-8">ohne</a></div><div class="col-2">381-402</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）ohne = es sei denn  ausser</a></div><div class="col-2">381</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）ohneと一格、二格、三格</a></div><div class="col-2">382</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）ohne（…なくては）</a></div><div class="col-2">383</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［英］but forに就いて  on1y for  約束話法</a></div><div class="col-2">386</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）…なく（基本的）</a></div><div class="col-2">388</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）ohne雑考 → <u>sonder</u> Fehl</a></div><div class="col-2">393</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）ohne語形</a></div><div class="col-2">394</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）ohne+名の述語</a></div><div class="col-2">396</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）（adnominal） Keine Regel ohne Ausnahme</a></div><div class="col-2">397</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）<u>主観</u>的  …無しに云えば<br>（sans mentir....）</a></div><div class="col-2">398</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）ohne（結果）  mitの反対</a></div><div class="col-2">399</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）…しかも…のohne</a></div><div class="col-2">400</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）ohne = nur</a></div><div class="col-2">401</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）［古］ohne außer  ohne....sonst</a></div><div class="col-2">401</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）rein, rauf, runter, usw.</a></div><div class="col-2">402</div></div></div>');