document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">74-1R</div><div class="col-8"><a href="../074/s0001.html">über<br>編者注：74-1R, 74-2R,ではüberの意味を<br>図形で説明している。</a></div><div class="col-2">1-46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0001.html">（1）über = gegenüber</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0003.html">（2）über einem Glase Wein</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0004.html">（3）「襲ひ掛る」 über（überfall）</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0006.html">（4）ein Scheck über....</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0006.html">（5）über ～ herab  über = von</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0007.html">（6）静止</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0013.html">（7）überとaufの区別</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0014.html">（8）…の上に超然として</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0015.html">（9）低迷  hovering  planer  schweben</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0016.html">（10）Die Pumpe kann das Wasser nur um 10 m über<br>den Grundwasserspieger heben.</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0017.html">（11）<u>über die Tannenspitzen</u>   hinの機能</a></div><div class="col-2">17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0020.html">（12）über die Haut等  全表面に広がる意。<br>（時間的・空間的）</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0025.html">（13）被覆  <u>tragen</u>  （着物）</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0027.html">（14）掩ふ（III. IV.）</a></div><div class="col-2">27</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0028.html">（15）<u>quer</u> über</a></div><div class="col-2">28</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0029.html">（16）運動  auch: über die Straße</a></div><div class="col-2">29</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0036.html">（17）über -- <u>hinweg</u></a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0037.html">（18）über -- <u>hinweg</u></a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0038.html">（19）静止の動詞と運動</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0040.html">（20）表面移動 ［下敷にして］</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0043.html">（21）<u>via</u> Sibirien</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2">74-2R</div><div class="col-8"><a href="../074/s0047.html">über</a></div><div class="col-2">47-124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0047.html">（1）über die Brücke  über die Straße</a></div><div class="col-2">47</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0063.html">（2）<u>皮岸に</u>、 静止、 <br>über die Staße wohnt等<br>の静止形をも含む）</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0065.html">（3）［heute］ über eine Woche</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0070.html">（4）über und über   副詞</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0071.html">（5）einmal über das andere.（umとは違ふ）</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0072.html">（6）同語重畳</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0073.html">（7）間投的（umもあり）  呪ひの間投句</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0078.html">（8）［時問的］後置句として  hindurch, durch.</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0081.html">（9）über das Wochhenende  土曜から日、月曜<u>にか<br>けて</u></a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0081.html">（10）zeitüber  時間的、空間的 （前からずっと）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0082.html">（11）瞰下的、支配的、空間的（III）<br>北海に日が沈む</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0082.html">（12）瞰下的、支配的、空間的（IV）</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0083.html">（13）über...zusammenschlagen.   特</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0090.html">（14）über den Haufen rennen</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0091.html">（15）half <u>past</u> three</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0091.html">（16）…以上、…も及ばず</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0098.html">（17）その上更に［それ以外に］  über -- hinaus.</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0103.html">（18）über（IV.） 度をすごす。「以上」に</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0108.html">（19）Deutschland über alles  「勝る」型</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0109.html">（20）「うずくまる」姿勢一般<br>über den Büchern sitzen    附</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0122.html">（21）über einer Missetat ertappen.<br>auf frischer Tat ertappen.</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0124.html">（22）…を聞いて愕く  über （=ob）と三格</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0124.html">（23）…の間に。…の後に。…のために。</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2">74-3R</div><div class="col-8"><a href="../074/s0125.html">um</a></div><div class="col-2">125-173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0125.html">（1）<u>um</u>sonst  <u>um</u> nichts</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0126.html">（2）間投句の<u>um</u></a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0126.html">（3）darum, daß目的  umとzu不定法と関係</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0127.html">（4）es sei <u>darum</u>.</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0128.html">（5）Es ist mir gar nicht <u>drum</u>.</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0128.html">（6）um（に就いて）  aboutの如し  Wissen um（von）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0129.html">（7）sich um....（be）kümmern（scheren）  grämen<br><u>um</u> etwas <u>beneiden</u></a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0131.html">（8）es handelt sich um....<br>es ist um ihn <u>geschehen</u>.</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0132.html">（9）einem ist s.u.s <u>ums Herz</u>   warm weit</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0133.html">（10）忌避、回避  einen großen Bogen machen um.<br>sich herumdrücken um ----</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0136.html">（11）周囲  rund um （round about）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0140.html">（12）um ～ her</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0140.html">（13）<u>um sich</u>（greifen, schlagen, schießen）<br>mit Geld sich werfen  打ち<u>まくる</u></a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0141.html">（14）空間的um.（<u>中心</u>として）自転<br>Die Erde dreht sich um ihre<br>eigene Achse.</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0141.html">（15）<u>um fünf Uhr</u></a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0142.html">（16）頃</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0144.html">（17）空間的：の辺［あたり］<br>um Herzもこれなり。</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0146.html">（18）「凡そ」の<u>um</u></a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0148.html">（19）was <u>drnm und dran</u> ist</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0148.html">（20）im Austausch gegen （Duden）  für（引換へて）<br>［英］<u>in exchange for</u></a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0160.html">（21）Aug um Aug 報復の<u>um</u>. Zahn um Zahn</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0160.html">（22）um ～ <u>rechten</u></a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0161.html">（23）<ruby>遉<rp>（</rp><rt>さす</rt><rp>）</rp></ruby>がは云々 …故なきに非ず  nicht umsonst,</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0163.html">（24）umsonst （gratis）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0163.html">（25）甲を捨てて乙<u>を</u>採る（見かへる）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0164.html">（26）um und um  副詞</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0164.html">（27）<u>um das dritte Wort</u></a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0165.html">（28）一日置きに  einen Tag um den andern</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0167.html">（29）eins um das andere  überと対照<br>eins <u>nach</u> dem andernは、甲、乙、丙、丁…<br>eins um den andernは、甲、乙、甲、乙、</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0169.html">（30）重要な区別  um meinet Willen</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0169.html">（31）verdienen um     特</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2">74-4R</div><div class="col-8"><a href="../074/s0174.html">unter</a></div><div class="col-2">174-208</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0174.html">（1）空間的unterと同じもの：</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0174.html">（2）［着物］の下に［隠して］</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0175.html">（3）unter seinen Händen  zwischen型</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0176.html">（4）leiden unter</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0176.html">（5）日付とunter  untem 15ten, 等</a></div><div class="col-2">176</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0177.html">（6）<u>unter</u> andern Worten = <u>in</u>, <u>mit</u></a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0177.html">（7）unter Segel,［成句的］</a></div><div class="col-2">177</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0178.html">（8）unter Anklage</a></div><div class="col-2">178</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0179.html">（9）<u>迂言動詞</u>の<u>unter</u></a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0179.html">（10）être sous clé</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0180.html">（11）空間的原意。</a></div><div class="col-2">180</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0183.html">（12）下<u>から</u>   <u>weg</u>!  <u>hervor</u>!  <u>empor</u>!</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0184.html">（13）unter Wasser  U=Boot, U=Bahn,  unter der Erde</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0187.html">（14）unter der <u>Gestalt</u>....<br>sub specie aeternernitatis.<br>「の見地から」  様相のunter<br>形態様相のunter<br>仏式unter</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0192.html">（15）……以下（抽象的）  überの反対</a></div><div class="col-2">192</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0197.html">（16）fast partitiv （<u>von</u>）</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0198.html">（17）重いもののために  ieiden unter....</a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0199.html">（18）Identitäts=unter</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0199.html">（19）unter:語源<br>希：έντόｓ<br>羅：interとinfra<br>梵：antar（副）  中に、中間に。<br>antara： 内部の、中間の、<u>他の</u>。<br>「他の」ゆえ.、<u>ander</u>（他の），<br><u>other</u>と関係す。</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0200.html">（20）unter:während<br>unterweilen （Dativ） etc.</a></div><div class="col-2">200</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0203.html">（21）<u>neben</u>, <u>außer</u>と同じ</a></div><div class="col-2">203</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0204.html">（22）unter der Schürze</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0205.html">（23）<u>unter</u> meine Augen   unter der Lupe.<br>unter seinen Händen （?）<br>（unterbreiten....）</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../074/s0206.html">（24）云々しつつ<br>（但しnomen actionisに非ざるもの）</a></div><div class="col-2">206</div></div></div>');