document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">77-1R</div><div class="col-8">ab</a></div><div class="col-2">1-122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）abe = ab</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）前綴と前置詞用法との一致</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）abgenutzt, abgemagert</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）廃～（”除”より来る）  abgerissen</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）ab = luft（名詞と）  ［排泄］</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）auf etw. absehen.   狙いのab<br />abstellen</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）落脱・剥脱のab</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）ab=geflacht</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）完了、終熄の<u>ab</u> （aus）</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）撮る （abklatsch）  abschreiben.</a></div><div class="col-2">22</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）一回遂行のab=</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）etwas abbekommen  …目に遭ふ</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Einmaligkeit （遂行のab=）   雑</a></div><div class="col-2">25</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Einmaligkeit（一番）開ロ一番<br />衆議一決、大命一下。</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Einmaligkeit  雑想。</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）abfertigen, abspeisen.（片づける）</a></div><div class="col-2">40</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）abfinden （mit）   s\'y faire:   特</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）どしどし、順々に、着々と、繰る如く<br />ab=fertigen</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）abreagieren  Abreaktion  片づける、<br />のける、去る、</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）時間（全長）<br />［ein Lied gedankenlos ab=leiern］</a></div><div class="col-2">53</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）ab=suchen等（空間の四格と共に）</a></div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）期間の四格を伴ふもの<br />seine Strafzeit absitzen.</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）seine Zeit <u>abarbeiten</u>等（時間の四格と）</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）etwas <u>abschleken</u>.  刈り”<u>取る</u>”等<br /><u>abwischen</u>.</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）sich etw. <u>ab</u>-ringen  <u>抵抗</u>を考へる</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）jemandem etwas ab=  （抵抗を考えぬ際）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）否定のab  とる。  除く。  落す。  去る。<br />却ける  Ecken und Kanten abstreifen.</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）離格DATIVとab=</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）abziehen（脱ぐ）</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）勢哀える（次第に） abklingen.  abschwelien.</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）das Haus abschreißen</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）離れる（具体的）  von ～ ab=<br />sich ab-trennen.</a></div><div class="col-2">88</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）出発  abfahren   abreisen   take off</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）Abrücken von Stalin</a></div><div class="col-2">90</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）ab=wesend  <u>不在</u>、いなくなる  geht mir <u>ab</u>.</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）止める（abrechen）  <u>中断する</u>  終熄</a></div><div class="col-2">92</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（37）止めさせる。止める  abraten</a></div><div class="col-2">95</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（38）遮断のab  ab-schneiden.  ab-schließen,</a></div><div class="col-2">96</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（39）切断（具体的）</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（40）中絶のab=</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（41）<u>einen</u> <u>abpassen</u>  ab=warten  完了形態</a></div><div class="col-2">98</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（42）［jemanden ab=weisen.］</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（43）疲らせる、いじめる、搾取する、等</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（44）くっきり、かっきり   abstehen  abgrenzen</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（45）abgeklärt, abgetötet  …し切った、<br />透みきった</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（46）abkühlen</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（47）seitwärts, weg= 外らす 外れる</a></div><div class="col-2">117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（48）去る、却く。 abziehen, abreisen, abtreten,</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（49）ab= 去る = fort   abreisen, abfliegen,</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（50）ab= <u>hinab</u>. （下へ）</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（51）取り極め：abkommen</a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（52）手離す =ab=  Abgabe.</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（53）nach außen  ab=</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（54）ablagern, 棄てる   abladen.  おろす<br />Nirderschläge.</a></div><div class="col-2">121</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（55）abmindern  abschwächen  程度の低下（悪化）</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（56）払いのける、等  abwerfen</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2">77-2R</div><div class="col-8">acht</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）acht</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2">77-3R</div><div class="col-8">after</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）aftervermieten 等</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2">77-4R</div><div class="col-8">all, an</a></div><div class="col-2">125-240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）allwaltend等  παν－</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）all = ganz ［仏］tout</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）jmm etwas anraten  （ANT. ab-raten）</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）sich anstellen</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）喰いつく  噛みつく  振るいつ</a></div><div class="col-2">127</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6〉anläuten  玄関の呼鈴をならす</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）空間的。 an （あてがって見る）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）an （着る）  ankleiden</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）［英］in=an の参考</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）anklopfen</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）an=sehen 参考</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）sich（三格と） anschließen<br />寄る、加はる、附く、gesellen</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）an= = heran  …寄る、寄せる</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Anhalt  Angriff（s）punkt<br />拠り所、手がかり、つかまえ所<br />引っかかり、足がかり、</a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）annähen</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）an-kleben  普通</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）ぶつかる  gegen etwas <u>an-kämpfen</u>, etc.</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Anfechtungen  主観的</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）be= と同じやうな<u>他働化</u>の見地から、<br />angreifen  antasten.</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）表面に向って働きかける働作  ankränkelt</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）jemanden. angehen. ansprochen.</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）jem. <u>um</u> ～ <u>an</u> = sprechen<br />gehen</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）angeboren, anhaften,  Dativと</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）［an=schlagen  ぶつかる］</a></div><div class="col-2">144</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）anzünden（点火）</a></div><div class="col-2">145</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）an-regen, an-treiben. <u>動かす</u></a></div><div class="col-2">150</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）<u>kommen</u> と共にan+ 過分詞</a></div><div class="col-2">152</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）四格と<u>an</u>=［streben］ 進む方向、近づ<目標</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）an= heran（herbei）  近づく（梵  upa）</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）heran-anziehen（attirer）  引きつける<br />引きよせる</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）拉典語のad=</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）意識へのan</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）an=dauern.  an=spannen  （しめる）</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）蓄積のan  Jahresringe  <u>ansetzen</u><br />Rost</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）増大・膨張・充溢、蓄積  自働詞<br />an=wachsen.</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）sanft  ansteigend.</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（37）<u>An</u>führer. （Ton-angeber）</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（38）etwas <u>fühlt</u> sich soundso <u>an</u>.（再帰動詞）</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（39）einen an = lächein</a></div><div class="col-2">171</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（40）sich etwas ansehen.  特</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（41）einen <u>amnuten</u>. （”良き”意味多し）</a></div><div class="col-2">185</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（42）定住のan= ansiedeln. sich ankaufen.</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（43）anreden. anfahren （anと四格）</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（44）an=ziehen （牽き始める）  <u>機みをつける</u></a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（45）開始一般  einen Päan <u>anstimmen</u>.</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（46）［とりかかる］の表現雑考</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（47）［an=wärmen］「し掛け」</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（48）anlaufen, angesäuselt..  仄かに</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（49）schön ankommen</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（50）jem. etw. anmerken.</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（51）［einem etwas <u>an</u>=merken］  <u>Dativ</u></a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（52）Anpassungsveimögen<br />［sich ein Kleid <u>an</u>=messen lassen］</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（53）適合する。ふさわしい。  angemessen sein</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（54）<u>人に向って</u>  anraten.  anempfehlen.</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（55）［sich etwas an=schaffen］  附与創出のan</a></div><div class="col-2">225</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（56）<u>an</u>maßen （sich）</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（57）an-nehmen  帯びる  ［英］take on</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（58）anpreisen 等</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（59）設定のan   ansetzen  anlegen.</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（60）<u>anheim</u></a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2">77-5R</div><div class="col-8">Anti</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Anti- と Phil0-</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2">77-6R</div><div class="col-8">auf</a></div><div class="col-2">242-316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>aufdämmern</u>  Mit geht ein Licht auf.</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）aufklatschen.  aufschlagen.</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）auf und ab.</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）「差出す」  auf=   <u>Gepäckaufgabe</u></a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）auf und ab.  abの反対としてのauf.</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）具体的auf （上）</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［英］aufと同じup</a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［英］speak up （herzu, herbei）</a></div><div class="col-2">247</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）［英］speed <u>up</u></a></div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）エスぺラン卜のek=</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）赤赤と、むかっと（反抗）</a></div><div class="col-2">254</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）覚ます。起こす。立たせる。</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［zum Tanz］<u>auf</u> spielen 等</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）eine Frage <u>auf</u>werfen</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）拾ふ、ためる  aufnotieren</a></div><div class="col-2">258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）auffallen  （眼につ<）</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）拾ふ＜発見する  aufgabeln.  auflesen.</a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）開ける、開く、融ける、解ける</a></div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）崩壊  ほどける Auf-weichung. Auf-lösung,</a></div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）負はせる、課する、載せる  （auf=erlegen.）</a></div><div class="col-2">270</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）…し付ける、［着］  aufwickeln.  aufsetzen.</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）…し付ける  （定着）  auflöten</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）かさばる、張れ「上る」  aufgedunsen.</a></div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）蓄積する（→滞る、止まる）</a></div><div class="col-2">288</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）阻止のauf  aufhalten</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）消耗・蕩盡</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）［drauf-gehen］等  auf-brauchen</a></div><div class="col-2">290</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）－止める－  aufnutzen, draufgehen.</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）反抗のauf  aufruhr.  aufbegehren.</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）［auf=leben］  aufflackern.  auflodern.</a></div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）作興、振興、修復  aufwärmen</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）aufstellen.  aufgedonnert.</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）作興、振起の純型  aufrütteln</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）活発・覚醒・利発の状態  aufgeweckt.</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）Auf=marsch  展開、陳列、列挙  aufgebot.</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）延期  aufschieben  ［英］putt pff.</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2">77-7R</div><div class="col-8">aus</a></div><div class="col-2">317-366</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）普通のaus=（出す、出る）</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）aus-klinken  はずす</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）ausspielen  効かす、切札として出す</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）否定  <u>ausbleiben</u>.</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）auslassen</a></div><div class="col-2">318</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Licht aussenden  ausstrahlen</a></div><div class="col-2">319</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）世間に（弘く） aus ～   in die Welt hinaus</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）…し出す。  ausdenken.  ausfinden.</a></div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）消す  ［英］：off, out.</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）［nach etwas］aus=</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Lativisch結果挙述と<br />seine Aufregung <u>aus</u>laufen</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）mit AKKUSATIV.  （勝ち<u>ぬく</u>）<br />eine Sache <u>ausfechten</u>, <u>auskämpen</u>,</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）auspfeifen （追い出す） einen <u>aus</u>lachen.</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）aus=trinken.</a></div><div class="col-2">326</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）「云々し歇む」 Mann <u>lernt</u> nie <u>aus</u>,</a></div><div class="col-2">327</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）sich austoben.  sich  -ieben  -klingen</a></div><div class="col-2">331</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）ausklingen 余韻嫋々   特</a></div><div class="col-2">344</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）（死ぬ）（止める）</a></div><div class="col-2">345</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）調和のaus=  aussöhnen.  ausgeglichen.</a></div><div class="col-2">349</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）…し盡す。（隈なく） ausheilen.</a></div><div class="col-2">351</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）ausf-führen. （durch-führen）</a></div><div class="col-2">357</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）<u>完成・仕上げのaus</u>.  ausbilden.  ausarbeiten.</a></div><div class="col-2">357</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）ausbeuten.  ausplündern.</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）尽すのausと同じ［aus=reden lassen］<br />おしまひまで</a></div><div class="col-2">358</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）einem etw.  aus=reden.</a></div><div class="col-2">359</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）ausdenken（考え<u>出す</u>）  <u>ausgeklügelt</u> Buch.</a></div><div class="col-2">359</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）aus= 外づす。  ausklinken,  aushängen.</a></div><div class="col-2">360</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）einen aus-dauern:<br />durch Ausdauer nachgiebig machen.</a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）aus=holen</a></div><div class="col-2">361</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）sich etwas ausleihen  借りて来る。<br />借りうける。</a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）LATIVISCHES AUS</a></div><div class="col-2">362</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（32）［英］outstanding  stand out</a></div><div class="col-2">363</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（33）<u>aus</u>brechen=ek→</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（34）単回遂行相動作の一亜種のとしてのaus-<br />straffrei ausgehenなど</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（35）auseinander=</a></div><div class="col-2">366</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（36）Außer-  außerberuflich.</a></div><div class="col-2">366</div></div></div>');