document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">80-1R</div><div class="col-8">in</a></div><div class="col-2">1-6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）in einem Buch <u>lesen</u>  <u>blättern</u></a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［steht］<u>in</u> meiner <u>Macht</u></a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Arm in Arm（重語）</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）ins Horn stoßen</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）［耽ける」のin</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Heideggers   <u>Welt</u> = in（広範疇）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［羅］in（上）</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）150 Schläge <u>in</u> der Minute</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）sich verlieben <u>in</u>, <u>in</u> ～ verliebt sein</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）in der Achtung sinken   steigen  特項</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2">80-2R</div><div class="col-8">in</a></div><div class="col-2">7-41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）jemandem im <u>Amte</u> nachfolgen,等のin</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）im Mannesstamme  特項</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）［英］<u>inquire into</u></a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）乗物に関する一般論</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）乗物とin</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）in der Hoffnung.... 後へ残すin ～</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Resignations="in"  sich fügen <u>in</u>.</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）一般論（A）  －英のwithinについて－</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）［英］into 英特有のLativa.</a></div><div class="col-2">15</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）仏  en=als   wie  parler en maître.</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）仏語のen</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）仏語のdans</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［仏］時  en été. en hiver.</a></div><div class="col-2">20</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）時、時刻を指す名詞を副詞にする時</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）－時－</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2">80-3R</div><div class="col-8">in</a></div><div class="col-2">42-84</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）一月のうちに、一日にして等</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［仏］場所    à la ville    en ville<br>dans une ville</a></div><div class="col-2">43</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）手に［持つ］</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）<u>位置</u> ［L0kativ］</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）方向のnachの代りに<u>in</u> （古）</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）in den Rat gehen =準空間表現=</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）<u>in</u> die Schule gehen    <u>zur</u>  <u>auf die</u>  特項</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）羅  abs ～   局限化的</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）im Handumdrehen. im Nu.</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）in ～ lesen.</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>in</u> Rom  地名と<u>in</u>  然しzu Amalfi.</a></div><div class="col-2">62</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）副詞句 im Grundsatz = grundsätzlich</a></div><div class="col-2">63</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）範囲・程度・分量の副詞</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）in dieser Weise</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）状能一般のin</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）jemandem in die Hand <u>sehen</u></a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）Schwalz in Schwarz</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）<u>表現形式のin</u>と<u>極限化のin</u>との中間現象</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）inにはLativa非常に多き故、一項目をなす必要<br>あり。</a></div><div class="col-2">84</div></div>');
document.write('<div class="row"><div class="col-2">80-4R</div><div class="col-8">in</a></div><div class="col-2">85-117</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>ins</u> Gespräch <u>kommen</u></a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Hand in Hand.  Auge in Auge.</a></div><div class="col-2">85</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）空間的in.</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）（bis） in---hinein. …まで</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）in die Arbeit  bei jemm.<br>in die Schule<br>in die Lehre nehmen</a></div><div class="col-2">89</div></div>');
document.write('<div class="row"><div class="col-2">80-5R</div><div class="col-8">in</a></div><div class="col-2">118-148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）in etw.  schwelgen （schwelgend etw. erzeugen）</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）in ～ schwelgen</a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）multa <u>movent</u></a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Tätigkeitsgebiet（普通例）</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）帰依信奉のin Das billische "in"</a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2">80-6R</div><div class="col-8">in</a></div><div class="col-2">149-167</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>傾向のin IV</u>.</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）im Urteil des ～<br>in der Meinug des ～ = <u>nach</u></a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）in sich selbst zusammen</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）sich in....（IV.） fügen</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Resignation <u>in</u></a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）盲目的没入・信用・放任のin<br>vertrauen ins...</a></div><div class="col-2">165</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）<ruby>沈<rt>ちん</rt>湎<rt>でん</rt></ruby>・没入・耽溺のin  －意識の局面－<br><u>sich</u> in Experiment <u>verbelßen</u>, usw.</a></div><div class="col-2">167</div></div>');
document.write('<div class="row"><div class="col-2">80-7R</div><div class="col-8">in</a></div><div class="col-2">168-197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）無限－直線運動のin  ins Ziellose （hinein）</a></div><div class="col-2">168</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）線に沿ふ運動（四格）</a></div><div class="col-2">169</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）tief ins Gesicht  in die Stirn</a></div><div class="col-2">183</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）ins Zeng legen.</a></div><div class="col-2">184</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）力強き突進的動きには一般にin</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）sich ins Schwert werfen.</a></div><div class="col-2">191</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）im Geviert, ins Geviert.<br>im Quadrat, im Durchmesser.</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>ins Kreuz</u> gebaut.  結果のinの一種</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）ins Genick  in die Stirn</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2">80-8R</div><div class="col-8">in</a></div><div class="col-2">198-230</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）遷延のin （IV.）  in den Tag hineinleben.</a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）in den Tag hineinleben.    補</a></div><div class="col-2">204</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）in ～ hinein （hineinragen）</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）insの空間的原意</a></div><div class="col-2">205</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）特に<u>眼</u>の表現について</a></div><div class="col-2">206</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）象徴的表現（hinein）  方向の一種</a></div><div class="col-2">207</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）<u>in</u> einem Zug = <u>auf</u> einen Zug</a></div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）in die Maschine diktieren.</a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）in = 羅典のsub</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）in meinem Namen等</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Modus表現のinに関する一般化原理</a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）附帯描写のin. （物主代名詞と共に）<br>状態を指す</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2">80-9R</div><div class="col-8">in</a></div><div class="col-2">231-263</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）主語の述語が副詞化し、主観的「原因」等<br>を指す。</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）in der Eile</a></div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）［羅典］</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）in der Hoffnung, dass</a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）im Geist   英  in imagination</a></div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）in der Meinung<br>Annahme<br>Ansicht  一般</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）in her opinion   殆ど<u>nach</u></a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）ある動作をする際の「状態」を指す。</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）in großer Eile.  副詞句（Art und Weise）</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2">80-10R</div><div class="col-8">in</a></div><div class="col-2">264-278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）<u>im</u> Schweiß deines Angesichts</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）in tiefem Nach denken  = tief nachdenkend</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）im ～ = mit, durch, unter   verbringen等</a></div><div class="col-2">265</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）indem....   dadurch, daß....</a></div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）拉丁語に於けるablativus</a></div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）He sat in a daze.</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Körpertei（動作の行はわれる<u>部分</u>）<br>sich in....<u>zurecht</u>-rücken</a></div><div class="col-2">268</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）<u>im</u> eigentlichen Sinne des Wortes</a></div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）im Sinne des.... adnominal<br>adverbal</a></div><div class="col-2">273</div></div>');
document.write('<div class="row"><div class="col-2">80-11R</div><div class="col-8">in</a></div><div class="col-2">279-315</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）der Sinne （向き）</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）im Schweiß,  im Lichte,  ruhen   in einer<br>を浴びて   stehen   Farbe<br>表面を指す  liegen</a></div><div class="col-2">281</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）He was <u>in a frenzy</u></a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）in［状態］ sein   ［仏］en secret. en train.</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）状態   in einer Bziehung （<u>stehen</u>）</a></div><div class="col-2">287</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）im <u>Geruch</u> der Heiligkeitの参考   挿入項</a></div><div class="col-2">297</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）im Geruch der Heiligkeit stehen.   挿入項</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）占拠領有のin  inne haben</a></div><div class="col-2">300</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）im Besitz <u>sein</u>   <u>außer</u>の反対   beiと似たり</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）im  Rechte  sein<br>Besitz</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）être dans le vrai   特</a></div><div class="col-2">308</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）<u>persister dans</u>....</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）in ［Nomen Actionis］ sein,<br>［状態名詞］  stehen,<br>sich befinden</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）in Blüte <u>stehen</u></a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2">80-12R</div><div class="col-8">in</a></div><div class="col-2">-316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）～ begriffen型（進行過程）</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>in der Betrachtung</u> stehen   動詞不定法</a></div><div class="col-2">317</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）im Begriff sein.</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［mitter］  im Gehen = gehend.</a></div><div class="col-2">340</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）N0men actionis.<br>im Steigen （begriffen）  不定法と。</a></div><div class="col-2">341</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）im Kleid.</a></div><div class="col-2">353</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）［英］he <u>bustled</u> into his frock-coat.</a></div><div class="col-2">364</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）in Gebrauch sein. （受働的）（無冠詞）</a></div><div class="col-2">365</div></div>');
document.write('<div class="row"><div class="col-2">80-13R</div><div class="col-8">in</a></div><div class="col-2">377-415</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）im kleinen</a></div><div class="col-2">377</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）…の中に「入って」…</a></div><div class="col-2">377</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">…の中へ「容れて」…</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）…を外さないように。im Takt</a></div><div class="col-2">379</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）目的語的（mitに似たり）<br>sich in....irren, etc.</a></div><div class="col-2">386</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Darin hast du recht  批評的意味を特徴とす</a></div><div class="col-2">409</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）jemn in ～ unterrichten<br>in ～ üben</a></div><div class="col-2">412</div></div>');
document.write('<div class="row"><div class="col-2">80-14R</div><div class="col-8">in</a></div><div class="col-2">416-455</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）jemanden in der Arbeit <u>stören</u>, <u>ablösen</u>.</a></div><div class="col-2">416</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）（…の課目を練習する）及び<br>（一生懸命に…云々に<u>耽ける</u>）<br>Beschäftigungs = od. Tätigkeits = gebiet.</a></div><div class="col-2">417</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）特に<u>in</u> Baumwolle <u>reisen</u>等</a></div><div class="col-2">426</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）行為の「用件」</a></div><div class="col-2">434</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）einen <u>in Audienz</u> empfangen等（無冠詞）</a></div><div class="col-2">438</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）mit einem <u>in gleichen Jahren</u> sein</a></div><div class="col-2">438</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）…の中「を」</a></div><div class="col-2">439</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）besteht in ～ </a></div><div class="col-2">440</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）…の點に［で］  besteht <u>darin</u>, dass</a></div><div class="col-2">443</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Sachliche Identität.</a></div><div class="col-2">444</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）普通の”<u>に於て</u>”</a></div><div class="col-2">446</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）語（に於て）＝場合</a></div><div class="col-2">451</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）範囲・分野   特</a></div><div class="col-2">451</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）空間的inの象徴的転用一般に就て</a></div><div class="col-2">454</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）副詞（形容詞と此に）   <u>im allgemeinen</u>, etc.</a></div><div class="col-2">455</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）「…の心の中で」を単に代名詞、名詞で<br>現はす。</a></div><div class="col-2">455</div></div>');
document.write('<div class="row"><div class="col-2">80-15R</div><div class="col-8">in</a></div><div class="col-2">456-479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）in ihm（心、人格）（an ihmとの違）</a></div><div class="col-2">456</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）樹の名と此に</a></div><div class="col-2">467</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）<u>inとauf</u>!</a></div><div class="col-2">467</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）÷及びaufgehen in～について  2 in 6 ist 3</a></div><div class="col-2">468</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Heideggerの<u>in</u>   in ～ aufgehen  参考</a></div><div class="col-2">469</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）数量規定    程度、比例、範囲、  in großen Mengen</a></div><div class="col-2">470</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）in verschieden <u>Größen</u> und <u>Farben</u></a></div><div class="col-2">475</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）im Wert von ～   in Höhe, Gewicht von ～</a></div><div class="col-2">475</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）数量規定と共に60 meters <u>in height</u></a></div><div class="col-2">477</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）in jem, verliebt</a></div><div class="col-2">479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）<u>時のin</u>  最も基礎的</a></div><div class="col-2">479</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）in zwei Wochen ［二週聞で］</a></div><div class="col-2">479</div></div></div>');