document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Category Number</div><div class="col-8">Category Title</div><div class="col-2">Index Page</div></div>');
document.write('<div class="row"><div class="col-2">81-1R</div><div class="col-8"><a href="../081/s0001.html">in</a></div><div class="col-2">1-76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0001.html">（1）［エ］は前置詞を副詞で造る：<br>dank\' al   のおかげで</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0001.html">（2）定冠詞の問題   形谷詞を伴うもの。</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0002.html">（3）動作形式のinと前置詞との中間現象</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0002.html">（4）Verweisungen</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0003.html">（5）前置詞句。<br>mit （gegen=Schiller）<br>im Gegensetz zu...   von （Goethe）<br>zu... <br>in eins mit...（Heidgg）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0070.html">（6）in Richtung  "Mitteleulopa"<br>凍結形を伴うもの    特</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0071.html">（7）in an effort to ～ ”云々せんとして”  例外</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0071.html">（8）inの代りにmit</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0072.html">（9）in以外の前置詞句    at variance with</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0072.html">（10）en recherche de</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0073.html">（11）en matière de = in Sachen des</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0074.html">（12）in seiner Eigenschaft <u>als</u>, ～</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0074.html">（13）［仏］à l\'insu de</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0075.html">（14）［仏］à l\'abri de</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0075.html">（15）in case of    侍</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0076.html">（16）à l\'instar de = à l\'exemple de...<br>à la maniere de</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../081/s0076.html">（17）完全温存定冠詞  auf der Suche nach...<br>迂言前置詞でないもの：</a></div><div class="col-2">76</div></div></div>');
