document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">81-1R</div><div class="col-8">in</div><div class="col-2">1-76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）［エ］は前置詞を副詞で造る：<br>dank\' al   のおかげで</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）定冠詞の問題   形谷詞を伴うもの。</div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）動作形式のinと前置詞との中間現象</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Verweisungen</div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）前置詞句。<br>mit （gegen=Schiller）<br>im Gegensetz zu...   von （Goethe）<br>zu... <br>in eins mit...（Heidgg）</div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）in Richtung  "Mitteleulopa"<br>凍結形を伴うもの    特</div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）in an effort to ～ ”云々せんとして”  例外</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）inの代りにmit</div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）in以外の前置詞句    at variance with</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）en recherche de</div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）en matière de = in Sachen des</div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）in seiner Eigenschaft <u>als</u>, ～</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［仏］à l\'insu de</div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）［仏］à l\'abri de</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）in case of    侍</div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）à l\'instar de = à l\'exemple de...<br>à la maniere de</div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）完全温存定冠詞  auf der Suche nach...<br>迂言前置詞でないもの：</div><div class="col-2">76</div></div></div>');