document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">85-1R</div><div class="col-8"></a></div><div class="col-2">1-37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=ienの地名  Sardinien.</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）知名の地名  Grönland.</a></div><div class="col-2">2</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）三綴の法則  Mephistophiles.</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）<u>Etymologische Zwillinge</u>.</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）英独同語幹の語［1］  to warn （warnen）</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）operate.  tolerate</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）文例（-ate）</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［英］äffende Vokabeln.</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）arrival. （1）</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）arrival型（2）</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Quickie.</a></div><div class="col-2">9</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）dot, spot, blot.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［P］AnlautはPfに  Auslaut, Inlautはfpz.</a></div><div class="col-2">11</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）finish.  anguish （名詞）</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）refug<u>ee</u>.（1）</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）refug<u>ee</u>.（2）</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）［英］gang<u>ster</u>.</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Ungetüm-e.  Aschermittwochは如何</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2">85-2R</div><div class="col-8"></a></div><div class="col-2">38-73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Mannerはman+irなるべし。</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［AHD］<u>barn</u>,等。</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Häuptenはpl.に非ず！</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）Dentalbildung</a></div><div class="col-2">45</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）EN= Dental=Bildung</a></div><div class="col-2">46</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）mit Vergunst.  Inbrunnst.  Nachbar<u>schaft</u></a></div><div class="col-2">48</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）女性の複数 =en式</a></div><div class="col-2">54</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Nachricht.  Bahn,  Bahnen.</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）地名の =en  München.</a></div><div class="col-2">57</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）=ienに終る地名  Indonesien.</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=en［=er］等の変音の問題  Lager → Läger （?）</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）［中性］N式das Eis<u>en</u>.n</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Stipendium  奨学金、研究費  Colosseum.</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Leprosarium等</a></div><div class="col-2">64</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）特にIndivid<u>uu</u>m.  Vak<u>uu</u>m.  Resid<u>uu</u>m.等</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=itätの代りに=um.</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）特に=eum, =äum</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Diektrikum → =ka  複数形</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）器具のoir  encensoir.</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）場所=oir［e］ ［仏］fumoir.</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）Reperto<u>ire</u>, n.</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）</a></div><div class="col-2">71</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）Kuriale. n.  ～ ien. （公文書形式）</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）Kreditiv. n.  Imperativ. m.</a></div><div class="col-2">73</div></div>');
document.write('<div class="row"><div class="col-2">85-3R</div><div class="col-8"></a></div><div class="col-2">74-107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）ungefüge.  ungestalt.  ungestüm</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Die Perspektive.</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Die Zentrale等  （形容詞の名詞化と区別<br>すべきもの）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2">_</div><div class="col-8">（4）=iv［e］ （m.f.n.）</a></div><div class="col-2">75</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Skotom</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）例外  scheinbar!</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）=mwnt, n. ［m］</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）DAS M0D<u>ELL</u> 型</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）Das Zermoniell型（-ell語尾のままを名詞に）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）tum語尾の性に関する考察  特項</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）具体人の集合を指す=tum（集約名詞的）</a></div><div class="col-2">81</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=tum 語尾の性  男性：Irritum. m.<br>Reichtum. m.</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）Zauberwesen: Zaub<u>erei</u><br>Pennalismus. 古参生の新参いじめ<br>official<u>dom</u>.  Beamtent<u>um</u>.  史”道”振粛</a></div><div class="col-2">83</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）［英］dom  pagandom （heidentum）  freedom.</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［仏］の=ité考察</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Fürstentum  領</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）Das freundliche <u>Wesen</u>等</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Lebewesen.  具体的： =wesen   un être vivant</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）<u>英系=ingは中性</u></a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Das Mobili<u>ar</u> （中性の=ar）</a></div><div class="col-2">106</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）Parla<u>ment</u></a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2">85-4R</div><div class="col-8"></a></div><div class="col-2">108-140</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=ienの複数  Alikali, n. pl.  Alkalien.</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=al  =ar  =är</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Das Pektorale { =ien<br>=ia</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）=gen.</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）中性  =én  Phosgen</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）化学 Nomenklatur=an,  =en等</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Volu<u>men</u>型</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=yl  基（Gruppe）  Phenyl  （CH<sub>5</sub>）</a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）石名ハ例外： Turmalin 電気石、m.<br>［男性］</a></div><div class="col-2">114</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）=in  独はMargarin, n. Margarine, f.<br>（人造バター）</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=in</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=in  glyceri<u>n</u></a></div><div class="col-2">120</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=in</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）露人名語尾in</a></div><div class="col-2">122</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）KREFAVIN</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）BIOCITIN</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）Purginol</a></div><div class="col-2">125</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Cortisone</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Plastls</a></div><div class="col-2">130</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）宝石名参考 <u>黒玉</u>（石炭の如く、燃える）<br>仏 jais.  希 Gagates.  独  Gagat.</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）鉱石、石の-it, m.其の他<br>des Magnetites（-en）</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）=it Mineralienとしては男性</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）石のlith, m.</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=at, n. 受働的  das Filtrat.</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）=（塩）</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）Risiko → Risiken  ［Pl. =en］</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）Harmin系の=on.</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）=on  ［Pl =<u>en</u>］</a></div><div class="col-2">138</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）Ion → Ionen</a></div><div class="col-2">140</div></div>');
document.write('<div class="row"><div class="col-2">85-5R</div><div class="col-8"></a></div><div class="col-2">141-174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Ion → Ionen［=enの附加、アクセントの推移］</a></div><div class="col-2">141</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=icht, （n.）</a></div><div class="col-2">142</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）=nis</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［英］=ness</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Gebäude型</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）Verbal-substantive  Ge--e</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Pferdegetrappel型→</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）絆括のGe=  Gebrüder.</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）総（綜）のvon［=Ge=  或は<u>Gesamt</u>=</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）=sal</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=sal -sal</a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=sel（片）</a></div><div class="col-2">166</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）［英］flotsam.</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Kabi<u>nett</u>型</a></div><div class="col-2">172</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Mode<u>ll</u>.</a></div><div class="col-2">173</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Eidam</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）女性の複数は原則として=enであるということに</a></div><div class="col-2">174</div></div>');
document.write('<div class="row"><div class="col-2">85-6R</div><div class="col-8"></a></div><div class="col-2">175-210</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）普通のE</a></div><div class="col-2">175</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）原語=aと独系=eとのeinherlaufenせるもの：</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）形容詞から=E</a></div><div class="col-2">179</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）=E Nomen actionis</a></div><div class="col-2">182</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Lache, Mache ［Nomen actionis］</a></div><div class="col-2">187</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）［仏］Nomen actionis  en=ée<br>allée et venue</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Freude.</a></div><div class="col-2">188</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=de, =te  growth.  youth.</a></div><div class="col-2">189</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=end, f.</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）女を意味する［=e］</a></div><div class="col-2">193</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Die Kooperati<u>ve</u><br>die Antike und die Moderne.</a></div><div class="col-2">194</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）［英］the molal<u>e</u></a></div><div class="col-2">196</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）仏系英語  morale  モラール</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Materie型</a></div><div class="col-2">197</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Deteßteien.</a></div><div class="col-2">198</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=ei  Walachei Wallachei</a></div><div class="col-2">199</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=ei  Klerisei（集約名詞） = der Kleurus.</a></div><div class="col-2">201</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=ei  Auskunftei等</a></div><div class="col-2">209</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）=ei  ［仏］=age （nomen actionis）</a></div><div class="col-2">210</div></div>');
document.write('<div class="row"><div class="col-2">85-7R</div><div class="col-8">=ei.  =erie.  =keit.  =heit.  =ung.</a></div><div class="col-2">211-229</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）集約名詞の =ei, =rei,  Klerisel=der Klerus</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）［英］dentistry</a></div><div class="col-2">211</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）［仏］tracasserie =tracas型</a></div><div class="col-2">212</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）=ei  （女性以外の）</a></div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）=ei  ［仏］=erie</a></div><div class="col-2">214</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）製造所、店舗の=erei</a></div><div class="col-2">215</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）=ei  Försterei  館（やかた）</a></div><div class="col-2">217</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=ei  Sucrerie（Zucker<u>werk</u>）</a></div><div class="col-2">218</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）Melo<u>dei</u> statt Melodie</a></div><div class="col-2">219</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Fasan<u>erie</u></a></div><div class="col-2">220</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=erie  Donquichott<u>erie</u>.</a></div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=keit, =heitに関する参考事項</a></div><div class="col-2">221</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=keit,  =heit（具体的）</a></div><div class="col-2">222</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Genau<u>ig</u>keit  Geschwind<u>ig</u>keit等のつなぎの<br><u>ig</u>と<u>keit</u></a></div><div class="col-2">223</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［英］=hood</a></div><div class="col-2">224</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=ung（女性以外）</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=ung（空間的）  Vertiefung  凹み</a></div><div class="col-2">227</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=ung型<u>動作名詞</u></a></div><div class="col-2">228</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）=ung考</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）=ung語尾の具体名詞</a></div><div class="col-2">229</div></div>');
document.write('<div class="row"><div class="col-2">85-8R</div><div class="col-8"></a></div><div class="col-2">230-258</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）外来語のnomen actionis:  Kontrolle</a></div><div class="col-2">230</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=ik</a></div><div class="col-2">231</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）=ik  Peristaltik  蠕動</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［英］mechn<u>ics</u>  等</a></div><div class="col-2">233</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）=ikと其の性</a></div><div class="col-2">235</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=graphie</a></div><div class="col-2">236</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）=ie  一般</a></div><div class="col-2">237</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=typie  Zyanotypie.</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=phobie</a></div><div class="col-2">238</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）=pathie</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=nomie</a></div><div class="col-2">239</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=metrie</a></div><div class="col-2">240</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=logie</a></div><div class="col-2">241</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）=manie</a></div><div class="col-2">242</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）=skopie</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=tomie</a></div><div class="col-2">243</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=thek（e）</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）～ ie</a></div><div class="col-2">244</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1~9）Melodei = Melodie</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Diarrhöe</a></div><div class="col-2">245</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=ade   Robinson-Krusoen<u>ade</u></a></div><div class="col-2">246</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）-ade  =erei  ［仏］</a></div><div class="col-2">248</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）spezies（羅・第五変化）（単複同形）</a></div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）ies  及び  =es</a></div><div class="col-2">249</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=itis  病名のitis, f. pl.  <u>～ iden</u></a></div><div class="col-2">250</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）=itis</a></div><div class="col-2">252</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）病名等の=ose  =ese   Atlantis.</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）病名等の=ose  =ese  =yse  =ase  Neurose.</a></div><div class="col-2">253</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）=oseの病名</a></div><div class="col-2">255</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（30）=ose<u>物質名</u>（Monosaccharide） 単糖類</a></div><div class="col-2">256</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（31）LuziferinとLuziferase</a></div><div class="col-2">257</div></div>');
document.write('<div class="row"><div class="col-2">85-9R</div><div class="col-8"></a></div><div class="col-2">259-278</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Zym<u>ase</u> 等の =ase</a></div><div class="col-2">259</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=isと=e</a></div><div class="col-2">260</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Firm<u>a</u> → pl. Firm<u>en</u>.</a></div><div class="col-2">261</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）女性語尾=a</a></div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）=tion.</a></div><div class="col-2">262</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=tät, f.</a></div><div class="col-2">264</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Fakturistin. Drogistin.</a></div><div class="col-2">266</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=in.  女性の=in.</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=tion</a></div><div class="col-2">267</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Spion=age, f.</a></div><div class="col-2">269</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Debatte</a></div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=ationとierungに就いて</a></div><div class="col-2">271</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=<u>schaft</u></a></div><div class="col-2">272</div></div>');
document.write('<div class="row"><div class="col-2">85-10R</div><div class="col-8"></a></div><div class="col-2">279-305</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）具体的意味の=schaft</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Leidenschaft其他範疇を有せざる歴史的単語</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）=schaft（歴史的現象）</a></div><div class="col-2">279</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［英］-ship</a></div><div class="col-2">280</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Kategorie.</a></div><div class="col-2">282</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=ade</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）=id, n. ［～化物］</a></div><div class="col-2">283</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）=oid  =id</a></div><div class="col-2">284</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）arachnoiden  蜘蛛類</a></div><div class="col-2">286</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）=oid  =id</a></div><div class="col-2">289</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=ode,  =ide</a></div><div class="col-2">291</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=enz,  =anz</a></div><div class="col-2">292</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）特にinchoativischな=SCENZ［werden型］</a></div><div class="col-2">293</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Materie型女性名詞  Studie</a></div><div class="col-2">294</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Mut  Anmut, f.</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）Futurは例外</a></div><div class="col-2">296</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=tur  =schaft,  =at</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=tur （= =lichkeit）  Lineatur.</a></div><div class="col-2">298</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）=tur  Lineatur.</a></div><div class="col-2">299</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）=tur  =sur  Naßrasur</a></div><div class="col-2">301</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=kultur</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）-gen  -geneität</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）der Komedo → Komedonen 複数形の問題</a></div><div class="col-2">302</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）=a → =en  =o → =en</a></div><div class="col-2">303</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）Kapital  Kapitäl,  Stuck   Stück</a></div><div class="col-2">304</div></div>');
document.write('<div class="row"><div class="col-2">85-11R</div><div class="col-8"></a></div><div class="col-2">306-325</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Mai  Maat  Meer  Moor</a></div><div class="col-2">306</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）die <u>Bö</u>  Me<u>nü</u>  Aperçü</a></div><div class="col-2">307</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）商語は伊系多し</a></div><div class="col-2">309</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）開綴のe  chile</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）羅典形=oとギリシャ形=onとの現代語における<br>反映</a></div><div class="col-2">310</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）三綴りの法則  antepaenuttimaに1アクセン卜</a></div><div class="col-2">311</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）Idyll,  Idylle型</a></div><div class="col-2">312</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）der Zeh, die Zehe型</a></div><div class="col-2">313</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）der Zeh, とdie Zehe型</a></div><div class="col-2">314</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）der Floß  die Flöße  いかだ</a></div><div class="col-2">316</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Idyll, Idylle型</a></div><div class="col-2">320</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）複数形なきStoffnamen</a></div><div class="col-2">321</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）diebisch  vatemörderisch</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）=mutと其の性</a></div><div class="col-2">322</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）Matrix → Matrizes</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）der Gefallenとdas Gefallen</a></div><div class="col-2">323</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）［仏］何等かの理由で=sを語尾とする名詞</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Singularia tantum</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）［英独仏］……の語尾</a></div><div class="col-2">324</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）imitateur-trice</a></div><div class="col-2">325</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）Hölder-lin（1）  発音</a></div><div class="col-2">325</div></div></div>');