document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">袋番号</div><div class="col-8">タイトル</div><div class="col-2">ページ</div></div>');
document.write('<div class="row"><div class="col-2">88-11R</div><div class="col-8"><a href="../088/s0001.html"></a></div><div class="col-2">1-12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0001.html">（1）Ausprägung   sich herausbilden<br>（Vollentwicklung）</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0002.html">（2）文法形態</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0002.html">（3）（1）定形はそれ自体が文章である。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0003.html">（4）（2）「動詞」と「定形」とはちがう。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0004.html">（5）（3）機構要求が動詞の本質なること。</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0005.html">（6）構出と構入</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0006.html">（7）文法形態は意味関係に関係なし</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0007.html">（8）動詞に構入される文肢の図示法（?）</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0008.html">（9）支配</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0009.html">（10）規定とは</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0009.html">（11）冠詞といふ現象</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0010.html">（12）文法形態と意味形態との齟齬</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0011.html">（13）-ADNOMINAL- Apposition.</a></div><div class="col-2"></div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8"><a href="../088/s0012.html">（14）Adnominal規定の分類</a></div><div class="col-2"></div></div></div>');
