document.write('<div class="container">');
document.write('<div class="row"><div class="col-2">Number</div><div class="col-8">Category Title</div><div class="col-2">Page</div></div>');
document.write('<div class="row"><div class="col-2">86-1R</div><div class="col-8"></a></div><div class="col-2">1-17</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）男性で=nの複数（必ずしも弱に非ず）</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）仏英=ard</a></div><div class="col-2">1</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）-ard</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）［仏］ouragan=Orkan</a></div><div class="col-2">3</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）［仏］樹名=ier</a></div><div class="col-2">4</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=er式NOMEN AGENTIS</a></div><div class="col-2">5</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）二綴り語の=e式複数</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）純独乙系語の=at</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）外来語の複数語尾=enに関する参考事項</a></div><div class="col-2">6</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Satz-Sätze</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）eごの複数に関するMütter式</a></div><div class="col-2">7</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）=E=  同音E式</a></div><div class="col-2">8</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）例外Charakter =e</a></div><div class="col-2">10</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Aal - Aale と Saal - Säle</a></div><div class="col-2">12</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）=e式複数参考</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）E式の編音、不変音に関する参考。</a></div><div class="col-2">13</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=E  Plätze.</a></div><div class="col-2">14</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）Kranz,  Kränze</a></div><div class="col-2">16</div></div>');
document.write('<div class="row"><div class="col-2">86-2R</div><div class="col-8"></a></div><div class="col-2">18-37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）外来語の男性は困雜！  der Ballast等</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）<u>EN式男性名詞</u>に関す参考文例</a></div><div class="col-2">18</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）男と中の=en</a></div><div class="col-2">19</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）男性弱変化</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）-ist.  -ant.  -loge 石の=it等は強弱不明</a></div><div class="col-2">21</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=eseの弱変化男性  Chinese.</a></div><div class="col-2">23</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）弱変化男性</a></div><div class="col-2">24</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）男性弱変化名詞  分類し難きものの例 </a></div><div class="col-2">30</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）男性弱変化名詞（外来語の）=eに就いて</a></div><div class="col-2">36</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）［仏］=logueなどと=log<u>iste</u>など</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）能働者と受働者の表現</a></div><div class="col-2">37</div></div>');
document.write('<div class="row"><div class="col-2">86-3R</div><div class="col-8"></a></div><div class="col-2">38-78</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）Gevatter</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）Konsul.  pl. =Konsul-n型</a></div><div class="col-2">38</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）der Ras<u>en</u> m.</a></div><div class="col-2">39</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）der Rasen等の参考</a></div><div class="col-2">41</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）der Gefallen対das Gegallen</a></div><div class="col-2">42</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）語幹男性名詞（動作名詞）</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）</a></div><div class="col-2">44</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）語幹男性名詞</a></div><div class="col-2">55</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）語幹動詞［<u>男</u>］</a></div><div class="col-2">56</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）男性語幹名詞は～e式複数形</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）語幹男性名詞（擬音詞型）</a></div><div class="col-2">58</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）der Text</a></div><div class="col-2">59</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）拉系語の平行現象</a></div><div class="col-2">60</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）語幹男性例外（=r多し）</a></div><div class="col-2">61</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）［仏］</a></div><div class="col-2">65</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）［仏］ =is</a></div><div class="col-2">66</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）［男］el, =erのNomen actionis</a></div><div class="col-2">67</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=mと性</a></div><div class="col-2">68</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）=CKと性</a></div><div class="col-2">69</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）=ianer （=ide）</a></div><div class="col-2">70</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=er  nomen agentis</a></div><div class="col-2">72</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）［G0T］</a></div><div class="col-2">74</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）</a></div><div class="col-2">76</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）=or</a></div><div class="col-2">78</div></div>');
document.write('<div class="row"><div class="col-2">86-4R</div><div class="col-8"></a></div><div class="col-2">79-115</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=erの俗間用法</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=er  酒名</a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）Sommefrisch<u>ler</u></a></div><div class="col-2">79</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）</a></div><div class="col-2">80</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）=lingの語尾</a></div><div class="col-2">82</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）=ing</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）-em, am</a></div><div class="col-2">86</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）-ich  -ch</a></div><div class="col-2">87</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=ig =ich</a></div><div class="col-2">91</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）Grob<u>ian</u>.  Dummr<u>ian</u> 等</a></div><div class="col-2">97</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=bold.</a></div><div class="col-2">99</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）-s, m.</a></div><div class="col-2">100</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=0R.</a></div><div class="col-2">101</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）=iker</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）=ikus.</a></div><div class="col-2">102</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）=iker（病者名もあり）</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）累系の=or</a></div><div class="col-2">103</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）=or  =eur</a></div><div class="col-2">104</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）</a></div><div class="col-2">105</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）der Motoren  Motore</a></div><div class="col-2">107</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=eur</a></div><div class="col-2">108</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）=orの語尾</a></div><div class="col-2">109</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）西班牙系=dor</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）［英］=ite, =an</a></div><div class="col-2">110</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=ist</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）=ast</a></div><div class="col-2">111</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）仏式  <u>Atelier</u>型</a></div><div class="col-2">112</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）=<u>ismus</u></a></div><div class="col-2">113</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（29）=Ismus.</a></div><div class="col-2">115</div></div>');
document.write('<div class="row"><div class="col-2">86-5R</div><div class="col-8"></a></div><div class="col-2">116-154</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）病名等の=ismus.（≒manie）</a></div><div class="col-2">116</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）MECHANISMUS等</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）=smusの複数形</a></div><div class="col-2">118</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）=<u>us</u></a></div><div class="col-2">119</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Kasus.  Casus</a></div><div class="col-2">123</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）拉丁第四変化形： 具体象名詞  =us</a></div><div class="col-2">124</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）ululatus.</a></div><div class="col-2">126</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）［仏］rut, m.</a></div><div class="col-2">128</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）us 語例</a></div><div class="col-2">129</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）<u>Iltis</u>. <u>Ethos</u>, Logos</a></div><div class="col-2">131</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）Autobus, ～ sse</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1Z）0tto→ Ottonen→</a></div><div class="col-2">132</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）=en［外来語］ （複数形）</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（14）Primas, m.</a></div><div class="col-2">133</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（15）中性の=<u>at</u></a></div><div class="col-2">134</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（16）弱変化男性の歴史的関係</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（17）=ist（と他型との関係）</a></div><div class="col-2">135</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（18）男性の=at（弱）</a></div><div class="col-2">136</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（19）Advokat  （Prädikat）</a></div><div class="col-2">137</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（20）Schogun<u>at</u></a></div><div class="col-2">139</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（21）=tva, n.</a></div><div class="col-2">146</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（22）=antと=at［能働と受働］</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（23）=log, =graph, =oph, =nom,等</a></div><div class="col-2">147</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（24）地名 → 人名 ～</a></div><div class="col-2">148</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（25）=et, =ot, =it, =yt, =eut, =aut, =ast</a></div><div class="col-2">149</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（26）［英］=ite</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（27）弱変化男性=Summand型</a></div><div class="col-2">151</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（28）=antと=entの男性</a></div><div class="col-2">153</div></div>');
document.write('<div class="row"><div class="col-2">86-6R</div><div class="col-8"></a></div><div class="col-2">155-164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（1）=ans, =ens</a></div><div class="col-2">155</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（2）=ar, =är</a></div><div class="col-2">156</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（3）</a></div><div class="col-2">157</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（4）中性の=ier</a></div><div class="col-2">158</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（5）Parlament<u>a</u>rier</a></div><div class="col-2">159</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（6）［英］Blackmarketeer</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（7）0ffizier</a></div><div class="col-2">160</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（8）Bankier型</a></div><div class="col-2">161</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（9）=eur. =ieren → =eur.</a></div><div class="col-2">162</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（10）動詞代りの名詞  He is a sound sleeper.</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（11）=inで男性（宝石名）</a></div><div class="col-2">163</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（12）Bro<u>sam</u> Gehor<u>sam</u></a></div><div class="col-2">164</div></div>');
document.write('<div class="row"><div class="col-2"></div><div class="col-8">（13）石の名一般  Obsidian, m. 黒曜石</a></div><div class="col-2">164</div></div></div>');