<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">06-1B</div>
<div class="daimoku">Genitiv</div>
<div class="mpage">1-283</div>
<div class="bango"> </div>
<div class="daimoku">[01]Genitivs Abusolutus</div>
<div class="mpage">4</div>
<div class="bango"> </div>
<div class="daimoku">[02]Genitivs Abusolutus 副詞的規定</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">[03]内容、性質、種類等の規定（形容詞的）</div>
<div class="mpage">57</div>
<div class="bango"> </div>
<div class="daimoku">[04]Gentivs Qualitatis proprius.</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">[05]掲称的二格、掲称的附置規定に等しきもの</div>
<div class="mpage">86</div>
<div class="bango"> </div>
<div class="daimoku">[06]Subjekt=Genitiv.</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">[07]Objekt=Genitiv（物質代名詞にも此の区別あり）</div>
<div class="mpage">101</div>
<div class="bango"> </div>
<div class="daimoku">[08]Genitivs Partitivusの最も純粋なるもの。</div>
<div class="mpage">123</div>
<div class="bango"> </div>
<div class="daimoku">[09]Du bist des Todes（述語用法の疑問系）</div>
<div class="mpage">124</div>
<div class="bango"> </div>
<div class="daimoku">[10]不定法名詞の二格</div>
<div class="mpage">128</div>
<div class="bango"> </div>
<div class="daimoku">[11]熟語化した二格副詞</div>
<div class="mpage">137</div>
<div class="bango"> </div>
<div class="daimoku">[12]見地の二格</div>
<div class="mpage">142</div>
<div class="bango"> </div>
<div class="daimoku">[13]<u>des Inhalts</u>, <u>der Art</u></div>
<div class="mpage">153</div>
<div class="bango"> </div>
<div class="daimoku">[14]述語的Gen. Abs.の熟語（von---）</div>
<div class="mpage">157</div>
<div class="bango"> </div>
<div class="daimoku">[15]des Weiteren等（比較級が主）</div>
<div class="mpage">164</div>
<div class="bango"> </div>
<div class="daimoku">[16]Namens, sein zeichens.（nach---）</div>
<div class="mpage">168</div>
<div class="bango"> </div>
<div class="daimoku">[17]ein glas Weinに形容詞がつくとein glas &lt;uとなる事。&lt;/u</div>
<div class="mpage">175</div>
<div class="bango"> </div>
<div class="daimoku">[18]Gen.Abs.の形容詞的用法（熟語には非ざるもの）</div>
<div class="mpage">175</div>
<div class="bango"> </div>
<div class="daimoku">[19]Zeitliche Erstreckung（Akkusativの代わり）</div>
<div class="mpage">176</div>
<div class="bango"> </div>
<div class="daimoku">[20]数詞、量詞と共に。</div>
<div class="mpage">179</div>
<div class="bango"> </div>
<div class="daimoku">[21]拉典式。--- des Kaisere sein</div>
<div class="mpage">216</div>
<div class="bango"> </div>
<div class="daimoku">[22]<u>seines Weges gehen</u>. 等の熟語</div>
<div class="mpage">229</div>
<div class="bango"> </div>
<div class="daimoku">[23]seines Orts. höheren Orts等。</div>
<div class="mpage">235</div>
<div class="bango"> </div>
<div class="daimoku">[24]時の副詞（二格形） eines schönen Tages.</div>
<div class="mpage">238</div>
<div class="bango"> </div>
<div class="daimoku">[25]Saxon Genitiveを用いなければならぬ場合。(für sein und der Seinigen Wohl)</div>
<div class="mpage">246</div>
<div class="bango"> </div>
<div class="daimoku">[26]"Saxon Genitive"(Sprich Wörtlich)</div>
<div class="mpage">249</div>
<div class="bango"> </div>
<div class="daimoku">[27]間投のGenitiv(über---!)</div>
<div class="mpage">270</div>
<div class="bango"> </div>
<div class="daimoku">[28]ein wenig Wassers</div>
<div class="mpage">277</div>
<div class="bango"> </div>
<div class="daimoku">[29]二格（関係代名詞）離置。</div>
<div class="mpage">283</div>
<div class="bango">06-2B</div>
<div class="daimoku"><u>Manns</u> <u>Genug</u></div>
<div class="mpage">284-287</div>
<div class="bango">06-3B</div>
<div class="daimoku">METAPHERと共に用ひるGENITIV.</div>
<div class="mpage">288-295</div>
<div class="bango">06-4B</div>
<div class="daimoku">ubi locorum等</div>
<div class="mpage">296-305</div>
<div class="bango">06-5B</div>
<div class="daimoku"><u>des Weines</u> trinken GENITIVUS PARTITIVUS</div>
<div class="mpage">306-310</div>
<div class="bango">06-6B</div>
<div class="daimoku">des（そのため）</div>
<div class="mpage">311-321</div>
<div class="bango">06-7B</div>
<div class="daimoku">否定と二格との関係</div>
<div class="mpage">322-328</div>
<div class="bango">06-8R</div>
<div class="daimoku">[MHD]nichts考。通り言葉の二格。deinの代わりに<br />名詞の二格。Genitiv の収縮文に於ける機能は重要な<br />り。Die Germanen <u>des Tacitus</u>型（編者注：ほか4件）</div>
<div class="mpage">329-334</div>
<div class="bango">06-9B</div>
<div class="daimoku">Genitivの意味に閏する一般考察。</div>
<div class="mpage">335-338</div>
<div class="bango">06-10R</div>
<div class="daimoku">それは不可能。 Eines Bogenschulusses weit.二格の語形[MHD]では閏係で充分わかるが[NHD]では</div>
<div class="mpage">339-353</div>
<div class="bango">06-11R</div>
<div class="daimoku">Gentivの重畳</div>
<div class="mpage">354-366</div>
</div>