<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">08-1B</div>
<div class="daimoku">間投的四格。</div>
<div class="mpage">1</div>
<div class="bango">08-2B</div>
<div class="daimoku">四格 Akkusativ</div>
<div class="mpage">2-156</div>
<div class="bango">08-2B</div>
<div class="daimoku">[01]umliche Erstreckung. 編者注:?</div>
<div class="mpage">6</div>
<div class="bango">08-2B</div>
<div class="daimoku">[02]Zeitliche Erstreckung. Meine Tage等</div>
<div class="mpage">6</div>
<div class="bango">08-2B</div>
<div class="daimoku">[03]測定的。（主として比較級の前に）</div>
<div class="mpage">25</div>
<div class="bango">08-2B</div>
<div class="daimoku">[04]測定定。（weiter, voraus等を伴わぬ場合） <u>副詞的</u></div>
<div class="mpage">38</div>
<div class="bango">08-2B</div>
<div class="daimoku">[05]時の副詞。<u>Zeitpunkt</u></div>
<div class="mpage">39</div>
<div class="bango">08-2B</div>
<div class="daimoku">[06] [02]と同じ ...über, durch.</div>
<div class="mpage"> </div>
<div class="bango">08-2B</div>
<div class="daimoku">[07]四格の副詞化。 nichts.（ονδεν, πολ<br />υ）</div>
<div class="mpage">46</div>
<div class="bango">08-2B</div>
<div class="daimoku">[08]結果挙述の四格</div>
<div class="mpage">71</div>
<div class="bango">08-2B</div>
<div class="daimoku">[09]結果挙述四格の一種</div>
<div class="mpage">74</div>
<div class="bango">08-2B</div>
<div class="daimoku">[10]Erstreckungusakkusativ mit Nachadverb通過のAkkusativ（<u>hinau</u>等と）</div>
<div class="mpage">88</div>
<div class="bango">08-2B</div>
<div class="daimoku">[11]drei Meter hoch等。</div>
<div class="mpage">91</div>
<div class="bango">08-2B</div>
<div class="daimoku">[12]「差のum」＋比較級の代りに単に四格。</div>
<div class="mpage">103</div>
<div class="bango">08-2B</div>
<div class="daimoku">[13]Inneres Objekt. 〔外国語〕</div>
<div class="mpage">106</div>
<div class="bango">08-2B</div>
<div class="daimoku">[14]Lassenと二個の四格</div>
<div class="mpage">107</div>
<div class="bango">08-2B</div>
<div class="daimoku">[15]数量四格を支配する動詞。～betragen,<br />～messen, ～zähLen</div>
<div class="mpage">109</div>
<div class="bango">08-2B</div>
<div class="daimoku">[16]be= と四格。</div>
<div class="mpage">110</div>
<div class="bango">08-2B</div>
<div class="daimoku">[17]eine Zeit <u>lang</u> 「langを前置詞に扱っては？〕</div>
<div class="mpage">110</div>
<div class="bango">08-2B</div>
<div class="daimoku">[18]<u>einen Strich</u> malen. 量的規定の四格。</div>
<div class="mpage">111</div>
<div class="bango">08-2B</div>
<div class="daimoku">[19]二菫四格（nennen, schelten)</div>
<div class="mpage">114</div>
<div class="bango">08-2B</div>
<div class="daimoku">[20]特 「lehren, 其他」</div>
<div class="mpage">123</div>
<div class="bango">08-2B</div>
<div class="daimoku">[21]結果挙述。退去を命ずる等。</div>
<div class="mpage">134</div>
<div class="bango">08-2B</div>
<div class="daimoku">[22]挙形（又は省略形は一格又は四格）</div>
<div class="mpage">146</div>
<div class="bango">08-2B</div>
<div class="daimoku">[23]Wache stehenに対する一格形</div>
<div class="mpage">147</div>
<div class="bango">08-2B</div>
<div class="daimoku">[24]<u>seinen</u> <u>Mann</u> stehen=sich Bewähren</div>
<div class="mpage">152</div>
<div class="bango">08-2B</div>
<div class="daimoku">[25]Karussel fahren等</div>
<div class="mpage">154</div>
<div class="bango">08-3B</div>
<div class="daimoku">数値の四格。 aufと関係</div>
<div class="mpage">157</div>
<div class="bango">08-4B</div>
<div class="daimoku">文肢。Inneres Objekt</div>
<div class="mpage">158-191</div>
<div class="bango">08-4B</div>
<div class="daimoku">[01]Genitiv.</div>
<div class="mpage">159</div>
<div class="bango">08-4B</div>
<div class="daimoku">[02]四格の例</div>
<div class="mpage">160</div>
<div class="bango">08-4B</div>
<div class="daimoku">[03]Funken sprühen等（結果の四格と似て非なこと）</div>
<div class="mpage">173</div>
<div class="bango">08-4B</div>
<div class="daimoku">[04]代名詞四格のInneres Objektは、普通のものより<br />は目に立たざる故、用ひられる事多し。</div>
<div class="mpage">177</div>
<div class="bango">08-4B</div>
<div class="daimoku">[05]特別に拵へるもの。</div>
<div class="mpage">177</div>
<div class="bango">08-4B</div>
<div class="daimoku">[06]lassenと二つの四格</div>
<div class="mpage">177</div>
<div class="bango">08-4B</div>
<div class="daimoku">[07]einen Strich streichen ひとこすりする。</div>
<div class="mpage">178</div>
<div class="bango">08-4B</div>
<div class="daimoku">[08]<u>夢が</u>夢みる。（主語とinneres Verbum）</div>
<div class="mpage">179</div>
<div class="bango">08-4B</div>
<div class="daimoku">[09]希・羅</div>
<div class="mpage">180</div>
<div class="bango">08-5R</div>
<div class="daimoku">特に人聞の四格に閲する注意：「その人の言う事を」<br />「その人の考えていることを」など。 Guten Morgen<br />! の完全形。 den <u>Weg gehen</u>, die <u>Strasse</u> ziehen<br />等。 Den Herrn Spielen等<br />編者注：このほか9件</div>
<div class="mpage">192-199</div>
<div class="bango">08-6B</div>
<div class="daimoku"><u>Was</u> andere <u>tanzen</u>, muss er schätzen.</div>
<div class="mpage">200-202</div>
</div>