<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">15-1R</div>
<div class="daimoku">具体的なdas ～ e</div>
<div class="mpage">1-2</div>
<div class="bango">15-2B</div>
<div class="daimoku">形容詞の名詞化 名詞的用法<br />Das schickssal Teusend<u>er</u> von Menschen.</div>
<div class="mpage">3-158</div>
<div class="bango"> </div>
<div class="daimoku">[01]過去分詞。（男女のみ） 形容詞の名詞化<br />der Abtrünnige, Aufständische, der Aussätzige.</div>
<div class="mpage">5</div>
<div class="bango"> </div>
<div class="daimoku">[02]形容詞（男女のみ）及ひ複数（人）</div>
<div class="mpage">25</div>
<div class="bango"> </div>
<div class="daimoku">[03]女性。</div>
<div class="mpage">37-38</div>
<div class="bango"> </div>
<div class="daimoku">[04]重（名詞化）Allerlei等</div>
<div class="mpage">38</div>
<div class="bango"> </div>
<div class="daimoku">[05]中性の際を小文字で書く傾向。</div>
<div class="mpage">61</div>
<div class="bango"> </div>
<div class="daimoku">[06]zu-endを名詞化</div>
<div class="mpage">63</div>
<div class="bango"> </div>
<div class="daimoku">[07]中性。（......点、方面を指すもの）（性質）定冠詞</div>
<div class="mpage">64</div>
<div class="bango"> </div>
<div class="daimoku">[08]Gattunngegriffの中性。</div>
<div class="mpage">71</div>
<div class="bango"> </div>
<div class="daimoku">[09]学問的概念としての中性。 Das 0rganische,<br />Unorganische.</div>
<div class="mpage">78</div>
<div class="bango"> </div>
<div class="daimoku">[10]名詞か略される場合には小書</div>
<div class="mpage">81</div>
<div class="bango"> </div>
<div class="daimoku">[11]過去、現在「分詞句」の名詞化</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">[12]冠詞を件はぬ際</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">[13]現在分訶より。（成句語）</div>
<div class="mpage">102</div>
<div class="bango"> </div>
<div class="daimoku">[14]現在分詞（新造）</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">[15]小書するもの。（前置詞と共に）</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">[16]形容詞の次に転来名詞。（弱変化例外あり！）</div>
<div class="mpage">122</div>
<div class="bango"> </div>
<div class="daimoku">[17]ein Leichtes sein.</div>
<div class="mpage">123</div>
<div class="bango"> </div>
<div class="daimoku">[18]<u>Was</u> gibt's <u>Neues</u>? (ce que.....de....)</div>
<div class="mpage">130</div>
<div class="bango"> </div>
<div class="daimoku">[19]manches, vieles, weniges, alles, einiges, eines,<br />solches, =mancherlei u.s.w. dieses, yenes,<br />das beste, meiste.</div>
<div class="mpage">136</div>
<div class="bango"> </div>
<div class="daimoku">[20]中性（其の場合云々の具体的「事柄」を指す）<br />普通名詞的の中性（das Freie, des Äussere）</div>
<div class="mpage">138</div>
<div class="bango"> </div>
<div class="daimoku">[21]zu+不定法の名詞化</div>
<div class="mpage">147</div>
<div class="bango"> </div>
<div class="daimoku">[22]Gedrucktes, Eingemachtes, Gebackenes, Gehacktes</div>
<div class="mpage">148</div>
<div class="bango"> </div>
<div class="daimoku">[23]弱語尾（三格語尾=emの弱化）<br />Der mich <u>zu</u> Saladins <u>Gefangenen</u> machte.<br />(statt Gefangenem.)</div>
<div class="mpage">149</div>
<div class="bango"> </div>
<div class="daimoku">[24]yung und alt</div>
<div class="mpage">150</div>
<div class="bango"> </div>
<div class="daimoku">[25]長き冠飾句的なるもの。然し、<u>der Lebendig<br />begrabene</u>等も可。</div>
<div class="mpage">152</div>
<div class="bango">15-3B</div>
<div class="daimoku">［英］Gerundによる文の名詞化。</div>
<div class="mpage">159-169</div>
<div class="bango">15-4B</div>
<div class="daimoku">主語二格と〈前置詞句一個）の附加詞（durchの機能）</div>
<div class="mpage">170-222</div>
<div class="bango">15-5B</div>
<div class="daimoku">名詞化〈但し形容詞を除く）</div>
<div class="mpage">223-256</div>
<div class="bango"> </div>
<div class="daimoku">[01]［接続其他のPartikel］大文字（二格は無語尾）</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">[02]動詞（結？したるものとせざるものと）</div>
<div class="mpage">238</div>
<div class="bango"> </div>
<div class="daimoku">[03]再帰動詞の=ung名詞化。</div>
<div class="mpage">239</div>
<div class="bango"> </div>
<div class="daimoku">[04]動詞不定法（新造）</div>
<div class="mpage">240</div>
<div class="bango"> </div>
<div class="daimoku">[05]動詞不定法句（新造）。</div>
<div class="mpage">240</div>
<div class="bango"> </div>
<div class="daimoku">[06]形容詞のまま。</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">[07]etwas Gutes, nichts Gutes等。</div>
<div class="mpage">241</div>
<div class="bango"> </div>
<div class="daimoku">[08]形容詞つきの名詞。 （大書）。</div>
<div class="mpage">242</div>
<div class="bango"> </div>
<div class="daimoku">[09]男性化。</div>
<div class="mpage">243</div>
<div class="bango"> </div>
<div class="daimoku">[10]名詞の名詞化（中性）</div>
<div class="mpage">243</div>
<div class="bango"> </div>
<div class="daimoku">[11]Nomen actions mit dem yungen Nexus.</div>
<div class="mpage">244</div>
<div class="bango"> </div>
<div class="daimoku">[12]不定法。殊に不定冠詞。ein Kommen und Gehen</div>
<div class="mpage">245</div>
<div class="bango"> </div>
<div class="daimoku">[13]不定法。keinと共に。</div>
<div class="mpage">247</div>
<div class="bango"> </div>
<div class="daimoku">[14]文章の名詞化（中性）<br />［英］→「自由型Composita」と一部一致す。</div>
<div class="mpage">248</div>
<div class="bango"> </div>
<div class="daimoku">[15]名詞化とmit Bestimmungen</div>
<div class="mpage">256</div>
<div class="bango">15-6B</div>
<div class="daimoku"><u>文の</u>名詞化</div>
<div class="mpage">257-263</div>
<div class="bango">15-7R</div>
<div class="daimoku">四格目的語が二格でなく、前置詞を要するもの
<p> </p>
<ol>
<li>der Besuch bei～</li>
<li>ein Überfall auf～</li>
</ol>
<p>Das <u>vertriebenen</u>gesetz（合成名詞と、形容詞の<br />名詞化の複数の……二格か？</p>
</div>
<div class="mpage">264-265</div>
<div class="bango">15-8B</div>
<div class="daimoku">複数二格の無冠詞、（形容詞の名詞化）<br /><u>普通名詞</u>の場合は不可能なり。</div>
<div class="mpage">266-268</div>
<div class="bango">15-9R</div>
<div class="daimoku">形容詞のままを名詞的に。<br /><u>Das Deutsche, das Italienische</u>など（中性の場合<br />の重要なもの）</div>
<div class="mpage">269</div>
<div class="bango">15-10B</div>
<div class="daimoku">不定法名詞化の一型 「文章の短縮」的意形</div>
<div class="mpage">270-276</div>
<div class="bango">15-11B</div>
<div class="daimoku">=en(不完全名詞化〉)</div>
<div class="mpage">277-279</div>
<div class="bango">15-12R</div>
<div class="daimoku">an <u>das Unmög1iche</u> grenzen.（範囲ヲ指スモノ〉<br />［英］<u>verge</u> on～<br />Das Äussere 中性にして具体物を指すもの。<br />［羅］にも不定名詞あり、中性！<br />熟語的（形容詞の名詞化）<br />=en動作名詞と語幹形との区別、習慣的に差の生<br />ぜるもの多し！<br />'statt Erfunde =n<u>em</u><br />［羅］GERUNDIUMとGERUNDIVUM. zu+不定旬に相当<br />文の名詞化の際の一つの注意 adnominalな前置詞<br />文肢の重畳は避けよ</div>
<div class="mpage">280-284</div>
<div class="bango">15-13B</div>
<div class="daimoku">文を不定法名詞に省略する経過（直前を受ける<br />不定法名詞</div>
<div class="mpage">285-288</div>
<div class="bango">15-14B</div>
<div class="daimoku">名詞化した不定法（<u>具体動作</u>）</div>
<div class="mpage">289-293</div>
<div class="bango">15-15R</div>
<div class="daimoku">定形中心文法の基礎問題 「伯父か書いた」を<br />「伯父の到着」という（日誌などで）<br />［仏］alleés et venues. Kommeen u.Gehen.<br />名詞化はまだ文章として考えていることの徴候的<br />証拠</div>
<div class="mpage">294-295</div>
<div class="bango">15-16B</div>
<div class="daimoku">=ung型 nomen actionisの諸問題。</div>
<div class="mpage">296-297</div>
<div class="bango">15-17B</div>
<div class="daimoku">名詞化形容詞の如くにして然らざるもの：</div>
<div class="mpage">298</div>
<div class="bango">15-18B</div>
<div class="daimoku">［仏］不定法名詞<br />1. Au lever du rideau, la scène est vide.</div>
<div class="mpage">299</div>
<div class="bango">15-19R</div>
<div class="daimoku"><u>［領］を意味するもの</u>。<br />das <u>Nachsehen</u> haben等の熟語的なもの。<br />完全に名詞化した不定法<br />熟成した不定法の名詞化<br />［英］sewing machine型<br />Der Blick <u>in den</u>Garten等、方向指示の問題<br />bis zum <u>Überfliessen</u>.<br />領地を意味する中性<br /><u>Die Herren Gelehrten</u></div>
<div class="mpage">300-306</div>
<div class="bango">15-20B</div>
<div class="daimoku"><u>Bediente</u>の問題 複数の弱変化</div>
<div class="mpage">307</div>
<div class="bango">15-21R</div>
<div class="daimoku">［語尾］人間のDeutsch<u>em</u>, Deutsch<u>es</u>は避ける。<br />ihnen als Deutsch<u>en</u>.<br />葡萄酒名は男性。<br />再帰動詞の名訶化 sich winden → das Winden.<br />複数形 Das Verbrechen→die Verbrechen:<br />die ersten, die beiden, die meisten, die übrigen<br />zum Aufdenbaum klettern<br />［英］無冠詞もあり。 1.Give to needy!<br />Das Deutsch<u>e</u>とdas Deutsch<br />im Dunkeln. （im Dunkel）<br />im Stillen. （*in der Stille）<br /><u>男性で人ならざるもの。</u><br />複数は人ならざること。</div>
<div class="mpage">308-313</div>
</div>