<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">13-1B</div>
<div class="daimoku">形容詞形態・語尾</div>
<div class="mpage">1-131</div>
<div class="bango"> </div>
<div class="daimoku">[01]? 尾をつけさるもの（中には不定数詞に扱うもの<br />あり。</div>
<div class="mpage">3</div>
<div class="bango"> </div>
<div class="daimoku">[02]定冠詞をくりかえすことあり。</div>
<div class="mpage">4</div>
<div class="bango"> </div>
<div class="daimoku">[03]中性単数の前の語尾の省略 (archaistich)</div>
<div class="mpage">5</div>
<div class="bango"> </div>
<div class="daimoku">[04]（熟語的用法の際のみ.）前綴の形容詞化。</div>
<div class="mpage">19</div>
<div class="bango"> </div>
<div class="daimoku">[05]ganz Deutschland.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">[06]wir Deutscheかwir Deutschenか？</div>
<div class="mpage">30</div>
<div class="bango"> </div>
<div class="daimoku">[07]=erkei</div>
<div class="mpage">34</div>
<div class="bango"> </div>
<div class="daimoku">[08]語尾をとらぬ熟語。</div>
<div class="mpage">37</div>
<div class="bango"> </div>
<div class="daimoku">[09]<u>al1erhand</u>.</div>
<div class="mpage">38</div>
<div class="bango"> </div>
<div class="daimoku">[10]形容詞の後置</div>
<div class="mpage">39</div>
<div class="bango"> </div>
<div class="daimoku">[11]<u>Lieben</u> Freunde! (Vokati.)</div>
<div class="mpage">68</div>
<div class="bango"> </div>
<div class="daimoku">[12]frohes Mutes.（副詞的 Genitivに多し）</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">[13]lauter, eitel.（前置詞的接続詞なり）</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">[14]=eの語尾</div>
<div class="mpage">85</div>
<div class="bango"> </div>
<div class="daimoku">[15]強変化の例語について</div>
<div class="mpage">87</div>
<div class="bango"> </div>
<div class="daimoku">[16]大害する附加語的形容詞</div>
<div class="mpage">89</div>
<div class="bango"> </div>
<div class="daimoku">[17]Das <u>Weisse Haus</u> 白亜館（アメリカ）</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">[18]Saxon genitive後の形容詞は強変化<br />（弱変化：schönes Knaben等もあるわけ）</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">[19]mir Unglücklichem等。（名詞化へ行く）</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">[20]so ist diese Auffassung <u>eine irrige</u>.</div>
<div class="mpage">110</div>
<div class="bango"> </div>
<div class="daimoku">[21]弱変化男性名詞の前の強語尾</div>
<div class="mpage">120</div>
<div class="bango"> </div>
<div class="daimoku">[22]形容詞 格支配 無語尾のrosa, lila等</div>
<div class="mpage">124</div>
<div class="bango"> </div>
<div class="daimoku">[23]?</div>
<div class="mpage">131</div>
<div class="bango">13-2B</div>
<div class="daimoku"> </div>
<div class="mpage">132-250</div>
<div class="bango"> </div>
<div class="daimoku">（1）前に何かある場合に弱変化語尾を用いる例。</div>
<div class="mpage">132</div>
<div class="bango"> </div>
<div class="daimoku">（2）Die graue Substanz. 造語形容詞</div>
<div class="mpage">139</div>
<div class="bango"> </div>
<div class="daimoku">（3）形容詞　形容詞の意味</div>
<div class="mpage">144</div>
<div class="bango"> </div>
<div class="daimoku">（4）Epithetisch.</div>
<div class="mpage">147</div>
<div class="bango"> </div>
<div class="daimoku">（5）副詞と見られ勝ちな場合。</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">（6）Epithetischとは少し違う場合。羅典式、述語（副詞） <u>Laetus</u> abit</div>
<div class="mpage">183</div>
<div class="bango"> </div>
<div class="daimoku">動詞代りの形容詞。1.（seinと共に）<br />2.sich machenと共に 3.weidenと共に</div>
<div class="mpage">185</div>
<div class="bango"> </div>
<div class="daimoku">（8）厳密に規定的（特殊化的、限定的）</div>
<div class="mpage">202</div>
<div class="bango"> </div>
<div class="daimoku">（9）外囲的形容詞の重畳（弱語尾の問題もあり）<br />指示詞と称するものの理由ここにあり。</div>
<div class="mpage">204</div>
<div class="bango"> </div>
<div class="daimoku">（10）形容に非ずして「限定」的</div>
<div class="mpage">222</div>
<div class="bango"> </div>
<div class="daimoku">（11）拉丁のsummus, medius, imus等と同じ関係にな<br />るもの。</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">（12）Genitiv的（及び範囲規定）philosophische<br />Unkenntnis
<p> </p>
<p>編者注：上記（3）～（12）はノート・ブ<br />ック式にまとめられている。したがって、この<br />部分だけを独立させ、-つの袋にしたほうが良<br />かったかもしれない。この部分の主タイ卜ルは<br />「形容詞・形容詞の意味」である。</p>
</div>
<div class="mpage">234</div>
<div class="bango">13-3B</div>
<div class="daimoku">定語尾属か不定語尾属か?。（準定語尾属）</div>
<div class="mpage">251-299</div>
<div class="bango"> </div>
<div class="daimoku">[01]alle其他定語尾属と形容詞</div>
<div class="mpage">253</div>
<div class="bango"> </div>
<div class="daimoku">[02]Alle, dieseと<u>強</u>（その他例外）</div>
<div class="mpage">254</div>
<div class="bango"> </div>
<div class="daimoku">[03]einige, mehrere, viele, beide</div>
<div class="mpage">264</div>
<div class="bango"> </div>
<div class="daimoku">[04]mancherと弱（強）</div>
<div class="mpage">275</div>
<div class="bango"> </div>
<div class="daimoku">[05]二個の形容詞のうち前を強、後を弱にする例。（前が指示詞化す）</div>
<div class="mpage">279</div>
<div class="bango"> </div>
<div class="daimoku">[06]二番目の形容詞を無意味に弱にすることがManieになっている人の例。</div>
<div class="mpage">286</div>
<div class="bango"> </div>
<div class="daimoku">[07]一格のwir, ihr後の弱変化</div>
<div class="mpage">287</div>
<div class="bango"> </div>
<div class="daimoku">[08]einzeln等の後の弱変化 <u>dieser</u> <u>mein</u> best<u>er</u> Freund.</div>
<div class="mpage">289</div>
<div class="bango"> </div>
<div class="daimoku">[09]viele, wenige, mehrere</div>
<div class="mpage">291</div>
<div class="bango"> </div>
<div class="daimoku">[10]schönes Äuss<u>ere</u>.(=es)</div>
<div class="mpage">297</div>
<div class="bango">13-4R</div>
<div class="daimoku">Sie ist tipptopp.（firstrate)</div>
<div class="mpage">300-306</div>
<div class="bango"> </div>
<div class="daimoku">「仏」は名詞と形容詞との区別あいまいなり：<br />porteur, porteuse型及び、(Appositiv →)<br />名詞をすぐ形容詞として用い得。<br />形容詞の無語尾：（色）Des rubans <u>chocolat</u>.<br />形容詞の示格機能</div>
<div class="mpage">300-306</div>
<div class="bango">13-5B</div>
<div class="daimoku">Weissbrot</div>
<div class="mpage">307-314</div>
<div class="bango">13-6B</div>
<div class="daimoku">rot und geres Tu1penbeet.</div>
<div class="mpage">315-322</div>
<div class="bango">13-7B</div>
<div class="daimoku">geraum, feind, gram等、専ら述語用法の形容詞。</div>
<div class="mpage">323-333</div>
<div class="bango">13-8B</div>
<div class="daimoku">形容詞の性数。KONGRUENZ</div>
<div class="mpage">334-338</div>
<div class="bango">13-9B</div>
<div class="daimoku">Alles Gute. Dieses Gute. 及びそれらに類する場合</div>
<div class="mpage">339-352</div>
<div class="bango">13-10R</div>
<div class="daimoku">人を主語にするか、物を主語にするかの問題<br />形容詞 動詞もあり：gefallen.<br />形容詞格語尾 無冠詞の場合の形容詞変化：<br />問題の gut<u>es</u> Mensch<u>en</u></div>
<div class="mpage">353-355</div>
<div class="bango">13-11B</div>
<div class="daimoku">合成名詞 Rote=Kieuz=Schwester.</div>
<div class="mpage">356-362</div>
<div class="bango">13-12R</div>
<div class="daimoku">la sage-femme 産婆<br />副詞の形容詞化 Militärische Erfolk=losigkeit<br />.=見地の形容詞。<br />名詞化は弱か強か?</div>
<div class="mpage">363-370</div>
<div class="bango">13-13B</div>
<div class="daimoku">alle=, dies=, jed=, kein=, 等の二格語尾（弱を主に）</div>
<div class="mpage">371-376</div>
<div class="bango">13-14R</div>
<div class="daimoku">格語尾=el, =belの際<br />形容詞の格語尾 <u>Unser</u> wacke<u>re</u> Freund<br />定語尾属一般論。<br />前に何かある際の強語尾<br />附加語は格語尾あり、述語は無語尾といふ基本問題の<br />参考<br />「仏」<u>grand</u> hommeとhomme <u>grand</u><br />度量衡名（単）の前につける場合の形容詞語尾。</div>
<div class="mpage">377-383</div>
<div class="bango">13-15R</div>
<div class="daimoku"><u>強語尾の重要性</u>。複数（名詞化した）の=en語尾形<br />複数（名詞化した）の=en語尾形<br />solcheの後の強弱に依る意味の区別<br />Saxon Genitive等の強語尾<br />動詞とà blanc, à vide等 moudre à vide<br />形容詞の意味上の根本問題<br />indifferenzとDifferenziertheit
<p> </p>
<p>編者注：このほか17件あり。</p>
</div>
<div class="mpage">384-403</div>
</div>