<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">21-1B</div>
<div class="daimoku"><u>immer</u></div>
<div class="mpage">1-20</div>
<div class="bango"> </div>
<div class="daimoku">immer 常に。</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">認容的<u>immer</u></div>
<div class="mpage">3</div>
<div class="bango"> </div>
<div class="daimoku">jedenfalls. immerhin（併しいづれにせよ）</div>
<div class="mpage">6</div>
<div class="bango"> </div>
<div class="daimoku">immer（toujours）<u>やはり</u> 今までに従って、<br />gleichfalls.</div>
<div class="mpage">10</div>
<div class="bango"> </div>
<div class="daimoku">命令法と共に。</div>
<div class="mpage">15</div>
<div class="bango"> </div>
<div class="daimoku">空間的。（immer gradaus）</div>
<div class="mpage">17</div>
<div class="bango"> </div>
<div class="daimoku">immer = je 各々</div>
<div class="mpage">18</div>
<div class="bango"> </div>
<div class="daimoku">［雑］irgend（＝） nirgend（s）</div>
<div class="mpage">20</div>
<div class="bango">21-2B</div>
<div class="daimoku">［雑］<u>mal</u>と<u>einmal</u></div>
<div class="mpage">21-49</div>
<div class="bango"> </div>
<div class="daimoku">（nun）einmal「どうせ」</div>
<div class="mpage">22</div>
<div class="bango"> </div>
<div class="daimoku">erst mal wieder mal</div>
<div class="mpage">23</div>
<div class="bango"> </div>
<div class="daimoku">zunächst einmal. erst einmal vorläufig einmal</div>
<div class="mpage">24</div>
<div class="bango"> </div>
<div class="daimoku">nlcht einmal</div>
<div class="mpage">25</div>
<div class="bango"> </div>
<div class="daimoku">wieder einmal（erst einmal）</div>
<div class="mpage">28</div>
<div class="bango"> </div>
<div class="daimoku"><u>nicht einmal</u>.</div>
<div class="mpage">30</div>
<div class="bango"> </div>
<div class="daimoku">endlich einmal schliesslich einmal</div>
<div class="mpage">35</div>
<div class="bango"> </div>
<div class="daimoku">gerade einmal gelegentlich einmal<br />später einmal たまに いつか一度</div>
<div class="mpage">41</div>
<div class="bango"> </div>
<div class="daimoku">vorlänglig einmal zunächst einmal</div>
<div class="mpage">43</div>
<div class="bango">21-3B</div>
<div class="daimoku">［雑］<u>ja</u></div>
<div class="mpage">50-87</div>
<div class="bango"> </div>
<div class="daimoku">…ja…！（どうも畏れ入った）　実に！</div>
<div class="mpage">51</div>
<div class="bango"> </div>
<div class="daimoku">自明の事柄として言ふ際。</div>
<div class="mpage">53</div>
<div class="bango"> </div>
<div class="daimoku">「否むしろ」（wo nicht gar, と同じ）<br />Man könnte fast sagen.→（並列接続的）</div>
<div class="mpage">59</div>
<div class="bango"> </div>
<div class="daimoku"><u>ja</u> nicht.（金輪際） ja（命令法と）<br /><u>nur ja</u></div>
<div class="mpage">67</div>
<div class="bango"> </div>
<div class="daimoku">関係文中のja（doch）</div>
<div class="mpage">71</div>
<div class="bango"> </div>
<div class="daimoku">疑問文の先頭に（せき込むトキ） ja［aber］</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">如何となれば…、それが証拠に。 auchに似たり</div>
<div class="mpage">73</div>
<div class="bango"> </div>
<div class="daimoku">反語的「…ではないか！」（助勢詞）「ハア」</div>
<div class="mpage">75</div>
<div class="bango"> </div>
<div class="daimoku">肯定命令法とja.</div>
<div class="mpage">76</div>
<div class="bango"> </div>
<div class="daimoku">［雑］<u>je</u></div>
<div class="mpage">82</div>
<div class="bango"> </div>
<div class="daimoku">von je, von jeher.</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">je nachdem，（副詞的、接続詞的）</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">je（nieの反対）</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">je <u>各々</u> <u>respektive</u>.ja wohl? da ja....<br />ja（うるさいとき、よい加減な返事）<br /><u>ja aber</u></div>
<div class="mpage">86</div>
<div class="bango">21-4B</div>
<div class="daimoku"><u>gerade</u></div>
<div class="mpage">88-119</div>
<div class="bango"> </div>
<div class="daimoku">noch gerade....［genug.］</div>
<div class="mpage">89</div>
<div class="bango"> </div>
<div class="daimoku">just.（前置的） ちようど</div>
<div class="mpage">90</div>
<div class="bango"> </div>
<div class="daimoku">かへって…が 「が」</div>
<div class="mpage">92</div>
<div class="bango"> </div>
<div class="daimoku">丁度（偶然） <u>ausgerechnet</u>.</div>
<div class="mpage">94</div>
<div class="bango"> </div>
<div class="daimoku">nicht gerade必ずしも…と言ふ程ではない。<br />-1itotes- まさか…に非ず</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">普通の場合（時間的）ちようど</div>
<div class="mpage">102</div>
<div class="bango"> </div>
<div class="daimoku">ちようど直ぐ right here.</div>
<div class="mpage">105</div>
<div class="bango"> </div>
<div class="daimoku">gerade deshlb, weil 等（前置的接続詞）</div>
<div class="mpage">105</div>
<div class="bango"> </div>
<div class="daimoku">gerade....皮肉 仏の<u>bien</u></div>
<div class="mpage">106</div>
<div class="bango"> </div>
<div class="daimoku">gerade so wie～</div>
<div class="mpage">106</div>
<div class="bango"> </div>
<div class="daimoku">ちょうど（時間的ならざるもの）</div>
<div class="mpage">107</div>
<div class="bango"> </div>
<div class="daimoku">gar</div>
<div class="mpage">108</div>
<div class="bango"> </div>
<div class="daimoku">Adverbal さヘ一一一する。</div>
<div class="mpage">109</div>
<div class="bango"> </div>
<div class="daimoku">überhaupt nicht = gar nicht</div>
<div class="mpage">109</div>
<div class="bango"> </div>
<div class="daimoku"><u>nicht gar</u> nicht so gar.<br />ganzと同じ（肯定の際）<br />und gar = nun gar, vollends.</div>
<div class="mpage">110</div>
<div class="bango"> </div>
<div class="daimoku"><u>gar</u></div>
<div class="mpage">112</div>
<div class="bango"> </div>
<div class="daimoku">gar zuとgar so gal=sogar.gar［sogar］［wohigar］.</div>
<div class="mpage">113</div>
<div class="bango"> </div>
<div class="daimoku">sogar wohl gar</div>
<div class="mpage">114</div>
<div class="bango"> </div>
<div class="daimoku">so gar gar nicht.</div>
<div class="mpage">115</div>
<div class="bango"> </div>
<div class="daimoku">［雑］ ganz</div>
<div class="mpage">117</div>
<div class="bango"> </div>
<div class="daimoku">gar nicht gar kein ganz und gar gut.（nicht....gut）</div>
<div class="mpage">118</div>
<div class="bango">21-5B</div>
<div class="daimoku">［雜］<u>erst</u></div>
<div class="mpage">120-165</div>
<div class="bango"> </div>
<div class="daimoku">わざわざ <u>vollende</u>（否定の強調）</div>
<div class="mpage">121</div>
<div class="bango"> </div>
<div class="daimoku">それこそ（大変なことになる） vollends.<br />況ンヤ、ニ至ッテハ</div>
<div class="mpage">123</div>
<div class="bango"> </div>
<div class="daimoku">先以て…して掛かる。（時聞的） erst <u>noch</u></div>
<div class="mpage">125</div>
<div class="bango"> </div>
<div class="daimoku">「やっと」</div>
<div class="mpage">126</div>
<div class="bango"> </div>
<div class="daimoku">erst recht. 又はerstのみ。 nun erst recht.</div>
<div class="mpage">132</div>
<div class="bango"> </div>
<div class="daimoku">wenn....［nur］erst 云々した暁にはが最後</div>
<div class="mpage">134</div>
<div class="bango"> </div>
<div class="daimoku">試みに…せしめよ。（まづ…）</div>
<div class="mpage">136</div>
<div class="bango"> </div>
<div class="daimoku">erst「はやく」に近し</div>
<div class="mpage">137</div>
<div class="bango"> </div>
<div class="daimoku">eben</div>
<div class="mpage">138</div>
<div class="bango"> </div>
<div class="daimoku">eben（最も軽い場合）ほとんど無意味=nur<br />［雑］ <u>eben</u></div>
<div class="mpage">139</div>
<div class="bango"> </div>
<div class="daimoku">eben（Litotes）あながち…に非ず。<br />大して、…といふほどでもない。<br />否定詞を伴ふもの。</div>
<div class="mpage">141</div>
<div class="bango"> </div>
<div class="daimoku">つまり、とりも直ず。</div>
<div class="mpage">143</div>
<div class="bango"> </div>
<div class="daimoku">というのは（denn） つまり（大した仕細なし!）</div>
<div class="mpage">145</div>
<div class="bango"> </div>
<div class="daimoku">nicht eben（大して）（必ずしも）</div>
<div class="mpage">149</div>
<div class="bango"> </div>
<div class="daimoku">eben doch.（つまりやっぱり）</div>
<div class="mpage">150</div>
<div class="bango"> </div>
<div class="daimoku">同じ概念に逆戻って強調するeben.<br />［それより言ひ様がない」時</div>
<div class="mpage">151</div>
<div class="bango"> </div>
<div class="daimoku">申すまでもなく。</div>
<div class="mpage">153</div>
<div class="bango"> </div>
<div class="daimoku">eben=gerade.</div>
<div class="mpage">157</div>
<div class="bango"> </div>
<div class="daimoku">［雑］<u>etwa</u></div>
<div class="mpage">160</div>
<div class="bango"> </div>
<div class="daimoku">nicht etwa....sondern.</div>
<div class="mpage">161</div>
<div class="bango"> </div>
<div class="daimoku">etwa ....なぞと（結局が否定）</div>
<div class="mpage">161</div>
<div class="bango"> </div>
<div class="daimoku">…とでも（思ふか、等）=疑問文の</div>
<div class="mpage">162</div>
<div class="bango"> </div>
<div class="daimoku">eventuell.（疑問文に非ざる場合）</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">etwa=sagen wirたとへば</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">概ね、凡そ。</div>
<div class="mpage">163</div>
<div class="bango"> </div>
<div class="daimoku">殆ど無くてもよい際の erst</div>
<div class="mpage">164</div>
<div class="bango"> </div>
<div class="daimoku">［雑］<u>etwas</u></div>
<div class="mpage">165</div>
</div>