<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">25-1R</div>
<div class="daimoku">wenn....nicht.... 或は云々することもあるべし<br />....es sei denn,daß....<br />［MHD］ daz, dazの構造：<br />Verweisung<br />Konsekutiv=wenn<br />wennと時称 Modusの問題一括</div>
<div class="mpage">1-3</div>
<div class="bango">25-2B</div>
<div class="daimoku">接続詞補足 1.einmal（…云々するや否や、したる以上…） 2.<u>als ob</u>,［tout comme si］</div>
<div class="mpage">4-5</div>
<div class="bango">25-3B</div>
<div class="daimoku">wenn....nur.... pourvu que</div>
<div class="mpage">6-10'</div>
<div class="bango">25-4R</div>
<div class="daimoku">一概念一用語の圧釈、Wenn<br />wenn（falls） …の場合のために言うが<br />およろしければ等 （会話）<br />wie wenn....?</div>
<div class="mpage">11-23</div>
<div class="bango">25-5B</div>
<div class="daimoku">…する時の。 adnominal（時間関係を存す）</div>
<div class="mpage">24-34</div>
<div class="bango">25-6B</div>
<div class="daimoku"><u>普通のwenn</u> PARADIGMA</div>
<div class="mpage">35-38</div>
<div class="bango">25-7B</div>
<div class="daimoku">時間性を帯びた<u>wenn</u>（im Augenblick）</div>
<div class="mpage">39-40</div>
<div class="bango">25-8B</div>
<div class="daimoku">引用的・指摘的［ADVERSATIV］</div>
<div class="mpage">41-45</div>
<div class="bango">25-9B</div>
<div class="daimoku">［英］ unless</div>
<div class="mpage">46-48</div>
<div class="bango">25-10B</div>
<div class="daimoku">加項。wenn.</div>
<div class="mpage">49</div>
<div class="bango">25-11B</div>
<div class="daimoku"> </div>
<div class="mpage">50-100</div>
<div class="bango"> </div>
<div class="daimoku">［01］もしも。…れば。</div>
<div class="mpage">50</div>
<div class="bango"> </div>
<div class="daimoku">［02］対比の型 1.so sehr... so....</div>
<div class="mpage">51</div>
<div class="bango"> </div>
<div class="daimoku">［03］-Dass-</div>
<div class="mpage">60</div>
<div class="bango"> </div>
<div class="daimoku">［04］nichtに注意（直接法ゆえ）</div>
<div class="mpage">61</div>
<div class="bango"> </div>
<div class="daimoku">［05］daßを使はず並立せしめる際<br />（直接法を用ひる場合）</div>
<div class="mpage">65</div>
<div class="bango"> </div>
<div class="daimoku">［06］damitの意（挿入文ならず）</div>
<div class="mpage">68</div>
<div class="bango"> </div>
<div class="daimoku">［07］daßと直接法。</div>
<div class="mpage">69</div>
<div class="bango"> </div>
<div class="daimoku">［08］daßの代りにum zu或ひは単に不定法とzuを用ひることもあり。</div>
<div class="mpage">72</div>
<div class="bango"> </div>
<div class="daimoku">［09］事程左様に（daßのみ）（及びso daß）<br />規定的及び中間現象</div>
<div class="mpage">80</div>
<div class="bango"> </div>
<div class="daimoku">［10］規定的</div>
<div class="mpage">93</div>
<div class="bango"> </div>
<div class="daimoku">［11］0hne daß.</div>
<div class="mpage">98</div>
<div class="bango"> </div>
<div class="daimoku">［12］damit....（…するために言うが）挿入的</div>
<div class="mpage">99</div>
<div class="bango">25-12B</div>
<div class="daimoku">Daß dich die Pest!</div>
<div class="mpage">101</div>
<div class="bango">25-13B</div>
<div class="daimoku">挿入のdaß.</div>
<div class="mpage">102-108</div>
<div class="bango">25-14B</div>
<div class="daimoku">dasはdasなること。</div>
<div class="mpage">109-114</div>
<div class="bango">25-15B</div>
<div class="daimoku">nicht,daß....<u>nicht</u> …しなかったといふわけではないが、勿論…することはしたがね。（zwar....）</div>
<div class="mpage">115-122</div>
<div class="bango">25-16B</div>
<div class="daimoku">höchstens, daß....其他例外的のもの à peine si..</div>
<div class="mpage">123-128</div>
<div class="bango">25-17R</div>
<div class="daimoku"><u>nur daß</u>ただ……だけの<u>話</u>だ<br />vorausgesetzt, daß....<br />anstatt daß, statt daß.<br />（währendと同意にも用ふ）<br />編者注：このほか11件あり。</div>
<div class="mpage">129-141</div>
<div class="bango">25-18B</div>
<div class="daimoku">問投句的daß--!</div>
<div class="mpage">142-144</div>
<div class="bango">25-19B</div>
<div class="daimoku">副詞化するdaß----</div>
<div class="mpage">145-147</div>
<div class="bango">25-20B</div>
<div class="daimoku">Daß dich!［<u>Apokope</u>］</div>
<div class="mpage">148-149</div>
<div class="bango">25-21B</div>
<div class="daimoku"><u>adnominalのdaß</u></div>
<div class="mpage">150-152</div>
<div class="bango">25-22B</div>
<div class="daimoku">daß = 0hne daß. （quin的）</div>
<div class="mpage">153-165</div>
<div class="bango">25-23B</div>
<div class="daimoku">Quelque sotte, ma foi !<br />ich müßte ein Narrsein !</div>
<div class="mpage">166-174</div>
<div class="bango">25-24B</div>
<div class="daimoku">Quelque sotte !</div>
<div class="mpage">175</div>
<div class="bango">25-25B</div>
<div class="daimoku">移轍的現象としてのdassの特殊用法<br />同じことをもう一度言い直す型</div>
<div class="mpage">176-177</div>
<div class="bango">25-26B</div>
<div class="daimoku">daß ”と言って、とての意多し<br />主文章にdeswegen,darüber、前置詞をsubintellige</div>
<div class="mpage">178-184</div>
<div class="bango">25-27B</div>
<div class="daimoku">daß = ut,（damit）</div>
<div class="mpage">185-187</div>
<div class="bango">25-28B</div>
<div class="daimoku">daß［ut....=eret］ damit. …せんとして。<br />時称一致の問題。</div>
<div class="mpage">188-199</div>
<div class="bango">25-29R</div>
<div class="daimoku">daß es［nur so］eine Art hat.<br />daßの用ひ方のアイマイなもの<br />bis（普通の）<br />餘計なdaß bis daß bevor daß jenachdem daß<br />編者注：このほか6件あり。</div>
<div class="mpage">200-208</div>
<div class="bango">25-30B</div>
<div class="daimoku"> </div>
<div class="mpage">209-250</div>
<div class="bango"> </div>
<div class="daimoku">［01］-bis-</div>
<div class="mpage">209</div>
<div class="bango"> </div>
<div class="daimoku">［02］遂に。</div>
<div class="mpage">210</div>
<div class="bango"> </div>
<div class="daimoku">［03］um so mehr....da</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">［04］wennにも同じものあり …であるに拘らず</div>
<div class="mpage">225</div>
<div class="bango"> </div>
<div class="daimoku">［05］da=wo 関係的 （adnominal, adverbal）</div>
<div class="mpage">237</div>
<div class="bango"> </div>
<div class="daimoku">［06］wie....denn</div>
<div class="mpage">239</div>
<div class="bango"> </div>
<div class="daimoku">［07］wie.</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">［08］....であると同様に wie（sowie） 並立的</div>
<div class="mpage">250</div>
<div class="bango">25-31R</div>
<div class="daimoku">wie<br />関係詞様（adnominai）な<u>wie</u>, <u>so wie</u><br />wie billig = billigerweise<br />wieと同意のmaßen</div>
<div class="mpage">251-252</div>
<div class="bango">25-32B</div>
<div class="daimoku">wie Sie wollen. as you like it.</div>
<div class="mpage">253-256</div>
<div class="bango">25-33B</div>
<div class="daimoku">顛末と現状</div>
<div class="mpage">257-260</div>
<div class="bango">25-34R</div>
<div class="daimoku">現場のwie<br />wie = sowie …云々すると…（…である）<br />…云々するにつれて…</div>
<div class="mpage">261-267</div>
<div class="bango">25-35B</div>
<div class="daimoku">wie ich es bin, 等 （wie da sind....）</div>
<div class="mpage">268-275</div>
<div class="bango">25-36R</div>
<div class="daimoku">drive as he would<br /><u>Wie</u> dies <u>hier</u> der Fall ist</div>
<div class="mpage">276</div>
<div class="bango">25-37B</div>
<div class="daimoku">hungrig wie er war等</div>
<div class="mpage">277-286</div>
<div class="bango">25-38B</div>
<div class="daimoku">wie er gekommen war等</div>
<div class="mpage">287-293</div>
<div class="bango">25-39R</div>
<div class="daimoku">um zu in order to in oder that<br />仏 en vue de</div>
<div class="mpage">294-301</div>
<div class="bango">25-40B</div>
<div class="daimoku">［仏］ histoire de...</div>
<div class="mpage">302-303</div>
<div class="bango">25-41B</div>
<div class="daimoku">um</div>
<div class="mpage">304-305</div>
<div class="bango">25-42B</div>
<div class="daimoku">後続のum....zu</div>
<div class="mpage">306-311</div>
<div class="bango">25-43B</div>
<div class="daimoku">意外な結果ではないがやはり後続的意型<br />”云々して云々する″型</div>
<div class="mpage">312-319</div>
<div class="bango">25-44B</div>
<div class="daimoku"> </div>
<div class="mpage">320-392</div>
<div class="bango"> </div>
<div class="daimoku">［01］純粋に後続を指すum（直後を指す）</div>
<div class="mpage">320</div>
<div class="bango"> </div>
<div class="daimoku">［02］teleologische Auslegung.<br />云々「して」云々している（対照のum.）</div>
<div class="mpage">323</div>
<div class="bango"> </div>
<div class="daimoku">［03］「…であるとは」と言ふdaßと同じ用法</div>
<div class="mpage">329</div>
<div class="bango"> </div>
<div class="daimoku">［04］目的と結果との中間現象（皮肉が現れる）</div>
<div class="mpage">331</div>
<div class="bango"> </div>
<div class="daimoku">［05］weil</div>
<div class="mpage">333</div>
<div class="bango"> </div>
<div class="daimoku">［06］Warum! weil.</div>
<div class="mpage">363</div>
<div class="bango"> </div>
<div class="daimoku">［07］dennと同</div>
<div class="mpage">370</div>
<div class="bango"> </div>
<div class="daimoku">［08］weii=während（遅くならなぃぅちに…しておく）</div>
<div class="mpage">371</div>
<div class="bango"> </div>
<div class="daimoku">［09］Sintemal,其他古形一般</div>
<div class="mpage">376</div>
<div class="bango"> </div>
<div class="daimoku">［10］weil, puisque....（da....doch）</div>
<div class="mpage">381</div>
<div class="bango"> </div>
<div class="daimoku">［11］Bis.</div>
<div class="mpage">383</div>
<div class="bango"> </div>
<div class="daimoku">［12］規定的bis.</div>
<div class="mpage">384</div>
<div class="bango"> </div>
<div class="daimoku">［13］Solangel----bis----</div>
<div class="mpage">388</div>
<div class="bango"> </div>
<div class="daimoku">［14］文頭のbis</div>
<div class="mpage">390</div>
<div class="bango"> </div>
<div class="daimoku">［15］wenn</div>
<div class="mpage">391</div>
<div class="bango"> </div>
<div class="daimoku">［16］wann=als</div>
<div class="mpage">392</div>
<div class="bango">25-45R</div>
<div class="daimoku">wenn anders.</div>
<div class="mpage">393-396</div>
<div class="bango">25-46B</div>
<div class="daimoku">挿入的（um--zu）sc,［anders］<br /><u>wenn anders</u> = vorausgesetzt,<br />（andersは仏語のd'ailleursなる可し）<br />si elles sont bonnes d'ailleurs等</div>
<div class="mpage">397-399</div>
<div class="bango">25-47R</div>
<div class="daimoku">wenn=<u>daß</u> zu + 不定法<br />wenn（um zuの挿入句と同じ）<br />wenn=daß （dadurch....等と対する時は殊に明瞭）</div>
<div class="mpage">400-403</div>
<div class="bango">25-48B</div>
<div class="daimoku"> </div>
<div class="mpage">404-499</div>
<div class="bango"> </div>
<div class="daimoku">［01］殆んどdaß（zu+不定法）と同じ。<br />（事実を指すwennの順序が上下に変ったもの）</div>
<div class="mpage">404</div>
<div class="bango"> </div>
<div class="daimoku">［02］「もしも」と「wenn」と二つとも含む（一般的宣言）</div>
<div class="mpage">405</div>
<div class="bango"> </div>
<div class="daimoku">［03］sooft</div>
<div class="mpage">406</div>
<div class="bango"> </div>
<div class="daimoku">［04］wenn = Während, da doch</div>
<div class="mpage">407</div>
<div class="bango"> </div>
<div class="daimoku">［05］wenn（wannの代り）</div>
<div class="mpage">412</div>
<div class="bango"> </div>
<div class="daimoku">［06］nur dann, wenn.... erst dann, wenn</div>
<div class="mpage">413</div>
<div class="bango"> </div>
<div class="daimoku">［07］wenn....!</div>
<div class="mpage">414</div>
<div class="bango"> </div>
<div class="daimoku">［08］wennと省略文</div>
<div class="mpage">421</div>
<div class="bango"> </div>
<div class="daimoku">［09］<u>Während</u>. 時間的derweil<br />Währendとsolangeとの差</div>
<div class="mpage">422</div>
<div class="bango"> </div>
<div class="daimoku">［10］時間的と同時に対立的</div>
<div class="mpage">425</div>
<div class="bango"> </div>
<div class="daimoku">［11］純粋に論理的対立</div>
<div class="mpage">426</div>
<div class="bango"> </div>
<div class="daimoku">［12］殆ど0bgleich</div>
<div class="mpage">431</div>
<div class="bango"> </div>
<div class="daimoku">［13］Indem 同時性</div>
<div class="mpage">432</div>
<div class="bango"> </div>
<div class="daimoku">［14］相反的indem 同時と対比 aduersativ.</div>
<div class="mpage">436</div>
<div class="bango"> </div>
<div class="daimoku">［15］indem = weil</div>
<div class="mpage">437</div>
<div class="bango"> </div>
<div class="daimoku">［16］indem = dadurch, daß....</div>
<div class="mpage">440</div>
<div class="bango"> </div>
<div class="daimoku">［17］wie = sobald, sowie, als</div>
<div class="mpage">442</div>
<div class="bango"> </div>
<div class="daimoku">［18］［SO］WIE DU BIST.</div>
<div class="mpage">461</div>
<div class="bango"> </div>
<div class="daimoku">［19］wie</div>
<div class="mpage">471</div>
<div class="bango"> </div>
<div class="daimoku">［20］wie denn, ［überhaupt］</div>
<div class="mpage">474</div>
<div class="bango"> </div>
<div class="daimoku">［21］…の所謂る …する所によれば …する如くんば</div>
<div class="mpage">475</div>
<div class="bango"> </div>
<div class="daimoku">［22］Solange（alsの問題）</div>
<div class="mpage">485</div>
<div class="bango"> </div>
<div class="daimoku">［23］…せぬ問に（bevor） während, weil</div>
<div class="mpage">493</div>
<div class="bango"> </div>
<div class="daimoku">［24］Sooft（alsの問題あり）</div>
<div class="mpage">494</div>
<div class="bango"> </div>
<div class="daimoku">［25］soviel_（soweit）（…限り）</div>
<div class="mpage">499</div>
<div class="bango">25-49B</div>
<div class="daimoku">［英］directly = as soon as</div>
<div class="mpage">500</div>
<div class="bango">25-50B</div>
<div class="daimoku">sobald</div>
<div class="mpage">501-508</div>
<div class="bango">25-51R</div>
<div class="daimoku">Sobald（alsの問題あり）<br />So wie（sobald）<br />zumal</div>
<div class="mpage">509-514</div>
<div class="bango">25-52B</div>
<div class="daimoku"> </div>
<div class="mpage">515-638</div>
<div class="bango"> </div>
<div class="daimoku">［01］zumal</div>
<div class="mpage">515</div>
<div class="bango"> </div>
<div class="daimoku">［02］falls</div>
<div class="mpage">517</div>
<div class="bango"> </div>
<div class="daimoku">［03］im fall（für den Fall, <u>daß</u>....）</div>
<div class="mpage">518</div>
<div class="bango"> </div>
<div class="daimoku">［04］nun</div>
<div class="mpage">524</div>
<div class="bango"> </div>
<div class="daimoku">［05］Seit（時称）</div>
<div class="mpage">532</div>
<div class="bango"> </div>
<div class="daimoku">［06］Trotzdem</div>
<div class="mpage">532</div>
<div class="bango"> </div>
<div class="daimoku">［07］Seitdem</div>
<div class="mpage">636</div>
<div class="bango"> </div>
<div class="daimoku">［08］nachdem nunと同じ（…したる今日）<br />（したる以上は）</div>
<div class="mpage">538</div>
<div class="bango"> </div>
<div class="daimoku">［09］nachdem</div>
<div class="mpage">542</div>
<div class="bango"> </div>
<div class="daimoku">［10］<u>je nachdem</u>（単にnachdemもあり）</div>
<div class="mpage">543</div>
<div class="bango"> </div>
<div class="daimoku">［11jehe（及びehe noch, before even, avant même）</div>
<div class="mpage">547</div>
<div class="bango"> </div>
<div class="daimoku">［12］sowie（種々）</div>
<div class="mpage">551</div>
<div class="bango"> </div>
<div class="daimoku">［13］bevor</div>
<div class="mpage">552</div>
<div class="bango"> </div>
<div class="daimoku">［14］<u>sofern, sowei</u>t, ［Aanminalな場合あり！］</div>
<div class="mpage">557</div>
<div class="bango"> </div>
<div class="daimoku">［15］soweit, soviel, sofern wofern</div>
<div class="mpage">558</div>
<div class="bango"> </div>
<div class="daimoku">［16］sowet（制限ならざるもの）</div>
<div class="mpage">564</div>
<div class="bango"> </div>
<div class="daimoku">［17］insofern, inwiefern.</div>
<div class="mpage">565</div>
<div class="bango"> </div>
<div class="daimoku">［18］sofern = wenn.</div>
<div class="mpage">569</div>
<div class="bango"> </div>
<div class="daimoku">［19］insoweit</div>
<div class="mpage">570</div>
<div class="bango"> </div>
<div class="daimoku">［20］statt, anstatt. <u>statt daß</u></div>
<div class="mpage">571</div>
<div class="bango"> </div>
<div class="daimoku">［21］挿入文的になる。（まだ多少umの元意で通ずる際）</div>
<div class="mpage">574</div>
<div class="bango"> </div>
<div class="daimoku">［22］…するとすれぱ</div>
<div class="mpage">574</div>
<div class="bango"> </div>
<div class="daimoku">［23］zu....um, genug....um.</div>
<div class="mpage">575</div>
<div class="bango"> </div>
<div class="daimoku">［24］…するほどに、（adverbal）<br />…するほどの、（adnominal）（程度を指す）</div>
<div class="mpage">576</div>
<div class="bango"> </div>
<div class="daimoku">［25］<u>w o</u> 空間的 wo----da....</div>
<div class="mpage">576</div>
<div class="bango"> </div>
<div class="daimoku">［26］関係代名詞としてのwo<br />名詞にかかるwoとその結合（worin, worauf, etc.）</div>
<div class="mpage">577</div>
<div class="bango"> </div>
<div class="daimoku">［27］空間的よりはむしろ場合、時（wenn）</div>
<div class="mpage">578</div>
<div class="bango"> </div>
<div class="daimoku">［28］wo, wo doch=da doch</div>
<div class="mpage">585</div>
<div class="bango"> </div>
<div class="daimoku">［29］so = wenn so Gott will</div>
<div class="mpage">589</div>
<div class="bango"> </div>
<div class="daimoku">［30］so = wie</div>
<div class="mpage">590</div>
<div class="bango"> </div>
<div class="daimoku">［31］ohne</div>
<div class="mpage">591</div>
<div class="bango"> </div>
<div class="daimoku">［32］ohne zu, ohne daß 普通の。（現在と）</div>
<div class="mpage">592</div>
<div class="bango"> </div>
<div class="daimoku">［33］挿入的［別に…云々しようといふ譯ではないが］</div>
<div class="mpage">598</div>
<div class="bango"> </div>
<div class="daimoku">［34］ohne（daß）相反的「しかも」云々、<br />「…としても、…しない」<br />「必ずしも云々といふのでないにしても」</div>
<div class="mpage">599</div>
<div class="bango"> </div>
<div class="daimoku">［35］damit 1.<u>sodaß</u>を以ても表現し得ることあり<br />2.単にdaß→ 3.auf daß→</div>
<div class="mpage">605</div>
<div class="bango"> </div>
<div class="daimoku">［36］挿入のdamit daßにも同意型あり！</div>
<div class="mpage">616</div>
<div class="bango"> </div>
<div class="daimoku">［37］Als 普通のals（過去） 英 as 多し</div>
<div class="mpage">617</div>
<div class="bango"> </div>
<div class="daimoku">［38］alsと現在 （historical presence）</div>
<div class="mpage">623</div>
<div class="bango"> </div>
<div class="daimoku">［39］als（後続的）</div>
<div class="mpage">624</div>
<div class="bango"> </div>
<div class="daimoku">［40］als=wie（zum Beispiel, etwa.）</div>
<div class="mpage">625</div>
<div class="bango"> </div>
<div class="daimoku">［41］in dem Grade....als. umso～als....<br />insofern als, umsomehr als等のals</div>
<div class="mpage">632</div>
<div class="bango"> </div>
<div class="daimoku">［42］<u>auf daß</u> 目的 ［英］in order that</div>
<div class="mpage">638</div>
<div class="bango">25-53R</div>
<div class="daimoku">widrigenfalls等<br />aufdass</div>
<div class="mpage">639-543</div>
<div class="bango">25-54B</div>
<div class="daimoku">Adnominalな<u>als ob</u></div>
<div class="mpage">644-647</div>
<div class="bango">25-55B</div>
<div class="daimoku">wie, wenn...!</div>
<div class="mpage">648</div>
<div class="bango">25-56B</div>
<div class="daimoku"><u>unerachtet</u>, <u>ungeachtet</u>.</div>
<div class="mpage">649</div>
<div class="bango">25-57B</div>
<div class="daimoku">obの独立文章</div>
<div class="mpage">650-653</div>
<div class="bango">25-58R</div>
<div class="daimoku">obの史的関係 ob = wenn<br />wie （als） soie<br />wie....denn<br />dieweil, derweil.<br />demzufolge<br />wie（云々すると…） 云々するや否や<br />編者注：このほか7件あり。</div>
<div class="mpage">654-667</div>
<div class="bango">25-59B</div>
<div class="daimoku">ob［普通の場合］</div>
<div class="mpage">668-672</div>
<div class="bango">25-60B</div>
<div class="daimoku">［古］maßen wie....denn....と同様に<br />（simplizに多し）</div>
<div class="mpage">673</div>
<div class="bango">25-61B</div>
<div class="daimoku">云々するにつれて =je nachdem.（云々次第で）<br />云々するに従って （wie es kommt）</div>
<div class="mpage">674-676</div>
<div class="bango"> </div>
<div class="daimoku">波にゆらるるままに</div>
<div class="mpage"> </div>
<div class="bango">25-62B</div>
<div class="daimoku">daher</div>
<div class="mpage">677</div>
<div class="bango">25-63R</div>
<div class="daimoku">wie（どうしたら云々できるかと……くろうする、など）</div>
<div class="mpage">678-679</div>
<div class="bango">25-64B</div>
<div class="daimoku">adverbalなる現場描写的 wie appositiv.</div>
<div class="mpage">680</div>
</div>