<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">27-1B</div>
<div class="daimoku">damitかmit ihrか</div>
<div class="mpage">1-2</div>
<div class="bango">27-2R</div>
<div class="daimoku">尊称の代名詞としてのDieselbe（n）<br />Höchst=dieselben等<br />［Das］複数的観念を考へる如く思われる時<br />（beid<u>e</u>s）等の用法と同じ<br />allerhand（=Alleriei） 名詞的にも附加的にも<br />Mein Rat is <u>der</u> （Das ist mein Rat.）<br /><u>dieser</u></div>
<div class="mpage">3-4</div>
<div class="bango"> </div>
<div class="daimoku"> </div>
<div class="mpage"> </div>
<div class="bango">27-3B</div>
<div class="daimoku">der derとかdie dieとかの重複する場合</div>
<div class="mpage">5</div>
<div class="bango">27-4R</div>
<div class="daimoku">［英］<u>that</u> intended = <u>What</u> was intended<br />damit等は「者」型名詞（人・生物）に用いない<br />その例外［MHD］</div>
<div class="mpage">6</div>
<div class="bango">27-5B</div>
<div class="daimoku"><u>That</u> long 限度のsoと同</div>
<div class="mpage">7-9</div>
<div class="bango">27-6B</div>
<div class="daimoku"><u>Im</u> Kaffee sit Zucker <u>dr土n</u>.</div>
<div class="mpage">10-11</div>
<div class="bango">27-7B</div>
<div class="daimoku">das（雑）</div>
<div class="mpage">12-26</div>
<div class="bango">27-8B</div>
<div class="daimoku"><u>Darein</u>を用ひる動詞</div>
<div class="mpage">27-28</div>
<div class="bango">27-9B</div>
<div class="daimoku">先行代名詞darüber等の省略</div>
<div class="mpage">29-40</div>
<div class="bango">27-10B</div>
<div class="daimoku">［MHD］iht aught</div>
<div class="mpage">41-49</div>
<div class="bango">27-11B</div>
<div class="daimoku">uunsereiner unsereins</div>
<div class="mpage">50-52</div>
<div class="bango">27-12B</div>
<div class="daimoku">「左様な」の諸型</div>
<div class="mpage">53-59</div>
<div class="bango">27-13B</div>
<div class="daimoku">desgleichen</div>
<div class="mpage"> </div>
<div class="bango">27-14B</div>
<div class="daimoku">dessenの用法［及びdes］<br />1.Es gibt <u>deren</u>, die....<br />2.仏の<u>en</u>, 伊のne</div>
<div class="mpage">64-69</div>
<div class="bango">27-15B</div>
<div class="daimoku">不定数詞 viel, mehr, nichts等々</div>
<div class="mpage">70-72</div>
<div class="bango">27-16R</div>
<div class="daimoku">gewißく或種の）<br />die andern（他人）<br />定冠詞と共に用ひた異例。</div>
<div class="mpage">73-74</div>
<div class="bango">27-17B</div>
<div class="daimoku">（A）いづれも each 二者中の<br />（B）いづれか eiher</div>
<div class="mpage">75-81</div>
<div class="bango">27-18R</div>
<div class="daimoku"><u>Einer</u> muß weichen. ［<u>どちらか</u>....］<br />dessen, eines, keines等を含む二格の重畳<br />誰かeiner不定詞。と規定詞、句。<br />［一方は、他は］einer, der andere, der eine, <br />der andere, einer, ein anderer<br />数詞としての<u>eines 二格</u><br />nichtは<u>nichts</u>なること（名詞的であること）</div>
<div class="mpage">82-86</div>
<div class="bango"> </div>
<div class="daimoku">hoch<u>dero</u>, höchst<u>dero</u>などについて</div>
<div class="mpage"> </div>
<div class="bango">27-19B</div>
<div class="daimoku">derjenigeの諸形態</div>
<div class="mpage">87-110</div>
<div class="bango">27-20B</div>
<div class="daimoku">編者注：本袋「27-20B」内は二つのノー卜ブックに整理されているので、これを記号①、②で示すことにした。</div>
<div class="mpage">111-358</div>
<div class="bango"> </div>
<div class="daimoku">指示代名詞其他</div>
<div class="mpage">114</div>
<div class="bango"> </div>
<div class="daimoku">①［01］der erstere, der letztere. Dieser, jener</div>
<div class="mpage">114</div>
<div class="bango"> </div>
<div class="daimoku">①［02］da=と前置詞の結合。（dahin, daherも）</div>
<div class="mpage">131</div>
<div class="bango"> </div>
<div class="daimoku">①［03］der, die, das（指示代名詞）</div>
<div class="mpage">132</div>
<div class="bango"> </div>
<div class="daimoku">①［04］der 指示「形容」詞</div>
<div class="mpage">149</div>
<div class="bango"> </div>
<div class="daimoku">①［05］eben=との結合（ebendaselbst等）</div>
<div class="mpage">155</div>
<div class="bango"> </div>
<div class="daimoku">①［06］einer, keiner［solcheの意］<br />関係句を伴ひ得ること。</div>
<div class="mpage">156</div>
<div class="bango"> </div>
<div class="daimoku">①［07］der...”の”「それ」。（規定を伴ふ場合）</div>
<div class="mpage">164</div>
<div class="bango"> </div>
<div class="daimoku">①［08］solcher（関係文を（伴ふ）（二格規定）</div>
<div class="mpage">165</div>
<div class="bango"> </div>
<div class="daimoku">①［09］関係代名詞代り。（の如きもの）der, die, das</div>
<div class="mpage">167</div>
<div class="bango"> </div>
<div class="daimoku">①［10］<u>solch</u>=「…なぞといふもの」（意味に注意）</div>
<div class="mpage">168</div>
<div class="bango"> </div>
<div class="daimoku">①［11］alle, alle beide, alle <u>zusammen</u><br /><u>samt und sonders</u><br />等の副詞的用法。（述語句なり）</div>
<div class="mpage">171</div>
<div class="bango"> </div>
<div class="daimoku">①［12］anderer, vieler等の複数二格の用法。</div>
<div class="mpage">174</div>
<div class="bango"> </div>
<div class="daimoku">①［13］dabei, damit等の Tmesis?</div>
<div class="mpage">174</div>
<div class="bango"> </div>
<div class="daimoku">①［14］alles Gute等。（形容詞）</div>
<div class="mpage">174</div>
<div class="bango"> </div>
<div class="daimoku">①［15］中性を人に用ひる例。（jedes, alles, keines）<br />was, das, eines</div>
<div class="mpage">175</div>
<div class="bango"> </div>
<div class="daimoku">①［16］［derer］”der”形（物に関して）</div>
<div class="mpage">180</div>
<div class="bango"> </div>
<div class="daimoku">①［17］dieserのemplatischな用法。<br />（selcheにもあり）</div>
<div class="mpage">188</div>
<div class="bango"> </div>
<div class="daimoku">①［18］或者は、或者は。［der］, eine, der andere; der, der;</div>
<div class="mpage">194</div>
<div class="bango"> </div>
<div class="daimoku">①［19］無選択なる指示。省略的指示<br />der und der u.s.w dieser und jener.</div>
<div class="mpage">196</div>
<div class="bango"> </div>
<div class="daimoku">①［20］deinesgleichen etc.</div>
<div class="mpage">215</div>
<div class="bango"> </div>
<div class="daimoku">①［21］derjenige</div>
<div class="mpage">216</div>
<div class="bango"> </div>
<div class="daimoku">①［22］derselbe（derselbige.）同じ<br />（関係代名詞の構文）</div>
<div class="mpage">217</div>
<div class="bango"> </div>
<div class="daimoku">①［23］dar=Prep.を用ひず<u>das</u>, <u>dessen</u>を用ひること</div>
<div class="mpage">323</div>
<div class="bango"> </div>
<div class="daimoku">①［24］andersの補足（<u>sonst</u>）kein anderer</div>
<div class="mpage">224</div>
<div class="bango"> </div>
<div class="daimoku">①［29］als solcher. adnominalとadverbal.</div>
<div class="mpage">288</div>
<div class="bango"> </div>
<div class="daimoku">①［30］［daß］等の前の<u>da</u>=von等の省略。</div>
<div class="mpage">298</div>
<div class="bango"> </div>
<div class="daimoku">①［31］……する「人の如き」（einer, jemand, 等）</div>
<div class="mpage">299</div>
<div class="bango"> </div>
<div class="daimoku">①［32］solcherの「指示的」用法。</div>
<div class="mpage">305</div>
<div class="bango"> </div>
<div class="daimoku">①［33］<u>ein und derselbe</u>.</div>
<div class="mpage">311</div>
<div class="bango"> </div>
<div class="daimoku">①［34］Wer.</div>
<div class="mpage">318</div>
<div class="bango"> </div>
<div class="daimoku">①［35］<u>eines</u>（男女の中の一人をさす）片一方</div>
<div class="mpage">319</div>
<div class="bango"> </div>
<div class="daimoku">不定代名詞</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">②［01］alles</div>
<div class="mpage">323</div>
<div class="bango"> </div>
<div class="daimoku">②［02］ander（nominal）</div>
<div class="mpage">326</div>
<div class="bango"> </div>
<div class="daimoku">②［03］alle=（dieser, jener, derの前で無語尾）</div>
<div class="mpage">327</div>
<div class="bango"> </div>
<div class="daimoku">②［04］mehr als einer等（一にして止まらず）</div>
<div class="mpage">333</div>
<div class="bango"> </div>
<div class="daimoku">②［05］dergleichen.（動詞は単?）（adnominal nominal）</div>
<div class="mpage">333</div>
<div class="bango"> </div>
<div class="daimoku">②［06］etwas, was.</div>
<div class="mpage">334</div>
<div class="bango"> </div>
<div class="daimoku">②［07］etwas, was.</div>
<div class="mpage">336</div>
<div class="bango"> </div>
<div class="daimoku">②［08］all=を単数と共に用ひる際 二つの場合あり。（gannz....とjeder）</div>
<div class="mpage">337</div>
<div class="bango"> </div>
<div class="daimoku">②［09］all=と単数</div>
<div class="mpage">338</div>
<div class="bango"> </div>
<div class="daimoku">②［10］稀なる。<u>das</u>の三格（事柄を指す。）</div>
<div class="mpage">339</div>
<div class="bango"> </div>
<div class="daimoku">②［11］dasの二格dessen.（事柄を受ける）<u>was</u>あるものとなきものと。</div>
<div class="mpage">346</div>
<div class="bango"> </div>
<div class="daimoku">②［12］<u>das</u>の一格四格。</div>
<div class="mpage">348</div>
<div class="bango"> </div>
<div class="daimoku">②［13］alle（副詞的位置）主語の述語又は四格の述語</div>
<div class="mpage">349</div>
<div class="bango"> </div>
<div class="daimoku">②［14］<u>einer</u> der----.</div>
<div class="mpage">353</div>
<div class="bango"> </div>
<div class="daimoku">②［15］ein....ander....［相互的ならざる］名詞的と附加語的</div>
<div class="mpage">354</div>
<div class="bango"> </div>
<div class="daimoku">②［16］alles, （名詞的）wenig, manches, dies, das, etwas, viel</div>
<div class="mpage">356</div>
<div class="bango"> </div>
<div class="daimoku">②［17］alleの後置</div>
<div class="mpage">357</div>
<div class="bango"> </div>
<div class="daimoku">②［18］alsの次の指示代名詞の省略。</div>
<div class="mpage">358</div>
<div class="bango">27-21B</div>
<div class="daimoku">強調用alle及び：jeder <u>in aller Stille</u></div>
<div class="mpage">359-375</div>
<div class="bango">27-22B</div>
<div class="daimoku">ander=</div>
<div class="mpage">376-414</div>
<div class="bango">27-28B</div>
<div class="daimoku">davonの代りにda....von</div>
<div class="mpage">453-462</div>
<div class="bango">27-29B</div>
<div class="daimoku">名詞的用法の複数二格（単数も）aller, vieier, usw. einiger usw. dieses, jenes usw.</div>
<div class="mpage">463-470</div>
<div class="bango">27-30B</div>
<div class="daimoku">das Ganze.（指示詞的）及び"das alles"</div>
<div class="mpage">471-478</div>
<div class="bango">27-31B</div>
<div class="daimoku">dessentwillen, dieserhalb等　形態の問題</div>
<div class="mpage">479-483</div>
<div class="bango">27-32B</div>
<div class="daimoku">［MHD］にはまだ中性の複数があった：diu</div>
<div class="mpage">484</div>
<div class="bango">27-33B</div>
<div class="daimoku"><u>Beides</u>及び関係諸項</div>
<div class="mpage">485-490</div>
<div class="bango">27-34R</div>
<div class="daimoku">無語尾の<u>viel</u>,<u>wenig</u><br /><u>alles und jedes</u><br />［特］alles, was<br /><u>全称の表現</u></div>
<div class="mpage">491-493</div>
<div class="bango">27-35B</div>
<div class="daimoku">welchesの代名詞用法</div>
<div class="mpage">494-498</div>
<div class="bango">27-36B</div>
<div class="daimoku">編者注：本袋「27-36B」内は普通の資料番号、（1）, （2）…により整理されているが、（5）, （6）だけがノー卜ブック形式に整理されているので、この部分だけは（5）［01］（6）［01］等として示すことにした。
<p> </p>
<p>各々の概念 jeder語考</p>
</div>
<div class="mpage">499-576</div>
<div class="bango"> </div>
<div class="daimoku">（1）everyとeach</div>
<div class="mpage">501</div>
<div class="bango"> </div>
<div class="daimoku">（2）bini,singuli</div>
<div class="mpage">503</div>
<div class="bango"> </div>
<div class="daimoku">（3）一切の、いかなる、どんな（jeder,alle）</div>
<div class="mpage">503</div>
<div class="bango"> </div>
<div class="daimoku">（4）［仏］tout le monde</div>
<div class="mpage">503</div>
<div class="bango"> </div>
<div class="daimoku">（5）「各々」といふ概念</div>
<div class="mpage">505</div>
<div class="bango"> </div>
<div class="daimoku">（5）［01］je 各々、毎</div>
<div class="mpage">505</div>
<div class="bango"> </div>
<div class="daimoku">（5）［02］jeder（附加的）</div>
<div class="mpage">506</div>
<div class="bango"> </div>
<div class="daimoku">（5）［03］je nachdem.</div>
<div class="mpage">508</div>
<div class="bango"> </div>
<div class="daimoku">（5）［04］alle</div>
<div class="mpage">509</div>
<div class="bango"> </div>
<div class="daimoku">（5）［05］auf=<u>einander</u>等</div>
<div class="mpage">511</div>
<div class="bango"> </div>
<div class="daimoku">（5）［06］ein....den andern［名詞が一方］</div>
<div class="mpage">516</div>
<div class="bango"> </div>
<div class="daimoku">（5）［07］einander</div>
<div class="mpage">520</div>
<div class="bango"> </div>
<div class="daimoku">（5）［08］jeder dritte<br />alle</div>
<div class="mpage">522</div>
<div class="bango"> </div>
<div class="daimoku">（6）［02］einer....dem andern（及び前置詞）</div>
<div class="mpage">546</div>
<div class="bango"> </div>
<div class="daimoku">（6）［03］<u>der</u> eine....den andern（及前置詞）<br />及びeiner den andern</div>
<div class="mpage">551</div>
<div class="bango"> </div>
<div class="daimoku">（6）［04jeinender, .....miteinander.</div>
<div class="mpage">557</div>
<div class="bango"> </div>
<div class="daimoku">（6）［05］名詞の重畳</div>
<div class="mpage">560</div>
<div class="bango"> </div>
<div class="daimoku">（6）［06］sich, euch, uns.再帰動詞</div>
<div class="mpage">562</div>
<div class="bango"> </div>
<div class="daimoku">（6）［07］jederを使って<u>複数</u></div>
<div class="mpage">565</div>
<div class="bango"> </div>
<div class="daimoku">（6）［08］alles und jedes</div>
<div class="mpage">567</div>
<div class="bango"> </div>
<div class="daimoku">（6）［09］einer und der andere（etlicheの意に）<br /><u>der und der</u>（irgendwelchの意）</div>
<div class="mpage">568</div>
<div class="bango"> </div>
<div class="daimoku">（6）［10］どれも同じの意<br />（so....wie....又は比較級）</div>
<div class="mpage">570</div>
<div class="bango"> </div>
<div class="daimoku">（6）［11］von Mund zu Mund ロ々に</div>
<div class="mpage">573</div>
<div class="bango"> </div>
<div class="daimoku">（6）［12］<u>man</u>----sich 其の他、単数形の場合</div>
<div class="mpage">576</div>
<div class="bango">27-37B</div>
<div class="daimoku">指示の助詞</div>
<div class="mpage">577-581</div>
<div class="bango">27-38B</div>
<div class="daimoku"><u>普通の指示代名詞</u></div>
<div class="mpage">582-585</div>
<div class="bango">27-39B</div>
<div class="daimoku">ganze Schiffe</div>
<div class="mpage">586-594</div>
<div class="bango">27-40B</div>
<div class="daimoku">間投的 Nun sage mir noch <u>einer</u>---!</div>
<div class="mpage">595-599</div>
<div class="bango">27-41B</div>
<div class="daimoku">jederの一用法（少しでも…すると忽ち）</div>
<div class="mpage">600</div>
<div class="bango">27-42B</div>
<div class="daimoku">省けぬdarin, davon其の他</div>
<div class="mpage">601-606</div>
<div class="bango">27-43B</div>
<div class="daimoku">darinの代りにin <u>ihm</u></div>
<div class="mpage">607-613</div>
<div class="bango">27-44B</div>
<div class="daimoku">jemand<u>em</u>（niemandと同じ問題）<br />jemandemの複数形の如き感じを与えるが、実は<br />単（DATIVの時）</div>
<div class="mpage">614-616</div>
<div class="bango">27-45B</div>
<div class="daimoku">或者は……或者は… 及び”一方が他を”（複のみ扱ふ） Die einen ....die andern</div>
<div class="mpage">617-623</div>
<div class="bango">27-46B</div>
<div class="daimoku">Das war</div>
<div class="mpage">624</div>
<div class="bango">27-47R</div>
<div class="daimoku">［仏］のen 人間にも用ひる：</div>
<div class="mpage">625-632</div>
<div class="bango">27-48B</div>
<div class="daimoku">広義の指示詞は語順に於て形容詞の前に置かれる</div>
<div class="mpage">633</div>
<div class="bango">27-49R</div>
<div class="daimoku">英仏に不要な<u>darauf</u>, ～の構造<br />jed<u>es</u> solch<u>es</u><br />事柄を指す各種の［中性］代名詞</div>
<div class="mpage">634-637</div>
<div class="bango">27-51R</div>
<div class="daimoku">viel<u>en</u> Kummer<br />etwesとwas<br />名詞的 dasjenige, wes....<br />重要見地：定概念と不定概念<br />［羅］iste（指示力お参考として）<br />［仏］toutとtoute<br />ein, keinは男一格；中一四格で（名詞省略では）<br />必ず強語尾を附す：<br />［英］alles= everything</div>
<div class="mpage">641-645</div>
<div class="bango">27-52B</div>
<div class="daimoku">これ、それ、あれ 基本事項</div>
<div class="mpage">646-648</div>
<div class="bango">27-53R</div>
<div class="daimoku">単なる辞令としてのalle<br />mehrere, plusieurs, several<br />und dergleichen<br />einzig, einig等の意味<br />keinerの二格 <u>keines</u><br />dergleichen, nichts, etwas等に起って来る二格形の問題。<br />solcherの形容詞扱ひ。 ein solcher, kein solcher<br />darinと<u>in dem</u><br />普通の場合 jemand, niemand<br />jemand anders?<br />manchermann<br />derjenige=Teufelの意</div>
<div class="mpage">649-656</div>
<div class="bango">27-54B</div>
<div class="daimoku">Die halbe Stadt. Die ganze Stadt.</div>
<div class="mpage">657</div>
<div class="bango">27-55R</div>
<div class="daimoku">場所を指す際には<u>von wo</u>, <u>von da</u>を用ひる。<br />（woven, devenに非ず!）</div>
<div class="mpage">658</div>
<div class="bango">27-56B</div>
<div class="daimoku">The lady <u>in question</u></div>
<div class="mpage">659</div>
</div>