<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">35-1B</div>
<div class="daimoku">編者注：本袋「35-1B」内は資科数<br />が多いのて資科番号、（1）,（2）<br />…に対応した目次を付けてある。</div>
<div class="mpage">1-177</div>
<div class="bango"> </div>
<div class="daimoku">述語句</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">（1）Genitivus absolutus</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">（2）［seiend形態］省略文的 bei offenem Fenster.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">（3）成句的なるもの eingerechnet....</div>
<div class="mpage">32</div>
<div class="bango"> </div>
<div class="daimoku">（4）述語句の自由描写的タイプ<br />Appositive, Supplementativ</div>
<div class="mpage">44</div>
<div class="bango"> </div>
<div class="daimoku">（5）仮定的、挿入的なものは分ける可し。</div>
<div class="mpage">51</div>
<div class="bango"> </div>
<div class="daimoku">（6）Zwanzig Männer verbunden, 等の句</div>
<div class="mpage">55</div>
<div class="bango"> </div>
<div class="daimoku">（7）Partizipium Präs. statt eines ganzen Satzes.</div>
<div class="mpage">58</div>
<div class="bango"> </div>
<div class="daimoku">（8）<u>mit</u> meinem Willen（=me volente）</div>
<div class="mpage">70</div>
<div class="bango"> </div>
<div class="daimoku">（9）Adnominalな熟語句</div>
<div class="mpage">71</div>
<div class="bango"> </div>
<div class="daimoku">（10）<u>コンマの問題</u> 仏では副詞化するので省くこと<br />が多い</div>
<div class="mpage">82</div>
<div class="bango"> </div>
<div class="daimoku">（11）一格、四格主語と現在分詞の句。</div>
<div class="mpage">82</div>
<div class="bango"> </div>
<div class="daimoku">（12）省略主文に附く熟語句</div>
<div class="mpage">83</div>
<div class="bango"> </div>
<div class="daimoku">（13）einmal:</div>
<div class="mpage">87</div>
<div class="bango"> </div>
<div class="daimoku">（14）前置詞附一文肢の如くにして実は熟語句なるもの</div>
<div class="mpage">87</div>
<div class="bango"> </div>
<div class="daimoku">（15）－語順－ 述語句に於ける基語を前に置く</div>
<div class="mpage">88</div>
<div class="bango"> </div>
<div class="daimoku">（16）仏：現在分詞の「形容詞性」は女性の際に明瞭：<br />Palpitant<u>e</u></div>
<div class="mpage">90</div>
<div class="bango"> </div>
<div class="daimoku">（17）非人称主語文（又はes）と述語句。</div>
<div class="mpage">91</div>
<div class="bango"> </div>
<div class="daimoku">（18）短かい熟語句</div>
<div class="mpage">92</div>
<div class="bango"> </div>
<div class="daimoku">（19）其の他の熟語句的文肢</div>
<div class="mpage">93</div>
<div class="bango"> </div>
<div class="daimoku">（20）四格と過去分詞及び0省略句。</div>
<div class="mpage">94</div>
<div class="bango"> </div>
<div class="daimoku">（21）迅速なる描写の過去分詞</div>
<div class="mpage">96</div>
<div class="bango"> </div>
<div class="daimoku">（22）述語の前にobgleich等基礎的要素を附するもの</div>
<div class="mpage">96</div>
<div class="bango"> </div>
<div class="daimoku">（23）熟語句総論（参考）</div>
<div class="mpage">97</div>
<div class="bango"> </div>
<div class="daimoku">（24）現在分詞句の特殊用法：－左手を眺むれば、等－</div>
<div class="mpage">97</div>
<div class="bango"> </div>
<div class="daimoku">（25）Kommaなしに附ける簡単な熟語句</div>
<div class="mpage">98</div>
<div class="bango"> </div>
<div class="daimoku">（26）habend, seiend, sollend等を実際入れた例</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">（27）書簡の終句と現在分詞句</div>
<div class="mpage">99</div>
<div class="bango"> </div>
<div class="daimoku">（28）受働的語法の場合</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">（29）熟語句の位置に関係代名詞文を用ふ</div>
<div class="mpage">100</div>
<div class="bango"> </div>
<div class="daimoku">（30）so schwatzend und malend verging die Zeit</div>
<div class="mpage">101</div>
<div class="bango"> </div>
<div class="daimoku">（31）述語句</div>
<div class="mpage">102</div>
<div class="bango"> </div>
<div class="daimoku">（32）拉丁語の現在分詞句（格変化する実例）</div>
<div class="mpage">102</div>
<div class="bango"> </div>
<div class="daimoku">（33）述語句一般の説明に必要なもの。</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">（34）tragennd形態（省略形）</div>
<div class="mpage">103</div>
<div class="bango"> </div>
<div class="daimoku">（35）附加語的述語を名詞の前に置く例。</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">（36）省略述語句と見られるもの。 Aug in Auge.</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">（37）簡単な過去分詞（特）</div>
<div class="mpage">104</div>
<div class="bango"> </div>
<div class="daimoku">（38）英仏語の述語句 having,being. ce disant.</div>
<div class="mpage">105</div>
<div class="bango"> </div>
<div class="daimoku">（39）habend形態（省略形）</div>
<div class="mpage">116</div>
<div class="bango"> </div>
<div class="daimoku">（40）［英］thoughや、whenと省略語句</div>
<div class="mpage">120</div>
<div class="bango"> </div>
<div class="daimoku">（41）予備部（あらゆる形態を含む）</div>
<div class="mpage">120</div>
<div class="bango"> </div>
<div class="daimoku">（42）稀な非人称動詞の分詞句</div>
<div class="mpage">121</div>
<div class="bango"> </div>
<div class="daimoku">（43）意味形態の上から見た述語句の分類</div>
<div class="mpage">122</div>
<div class="bango"> </div>
<div class="daimoku">（44）現在分詞を基礎とするもの</div>
<div class="mpage">125</div>
<div class="bango"> </div>
<div class="daimoku">（45）過去分詞を基礎に</div>
<div class="mpage">135</div>
<div class="bango"> </div>
<div class="daimoku">（46）述語句、einmal.... sobald...</div>
<div class="mpage">141</div>
<div class="bango"> </div>
<div class="daimoku">（47）Dies geschehen. cela fait.</div>
<div class="mpage">142</div>
<div class="bango"> </div>
<div class="daimoku">（48）［英］述語句が前置詞を伴う場合<br />Upon the door being opend（扉が開くと）</div>
<div class="mpage">143</div>
<div class="bango"> </div>
<div class="daimoku">（49）因由的</div>
<div class="mpage">144</div>
<div class="bango"> </div>
<div class="daimoku">（50）述語名詞（即ちApposition）</div>
<div class="mpage">145</div>
<div class="bango"> </div>
<div class="daimoku">（51）GerundかAbsolutiveか 連続體</div>
<div class="mpage">148</div>
<div class="bango"> </div>
<div class="daimoku">（52）形容詞を基礎とするもの</div>
<div class="mpage">154</div>
<div class="bango"> </div>
<div class="daimoku">（53）荘重なる現在分詞の使用例</div>
<div class="mpage">157</div>
<div class="bango"> </div>
<div class="daimoku">（54）未来分詞を基礎とするもの</div>
<div class="mpage">157</div>
<div class="bango"> </div>
<div class="daimoku">（55）一格以外を主語とする述語句</div>
<div class="mpage">160</div>
<div class="bango">35-2R</div>
<div class="daimoku">Adnominal用法ある前置詞の諸型は、seinを介して、<br />其の侭adverbal用法に移し得<br />MET0NYMIE<br />up to,in on,in for等の結合<br />［仏］loin,bien,mal等 副詞述語に<br />［仏］debout<br />大範疇をなすPrädicativ paradoxiae causaの一般例</div>
<div class="mpage">178-181</div>
<div class="bango">35-3B</div>
<div class="daimoku">編者注：本袋「35-3B」内は資料数<br />が多いので、資料番号、<br />（1）,（2）<br />…に対応した目次を付けてある。<br />…を…と 及びzu,seinをも</div>
<div class="mpage">182-267</div>
<div class="bango"> </div>
<div class="daimoku">（1）「を…と」型</div>
<div class="mpage">183</div>
<div class="bango"> </div>
<div class="daimoku">（2）独の場合（als,fürを介せざる結合）</div>
<div class="mpage">184</div>
<div class="bango"> </div>
<div class="daimoku">（3）Er glaubt <u>mich</u> <u>tot</u>.</div>
<div class="mpage">186</div>
<div class="bango"> </div>
<div class="daimoku">（4）zu（として）型多し</div>
<div class="mpage">188</div>
<div class="bango"> </div>
<div class="daimoku">（5）「を…と」と不定法</div>
<div class="mpage">245</div>
<div class="bango">35-4B</div>
<div class="daimoku">編者注：本袋「35-4B」内は資料数<br />が多いので、資料番号、（1）,（2）<br />…に対応した目次を付けてある。</div>
<div class="mpage">268-361</div>
<div class="bango"> </div>
<div class="daimoku">変態的述語</div>
<div class="mpage"> </div>
<div class="bango"> </div>
<div class="daimoku">（1）Ihr wart sonst <u>eine</u> <u>freie Stadt</u> ?</div>
<div class="mpage">269</div>
<div class="bango"> </div>
<div class="daimoku">（2）A ist B （bedeutet）（hat zur Folge）</div>
<div class="mpage">275</div>
<div class="bango"> </div>
<div class="daimoku">（3）Die Zeit ist <u>um</u>.</div>
<div class="mpage">283</div>
<div class="bango"> </div>
<div class="daimoku">（4）Und Berlin war schon eine <u>Bescheidung</u>.</div>
<div class="mpage">288</div>
<div class="bango"> </div>
<div class="daimoku">（5）…ist eine Unmöglichkeit=unmöglich</div>
<div class="mpage">304</div>
<div class="bango"> </div>
<div class="daimoku">（6）Ihr erster Gang <u>war</u> nach dem Bach.</div>
<div class="mpage">313</div>
<div class="bango"> </div>
<div class="daimoku">（7）変態的述語とKopula</div>
<div class="mpage">318</div>
<div class="bango"> </div>
<div class="daimoku">（8）Hin ist hin.</div>
<div class="mpage">325</div>
<div class="bango"> </div>
<div class="daimoku">（9）Paradoxiae causa <u>何々そのものである</u></div>
<div class="mpage">326</div>
<div class="bango"> </div>
<div class="daimoku">（10）He was the <u>color</u> of cheese</div>
<div class="mpage">343</div>
<div class="bango"> </div>
<div class="daimoku">（11）Verweisungen:</div>
<div class="mpage">350</div>
<div class="bango"> </div>
<div class="daimoku">（12）....war <u>freier Wille</u>.<br />=....war Folge eines freien Willens.</div>
<div class="mpage">350</div>
<div class="bango"> </div>
<div class="daimoku">（13）C'est ce ～ 「…の件がある」</div>
<div class="mpage">351</div>
<div class="bango"> </div>
<div class="daimoku">（14）花は桜木人は武士</div>
<div class="mpage">351</div>
<div class="bango"> </div>
<div class="daimoku">（15）Glück = glückssache 或はGegenstand....?</div>
<div class="mpage">352</div>
<div class="bango"> </div>
<div class="daimoku">（16）Kapazität</div>
<div class="mpage">352</div>
<div class="bango"> </div>
<div class="daimoku">（17）［仏］Quel jour sommes-nous aujourd'hui?</div>
<div class="mpage">353</div>
<div class="bango"> </div>
<div class="daimoku">（18）Er ist <u>ein grosser Geist</u> → 人のMetonymie</div>
<div class="mpage">353</div>
<div class="bango"> </div>
<div class="daimoku">（19）The child is three （sc.years old）</div>
<div class="mpage">354</div>
<div class="bango"> </div>
<div class="daimoku">（20）palam est</div>
<div class="mpage">354</div>
<div class="bango"> </div>
<div class="daimoku">（21）Erfindung等</div>
<div class="mpage">355</div>
<div class="bango"> </div>
<div class="daimoku">（22）Paradoxiae causa</div>
<div class="mpage">355</div>
<div class="bango"> </div>
<div class="daimoku">（23）基礎項の一つ（わかり易いもの）</div>
<div class="mpage">356</div>
<div class="bango"> </div>
<div class="daimoku">（24）雑</div>
<div class="mpage">356</div>
<div class="bango"> </div>
<div class="daimoku">（25）The pressure <u>was</u> on Germeny.</div>
<div class="mpage">357</div>
<div class="bango"> </div>
<div class="daimoku">（26）Es war zur Zeit der …云々<br />（daßの文の省略）</div>
<div class="mpage">361</div>
<div class="bango">35-5B</div>
<div class="daimoku">述語</div>
<div class="mpage">362-546</div>
<div class="bango"> </div>
<div class="daimoku">［01］___を受ける追加的名詞述語。 不定冠詞</div>
<div class="mpage">368</div>
<div class="bango"> </div>
<div class="daimoku">［02］述語の状況的用法。（形容詞の副詞的位置）</div>
<div class="mpage">387</div>
<div class="bango"> </div>
<div class="daimoku">［03］過去分詞四格述語がhabenを伴ふ場合（wollen）</div>
<div class="mpage">396</div>
<div class="bango"> </div>
<div class="daimoku">［04］名詞述語に用ふる筈のalsを形容詞にも冠せる。</div>
<div class="mpage">399</div>
<div class="bango"> </div>
<div class="daimoku">［05］fürを用ひる場合。</div>
<div class="mpage">400</div>
<div class="bango"> </div>
<div class="daimoku">［06］was für ein.</div>
<div class="mpage">401</div>
<div class="bango"> </div>
<div class="daimoku">［07］a1sと名詞。</div>
<div class="mpage">318</div>
<div class="bango"> </div>
<div class="daimoku">［08］述語（名詞、形容詞）のみの主文章</div>
<div class="mpage">402</div>
<div class="bango"> </div>
<div class="daimoku">［09］文中の四格を宣言する述語的形容詞</div>
<div class="mpage">413</div>
<div class="bango"> </div>
<div class="daimoku">［10］<u>K0PULA</u>とは何ぞや。</div>
<div class="mpage">435</div>
<div class="bango"> </div>
<div class="daimoku">［11］ich habe es <u>heraus</u>.</div>
<div class="mpage">435</div>
<div class="bango"> </div>
<div class="daimoku">［12］<u>was</u>が述語になる事。</div>
<div class="mpage">437</div>
<div class="bango"> </div>
<div class="daimoku">［13］述語文の代りにbedeuten, vorstellen, abgeben</div>
<div class="mpage">438</div>
<div class="bango"> </div>
<div class="daimoku">［14］bleibenの用法</div>
<div class="mpage">454</div>
<div class="bango"> </div>
<div class="daimoku">［15］…であった所の彼は、等。</div>
<div class="mpage">455</div>
<div class="bango"> </div>
<div class="daimoku">［16］das,was....の述語</div>
<div class="mpage">457</div>
<div class="bango"> </div>
<div class="daimoku">［17］関係代名詞<u>der</u>, <u>was</u>の述語。</div>
<div class="mpage">458</div>
<div class="bango"> </div>
<div class="daimoku">［18］<u>als</u>の省略。（Freies Prädikat）</div>
<div class="mpage">465</div>
<div class="bango"> </div>
<div class="daimoku">［19］welchesの述語（疑問詞）<u>was</u></div>
<div class="mpage">466</div>
<div class="bango"> </div>
<div class="daimoku">［20］welchesの述語（関係代名詞）</div>
<div class="mpage">467</div>
<div class="bango"> </div>
<div class="daimoku">［21］述語</div>
<div class="mpage">467</div>
<div class="bango"> </div>
<div class="daimoku">［22］es <u>so</u> haben ［od.wissen］wollen</div>
<div class="mpage">468</div>
<div class="bango"> </div>
<div class="daimoku">［23］主語、述語関係に非ずして、存在のseinによって<br />つながれる筈の主語と副詞規定をglauben、<br />vermuten等で一文にする。</div>
<div class="mpage">482</div>
<div class="bango"> </div>
<div class="daimoku">［24］完了形と区別しがたき場合。</div>
<div class="mpage">492</div>
<div class="bango"> </div>
<div class="daimoku">［25］Nennsatzの諸形態。（使用の動詞）</div>
<div class="mpage">493</div>
<div class="bango"> </div>
<div class="daimoku">［26］「wie + 代名詞」の述語的関係代名詞。</div>
<div class="mpage">494</div>
<div class="bango"> </div>
<div class="daimoku">［27］etwas für etwas nehmen.<br />halten.<br />ausgeben.</div>
<div class="mpage">496</div>
<div class="bango"> </div>
<div class="daimoku">［28］形容詞述語の先置</div>
<div class="mpage">531</div>
<div class="bango"> </div>
<div class="daimoku">［29］<u>Repetitio</u>.</div>
<div class="mpage">532</div>
<div class="bango"> </div>
<div class="daimoku">［30］附加詞的述語</div>
<div class="mpage">534</div>
<div class="bango"> </div>
<div class="daimoku">［31］werden等と四格。（lassen） <u>sich</u></div>
<div class="mpage">536</div>
<div class="bango"> </div>
<div class="daimoku">［32］「と」四格述語支配（命令文） 一格の異例。</div>
<div class="mpage">539</div>
<div class="bango"> </div>
<div class="daimoku">［33］einem sich dünken, sich vork0mmen, scheinen</div>
<div class="mpage">541</div>
</div>