<div id="container">
<div class="bango">袋番号</div>
<div class="daimoku">タイトル</div>
<div class="mpage">ページ</div>
<div class="bango">37-1B</div>
<div class="daimoku">自働と他働</div>
<div class="mpage">1-28</div>
<div class="bango"> </div>
<div class="daimoku">［01］自働i他働e, ä （三要形、規）</div>
<div class="mpage">2</div>
<div class="bango"> </div>
<div class="daimoku">［02］自働詞の他働詞化。（その侭移る際）</div>
<div class="mpage">18</div>
<div class="bango"> </div>
<div class="daimoku">［03］自働詞の他働詞化。（前綴りを附して）</div>
<div class="mpage">19</div>
<div class="bango"> </div>
<div class="daimoku">［04］日本語では他働詞と思われるものが自働詞で、<br />前置詞を支配する例</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">［05］zeigen.→ （a）etwas zeigen<br />（b）auf etwas zeigen</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">［06］<u>Belesen</u>heit（能動の意の変態現象）<br />Die große <u>Belesenheit</u>,</div>
<div class="mpage">21</div>
<div class="bango"> </div>
<div class="daimoku">［07］vonの用ひ方。（受働へ行くべきもの）</div>
<div class="mpage">22</div>
<div class="bango"> </div>
<div class="daimoku">［08］=ernで他働に。［Kausativa］</div>
<div class="mpage">25</div>
<div class="bango"> </div>
<div class="daimoku">［09］再帰動詞（他働詞）の自働詞化<br /><u>drängen</u> = sich drängen.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">［10］hangenとhängen.</div>
<div class="mpage">26</div>
<div class="bango"> </div>
<div class="daimoku">［11］～ igen （-lichen）</div>
<div class="mpage">27</div>
<div class="bango"> </div>
<div class="daimoku">［12］受働の代りと言っても好いような自働詞。<br />［Du fliegst hinaus式］</div>
<div class="mpage">28</div>
<div class="bango"> </div>
<div class="daimoku">［13］<u>dringen</u>の他働化 <u>aufdringen</u>.</div>
<div class="mpage">28</div>
<div class="bango">37-12B</div>
<div class="daimoku">他働詞の絶対化</div>
<div class="mpage">29-75</div>
<div class="bango"> </div>
<div class="daimoku">［01］結成したものと、その時々に造るもの。</div>
<div class="mpage">34</div>
<div class="bango"> </div>
<div class="daimoku">［02］<u>Etymologisches</u>.</div>
<div class="mpage">54</div>
<div class="bango"> </div>
<div class="daimoku">［03］再帰動詞と殆ど等しくなるものは分ける。<br />（sichの省略）</div>
<div class="mpage">65</div>
<div class="bango"> </div>
<div class="daimoku">［04］全然自働詞化して、たとえばsein支配となりたる<br />もの。（jagen, sprengen, abnehmen,zunehmen<br />, absetzen, einsetzen, hiniegen）halten,</div>
<div class="mpage">74</div>
<div class="bango"> </div>
<div class="daimoku">［05］［外国語］</div>
<div class="mpage">75</div>
<div class="bango">37-3R</div>
<div class="daimoku">［西班牙語］人的対象はすべてaを介す<br />jemanden verstehen, jemandes Worte, Gedanken,<br />Werke. Thomas Mann lesen.<br />自・他・両方のもの kleben, heilen, stecken,<br />編者注：このほか6件あり。</div>
<div class="mpage">76-82</div>
<div class="bango">37-4B</div>
<div class="daimoku">自働詞の他働詞化</div>
<div class="mpage">83</div>
<div class="bango">37-5B</div>
<div class="daimoku">［Faktitiv Kausativ］ 参項</div>
<div class="mpage">84</div>
<div class="bango">37-6R</div>
<div class="daimoku">stehenと四格補足語</div>
<div class="mpage">85-87</div>
<div class="bango"> </div>
<div class="daimoku">體勤作の前置詞支配（自働詞的考方）<br /><u>in</u> Er <u>klatscht in</u> die Hände.<br />［英］句の他働詞化 <u>to find fault with</u>.<br />lernen= lehren einlernen. anlernen,</div>
<div class="mpage"> </div>
<div class="bango">37-7B</div>
<div class="daimoku">自働詞形態の三式に就て</div>
<div class="mpage">88-89</div>
<div class="bango">37-8R</div>
<div class="daimoku">受働の本体を主語にして、自働詞を以て表現する<br />もの。<br />自動の定義：（四格を取ることありや？）<br />自他働 雑<br />zur Verfügung stehen.<br />zur Verfügung stellen.</div>
<div class="mpage">90-91</div>
</div>